import './english-reader.css';
import React,{useState} from 'react';

const readerChapters=[
'I’m going to dance again','Scaling Great Heights','Saint Kabir','The eyes are not here',
'Ismat Chughtai: A woman with a difference','The accidental tourist','Saint Ravidas','Bharathipura'
];
const panoramaProse=['Dharam Juddha','Yayati','A Silent Revolution','Too Many People, Too Few Trees','Echo and Narcissus','The Shehnai of Bismillah Khan','Kathmandu','My Childhood','The Gift of the Magi'];
const panoramaPoetry=['The Grandmother','On His Blindness','Blow, Blow, Thou Winter Wind','To Daffodils','Sound','Self Introduction','I Am Like Grass','Abraham Lincoln’s Letter to His Son’s Teacher'];
const panoramaRte=['The Secret of Work','Gandhiji’s Passion for Nursing','With the Photographer'];

export function EnglishSubjectSection({open}){
 const [book,setBook]=useState(null);
 if(!book) return <div className="english-book-shell"><div className="english-book-hero"><span className="badge">CLASS 9 • ENGLISH</span><h2>Choose your English book</h2><p>Select one textbook stream to open its chapters and learning sections.</p></div><div className="english-book-grid"><button className="english-book-card" onClick={()=>setBook('panorama')}><span>📘</span><strong>The Panorama</strong><small>Prose • Poetry • Read, Think &amp; Enjoy</small><b>Open Panorama →</b></button><button className="english-book-card" onClick={()=>setBook('reader')}><span>📗</span><strong>English Reader</strong><small>Panorama English Reader • 8 chapters</small><b>Open English Reader →</b></button></div></div>;
 return <div className="english-book-shell"><button className="english-book-back" onClick={()=>setBook(null)}>← Back to English books</button><div className="english-book-hero"><span className="badge">CLASS 9 • {book==='reader'?'ENGLISH READER':'THE PANORAMA'}</span><h2>{book==='reader'?'English Reader':'The Panorama'}</h2><p>{book==='reader'?'8 chapter reader stream':'Prose, Poetry and Read, Think &amp; Enjoy sections'}</p></div><div className="english-book-tabs">{book==='panorama'&&<><button className="english-book-tab" onClick={()=>document.getElementById('panorama-prose')?.scrollIntoView({behavior:'smooth'})}>Prose</button><button className="english-book-tab" onClick={()=>document.getElementById('panorama-poetry')?.scrollIntoView({behavior:'smooth'})}>Poetry</button><button className="english-book-tab" onClick={()=>document.getElementById('panorama-rte')?.scrollIntoView({behavior:'smooth'})}>Read, Think &amp; Enjoy</button></>}</div><div className="english-book-list">{book==='reader'&&<Section id="reader" title="English Reader" items={readerChapters} offset={0} open={open} prefix="Reader •"/>}{book==='panorama'&&<><Section id="panorama-prose" title="Prose" items={panoramaProse} offset={0} open={open} prefix="Panorama • Prose"/><Section id="panorama-poetry" title="Poetry" items={panoramaPoetry} offset={9} open={open} prefix="Panorama • Poetry"/><Section id="panorama-rte" title="Read, Think & Enjoy" items={panoramaRte} offset={0} open={open} prefix="Panorama • Read, Think & Enjoy"/></>}</div></div>
}
function Section({id,title,items,offset,open,prefix}){return <section id={id} className="english-book-section"><div className="english-section-head"><h3>{title}</h3><span>{items.length} chapters</span></div><div className="english-book-chapters">{items.map((name,i)=>{const n=offset+i+1;const chapter=`${prefix} ${n} ${name}`;return <button className="english-book-chapter" key={chapter} onClick={()=>open(chapter)}><span>{String(n).padStart(2,'0')}</span><div><strong>{name}</strong><small>{prefix}</small></div><b>Learn →</b></button>})}</div></section>}
