import React,{useMemo,useState}from'react';
import './EnglishWritingAssessment.css';

const BANKS={
practice:[
['What is the main purpose of speech writing?',['to present organised ideas to an audience','to write a private diary','to list random facts','to write only a story'],0,'A speech is organised for delivery to an audience.'],
['Which is a suitable opening?',['Respected Principal, teachers and my dear friends,','Once upon a time...','Dear customer, please pay the bill.','Hey bro, what is up?'],0,'A school speech needs a respectful audience-appropriate greeting.'],
['What should the introduction mainly do?',['introduce the topic and its importance','give every detail at once','start with unrelated jokes','repeat the conclusion'],0,'The introduction sets up the topic and purpose.'],
['A strong speech body usually contains…',['a few clear points with support','random one-line ideas','only the greeting','only the ending'],0,'Focused points make a speech coherent and persuasive.'],
['Which phrase shows audience connection?',['Let us work together.','My favourite colour is blue.','The bus arrived.','He closed the book.'],0,'Let us creates a shared call for action.'],
['Which language is best for a school speech?',['clear, confident and audience-friendly','extremely confusing','only slang','mostly unexplained abbreviations'],0,'Speech language should be easy to understand when heard.'],
['What often strengthens a conclusion?',['a clear message or call to action','a new unrelated topic','a random list','another greeting'],0,'A conclusion should reinforce the message and can ask the audience to act.'],
['Which is a good final check?',['greeting, topic, points, audience connection and closing','only difficult vocabulary','only word count','only punctuation'],0,'A complete audit checks the major structural features.']
],
challenge:[
['A speech starts with “I was just thinking about many things today.” What is the main weakness?',['the topic and purpose are unclear','the greeting is too respectful','there are too many facts','the conclusion is too strong'],0,'The audience should understand the topic early.'],
['Which introduction is strongest for a speech on saving water?',['Today I am here to speak about saving water and why every student can help.','Water is a thing. I do not know what to say.','My favourite subject is English.','Let me tell you about yesterday.'],0,'It clearly introduces the topic and the audience’s possible role.'],
['Which body plan is best?',['problem → reasons → practical solutions → action','greeting → random story → joke → goodbye','conclusion → new topic → greeting','only repeated slogans'],0,'The first plan develops the topic logically toward action.'],
['Which sentence is most audience-focused?',['We can reduce waste by using reusable bottles.','I think bottles are interesting.','My cousin bought a bottle yesterday.','There was a bottle on the table.'],0,'We makes the advice relevant to the audience.'],
['Which connector best introduces a result?',['Therefore','Although','Meanwhile','First'],0,'Therefore commonly signals a result or conclusion from previous points.'],
['A speech uses long, difficult sentences that are hard to say aloud. What should be improved first?',['make the language clearer and more speakable','add more difficult words','remove the topic','delete the conclusion'],0,'A speech should be clear when heard, not only when read.'],
['Which ending is strongest for an environmental speech?',['Let us protect our trees today and make care for nature a daily habit. Thank you.','Anyway, my exam is next week.','I have nothing else to say about another topic.','Trees are trees.'],0,'It reinforces the message and gives a clear action.'],
['Why should a speech avoid too many unrelated points?',['the audience needs a focused, memorable message','unrelated points always improve marks','speeches should never contain examples','more topics automatically mean better quality'],0,'Focus helps the audience follow and remember the central message.']
],
test:[
['Which best describes a speech?',['structured writing prepared for delivery to an audience','a personal diary entry','a shopping list','a fictional chapter only'],0,'A speech is written to communicate a message to listeners.'],
['Which is the most appropriate greeting for a school speech?',['Respected Principal, teachers and my dear friends,','Dear customer,','Hey guys!!!','To whom it may concern,'],0,'The first greeting suits a formal school audience.'],
['The introduction should primarily…',['set the topic and explain its significance','present every supporting detail','give only the thanks','introduce an unrelated issue'],0,'The introduction prepares the audience for the main subject.'],
['Which body structure is strongest?',['point → reason/example → next point → solution','random points with no links','conclusion before introduction','greeting repeated after every line'],0,'Ideas should develop in a logical sequence.'],
['Which sentence best connects with the audience?',['Together, we can make our school cleaner.','I cleaned my room yesterday.','My neighbour has a garden.','The classroom has four windows.'],0,'Together and we create a shared audience connection.'],
['Which sentence is most suitable for spoken delivery?',['Every student can save water by turning off taps properly.','Utilisation of hydrological conservation methodologies is hereby mandated.','The thing is the thing and the thing happened.','Water, water, water, water, water.'],0,'The first is clear, natural and easy to say aloud.'],
['What is a suitable closing?',['Let us act today for a healthier future. Thank you.','Now I will begin a new unrelated story.','That is all about my favourite movie.','Hello, everyone.'],0,'A closing should reinforce the message and end the speech clearly.'],
['Which audit is most complete?',['greeting, topic, main points, audience connection, action and thanks','only spelling','only word count','only the title'],0,'A final audit should cover the full speech structure and ending.'],
['Which sentence is most persuasive?',['We can protect our school by reducing waste every day.','Waste is a thing.','There is waste.','Maybe something should happen.'],0,'The first sentence gives a clear, practical and audience-focused call.'],
['What should you do before submitting?',['read the speech aloud and check clarity, structure and tone','add as many difficult words as possible','remove the conclusion','make every sentence very long'],0,'Reading aloud helps confirm delivery-friendly language and logical structure.']
]};

const shuffle=(items,seed)=>{const a=[...items];let x=seed||1;for(let i=a.length-1;i>0;i--){x=(x*9301+49297)%233280;const j=Math.floor((x/233280)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};

export default function EnglishSpeechWritingAssessment({mode='practice',onBack,addXp,finishSession}){const bank=BANKS[mode]||BANKS.practice;const questions=useMemo(()=>shuffle(bank.map((q,i)=>({q:q[0],options:q[1],answer:q[2],why:q[3],id:i})),Math.floor(Date.now()/86400000)+mode.length),[bank,mode]);const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const[elapsed,setElapsed]=useState(0);const[retry,setRetry]=useState(0);React.useEffect(()=>{if(submitted)return;const t=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(t)},[submitted,retry]);const score=questions.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0);const submit=()=>{if(submitted)return;setSubmitted(true);if(addXp)addXp(score*3);if(finishSession)finishSession({type:'english-speech-writing',mode,score,total:questions.length,percent:Math.round(score/questions.length*100),seconds:elapsed,at:Date.now()})};const retryTest=()=>{setAnswers({});setSubmitted(false);setElapsed(0);setRetry(v=>v+1)};const title=mode==='challenge'?'Speech Writing — Challenge':mode==='test'?'Speech Writing — Final Test':'Speech Writing — Practice';return <main className="ew-assessment"><button className="ew-back" onClick={onBack}>← Back to Speech Writing</button><header className="ew-head"><div><p className="ew-kicker">ENGLISH • LANGUAGE & SKILLS</p><h1>{title}</h1><p>Choose one answer for every question, then submit to see marks, percentage and explanations.</p></div><div className="ew-timer">{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</div></header><section className="ew-progress"><strong>{questions.length} Questions</strong><span>{Object.keys(answers).length}/{questions.length} answered</span></section><div className="ew-list">{questions.map((q,i)=><article className="ew-card" key={q.id}><div className="ew-qtop"><span>Q{i+1}</span>{submitted&&<strong className={answers[q.id]===q.answer?'ew-ok':'ew-bad'}>{answers[q.id]===q.answer?'Correct':'Review'}</strong>}</div><h2>{q.q}</h2><div className="ew-options">{q.options.map((opt,j)=><button key={opt} disabled={submitted} className={answers[q.id]===j?'selected':''} onClick={()=>setAnswers(a=>({...a,[q.id]:j}))}><span>{String.fromCharCode(65+j)}</span>{opt}</button>)}</div>{submitted&&<div className="ew-explain"><b>Answer:</b> {q.options[q.answer]}<br/><b>Why:</b> {q.why}</div>}</article>)}</div><div className="ew-submit"><div>{submitted?<><strong>Score: {score}/{questions.length}</strong><span> • {Math.round(score/questions.length*100)}%</span></>:<span>Review all answers before submitting.</span>}</div>{submitted?<button onClick={retryTest}>Retry {mode==='test'?'Test':mode}</button>:<button onClick={submit}>Submit {mode==='test'?'Final Test':mode}</button>}</div></main>}
