import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
  title:'Echo and Narcissus',
  author:'Moira Kerr and John Bennett',
  sourceNote:'Class 9 English • The Panorama • Prose Chapter 5',
  intro:'This lesson retells a Greek myth about Echo and Narcissus. The story explores beauty, self-love, rejection, punishment and the consequences of being unable to look beyond oneself.',
  authorNote:'The textbook presents this version as a rendering of a Greek myth by Moira Kerr and John Bennett. The lesson introduces Echo and Narcissus and the meaning carried by their names.',
  sections:[
    {title:'Part 1 — Narcissus is exceptionally handsome',flow:'Narcissus is introduced as an unusually handsome young man. His beauty is so striking that almost everyone who sees him falls in love with him. He is also shown as a hunter who spends time in the woods with his companions.',explanation:'नार्सिसस को एक असाधारण रूप से सुंदर युवक के रूप में प्रस्तुत किया गया है। उसकी सुंदरता देखकर लगभग हर व्यक्ति उस पर मोहित हो जाता है। वह अपने साथियों के साथ जंगल में शिकार करने जाता है।',vocabulary:[['handsome','सुंदर'],['hunter','शिकारी'],['companion','साथी'],['roam','इधर-उधर घूमना'],['gaze','एकटक देखना']],exam:'Remember the two opening facts: Narcissus is exceptionally handsome and spends time hunting with companions.',think:'How can unusual physical beauty affect the way other people treat someone?'},
    {title:'Part 2 — Echo and her punishment',flow:'Echo is a nymph who had once been a great chatterer. She had amused or spoken to passers-by and had offended the goddess Hera by helping to distract her from Zeus. Hera therefore placed a curse on Echo so that she could say only the last words she heard.',explanation:'इको एक अप्सरा थी जो बहुत बातूनी थी। वह राह चलते लोगों से बात करती थी और अपने व्यवहार से देवी हेरा को नाराज़ कर बैठी। हेरा ने उसे ऐसा शाप दिया कि वह केवल वही अंतिम शब्द बोल सके जो उसने सुने हों।',vocabulary:[['nymph','पौराणिक कथा की स्त्री आत्मा / अप्सरा'],['chatterer','बहुत बात करने वाला'],['passer-by','राहगीर'],['curse','शाप'],['detain','रोककर रखना']],exam:'Know why Hera cursed Echo and what the curse allowed her to say.',think:'Why would a punishment that limits speech be especially difficult for a chatterer?'},
    {title:'Part 3 — Echo follows Narcissus',flow:'Echo becomes interested in Narcissus and follows him through the trees. She wants to come closer and admire him, but she is afraid that he will laugh at the strange way she speaks. When Narcissus loses his companions and calls out, Echo answers with the last words she has heard.',explanation:'इको नार्सिसस में रुचि लेने लगती है और पेड़ों के बीच उसके पीछे चलती है। वह उसके पास जाकर उसे निहारना चाहती है, लेकिन उसे डर है कि नार्सिसस उसके बोलने के ढंग पर हँसेगा। जब नार्सिसस अपने साथियों से अलग होकर पुकारता है, तो इको सुने हुए अंतिम शब्द दोहराती है।',vocabulary:[['follow','पीछे चलना'],['timid','संकोची'],['trembling','काँपता हुआ'],['mystify','उलझन में डालना'],['stumbling upon','अचानक मिल जाना']],exam:'The sound of Echo’s reply is the reason Narcissus becomes confused about who is speaking.',think:'How does the curse shape the first conversation between Echo and Narcissus?'},
    {title:'Part 4 — The meeting ends in rejection',flow:'Echo and Narcissus eventually meet. Echo tries to express that she would have spoken first if her curse had not prevented it. Narcissus, however, thinks someone is playing a trick on him. Echo is mocked and rejected, and she retreats because she feels ashamed and helpless.',explanation:'इको और नार्सिसस अंततः आमने-सामने आते हैं। इको अपनी बात कहना चाहती है, लेकिन शाप के कारण केवल दूसरे के शब्द दोहरा सकती है। नार्सिसस इसे मज़ाक या चाल समझता है। इको को उपेक्षा और अपमान मिलता है तथा वह शर्म से पीछे हट जाती है।',vocabulary:[['ashamed','शर्मिंदा'],['embarrassed','लज्जित / असहज'],['mock','उपहास करना'],['helpless','असहाय'],['shyness','संकोच / लज्जा']],exam:'Be able to explain why Echo cannot speak freely and why Narcissus misunderstands her.',think:'How might the outcome have changed if Narcissus had tried to understand Echo?'},
    {title:'Part 5 — Echo’s beauty withers away',flow:'After the painful rejection, Echo hides in a dark cave and avoids the open air and sunlight. Her youth and beauty fade, her body becomes weak and shrunken, and eventually she vanishes. Only her voice remains, repeating the words that others say.',explanation:'अपमान के बाद इको एक अंधेरी गुफा में छिप जाती है और बाहर की हवा तथा धूप से दूर रहती है। उसकी जवानी और सुंदरता मुरझा जाती है, शरीर कमजोर होकर सिकुड़ जाता है और अंततः वह पूरी तरह गायब हो जाती है। केवल उसकी आवाज़ रह जाती है, जो दूसरों के शब्द दोहराती है।',vocabulary:[['wither','मुरझा जाना'],['shrunken','सिकुड़ा हुआ'],['vanish','गायब हो जाना'],['pathetic','दयनीय'],['murmuring','धीमी आवाज़ में बोलना']],exam:'The story shows the lasting consequence of Echo’s shame and rejection: her body fades while her voice remains.',think:'What does Echo’s fading body and surviving voice suggest about memory and speech?'},
    {title:'Part 6 — A prayer against Narcissus',flow:'Echo is not the only person Narcissus has treated cruelly. Others who have been scorned pray to the gods that Narcissus will one day experience the same pain. The prayer is granted, creating the turning point of the myth.',explanation:'नार्सिसस ने इको के अतिरिक्त अन्य लोगों के साथ भी कठोर व्यवहार किया था। जिन लोगों को उसने ठुकराया, वे देवताओं से प्रार्थना करते हैं कि एक दिन नार्सिसस को भी वही पीड़ा मिले। उनकी प्रार्थना स्वीकार हो जाती है और कथा में निर्णायक मोड़ आता है।',vocabulary:[['brutally','क्रूरता से'],['scorned','तिरस्कृत'],['prayer','प्रार्थना'],['grant','स्वीकृत करना / प्रदान करना'],['turning point','निर्णायक मोड़']],exam:'Know who prayed against Narcissus, what they wanted, and that the prayer was granted.',think:'Why does the myth connect Narcissus’s treatment of others with his later fate?'},
    {title:'Part 7 — Narcissus sees his own reflection',flow:'Tired and thirsty after hunting, Narcissus comes to a still, clear pool to drink. When he bends over the shining surface, he sees the reflection of a very beautiful face. He does not realise that the face is his own image.',explanation:'शिकार के बाद थका और प्यासा नार्सिसस एक शांत और स्वच्छ जलाशय के पास पानी पीने जाता है। चमकती सतह में उसे एक अत्यंत सुंदर चेहरा दिखाई देता है। उसे पता नहीं चलता कि वह उसी का अपना प्रतिबिंब है।',vocabulary:[['thirsty','प्यासा'],['still','शांत / स्थिर'],['reflection','प्रतिबिंब'],['shining','चमकता हुआ'],['image','प्रतिमा / प्रतिबिंब']],exam:'The pool and the reflection create the condition for Narcissus to fall in love with his own image.',think:'Why does Narcissus fail to recognise the reflection as his own?'},
    {title:'Part 8 — He cannot tear himself away',flow:'Narcissus becomes completely absorbed in the beautiful image. He remains beside the pool and cannot tear himself away from what he sees. The story presents this self-absorption as the fulfilment of the earlier prayer against him.',explanation:'नार्सिसस उस सुंदर छवि में पूरी तरह डूब जाता है। वह जलाशय के पास बैठा रहता है और अपने प्रतिबिंब से स्वयं को अलग नहीं कर पाता। कथा में यही उसकी उस प्रार्थना का परिणाम है जिसमें उसके साथ भी वही किए जाने की कामना की गई थी जो उसने दूसरों के साथ किया था।',vocabulary:[['absorbed','पूरी तरह तल्लीन'],['tear oneself away','किसी चीज़ से स्वयं को अलग करना'],['self-love','अपने प्रति अत्यधिक प्रेम'],['fulfilled','पूरा होना'],['fate','भाग्य / नियति']],exam:'Use the phrase tear oneself away for the idea that Narcissus cannot leave the reflection.',think:'What is the difference between healthy self-respect and the extreme self-absorption shown here?'},
    {title:'Part 9 — The flower called Narcissus',flow:'Narcissus remains beside the pool for a long time and eventually withers away. Where his body had been, a flower grows. Its golden and white blossom looks into quiet pools, and the flower is called Narcissus.',explanation:'नार्सिसस लंबे समय तक जलाशय के किनारे रहता है और अंततः मुरझा जाता है। जहाँ उसका शरीर था, वहाँ एक फूल उगता है। उसके सुनहरे और सफेद फूल की आकृति शांत जलाशयों की ओर झुकी रहती है और उसे Narcissus कहा जाता है।',vocabulary:[['blossom','फूल / पुष्प'],['wither away','धीरे-धीरे मुरझाना'],['quiet pool','शांत जलाशय'],['golden','सुनहरा'],['faded','मुरझाया / फीका पड़ा']],exam:'The ending explains how Narcissus becomes a flower and why the flower is associated with looking into pools.',think:'Why is the transformation into a flower an effective ending for the myth?'},
  ],
  glossary:[['roam','to wander around — इधर-उधर घूमना'],['nymph','a female spirit of mythology — पौराणिक अप्सरा'],['passer-by','a person passing by — राहगीर'],['detain','to stop or hold back — रोकना'],['stumbling upon','discovering unexpectedly — अचानक मिल जाना'],['mystify','to confuse — उलझन में डालना'],['annoyed','slightly angry — नाराज़'],['curse','a spoken wish for punishment — शाप'],['trembling','shaking with fear or excitement — काँपता हुआ'],['gaze','to look steadily — एकटक देखना'],['embarrassed','feeling awkward or ashamed — लज्जित / असहज'],['wither','to become weak or dry and fade — मुरझाना'],['shrunken','made smaller or less full — सिकुड़ा हुआ'],['altogether','completely / in total — पूरी तरह'],['pathetic','pitiful or sad — दयनीय'],['anxious','worried or eager — चिंतित / उत्सुक'],['brutally','in a violent or cruel way — क्रूरता से'],['scorned','treated as unworthy or rejected — तिरस्कृत'],['image','a reflection or likeness — प्रतिबिंब / छवि'],['murmuring','speaking in a low voice — धीमी आवाज़ में बोलना']],
  wordStudy:{
    spellings:[['handosum','handsome'],['anoyed','annoyed'],['watchfull','watchful'],['embarrassed','embarrassed'],['liclit','illicit'],['blosom','blossom']],
    ness:[['shy','shyness'],['kind','kindness'],['dark','darkness'],['weak','weakness'],['polite','politeness'],['happy','happiness'],['sad','sadness'],['ill','illness'],['aware','awareness'],['careful','carefulness']],
    less:[['help','helpless'],['hope','hopeless'],['care','careless'],['use','useless'],['harm','harmless'],['fear','fearless'],['home','homeless'],['power','powerless'],['end','endless'],['worth','worthless']],
    adverbs:[['skillful','skillfully'],['brave','bravely'],['beautiful','beautifully'],['bitter','bitterly'],['final','finally'],['slow','slowly'],['smart','smartly'],['careless','carelessly'],['heartily','heartily'],['wise','wisely'],['intelligent','intelligently'],['strong','strongly'],['clear','clearly'],['foolish','foolishly'],['rough','roughly']],
    match:[['spirit in the form of a woman','nymph'],['make somebody confused','mystify'],['felt awkward','embarrassed'],['refuse something in pride','scorn'],['violently and cruelly','brutally'],['pitiful','pathetic'],['wanting something very much','anxious']],
    phrases:[['follow through','continue something until it is completed'],['wither away','become weak and disappear gradually'],['tear oneself away','force oneself to leave'],['before long','soon'],['play trick on','deceive or mislead'],['at last','finally']]
  },
  grammar:{title:'Gerund and Participle',intro:'The chapter distinguishes a Gerund, which works as a noun, from a Participle, which works as a verb form or adjective. It also introduces Present, Past and Perfect Participles.',rules:[
    ['Gerund — noun form ending in -ing','A gerund is formed by adding -ing to the first form of a verb and functions as a noun.','Swimming is a good exercise. • I like painting.'],
    ['Gerund as subject','An -ing form can act as the subject of a sentence.','Walking is good for health.'],
    ['Gerund as object','A gerund can follow certain verbs and work as their object.','She hates smoking. • I know how to swim.'],
    ['Gerund after a preposition','A gerund can follow a preposition.','He stopped me from smoking.'],
    ['Present Participle','The present participle is the -ing form used to qualify a noun or to show an action in progress.','Barking dogs seldom bite. • Seeing the reflection, he stopped.'],
    ['Past Participle','The past participle is commonly used as an adjective and may show a completed state or action.','A tired man needs rest. • The room looked locked.'],
    ['Perfect Participle','Having + past participle shows that one action was completed before another action.','Having taken his meal, he went to school.'],
    ['Three-way distinction','Present participle usually points to an unfinished or continuing action; past participle to a finished state/action; perfect participle to an earlier completed action before another.','Running horse • written statement • Having finished the work, he left.']
  ]},
  composition:['Write a paragraph of about 80 words on “Beauty is only skin-deep”.'],
  activities:['Collect two fairy tales.','Retell the story Echo and Narcissus in your own words after reading it carefully.'],
  translationPractice:[
    ['मैं उसे पार्क में बैठा हुआ देखा।','I saw him sitting in the park.'],
    ['मैं उसे तैरते हुए पाया।','I found him swimming.'],
    ['उसने मुझे साथ चलने को कहा।','He asked me to come along.'],
    ['पुलिस ने चोर को भागते हुए देखा।','The police saw the thief running away.'],
    ['एक लड़का चलती हुई गाड़ी से कूद पड़ा।','A boy jumped from a moving vehicle.'],
    ['मैंने कहीं एक प्यासे आदमी को देखा।','I saw a thirsty man somewhere.'],
    ['इस कमरे में वे टूटी हुई कुर्सियाँ थीं।','There were broken chairs in this room.'],
    ['उसने घायल आदमी की बहुत सेवा की।','He cared for the injured man.'],
    ['मैं उसे कमरे में ताला लगाते देखा।','I saw him locking the room.'],
    ['सुबह में टहलना लाभदायक है।','Walking in the morning is beneficial.'],
    ['सिगरेट पीना हानिकारक है।','Smoking is harmful.'],
    ['मैं गाना गाती हूँ।','I sing a song.']
  ],
  examPrep:['Who was Narcissus and what was special about him?','Who was Echo, and why did Hera curse her?','What was the curse placed on Echo?','Why did Echo follow Narcissus and why was she eager to talk to him?','What happened when Echo and Narcissus met?','Why did Echo feel embarrassed and ashamed, and what was the result?','Who prayed against Narcissus, what did they pray for, and was the prayer granted?','What happened when Narcissus went to the pool?','What feeling do you get from the myth when Narcissus sees his reflection?','How did the story end for Narcissus?','What is a Gerund? Give two examples.','What is a Participle? Explain Present, Past and Perfect Participles.','Write about 80 words on “Beauty is only skin-deep”.']
};

const practice=[
 {q:'Who are credited with rendering “Echo and Narcissus” in this chapter?',o:['Moira Kerr and John Bennett','Moti Nisani and John Bennett','Kunal Varma and Moira Kerr','Arjun Dev Charan and Moira Kerr'],a:0,e:'The chapter title page credits Moira Kerr and John Bennett.'},
 {q:'Narcissus is introduced as:',o:['an exceptionally handsome young man','an old fisherman','a soldier with no companions','a travelling poet'],a:0,e:'The opening describes Narcissus as unusually handsome.'},
 {q:'What did Narcissus usually do with his companions?',o:['He went hunting','He taught grammar','He built houses','He sailed across the sea'],a:0,e:'The story places Narcissus with hunting companions.'},
 {q:'Echo was a:',o:['nymph','queen','merchant','hunter'],a:0,e:'Echo is introduced as a nymph.'},
 {q:'Why did Hera become angry with Echo?',o:['Echo had helped distract Hera from Zeus','Echo stole a golden flower','Echo refused to hunt','Echo broke a mirror'],a:0,e:'The lesson explains that Echo’s chatter had helped distract Hera.'},
 {q:'What could Echo say after Hera’s curse?',o:['Only the last words she heard','Anything she wanted','Only songs','Nothing at all'],a:0,e:'Her curse restricted her to repeating the last words she heard.'},
 {q:'Why did Echo follow Narcissus?',o:['She wanted to get closer and admire him','She wanted to defeat him in a hunt','She wanted to take his companions away','She wanted to find the pool first'],a:0,e:'Echo was attracted to Narcissus and wanted to approach him.'},
 {q:'Why was Narcissus confused by Echo’s voice?',o:['He thought someone was playing a trick on him','He knew Echo immediately','He could not hear anything','He was looking at a flower'],a:0,e:'Narcissus believed someone was trying to play a trick on him.'},
 {q:'What happened to Echo after she was rejected?',o:['She hid in a dark cave and gradually withered away','She became a hunter','She married Narcissus','She travelled to another kingdom'],a:0,e:'Echo withdrew from the world and her body faded away.'},
 {q:'What remained after Echo vanished?',o:['Her voice','Her hunting bow','Her crown','Her house'],a:0,e:'The story says that only her voice remained.'},
 {q:'What did the rejected people pray for?',o:['That Narcissus would one day experience the same pain of being scorned','That Narcissus would become a king','That Echo would lose her voice','That the pool would disappear'],a:0,e:'Their prayer asked that Narcissus suffer the same kind of rejection.'},
 {q:'Why did Narcissus go to the pool?',o:['He was tired and thirsty after hunting','He wanted to meet Echo','He wanted to wash his clothes','He was searching for a flower'],a:0,e:'He came to the still pool because he was tired and thirsty.'},
 {q:'What did Narcissus see in the water?',o:['His own reflection','Echo hiding in the cave','A hunting companion','A golden crown'],a:0,e:'He saw a beautiful face reflected on the water’s surface.'},
 {q:'Why could Narcissus not tear himself away?',o:['He became absorbed in the beautiful image','He was trapped by the trees','He had lost his companions','He was waiting for Echo'],a:0,e:'He became completely absorbed in his own reflection.'},
 {q:'What grew where Narcissus had been?',o:['A flower called Narcissus','A tall tree','A rose garden','A golden statue'],a:0,e:'The myth ends with the flower named Narcissus.'}
];

const challenge=[
 {q:'How does Narcissus’s beauty shape the first part of the story?',o:['It causes almost everyone who sees him to fall in love with him','It makes him dislike hunting','It prevents him from speaking','It makes him afraid of Echo'],a:0,e:'The opening stresses that his beauty attracts the love of nearly everyone who sees him.'},
 {q:'Why is Echo’s curse especially painful for her?',o:['She had been a great chatterer but can now only repeat another person’s last words','She cannot hear anyone','She can speak only to animals','She is forbidden to enter the forest'],a:0,e:'Her natural love of talking conflicts directly with the curse.'},
 {q:'What does Echo hope to do when she follows Narcissus?',o:['Get close to him and admire his beauty','Steal his companions','Lead him away from water','Challenge him to a contest'],a:0,e:'She wants to approach and gaze at him, hoping to speak.'},
 {q:'Why does Narcissus misunderstand Echo’s replies?',o:['Her repeated last words sound like someone is deliberately copying or tricking him','He knows that Echo is cursed','He thinks she is his sister','He cannot hear her voice'],a:0,e:'Echo can only repeat the last words she hears, so Narcissus interprets this as a trick.'},
 {q:'Why does Echo become embarrassed and ashamed?',o:['She cannot express herself freely and is mocked and rejected by Narcissus','She forgets how to hunt','She breaks Hera’s second curse','She loses the pool'],a:0,e:'Her inability to communicate and Narcissus’s rejection cause the shame.'},
 {q:'What is the major consequence of Echo’s rejection?',o:['Her youth and beauty fade, her body shrinks and only her voice remains','She becomes more beautiful','She becomes a queen','She forgets the curse'],a:0,e:'The myth shows Echo withering away until only her voice remains.'},
 {q:'Why is the prayer against Narcissus important?',o:['It connects his cruelty toward others with the punishment that follows','It makes Echo return to her old form','It changes the pool into a river','It makes Narcissus lose his companions'],a:0,e:'The prayer is the narrative link between his behaviour and his fate.'},
 {q:'What makes the pool scene a turning point?',o:['Narcissus sees a beautiful reflection and does not recognise it as himself','Echo appears again in person','The companions return and rescue him','Hera changes the curse'],a:0,e:'The reflection causes Narcissus to become absorbed in his own image.'},
 {q:'What does “tear himself away” mean in the story?',o:['Force himself to leave something he strongly wants to keep looking at','Fall into the water immediately','Close his eyes in fear','Run away from his companions'],a:0,e:'The phrase means to make oneself leave or separate from something.'},
 {q:'How is Narcissus’s fate related to the earlier prayer?',o:['He is made to experience a form of unreturned love by becoming absorbed in his own image','He is rewarded for rejecting others','He becomes invisible to everyone','He is allowed to escape into the forest'],a:0,e:'The prayer is fulfilled through his self-absorption and inability to receive the relationship he wants.'},
 {q:'Why does the myth end with a flower?',o:['The transformation provides a lasting image of Narcissus looking into quiet pools','It changes the lesson into a gardening manual','It brings Echo back','It removes the moral consequence'],a:0,e:'The flower visually continues the idea of looking into water.'},
 {q:'What is the strongest contrast between Echo and Narcissus?',o:['Echo cannot speak the words she wants while Narcissus becomes unable to look beyond his own image','Both can say anything they like','Echo loves herself and Narcissus loves everyone else','Both avoid other people for the same reason'],a:0,e:'Their difficulties are different: Echo is restricted by the curse, while Narcissus becomes absorbed in himself.'},
 {q:'What does “scorned” mean?',o:['Rejected or treated as unworthy','Praised warmly','Invited to dinner','Hidden from sunlight'],a:0,e:'The glossary uses scorned for someone treated with rejection or contempt.'},
 {q:'What does “mystify” mean?',o:['Confuse','Comfort','Reward','Praise'],a:0,e:'Mystify means to confuse or puzzle someone.'},
 {q:'Which suffix is used to form “shyness” from “shy”?',o:['-ness','-less','-ly','-ful'],a:0,e:'The word-study section explains that shyness is formed with the suffix -ness.'},
 {q:'Which word is correctly formed by adding “-less” to “help”?',o:['helpless','helpness','helply','helpful'],a:0,e:'Help + less gives helpless.'},
 {q:'Which adverb comes from “rough” by adding the pattern taught in the lesson?',o:['roughly','roughness','roughless','roughing'],a:0,e:'Rough + ly gives roughly.'},
 {q:'In “Swimming is a good exercise,” the word “Swimming” is a:',o:['Gerund','Past Participle','Perfect Participle','finite verb'],a:0,e:'Here the -ing form functions as a noun and is therefore a gerund.'},
 {q:'In “Barking dogs seldom bite,” the word “Barking” works as a:',o:['Present Participle','Gerund','Past Participle','Perfect Participle'],a:0,e:'It qualifies the noun dogs, so it works as a present participle.'},
 {q:'Which sentence uses a Gerund as an object?',o:['I like painting.','Swimming is healthy.','Having finished, he left.','The room was locked.'],a:0,e:'Painting is the object of the verb like.'},
 {q:'Which example shows a Past Participle used adjectivally?',o:['The room looked locked.','I like painting.','Swimming is healthy.','Having finished, he left.'],a:0,e:'Locked is a past participle functioning as an adjective.'},
 {q:'What construction expresses an action completed before another action?',o:['Having + Past Participle','Only the first form of the verb','May + verb','Was + noun'],a:0,e:'The lesson uses the perfect participle pattern Having + Past Participle.'},
 {q:'Which statement best distinguishes a Gerund from a Participle?',o:['A Gerund works as a noun, while a Participle works as a verb form or adjective','A Gerund is always a past tense verb','A Participle can never modify a noun','There is no difference in use'],a:0,e:'That is the central grammar distinction taught in the chapter.'},
 {q:'What theme is most strongly suggested by Narcissus’s fate?',o:['Extreme self-absorption can become destructive','Physical beauty guarantees happiness','Speech is always more important than actions','Rejection never causes pain'],a:0,e:'The myth presents extreme self-love as a destructive force.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`panorama-echo-narcissus-final-${i}`}));

function StudyView(){return <div className="pg-learn">
  <div className="pg-callout pg-no-book"><b>📘 Complete Guided Study</b><span>Story flow, आसान हिन्दी explanation, vocabulary, word study, grammar, activities, translation और exam preparation एक ही जगह।</span></div>
  <section className="pg-panel"><div className="pg-panel-title"><span>ABOUT THE LESSON</span><h2>Chapter का basic idea</h2></div><p>{study.intro}</p><div className="pg-author"><b>लेखक / स्रोत परिचय</b><p>{study.authorNote}</p></div></section>
  <div className="pg-anchorbar"><a href="#guided">Guided Reading</a><a href="#words">Word Study</a><a href="#grammar">Grammar</a><a href="#exam">Exam Prep</a></div>
  <section id="guided" className="pg-section-heading"><span>01</span><div><small>READ • UNDERSTAND • REMEMBER</small><h2>Guided Reading</h2><p>हर block story के flow को आसान English में समझाता है और फिर हिन्दी में उसका अर्थ स्पष्ट करता है।</p></div></section>
  <div className="pg-reading-stack">{study.sections.map((s,i)=><article className="pg-reading-card" key={s.title}><div className="pg-card-top"><div className="pg-num">{String(i+1).padStart(2,'0')}</div><div><span>STORY FLOW</span><h3>{s.title}</h3></div></div><div className="pg-flow"><div className="pg-flow-label">सरल English में पढ़ें</div><p>{s.flow}</p></div><div className="pg-hindi"><div className="pg-flow-label">हिन्दी में समझें</div><p>{s.explanation}</p></div><div className="pg-vocab-head">Vocabulary</div><div className="pg-vocab-grid">{s.vocabulary.map(([w,m])=><div className="pg-vocab" key={w}><b>{w}</b><span>{m}</span></div>)}</div><div className="pg-bottom-grid"><div className="pg-exam"><b>🎯 Exam Point</b><span>{s.exam}</span></div><div className="pg-think"><b>💡 Think</b><span>{s.think}</span></div></div></article>)}</div>
  <section id="words" className="pg-section-heading compact"><span>02</span><div><small>LANGUAGE BUILDING</small><h2>Word Study</h2><p>Spelling, -ness/-less word formation, adverbs, meanings और phrases revise करें।</p></div></section>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>Glossary</h3><div className="pg-glossary">{study.glossary.map(([w,m])=><div key={w}><b>{w}</b><span>{m}</span></div>)}</div></section><section className="pg-panel"><h3>Correct the spelling</h3><div className="pg-spelling">{study.wordStudy.spellings.map(([bad,good])=><div key={bad}><del>{bad}</del><b>→ {good}</b></div>)}</div></section></div>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>-ness word formation</h3><div className="pg-pillgrid">{study.wordStudy.ness.map(([w,m])=><div key={w}><b>{w}</b><span>→ {m}</span></div>)}</div></section><section className="pg-panel"><h3>-less word formation</h3><div className="pg-pillgrid">{study.wordStudy.less.map(([w,m])=><div key={w}><b>{w}</b><span>→ {m}</span></div>)}</div></section></div>
  <section className="pg-panel"><h3>Adverbs from adjectives</h3><div className="pg-pillgrid">{study.wordStudy.adverbs.map(([w,m])=><div key={w}><b>{w}</b><span>→ {m}</span></div>)}</div></section>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>Word Meaning</h3><div className="pg-match">{study.wordStudy.match.map(([q,a])=><div key={q}><span>{q}</span><b>{a}</b></div>)}</div></section><section className="pg-panel"><h3>Phrases</h3><div className="pg-match">{study.wordStudy.phrases.map(([q,a])=><div key={q}><span>{q}</span><b>{a}</b></div>)}</div></section></div>
  <section id="grammar" className="pg-section-heading compact"><span>03</span><div><small>GRAMMAR LAB</small><h2>{study.grammar.title}</h2><p>{study.grammar.intro}</p></div></section>
  <section className="pg-panel"><h3>Core rules</h3><div className="pg-grammar-grid">{study.grammar.rules.map(([t,e,x])=><div key={t}><b>{t}</b><span>{e}</span>{x&&<em>{x}</em>}</div>)}</div><div className="pg-rulebox"><b>Golden Rule</b><span>Check the job of the -ing or participle form in the sentence: noun = Gerund; adjective/verb-form use = Participle.</span></div></section>
  <section className="pg-panel"><h3>Quick grammar examples</h3><div className="pg-phrasegrid"><div><b>Swimming is healthy.</b><span>Gerund as subject.</span></div><div><b>I like painting.</b><span>Gerund as object.</span></div><div><b>He stopped me from smoking.</b><span>Gerund after a preposition.</span></div><div><b>Barking dogs seldom bite.</b><span>Present Participle.</span></div><div><b>The room looked locked.</b><span>Past Participle.</span></div><div><b>Having finished, he left.</b><span>Perfect Participle.</span></div></div></section>
  <section className="pg-section-heading compact"><span>04</span><div><small>WRITING • ACTIVITIES • TRANSLATION</small><h2>Composition & Activities</h2><p>Chapter के practical tasks को exam-ready format में देखें।</p></div></section>
  <section className="pg-tool-grid"><section className="pg-panel"><h3>Composition</h3><ol>{study.composition.map(x=><li key={x}>{x}</li>)}</ol></section><section className="pg-panel"><h3>Activities</h3><div className="pg-activitygrid">{study.activities.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div></section></section>
  <section className="pg-panel"><h3>Translation Practice</h3><div className="pg-translation">{study.translationPractice.map(([h,e],i)=><div key={h}><span>{String(i+1).padStart(2,'0')}</span><b>{h}</b><em>{e}</em></div>)}</div></section>
  <section id="exam" className="pg-section-heading compact"><span>05</span><div><small>EXAM MODE</small><h2>Exam Preparation</h2><p>इन questions पर short answer, long answer, grammar और writing practice करें।</p></div></section>
  <section className="pg-exam-grid"><section className="pg-panel"><h3>Important Questions</h3><ol>{study.examPrep.map(x=><li key={x}>{x}</li>)}</ol></section><section className="pg-panel pg-revision"><h3>One-minute revision</h3><div className="pg-revision-grid"><div><b>Characters</b><span>Echo and Narcissus.</span></div><div><b>Echo</b><span>Talkative nymph cursed by Hera to repeat last words heard.</span></div><div><b>Conflict</b><span>Echo is rejected; Narcissus later becomes absorbed in his own image.</span></div><div><b>Prayer</b><span>Rejected people pray that Narcissus experience the same pain.</span></div><div><b>Setting</b><span>Forest hunting and a still, clear pool.</span></div><div><b>Grammar</b><span>Gerund + Present, Past and Perfect Participles.</span></div></div></section></section>
  <section className="pg-panel"><h3>Chapter Checklist</h3><div className="pg-activitygrid"><div><span>✓</span><p>Can you explain Hera’s curse on Echo?</p></div><div><span>✓</span><p>Can you narrate the meeting of Echo and Narcissus?</p></div><div><span>✓</span><p>Can you explain why the prayer against Narcissus mattered?</p></div><div><span>✓</span><p>Can you describe the pool and the reflection?</p></div><div><span>✓</span><p>Can you distinguish Gerund and the three kinds of Participles?</p></div><div><span>✓</span><p>Can you form -ness, -less and -ly words correctly?</p></div></div></section>
</div>}

export function EnglishPanoramaChapter5({initialMode=null,onBack,addXp,finishSession}){
  const[mode,setMode]=useState(initialMode||'learn');
  const begin=nextMode=>setMode(nextMode);
  if(mode==='learn'||mode===null)return <div className="pg-shell"><button className="pg-back" onClick={onBack}>← वापस</button><header className="pg-hero"><div className="pg-kicker">THE PANORAMA • PROSE CHAPTER 5</div><h1>{study.title}</h1><p>Rendered by {study.author}</p><div className="pg-hero-stats"><span>9 guided parts</span><span>15 Practice questions</span><span>23 Challenge questions</span><span>20 Final Test questions</span></div></header><div className="pg-modebar"><button className="active" onClick={()=>begin('learn')}><b>LEARN</b><span>Guided study • vocabulary • grammar</span></button><button onClick={()=>begin('practice')}><b>15 Practice</b><span>11:15 min • Easy → Moderate</span></button><button onClick={()=>begin('challenge')}><b>23 Challenge</b><span>23:00 min • Moderate → Hard</span></button><button onClick={()=>begin('test')}><b>20 Final Test</b><span>25:00 min • Exam Level</span></button></div><StudyView/></div>;
  const bank=mode==='practice'?practice:mode==='challenge'?challenge:finalTest;
  return <PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>begin('learn')} addXp={addXp} finishSession={payload=>finishSession?.({subject:'english',book:'The Panorama',...payload})}/>;
}

export const englishPanoramaChapter5={title:study.title,author:study.author};
