import React,{useEffect,useMemo,useState}from'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';
import './EnglishPanoramaLanguageSkills.css';

const g=(id,title,mark,tag,core,sections,examples,traps,checks)=>({id,cat:'Grammar',title,mark,tag,core,sections,examples,traps,checks});

const grammar=[
g('tenses','Tenses','T','Time + action shape','Tense बताता है काम कब हुआ/हो रहा है; aspect बताता है उसे habit, process, completed result या duration के रूप में कैसे देखते हैं. Think: **When? + What kind of action?**',[ 
['01','सबसे आसान idea: Tense = Time + Action Shape','English में tense सीखने का सबसे आसान तरीका केवल नाम रटना नहीं है. पहले पूछो: action Present में है, Past में है या Future में? फिर पूछो: यह habit/fact है (Simple), अभी चल रहा है (Continuous), पहले हुआ लेकिन उसका link किसी later time से है (Perfect), या कितनी देर से चल रहा है यह important है (Perfect Continuous). English: Simple = fact/habit, Continuous = in progress, Perfect = earlier action linked to a reference time, Perfect Continuous = duration/activity.'],
['02','Simple Present — आदत, तथ्य, routine','Hindi clue: “रोज़, हमेशा, अक्सर, हर दिन” अक्सर Simple Present की ओर इशारा करते हैं. Form: I/We/You/They + V1; He/She/It + V1+s/es. Example: I play cricket. / He plays cricket. इसका उपयोग habits, routines, facts, general truths और fixed schedules के लिए होता है.'],
['03','Present Continuous — अभी चल रहा है','Form: am/is/are + V-ing. Hindi clue: “अभी”, “इस समय”, “इन दिनों”. Example: I am studying now. / She is reading a book. Temporary situations और arranged near-future plans भी यहाँ आ सकते हैं: We are meeting the teacher tomorrow.'],
['04','Present Perfect — काम पूरा, present link बाकी','Form: has/have + V3. इसका मुख्य idea है: action पहले हुआ, लेकिन उसका result/relevance अब है. Example: I have finished my homework. “मैंने homework कर लिया है” — focus present result पर है. Finished definite past time के साथ आम तौर पर Simple Past चाहिए: I finished it yesterday.'],
['05','Present Perfect Continuous — duration पर focus','Form: has/have been + V-ing. जब activity past में शुरू हुई और अब तक चल रही है, या effort/duration important है, यह form useful है. Example: She has been studying for two hours. Since + starting point; for + duration.'],
['06','Simple Past — finished past event','Form: V2 (regular verb में -ed, irregular में अलग form). Hindi clue: “कल, पिछले साल, पहले, दो घंटे पहले” जैसे finished past time markers. Example: I visited Patna yesterday. Negative/question में did/did not के बाद V1: Did you go? / I did not go.'],
['07','Past Continuous — past में action चल रहा था','Form: was/were + V-ing. अक्सर किसी दूसरे past event की background action बताता है: We were having dinner when he called. “जब call आया” उस समय dinner चल रहा था. While अक्सर continuing action के साथ आता है.'],
['08','Past Perfect — दो past actions में कौन पहले?','Form: had + V3. इसका सबसे useful school-level idea: past में दो घटनाएँ हों और earlier event दिखानी हो. Example: The train had left before we arrived. पहले train left हुई; बाद में we arrived. इसे केवल “बहुत पुराना past” समझना गलत है.'],
['09','Past Perfect Continuous — past reference तक duration','Form: had been + V-ing. जब किसी past reference point से पहले कोई activity कुछ समय से जारी थी और duration important है. Example: They had been waiting for an hour before the bus came.'],
['10','Future Simple — will','Form: will + V1. Predictions, promises, quick decisions और future facts में common: I will help you. / It will rain tomorrow. ध्यान: will के बाद base verb आता है — will go, not will goes.'],
['11','Future के दूसरे natural forms','Be going to + V1: prior plan/intention या evidence-based prediction — I am going to study tonight. Present Continuous: fixed arrangement — We are visiting Delhi on Monday. Simple Present: timetable/schedule — The train leaves at 6 a.m. Future meaning केवल “will” से नहीं बनता.'],
['12','Negative और Question बनाना — tense पहचानने की key','Simple Present में do/does: Do you play? He does not play. Simple Past में did: Did she go? She did not go. Continuous में be auxiliary tense बताता है: Are you reading? Perfect में have/has/had: Have you finished? Future में will: Will they come? Rule: auxiliary को पहचानो; main verb का form उसी के हिसाब से रखो.'],
['13','Time words: clue हैं, command नहीं','Yesterday/last week/ago usually completed past की strong clues हैं. Since = starting point (since 2022). For = duration (for three years). Already/just/yet अक्सर Present Perfect के साथ मिलते हैं. By the time past context में perfect relationship दिखा सकता है. लेकिन keyword देखकर blind choice मत करो; पूरा meaning पढ़ो.'],
['14','Advanced control: stative verbs और meaning','Know, believe, understand, own जैसे stative verbs सामान्य school English में अक्सर continuous नहीं होते: I know him, not I am knowing him. Compare: I have lived here for five years vs I have been living here for five years. दोनों past-to-present link रखते हैं; दूसरा ongoing activity/duration पर ज्यादा focus देता है.'],
['15','Exam decision tree — पहले meaning, फिर formula','Step 1: reference time पकड़ो. Step 2: action habit/fact है? → Simple. अभी/उस समय चल रहा है? → Continuous. Earlier action का later time से link/result है? → Perfect. Duration/ongoing effort important है? → Perfect Continuous. Step 3: subject के अनुसार auxiliary चुनो. Step 4: main verb का सही form देखो. Step 5: time marker से final check करो.'],
['16','12 tense families को एक map में याद करो','Present: I study / I am studying / I have studied / I have been studying. Past: I studied / I was studying / I had studied / I had been studying. Future: I will study / I will be studying / I will have studied / I will have been studying. सारे forms याद करने से ज्यादा important है समझना कि Simple, Continuous, Perfect और Perfect Continuous क्या communicate करते हैं.'] ],
[['मैं रोज़ स्कूल जाता हूँ। → I go to school every day.','habit → Simple Present'],['मैं अभी पढ़ रहा हूँ। → I am studying now.','action in progress → Present Continuous'],['मैं अपना काम कर चुका हूँ। → I have finished my work.','present result → Present Perfect'],['मैं दो घंटे से पढ़ रहा हूँ। → I have been studying for two hours.','duration to now → Present Perfect Continuous'],['मैं कल गया था। → I went yesterday.','finished past → Simple Past'],['जब वह आया, मैं पढ़ रहा था। → I was studying when he came.','background action → Past Continuous'],['हम पहुँचे तो ट्रेन जा चुकी थी। → The train had left before we arrived.','earlier past → Past Perfect'],['बस आने से पहले वे एक घंटे से इंतज़ार कर रहे थे। → They had been waiting for an hour before the bus came.','duration before past point → Past Perfect Continuous'],['मैं तुम्हारी मदद करूँगा। → I will help you.','promise/decision → Future Simple'],['मैं आज रात पढ़ने वाला हूँ। → I am going to study tonight.','prior plan → going to'],['ट्रेन 6 बजे चलती है। → The train leaves at 6 a.m.','timetable → Simple Present for future'],['वह सोमवार को शिक्षक से मिल रही है। → She is meeting the teacher on Monday.','fixed arrangement → Present Continuous for future']],
['Present Perfect को yesterday/last year जैसे finished definite time के साथ blindly मत लगाओ.','did/did not के बाद V1: did go, not did went.','does/does not के बाद भी V1: does go, not does goes.','since = starting point; for = duration.','will + V1: will go, not will goes.','Past Perfect का meaning “earlier past” है, “very old past” नहीं.','Continuous forms में stative verbs के साथ सतर्क रहो.','Keyword देखकर answer मत चुनो; whole sentence का meaning पढ़ो.'],
[['She ___ to school every day.',['goes','is going','went','will going'],0,'Every day shows a routine, so Simple Present is the natural choice.'],['Look! The children ___ in the park.',['are playing','play','have played','had played'],0,'Look! and the context show an action happening now: are + V-ing.'],['I ___ my homework, so I can play now.',['have finished','finished yesterday','am finish','had finish'],0,'The current result is important, so Present Perfect fits.'],['She ___ for two hours and is still reading.',['has been reading','reads yesterday','had read tomorrow','is read'],0,'The activity continues to now and duration is highlighted.'],['We ___ Patna last year.',['visited','have visited','are visiting','had visit'],0,'Last year is a finished past time, so Simple Past is required.'],['At 8 p.m. yesterday, I ___ dinner.',['was having','have had','will have','had have'],0,'A continuing action at a specific past moment takes Past Continuous.'],['The film ___ before we reached the cinema.',['had started','has started','starts','will start'],0,'The film started earlier than another past event, so Past Perfect fits.'],['They ___ for an hour before the teacher arrived.',['had been waiting','have wait','were waited','will wait'],0,'Duration continuing up to a past reference point calls for Past Perfect Continuous.'],['I think it ___ rain tonight.',['will','is','has','did'],0,'Will + base verb is a common form for a prediction.'],['Choose the correct use of since.',['She has lived here since 2021.','She has lived here since five years.','She lived here since five years.','She is live here since 2021.'],0,'Since introduces the starting point of a situation.']]),
g('modals','Modals','M','Meaning + force','Modal auxiliaries change the force of a sentence: they can express ability, permission, possibility, obligation, advice, necessity or expectation.',[
['01','Ability, permission and possibility','Can expresses present ability and some kinds of possibility or permission. Could can express past general ability and polite requests. May can express permission or possibility; might commonly presents a weaker possibility.'],
['02','Obligation and necessity','Must is strong obligation or a strong logical conclusion. Have to / had to commonly express external necessity. Need not expresses absence of necessity, not prohibition.'],
['03','Advice and expectation','Should and ought to express advice, expected behaviour or moral duty. Should can also show expectation: The bus should arrive soon.'],
['04','Form of a modal','Central modals are followed by the base verb: can swim, must study, should go. Do not add to after can, must or should. They normally form negatives/questions without do.'],
['05','Important contrasts','Must not means prohibition. Need not means no necessity. Could may be ability, possibility or polite request depending on context. Would can mark politeness, preference or repeated past behaviour.'],
['06','Advanced exam reasoning','Identify the speaker’s intended force before choosing a modal. The same situation can allow different modals if the intended meaning changes.']],
[['You must wear a helmet.','strong obligation'],['We had to leave early.','past necessity'],['You should revise daily.','advice'],['He may come tomorrow.','possibility'],['She can swim.','ability']],
['must go, not must to go.','must not ≠ need not.','had to is the dependable school-level past form of external obligation.','Modal + base verb.'],
[['Which modal expresses strong obligation?',['must','might','could','needn’t'],0,'Must expresses strong obligation.'],['Which sentence expresses past external necessity?',['We had to leave early.','We must left early.','We should to leave early.','We need leaving early.'],0,'Had to is the standard past form for this kind of necessity.'],['What does need not mean?',['There is no necessity.','The action is forbidden.','The action is impossible.','The action definitely happened.'],0,'Need not removes necessity; it does not prohibit an action.'],['Which form is correct?',['You should study.','You should to study.','You should studying.','You should studied.'],0,'Central modals take the base form of the main verb.']])
,g('voice','Active & Passive Voice','V','Focus + transformation','Active voice foregrounds the doer; passive voice foregrounds the receiver while preserving tense and intended meaning.',[
['01','Find the object','An ordinary passive transformation needs a transitive verb. In The teacher praised the student, student is the direct object and can become the passive subject.'],
['02','Build the passive','Move the object into subject position, keep the original tense through the correct form of be, and use the past participle (V3). Add by + agent only when useful.'],
['03','Tense patterns','Present simple → is/am/are + V3. Past simple → was/were + V3. Present perfect → has/have been + V3. Future → will be + V3. Modal → modal + be + V3.'],
['04','Questions and negatives','Keep the original question or negative meaning. Did the teacher praise him? → Was he praised by the teacher? Do not lose the auxiliary or tense.'],
['05','When to omit the agent','Use the by-phrase when the doer matters. Omit it when the agent is unknown, obvious or unimportant: The road was repaired yesterday.'],
['06','Advanced control','Do not passivise every verb mechanically. Intransitive verbs such as arrive, sleep and happen normally have no direct object for an ordinary passive.']],
[['The teacher praised the student. → The student was praised by the teacher.','simple past'],['They will complete the work. → The work will be completed by them.','future'],['People speak English here. → English is spoken here.','simple present']],
['Do not change the tense while changing voice.','Passive needs the appropriate form of be + V3.','Check that the original verb actually has an object.'],
[['Change to passive: The teacher praised the student.',['The student was praised by the teacher.','The student is praised by the teacher.','The teacher was praised by the student.','The student praised the teacher.'],0,'The simple past passive uses was/were + V3.'],['Choose the correct future passive.',['The work will be completed.','The work was completed.','The work is completing.','The work will complete.'],0,'Future passive is will be + V3.'],['What should remain unchanged in a voice transformation?',['Tense and intended meaning.','Every word in the original order.','Only the subject.','Only the object.'],0,'Voice changes focus, not the time or intended meaning.'],['Which verb normally resists an ordinary passive?',['arrive','build','write','praise'],0,'Arrive is normally intransitive and has no direct object.']])
,g('agreement','Subject–Verb Agreement','S','Find the real subject','The verb agrees with the grammatical subject, not with a nearby noun inside the subject phrase.',[
['01','The head noun controls the verb','The list of names is ready. List, not names, is the head subject. Long phrases can hide the real controller.'],
['02','Singular and plural','A singular subject takes a singular finite verb; a plural subject takes a plural finite verb in the present-tense system.'],
['03','Indefinite pronouns','Each, every, everyone, everybody, anyone, either and neither are commonly singular in standard school grammar.'],
['04','Either/or and neither/nor','With either…or and neither…nor, the verb is often matched to the nearer subject: Neither the teacher nor the students are ready.'],
['05','There is / there are','The noun presented after the introductory there controls agreement: There is a problem; There are many problems.'],
['06','Advanced control','Do not confuse grammatical number with real-world plurality. In exam questions, first identify the head subject, then inspect the verb.']],
[['The list of names is on the table.','head noun = list'],['Neither of the boys is absent.','neither → singular'],['The students are ready.','plural subject'],['There are many books.','postponed subject = books']],
['Ignore nouns after of when finding the head subject.','Do not let a long prepositional phrase decide the verb.','Check there is/there are against the noun that follows.'],
[['The list of names ___ on the table.',['is','are','were','have'],0,'List is the head singular subject.'],['Which is correct?',['Neither of the boys is absent.','Neither of the boys are absent.','Neither boys is absent.','Neither of boys were absent.'],0,'Neither is treated as singular in this construction.'],['There ___ many books on the shelf.',['are','is','was','has'],0,'Many books is plural, so are is required.'],['In A box of pencils is missing, the controlling noun is:',['box','pencils','of','missing'],0,'Box is the head noun of the subject phrase.']])
,g('narration','Reported Speech / Narration','R','Viewpoint + structure','Reported speech changes the viewpoint of a sentence, so pronouns, tense, time expressions and sentence structure may change.',[
['01','Statements','Use said/told + a that-clause as appropriate. Adjust pronouns and tense when the reporting context requires it.'],
['02','Questions','Use asked + a wh-clause or if/whether. The reported question uses statement order: He asked where I lived.'],
['03','Commands and requests','Use told/asked + object + to-infinitive. Negative commands commonly use not to: The teacher told us not to talk.'],
['04','Backshift','After a past reporting verb, school grammar commonly teaches am/is → was, are → were, have/has → had, will → would and can → could.'],
['05','Time and place words','Depending on context, now may become then, today → that day, tomorrow → the next day, here → there, this → that.'],
['06','Advanced context','Backshift is not a blind rule. Timeless facts can remain present: The teacher said that the Earth is round. Meaning and context govern the final form.']],
[['Rina said, “I am busy.” → Rina said that she was busy.','statement'],['He asked, “Where do you live?” → He asked where I lived.','reported question'],['The teacher said, “Sit down.” → The teacher told the students to sit down.','command']],
['No question inversion inside a reported question.','Told normally needs an object; said does not require one.','Pronouns must be changed from the new speaker’s viewpoint.'],
[['Rina said, “I am busy.”',['Rina said that she was busy.','Rina said that I am busy.','Rina said that she is busy tomorrow.','Rina said that she busy.'],0,'A past reporting verb commonly produces am → was and I → she.'],['He asked, “Where do you live?”',['He asked where I lived.','He asked where did I live.','He asked where do I live.','He said where I lived?'],0,'Reported questions use statement word order.'],['“Sit down,” the teacher said.',['The teacher told the students to sit down.','The teacher said the students sit down.','The teacher told to sit down the students.','The teacher asked the students sat down.'],0,'Reported commands commonly use told + object + to-infinitive.'],['Which is correct inside a reported question?',['where I lived','where did I live','where do I lived','where was I live'],0,'The embedded clause keeps statement order.']])
,g('clauses','Clauses','C','Structure + function','A clause contains a subject–verb relationship. Classify it by the job it performs in the larger sentence.',[
['01','Noun clauses','A noun clause functions like a noun: as subject, object or complement. I know what he wants. The clause what he wants is the object of know.'],
['02','Time adverb clauses','When, while, before, after, until and as soon as introduce time relationships.'],
['03','Condition adverb clauses','If, unless and provided that introduce conditions. The condition tells when the main clause can or cannot occur.'],
['04','Relative clauses','Who, whom, which, that, whose and where can introduce clauses that describe or identify a noun.'],
['05','Defining vs non-defining','A defining relative clause identifies the noun and normally has no commas. A non-defining clause adds extra information and is separated by commas.'],
['06','Advanced clause reading','Do not classify a clause only by its first word. Ask what the whole clause does in the sentence.']],
[['I know what he wants.','noun clause'],['I will call you when I reach home.','time clause'],['We will stay inside if it rains.','condition clause'],['The girl who won the race is my sister.','relative clause']],
['A noun clause is not a direct question; use statement order.','Classify by function, not just connector.','Choose relative pronouns according to the noun and grammatical role.'],
[['Which is a noun clause?',['I know what he wants.','I stayed because it rained.','The girl who won smiled.','When the bell rang, we left.'],0,'What he wants functions as the object of know.'],['Which connector introduces time?',['when','who','whose','which'],0,'When introduces a time relationship.'],['Which sentence contains a relative clause?',['The girl who won the race is my sister.','Tell me what you need.','I stayed because it rained.','When he arrived, we ate.'],0,'Who won the race describes the noun girl.'],['Which connector introduces condition?',['if','who','which','whose'],0,'If introduces a condition.']])
,g('determiners','Determiners','D','Noun control','Determiners come before nouns and specify identity, quantity, possession, reference or distribution.',[
['01','Articles','A/an introduce a singular countable noun when it is not specific. The points to a particular/known referent. Choose an by sound, not simply by spelling.'],
['02','Demonstratives and possessives','This/that/these/those point to things. My, your, his, her, our and their express possession.'],
['03','Quantifiers','Some, any, much, many, little, few, several and enough depend on countability and intended meaning.'],
['04','Distributives','Each and every normally take a singular countable noun. Either and neither deal with two choices.'],
['05','Countable vs uncountable','Many/few work with plural countable nouns; much/little work with uncountable nouns. Some and any can work with both in suitable contexts.'],
['06','Advanced control','Choose a determiner after classifying the noun by number, countability and specificity.']],
[['I have some useful books.','plural countable'],['Much water was wasted.','uncountable'],['Every student must attend.','singular countable'],['These books are new.','plural demonstrative']],
['every + singular countable noun.','an is determined by sound: an hour.','much normally modifies uncountable nouns.'],
[['Which is correct?',['I have some useful books.','I have much useful books.','I have every books.','I have a useful books.'],0,'Some can modify plural countable nouns.'],['Choose the best article: ___ hour.',['an','a','thee','some'],0,'Hour begins with a vowel sound.'],['Which determiner fits water?',['much','many','few','several'],0,'Water is uncountable here, so much is appropriate.'],['Which is correct?',['Every student must attend.','Every students must attend.','Every of student must attend.','Every students are attend.'],0,'Every is followed by a singular countable noun.']])
,g('prepositions','Prepositions','P','Relationship + collocation','Prepositions express relationships of time, place, movement and meaning; many are selected by fixed collocation.',[
['01','Time','At is common with a clock time; on with days/dates; in with months, years and longer periods.'],
['02','Place','At can mark a point/location, on a surface, and in an enclosed area or larger space.'],
['03','Movement','To marks destination; into movement to the inside; onto movement to a surface; across means from one side to another.'],
['04','Collocations','Good at, interested in, depend on, afraid of and proud of should be learned as complete combinations.'],
['05','Time expressions','On time means punctual; in time means early enough; by Monday means not later than Monday.'],
['06','Advanced control','Do not translate prepositions mechanically from Hindi. Identify the relationship and then test the natural English collocation.']],
[['He is good at mathematics.','fixed collocation'],['The train arrived on time.','punctual'],['She was born in 2012.','year'],['The book is on the table.','surface']],
['on time ≠ in time.','since/for express different time relationships.','movement into/onto differs from static in/on.'],
[['He is good ___ mathematics.',['at','on','for','with'],0,'Good at is the standard collocation.'],['The train arrived ___ time.',['on','in','at','by'],0,'On time means punctual.'],['She was born ___ 2012.',['in','on','at','to'],0,'Years take in.'],['Which word shows movement to the inside?',['into','in','at','on'],0,'Into expresses movement from outside to inside.']])
];

const extra=[g('idioms','Idioms & Phrases','I','Meaning in context','Idioms are fixed expressions whose overall meaning is often different from the literal meaning of their individual words.',[['01','Understand the whole expression','Treat an idiom as one meaning unit rather than translating each word independently.'],['02','Use context','The surrounding sentence tells whether the expression refers to difficulty, success, secrecy, surprise or another idea.'],['03','Register','Learn whether an expression is informal, neutral or suitable for formal communication before using it.'],['04','Keep the form stable','The wording of a common idiom is usually fixed: once in a blue moon, not once in a blue moons.'],['05','Build a memory system','Record the idiom, plain-English meaning and one natural sentence. Group expressions by meaning.']], [['a piece of cake','very easy'],['once in a blue moon','very rarely'],['break the ice','start friendly interaction'],['spill the beans','reveal a secret']],['Never translate an idiom word-for-word.','Context determines the intended sense.'],[['A piece of cake means:',['very easy','very tasty','very dangerous','very expensive'],0,'The expression means something is easy.'],['Once in a blue moon means:',['very rarely','every day','immediately','very loudly'],0,'It describes something that happens rarely.'],['Break the ice means:',['start friendly interaction','make something colder','end a friendship','break a rule'],0,'It means to begin interaction in a relaxed way.'],['Spill the beans means:',['reveal a secret','cook food','waste water','leave a place'],0,'The idiom means to reveal secret information.']])];

const translation={...g('translation','Hindi → English Translation','TR','Meaning + grammar','Translate the intended meaning into natural English while preserving tense, subject, number, viewpoint and relationships.',[['01','Read the whole Hindi sentence','First decide who acts, when it happens, whether the action is complete/ongoing and what the sentence is trying to communicate.'],['02','Choose English structure','Do not copy Hindi word order automatically. Build an English sentence with the right subject, auxiliary, article and word order.'],['03','Tense and aspect','Time markers such as रोज़, अभी, कल, पहले, से and रहा/रही often guide the English tense or aspect.'],['04','Articles and prepositions','English may require a/an/the or a specific preposition even when Hindi expresses the same relationship differently.'],['05','Natural vocabulary','Choose the English word that fits the context, register and collocation rather than translating each Hindi word separately.'],['06','Final audit','Check subject, tense, auxiliary, article, preposition, pronoun, spelling and punctuation before accepting the translation.']], [['वह रोज़ स्कूल जाता है।','He goes to school every day.'],['मैंने उसे कल देखा।','I saw him yesterday.'],['वह एक छात्र है।','He is a student.'],['वे दो घंटे से पढ़ रहे हैं।','They have been studying for two hours.']],['Word-for-word translation often creates unnatural English.','Do not lose Hindi tense markers.','Recheck pronouns, number and articles.'],[['“वह रोज़ स्कूल जाता है।”',['He goes to school every day.','He go school every day.','He is go to school every day.','He went to school every day.'],0,'A habitual present action takes Simple Present with the third-person form goes.'],['“मैंने उसे कल देखा।”',['I saw him yesterday.','I see him yesterday.','I have seen him yesterday.','I am seeing him yesterday.'],0,'A completed action at a definite past time takes Simple Past.'],['What should a strong translation preserve first?',['Meaning and grammatical relationships','Hindi word order only','Number of English words','The original line breaks'],0,'Meaning and grammatical relationships are the priority.'],['Which process is safest?',['Read → identify meaning/time → choose structure → proofread','Translate each word separately','Choose difficult vocabulary first','Ignore tense until the end'],0,'A staged process reduces literal-translation errors.']]) ,cat:'Language'};

const writing=[
['formal-letter','Formal Letter','FL','Purpose + formal register','Applications and complaints to a Headmaster, municipal authority, BSNL, Editor or Vidyut Board.',[['01','Purpose and audience','The reader expects a formal request, complaint, application or order. State the exact purpose early.'],['02','Format architecture','Plan sender address, date, receiver address, subject, salutation, body, request and closing.'],['03','Body logic','For a complaint: identify the problem → explain effect/evidence → request a practical remedy.'],['04','Language control','Use respectful, objective wording. Avoid slang, emotional exaggeration and unnecessary personal detail.'],['05','Revision checklist','Check addresses, subject line, salutation, purpose, requested action, closing and spelling.']],['A complaint should identify the problem before asking for a remedy.','The subject line should tell the reader what the letter is about.','Formal register should remain consistent.'],[['Which feature belongs in a formal letter?',['A clear subject line','Slang for every sentence','A random story','No closing'],0,'Formal letters need a clear purpose and professional structure.'],['What is the strongest complaint sequence?',['Problem → effect/evidence → requested remedy','Joke → story → unrelated opinion','Address → repeated greeting → no request','Only emotion'],0,'This sequence makes the request clear and actionable.'],['Which salutation is appropriate to a Headmaster?',['Respected Sir/Madam,','Hi buddy,','Hey everyone,','Dear bestie,'],0,'A formal salutation fits the institutional audience.'],['What should the final audit check?',['Format, purpose, grammar and requested action','Only word count','Only handwriting','Only vocabulary difficulty'],0,'A complete revision checks both task fulfilment and language accuracy.']]],
['informal-letter','Informal Letter','IL','Personal register','Letters to father, friend or uncle for invitation, thanks, holidays, congratulations, permission or life aims.',[['01','Audience','The relationship permits a warm and personal voice, but the letter still needs a clear purpose.'],['02','Opening','Use a natural greeting and establish the reason for writing without a mechanical formal tone.'],['03','Development','Add relevant experiences, explanations, questions or plans in a logical sequence.'],['04','Tone','Personal does not mean careless. Avoid random slang and keep sentences readable.'],['05','Closing','End with an appropriate personal closing and name.']],['Dear Father, ...','warm opening'],['Keep the purpose visible.','Use a personal but organised tone.','Do not copy formal-letter language mechanically.'],[['An informal letter should sound:',['Warm and personal but organised','Official and bureaucratic','Like a newspaper report','Like a notice'],0,'The relationship allows a personal register.'],['What should still remain clear?',['The reason for writing','Only the greeting','Only the date','Nothing'],0,'Every letter needs a clear communicative purpose.'],['Which is a suitable closing style?',['With love,','Yours faithfully, Chairman','NOTICE','Subject:'],0,'A personal closing suits an informal relationship.'],['What is a good revision rule?',['Check purpose, sequence, grammar and tone.','Remove all personal details.','Use only formal vocabulary.','Avoid paragraphs.'],0,'Informal writing still benefits from structure and accuracy.']]],
['notice','Notice','N','Scan + essentials','A concise public announcement for school or community use.',[['01','Purpose','A notice communicates information to a group quickly, so the reader should find the core facts immediately.'],['02','Required information','Include institution/heading, NOTICE, date, event or announcement, what, when, where, who/eligibility and authority.'],['03','Compression','Use short, information-rich statements rather than a long narrative.'],['04','Visual hierarchy','Heading and key details should stand out; avoid hiding time or venue inside a paragraph.'],['05','Final audit','Check date, time, venue, target audience and issuing authority.']],['What • When • Where • Who','information skeleton'],['Do not bury the date/time.','Do not turn a notice into a story.','Essential details must be complete.'],[['The main purpose of a notice is to:',['Communicate essential public information quickly','Tell a long personal story','Express private feelings','Write a full essay'],0,'Notices are concise public-information texts.'],['Which detail is essential?',['Date/time/venue when relevant','A fictional dialogue','Personal memories','Unrelated jokes'],0,'Readers need actionable event information.'],['A good notice is usually:',['Concise and scannable','Long and repetitive','Unstructured','Only one sentence'],0,'A notice prioritises fast retrieval of essentials.'],['What should be checked last?',['Who, what, when, where and issuing authority','Only adjectives','Only title decoration','Only handwriting'],0,'The final audit verifies task-critical information.']]],
['report','Report Writing','R','Facts + sequence','A factual account of an event or incident for a reader who was not present.',[['01','Report perspective','A report reconstructs an event using relevant facts, not unsupported drama.'],['02','Core questions','Cover who, what, when, where, why and how when relevant to the event.'],['03','Sequence','Use chronological or logical order so the reader can follow the event.'],['04','Language','Completed events commonly use past tense; select precise, neutral vocabulary.'],['05','Revision','Remove repetition, check factual consistency and make sure the headline matches the report.']],['Headline → opening facts → sequence → outcome','report architecture'],['Facts over exaggeration.','Use a clear sequence.','Keep headline and body consistent.'],[['A report should mainly present:',['Relevant facts in organised sequence','Private feelings only','Unrelated jokes','A fictional dialogue'],0,'Reports reconstruct events using relevant facts.'],['Which tense commonly suits a completed event report?',['Past tense','Random tense changes','Only future tense','Only present continuous'],0,'Past tense usually fits completed events.'],['Which planning questions help?',['Who, what, when, where, why, how','Only who','Only why','Only adjectives'],0,'These questions help ensure adequate event coverage.'],['What should revision remove?',['Repetition and unsupported exaggeration','Useful evidence','The event','The headline'],0,'Revision should improve relevance and factual control.']]],
['speech','Speech Writing','SP','Audience + persuasion','An organised spoken presentation for a school or community audience.',[['01','Audience','A speech is written to be heard. Address listeners directly and choose vocabulary they can follow.'],['02','Opening','Greet/address the audience and introduce the topic and purpose.'],['03','Development','Build two or three strong points with examples, reasons or a short call to action.'],['04','Flow','Use spoken signposts such as first, next, finally, therefore and in conclusion.'],['05','Closing','Finish with a memorable conclusion, reflection or call to action.']],['Greeting → topic → key points → call to action → closing','speech flow'],['Write for listening.','Keep one central message.','Do not crowd the speech with too many points.'],[['Which opening fits a school speech?',['Good morning respected teachers and dear friends,','Dear customer, pay now.','Hi invoice,','NOTICE'],0,'A speech needs an audience-appropriate greeting.'],['What strengthens a speech?',['Clear points with examples and a conclusion','Many unrelated points','Only a greeting','No audience reference'],0,'Organisation and examples make spoken arguments easier to follow.'],['Which connector helps spoken flow?',['First, next, finally','Because of a blue chair','Once maybe alphabet','Randomly'],0,'Signposting helps listeners track the structure.'],['A strong ending should:',['Reinforce the message or call to action','Introduce an unrelated topic','Repeat the greeting only','Stop without a conclusion'],0,'A clear ending gives the speech closure.']]],
['message','Message Writing','MSG','Accuracy under compression','A short transfer of essential information.',[['01','Purpose','A message passes information from one person to another when the original receiver is unavailable or needs a quick update.'],['02','Information filter','Capture who, what, when, where and any action required.'],['03','Compression','Remove background details that do not affect the action or understanding.'],['04','Accuracy','Names, dates, times, places and numbers must be copied carefully.'],['05','Final audit','Ask whether the receiver could act correctly after reading only the message.']],['Who + what + when + action','message test'],['Short does not mean incomplete.','Do not add irrelevant biography.','Never alter names or times.'],[['A good message prioritises:',['Essential actionable information','Every detail of the sender’s life','Decorative language','A long introduction'],0,'A message compresses information without losing what the receiver needs.'],['Which detail should never be guessed?',['A time or date','A descriptive adjective','A decoration','A greeting'],0,'Incorrect times/dates can make the message unusable.'],['What is the best test of a message?',['Can the receiver act correctly from it?','Is it the longest?','Does it use advanced vocabulary?','Does it contain jokes?'],0,'Actionability is the key test.'],['A message should avoid:',['Unnecessary background','Names','Times','Required actions'],0,'Background should be omitted when it does not affect the task.']]],
['paragraph-essay','Paragraph / Essay','PE','Central idea + development','A focused piece on people, television, games, matches, seasons, experiences or another assigned theme.',[['01','Topic sentence','State the central idea so the reader knows what the paragraph is about.'],['02','Development','Use two or three supporting points, reasons, facts or examples.'],['03','Coherence','Use linking words to show addition, contrast, cause, sequence or conclusion.'],['04','Unity','Every sentence should support the main idea; delete interesting but irrelevant details.'],['05','Conclusion','End with a final observation or judgement rather than repeating every sentence.']],['Topic → reasons/details → example → conclusion','basic plan'],['One central idea.','Logical linking.','No repetition disguised as development.'],[['A strong paragraph begins with:',['A clear central idea','Several unrelated topics','A conclusion only','A random quotation'],0,'The topic sentence establishes focus.'],['Which improves coherence?',['Linking words showing relationships','Changing topic every sentence','Repeating the title','Removing transitions'],0,'Transitions show how ideas relate.'],['Unity means:',['Every sentence supports the central idea','Every sentence is very long','Every paragraph has many topics','Only examples are allowed'],0,'Unity keeps the paragraph focused.'],['A useful final check asks:',['Did I answer the assigned topic fully and clearly?','Did I use the longest words?','Did I avoid all examples?','Did I remove the topic sentence?'],0,'Task fulfilment matters more than vocabulary complexity.']]],
['composition','Composition','CO','Description + narrative craft','A shaped response describing a situation or event.',[['01','Set the scene','Give only enough context for the reader to understand where, when and under what circumstances the situation occurs.'],['02','Develop the event','Select the important actions and details; keep the sequence understandable.'],['03','Language craft','Use concrete details, accurate verbs and consistent tense/viewpoint.'],['04','Control','Avoid turning the answer into a loose list of every detail you remember.'],['05','Ending','Show the result, response, lesson or final observation appropriate to the task.']],['Scene → situation → key development → result/reflection','composition arc'],['Relevant detail beats quantity.','Keep tense consistent.','Shape the beginning and ending.'],[['A good composition should feel:',['Shaped and purposeful','Like unrelated notes','Like a dictionary page','Like a list with no order'],0,'A composition needs deliberate structure.'],['Which detail is strongest?',['A relevant concrete detail','Any random detail','Only an adjective','An unrelated fact'],0,'Relevant detail makes the situation vivid without losing focus.'],['What should remain consistent?',['Tense and viewpoint','Random punctuation','Topic every sentence','Character names changing'],0,'Consistency helps the reader follow the narrative.'],['A strong ending may include:',['A result or reflection relevant to the situation','A completely new topic','An unrelated story','No closure'],0,'The ending should resolve or reflect on the developed situation.']]]
].map(([id,title,mark,tag,core,sections,examples,traps,checks])=>({id,cat:'Writing',title,mark,tag,core,sections,examples:examples.map(x=>Array.isArray(x)?x:[x,'guide']),traps,checks}));

const reading=[
{id:'factual-reading',cat:'Reading',title:'Factual Unseen Passage',mark:'F',tag:'Evidence reading',core:'Read factual passages for facts, relationships, sequence, cause/effect and supporting evidence.',sections:[['01','Read for structure','Identify the topic, paragraph roles and overall direction before chasing individual answers.'],['02','Evidence scan','Return to the relevant lines and verify exactly what is stated.'],['03','Inference','An inference is a reasonable conclusion supported by clues, not an unsupported guess.'],['04','Vocabulary in context','Use the surrounding sentence, paragraph topic and logical relationship to infer meaning.'],['05','Question traps','Watch not, except, least, most, mainly and only.'],['06','Advanced choice','When two options seem plausible, prefer the one with the strongest textual evidence and fewest assumptions.']],examples:[['Fact','directly stated information'],['Inference','reasonable conclusion from clues'],['Main idea','central point'],['Supporting detail','evidence that develops the point']],traps:['Do not select an option merely because it repeats a word from the passage.'],checks:[['A strong factual answer is:',['Supported by passage evidence','Based only on memory','The longest option','The option repeating a noun'],0,'Factual comprehension depends on evidence.'],['An inference is:',['A reasonable conclusion from clues','A random guess','A copied title','An unrelated fact'],0,'Inference goes beyond exact wording but remains text-supported.'],['What should you do with EXCEPT?',['Find the one option that does not fit','Ignore the word','Choose the first option','Choose the longest option'],0,'Exception words change the task.'],['For vocabulary in context, first use:',['Surrounding sentence and paragraph meaning','The rarest dictionary meaning','Only spelling','Only the options'],0,'Context narrows the intended meaning.']]},
{id:'literary-reading',cat:'Reading',title:'Literary Unseen Passage',mark:'L',tag:'Interpretation',core:'Read literary passages for character, mood, conflict, event, theme and supported inference.',sections:[['01','Character','Track what characters say, think and do; actions often reveal motives and traits.'],['02','Mood and tone','Notice emotional atmosphere and the narrator’s attitude.'],['03','Inference','Infer only what actions, dialogue and description support.'],['04','Theme','Ask what larger idea the events develop rather than naming only the plot.'],['05','Vocabulary','Use tone and context, not one isolated word.'],['06','Advanced distinction','Separate authorial statement, a character’s belief and your own interpretation.']],examples:[['Character trait','supported by behaviour'],['Tone','attitude/emotional quality'],['Theme','larger idea'],['Inference','reasoned interpretation']],traps:['Do not import information from another story or from memory.'],checks:[['A character inference should be based on:',['Actions, dialogue and clues','The name alone','Personal experience only','Another story'],0,'Literary inference must be grounded in the passage.'],['Tone means:',['The attitude or emotional quality of the writing','The number of paragraphs','The ending only','A dictionary entry'],0,'Tone describes attitude.'],['Theme is:',['A larger idea developed by the text','One isolated word','The title only','The setting only'],0,'Theme is broader than a single detail.'],['Two interpretations should be resolved by:',['Choosing the one with stronger textual support','Choosing the dramatic one','Choosing the longest one','Choosing the one from memory'],0,'Textual evidence should control interpretation.']]},
{id:'poetry-reading',cat:'Reading',title:'Poetry Unseen Passage',mark:'P',tag:'Image + tone',core:'Read poetry for image, tone, contrast, figurative meaning and the poet’s central idea.',sections:[['01','Read the stanza as a whole','Do not decode one difficult word before understanding the surrounding idea.'],['02','Images and contrasts','Notice repeated images, sensory details, oppositions and changes in emotional direction.'],['03','Figurative meaning','Metaphor, personification and symbolism create meaning beyond literal description.'],['04','Tone','Ask whether the poem sounds joyful, reflective, ironic, angry, peaceful or uncertain—and what creates that tone.'],['05','Context vocabulary','Use nearby lines to decide what an unfamiliar word means in that poem.'],['06','Advanced synthesis','Connect image + tone + central idea instead of treating poetic devices as isolated definitions.']],examples:[['Image','picture created in the reader’s mind'],['Tone','attitude/emotional quality'],['Metaphor','comparison without like/as'],['Personification','human quality given to a non-human thing']],traps:['Do not assume every poetic statement is literal.'],checks:[['An unfamiliar poetic word should first be solved using:',['Surrounding lines and imagery','Only the rarest dictionary meaning','The title alone','A random synonym'],0,'Poetic context is essential.'],['A metaphor mainly creates:',['A comparison that adds meaning or imagery','A timetable','A grammar error','A punctuation rule'],0,'Metaphor links things for expressive meaning.'],['Tone is best understood as:',['The attitude or emotional quality','The number of lines','The poet’s birthplace','Rhyme count only'],0,'Tone reflects expressive attitude.'],['A strong interpretation combines:',['Image, tone and central idea','Only rhyme words','Only punctuation','One difficult word'],0,'Poetry interpretation benefits from multiple contextual clues.']]}
];

const topics=[...grammar,translation,...extra,...writing,...reading];
const byId=Object.fromEntries(topics.map(t=>[t.id,t]));
const cats=['Grammar','Language','Writing','Reading'];
function bank(topic){const q=topic.checks.map(([question,opts,a,e])=>({q:question,o:opts,a,e}));return{practice:q.slice(0,5),challenge:q.slice(1,Math.min(8,q.length)),finalTest:q.slice(0,Math.min(10,q.length))};}
function navTopic(id){const p=new URLSearchParams(window.location.search);p.set('topic',id);window.history.pushState({},'',`${window.location.pathname}?${p}${window.location.hash||''}`);window.dispatchEvent(new Event('popstate'));}
function leaveTopic(){const p=new URLSearchParams(window.location.search);p.delete('topic');window.history.pushState({},'',`${window.location.pathname}?${p}${window.location.hash||''}`);window.dispatchEvent(new Event('popstate'));}

function TopicPage({topic,onBack,addXp,finishSession}){const[mode,setMode]=useState(null);const b=useMemo(()=>bank(topic),[topic]);if(mode){const chosen=b[mode==='practice'?'practice':mode==='challenge'?'challenge':'finalTest'];return <PanoramaTimedQuiz key={`${topic.id}-${mode}`} mode={mode==='test'?'test':mode} title={`${topic.title} • ${mode==='practice'?'Practice':mode==='challenge'?'Challenge':'Final Test'}`} bank={chosen} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;}return <main className="pg-shell els-page els-topic-page"><header className="els-topic-bar"><button className="pg-back" onClick={onBack}>← Back to Skills Hub</button><span>{topic.cat} • ADVANCED TOPIC</span></header><section className="els-topic-hero"><div><div className="els-kicker">CLASS 9 • ENGLISH • DEEP LEARNING</div><h1>{topic.title}</h1><p>{topic.core}</p><div className="els-topic-chips"><span>{topic.tag}</span><span>{topic.sections.length} deep lessons</span><span>3 assessment levels</span></div></div><div className="els-topic-symbol">{topic.mark}</div></section><section className="els-assessment-dock"><div><span>ASSESSMENT PATH</span><h2>Learn → practise → challenge → test</h2><p>Each topic has its own assessment flow so the learner can master the concept before moving on.</p></div><div className="els-assessment-actions"><button onClick={()=>setMode('practice')}><b>Practice</b><small>5 guided questions</small></button><button onClick={()=>setMode('challenge')}><b>Challenge</b><small>{b.challenge.length} harder questions</small></button><button onClick={()=>setMode('test')}><b>Final Test</b><small>{b.finalTest.length} exam questions</small></button></div></section><div className="els-topic-layout"><aside className="els-topic-nav"><strong>LESSON MAP</strong>{topic.sections.map(([n,t])=><a href={`#${topic.id}-${n}`} key={n}>{n} {t}</a>)}<button onClick={()=>setMode('practice')}>Start Practice →</button></aside><div className="els-topic-body">{topic.sections.map(([n,t,body])=><article className="els-deep-card" id={`${topic.id}-${n}`} key={n}><div className="els-deep-num">{n}</div><div><span>LESSON {n}</span><h2>{t}</h2><p>{body}</p></div></article>)}<section className="els-topic-block"><span>EXAMPLES & APPLICATION</span><h2>See the concept in action</h2><div className="els-example-grid">{topic.examples.map((x,i)=><article key={i}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div></section><section className="els-growth-grid"><article><span>ERROR CLINIC</span><h2>Common traps to eliminate</h2>{topic.traps.map((x,i)=><p key={i}>• {x}</p>)}</article><article><span>ACTIVE RECALL</span><h2>Make the rule yours</h2><p>Close the page and explain one rule in your own words. Then create one new example. Recognition is not mastery; retrieval is.</p><button onClick={()=>setMode('challenge')}>Open Challenge →</button></article></section></div></div></main>}

export function EnglishPanoramaLanguageSkills({onBack,addXp,finishSession}){const[topicId,setTopicId]=useState(()=>new URLSearchParams(window.location.search).get('topic')||null);useEffect(()=>{const s=()=>setTopicId(new URLSearchParams(window.location.search).get('topic')||null);window.addEventListener('popstate',s);return()=>window.removeEventListener('popstate',s)},[]);if(topicId&&byId[topicId])return <TopicPage topic={byId[topicId]} onBack={leaveTopic} addXp={addXp} finishSession={finishSession}/>;return <main className="pg-shell els-page"><div className="els-top"><button className="pg-back" onClick={onBack}>← Back to English</button><span className="els-badge">ADVANCED LANGUAGE LAB</span></div><section className="els-hero els-hero-advanced"><div><div className="els-kicker">CLASS 9 • ENGLISH • BSEB-ALIGNED</div><h1>English Language<br/><em>&amp; Skills Hub</em></h1><p>Every syllabus area is now a dedicated deep-learning topic page with concept lessons, examples, an error clinic, active recall and three assessment levels.</p><div className="els-chips"><span>{topics.length} topic pages</span><span>Grammar + Language</span><span>Writing</span><span>Reading</span></div></div><div className="els-hero-side"><strong>{topics.length}</strong><span>TOPIC PAGES</span><strong>3</strong><span>ASSESSMENT LEVELS</span></div></section><section className="els-guidance"><div><span>MASTER METHOD</span><h2>Learn deeply, then prove it</h2><p><b>Understand</b> the rule → <b>apply</b> it to examples → <b>debug</b> common mistakes → <b>practise</b> → <b>challenge</b> → <b>test</b>.</p></div><button onClick={()=>navTopic('tenses')}>Start with Tenses →</button></section>{cats.map(cat=><section className="els-topic-section" key={cat}><div className="els-topic-section-head"><div><span>{cat.toUpperCase()} LAB</span><h2>{cat==='Grammar'?'Grammar from foundation to advanced control':cat==='Language'?'Translation as a complete language skill':cat==='Writing'?'Writing formats, structure and revision': 'Evidence, inference and interpretation'}</h2></div><em>{topics.filter(t=>t.cat===cat).length} pages</em></div><div className="els-topic-grid">{topics.filter(t=>t.cat===cat).map((t,i)=><button className={`els-topic-card ${t.id==='tenses'?'is-featured':''}`} key={t.id} onClick={()=>navTopic(t.id)}><div className="els-topic-card-mark">{t.mark}</div><div><small>{String(i+1).padStart(2,'0')} • {t.tag}</small><h3>{t.title}</h3><p>{t.core}</p><b>Open deep topic →</b></div></button>)}</div></section>)}<section className="els-roadmap"><div><span>EXAM FLUENCY PATH</span><h2>Do not just memorise rules—build control</h2><p>Move topic by topic. Finish Learn, then Practice, Challenge and Final Test. Return to weak topics and rebuild from the explanation instead of repeating only the answers you already know.</p></div><button onClick={()=>navTopic('tenses')}>Open Tenses master page →</button></section></main>}
