import React,{useMemo,useState}from'react';
import './EnglishReportedSpeechTopic.css';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';

const LESSONS=[
{id:'01',group:'FOUNDATION',title:'Direct vs Reported Speech',meaning:'Direct speech gives the speaker’s exact words. Reported speech tells the same message from the reporter’s point of view, usually without quotation marks.',simple:'सीधी बात में वही शब्द लिखते हैं जो व्यक्ति ने बोले। Reported speech में हम उस बात को अपने sentence में बताते हैं।',structure:'Direct: Rina said, “I am tired.” → Reported: Rina said that she was tired.',examples:[['Mohan said, “I am ready.”','Mohan said that he was ready.'],['Sita said, “I like tea.”','Sita said that she liked tea.']],clue:'Same message; viewpoint and structure change.'},
{id:'02',group:'FOUNDATION',title:'Reporting verbs: said and told',meaning:'Say normally reports words without a required object. Tell normally takes a person as its object: told me, told her, told the students.',simple:'said के बाद व्यक्ति लगाना हो तो आम तौर पर said to आता है; told के बाद object आता है।',structure:'said + clause • said to + person • told + person + clause',examples:[['He said, “I am busy.”','He said that he was busy.'],['He said to me, “I am busy.”','He told me that he was busy.'],['The teacher told the students that the test was ready.','told + object + reported clause.']],clue:'tell needs a listener/object in this school pattern.'},
{id:'03',group:'STATEMENTS',title:'Reporting statements with that',meaning:'A statement can be introduced with said that or told + object + that. The reporting clause identifies who reports the message.',simple:'Statement को report करते समय that लगाया जा सकता है।',structure:'said/told + (object) + that + reported clause',examples:[['Riya said, “I know the answer.”','Riya said that she knew the answer.'],['He told me, “The room is clean.”','He told me that the room was clean.']],clue:'First control the reporting verb; then rebuild the statement.'},
{id:'04',group:'PRONOUNS',title:'Pronoun changes',meaning:'Pronouns change according to the new speaker/listener viewpoint. I may become he/she; my may become his/her; you depends on who is being addressed.',simple:'Pronoun बदलते समय पूछो: अब बात किसके दृष्टिकोण से कही जा रही है?',structure:'I → he/she • my → his/her • we → they • our → their • you → context-based',examples:[['Rina said, “I am happy.”','Rina said that she was happy.'],['Amit said to me, “You are late.”','Amit told me that I was late.'],['The boys said, “We finished our work.”','The boys said that they had finished their work.']],clue:'Pronoun change follows speaker + listener relationship.'},
{id:'05',group:'BACKSHIFT',title:'Present to past after a past reporting verb',meaning:'When the reporting verb is past, school grammar commonly teaches backshift: present forms move one step into the past when the context requires it.',simple:'जैसे: am/is → was, are → were, do/does → did, has/have → had.',structure:'am/is → was • are → were • V1/V-s → V2 • has/have → had',examples:[['He said, “I am tired.”','He said that he was tired.'],['She said, “I play cricket.”','She said that she played cricket.'],['They said, “We have finished.”','They said that they had finished.']],clue:'Past reporting verb often triggers one-step backshift.'},
{id:'06',group:'BACKSHIFT',title:'Past and future backshift',meaning:'Past forms may shift to past perfect, and will commonly becomes would after a past reporting verb in school-level narration.',simple:'Past और future को report करते समय भी tense बदल सकता है: V2 → had + V3; will → would.',structure:'V2 → had + V3 • will → would • can → could',examples:[['She said, “I saw him.”','She said that she had seen him.'],['He said, “I will help you.”','He said that he would help me.'],['Rina said, “I can swim.”','Rina said that she could swim.']],clue:'Move the tense carefully; do not change meaning.'},
{id:'07',group:'TIME & PLACE',title:'Time and place words',meaning:'Words referring to the original speaking situation may change when the viewpoint changes.',simple:'now, today, tomorrow जैसे शब्द reporting situation के अनुसार बदल सकते हैं।',structure:'now → then • today → that day • tomorrow → the next day • yesterday → the previous day • here → there',examples:[['He said, “I am leaving today.”','He said that he was leaving that day.'],['She said, “I will come tomorrow.”','She said that she would come the next day.'],['Ravi said, “I live here.”','Ravi said that he lived there.']],clue:'Change a time/place word only when the new context requires it.'},
{id:'08',group:'QUESTIONS',title:'Reported yes/no questions',meaning:'Questions beginning with do/does/did, is/are, can, will and similar auxiliaries are commonly reported with asked + if/whether. The reported clause uses statement order.',simple:'Yes/No question में if/whether आता है और question order हटकर statement order आता है।',structure:'asked + if/whether + subject + verb',examples:[['He asked, “Are you ready?”','He asked if I was ready.'],['She asked, “Do you know him?”','She asked whether I knew him.'],['Ravi asked, “Will you come?”','Ravi asked if I would come.']],clue:'No question inversion: He asked if I was ready.'},
{id:'09',group:'QUESTIONS',title:'Reported Wh-questions',meaning:'Wh-questions keep the question word but change the rest into statement word order. Do not use do/does/did as question support inside the reported clause.',simple:'Wh-word वही रहता है, लेकिन उसके बाद सामान्य statement order आता है।',structure:'asked + wh-word + subject + verb',examples:[['He asked, “Where do you live?”','He asked where I lived.'],['She asked, “Why are you late?”','She asked why I was late.'],['The teacher asked, “When did you finish?”','The teacher asked when I had finished.']],clue:'Where I lived, not where did I live.'},
{id:'10',group:'COMMANDS',title:'Commands and requests',meaning:'Commands are commonly reported with told + object + to-infinitive. Requests may use asked + object + to-infinitive depending on tone and context.',simple:'आदेश में told + person + to + verb. Request में asked + person + to + verb.',structure:'told/asked + object + to + V1',examples:[['The teacher said, “Sit down.”','The teacher told the students to sit down.'],['Mother said to me, “Open the door.”','Mother told me to open the door.'],['He said to me, “Please help me.”','He asked me to help him.']],clue:'The listener becomes an object after told/asked.'},
{id:'11',group:'COMMANDS',title:'Negative commands',meaning:'A negative command is reported with not to + base verb.',simple:'“मत करो” वाले sentence में not to आता है।',structure:'told/asked + object + not to + V1',examples:[['The teacher said, “Do not talk.”','The teacher told the students not to talk.'],['She said to him, “Do not waste time.”','She told him not to waste time.']],clue:'do not → not to in the reported command pattern.'},
{id:'12',group:'SPECIAL',title:'Exclamations and emotional sentences',meaning:'Exclamatory sentences are reported by choosing a suitable reporting verb such as exclaimed, cried or said with an emotion clause, depending on context.',simple:'भाववाचक sentence में खुशी, दुख, आश्चर्य आदि का भाव report करना जरूरी है।',structure:'exclaimed/said + that + emotional clause',examples:[['She said, “What a beautiful flower!”','She exclaimed that it was a very beautiful flower.'],['He said, “Alas! I am defeated.”','He exclaimed with sorrow that he was defeated.']],clue:'Preserve the emotion, not just the words.'},
{id:'13',group:'SPECIAL',title:'Suggestions with let us',meaning:'“Let us/Let’s” commonly reports a suggestion with suggested or proposed that we should … / suggested + V-ing depending on the construction taught.',simple:'“Let us…” अक्सर suggestion होता है, इसलिए suggested/proposed से report करते हैं।',structure:'Let us + V1 → suggested that we should + V1',examples:[['He said, “Let us go for a walk.”','He suggested that we should go for a walk.'],['Rina said, “Let’s study together.”','Rina suggested that we should study together.']],clue:'Identify suggestion before choosing the reporting verb.'},
{id:'14',group:'EXCEPTIONS',title:'Universal truths and facts',meaning:'A timeless fact can remain in the present after a past reporting verb when the truth is still valid.',simple:'अगर बात हमेशा सच है, तो present tense रह सकता है।',structure:'The teacher said, “The Earth is round.” → The teacher said that the Earth is round.',examples:[['The teacher said, “The Earth is round.”','The teacher said that the Earth is round.'],['He said, “Water boils at 100°C.”','He said that water boils at 100°C.']],clue:'Truth stays true; context can keep present tense.'},
{id:'15',group:'CONTEXT',title:'When backshift is not automatic',meaning:'Tense change depends on context, especially when the reporting verb is present or the original fact remains current.',simple:'हर sentence में mechanically tense बदलना सही नहीं; reporting context देखना जरूरी है।',structure:'Present reporting verb often keeps the original tense: He says, “I am ready.” → He says that he is ready.',examples:[['He says, “I am ready.”','He says that he is ready.'],['She says, “I have finished.”','She says that she has finished.']],clue:'Reporting context decides whether backshift is needed.'},
{id:'16',group:'EXAM',title:'Common narration traps',meaning:'Most exam errors come from changing only one part. Check pronoun, reporting verb, tense, time word and sentence order together.',simple:'एक साथ पाँच चीजें check करो: reporting verb, pronoun, tense, time-word, word order.',structure:'REPORTING VERB → PRONOUN → TENSE → TIME/PLACE → WORD ORDER',examples:[['Incorrect: He asked where did I live.','Correct: He asked where I lived.'],['Incorrect: She told that she was tired.','Correct: She told me that she was tired.'],['Incorrect: Teacher said me to sit.','Correct: Teacher told me to sit.']],clue:'Do a full-system audit, not a one-word correction.'},
{id:'17',group:'ADVANCED',title:'Full transformation workflow',meaning:'For a reliable exam transformation, identify sentence type first, choose the reporting verb, adjust pronouns, apply necessary tense/time changes, then rebuild the clause.',simple:'पहले sentence का type पहचानो, फिर step-by-step conversion करो।',structure:'1 Type → 2 Reporting verb → 3 Pronouns → 4 Tense → 5 Time/place → 6 Clause order → 7 Meaning check',examples:[['“Where are you going?”','asked + where + I + was going'],['“Finish your work.”','told + object + to + finish'],['“I will help you tomorrow.”','said/told + would + pronoun change + next day']],clue:'Sequence prevents most narration mistakes.'},
{id:'18',group:'MASTER',title:'Final exam audit',meaning:'Before submitting a narration answer, read it as a complete sentence. The grammar may be technically transformed but still wrong if the speaker, listener, time or meaning has changed incorrectly.',simple:'अंत में पूरा sentence दोबारा पढ़ो और देखो कि मूल अर्थ वही है या नहीं।',structure:'TYPE ✓ VERB ✓ PRONOUN ✓ TENSE ✓ TIME ✓ ORDER ✓ MEANING ✓',examples:[['Rina said to me, “I will meet you tomorrow.”','Rina told me that she would meet me the next day.'],['Teacher said, “Do not waste time.”','Teacher told the students not to waste time.']],clue:'Correct grammar + preserved meaning = exam-ready narration.'}
];

const Q=(q,o,a,e)=>({q,o,a,e});
const QUESTION_BANK=[
Q('Rina said, “I am tired.”',['Rina said that she was tired.','Rina said that I was tired.','Rina told that she is tired.','Rina says that she was tired.'],0,'Past reporting verb said commonly triggers am → was and I → she.'),
Q('He said to me, “I am busy.”',['He said me that he was busy.','He told me that he was busy.','He told that I was busy.','He said that I am busy.'],1,'Tell normally takes the listener as an object: told me.'),
Q('The boys said, “We have finished our work.”',['The boys said that we had finished our work.','The boys said that they have finished their work.','The boys said that they had finished their work.','The boys told that they finished our work.'],2,'we → they, our → their, have → had.'),
Q('She said, “I play cricket.”',['She said that she played cricket.','She said that I played cricket.','She told that she plays cricket.','She said she play cricket.'],0,'Present Simple commonly backshifts to Past Simple.'),
Q('He said, “I saw the film.”',['He said that he sees the film.','He said that he had seen the film.','He said that he has seen the film.','He told that I had seen the film.'],1,'Past Simple commonly backshifts to Past Perfect.'),
Q('Ravi said, “I will help you.”',['Ravi said that he would help me.','Ravi said that I will help him.','Ravi told that he would help you.','Ravi said that he helps me.'],0,'will → would; I → he; you → me from Ravi’s viewpoint.'),
Q('She said, “I can swim.”',['She said that she could swim.','She said that I could swim.','She told that she can swam.','She said that she can swimming.'],0,'can commonly backshifts to could after past reporting.'),
Q('He said, “I am leaving today.”',['He said that he is leaving today.','He said that I was leaving that day.','He said that he was leaving that day.','He told that he was leaving tomorrow.'],2,'am → was and today → that day.'),
Q('She said, “I will come tomorrow.”',['She said that she would come the next day.','She said that I will come tomorrow.','She told that she would come yesterday.','She said that she will came next day.'],0,'will → would and tomorrow → the next day.'),
Q('Ravi said, “I live here.”',['Ravi said that he lives here.','Ravi said that he lived there.','Ravi told that I lived there.','Ravi said that he had lived tomorrow.'],1,'I → he, present → past in the past-reporting pattern, here → there.'),
Q('He asked, “Are you ready?”',['He asked if I was ready.','He asked if was I ready.','He asked that I was ready.','He said if I am ready.'],0,'Yes/no question → if + statement order.'),
Q('She asked, “Do you know him?”',['She asked did I know him.','She asked whether I knew him.','She told whether I knew him.','She asked whether did I know him.'],1,'Do-support disappears; use statement order.'),
Q('He asked, “Where do you live?”',['He asked where did I live.','He asked where I lived.','He asked where do I live.','He told where I lived.'],1,'Wh-word stays; reported clause uses statement order.'),
Q('The teacher asked, “When did you finish?”',['The teacher asked when did I finish.','The teacher asked when I had finished.','The teacher told when I finished.','The teacher asked when had I finished.'],1,'Past question can backshift did + finish to had finished.'),
Q('The teacher said, “Sit down.”',['The teacher said the students sit down.','The teacher told the students to sit down.','The teacher asked the students sat down.','The teacher told to the students sit down.'],1,'Command → told + object + to + V1.'),
Q('Mother said to me, “Open the door.”',['Mother told me to open the door.','Mother said me open the door.','Mother told to open me the door.','Mother asked that I opened the door.'],0,'Direct command becomes told + object + to + V1.'),
Q('The teacher said, “Do not talk.”',['The teacher told the students do not talk.','The teacher told the students not to talk.','The teacher said the students not talk.','The teacher asked the students did not talk.'],1,'Negative command → not to + V1.'),
Q('He said, “Let us go.”',['He commanded that we went.','He suggested that we should go.','He told us go.','He asked whether we went.'],1,'Let us commonly introduces a suggestion.'),
Q('The teacher said, “The Earth is round.”',['The teacher said that the Earth was round.','The teacher said that the Earth is round.','The teacher told that the Earth were round.','The teacher said that the Earth has rounded.'],1,'A universal truth may remain in the present.'),
Q('Which is correct?',['He asked where did I live.','He asked where I lived.','He asked where do I lived.','He told where did I live.'],1,'Reported questions use statement order.'),
Q('Which is correct?',['She told that she was tired.','She told me that she was tired.','She said me that she was tired.','She told me that I was tired.'],1,'Tell requires an object in this pattern.'),
Q('“You are late,” Amit said to me.',['Amit said that I was late.','Amit told me that I was late.','Amit told me that he was late.','Amit says that I am late.'],1,'you changes to I from the listener’s viewpoint; said to → told.'),
Q('“I have finished,” she said.',['She said that she had finished.','She said that I had finished.','She told that she has finished.','She says that she had finished.'],0,'have finished → had finished in the school backshift pattern.'),
Q('“I was ill,” he said.',['He said that he is ill.','He said that he had been ill.','He told that I was ill.','He said that he was ill tomorrow.'],1,'Past be commonly backshifts to Past Perfect: had been.'),
Q('“I will see you next week,” Rina said.',['Rina said that she would see me the following week.','Rina said that I will see her next week.','Rina told that she would see you tomorrow.','Rina said that she saw me next week.'],0,'will → would; you → me; next week shifts with viewpoint.'),
Q('“Can you help me?” he asked.',['He asked if I could help him.','He asked that I can help him.','He asked if could I help him.','He told me if I could help.'],0,'Yes/no question → if + statement order; can → could.'),
Q('“Why are you crying?” mother asked me.',['Mother asked me why was I crying.','Mother asked me why I was crying.','Mother told me why I was crying.','Mother asked me why did I cry.'],1,'Wh-question keeps why but uses statement order.'),
Q('“Please wait for me,” she said to him.',['She told him to wait for her.','She said him to wait for me.','She asked him not to wait.','She told to him that he waits.'],0,'A request can be reported as asked/told + object + to + V1; pronoun changes to her.'),
Q('“Do not touch this,” the guard said to us.',['The guard told us not to touch that.','The guard said us not touching this.','The guard told to us do not touch that.','The guard asked that we did not touch this.'],0,'Negative command + pronoun/time/place viewpoint: not to touch that.'),
Q('“We are going now,” they said.',['They said that they were going then.','They said that we are going now.','They told that they were going today.','They said that they had gone now.'],0,'we → they; are → were; now → then.'),
Q('Which reporting verb best fits a command?',['asked','told','wondered','replied'],1,'Told + object + to is the standard school pattern for commands.'),
Q('Which reporting verb best fits a question?',['asked','ordered','suggested','exclaimed'],0,'Questions are commonly reported with asked.'),
Q('A reported yes/no question commonly uses…',['that','if/whether','to','because'],1,'Use if or whether.'),
Q('A reported Wh-question keeps…',['question inversion','the Wh-word and statement order','do/does support','quotation marks'],1,'Keep where/why/when/how etc., then use statement order.'),
Q('In reported speech, “now” may become…',['then','tomorrow','yesterday','there'],0,'now → then when the viewpoint changes.'),
Q('In reported speech, “here” may become…',['today','then','there','that day'],2,'here → there when place viewpoint changes.'),
Q('“She says, ‘I am ready.’” →',['She says that she was ready.','She says that she is ready.','She said that she is ready.','She tells that I am ready.'],1,'With present reporting verb says, backshift is not required in the ordinary pattern.'),
Q('Which sentence preserves universal truth correctly?',['He said that water boiled at 100°C.','He said that water boils at 100°C.','He told that water boiling.','He said that water will boil yesterday.'],1,'A still-valid general truth can remain present.'),
Q('“Let’s study together,” Rina said.',['Rina suggested that we should study together.','Rina told that we study together.','Rina asked if we studied together.','Rina ordered us studied together.'],0,'Let’s expresses a suggestion.'),
Q('Which is the correct transformation? “He said to me, ‘I will help you.’”',['He told me that he would help me.','He told me that I would help him.','He said me that he will help me.','He told that he would help you.'],0,'said to → told; I → he; will → would; you → me.'),
Q('Which is the best final audit for narration?',['Only tense','Only pronouns','Reporting verb + pronoun + tense + time/place + word order + meaning','Only quotation marks'],2,'Narration transformation is a system, not a single-word change.'),
Q('“He asked, ‘Can you swim?’” →',['He asked if I could swim.','He asked if could I swim.','He told me that I can swim.','He asked that I swam.'],0,'can → could and question order becomes statement order.'),
Q('“The teacher said, ‘Do not waste time.’” →',['The teacher told the students not to waste time.','The teacher said the students do not waste time.','The teacher told the students to not wasting time.','The teacher asked the students did not waste time.'],0,'Negative command → told + object + not to + V1.'),
Q('“She said, ‘I saw him yesterday.’” →',['She said that she had seen him the previous day.','She said that she saw him tomorrow.','She told that I had seen him yesterday.','She said that she has seen him the next day.'],0,'Past event and yesterday commonly backshift to had seen and the previous day.'),
Q('“Rina said to me, ‘I am happy today.’” →',['Rina told me that she was happy that day.','Rina said me that I was happy today.','Rina told that she is happy tomorrow.','Rina asked me if she was happy.'],0,'said to → told; I → she; am → was; today → that day.')
];

const bankFor=mode=>mode==='practice'?QUESTION_BANK.slice(0,15):mode==='challenge'?[...QUESTION_BANK.slice(15,27),...QUESTION_BANK.slice(36,41)]:QUESTION_BANK;

export default function EnglishReportedSpeechTopic({onBack=()=>{},addXp=()=>{},finishSession=()=>{}}){
 const[lesson,setLesson]=useState(0),[mode,setMode]=useState('learn');
 const bank=useMemo(()=>bankFor(mode),[mode]);
 const start=m=>{setMode(m);setLesson(0);window.scrollTo({top:0,behavior:'smooth'});};
 if(mode!=='learn')return <EnglishTimedQuiz title="Reported Speech / Narration" mode={mode} getBank={bankFor} onModeChange={start} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession}/>;
 const l=LESSONS[lesson];
 return <main className="ers-wrap">
  <header className="ers-header"><button onClick={onBack}>← Language & Skills</button><span>ENGLISH • GRAMMAR • REPORTED SPEECH</span></header>
  <section className="ers-hero"><div className="ers-hero-main"><span className="ers-kicker">MASTER NARRATION STEP BY STEP</span><h1>Reported Speech</h1><p>Learn statements, questions, commands, pronoun changes, backshift, time/place changes, exceptions and exam-level transformations.</p><div className="ers-rule"><b>TYPE FIRST</b><b>CHANGE VIEWPOINT</b><b>CHECK TENSE</b><b>PRESERVE MEANING</b></div></div><aside className="ers-side"><strong>EXAM CONTROL</strong><div>Statements</div><div>Questions</div><div>Commands</div><div>Special cases</div></aside></section>
  <nav className="ers-modes"><button className="active" onClick={()=>setMode('learn')}>Learn</button><button onClick={()=>start('practice')}>Practice</button><button onClick={()=>start('challenge')}>Challenge</button><button onClick={()=>start('test')}>Final Test</button></nav>
  <div className="ers-learning"><aside className="ers-map"><div className="ers-map-title">18 LESSONS</div>{LESSONS.map((x,i)=><button key={x.id} className={i===lesson?'active':''} onClick={()=>{setLesson(i);window.scrollTo({top:0,behavior:'smooth'})}}><em>{x.id}</em><div><strong>{x.title}</strong><small>{x.group}</small></div></button>)}</aside>
   <section className="ers-lesson"><div className="ers-lesson-top"><span>{l.group}</span><b>LESSON {l.id}</b></div><h2>{l.title}</h2><p className="ers-meaning">{l.meaning}</p><div className="ers-hindi"><strong>हिंदी में समझें:</strong> {l.simple}</div><div className="ers-structure">{l.structure}</div><div className="ers-examples">{l.examples.map((ex,i)=><article className="ers-example" key={i}><strong>{ex[0]}</strong><p>{ex[1]}</p></article>)}</div><div className="ers-footer"><button disabled={lesson===0} onClick={()=>setLesson(i=>i-1)}>← Previous</button><button disabled={lesson===LESSONS.length-1} onClick={()=>setLesson(i=>i+1)}>Next Lesson →</button></div></section>
  </div>
 </main>;
}
