import React,{useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishInformalLetterTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Informal Letter क्या है?',simple:'Informal letter मित्र, भाई-बहन या किसी close person को personal बात, अनुभव, खबर या शुभकामना बताने के लिए लिखा जाता है।',meaning:'Informal writing is personal communication, so the tone can be warm and natural.',structure:'sender address → date → salutation → friendly opening → main message → closing → name',examples:['मित्र को छुट्टियों का अनुभव बताना।','भाई/बहन को परीक्षा की तैयारी के बारे में लिखना।','मित्र को जन्मदिन की शुभकामना देना।'],clue:'जिससे personal relationship हो, उसके लिए friendly tone रखो; official language की जरूरत नहीं।'},
{n:'02',group:'FOUNDATION',title:'Formal vs Informal पहचानो',simple:'Formal letter official person या institution को लिखा जाता है। Informal letter अपने लोगों को लिखा जाता है।',meaning:'Relationship decides the register.',structure:'Principal/Editor/Officer → formal | Friend/Family → informal',examples:['Principal को complaint → formal','Friend को picnic के बारे में → informal','Brother को exam advice → informal'],clue:'Recipient और relationship पहले पहचानो, फिर tone चुनो।'},
{n:'03',group:'FORMAT',title:'Sender’s Address + Date',simple:'Informal letter में आम तौर पर ऊपर sender का address और उसके नीचे date लिखी जाती है।',meaning:'These details tell the reader where and when the letter was written.',structure:'Address → Date',examples:['24, Rajendra Nagar\nPatna, Bihar – 800016','15 September 2026'],clue:'Address छोटा, clear और consistent रखो।'},
{n:'04',group:'FORMAT',title:'Salutation कैसे लिखें',simple:'Informal letter में relationship के अनुसार friendly salutation चुनी जाती है।',meaning:'The opening should sound natural for the person receiving the letter.',structure:'Dear + name/relationship',examples:['Dear Rohan,','Dear Brother,','Dear Anu,'],clue:'“Respected Sir/Madam” सामान्य informal letter के लिए सही choice नहीं है।'},
{n:'05',group:'OPENING',title:'Friendly opening',simple:'शुरुआत में हाल-चाल पूछ सकते हो और फिर letter का reason बता सकते हो।',meaning:'A brief personal opening creates a natural connection before the main message.',structure:'greeting → well-being → reason for writing',examples:['I hope you are fine. I am writing to tell you about…','How are you? I hope your studies are going well.'],clue:'Opening बहुत लंबी मत करो; जल्दी main topic पर आओ।'},
{n:'06',group:'BODY',title:'Main message लिखना',simple:'मुख्य भाग में घटना, अनुभव, सूचना, advice या personal news साफ क्रम में लिखो।',meaning:'The body should contain the actual personal message.',structure:'what happened → details → feelings/opinion → useful information',examples:['Our school picnic was exciting because…','I have started a new study routine…','You should visit us during the holidays.'],clue:'एक paragraph में बहुत सारे unrelated points मत मिलाओ।'},
{n:'07',group:'STYLE',title:'Friendly लेकिन clear language',simple:'Informal का अर्थ careless writing नहीं है। भाषा natural, warm और easy हो सकती है, लेकिन spelling और grammar फिर भी सही रखें।',meaning:'Informal register allows warmth without sacrificing clarity.',structure:'natural vocabulary + short clear sentences + personal tone',examples:['I was really happy to hear your news.','You will surely enjoy the trip.'],clue:'Chat abbreviations जैसे “u”, “btw”, “gr8” exam answer में avoid करो।'},
{n:'08',group:'STYLE',title:'Feelings और personal details',simple:'Informal letter में खुशी, उत्साह, चिंता, surprise या gratitude जैसे feelings naturally लिख सकते हो।',meaning:'Personal writing can include emotion and opinion.',structure:'event → feeling → reason',examples:['I felt very proud when our team won.','I was surprised to see the new science lab.'],clue:'Feeling के साथ reason लिखने से answer ज्यादा meaningful बनता है।'},
{n:'09',group:'CLOSING',title:'Closing कैसे करें',simple:'अंत में मिलने, reply करने या greetings भेजने की बात लिखकर friendly close किया जा सकता है।',meaning:'The ending should sound personal and connected to the relationship.',structure:'final thought → reply/meeting → good wishes → name',examples:['Please write back soon.','Give my regards to uncle and aunty.','See you during the holidays.'],clue:'Formal “Yours faithfully” की जगह relationship के हिसाब से natural closing चुनो।'},
{n:'10',group:'APPLICATION',title:'Common informal-letter purposes',simple:'Exam में experience, invitation, congratulations, advice, apology, thanks, news और holiday plans जैसे topics आ सकते हैं।',meaning:'Purpose decides what details belong in the body.',structure:'experience → event + feelings | advice → problem + suggestions | invitation → event + date + place',examples:['Invitation to a birthday celebration','Advice to a friend before exams','Letter describing a school trip'],clue:'Purpose पहचानकर उसी से जुड़े 3–4 points पहले note कर लो।'},
{n:'11',group:'PLANNING',title:'Question को 4 points में तोड़ो',simple:'Recipient, purpose, key details और closing idea लिखकर फिर draft शुरू करो।',meaning:'Quick planning prevents missing important details.',structure:'WHO → WHY → 3 KEY DETAILS → HOW TO CLOSE',examples:['Who: friend | Why: school trip | Details: place, activities, best moment | Close: invite reply'],clue:'पहले points लिखने में 1 मिनट लगाओ; पूरा answer ज्यादा organised बनेगा।'},
{n:'12',group:'ERROR CONTROL',title:'Common mistakes',simple:'बहुत formal tone, chat language, missing date, बहुत कम details, repeated sentences और weak closing common mistakes हैं।',meaning:'The main risk is mismatch between personal purpose and writing style.',structure:'relationship check → format check → content check → language check',examples:['Too formal: “I hereby request…”','Too casual: “Bro, u gotta come ASAP.”','Better: “I really want you to visit us this summer.”'],clue:'Natural लिखो, लेकिन exam-standard English बनाए रखो।'},
{n:'13',group:'GUIDED BUILD',title:'एक letter step-by-step बनाओ',simple:'Address और date लिखो, फिर salutation, opening, 2–3 body paragraphs, closing और name जोड़ो।',meaning:'A repeatable sequence makes drafting easier under exam pressure.',structure:'format → opening → main message → personal feeling/detail → closing',examples:['Topic: school picnic → place → activities → favourite moment → invitation/reply'],clue:'हर paragraph का एक clear job रखो।'},
{n:'14',group:'EDITING',title:'Letter को edit करना',simple:'Draft के बाद check करो कि tone personal है, सभी question-points cover हैं और grammar साफ है।',meaning:'Editing improves clarity and prevents avoidable mistakes.',structure:'format → relevance → tone → grammar → punctuation',examples:['Check: address ✓ date ✓ salutation ✓ reason ✓ details ✓ close ✓ name'],clue:'Question को फिर से पढ़कर हर instruction पर tick लगाओ।'},
{n:'15',group:'FINAL AUDIT',title:'Final Informal Letter Audit',simple:'Submit करने से पहले पूछो: सही person को लिखा? Friendly tone है? सभी points आए? Opening और closing natural हैं? Grammar ठीक है?',meaning:'A simple final audit protects marks without making the answer complicated.',structure:'WHO → WHY → DETAILS → FEELING/INFO → FRIENDLY CLOSE',examples:['WHO: Riya','WHY: tell about summer camp','DETAILS: place + activities','FEELING: what I enjoyed','CLOSE: write back soon'],clue:'Fancy vocabulary से ज्यादा natural, relevant और organised writing important है।'}
];

const BANKS={
practice:[
['Which recipient is most suitable for an informal letter?',['a close friend','the District Magistrate','the newspaper editor','the school principal'],0,'Informal letters are normally written to people with whom we have a personal relationship.'],
['Which salutation fits a letter to a friend?',['Dear Rohan,','Respected Sir/Madam,','To the Editor,','Dear Sir/Madam,'],0,'A friend is a personal recipient, so a friendly salutation such as Dear Rohan is suitable.'],
['Which opening sounds natural in an informal letter?',['I hope you are fine. I am writing to tell you about our trip.','I hereby request you to take action.','Through this letter, I wish to complain.','I write to bring this official matter to your notice.'],0,'Informal writing can begin with a brief personal greeting and the reason for writing.'],
['Which should normally come after the sender address?',['the date','the signature','the final greeting','the score'],0,'The date usually follows the sender address.'],
['Which sentence is informal but still exam-appropriate?',['I was really excited to meet my old friends.','Bro u gotta come ASAP.','I hereby submit my request.','Kindly take necessary action.'],0,'Personal feeling is appropriate, while chat abbreviations should be avoided in exam writing.'],
['A letter inviting a friend to your birthday should mainly include…',['event details and an invitation','an official complaint','a subject line for an authority','office reference numbers'],0,'The reader needs the event details and a clear invitation.']
],
challenge:[
['A student writes “Respected Sir” to a close friend. What is the main problem?',['The tone does not match the relationship','The address is too short','The date is missing from the middle paragraph','The vocabulary is too simple'],0,'The recipient is a friend, so the salutation should be friendly rather than official.'],
['Which plan is best for “Write to your friend describing a school picnic”?',['place → activities → best moment → feeling','complaint → evidence → action request','designation → subject → official request','definition → rule → conclusion'],0,'A personal experience letter needs details of the event and your response to it.'],
['Which sentence best closes an informal letter to a cousin?',['Write back soon and give my regards to everyone at home.','I request you to take immediate action.','Yours faithfully,','I shall be grateful for your consideration.'],0,'The first option is natural and personal for a cousin.'],
['What should you avoid even in an informal exam letter?',['chat abbreviations and slang','personal feelings','friendly language','a warm closing'],0,'Informal does not mean careless; exam writing should remain clear and standard.'],
['Your friend is nervous about exams. Which body point is most useful?',['give two practical study suggestions and encouragement','describe a municipal problem','add an office address','write a newspaper headline'],0,'Advice letters should focus on the friend’s problem, useful suggestions and encouragement.']
],
test:[
['What is the main purpose of an informal letter?',['personal communication','official complaint','public notice','business contract'],0,'The defining feature is personal communication.'],
['Which is the best salutation for a sister?',['Dear Sister,','Respected Madam,','To the Principal,','Sir/Madam,'],0,'A family member is a personal recipient.'],
['Which sequence is most suitable?',['address → date → salutation → body → closing','subject → receiver → body → official seal','heading → notice → signature → date','receiver address → subject → salutation only'],0,'This sequence matches the simple informal-letter structure taught in the lesson.'],
['Which sentence is most appropriate in an exam?',['I was very happy to hear your good news.','u were gr8 yesterday','ASAP bro!!!','I hereby inform you that…'],0,'The first sentence is friendly, grammatical and suitable for exam writing.'],
['For an invitation letter, which details are important?',['date, place and reason for the invitation','office file number and designation','complaint evidence only','newspaper publication date'],0,'An invitation should tell the reader when, where and what the event is.'],
['Which closing is best for a friend?',['Please write back soon.','I await your official response.','Yours faithfully,','Kindly take necessary action.'],0,'The first closing is personal and natural.'],
['If the question asks for feelings, you should…',['state the feeling and explain why','skip the body','use only formal phrases','write unrelated information'],0,'Feelings become clearer when supported by a brief reason or event.'],
['What is the biggest style error in informal writing?',['using an official tone for a personal relationship','being warm','giving relevant details','asking the reader to reply'],0,'The tone should match the personal relationship.']
]};

const getBank=m=>BANKS[m]||BANKS.practice;

const SAMPLES=[
{title:'Example 1 — Friend को school trip के बारे में',topic:'Write to your friend describing your school trip.',parts:['24, Rajendra Nagar\nPatna, Bihar – 800016','15 September 2026','Dear Rohan,','I hope you are fine. I am writing to tell you about our school trip to Rajgir last week.','We visited the ropeway, the hot springs and a museum. The best part was travelling with our classmates and taking many photographs. I enjoyed the trip because I learnt many new things outside the classroom.','I wish you had been with us. Do write back and tell me about your recent activities.','Yours lovingly,\nAmit']},
{title:'Example 2 — Sister को exam advice',topic:'Write to your sister giving her advice for her annual examination.',parts:['24, Rajendra Nagar\nPatna, Bihar – 800016','15 September 2026','Dear Neha,','I hope your studies are going well. Do not worry too much about the coming examination. I am writing to share a few simple suggestions.','Make a small daily timetable and revise your difficult topics first. Take short breaks and practise previous questions regularly. Most importantly, sleep well and stay confident.','I am sure you will do your best. Please write to me about your preparation.','Yours affectionately,\nAmit']},
{title:'Example 3 — Friend को birthday invitation',topic:'Write to your friend inviting him to your birthday celebration.',parts:['24, Rajendra Nagar\nPatna, Bihar – 800016','15 September 2026','Dear Rohan,','How are you? I am happy to tell you that my birthday is on 20 September. I am organising a small celebration at my home in the evening.','The programme will begin at 6 p.m. We will have games, music and dinner with a few close friends. I really want you to be there because your presence will make the evening special.','Please come on time. I am waiting to celebrate the day with you.','Yours lovingly,\nAmit']}
];

const SUBJECTIVE=[
'Write an informal letter to your friend describing a memorable school picnic.','Write a letter to your brother or sister giving advice for the annual examination.','Write a letter to your friend inviting them to your birthday celebration.','Write a letter to your cousin describing how you spent your summer vacation.','Write a letter to a friend congratulating them on winning a school competition.','Write a letter to your friend thanking them for a useful gift or book.','Write a letter to a cousin apologising for missing an important family function.','Write a letter to a friend describing a new hobby you have started and why you enjoy it.'
];

export default function EnglishInformalLetterTopic({addXp=()=>{},finishSession=()=>{},onBack=()=>{}}){
 const[lesson,setLesson]=useState(0);const[mode,setMode]=useState('learn');
 const progress=Math.round(((lesson+1)/LESSONS.length)*100);const current=LESSONS[lesson];const quiz=useMemo(()=>getBank(mode),[mode]);
 const back=()=>{const p=new URLSearchParams();p.set('page','language-skills');p.set('subject','english');p.set('languageSkills','1');p.delete('topic');p.delete('mode');const url=`${window.location.pathname}?${p.toString()}${window.location.hash||''}`;window.history.pushState({},'',url);window.dispatchEvent(new PopStateEvent('popstate'));};
 return <main className="eilt-shell">
  <header className="eilt-hero"><div><button type="button" className="eilt-back" onClick={back}>← Writing / Language & Skills</button><span className="eilt-kicker">CLASS 9 • ENGLISH • WRITING</span><h1>Informal Letter</h1><p>Easy format • friendly tone • planning • examples • exam practice</p></div><div className="eilt-stat"><strong>{mode==='learn'?LESSONS.length:quiz.length}</strong><span>{mode==='learn'?'guided lessons':'timed questions'}</span></div></header>
  <nav className="eilt-modebar" aria-label="Informal Letter modes"><button className={mode==='learn'?'active':''} onClick={()=>setMode('learn')}>Learn</button><button className={mode==='practice'?'active':''} onClick={()=>setMode('practice')}>Practice</button><button className={mode==='challenge'?'active':''} onClick={()=>setMode('challenge')}>Challenge</button><button className={mode==='test'?'active':''} onClick={()=>setMode('test')}>Final Test</button></nav>
  {mode==='learn'?<>
   <section className="eilt-progress"><div><span>Lesson {lesson+1} of {LESSONS.length}</span><b>{progress}% complete</b></div><div className="eilt-track"><i style={{width:`${progress}%`}}/></div></section>
   <section className="eilt-layout"><aside className="eilt-map"><div className="eilt-map-title">Lesson map</div>{LESSONS.map((item,i)=><button key={item.n} className={i===lesson?'selected':''} onClick={()=>setLesson(i)}><span>{item.n}</span><div><strong>{item.title}</strong><small>{item.group}</small></div></button>)}</aside>
    <article className="eilt-lesson"><div className="eilt-badge">{current.group}</div><h2>{current.title}</h2><p className="eilt-simple">{current.simple}</p><div className="eilt-grid"><section><h3>Core idea</h3><p>{current.meaning}</p></section><section><h3>Exam structure</h3><p>{current.structure}</p></section></div><section className="eilt-examples"><h3>Examples / application</h3>{current.examples.map((x,i)=><div key={i}>{x}</div>)}</section><section className="eilt-clue"><strong>Exam clue</strong><p>{current.clue}</p></section><div className="eilt-lesson-nav"><button onClick={()=>setLesson(v=>Math.max(0,v-1))} disabled={lesson===0}>← Previous</button><button onClick={()=>setLesson(v=>Math.min(LESSONS.length-1,v+1))} disabled={lesson===LESSONS.length-1}>{lesson===LESSONS.length-1?'Final lesson':'Next lesson →'}</button></div></article>
   </section>
   <section className="eilt-models"><div className="eilt-models-head"><span>LEARN • MODEL WRITING</span><h2>3 Easy Informal Letter Examples</h2><p>Notice the friendly tone, simple sentences and clear paragraph order.</p></div><div className="eilt-model-grid">{SAMPLES.map((s,i)=><article key={s.title}><div className="eilt-model-head"><span>EXAMPLE {i+1}</span><h3>{s.title}</h3><p>{s.topic}</p></div><div className="eilt-letter">{s.parts.map((part,j)=><p key={j} className={j===2?'eilt-salutation':j===s.parts.length-1?'eilt-close':''}>{part}</p>)}</div></article>)}</div></section>
   <section className="eilt-subjective"><span>WRITE YOUR OWN</span><h2>8 Subjective Practice Questions</h2><p>These are separate writing tasks. They do not affect Practice, Challenge or Final Test scores.</p><div className="eilt-question-grid">{SUBJECTIVE.map((q,i)=><article key={q}><b>Q{i+1}</b><p>{q}</p><small>Check: format • friendly tone • relevant details • clear closing</small></article>)}</div></section>
  </>:<EnglishTimedQuiz title="Informal Letter" mode={mode} getBank={getBank} onModeChange={setMode} onBack={()=>{setMode('learn');setLesson(0)}} addXp={addXp} finishSession={finishSession}/>} 
 </main>;
}
