import React,{useMemo,useState,useEffect}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishCompositionTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'What is composition writing?',simple:'A composition is a complete piece of writing built around a clear purpose. It may tell a story, describe a scene, narrate an experience or develop an imaginative situation.',hindi:'Composition का मतलब सिर्फ sentences लिखना नहीं है। इसमें एक clear purpose, connected ideas और proper beginning–middle–end चाहिए।',meaning:'Composition is purposeful, connected writing rather than a collection of unrelated sentences.',structure:'purpose → plan → opening → development → closing',examples:['Narrative composition: an event is developed through sequence.','Descriptive composition: a scene is developed through selected details.','Imaginative composition: an invented situation is made believable through action and description.'],clue:'Before writing, identify what the question asks you to create and what the reader should understand or experience.'},
{n:'02',group:'PLANNING',title:'Read the prompt like a writer',simple:'Underline the action word and the limits of the task. Notice whether you must narrate, describe, continue a story, use given hints or write from a situation.',hindi:'Question में command word पकड़ो—describe, narrate, continue, imagine, write from hints आदि। यही structure तय करेगा।',meaning:'The prompt controls the purpose, content and form of the composition.',structure:'command word → topic → limits → writing purpose',examples:['“Describe” → focus on scene and sensory detail.','“Narrate” → focus on events and sequence.','“Complete the story” → respect the given opening and continue logically.'],clue:'Do not force one memorised composition into every question; adapt the plan to the exact prompt.'},
{n:'03',group:'PLANNING',title:'Central idea + writing direction',simple:'Choose one clear direction before drafting. The central idea controls which events, details and sentences belong.',hindi:'एक main direction तय करो। जो detail उस direction को help नहीं करती, उसे हटाना बेहतर है।',meaning:'A central idea prevents the composition from drifting.',structure:'topic/situation + central idea = writing direction',examples:['Lost wallet story → honesty becomes the central direction.','Rainy market description → crowded movement and changing atmosphere become the focus.'],clue:'Try to complete this sentence before drafting: “My composition is mainly about…”'},
{n:'04',group:'STRUCTURE',title:'Strong openings',simple:'The opening should create immediate orientation or interest. Start with action, setting, a striking observation, a problem or a natural scene instead of unnecessary background.',hindi:'Opening में reader को जल्दी scene या situation में ले जाओ। बहुत लंबी introduction से बचो।',meaning:'An effective opening establishes situation and encourages the reader to continue.',structure:'hook → setting/situation → direction',examples:['Action: “The moment the bell rang, everyone rushed towards the gate.”','Setting: “The village was unusually quiet that winter morning.”','Problem: “I noticed the envelope only after the train had begun to move.”'],clue:'The first paragraph should make the reader know where they are, what is happening or what matters.'},
{n:'05',group:'NARRATION',title:'Sequence of events',simple:'Narrative writing needs a clear chain of events. Use time markers only when useful and make each event cause, change or prepare for the next.',hindi:'Story में events का order clear रखो: पहले क्या हुआ, फिर क्या हुआ, और उसके कारण आगे क्या बदला।',meaning:'Narrative coherence comes from meaningful event sequence, not merely many events.',structure:'situation → event → complication → response → outcome',examples:['First problem → attempt to solve → unexpected complication → final solution.'],clue:'Every major event should change the situation in some way; remove events that do nothing.'},
{n:'06',group:'NARRATION',title:'Setting and atmosphere',simple:'A setting tells the reader when and where the action happens. Atmosphere adds the emotional feel of the place through carefully selected details.',hindi:'Setting = कहाँ/कब। Atmosphere = scene कैसा feel होता है। दोनों को relevant details से बनाओ।',meaning:'Setting anchors the composition; atmosphere shapes how the scene feels.',structure:'place + time + sensory detail + atmosphere',examples:['Place: empty railway platform.','Time: just before sunrise.','Atmosphere: cold air, dim lights and long shadows.'],clue:'Do not list every object in the scene; choose details that support the mood or action.'},
{n:'07',group:'DESCRIPTION',title:'Show through the senses',simple:'Description becomes stronger when the reader can see, hear, smell, feel or sometimes taste the scene. Use precise details instead of a long list of adjectives.',hindi:'सिर्फ “beautiful, nice, big” मत लिखो। Sense-based detail दो ताकि reader scene imagine कर सके।',meaning:'Sensory detail creates a vivid mental picture.',structure:'object → specific feature → sensory effect',examples:['The wet road reflected the yellow streetlights.','The smell of fresh earth rose after the rain.','A distant whistle broke the silence.'],clue:'One precise sensory detail is often stronger than three general adjectives.'},
{n:'08',group:'DESCRIPTION',title:'Specific vocabulary',simple:'Prefer exact verbs and nouns. Strong compositions use language that communicates movement, shape, sound and feeling without becoming unnatural.',hindi:'Difficult words भरने से quality नहीं बढ़ती। Exact और natural vocabulary ज्यादा useful है।',meaning:'Specific vocabulary improves clarity and imagery.',structure:'precise noun + precise verb + controlled modifier',examples:['“The boy ran” → “The boy sprinted towards the gate.”','“The wind was strong” → “A sharp wind rattled the windows.”'],clue:'Use a stronger word only when it is accurate; do not decorate every sentence.'},
{n:'09',group:'CHARACTER',title:'Character and point of view',simple:'A composition becomes believable when actions and reactions reveal the character. First person can feel personal; third person can create a wider viewpoint.',hindi:'Character को सिर्फ “he was brave” मत कहो। उसके actions और choices से quality दिखाओ।',meaning:'Characterisation is created through actions, thoughts, speech and reactions.',structure:'situation → reaction → choice → consequence',examples:['Instead of saying “She was honest”, show her returning a lost wallet.','Use thoughts carefully in first-person narration.'],clue:'Let the reader infer character from what the person does and decides.'},
{n:'10',group:'PLOT',title:'Conflict and turning point',simple:'A strong narrative usually contains a problem, challenge or decision that changes the direction of events. The turning point is where the story moves towards its outcome.',hindi:'Story को interesting बनाने के लिए challenge या problem चाहिए। Turning point पर situation बदलती है।',meaning:'Conflict gives narrative movement; a turning point creates meaningful change.',structure:'goal → obstacle → escalation → turning point → resolution',examples:['A student loses an important document before an exam.','A traveller realises the wrong train has been taken.'],clue:'A story without a meaningful problem may read like a list of events.'},
{n:'11',group:'DIALOGUE',title:'Dialogue inside a composition',simple:'Dialogue can reveal character, move the plot and make a scene feel immediate. Keep it purposeful and punctuate it correctly.',hindi:'Dialogue तभी डालो जब उससे character, information या story आगे बढ़े। हर line में conversation जरूरी नहीं।',meaning:'Dialogue should do narrative work rather than act as filler.',structure:'speaker → purposeful line → response/action',examples:['“Are you sure this is the right road?” Ravi asked.','“Yes,” Meena replied, pointing towards the signboard.'],clue:'After important dialogue, an action or reaction can show what changed.'},
{n:'12',group:'DEVELOPMENT',title:'Building the middle',simple:'The middle is where the main situation develops. Add consequences, obstacles, details, choices or discoveries rather than repeating the opening.',hindi:'Middle में opening को repeat मत करो। यहाँ problem grow हो, details develop हों और character decisions लें।',meaning:'Development means the situation changes as the composition progresses.',structure:'development → complication → response → new information',examples:['The clue seems useful, but it creates a second problem.','The character tries one solution and learns why it fails.'],clue:'Ask “What changes here?” after each paragraph. If nothing changes, revise it.'},
{n:'13',group:'COHERENCE',title:'Transitions and paragraphing',simple:'Break long compositions into purposeful paragraphs. Use natural transitions for time, contrast, cause or change of focus.',hindi:'हर paragraph का एक clear function रखो। Transition ideas को जोड़ें, filler की तरह नहीं।',meaning:'Paragraphing gives the reader visible stages of the composition.',structure:'paragraph 1 → paragraph 2 → paragraph 3 → closing',examples:['Later that evening…','A few minutes afterwards…','However, the plan changed when…'],clue:'A new paragraph should usually signal a meaningful new stage, place, speaker focus or idea.'},
{n:'14',group:'CREATIVE CONTROL',title:'Imagination without losing logic',simple:'Creative writing can be unusual, but events still need internal logic. New situations, objects or characters should follow the rules established by the composition.',hindi:'Imaginative writing में creativity रखो, लेकिन story के अंदर rules consistent रहने चाहिए।',meaning:'Imagination works best when the invented world remains internally consistent.',structure:'creative premise → established rules → development → consequence',examples:['A mysterious letter can cause events, but its clues should remain consistent.','An invented object should have a believable limitation.'],clue:'Surprise the reader, but do not solve every problem with a sudden unexplained miracle.'},
{n:'15',group:'ENDING',title:'Resolution and final impression',simple:'The ending should resolve the main problem or give a satisfying final impression. It may reveal a lesson, consequence, realisation or emotional change.',hindi:'Ending में main situation का result दो। अचानक “and then I woke up” जैसे shortcuts तभी use करो जब question सच में dream story हो।',meaning:'A strong ending answers the main narrative question and leaves a clear impression.',structure:'turning point → consequence → resolution → final impression',examples:['The lost item is recovered because the character acts honestly.','The journey ends with a new understanding rather than a random event.'],clue:'Do not introduce a brand-new major problem in the final two lines.'},
{n:'16',group:'TASK TYPES',title:'Picture and visual-prompt composition',simple:'When a picture or visual situation is supplied, convert what you see into a coherent composition. Select significant details and infer only what is reasonable.',hindi:'Picture में दिखाई देने वाली important चीजों से story/description बनाओ। बिना आधार के बहुत बड़ा plot invent मत करो।',meaning:'Visual prompts require observation, selection and logical inference.',structure:'observe → select → infer → organise → write',examples:['Notice people, setting, action, time, objects and relationships.','Build a sequence from visible actions when the prompt is narrative.'],clue:'The picture is a starting point; your composition still needs a clear purpose and logical flow.'},
{n:'17',group:'EDITING',title:'Language, tense and mechanics',simple:'After drafting, check tense consistency, subject–verb agreement, articles, pronouns, punctuation, spelling and sentence boundaries. For narratives, past tense is common unless the task calls for another viewpoint.',hindi:'पहले ideas ठीक करो, फिर grammar audit करो। खासकर tense, articles, punctuation और spelling check करो।',meaning:'Editing converts a good draft into controlled exam writing.',structure:'content → organisation → grammar → vocabulary → spelling → punctuation',examples:['“He go” → “He goes” in present narration.','“Because he was late. He ran.” → “Because he was late, he ran.”'],clue:'Read the composition once only for meaning, then a second time only for language errors.'},
{n:'18',group:'EXAM CONTROL',title:'Length, layout and final audit',simple:'Respect the required length and keep the composition readable. Before submission, verify task, structure, development, coherence, ending and language accuracy.',hindi:'Final check में देखो: prompt पूरा किया? word limit सही? paragraphs clear? story/description complete? grammar सही?',meaning:'Exam control means completing the exact task within the required format and length.',structure:'task → plan → draft → revise → final audit',examples:['Check the prompt again.','Remove repetition.','Check paragraph breaks.','Count roughly to the required range.'],clue:'A concise, complete and accurate composition is stronger than a longer composition filled with repetition.'}
];

const MODELS=[
['Narrative','The Unexpected Package','I was returning home from school when I noticed a small brown package near the gate of the community library. It had no name or address on it. For a moment, I thought I should simply leave it where it was, but then I remembered the notice inside the library asking visitors to hand over lost property. I picked it up carefully and carried it to the librarian.\n\nThe librarian checked the package and found a phone number written on a slip of paper inside. She called the number and soon an anxious student arrived. He had been searching for the package since morning because it contained his project model for the next day’s exhibition.\n\nThe student thanked us repeatedly. I realised that returning something valuable does not require a grand gesture; it often begins with a small honest decision.'],
['Descriptive','A Busy Railway Platform','The railway platform seemed to wake up all at once. Porters moved quickly between passengers, vendors called out from their stalls and luggage rolled across the floor. A cool breeze passed through the open side of the station while the announcement system crackled above the noise.\n\nNear the tea stall, passengers waited with cups in their hands. Some checked the station clock every few minutes, while others watched the tracks in silence. Children pointed at the coaches whenever a train appeared in the distance. The smell of hot tea, the sound of footsteps and the repeated announcements created a restless but familiar atmosphere.\n\nWhen the train finally entered the platform, the waiting crowd became a moving stream of people. Within minutes, the platform had changed again, but the energy of the place remained.'],
['Personal Experience','A Lesson I Learned from a Mistake','I once believed that finishing a task quickly was always better than spending time checking it. That belief changed when I submitted a class assignment without reading it again. I had understood the topic correctly, but I had left two questions incomplete and made several careless errors.\n\nAt first, I felt disappointed because the work had taken a long time. Then my teacher asked me to compare the first draft with the corrected version. I noticed that most of the problems could have been found in a few minutes of careful review. The experience taught me that revision is not a sign that the first attempt was useless; it is a normal part of good work.\n\nSince then, I have developed the habit of checking important work before submitting it. A small final review can protect hours of effort.'],
['Story from Hints','The Missing Key','One evening, Rohan returned home and discovered that the key to the front door was missing. He checked his schoolbag twice, searched his pockets and retraced his steps to the bus stop. Nothing helped. As darkness grew, he began to worry.\n\nWhile thinking about where he had been during the afternoon, he remembered stopping at a roadside bookstall. He hurried back and asked the shopkeeper whether he had seen a small key. The shopkeeper pointed towards a bench. Rohan found the key underneath a newspaper where he had placed it while comparing two books.\n\nRohan thanked the shopkeeper and headed home. The incident was simple, but it taught him to keep important things in one fixed place instead of leaving them wherever he happened to be.'],
['Imaginative','The Day the School Bell Stopped','The school bell refused to ring one Monday morning. At first, nobody thought much about it. The teachers simply checked the clocks and continued their lessons. But after the usual lunch bell also remained silent, the entire school had to depend on handwritten notices and classroom announcements.\n\nThe unusual situation changed the rhythm of the day. Students became more alert because they could no longer rely on the familiar sound that told them when to move. Teachers planned transitions more carefully, and the office began repairing the system. By the afternoon, everyone had discovered that the bell had stopped because a small electrical fault had affected the control unit.\n\nWhen the repaired bell finally rang, the sound seemed surprisingly cheerful. The next morning, students arrived on time without being reminded. Perhaps the broken bell had taught them something useful about responsibility and routine.'],
['Picture-based','After the Heavy Rain','The storm had ended, but the neighbourhood still showed signs of the heavy rain. Water stood in shallow pools along the road, leaves covered the pavement and the sky remained grey. A few residents stepped outside to check their surroundings.\n\nNear the corner, two students noticed that rainwater had collected around a blocked drain. They called an adult for help and, together, cleared away the visible leaves and plastic waste without entering the water. A shopkeeper placed a warning sign near the wet area so that pedestrians could take another path.\n\nBy evening, the water level had fallen and the road became easier to use. The scene reminded everyone that small, sensible actions can make a difficult situation safer for the community.'],
['Dialogue-led','A Difficult Decision','“We have only ten minutes left,” Neha said, looking at the unfinished chart.\n\n“I know,” Aman replied. “We can either rush and submit a messy chart, or simplify the design and finish it properly.”\n\nThey looked at the remaining materials and decided to remove the decorative section that was taking too long. Aman rewrote the heading while Neha organised the information into three clear parts. Within a few minutes, the chart looked simpler but much easier to understand.\n\n“Sometimes the best solution is not to do more,” Neha said.\n\nAman smiled. “It is to choose what matters most.”\n\nThe next day, their teacher praised the clarity of the chart. The two students realised that good decisions often depend on priorities rather than pressure.'],
['Reflective','Why Reading Still Matters','Reading remains one of the simplest ways to extend learning beyond the classroom. A textbook may explain the required lesson, but a library book, biography, magazine article or carefully chosen story can introduce unfamiliar ideas and perspectives.\n\nRegular reading also teaches patience. Unlike a short message that can be understood in seconds, a longer text asks the reader to follow an idea across several pages. That habit can strengthen attention and make complex information easier to handle. Reading does not have to mean spending every free hour with a book; even a consistent daily period can be useful.\n\nFor students, the real value of reading is not only the number of pages completed. It is the habit of thinking, questioning and making connections. That habit can support learning in many subjects.']
];

const TRAPS=['Do not confuse composition with a list of disconnected events or descriptions.','Do not begin every story with the same memorised sentence.','Avoid sudden endings that solve the main problem without development.','Do not overload every sentence with difficult adjectives.','Keep narrative tense consistent unless there is a clear reason to shift it.','Use dialogue only when it adds character, information or movement.','Do not invent details that contradict the supplied picture, hints or situation.','Check spelling, punctuation, articles, agreement and sentence boundaries before submission.'];
const TASKS=['Write a narrative composition beginning: “The road was almost empty when I heard someone calling my name…”','Describe a crowded railway station just before a train arrives.','Write a composition on a mistake that taught you an important lesson.','Complete a story from these hints: lost key → search → unexpected helper → recovery → lesson.','Write an imaginative composition: “The day every clock in the town stopped.”','Write a picture-based composition about a community responding to heavy rain.','Write a dialogue-led composition about two students making a difficult choice.','Write a reflective composition on “Why good habits matter.”'];

const BANKS={practice:[
['Composition writing should mainly have…',['a clear purpose and connected development','random sentences','only difficult vocabulary','no ending'],0,'A composition is complete purposeful writing with connected ideas.'],
['The first step before drafting is usually to…',['understand the prompt','write the conclusion','add quotations','choose the longest words'],0,'The prompt defines the task and direction.'],
['A narrative composition mainly depends on…',['a meaningful sequence of events','a list of adjectives','only dialogue','random facts'],0,'Narration develops through connected events.'],
['A descriptive composition should emphasise…',['specific sensory details','only opinions','unrelated statistics','a formal letter format'],0,'Sensory detail helps create a clear picture.'],
['The setting tells the reader…',['when and where the situation happens','the final moral only','the writer’s marks','the question number'],0,'Setting anchors time and place.'],
['Which opening is strongest?',['The moment the bell rang, everyone rushed towards the gate.','There are many things in the world.','I am writing this composition now.','Once I decided that life was good.'],0,'It begins with action and immediate situation.'],
['A strong narrative event should usually…',['change or develop the situation','repeat the opening','add an unrelated fact','stop the story'],0,'Events should contribute to development.'],
['One precise sensory detail is often better than…',['many general adjectives','a clear verb','a relevant noun','a logical event'],0,'Specific detail is more effective than adjective overload.'],
['Character is best shown through…',['actions, choices and reactions','only the word “brave”','the title alone','the number of paragraphs'],0,'Behaviour provides evidence of character.'],
['Dialogue should be used when it…',['reveals character or moves the situation forward','fills empty space','repeats every fact','replaces all narration'],0,'Purposeful dialogue does narrative work.'],
['The middle of a story should mainly…',['develop the situation through obstacles, choices or discoveries','repeat the first paragraph','introduce the writer’s marks','end immediately'],0,'Development belongs in the middle.'],
['A good ending should usually…',['resolve the main situation or leave a clear final impression','introduce a new major problem','ignore the story','repeat the title only'],0,'The ending gives closure.'],
['In a picture-based composition, you should first…',['observe important details','invent a completely unrelated setting','ignore the picture','write the conclusion'],0,'Observation is the starting point.'],
['Narrative tense should generally be…',['consistent','changed every sentence','always future','random'],0,'Consistency improves clarity.'],
['Paragraphing helps the reader…',['see meaningful stages of the composition','count difficult words','avoid the title','skip the ending'],0,'Paragraphs separate stages and shifts.'],
['Which is the strongest verb choice?',['The wind rattled the windows.','The wind was very very strong.','The wind was nice.','The wind was a thing.'],0,'Rattled is precise and creates a clear image.'],
['A composition from hints should…',['use the hints as the logical basis of development','ignore the hints','copy the hints without connecting them','change every detail'],0,'Hints should guide the composition.'],
['Creative writing still needs…',['internal logic','only surprises','no cause and effect','random endings'],0,'Imagination works best when the invented situation remains coherent.'],
['Editing should include checking…',['grammar, spelling and punctuation','only the title','only handwriting','only paragraph count'],0,'Language mechanics are part of final control.'],
['A final audit should ask…',['Does the whole composition answer the task clearly?','Did I use the hardest words?','Did I make it as long as possible?','Did I add ten dialogues?'],0,'Task fulfilment is the most important final check.']
],challenge:[
['Which topic sentence best controls a composition about an unexpected journey?',['The journey began as an ordinary trip but changed when we took the wrong road.','Journeys are common in life.','I like travelling.','The road was there.'],0,'It gives a specific direction for development.'],
['Which event best creates a turning point?',['The character discovers that the person offering help knows the missing information.','The character walks for ten minutes.','The character looks at the sky.','The character repeats the opening.'],0,'It introduces information that changes the direction of the story.'],
['Which description is most precise?',['Rainwater slid from the roof and struck the metal railing in a steady rhythm.','It was a very nice rain.','The rain was good and beautiful and amazing.','There was weather.'],0,'It uses precise physical and sensory detail.'],
['Which sentence best reveals honesty through action?',['She found the wallet and handed it to the office without opening it.','She was a very honest girl.','Everyone knew she was honest.','Honesty is important.'],0,'The action provides evidence of the character trait.'],
['Which dialogue is most purposeful?',['“The bridge is closed,” the guard said. “Use the road beside the fields.”','“Hello.” “Hello.” “Hello.”','“I like this.” “I like that.”','“What is this?” “It is this.”'],0,'It gives useful information and moves the situation forward.'],
['What weakens the middle of a story most?',['several events occur but none changes the situation','a meaningful obstacle appears','the character makes a decision','new information changes the plan'],0,'Events without development create a flat narrative.'],
['Which transition best shows time?',['A few minutes later, the lights came back on.','However, the lights came back on.','For example, the lights came back on.','Because, the lights came back on.'],0,'A few minutes later clearly marks time.'],
['A picture shows a flooded street and people waiting near a shop. Which inference is reasonable?',['The people may be waiting for the water to fall or for a safe route.','The people are definitely planning a national election.','The shop must belong to the tallest person.','The weather will certainly remain the same for a week.'],0,'It stays close to what the visual situation reasonably supports.'],
['Which ending is strongest for a story about finding a lost key?',['After finding the key, she decided to keep important items in one fixed place.','Then another unrelated adventure began.','The key was lost again, and the story stopped.','Keys are useful objects.'],0,'It resolves the problem and gives a relevant final impression.'],
['Which revision improves coherence?',['First the train stopped, then the passengers learned why, and finally they chose another route.','The train stopped. Blue shoes. I like mangoes.','The train stopped, stopped, stopped, stopped.','The passengers learned why before the train stopped, although nothing happened.'],0,'The revised sequence has clear logical stages.'],
['Which sentence best creates atmosphere?',['The empty corridor echoed with footsteps under the weak yellow lights.','The corridor was good.','The corridor was a corridor.','The corridor had many things.'],0,'Sound and light create a specific atmosphere.'],
['A story suddenly says “A stranger solved everything” without explanation. The main problem is…',['an unsupported resolution','too much paragraphing','too many precise verbs','a strong setting'],0,'The solution appears without development or believable connection.'],
['Which plan best fits a reflective composition?',['idea → example/experience → insight → broader conclusion','random events → dialogue → signature','setting → chase → unrelated fact','list of adjectives → title'],0,'Reflection connects an experience or idea to a clear insight.'],
['Which sentence shows internal logic in imaginative writing?',['The magical map worked only when the traveller followed the symbols exactly.','The map solved every problem whenever the writer needed it.','The map changed its rules in every paragraph.','The map had no connection to the story.'],0,'A consistent rule makes the imaginative element believable within the story.'],
['Which edit improves sentence control?',['Because the road was blocked, we waited near the gate.','Because the road was blocked. We waited near the gate.','Because road blocked we waited gate.','Because the road was blocked, and. We waited.'],0,'The dependent clause is correctly connected to the main clause.'],
['Which title best fits a composition about choosing honesty over convenience?',['The Honest Choice','A Very Nice Day','Things That Happen','My Composition'],0,'The title reflects the central direction without being vague.'],
['Which detail should be removed from a rainy-market description?',['A sentence about a sports score from the previous month.','Umbrellas turning inside out in the wind.','Wet sacks stacked beneath an awning.','The smell of tea from a nearby stall.'],0,'The sports score does not support the market scene.'],
['A narrative begins in past tense but suddenly uses present tense for completed events without purpose. This mainly affects…',['tense consistency','setting accuracy','title choice','character age'],0,'Unplanned tense shifts can make a narrative confusing.'],
['What is the best reason to revise after drafting?',['to improve meaning, organisation and correctness','to make every sentence longer','to add difficult vocabulary','to remove all simple words'],0,'Revision improves communication and accuracy.'],
['Advanced composition control means…',['adapting structure and detail to the exact prompt while keeping the writing coherent','using one memorised story for every question','maximising vocabulary difficulty','adding events until the page is full'],0,'Strong writers adapt to purpose rather than forcing a template.']
],test:[
['A composition is strongest when it has…',['purpose, organised development and a satisfying close','only a long introduction','many unrelated details','difficult words in every line'],0,'Strong composition combines purpose, structure, development and closure.'],
['The command “Describe” should make you focus mainly on…',['selected sensory and visual detail','a chain of unrelated events','a formal letter format','only dialogue'],0,'Description builds a scene through relevant detail.'],
['The command “Narrate” mainly asks you to…',['develop events in meaningful sequence','list adjectives','write only a conclusion','copy the question'],0,'Narration is event-based development.'],
['The best opening for a story usually…',['establishes the situation and gives the reader a reason to continue','explains every later event','starts with a dictionary definition','lists the moral first'],0,'The opening orients and creates interest.'],
['Which setting is most effective?',['An empty bus stop at dawn, with wet benches and a flickering light.','A very nice place.','A place with many things.','Somewhere.'],0,'It establishes place, time and atmosphere with precise detail.'],
['Which event best shows cause and effect?',['The bridge closed after heavy rain, so the travellers had to take another route.','The bridge was near a tree.','The travellers wore shoes.','Rain is common in stories.'],0,'It connects the event and consequence explicitly.'],
['Which sentence creates imagery most effectively?',['Orange light spilled across the wet road as the clouds began to clear.','The road was beautiful.','The road was nice.','There was a road.'],0,'It uses concrete visual detail to create an image.'],
['Which sentence reveals character indirectly?',['He returned the extra change before the shopkeeper noticed the mistake.','He was a very honest boy.','Honesty is good.','Everyone called him honest.'],0,'The behaviour demonstrates honesty.'],
['Dialogue is most useful when it…',['reveals character, information or conflict','fills every paragraph','repeats the narrator','replaces all description'],0,'Purposeful dialogue contributes to the composition.'],
['A turning point is the moment when…',['the direction of the situation changes significantly','the title is written','the story starts','the writer counts words'],0,'The turning point redirects the narrative.'],
['Which is the best middle paragraph for a problem-solving story?',['The first plan failed, so the character examined the evidence and noticed a new clue.','The weather was nice.','The title was interesting.','The story was a story.'],0,'It develops the problem through failure and new information.'],
['Which transition is best for contrast?',['However','Finally','For example','First'],0,'However introduces contrast.'],
['Which picture-based approach is safest?',['observe the main actions and details, then infer a logical situation','invent an unrelated fantasy world','ignore visible people','copy every object into a list'],0,'Visual composition should begin with observation and reasonable inference.'],
['Which ending provides proper closure?',['The decision solved the immediate problem and changed how the character would act next time.','A new major mystery suddenly appeared.','The story stopped in the middle of a sentence.','The title was repeated.'],0,'It resolves the situation and adds a relevant final impression.'],
['Which imaginative idea remains internally consistent?',['A device works only when its three stated conditions are met.','The device works differently whenever the plot needs help.','The device has no rules at all.','The device solves every conflict instantly.'],0,'Consistent rules make an invented situation coherent.'],
['Which paragraph break is most appropriate?',['Start a new paragraph when the composition moves to a new major stage or focus.','Start a new paragraph after every sentence.','Never use paragraphs.','Use a new paragraph only before the title.'],0,'Paragraphing should show meaningful shifts.'],
['Which word choice is most controlled?',['The narrow path twisted between the trees.','The path was very very good.','The path was super amazing.','The path was a thing.'],0,'Twisted and narrow are precise and natural.'],
['Which correction is best? “He opened the door. Because he heard a noise.”',['He opened the door because he heard a noise.','He opened the door because. He heard a noise.','He open the door because heard noise.','He opened door, because.'],0,'The dependent clause is correctly joined to the main clause.'],
['Which sentence maintains past-tense narration?',['She looked outside and realised that the rain had stopped.','She looks outside and realised that the rain had stopped.','She looked outside and realises that the rain has stopped.','She look outside and realised.'],0,'The verbs are controlled within the past-time narrative.'],
['Which final audit is most complete?',['task, purpose, structure, development, coherence, ending, grammar, spelling and length','only vocabulary','only title','only word count'],0,'A full audit checks content, organisation and mechanics.'],
['A composition is 180 words when the task expects about 100–120. The best revision is to…',['remove repetition and less relevant detail while preserving the central idea','add more adjectives','delete the ending','ignore the instruction'],0,'Concise revision improves task control.'],
['Which statement about description is correct?',['Specific detail is stronger than a long list of vague adjectives.','Every noun needs three adjectives.','Description should contain no verbs.','Description must always be in first person.'],0,'Precision creates clearer description.'],
['Which plan best fits a story from hints?',['use each hint as a stage or cause in a connected narrative','write one unrelated paragraph for each hint','ignore difficult hints','repeat the first hint throughout'],0,'Hints should form a logical chain.'],
['Which reflection is strongest?',['The mistake taught me that checking important work can prevent avoidable errors.','Mistakes are mistakes.','I made a mistake and then went home.','This is the end.'],0,'It turns the experience into a clear insight.'],
['Which overall principle best represents exam-ready composition?',['Adapt to the prompt, develop one clear direction, connect ideas logically and edit the final draft carefully.','Memorise one story and change only the title.','Use the longest sentences possible.','Use difficult words even when they are inaccurate.'],0,'Exam-ready writing is controlled, task-specific and coherent.']
]};

const rotate=(questions,mode)=>{const shift=mode==='challenge'?1:mode==='test'?2:0;return questions.map((item,i)=>{const[q,opts,a,e]=item;const next=[...opts];const move=(a+shift+i)%next.length;const correct=next[a];next.splice(a,1);next.splice(move,0,correct);return[q,next,move,e]})};
const readMode=()=>{if(typeof window==='undefined')return'practice';const m=new URLSearchParams(window.location.search).get('mode');return['practice','challenge','test'].includes(m)?m:'practice'};
const modelStructure=kind=>kind==='Narrative'||kind==='Story from Hints'||kind==='Dialogue-led'||kind==='Picture-based'?'Opening → development → turning point → resolution':kind==='Descriptive'?'overall scene → sensory details → movement/focus → final impression':kind==='Reflective'?'idea → experience/reasoning → insight → conclusion':'opening → experience/problem → response → learning/closing';
const modelStep=(kind,i,total)=>{if(kind==='Descriptive')return i===0?'SCENE':i===total-1?'FINAL IMPRESSION':'DETAIL / ATMOSPHERE';if(kind==='Reflective')return i===0?'IDEA':i===total-1?'INSIGHT / CLOSE':'REASONING';return i===0?'OPENING / SETTING':i===total-1?'RESOLUTION / CLOSE':i===1?'DEVELOPMENT':'TURNING POINT / CHANGE'};

export default function EnglishCompositionTopic({onBack=()=>{},addXp=()=>{},finishSession=()=>{}}){
 const [mode,setMode]=useState(readMode);const[lesson,setLesson]=useState(0);
 useEffect(()=>{const sync=()=>setMode(readMode());window.addEventListener('popstate',sync);sync();return()=>window.removeEventListener('popstate',sync)},[]);
 const bank=useMemo(()=>rotate(BANKS[mode]||BANKS.practice,mode),[mode]);
 const changeMode=m=>{const p=new URLSearchParams(window.location.search);p.set('subject','english');p.set('languageSkills','1');p.set('topic','composition');p.set('mode',m);window.history.pushState({},'',`${window.location.pathname}?${p}`);window.dispatchEvent(new PopStateEvent('popstate'))};
 const learn=()=>{const p=new URLSearchParams(window.location.search);p.set('subject','english');p.set('languageSkills','1');p.set('topic','composition');p.delete('mode');window.history.pushState({},'',`${window.location.pathname}?${p}`);window.dispatchEvent(new PopStateEvent('popstate'))};
 const next=()=>changeMode(mode==='practice'?'challenge':mode==='challenge'?'test':'practice');const current=LESSONS[lesson];
 const assessment=['practice','challenge','test'].includes(mode)&&new URLSearchParams(window.location.search).get('mode')===mode;
 if(assessment)return <EnglishTimedQuiz title="Composition" mode={mode} getBank={()=>bank} onModeChange={changeMode} onBack={learn} addXp={addXp} finishSession={finishSession} onNextLevel={next} secondsPerQuestion={mode==='test'?55:50}/>;
 return <main className="ec-shell">
  <header className="ec-hero"><div><button type="button" className="ec-back" onClick={onBack}>← Language & Skills</button><span className="ec-kicker">ENGLISH • LANGUAGE & SKILLS • COMPOSITION</span><h1>Composition</h1><p>Learn to plan, narrate, describe and build original exam-ready compositions.</p></div><div className="ec-stat"><strong>{LESSONS.length}</strong><span>guided lessons</span></div></header>
  <nav className="ec-modebar"><button className="active" type="button">Learn</button><button type="button" onClick={()=>changeMode('practice')}>Practice</button><button type="button" onClick={()=>changeMode('challenge')}>Challenge</button><button type="button" onClick={()=>changeMode('test')}>Final Test</button></nav>
  <section className="ec-progress"><div><span>Lesson {lesson+1} of {LESSONS.length}</span><b>{Math.round((lesson+1)*100/LESSONS.length)}%</b></div><div className="ec-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></section>
  <div className="ec-layout"><aside className="ec-map"><div className="ec-map-title">Lesson map</div>{LESSONS.map((x,i)=><button key={x.n} className={i===lesson?'selected':''} onClick={()=>setLesson(i)} type="button"><span>{x.n}</span><div><strong>{x.title}</strong><small>{x.group}</small></div></button>)}</aside>
   <section><article className="ec-lesson"><span className="ec-badge">{current.group}</span><h2>{current.title}</h2><p className="ec-simple">{current.simple}</p><div className="ec-inline-guide"><span>समझने का आसान तरीका</span><p>{current.hindi}</p></div><div className="ec-grid"><section><h3>Core meaning</h3><p>{current.meaning}</p></section><section><h3>Structure</h3><p>{current.structure}</p></section></div><section className="ec-examples"><h3>Quick examples</h3>{current.examples.map((x,i)=><div key={i}>{x}</div>)}</section><div className="ec-clue"><strong>Exam clue</strong><p>{current.clue}</p></div></article>
    <div className="ec-lesson-nav"><button type="button" disabled={lesson===0} onClick={()=>setLesson(v=>Math.max(0,v-1))}>← Previous lesson</button><span>{lesson+1} / {LESSONS.length}</span><button type="button" onClick={()=>setLesson(v=>Math.min(LESSONS.length-1,v+1))}>{lesson===LESSONS.length-1?'Review audit':'Next lesson →'}</button></div>
    <section className="ec-reference"><h2>Quick reference</h2><div className="ec-reference-grid">{[['NARRATIVE','events → conflict → resolution'],['DESCRIPTION','scene → senses → precise detail'],['IMAGINATIVE','premise → rules → consequence'],['REFLECTION','experience → insight → conclusion']].map(([a,b])=><div key={a}><small>{a}</small><h3>{b}</h3><p>Match the structure to the question instead of forcing a fixed template.</p></div>)}</div></section>
    <section className="ec-models"><div className="ec-models-head"><div><span>MODEL COMPOSITIONS</span><h2>Read the Structure, Then Read the Writing</h2><p>Complete English-only models with visible stages, so the organisation is easy to study.</p></div></div><div className="ec-model-grid">{MODELS.map(([kind,title,text])=>{const parts=text.split('\n\n');return <article key={title}><div className="ec-model-head"><span>{kind}</span><h3>{title}</h3><p>{modelStructure(kind)}</p></div><div className="ec-model-body">{parts.map((p,i)=><div className="ec-model-part" key={i}><small>{modelStep(kind,i,parts.length)}</small><p>{p}</p></div>)}</div></article>})}</div></section>
    <section className="ec-errors"><h2>Common errors</h2><div className="ec-error-grid">{TRAPS.slice(0,6).map((x,i)=><div key={i}>{x}</div>)}</div></section>
    <section className="ec-writing"><h2>Write it yourself</h2><p>Use the current lesson as your drafting target.</p><div className="ec-task">{TASKS[lesson%TASKS.length]}</div><div className="ec-checks"><span>✓ Task understood</span><span>✓ Clear direction</span><span>✓ Strong opening</span><span>✓ Logical development</span><span>✓ Effective ending</span><span>✓ Grammar & spelling checked</span></div></section>
   </section></div>
  <section className="ec-audit"><div><span>FINAL AUDIT</span><h2>Ready for composition under exam conditions?</h2><p>Task → purpose → plan → opening → development → coherence → ending → language → length.</p></div><button type="button" onClick={()=>changeMode('practice')}>Start Practice →</button></section>
 </main>;
}