import {EnglishReaderEngine} from './EnglishReaderChapter.jsx';
const q=(q,o,a,e)=>({q,o,a,e});
const study={chapter:7,title:'Saint Ravidas',subtitle:'Supplementary Reader-IX',sourceNote:'Source: supplied English Reader PDF, Chapter 7, pp. 33–35. The lesson presents Ravidas as a liberator of oppressed people and focuses on equality, dignity, caste reform, devotion and social change.',intro:'Saint Ravidas is presented as a saint-poet from a socially oppressed background whose spiritual teaching rejected caste hierarchy, untouchability, prejudice and narrow privilege. The chapter combines the story of his journey to Banaras with his teachings, disciples, legacy and continuing relevance.',sections:[
{title:'Ravidas and the meaning of the chapter',flow:'The lesson hails Guru Ravidas as a liberator of the common people and a voice for oppressed, non-privileged humanity. He is described as a cobbler who worked with leather, yet his spiritual stature earned wide respect. The source also notes that he became associated with devotion and social reform.',explanation:'Guru Ravidas को oppressed और non-privileged लोगों की आवाज़ के रूप में प्रस्तुत किया गया है। उनका पेशा cobbler का था, लेकिन उनकी spiritual greatness के कारण उन्हें बहुत सम्मान मिला।',vocabulary:[['liberator','मुक्तिदाता'],['oppressed','शोषित/पीड़ित'],['non-privileged','विशेषाधिकार से वंचित'],['stature','महत्त्व/प्रतिष्ठा']],exam:'Explain why Ravidas is called a liberator of the common people.',think:'Why does the source connect spiritual greatness with social service?'},
{title:'The procession from Chittor to Banaras',flow:'The narrative describes a large procession from Chittor to Banaras. Elephants, soldiers, royal family members, expensive presents and crowds of people come to honour Ravidas. The journey shows the remarkable respect a saint from a humble background could receive.',explanation:'Chittor से Banaras की यात्रा में हाथी, सैनिक, royal family के लोग और अनेक presents का वर्णन है। बहुत लोग Ravidas का सम्मान करने के लिए आते हैं। इससे उनकी spiritual influence का पता चलता है।',vocabulary:[['procession','जुलूस'],['royal','राजकीय'],['honour','सम्मान देना'],['humble','साधारण/विनम्र']],exam:'Describe the procession and what it shows about Ravidas’s reputation.',think:'Why is the contrast between humble occupation and public honour important?'},
{title:'The social condition of his time',flow:'The lesson places Ravidas in the later fourteenth and early fifteenth centuries. It describes a period marked by darkness, foreign oppression, humiliation and tension around religion and social practice. The need for security and stability was felt by ordinary people, and reformers such as Ravidas challenged social evils.',explanation:'Chapter Ravidas के समय को मध्यकालीन India के कठिन social conditions से जोड़ता है। oppression, humiliation और social-religious conflict के बीच reformers का message और महत्वपूर्ण बनता है।',vocabulary:[['humiliation','अपमान'],['oppression','दमन'],['reform','सुधार'],['stability','स्थिरता']],exam:'Remember the historical setting used by the lesson.',think:'Why do reform movements often grow during social hardship?'},
{title:'Ravidas’s central teaching',flow:'Ravidas teaches that the person who truly worships God becomes a person of God. High and low caste distinctions are presented as meaningless and absurd. He emphasises self-respect, dignity and the equality of all people and asks the humblest and poorest to value their human worth.',explanation:'Ravidas की central teaching में भगवान की भक्ति के साथ human equality जुड़ी है। high और low caste की distinction को meaningless बताया गया है। वह dignity और self-respect पर जोर देते हैं।',vocabulary:[['dignity','गरिमा'],['equality','समानता'],['self-respect','आत्मसम्मान'],['absurd','निरर्थक/बेतुका']],exam:'State the main social idea in Ravidas’s teaching.',think:'How can spiritual equality challenge caste hierarchy?'},
{title:'Against caste and untouchability',flow:'Ravidas waged a relentless war against caste and casteism. He suffered humiliation, but remained committed to the uplift of oppressed classes and backward sections of society. His message questioned the idea that birth can decide a person’s worth.',explanation:'Ravidas ने caste और casteism के खिलाफ लगातार संघर्ष किया। उन्होंने humiliation सहा, फिर भी oppressed और backward sections के uplift के लिए काम किया।',vocabulary:[['relentless','अथक/निरंतर'],['casteism','जातिवाद'],['uplift','उत्थान'],['backward section','पिछड़ा वर्ग/समुदाय']],exam:'Use Ravidas’s own social position and teaching as evidence against casteism.',think:'Why is personal experience powerful in social reform?'},
{title:'Disciples, kings and Mirabai',flow:'The lesson says people of different social positions became his disciples and devotees, including kings and women. It specifically mentions Mirabai among his followers. This wide circle of disciples shows that his spiritual appeal crossed social rank.',explanation:'Ravidas के disciples और devotees अलग-अलग social positions से थे। Kings तथा women भी उनसे जुड़े और Mirabai का नाम विशेष रूप से आता है। इससे उनके message की broad appeal दिखती है।',vocabulary:[['disciple','शिष्य'],['devotee','भक्त'],['social rank','सामाजिक स्थिति'],['appeal','प्रभाव/आकर्षण']],exam:'Remember Mirabai and the diversity of Ravidas’s followers.',think:'What does a mixed group of disciples reveal about equality?'},
{title:'Verses, Guru Granth Sahib and lasting greatness',flow:'The chapter notes that Ravidas’s verses are included in Guru Granth Sahib and are therefore respected by Sikhs. Even after about six centuries, he remains honoured by people in many regions. His teachings have a legacy beyond the boundaries of the community in which he lived.',explanation:'Ravidas के कुछ verses Guru Granth Sahib में शामिल होने का उल्लेख है। छह शताब्दियों बाद भी उनका सम्मान बना हुआ है। यह उनकी teaching की lasting legacy को दिखाता है।',vocabulary:[['legacy','विरासत'],['verse','पद्य/कविता की पंक्ति'],['revered','पूजित/सम्मानित'],['century','शताब्दी']],exam:'Explain two signs of Ravidas’s lasting legacy.',think:'Why can teachings cross community boundaries?'},
{title:'Ram Nam and the alchemy story',flow:'The lesson tells of a devotee offering Ravidas an alchemy that could turn metal into gold. Ravidas says that his true alchemy is “Ram Nam” and refuses to use or touch the promised object. He continues living simply and spends his life in devotion, service and the uplift of others.',explanation:'Alchemy की कहानी में Ravidas material gold से अधिक spiritual value को महत्व देते हैं। उनके लिए “Ram Nam” ही असली alchemy है। यह simplicity और spiritual priorities को दर्शाता है।',vocabulary:[['alchemy','धातु को सोना बनाने की कथित विद्या'],['material','भौतिक'],['devotion','भक्ति'],['simplicity','सादगी']],exam:'What does the Ram Nam episode reveal about Ravidas’s values?',think:'Why might a reformer reject material wealth?'},
{title:'Relevance in the present day',flow:'The final section argues that Ravidas’s ideology and teachings have greater relevance today than ever before. It connects his message with universal brotherhood and the need to resist discrimination. Money-power and muscle-power may dominate society, but Ravidas’s stress on human dignity remains a moral challenge to injustice.',explanation:'अंत में कहा गया है कि Ravidas की equality, dignity और brotherhood की teaching आज भी relevant है। social discrimination के खिलाफ उनका message present society के लिए महत्वपूर्ण बना रहता है।',vocabulary:[['ideology','विचारधारा'],['relevance','प्रासंगिकता'],['discrimination','भेदभाव'],['brotherhood','भाईचारा']],exam:'Explain why the lesson calls Ravidas relevant today.',think:'Which of his values can directly weaken discrimination?'}],
glossary:[['liberator','मुक्तिदाता'],['oppressed','शोषित/पीड़ित'],['casteism','जातिवाद'],['untouchability','अस्पृश्यता'],['dignity','गरिमा'],['self-respect','आत्मसम्मान'],['devotion','भक्ति'],['uplift','उत्थान'],['legacy','विरासत'],['relevance','प्रासंगिकता'],['alchemy','रसायन-विद्या'],['brotherhood','भाईचारा']],
wordStudy:[['high and low casts','ऊँच-नीच की जातिगत सोच; source’s social distinction'],['wage a war','लगातार संघर्ष करना'],['social cause','समाज सुधार का उद्देश्य'],['human worth','मानवीय मूल्य/गरिमा'],['money-power','धन के प्रभाव की शक्ति'],['muscle-power','बल/शारीरिक शक्ति का प्रभाव']],
textbookAnswers:[['Describe the procession to Banaras from Chittor.','The lesson describes a grand procession with elephants, soldiers, members of the royal family, presents and many people travelling to honour Ravidas.'],['Why did the pandits of Kashi oppose Ravidas?','The chapter presents them as opposing a saint whose message challenged caste distinctions, privilege and the established social order.'],['How did Ravidas become a great religious Guru? Who were his disciples?','His devotion, moral courage and rejection of caste discrimination earned him disciples and devotees from different social groups, including kings and Mirabai.'],['What was the teaching of Saint Ravidas about untouchables? Was he satisfied by their condition?','He rejected untouchability and caste hierarchy and worked for the uplift of oppressed people. He was not satisfied with their social condition.'],['Mention the incident that proves Ravidas did not prefer material wealth.','A devotee offered an alchemy said to turn metal into gold. Ravidas refused it and described Ram Nam as the true alchemy.'],['Describe the contributions of Saint Ravidas to society.','He challenged casteism and untouchability, taught equality and dignity, served the poor and oppressed, and left a widely respected spiritual legacy.']],
revision:[['Social background','Presented as a cobbler and a saint of the oppressed.'],['Historical period','Later fourteenth and early fifteenth centuries.'],['Central teaching','Worship of God must go with equality and human dignity.'],['Social struggle','Opposition to casteism and untouchability.'],['Disciples','People across social rank; Mirabai is named.'],['Legacy','Verses in Guru Granth Sahib and continuing relevance.']],
discussion:['Sincerity and commitment have their own rewards. Discuss with reference to Ravidas.','Untouchability is a social curse. Discuss the chapter’s message against it.'],activities:['Do a project work on the social condition in the medieval age.'],extra:'The supplied Chapter 7 pages show Literature, A. Let’s Answer, B. Let’s Discuss and C. Let’s Do. No separate grammar exercise is shown, so none has been invented.'};
const practice=[
q('Who is described as a liberator of the common people?',['Guru Ravidas','Bill Bryson','Ismat Chughtai','Jagannath'],0,'The chapter opens by presenting Guru Ravidas as a liberator of oppressed people.'),q('What was Ravidas’s occupation?',['Cobbler','Soldier','Merchant','Farmer'],0,'The source describes him as a cobbler.'),q('Where did the grand procession travel?',['Chittor to Banaras','Banaras to Delhi','Agra to Chittor','Jaipur to Banaras'],0,'The narrative describes the procession from Chittor to Banaras.'),q('What does Ravidas teach about high and low caste?',['They are meaningless and absurd','They must always be preserved','They decide spiritual worth','They are more important than devotion'],0,'The chapter rejects caste distinctions as meaningless.'),q('What social evil did Ravidas fight?',['Untouchability','Travel accidents','Airline rules','Deforestation'],0,'Untouchability is a central target of his reform message.'),q('Who is named among his disciples?',['Mirabai','Sonal Mansingh','George Lechner','Bill Bryson'],0,'Mirabai is specifically named.'),q('Where are verses of Ravidas included?',['Guru Granth Sahib','Adi Grantha only as a separate work','Ramcharitmanas','Akbarnama'],0,'The chapter notes verses in Guru Granth Sahib.'),q('What does Ravidas call the true alchemy?',['Ram Nam','Gold dust','Royal patronage','Book learning'],0,'He describes Ram Nam as the true alchemy.'),q('Which quality is central to his teaching?',['Dignity','Caste privilege','Untouchability','Humiliation'],0,'Human dignity is central to the lesson.'),q('Which problem makes his teaching relevant today?',['Discrimination','Railway delays','Travel fatigue','Airline tickets'],0,'The final section connects his message with discrimination.'),q('What did Ravidas do for oppressed people?',['He worked for their uplift','He ignored them','He defended caste hierarchy','He avoided society'],0,'The lesson presents his work for the uplift of oppressed classes.'),q('Which time period is given?',['Later fourteenth and early fifteenth centuries','Eighteenth century only','Twentieth century','Ancient Roman period'],0,'The historical section gives this medieval period.'),q('What kind of legacy does the chapter emphasise?',['Spiritual and social reform','Military conquest','Royal wealth','Scientific invention'],0,'The chapter focuses on spiritual teaching and social reform.'),q('What is brotherhood in the chapter’s context?',['A universal human bond','A caste privilege','A royal title','A travel route'],0,'Brotherhood is used as a universal social ideal.'),q('What is the main message against caste?',['Birth should not determine human worth','Caste must control spiritual life','Only high caste people can worship','Untouchability is necessary'],0,'The chapter rejects caste as a basis for human value.')];
const challenge=[
q('Why is Ravidas’s occupation significant in the lesson?', ['It creates a contrast between humble social position and great spiritual respect','It proves he avoided all work','It explains a royal appointment','It shows he rejected devotion'],0,'The contrast strengthens the chapter’s critique of status-based hierarchy.'),
q('What does the procession from Chittor to Banaras demonstrate?', ['His influence crossed ordinary social boundaries and attracted people of high status','He became a military commander','He wanted royal wealth','The journey was only commercial'],0,'The procession shows extraordinary respect from powerful and ordinary people.'),
q('Why does the chapter describe its historical period as socially dark?', ['It gives a setting of oppression, humiliation and conflict in which reform was needed','It refers only to weather','It explains a festival','It focuses on travel conditions'],0,'The lesson uses social hardship to frame Ravidas’s reform.'),
q('How does devotion become a social message in Ravidas’s teaching?', ['True devotion is linked with recognising the equality and dignity of people','Devotion is reserved for one caste','Devotion means collecting wealth','Devotion avoids all social questions'],0,'The chapter connects worship of God with equality.'),
q('Why is self-respect important to the oppressed?', ['It challenges the idea that social rank can erase human dignity','It encourages hatred of others','It creates caste hierarchy','It avoids education'],0,'The text urges the humble and poor to recognise their worth.'),
q('How does personal suffering affect Ravidas’s reform message?', ['His experience of humiliation gives moral force to his opposition to caste discrimination','It makes him support untouchability','It causes him to reject all people','It ends his devotion'],0,'The lesson notes that he suffered humiliation yet remained committed to uplift.'),
q('What does the diversity of his disciples imply?', ['His spiritual appeal crossed caste, gender and status divisions','Only rulers accepted him','His message was limited to one profession','He had no social influence'],0,'Kings and women such as Mirabai are among those named.'),
q('Why is inclusion in Guru Granth Sahib important for the lesson?', ['It shows that his verses became part of a respected tradition beyond one social group','It proves he was a military leader','It means his ideas were forgotten','It limits his audience to cobblers'],0,'The chapter uses the verses as evidence of lasting and cross-community respect.'),
q('What does the Ram Nam story suggest about materialism?', ['Ravidas valued spiritual wealth over promised material wealth','He wanted gold above all else','He sought royal office','He believed money solved discrimination'],0,'He refuses the alchemy and identifies Ram Nam as true value.'),
q('Why is the chapter’s title centred on the word saint?', ['His moral and spiritual teaching is central to the portrait, not social status or occupation','He was a royal title-holder','He wrote only political documents','He avoided human society'],0,'The lesson focuses on saintly teaching and social reform.'),
q('What is the connection between casteism and untouchability in the lesson?', ['Both deny equal human dignity and require social reform','They are presented as unrelated','Both improve equality','They are forms of travel etiquette'],0,'The chapter treats them as related social injustices.'),
q('Why does the source call Ravidas relevant today?', ['Present societies can still face discrimination, so his equality and dignity message remains useful','Modern people no longer face social problems','His teaching concerns only medieval clothing','His legacy is purely historical'],0,'The final paragraphs explicitly stress present relevance.'),
q('What is the strongest evidence of long-term influence?', ['His verses are preserved in Guru Granth Sahib and he is still revered centuries later','He owned a large palace','He served one ruler','He travelled to Europe'],0,'The source gives both textual and continuing social evidence.'),
q('How does the lesson connect sincerity and reward?', ['Ravidas’s commitment to service, devotion and truth earns enduring respect','He seeks reward through money','He avoids commitment','He values status over service'],0,'The discussion prompt matches the life story of committed reform.'),
q('Why is the procession more symbolic than merely ceremonial?', ['It reverses normal expectations about status by showing rulers and crowds honouring a humble saint','It is only a transport scene','It proves he was a king','It marks a military victory'],0,'The contrast makes the anti-hierarchy theme visible.'),
q('Which idea best summarises Ravidas’s view of society?', ['Human worth is not determined by caste or birth','Caste should determine dignity','Only priests deserve respect','Poverty is proof of moral weakness'],0,'Equality and dignity are repeated throughout the chapter.'),
q('Why does the chapter mention money-power and muscle-power near the end?', ['It contrasts material domination with Ravidas’s moral and spiritual values','It praises violence','It introduces a political campaign','It explains the procession route'],0,'The source uses these forms of power to show why moral values still matter.'),
q('How can spiritual teaching become social reform?', ['By changing beliefs about human worth and challenging unjust practices','By avoiding society entirely','By collecting wealth','By preserving privilege'],0,'Ravidas’s teaching attacks unjust social distinctions.'),
q('What does the alchemy metaphor add to the chapter?', ['It shows that the greatest transformation is spiritual rather than material','It teaches gold-making as a profession','It replaces the caste discussion','It explains trade routes'],0,'Ram Nam is presented as the valuable transformation.'),
q('Why is Mirabai’s inclusion especially useful?', ['It illustrates that Ravidas’s influence reached beyond caste and gender boundaries','It proves he lived in the modern era','It shows she was his ruler','It explains the procession logistics'],0,'The disciple example demonstrates broad social appeal.'),
q('What is the ethical force of calling untouchability a social curse?', ['It frames the practice as harmful to human dignity and worthy of rejection','It presents untouchability as necessary','It treats it as a private preference','It praises caste separation'],0,'The discussion exercise explicitly asks learners to treat untouchability as a social curse.'),
q('Why can a humble occupation strengthen a reformer’s message?', ['It shows that dignity and spiritual greatness do not depend on prestige','It makes the person less credible','It proves education is unnecessary','It shows wealth is more important'],0,'Ravidas’s occupation contrasts with his wide spiritual respect.'),
q('What is the best interpretation of “liberator” here?', ['Someone who helps people reject oppression and recover dignity','A military conqueror','A wealthy landlord','A railway officer'],0,'The chapter uses liberation in a social and spiritual sense.'),
q('Which conclusion best combines all major themes?', ['Ravidas united devotion with equality, dignity, anti-caste reform and service to the oppressed','Ravidas mainly sought wealth','Ravidas supported social hierarchy','Ravidas avoided all people'],0,'This synthesis matches the chapter’s biography, teaching and legacy.')];
const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`final-${i}`}));
export function EnglishReaderChapter7({initialMode='learn',onBack,addXp,finishSession}){return <EnglishReaderEngine study={{...study,practice,challenge,finalTest}} initialMode={initialMode} onBack={onBack} addXp={addXp} finishSession={finishSession}/>;}
export const englishReaderChapter7Meta={title:study.title,author:'',sourceNote:study.sourceNote,modeCounts:{practice:practice.length,challenge:challenge.length,final:finalTest.length}};
export {study as englishReaderChapter7Study};
