import React,{useState}from'react';
import './EnglishSubjectVerbAgreementTopic.css';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';

const LESSONS=[
{id:'01',group:'FOUNDATION',title:'What is subject–verb agreement?',meaning:'The subject controls the form of the finite verb. First find who or what performs the action or carries the state; then choose the verb that agrees with that grammatical subject.',structure:'Singular subject → singular present verb: The boy plays. Plural subject → plural present verb: The boys play.',examples:[['The student works hard.','student = singular → works'],['The students work hard.','students = plural → work'],['She is ready.','she = singular → is'],['They are ready.','they = plural → are']],clue:'Find the real subject before looking at the nearest noun.'},
{id:'02',group:'CORE RULES',title:'Singular vs plural subjects',meaning:'In the Simple Present, a third-person singular subject normally takes the -s/-es verb form, while plural subjects take the base form. With be, use is/was for singular and are/were for plural.',structure:'he/she/it + V-s/es • I/you/we/they + V1 • singular be = is/was • plural be = are/were',examples:[['Rina reads every day.','singular → reads'],['Rina and Amit read every day.','compound plural → read'],['The book is useful.','book → is'],['The books are useful.','books → are']],clue:'Verb agreement is grammatical, not about how long the subject sounds.'},
{id:'03',group:'HEAD NOUN',title:'Find the head noun',meaning:'A subject may contain extra words. The head noun is the central noun that controls agreement. Phrases beginning with of, with, together with, along with and as well as do not normally change the number of the main subject.',structure:'[Head noun + modifiers] + verb. The box of pencils is heavy.',examples:[['The list of names is ready.','list controls; names is inside the of-phrase'],['A box of pencils is missing.','box controls; pencils does not'],['The teacher, along with the students, is present.','teacher controls agreement'],['The quality of these books is excellent.','quality controls agreement']],clue:'Cross out the prepositional phrase mentally and test the remaining subject.'},
{id:'04',group:'COMPOUND SUBJECTS',title:'Subjects joined by and',meaning:'Two subjects joined by and normally form a plural subject and take a plural verb. When two nouns joined by and refer to one combined idea or one unit, singular agreement may be possible by meaning.',structure:'A + and + B → plural: Rina and Sita are friends.',examples:[['Rina and Sita are friends.','two subjects → plural'],['The teacher and the student are talking.','two people → plural'],['Bread and butter is my usual breakfast.','one combined meal/idea → singular by meaning'],['Slow and steady wins the race.','one combined expression/idea → singular']],clue:'Ask: two separate subjects, or one combined idea?'},
{id:'05',group:'EACH / EVERY',title:'Each, every and the distributive rule',meaning:'Each and every make the following noun phrase singular in standard school grammar. Even when an of-phrase contains a plural noun, the verb agrees with each/every construction.',structure:'each/every + singular noun + singular verb. Each of + plural noun + singular verb.',examples:[['Every student is ready.','every + singular noun → is'],['Each boy plays well.','each + singular noun → plays'],['Each of the boys is ready.','each controls; boys is inside of-phrase'],['Every one of the books is useful.','every one is grammatically singular']],clue:'Never let the plural noun after of pull the verb away from each/every.'},
{id:'06',group:'INDEFINITE PRONOUNS',title:'Everyone, someone, nobody and similar subjects',meaning:'Indefinite pronouns such as everyone, everybody, anyone, anybody, someone, somebody, no one and nobody are treated as singular in standard school grammar.',structure:'everyone/everybody/someone/somebody/anyone/anybody/no one/nobody + singular verb',examples:[['Everyone is invited.','everyone → is'],['Someone has left a bag.','someone → has'],['Nobody knows the answer.','nobody → knows'],['Anybody can join.','anybody → can']],clue:'Their meaning may refer to many people, but their grammatical form is singular.'},
{id:'07',group:'EITHER / NEITHER',title:'Either, neither and either of / neither of',meaning:'Either and neither are singular when used alone or in the common either of / neither of school pattern. The following plural noun in an of-phrase does not control the verb.',structure:'Either of + plural noun + singular verb. Neither of + plural noun + singular verb.',examples:[['Either of the answers is possible.','either → is'],['Neither of the boys is absent.','neither → is'],['Either option works.','option is singular'],['Neither plan seems practical.','plan is singular']],clue:'either/neither = one of two or not one of two → singular verb in this rule.'},
{id:'08',group:'THERE IS / THERE ARE',title:'Introductory there',meaning:'In there is/there are constructions, the verb agrees with the noun that follows. There itself is not the real grammatical subject.',structure:'There is + singular noun. There are + plural noun.',examples:[['There is a book on the desk.','book → is'],['There are three books on the desk.','three books → are'],['There was a problem.','problem → was'],['There were several problems.','problems → were']],clue:'Look after there to identify the noun that controls agreement.'},
{id:'09',group:'EITHER / OR',title:'Either…or and neither…nor',meaning:'With either…or and neither…nor, school grammar commonly uses the verb that agrees with the nearer subject. This is especially important when one part is singular and the other plural.',structure:'Either A or B + verb → agreement commonly follows the nearer subject B.',examples:[['Either the teacher or the students are responsible.','nearest subject students → are'],['Either the students or the teacher is responsible.','nearest subject teacher → is'],['Neither Rina nor her friends are ready.','friends → are'],['Neither the players nor the captain is available.','captain → is']],clue:'Check the subject closest to the verb in mixed-number pairs.'},
{id:'10',group:'QUANTITY',title:'Amounts, distances and periods as one unit',meaning:'A measurement or amount can act as a single unit and therefore take a singular verb when the sentence treats it as one whole quantity.',structure:'Five kilometres is… • Ten years is… • Fifty rupees is… when the quantity is one whole amount.',examples:[['Five kilometres is a long walk.','one distance → is'],['Ten years is a long time.','one period → is'],['Fifty rupees is enough.','one amount → is'],['Two hours is enough for the test.','one block of time → is']],clue:'Ask whether the expression is counted as separate items or one total unit.'},
{id:'11',group:'11/11 RULE',title:'Some nouns are plural in form',meaning:'Certain nouns look plural and normally take plural verbs: police, cattle and people. Others are fixed singular names such as news, mathematics and physics in common school usage.',structure:'The police are… • The cattle are… • The news is… • Mathematics is…',examples:[['The police are investigating the case.','police → plural'],['The cattle are grazing.','cattle → plural'],['The news is surprising.','news → singular'],['Mathematics is interesting.','school subject name → singular']],clue:'Do not decide agreement only from the final letter of the noun.'},
{id:'12',group:'COLLECTIVE NOUNS',title:'Team, family, committee and group nouns',meaning:'Collective nouns name a group. In school-level standard English, singular agreement is often used when the group acts as one unit; plural agreement can appear when members are emphasised, especially in British usage.',structure:'The team is winning. / The team are arguing among themselves. Meaning and variety of English matter.',examples:[['The team is ready.','one unit → singular'],['The committee has approved the plan.','one body → singular'],['The family is moving to Patna.','one unit/action → singular'],['The team are arguing among themselves.','members emphasised; plural possible in British usage']],clue:'For Class 9 exam answers, follow the intended meaning and the variety taught by the school.'},
{id:'13',group:'RELATIVE STRUCTURES',title:'Agreement after who / that',meaning:'A relative pronoun takes its number from the antecedent noun it refers to. The verb inside the relative clause must agree with that antecedent.',structure:'singular antecedent + who/that + singular verb; plural antecedent + who/that + plural verb',examples:[['She is one of the students who work hard.','who refers to students → work'],['She is the student who works hard.','who refers to student → works'],['These are the books that belong to me.','books → belong'],['This is the book that belongs to me.','book → belongs']],clue:'Identify what who/that refers to before choosing the relative-clause verb.'},
{id:'14',group:'SPECIAL PATTERNS',title:'Titles, names and words used as subjects',meaning:'A title, a book name or a quoted word may represent one thing even when it contains plural-looking words, so it can take a singular verb.',structure:'“The Arabian Nights” is a book. • “Gulliver’s Travels” is a novel.',examples:[['“Gulliver’s Travels” is a novel.','one title → is'],['“The Chronicles” is my favourite book.','one title → is'],['Physics is difficult for some students.','subject name → is'],['The scissors are on the table.','real plural object → are']],clue:'Ask whether the expression names one work/idea or several objects.'},
{id:'15',group:'FOR / WITH / AS WELL AS',title:'Ignore interrupting phrases',meaning:'Expressions such as together with, along with, as well as, accompanied by and with do not make the main subject plural. The main subject still controls the verb.',structure:'Subject + along with/as well as/together with + extra noun + verb.',examples:[['The captain, along with the players, is ready.','captain → is'],['Rina, as well as her friends, has arrived.','Rina → has'],['The teacher with two assistants is entering.','teacher → is'],['The boy, accompanied by his parents, was present.','boy → was']],clue:'Treat the interrupting phrase as extra information, not a second grammatical subject.'},
{id:'16',group:'EXAM MASTER',title:'Five-second agreement audit',meaning:'When an agreement question looks difficult, reduce it to the controlling subject. Ignore distracting phrases, identify number, then choose the finite verb. Finally read the whole sentence for meaning.',structure:'1 Find subject → 2 remove distractions → 3 decide singular/plural → 4 choose verb → 5 reread.',examples:[['The box of old books is heavy.','box → singular → is'],['Neither of the answers is correct.','neither → singular → is'],['Either the boys or the teacher is coming.','nearer subject teacher → is'],['There are many reasons.','reasons → plural → are']],clue:'SUBJECT → NUMBER → VERB → MEANING CHECK.'}
];

const Q=(q,o,a,e)=>({q,o,a,e});
const QUESTIONS=[
Q('The list of names ___ on the table.',['are','is','were','have'],1,'The head noun is list, which is singular.'),
Q('A box of pencils ___ missing.',['are','were','have','is'],3,'Box is the head noun; the of-phrase does not control agreement.'),
Q('Rina and Sita ___ friends.',['is','was','are','has'],2,'Two separate subjects joined by and normally take a plural verb.'),
Q('Every student ___ a notebook.',['have','has','are having','were'],1,'Every makes the subject grammatically singular.'),
Q('Each of the boys ___ ready.',['are','were','is','have'],2,'Each is singular; boys is inside the of-phrase.'),
Q('Everyone ___ the rule.',['know','knows','knowing','have known'],1,'Everyone is singular in standard school grammar.'),
Q('Neither of the answers ___ correct.',['are','were','is','have'],2,'Neither takes a singular verb in this standard school pattern.'),
Q('There ___ three books on the desk.',['is','was','has','are'],3,'The noun after there is three books, which is plural.'),
Q('There ___ a problem with the machine.',['are','is','were','have'],1,'The following noun is a singular problem.'),
Q('Either the students or the teacher ___ responsible.',['are','were','is','have'],2,'The nearer subject is teacher, which is singular.'),
Q('Either the teacher or the students ___ responsible.',['is','are','was','has'],1,'The nearer subject is students, which is plural.'),
Q('Five kilometres ___ a long walk.',['are','were','is','have'],2,'The distance is treated as one whole unit.'),
Q('The police ___ investigating the case.',['is','was','are','has'],2,'Police is a plural noun in this usage.'),
Q('The news ___ surprising.',['are','were','have','is'],3,'News is singular in standard school grammar.'),
Q('The team ___ ready for the match.',['are','were','is','have'],2,'The team is treated as one unit here.'),
Q('The team ___ arguing among themselves.',['is','are','was','has'],1,'Plural agreement is possible when members are emphasised; this sentence does that.'),
Q('She is the student who ___ hard.',['work','works','working','have worked'],1,'Who refers to the singular antecedent student.'),
Q('These are the books that ___ to me.',['belongs','belong','is belonging','has belonged'],1,'That refers to plural books.'),
Q('The teacher, along with the students, ___ present.',['are','were','is','have'],2,'Along with does not change the main subject teacher.'),
Q('Rina, as well as her friends, ___ arrived.',['have','are','has','were'],2,'Rina is the main singular subject.'),
Q('“Gulliver’s Travels” ___ a novel.',['are','were','is','have'],2,'The title represents one work.'),
Q('Mathematics ___ an important subject.',['are','were','have','is'],3,'The school subject name mathematics is treated as singular.'),
Q('Which sentence is correct?',['The students in my class studies daily.','The students in my class study daily.','The students in my class studies daily.','The students in my class has study daily.'],1,'Students is plural, so the Simple Present verb is study.'),
Q('Which sentence is correct?',['The quality of these books are excellent.','The quality of these books is excellent.','The quality of these books have excellent.','The quality of these books were excellent.'],1,'Quality is the head noun and is singular.'),
Q('Which sentence is correct?',['Each boy play well.','Each boys plays well.','Each boy plays well.','Each boy are playing well.'],2,'Each + singular noun takes singular verb plays.'),
Q('Which sentence is correct?',['Nobody know the answer.','Nobody knows the answer.','Nobody are knowing the answer.','Nobody have know the answer.'],1,'Nobody is singular.'),
Q('Which sentence is correct?',['Neither Rina nor her friends is ready.','Neither Rina nor her friends are ready.','Neither Rina nor her friends has ready.','Neither Rina nor her friends was ready.'],1,'The nearer subject friends is plural, so are is used.'),
Q('Which sentence is correct?',['Neither the players nor the captain are available.','Neither the players nor the captain is available.','Neither the players nor the captain have available.','Neither the players nor the captain were available.'],1,'The nearer subject captain is singular.'),
Q('“Ten years ___ a long time.”',['are','is','were','have'],1,'Ten years is treated as one period of time.'),
Q('“The cattle ___ grazing.”',['is','was','are','has'],2,'Cattle is plural in standard usage.'),
Q('Which sentence is correct?',['The news are good.','The news is good.','The news have good.','The news were good.'],1,'News is singular.'),
Q('Which sentence is correct?',['The captain, together with the players, are ready.','The captain, together with the players, is ready.','The captain together with the players have ready.','The captain, together with the players, were ready.'],1,'Together with does not create a compound subject.'),
Q('Which sentence is correct?',['There is many reasons.','There are many reasons.','There has many reasons.','There was many reasons.'],1,'Many reasons is plural.'),
Q('Which sentence is correct?',['There are a book on the desk.','There is a book on the desk.','There have a book on the desk.','There were a book on the desk.'],1,'A book is singular.'),
Q('In “A group of students is waiting”, the head noun is…',['students','of','group','waiting'],2,'Group is the head noun and controls is.'),
Q('In “The teacher with two assistants is entering”, the subject controlling is is…',['two','assistants','teacher','with'],2,'Teacher is the main subject.'),
Q('Which pair is correct?',['Everyone are / Each are','Everyone is / Each is','Everyone have / Each have','Everyone were / Each were'],1,'Both everyone and each are grammatically singular in these patterns.'),
Q('Which verb agrees with the plural subject “The boys”?',['plays','runs','goes','play'],3,'Plural subject boys takes the base verb play.'),
Q('Which verb agrees with “She”?',['go','play','writes','study'],2,'Third-person singular she takes writes in the Simple Present.'),
Q('Which sentence best follows the five-second audit?',['The list of names are ready.','The list of names is ready.','The list of names have ready.','The list of names were ready.'],1,'Remove the of-phrase: The list is ready.'),
Q('Choose the best completion: “The teacher and the student ___ talking.”',['is','are','has','was'],1,'Teacher + student are two separate subjects joined by and.'),
Q('Choose the best completion: “Either the teacher or the students ___ coming.”',['is','was','are','has'],2,'Students is the nearer plural subject.'),
Q('Choose the best completion: “She is one of the students who ___ hard.”',['works','work','is working','has work'],1,'Who refers to students, the plural antecedent.'),
Q('Choose the best completion: “She is the student who ___ hard.”',['work','works','are working','have worked'],1,'Who refers to student, singular.'),
Q('Choose the best completion: “Two hours ___ enough for the test.”',['are','were','is','have'],2,'The time is treated as one block/period here.'),
Q('Which sentence has correct agreement?',['The committee have approved the plan.','The committee has approved the plan.','The committee are approve the plan.','The committee were approve the plan.'],1,'The committee is treated as one body in this school-style sentence.')
];

const bankFor=mode=>mode==='practice'?QUESTIONS.slice(0,15):mode==='challenge'?QUESTIONS.slice(15,30):QUESTIONS.slice(25,45).concat(QUESTIONS.slice(5,25)).slice(0,20);

export default function EnglishSubjectVerbAgreementTopic({onBack,addXp=()=>{},finishSession=()=>{}}){
 const[lesson,setLesson]=useState(0);const[mode,setMode]=useState('learn');
 const start=m=>{setMode(m);window.scrollTo({top:0,behavior:'smooth'})};
 if(mode!=='learn')return <EnglishTimedQuiz title="Subject–Verb Agreement" mode={mode} getBank={bankFor} onModeChange={start} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession}/>;
 const l=LESSONS[lesson];
 return <main className="sva-wrap">
  <header className="sva-header"><button onClick={onBack}>← Language & Skills</button><span>ENGLISH • GRAMMAR • SUBJECT–VERB AGREEMENT</span></header>
  <section className="sva-hero"><div><span className="sva-kicker">MASTER THE CONTROLLING SUBJECT</span><h1>Subject–Verb Agreement</h1><p>Learn to find the real subject, ignore distracting nouns, handle special structures, and choose the exact verb form required in an exam.</p><div className="sva-stats"><b>{LESSONS.length}</b><span>deep lessons</span><b>{QUESTIONS.length}</b><span>assessment questions</span><b>3</b><span>assessment levels</span></div></div><aside><strong>CORE METHOD</strong><div>1. Find the subject</div><div>2. Find its number</div><div>3. Ignore distractions</div><div>4. Choose the verb</div><div>5. Read the sentence again</div></aside></section>
  <nav className="sva-modes"><button className="active">Learn</button><button onClick={()=>start('practice')}>Practice</button><button onClick={()=>start('challenge')}>Challenge</button><button onClick={()=>start('test')}>Final Test</button></nav>
  <section className="sva-learning"><nav className="sva-map"><span>LESSON MAP</span>{LESSONS.map((x,i)=><button key={x.id} className={i===lesson?'active':''} onClick={()=>{setLesson(i);window.scrollTo({top:0,behavior:'smooth'})}}><em>{x.id}</em><strong>{x.title}</strong><small>{x.group}</small></button>)}</nav>
   <article className="sva-lesson"><div className="sva-lesson-top"><span>{l.group}</span><b>{l.id} / {LESSONS.length}</b></div><h2>{l.title}</h2><p className="sva-meaning">{l.meaning}</p><section><span>STRUCTURE</span><div className="sva-structure">{l.structure}</div></section><section><span>EXAMPLES</span><div className="sva-examples">{l.examples.map((e,i)=><div key={i}><strong>{e[0]}</strong><p>{e[1]}</p></div>)}</div></section><div className="sva-clue"><span>EXAM CLUE</span><b>{l.clue}</b></div><div className="sva-lesson-nav"><button disabled={lesson===0} onClick={()=>setLesson(i=>Math.max(0,i-1))}>← Previous</button><button onClick={()=>setLesson(i=>Math.min(LESSONS.length-1,i+1))}>{lesson===LESSONS.length-1?'Restart lesson map':'Next lesson →'}</button></div></article></section>
  <section className="sva-bottom"><div><strong>Assessment rule</strong><p>Every level uses the common timed quiz engine: timer → answer questions → submission/timeout → marks + percentage → complete review with correct answer, your answer and explanation.</p></div><button onClick={()=>start('practice')}>Start Practice →</button></section>
 </main>;
}
