import React,{useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishSpeechWritingTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Speech Writing क्या है?',simple:'Speech यानी श्रोताओं के सामने बोलने के लिए तैयार किया गया organised text। इसमें clear topic, audience-friendly language, ideas और strong ending होती है।',meaning:'A speech is a structured piece of writing prepared to be delivered to an audience.',structure:'greeting → topic → key ideas → examples/reasons → call to action → closing',examples:['स्वच्छता पर भाषण','पेड़ बचाने पर भाषण','समय का महत्व'],clue:'Speech में paragraph-style facts के साथ audience से direct connection भी होना चाहिए।'},
{n:'02',group:'FOUNDATION',title:'Speech के 5 सवाल',simple:'हर speech लिखने से पहले पूछो: किस विषय पर? किस audience के लिए? उद्देश्य क्या है? कौन-से 2–3 मुख्य points होंगे? अंत में क्या message देना है?',meaning:'These questions define the purpose, audience and structure before drafting.',structure:'TOPIC + AUDIENCE + PURPOSE + KEY POINTS + MESSAGE',examples:['Topic: Cleanliness | Audience: school students | Purpose: motivate | Points: health, habits, responsibility'],clue:'Topic पता होना काफी नहीं; audience और purpose से language तय होती है।'},
{n:'03',group:'FORMAT',title:'Greeting / Salutation',simple:'शुरुआत में audience को appropriate greeting दें। School speech में “Respected Principal, teachers and my dear friends” जैसे forms useful हैं।',meaning:'The opening greeting respectfully addresses the intended audience.',structure:'Respected Principal/teachers + dear friends/audience',examples:['Respected Principal, teachers and my dear friends,','Good morning everyone.'],clue:'Greeting को situation और audience के अनुसार रखें; हर speech में एक ही fixed line जरूरी नहीं।'},
{n:'04',group:'OPENING',title:'Topic introduce कैसे करें',simple:'पहले कुछ sentences में topic साफ कर दो और बताओ कि वह important क्यों है।',meaning:'The introduction establishes the topic and its significance.',structure:'topic → importance → purpose',examples:['Today I am here to speak about the importance of trees and our responsibility to protect them.'],clue:'Opening इतना लंबा मत करो कि main topic देर से आए।'},
{n:'05',group:'BODY',title:'2–3 strong points बनाओ',simple:'Body में मुख्य विचारों को छोटे, clear paragraphs में रखो। हर point को reason, fact या simple example से support कर सकते हो।',meaning:'The body develops a few relevant ideas with supporting reasons or examples.',structure:'point 1 → support | point 2 → support | point 3 → support',examples:['Health benefits → cleaner surroundings → shared responsibility'],clue:'बहुत सारे points लिखने से speech बिखर सकती है; 2–3 strong points बेहतर हैं।'},
{n:'06',group:'BODY',title:'Audience से connect करना',simple:'Speech audience को ध्यान में रखकर लिखी जाती है। “We”, “our”, “let us” जैसे words shared responsibility या action दिखा सकते हैं।',meaning:'Audience connection makes the speech engaging and relevant.',structure:'we/our → shared problem → shared action',examples:['Let us keep our school clean.','We can make a difference by saving water.'],clue:'हर line में “friends” लिखना जरूरी नहीं; connection natural होना चाहिए।'},
{n:'07',group:'LANGUAGE',title:'Simple और persuasive language',simple:'Speech की language clear, confident और persuasive हो। कठिन vocabulary के बजाय ऐसे शब्द चुनो जो सुनते ही समझ आएँ।',meaning:'Spoken language should be clear, purposeful and persuasive.',structure:'clear claim + reason + motivating phrase',examples:['Small daily actions can create a cleaner school.','Together, we can protect our environment.'],clue:'Essay जैसी बहुत भारी language speech को बोलने में कठिन बना सकती है।'},
{n:'08',group:'LANGUAGE',title:'Facts, examples और questions',simple:'Relevant fact, example या rhetorical question speech को stronger बना सकते हैं। लेकिन facts वही रखें जो topic से सीधे जुड़ते हों।',meaning:'Relevant facts, examples and rhetorical questions can strengthen a speech.',structure:'claim → example/fact → audience thought',examples:['What kind of school do we want to leave for the next generation?'],clue:'Question का उद्देश्य audience को सोचने पर मजबूर करना है, केवल decoration नहीं।'},
{n:'09',group:'LINKING',title:'Connectors का उपयोग',simple:'First, moreover, however, therefore, finally जैसे connectors ideas को smoothly जोड़ते हैं।',meaning:'Connectors make transitions between ideas clear.',structure:'first → moreover → however → therefore → finally',examples:['First, we need awareness. Moreover, we need regular action. Therefore, let us begin today.'],clue:'हर sentence में connector डालना जरूरी नहीं; natural flow बनाए रखो।'},
{n:'10',group:'CLOSING',title:'Strong conclusion + call to action',simple:'अंत में main message को briefly दोहराओ और जरूरत हो तो audience से action लेने की appeal करो।',meaning:'The conclusion reinforces the message and may include a practical call to action.',structure:'message → action/hope → thanks',examples:['Let us save every drop of water and make conservation a daily habit. Thank you.'],clue:'Conclusion में नया major argument शुरू मत करो।'},
{n:'11',group:'TONE',title:'Formal speech vs friendly school speech',simple:'Speech का tone audience के हिसाब से बदलता है। School competition में respectful और confident tone अच्छा रहता है; casual slang से बचो।',meaning:'Tone should match the event while remaining respectful and audience-appropriate.',structure:'formal + warm + confident',examples:['“I strongly believe...”','“Let us work together...”'],clue:'Overly casual internet-style language exam speech में weak लग सकती है।'},
{n:'12',group:'COMMON TYPES',title:'किस प्रकार के speech topics आते हैं?',simple:'Environment, education, discipline, health, technology, road safety, national responsibility और social awareness जैसे topics common practice areas हैं।',meaning:'Knowing common themes helps you prepare flexible ideas and examples.',structure:'issue → importance → solutions → action',examples:['Save Trees','Importance of Education','Road Safety Awareness','Time Management'],clue:'Topic बदल सकता है, लेकिन structure और reasoning method largely वही रहता है।'},
{n:'13',group:'ERROR CONTROL',title:'Common mistakes',simple:'Greeting missing, topic unclear, points random, speech too essay-like, repetitive wording, no conclusion और weak call to action common errors हैं।',meaning:'Most speech-writing errors come from weak structure, poor audience awareness or an incomplete ending.',structure:'greeting → opening → points → connection → conclusion',examples:['Weak: “Trees are good. Trees are useful. Trees are important.”','Better: “Trees support life, protect our surroundings and deserve our daily care.”'],clue:'हर paragraph के बाद पूछो: क्या यह audience को topic समझा या action की दिशा दी?'},
{n:'14',group:'GUIDED BUILD',title:'Speech step-by-step बनाओ',simple:'पहले topic, audience और purpose लिखो। फिर greeting, introduction, 2–3 points, example/solution, conclusion और thanks जोड़ो।',meaning:'A repeatable drafting sequence makes speech writing faster and safer in exams.',structure:'plan → greet → introduce → develop → persuade → conclude → audit',examples:['Topic: Trees → audience: students → purpose: protect trees → 3 points → action'],clue:'पहले ideas की skeleton बनाओ, फिर polished sentences लिखो।'},
{n:'15',group:'FINAL AUDIT',title:'Final Speech Audit',simple:'Submit करने से पहले check करो: greeting सही है? topic clear है? 2–3 main points हैं? audience connection है? language बोलने योग्य है? conclusion और thanks हैं?',meaning:'The final audit checks structure, relevance, tone and delivery-friendly language.',structure:'GREETING ✓ TOPIC ✓ POINTS ✓ AUDIENCE ✓ LANGUAGE ✓ ACTION ✓ CLOSING ✓',examples:['Greeting ✓','Clear topic ✓','Strong points ✓','Call to action ✓','Thanks ✓'],clue:'Speech पढ़ते समय imagine करो कि तुम इसे वास्तव में audience के सामने बोल रहे हो।'}
];

const BANKS={
practice:[
['What is the main purpose of speech writing?',['to present organised ideas to an audience','to write a private diary','to list random facts','to write only a story'],0,'A speech is organised for delivery to an audience.'],
['Which is a suitable opening?',['Respected Principal, teachers and my dear friends,','Once upon a time...','Dear customer, please pay the bill.','Hey bro, what is up?'],0,'A school speech needs a respectful audience-appropriate greeting.'],
['What should the introduction mainly do?',['introduce the topic and its importance','give every detail at once','start with unrelated jokes','repeat the conclusion'],0,'The introduction sets up the topic and purpose.'],
['A strong speech body usually contains…',['a few clear points with support','random one-line ideas','only the greeting','only the ending'],0,'Focused points make a speech coherent and persuasive.'],
['Which phrase shows audience connection?',['Let us work together.','My favourite colour is blue.','The bus arrived.','He closed the book.'],0,'Let us creates a shared call for action.'],
['Which language is best for a school speech?',['clear, confident and audience-friendly','extremely confusing','only slang','mostly unexplained abbreviations'],0,'Speech language should be easy to understand when heard.'],
['What often strengthens a conclusion?',['a clear message or call to action','a new unrelated topic','a random list','another greeting'],0,'A conclusion should reinforce the message and can ask the audience to act.'],
['Which is a good final check?',['greeting, topic, points, audience connection and closing','only difficult vocabulary','only word count','only punctuation'],0,'A complete audit checks the major structural features.']
],
challenge:[
['A speech starts with “I was just thinking about many things today.” What is the main weakness?',['the topic and purpose are unclear','the greeting is too respectful','there are too many facts','the conclusion is too strong'],0,'The audience should understand the topic early.'],
['Which introduction is strongest for a speech on saving water?',['Today I am here to speak about saving water and why every student can help.','Water is a thing. I do not know what to say.','My favourite subject is English.','Let me tell you about yesterday.'],0,'It clearly introduces the topic and the audience’s possible role.'],
['Which body plan is best?',['problem → reasons → practical solutions → action','greeting → random story → joke → goodbye','conclusion → new topic → greeting','only repeated slogans'],0,'The first plan develops the topic logically toward action.'],
['Which sentence is most audience-focused?',['We can reduce waste by using reusable bottles.','I think bottles are interesting.','My cousin bought a bottle yesterday.','There was a bottle on the table.'],0,'We makes the advice relevant to the audience.'],
['Which connector best introduces a result?',['Therefore','Although','Meanwhile','First'],0,'Therefore commonly signals a result or conclusion from previous points.'],
['A speech uses long, difficult sentences that are hard to say aloud. What should be improved first?',['make the language clearer and more speakable','add more difficult words','remove the topic','delete the conclusion'],0,'A speech should be clear when heard, not only when read.'],
['Which ending is strongest for an environmental speech?',['Let us protect our trees today and make care for nature a daily habit. Thank you.','Anyway, my exam is next week.','I have nothing else to say about another topic.','Trees are trees.'],0,'It reinforces the message and gives a clear action.'],
['Why should a speech avoid too many unrelated points?',['the audience needs a focused, memorable message','unrelated points always improve marks','speeches should never contain examples','more topics automatically mean better quality'],0,'Focus helps the audience follow and remember the central message.']
],
test:[
['Which best describes a speech?',['structured writing prepared for delivery to an audience','a personal diary entry','a shopping list','a fictional chapter only'],0,'A speech is written to communicate a message to listeners.'],
['Which is the most appropriate greeting for a school speech?',['Respected Principal, teachers and my dear friends,','Dear customer,','Hey guys!!!','To whom it may concern,'],0,'The first greeting suits a formal school audience.'],
['The introduction should primarily…',['set the topic and explain its significance','present every supporting detail','give only the thanks','introduce an unrelated issue'],0,'The introduction prepares the audience for the main subject.'],
['Which body structure is strongest?',['point → reason/example → next point → solution','random points with no links','conclusion before introduction','greeting repeated after every line'],0,'Ideas should develop in a logical sequence.'],
['Which sentence best connects with the audience?',['Together, we can make our school cleaner.','I cleaned my room yesterday.','My neighbour has a garden.','The classroom has four windows.'],0,'Together and we create a shared audience connection.'],
['Which sentence is most suitable for spoken delivery?',['Every student can save water by turning off taps properly.','Utilisation of hydrological conservation methodologies is hereby mandated.','The thing is the thing and the thing happened.','Water, water, water, water, water.'],0,'The first is clear, natural and easy to say aloud.'],
['What is a suitable closing?',['Let us act today for a healthier future. Thank you.','Now I will begin a new unrelated story.','That is all about my favourite movie.','Hello, everyone.'],0,'A closing should reinforce the message and end respectfully.'],
['Which feature makes a speech persuasive?',['clear reasons, examples and a call to action','only difficult vocabulary','unrelated jokes','repetition without purpose'],0,'Persuasion grows from clear reasoning and purposeful language.'],
['What does “audience” mean?',['the people listening to the speech','the speech writer’s notebook','the title of the speech','the final sentence'],0,'Audience means the listeners or intended listeners.'],
['Which final audit is most complete?',['greeting, topic, points, tone, audience connection, action and closing','only spelling','only title length','only the number of paragraphs'],0,'A full audit checks both structure and communicative effectiveness.']
]};
const getBank=m=>BANKS[m]||BANKS.practice;

const EXAMPLES=[
{title:'Example 1 — Save Trees',topic:'Speech on the importance of trees.',parts:['SAVE TREES, SAVE LIFE','Respected Principal, teachers and my dear friends,','Good morning everyone. Today I am here to speak about the importance of trees. Trees give us oxygen, protect the soil and help keep our surroundings healthy.','But trees are useful only when we protect them. We can plant saplings, avoid unnecessary cutting and care for the trees around our school and homes.','Let us remember that protecting nature is not someone else’s duty. It is our shared responsibility. Let us plant, protect and respect trees. Thank you.']},
{title:'Example 2 — Importance of Education',topic:'Speech on the value of education.',parts:['EDUCATION: THE KEY TO PROGRESS','Respected Principal, teachers and my dear friends,','Education is not only about passing examinations. It teaches us how to think, solve problems and make responsible decisions. It opens the door to knowledge and opportunity.','As students, we should attend school regularly, ask questions and use what we learn in daily life. We should also respect teachers and support classmates who need help.','Let us value education not only for marks, but for becoming capable and responsible citizens. Thank you.']},
{title:'Example 3 — Road Safety',topic:'Speech on road safety awareness.',parts:['ROAD SAFETY: OUR SHARED RESPONSIBILITY','Respected Principal, teachers and my dear friends,','Every journey should end safely. Road accidents can be reduced when we follow simple rules and remain alert.','We should use helmets and seat belts, obey traffic signals and never use a phone while travelling in a way that distracts us. Students should also encourage family members to follow safety rules.','Safety begins with responsible behaviour. Let us follow traffic rules and encourage others to do the same. Thank you.']}
];

const SUBJECTIVE=['Write a speech for your school assembly on “Save Water”.','Prepare a speech on the importance of discipline in student life.','Write a speech on “Clean School, Healthy School”.','Prepare a speech for a school programme on the value of time.','Write a speech on responsible use of technology by students.','Prepare a speech on road safety awareness.','Write a speech encouraging students to plant and protect trees.','Prepare a speech on the importance of reading books.'];

export default function EnglishSpeechWritingTopic({onBack,addXp,finishSession}){
const[mode,setMode]=useState('learn');
const[lesson,setLesson]=useState(0);
const[example,setExample]=useState(0);
const[showSubjective,setShowSubjective]=useState(false);
const bank=useMemo(()=>getBank(mode),[mode]);
const go=(m)=>{setMode(m);window.scrollTo({top:0,behavior:'smooth'})};
const back=()=>{if(typeof onBack==='function'){onBack();return}const p=new URLSearchParams();p.set('page','language-skills');p.set('subject','english');p.set('languageSkills','1');p.delete('topic');p.delete('mode');window.location.assign(`${window.location.pathname}?${p.toString()}${window.location.hash||''}`)};
const finish=(result)=>{if(typeof addXp==='function')addXp(result.passed?20:5);if(typeof finishSession==='function')finishSession({subject:'English',area:'Language & Skills',topic:'Speech Writing',mode,result,at:new Date().toISOString()})};
return <div className="speech-topic-shell">
<header className="speech-topic-header"><div><div className="speech-eyebrow">ENGLISH • LANGUAGE & SKILLS • WRITING</div><h1>Speech Writing</h1><p>Plan clearly, speak naturally, persuade responsibly.</p></div><button type="button" className="speech-exit" onClick={back}>← Writing / Language & Skills</button></header>
<nav className="speech-mode-tabs" aria-label="Speech Writing sections"><button className={mode==='learn'?'active':''} onClick={()=>go('learn')}>Learn</button><button className={mode==='practice'?'active':''} onClick={()=>go('practice')}>Practice</button><button className={mode==='challenge'?'active':''} onClick={()=>go('challenge')}>Challenge</button><button className={mode==='test'?'active':''} onClick={()=>go('test')}>Final Test</button></nav>
{mode==='learn'?<main>
<section className="speech-hero-card"><div><span className="speech-chip">15 guided lessons</span><h2>Write a speech that sounds natural when spoken.</h2><p>Foundation → format → ideas → audience connection → persuasive control → final audit.</p></div><div className="speech-hero-stat"><strong>3</strong><span>model speeches</span></div></section>
<section className="speech-progress"><div><strong>Lesson {String(lesson+1).padStart(2,'0')} / {LESSONS.length}</strong><span>{LESSONS[lesson].group}</span></div><div className="speech-progress-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></section>
<section className="speech-lesson-card"><div className="speech-lesson-kicker">{LESSONS[lesson].n} • {LESSONS[lesson].group}</div><h2>{LESSONS[lesson].title}</h2><p className="speech-simple">{LESSONS[lesson].simple}</p><div className="speech-two-col"><article><h3>Core meaning</h3><p>{LESSONS[lesson].meaning}</p></article><article><h3>Exam structure</h3><p>{LESSONS[lesson].structure}</p></article></div><div className="speech-example-box"><h3>Examples</h3>{LESSONS[lesson].examples.map((x,i)=><p key={i}>• {x}</p>)}</div><div className="speech-clue"><strong>Exam clue:</strong> {LESSONS[lesson].clue}</div><div className="speech-lesson-nav"><button type="button" disabled={lesson===0} onClick={()=>setLesson(v=>Math.max(0,v-1))}>← Previous</button><button type="button" onClick={()=>setLesson(v=>Math.min(LESSONS.length-1,v+1))}>{lesson===LESSONS.length-1?'Stay on final lesson':'Next lesson →'}</button></div></section>
<section className="speech-models"><div className="speech-section-heading"><div><span>MODEL SPEECHES</span><h2>Three exam-friendly examples</h2></div><p>Notice the greeting, focused points, audience connection and closing.</p></div><div className="speech-model-layout"><div className="speech-model-list">{EXAMPLES.map((x,i)=><button type="button" key={x.title} className={example===i?'active':''} onClick={()=>setExample(i)}><span>0{i+1}</span><div><strong>{x.title.replace(/^Example \d+ — /,'')}</strong><small>{x.topic}</small></div></button>)}</div><article className="speech-model-card"><div className="speech-paper-label">MODEL {example+1}</div>{EXAMPLES[example].parts.map((x,i)=>i===0?<h3 key={i}>{x}</h3>:<p key={i}>{x}</p>)}</article></div></section>
<section className="speech-subjective"><div className="speech-section-heading"><div><span>SUBJECTIVE PRACTICE</span><h2>8 writing tasks</h2></div><p>These are independent writing prompts, not timed MCQs.</p></div><button type="button" className="speech-subjective-toggle" onClick={()=>setShowSubjective(v=>!v)}>{showSubjective?'Hide prompts':'Show all prompts'}</button>{showSubjective&&<div className="speech-subjective-grid">{SUBJECTIVE.map((q,i)=><article key={i}><b>{String(i+1).padStart(2,'0')}</b><p>{q}</p></article>)}</div>}</section>
<section className="speech-rule-strip"><div><strong>Golden formula</strong><p>Greeting → Topic → 2–3 strong points → Example/solution → Audience connection → Call to action → Thanks</p></div><button type="button" onClick={()=>go('practice')}>Start Practice →</button></section>
</main>:<main className="speech-quiz-wrap"><EnglishTimedQuiz key={mode} topic={{id:'speech',title:'Speech Writing'}} mode={mode} bank={bank} onFinish={finish} onExit={()=>go('learn')}/></main>}
</div>;
}
