import {EnglishReaderEngine} from './EnglishReaderChapter.jsx';
const q=(q,o,a,e)=>({q,o,a,e});

const study={
 chapter:3,
 title:'Saint Kabir',
 subtitle:'Saint Kabir • Supplementary Reader-IX',
 sourceNote:'Source: supplied English Reader PDF, Chapter 3, pp. 12–17. The lesson presents Kabir’s life, social criticism, teachings, legacy and textbook exercises.',
 intro:'Saint Kabir is presented as a major poet of the Bhakti Era and a fearless critic of caste divisions, untouchability, religious extremism, ritualism and social inequality. The lesson emphasises his message of equality, love, compassion, tolerance and brotherhood.',
 sections:[
  {title:'Kabir and the opening poem',flow:'The lesson introduces Kabir as one of the greatest poets of the Bhakti Era. It says he was the son of a widow, was looked after by Neema and Neeru in Varanasi, wrote from personal experience, and was known for forms named Panchmel, Khichdi or Sadhukdi. The opening translated poem stresses that human beings share one origin and are divided by worldly influences.',explanation:'पाठ Kabir को Bhakti Era के महान कवियों में रखता है। उनकी रचनाएँ personal experience पर आधारित बताई गई हैं। शुरुआती कविता का मुख्य भाव है कि मनुष्य एक ही मूल से आते हैं, लेकिन संसार की बुरी प्रवृत्तियाँ हमें अलग-अलग समूहों में बाँट देती हैं।',vocabulary:[['Bhakti Era','भक्ति काल'],['personal experience','व्यक्तिगत अनुभव'],['Panchmel','कई भाषाई रूपों का मिश्रित काव्य रूप'],['innumerable','असंख्य']],exam:'Explain the central idea of the opening poem: common human origin versus artificial division.',think:'Why does the poem question the knowledge that makes people separate? '},
  {title:'Kabir in his historical setting',flow:'The lesson places Kabir in the period 1448 A.D. to 1518 A.D. It describes Varanasi as a centre of Hindu orthodoxy and culture and says Kabir lived in poverty in a hostile environment. The lesson also notes tension involving Brahmanism and Islam and says orthodox Hindu priests and Maulavis complained against him to Emperor Sikander Lodi.',explanation:'पाठ के अनुसार Kabir का समय 1448 से 1518 ई. के बीच था। Varanasi को Hindu orthodoxy और culture का प्रमुख केंद्र बताया गया है। गरीबी और विरोध के वातावरण में Kabir ने धार्मिक तथा सामाजिक रूढ़ियों की आलोचना की।',vocabulary:[['orthodoxy','रूढ़ धार्मिक विचार'],['hostile','विरोधपूर्ण'],['ascendancy','प्रभुत्व'],['Maulavi','इस्लामी धार्मिक विद्वान']],exam:'Remember the historical period and why orthodox groups opposed Kabir.',think:'How can a hostile social environment make a reformer’s message more significant?'},
  {title:'Ramananda and Shaikh Taqi',flow:'In his youth Kabir became a disciple of Saint Ramananda, who taught faith in a personal God and equal access to spiritual fulfilment irrespective of caste or social status. Ramananda’s disciples included people from different occupations and communities. The lesson also says Kabir came into contact with Shaikh Taqi, a Sufi saint, and used knowledge of both Hinduism and Islam in his struggle against elitism and orthodoxy.',explanation:'युवा अवस्था में Kabir Saint Ramananda के शिष्य बने। Ramananda का संदेश जाति या सामाजिक स्थिति से परे व्यक्तिगत भक्ति और आध्यात्मिक मुक्ति पर आधारित था। Shaikh Taqi से संपर्क ने Kabir को Hinduism और Islam दोनों की समझ दी।',vocabulary:[['disciple','शिष्य'],['Vaishnava','विष्णु-भक्ति से जुड़ा धार्मिक परंपरा-सम्बन्धी'],['salvation','मोक्ष'],['elitism','विशेषाधिकारवादी श्रेष्ठता-बोध']],exam:'Connect Ramananda’s liberal social outlook and Shaikh Taqi’s influence with Kabir’s broad perspective.',think:'Why is learning across traditions useful when challenging social division?'},
  {title:'Rejecting ritualism and blind authority',flow:'Kabir rejected the authority of traditional scriptures when used to support blind beliefs and rituals. He opposed idol worship, the display of siddhis by yogis, caste and untouchability, and the idea that priests and Maulavis possessed a special monopoly over religion. The lesson describes his approach as bold, original, direct and simple.',explanation:'Kabir ने blind beliefs, बाहरी rituals, caste और untouchability का विरोध किया। वे यह नहीं मानते थे कि धार्मिक ज्ञान पर केवल Pandits या Maulavis का एकाधिकार है। उनका संदेश common people तक सरल और सीधी भाषा में पहुँचता था।',vocabulary:[['ritualism','कर्मकांड पर अत्यधिक जोर'],['siddhis','योगियों से जोड़ी जाने वाली विशेष शक्तियाँ'],['monopoly','एकाधिकार'],['pedantry','दिखावटी विद्वत्ता']],exam:'List the main forms of religious and social authority Kabir rejected.',think:'What makes a reformer’s language effective for ordinary people?'},
  {title:'Love, compassion and the rebel’s challenge',flow:'Through contact with people and personal experience, Kabir conveyed love, compassion and brotherhood. He emphasised that before God there is no Hindu or Muslim. The lesson calls him a rebel because he wanted to wipe out social evils and create a social order and authentic religion based on equality and brotherhood. His famous “burning stick” image is used to show the intensity of his protest.',explanation:'Kabir का message केवल विरोध नहीं था; उसमें love, compassion और brotherhood भी था। वे समाज की बुराइयों को दूर करके equality और brotherhood पर आधारित व्यवस्था चाहते थे।',vocabulary:[['compassion','करुणा'],['brotherhood','भाईचारा'],['fortitude','दृढ़ साहस'],['rebel','स्थापित गलत प्रथाओं के विरुद्ध खड़ा व्यक्ति']],exam:'Explain why Kabir is described as both a rebel and a teacher of love.',think:'How can strong criticism and compassion exist together?'},
  {title:'Tolerance and the story after Kabir’s death',flow:'Kabir preached tolerance and taught that one should answer pain with goodness. The lesson narrates that after his death both Hindus and Muslims claimed his body, one group wanting cremation and the other burial. When the shroud was removed, flowers were found instead, and the flowers were shared. The episode symbolises brotherhood between the two communities.',explanation:'Kabir tolerance की शिक्षा देते थे। मृत्यु के बाद शरीर के संस्कार को लेकर Hindu और Muslim समुदायों में मतभेद का वर्णन आता है, लेकिन शroud हटाने पर flowers मिलते हैं जिन्हें दोनों समुदायों ने बाँट लिया। यह कहानी brotherhood का प्रतीक बनती है।',vocabulary:[['tolerance','सहनशीलता'],['cremation','दाह-संस्कार'],['burial','दफ़न'],['shroud','कफ़न']],exam:'Describe what the flowers symbolised after Kabir’s death.',think:'Why does the lesson end this episode with sharing rather than conflict?'},
  {title:'Kabir’s seven broad teachings',flow:'The lesson summarises Kabir’s teaching as rejection of caste and untouchability; denial of special religious authority to priests and mullas; rejection of blind scriptural authority; disapproval of prideful book-learning disconnected from common people; rejection of Hindu-Muslim discord; no preference for one religion; and condemnation of idolatry, superstition and sectarian externalism.',explanation:'सात बिंदुओं में Kabir की शिक्षाओं का सार equality, anti-caste outlook, blind belief का विरोध, religious monopoly का विरोध और Hindu-Muslim unity के रूप में सामने आता है।',vocabulary:[['repudiation','दृढ़ अस्वीकृति'],['sectarianism','सांप्रदायिक पक्षधरता'],['idolatry','मूर्ति-पूजा'],['discord','कलह/असहमति']],exam:'Be ready to summarise the seven teaching points in your own words.',think:'Which of the seven points directly attacks social division, and why?'},
  {title:'People’s poet and lasting relevance',flow:'Kabir earned his livelihood as a weaver and remained on a path of virtue and reform. The lesson calls him a saint-poet and a people’s poet whose songs remain popular in north India. It mentions the Kabir Panth, Saint Guru Nanak’s influence from Kabir and verses of Kabir in the Adi Grantha. The final message connects equality, love, communal amity and brotherhood with present-day social challenges.',explanation:'Kabir का जीवन weaving से जुड़ा रहा और उनकी कविताएँ common people तक पहुँचीं। Kabir Panth और बाद की परंपराओं में उनकी influence का उल्लेख है। पाठ का निष्कर्ष है कि equality, love और communal amity का message आज भी मार्गदर्शक हो सकता है।',vocabulary:[['livelihood','जीविका'],['amity','मैत्री/सौहार्द'],['revered','सम्मानित'],['beacon','मार्गदर्शक प्रकाश']],exam:'Explain why Kabir is remembered even after centuries and how his message remains relevant.',think:'Which part of Kabir’s message is most useful for a society facing division?' }
 ],
 glossary:[['Bhakti','भक्ति; ईश्वर के प्रति समर्पित भाव'],['orthodoxy','रूढ़ धार्मिक विश्वास'],['untouchability','अस्पृश्यता'],['ritualism','कर्मकांडवाद'],['tolerance','सहनशीलता'],['compassion','करुणा'],['brotherhood','भाईचारा'],['sectarianism','सांप्रदायिक विभाजन'],['reform','सुधार'],['amity','सौहार्द'],['weaver','बुनकर'],['livelihood','जीविका']],
 wordStudy:[['castigate','कड़ी निंदा करना'],['vehemently','जोश/तीव्रता से'],['repudiate','अस्वीकार करना'],['non-conformist','रूढ़ व्यवस्था के अनुरूप न चलने वाला'],['pedantic','दिखावटी विद्वत्ता से जुड़ा'],['preach tolerance','सहनशीलता का संदेश देना'],['communal amity','समुदायों के बीच सौहार्द']],
 textbookAnswers:[
  ['Who was Kabir? What did he think about caste system and division of mankind?','The lesson presents Kabir as a major Bhakti-era poet who opposed caste division and untouchability. He taught that people share a common human origin and should live with equality and brotherhood.'],
  ['Why did orthodox Hindu priests and Maulavis hate Kabir?','Because he criticised religious orthodoxy, superstition, ritualism and their claimed religious authority, while challenging Hindu-Muslim divisions.'],
  ['What did Kabir preach? To whom did he appeal?','He preached equality, love, compassion, tolerance, brotherhood and devotion beyond caste or religious division. His appeal was especially to ordinary and non-literate people rather than only elites.'],
  ['What happened with Kabir’s body after his death?','The lesson says Hindus and Muslims claimed the body for different rites, but when the shroud was removed, flowers were found and were shared by both communities.'],
  ['Why is Kabir remembered even today?','His songs and teachings continue to stress unity, non-violence, love, compassion, tolerance, truth, equality and belief in one God.'],
  ['What kind of social order did Kabir want to bring about?','A social order and authentic religion based on equality and brotherhood, free from caste-based discrimination and sectarian hostility.'],
  ['What do you mean by tolerance? What did Kabir say in this connection?','Tolerance means accepting difference without hatred or unjust hostility. The lesson says Kabir taught that one should give flowers in return to those who give pain and sorrow.'],
  ['Summarise Kabir’s teachings. How far are they relevant in contemporary society?','His teachings reject caste discrimination, untouchability, blind belief, religious monopoly and Hindu-Muslim discord while promoting equality, love, compassion, tolerance and brotherhood. These values remain relevant wherever social or communal division persists.']
 ],
 revision:[['Period','1448 A.D. – 1518 A.D. according to the supplied lesson.'],['Mentor','Saint Ramananda.'],['Other influence','Shaikh Taqi, described as a Sufi saint.'],['Main targets of criticism','Caste, untouchability, blind beliefs, ritualism, religious monopoly and sectarian division.'],['Positive message','Equality, love, compassion, tolerance and brotherhood.'],['Legacy','Kabir Panth; influence noted on Guru Nanak and verses in Adi Grantha.']],
 discussion:['The essence of religion lies in love and forgiveness. Discuss this idea with reference to Kabir’s teachings.'],
 activities:['Recite two verses of Kabir and translate them into English.','Do a project work on Kabir Panth and its relevance today; the source suggests taking help from a teacher or a reference book in the school library.'],
 extra:'The supplied pages end with A. Let’s Answer, B. Let’s Discuss and C. Let’s Do. The chapter does not show a separate grammar exercise, so none has been invented.'
};

const practice=[
 q('Kabir is presented in the lesson as one of the greatest poets of the:', ['Bhakti Era','Modern Age','Victorian Age','Romantic Age'],0,'The opening biography identifies Kabir as a great poet of the Bhakti Era.'),
 q('What is the central idea of the opening poem?', ['Human beings share a common origin despite artificial divisions','Only one community can seek truth','People are divided by nature into fixed groups','Religious labels are more important than human life'],0,'The poem stresses one origin and questions the divisions created by the world.'),
 q('According to the lesson, Kabir lived during:', ['1448–1518 A.D.','1248–1318 A.D.','1548–1618 A.D.','1648–1718 A.D.'],0,'The supplied biography gives 1448 A.D. to 1518 A.D.'),
 q('Who was Kabir’s mentor according to the lesson?', ['Saint Ramananda','Saint Guru Nanak','Shaikh Taqi','Sikander Lodi'],0,'The lesson names Saint Ramananda as his mentor.'),
 q('Shaikh Taqi is described as a:', ['Sufi saint','Hindu priest','poet of the court','military commander'],0,'The text calls Shaikh Taqi a Sufi saint.'),
 q('Which practice did Kabir strongly reject?', ['Untouchability','Brotherhood','Compassion','Tolerance'],0,'Untouchability is one of the social evils he vehemently denounced.'),
 q('Kabir’s appeal was mainly directed to:', ['Common and non-literate people','Only religious elites','Only royal rulers','Only scholars'],0,'The lesson says his appeal was to non-literate masses and not merely to elites.'),
 q('What did Kabir teach about Hindu and Muslim identity before God?', ['There is no such division before God','One community is superior','Religious division is necessary','Only priests can decide identity'],0,'He emphasised that before God there is no Hindu or Muslim.'),
 q('What does the lesson use the flowers after Kabir’s death to symbolise?', ['Brotherhood between communities','Victory of one sect','A royal punishment','A new ritual system'],0,'The flowers are shared and symbolise brotherhood.'),
 q('Kabir earned his livelihood primarily as a:', ['Weaver','Merchant','Soldier','Farmer'],0,'The lesson says he earned his livelihood at the loom.'),
 q('Which value is repeatedly linked with Kabir’s message?', ['Equality','Sectarianism','Untouchability','Religious monopoly'],0,'Equality is central to the lesson’s presentation of Kabir.'),
 q('What kind of language did Kabir use for common people?', ['Direct and simple','Highly technical','Only Sanskrit','Only Persian'],0,'The lesson explicitly describes his approach as direct and simple.'),
 q('Which organization is named as tracing its origin to Kabir’s preaching?', ['Kabir Panth','Nehru Institute','Arya Samaj','Brahmo Samaj'],0,'The final section mentions the Kabir Panth.'),
 q('The lesson says many verses of Kabir are found in the:', ['Adi Grantha','Ramcharitmanas','Arthashastra','Akbarnama'],0,'It states that the Adi Grantha contains many verses of Kabir.'),
 q('Which phrase best captures Kabir’s social ideal?', ['Equality and brotherhood','Caste hierarchy and ritual privilege','Sectarian competition','Blind obedience'],0,'The lesson repeatedly presents equality and brotherhood as his social ideal.')
];

const challenge=[
 q('Why does the opening poem challenge the idea of social separation?', ['It argues that common human origin makes rigid division difficult to justify','It argues that people should stop speaking different languages','It claims all occupations are identical','It says history has no importance'],0,'The poem contrasts one common origin with divisions created by worldly influence.'),
 q('What makes Kabir a non-conformist in the lesson?', ['He refuses to accept unjust caste, ritual and religious authority simply because tradition supports them','He refuses to speak to ordinary people','He rejects every form of social interaction','He supports every existing institution'],0,'Non-conformism is shown through his criticism of established but unjust practices.'),
 q('Why is Ramananda important to Kabir’s intellectual development?', ['His liberal teaching connected spiritual faith with equality across caste and status','He taught Kabir to value caste hierarchy','He made Kabir a royal officer','He opposed all forms of devotion'],0,'The source connects Ramananda with personal devotion and concern for low-caste people.'),
 q('What does the mention of Shaikh Taqi suggest about Kabir’s outlook?', ['He drew on contact with more than one religious tradition while challenging orthodoxy','He rejected all knowledge of Islam','He became a court historian','He stopped questioning religious practice'],0,'The lesson says Kabir used knowledge of both Hinduism and Islam.'),
 q('Why did Kabir reject the monopoly of Pandits and Maulavis?', ['He did not accept that only religious specialists could act as guardians of religion and God','He wanted to become the only religious authority','He disliked education itself','He wanted all books destroyed'],0,'The text says he did not believe religious authority was a monopoly of Pandits and Maulavis.'),
 q('Which pair best represents the two sides of Kabir’s message?', ['Strong rejection of social injustice + positive appeal to love and brotherhood','Silence + withdrawal from society','Royal power + military discipline','Caste privilege + ritual competition'],0,'His reform message combines criticism of injustice with constructive human values.'),
 q('Why is Kabir called a “rebel” in the lesson?', ['He wanted to wipe out social evils and reform society around equality and brotherhood','He wanted to create political violence','He opposed every form of community','He sought royal office'],0,'The supplied text directly connects the rebel label with social reform.'),
 q('What does the flowers episode imply about the result of Kabir’s message?', ['His message can unite communities even where ritual differences create conflict','Religious conflict can never be resolved','Flowers have a special legal status','Only one funeral custom is valid'],0,'The episode symbolically turns a dispute into shared remembrance.'),
 q('Which statement best explains why simple language mattered to Kabir?', ['It allowed his social and spiritual message to reach ordinary people beyond elite circles','It made his ideas less serious','It removed the need for personal experience','It limited his audience to scholars'],0,'The lesson explicitly says his appeal was to the non-literate masses and his approach was direct and simple.'),
 q('How are Kabir’s livelihood and his social appeal connected?', ['He remained a working weaver while becoming a people’s poet, linking reformist teaching with common life','He became a court poet and stopped working','His livelihood depended on religious office','He withdrew from ordinary occupations'],0,'The lesson stresses that he continued as a weaver and was a poet of the people.'),
 q('Which contemporary problem does the lesson itself identify as making Kabir’s message important?', ['Communal violence and caste conflict','Lack of royal patronage','Decline of handwriting','Shortage of libraries'],0,'The concluding paragraph explicitly mentions communal violence, caste conflicts and related social crises.'),
 q('Which inference best follows from the seven teaching points?', ['Kabir opposed both social hierarchy and the external religious practices that strengthened division','Kabir wanted to replace one religious monopoly with another','Kabir supported caste while opposing language differences','Kabir rejected compassion as weakness'],0,'The seven points consistently reject hierarchy, monopoly, blind belief and sectarianism.'),
 q('Why is “no preference for any religion” significant in the lesson?', ['It supports the text’s insistence on equality rather than sectarian superiority','It proves Kabir rejected every form of faith','It makes his message purely political','It means religion had no place in his thought at all'],0,'The point is presented alongside rejection of Hindu-Muslim discord and sectarianism.'),
 q('Which evidence best supports the claim that Kabir’s message outlived his own period?', ['His songs remained popular, Kabir Panth developed, Guru Nanak was influenced by him, and his verses appear in Adi Grantha','He served a ruler for many years','His poems were never remembered','Only one manuscript mentions him'],0,'The final section lists multiple forms of lasting influence.'),
 q('Why is equality a stronger summary than “religious criticism” alone?', ['The lesson criticises caste and ritual while also positively promoting love, brotherhood and communal amity','Kabir only criticised priests and nothing else','Equality appears only in the title','The lesson never discusses social relations'],0,'Equality ties together both the negative critique and the positive social vision.'),
 q('How does the opening poem support the lesson’s later teaching points?', ['The poem’s common-human-origin idea becomes the basis for rejecting caste and sectarian separation','The poem contradicts the later discussion of equality','The poem is only a biography with no theme','The poem supports religious monopoly'],0,'Its central idea directly aligns with the later anti-division teachings.'),
 q('What does “people’s poet” imply in this context?', ['Kabir’s language, songs and ideas reached ordinary people rather than remaining confined to elites','Kabir wrote only for rulers','Kabir avoided social questions','Kabir had no connection with common life'],0,'The text stresses his appeal to non-literate masses and continuing popularity among common people.'),
 q('Which response best fits Kabir’s teaching on pain and sorrow?', ['Answer harm with goodness and maintain tolerance','Return harm with greater harm','Ignore every social injustice','Create new divisions'],0,'The lesson specifically links his teaching with giving flowers in return for pain and sorrow.'),
 q('Why is the lesson careful to mention both rejection and compassion?', ['Kabir is presented as a reformer who opposed harmful practices without abandoning love and humanity','The author wants to show that he changed subjects frequently','Compassion is unrelated to his social criticism','The two ideas contradict each other'],0,'The lesson balances forceful protest with a positive ethical message.'),
 q('What is the strongest exam-ready conclusion from the chapter?', ['Kabir’s lasting relevance lies in combining resistance to injustice with equality, tolerance and brotherhood','Kabir’s importance rests only on historical dates','Kabir is remembered only because of one poem','Kabir’s message was limited to medieval ritual practice'],0,'This conclusion integrates the source’s historical, social and contemporary relevance sections.'),
 q('Which statement best distinguishes ritual from the deeper value Kabir emphasises?', ['External ritual is not enough without humane values such as equality, compassion and brotherhood','Ritual is always meaningless','Only books matter in religion','Social values are separate from religion'],0,'Kabir’s criticism targets external and blind practices while his positive message stresses humane values.'),
 q('If a society has caste conflict and communal hostility, which part of Kabir’s teaching is most directly applicable?', ['Equality, no preference for one religion and communal amity','Priestly monopoly','Sectarian externalism','Untouchability'],0,'These values directly address the forms of division named in the lesson.'),
 q('Why can Kabir be described as both spiritually concerned and socially reformist?', ['He spoke about God while also challenging caste, untouchability, superstition and social division','He avoided religion entirely','He focused only on political power','He rejected all ethical values'],0,'The lesson combines spiritual devotion with a reformist social outlook.'),
 q('What is the best inference from Kabir continuing as a weaver?', ['His reform message remained connected with working people and ordinary life','He rejected all learning','He lacked any spiritual interest','He wanted to avoid public communication'],0,'The source pairs his livelihood at the loom with his identity as a people’s poet.'),
 q('Which idea best links Kabir’s life, poetry and legacy?', ['A common-human vision expressed in direct poetry and carried forward through continuing traditions','A desire for social separation','A preference for elite scholarship','A rejection of communication across communities'],0,'His biography, poetry and legacy are all organised around breaking unjust divisions.')
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`final-${i}`}));

export function EnglishReaderChapter3({initialMode='learn',onBack,addXp,finishSession}){
 return <EnglishReaderEngine study={{...study}} initialMode={initialMode} onBack={onBack} addXp={addXp} finishSession={finishSession}/>;
}
export const englishReaderChapter3Meta={title:study.title,author:'Saint Kabir',sourceNote:study.sourceNote,modeCounts:{practice:practice.length,challenge:challenge.length,final:finalTest.length}};
export {study as englishReaderChapter3Study};
