import {EnglishReaderEngine} from './EnglishReaderChapter.jsx';
const q=(q,o,a,e)=>({q,o,a,e});
const study={chapter:6,title:'The Accidental Tourist',subtitle:'Bill Bryson • Supplementary Reader-IX',sourceNote:'Source: supplied English Reader PDF, Chapter 6, pp. 29–32. This chapter covers Bill Bryson’s travel mishaps, absent-mindedness, family reactions and the final airline-ticket confusion.',intro:'Bill Bryson humorously describes himself as a difficult traveller. The lesson builds comedy from everyday mistakes with luggage, food, seats, notebooks and airline records, while his wife repeatedly reacts to his confusion and clumsiness.',sections:[
{title:'A traveller who struggles with real life',flow:'Bryson says that, among the things he is not good at, living in the real world stands out. He is amazed by how other people organise everyday details when he finds many ordinary tasks difficult. Travel gives these weaknesses especially comic opportunities.',explanation:'Bryson बताता है कि वह real world की practical situations में अक्सर confused रहता है। जहाँ दूसरे लोग छोटी-छोटी चीजें आसानी से संभालते हैं, वहाँ उसे travel के समय बार-बार problems होती हैं।',vocabulary:[['outstanding','विशेष रूप से स्पष्ट'],['constantly','लगातार'],['wonder','आश्चर्य करना'],['practical','व्यावहारिक']],exam:'Explain the self-description that makes the chapter humorous.',think:'Why is self-mockery effective in travel writing?'},
{title:'The dangerous-looking zipper and lost contents',flow:'At Logan Airport, Bryson remembers a previous journey when he joined British Airways. He notices a problem with the zipper on his carry-on bag, struggles to open it and discovers that the bag has given way. Newspapers, papers, passport, money and other belongings are scattered in confusion.',explanation:'Logan Airport पर carry-on bag की zipper के कारण Bryson की चीजें बिखर जाती हैं। Passport, money, papers और दूसरी travel items को संभालना मुश्किल हो जाता है। यही घटना उसकी absent-mindedness और comic chaos दिखाती है।',vocabulary:[['carry-on','हाथ में ले जाने वाला bag'],['zipper','चेन'],['scattered','बिखरा हुआ'],['belongings','सामान']],exam:'Remember the Logan Airport luggage incident as evidence of his clumsiness.',think:'How can a small mechanical problem become a comic disaster?'},
{title:'“My finger! My fingers!”',flow:'During the struggle with the bag, Bryson gets his finger caught in the zipper. He reacts dramatically and imagines that he may be badly injured. The moment becomes humorous because his panic is out of proportion to the actual problem.',explanation:'Bag की zipper में finger फँस जाने पर Bryson बहुत घबरा जाता है और dramatic प्रतिक्रिया देता है। यह scene बताता है कि छोटी परेशानी भी उसकी imagination में बड़ी disaster बन सकती है।',vocabulary:[['panic','घबराहट'],['hysteria','अत्यधिक घबराहट'],['out of proportion','स्थिति से अधिक बड़ा'],['dramatic','अतिनाटकीय']],exam:'Why is the finger incident comic rather than tragic?',think:'How does exaggeration create humour?'},
{title:'The wife as a witness to confusion',flow:'Bryson’s wife is used to his travel disasters. At one point she looks at him with an expression that suggests disbelief. Her reactions help readers judge how unusual his behaviour is and give the narration a second comic perspective.',explanation:'Bryson की पत्नी उसकी travel mistakes से परिचित है। उसकी प्रतिक्रियाएँ यह दिखाती हैं कि narrator की परेशानी कितनी असामान्य और मज़ेदार लगती है।',vocabulary:[['disbelief','अविश्वास'],['expression','भाव-भंगिमा'],['accustomed','आदी'],['witness','प्रत्यक्ष देखने वाला']],exam:'Explain the function of the wife’s reactions in the narrative.',think:'Why can a second person’s reaction make a story funnier?'},
{title:'Fear of disasters in the air',flow:'Bryson admits that he usually expects some kind of catastrophe when he travels. He worries about accidents and awkward public situations, which makes his journeys more stressful. Yet the narration keeps the tone light by turning fear into self-aware humour.',explanation:'Travel करते समय Bryson को किसी disaster की आशंका बनी रहती है। उसकी anxiety और real-world clumsiness मिलकर comic situations पैदा करती हैं, लेकिन narrator खुद अपनी कमजोरियों पर हँसता भी है।',vocabulary:[['catastrophe','बड़ी विपत्ति'],['anxiety','चिंता'],['awkward','असहज'],['self-aware','अपने व्यवहार से परिचित']],exam:'How does anxiety contribute to the chapter’s humour?',think:'Can fear be funny when the writer looks back on it safely?'},
{title:'The spilled drink episode',flow:'On another occasion Bryson knocks a soft drink onto a woman’s lap. The flight attendant cleans the mess and brings a replacement drink. He then manages to spill it again. The repeated accident turns embarrassment into comic escalation.',explanation:'एक बार Bryson ने एक महिला की गोद पर soft drink गिरा दिया। Flight attendant ने सफाई की और नया drink दिया, लेकिन Bryson उसे भी गिरा बैठता है। Repetition से scene और अधिक हास्यास्पद बन जाता है।',vocabulary:[['spill','गिरा देना'],['lap','गोद'],['replacement','बदली हुई वस्तु'],['escalation','स्थिति का और बढ़ जाना']],exam:'Why does the second spill make the first mistake funnier?',think:'What role does repetition play in comic writing?'},
{title:'The worst plane journey',flow:'Bryson describes another flight as a particularly bad experience. He fidgets with a notebook and drinks, behaves awkwardly around fellow passengers and makes the cramped seat into an arena for small accidents. His wife and nearby travellers react with a mixture of patience and surprise.',explanation:'एक अन्य flight को वह अपने worst experiences में रखता है। Notebook, drinks, seat और आसपास के passengers के बीच उसकी छोटी-छोटी गलतियाँ लगातार comedy पैदा करती हैं।',vocabulary:[['fidget','बेचैनी से हिलना-डुलना'],['cramped','तंग जगह वाला'],['passenger','यात्री'],['patience','धैर्य']],exam:'List the everyday behaviours that make the flight episode comic.',think:'Why are ordinary mistakes enough for good humour?'},
{title:'Food, children and the frequent-flyer problem',flow:'Bryson also describes the difficulty of eating quietly and controlling small habits on a flight. He jokes about children, food and the possibility of future bills. He notes that although his wife may manage some travel details better, he repeatedly forgets to ask about his frequent-flyer miles.',explanation:'Flight में food और छोटे habits को manage करना भी Bryson के लिए कठिन है। वह children, food और खर्चों पर मज़ाक करता है। साथ ही frequent-flyer miles के बारे में पूछना भूल जाने पर स्वयं को हास्यास्पद स्थिति में पाता है।',vocabulary:[['frequent-flyer miles','उड़ानों से मिलने वाले travel points'],['frugal','कम खर्च करने वाला'],['bill','खर्च का विवरण'],['forgetful','भुलक्कड़']],exam:'Connect forgetfulness with the frequent-flyer details.',think:'How does the chapter turn forgetfulness into a recurring character trait?'},
{title:'The Australia ticket mix-up',flow:'Bryson finally recalls an airline check-in incident involving a trip to Australia. The clerk says the ticket is in the name of B. Bryson while his card is in the name of W. Bryson. He cannot believe the airline has treated the two names as unrelated, and jokes about his close relationship with William and Bill.',explanation:'Australia flight के समय ticket पर B. Bryson और card पर W. Bryson देखकर airline clerk समस्या बताती है। Bryson मज़ाकिया ढंग से समझाता है कि Bill और William उसी व्यक्ति के नाम हैं, लेकिन system के लिए वे अलग लगते हैं।',vocabulary:[['entitled','अधिकृत'],['relationship','संबंध'],['venerable','पुराना और सम्मानित'],['mix-up','गड़बड़ी']],exam:'Explain the final ticket-name confusion and why it is funny.',think:'What does the final episode reveal about bureaucracy and common sense?'}],
glossary:[['clumsy','अनाड़ी'],['absent-minded','भुलक्कड़/ध्यान भटकने वाला'],['catastrophe','विपत्ति'],['panic','घबराहट'],['luggage','यात्रा का सामान'],['scattered','बिखरा हुआ'],['cramped','तंग जगह वाला'],['frequent-flyer','बार-बार उड़ान भरने वाला'],['mix-up','गड़बड़ी'],['bureaucracy','नियमों की जटिल प्रशासनिक प्रक्रिया'],['embarrassment','लज्जा/झेंप'],['self-mocking','अपने ऊपर मज़ाक करने वाला']],
wordStudy:[['real world','रोजमर्रा की practical दुनिया'],['give way','टूटकर/खुलकर रास्ता देना'],['out of proportion','वास्तविक स्थिति से बहुत अधिक बड़ा'],['a close and venerable relationship','Bill और William नामों के संबंध पर humorous phrase'],['take catastrophe in my stride','मुश्किल को भी humour के साथ लेना'],['accidental tourist','ऐसा traveller जिसकी गलतियाँ यात्रा को accidental comedy बना दें']],
textbookAnswers:[['Have you ever travelled by a train or a plane? Do you remember an interesting incident?','The exercise invites a personal response. A learner can describe one memorable travel incident, focusing on what happened and why it was interesting.'],['Why does the writer say that he is easily confused?','He gives repeated examples of luggage trouble, spills, forgotten details and airline-name confusion to show that practical travel situations often confuse him.'],['Describe the incident that exasperated the narrator at Logan Airport in Boston.','The airport luggage incident became chaotic when the carry-on zipper caused trouble, his belongings spilled out and he panicked after catching a finger in the zipper.']],
revision:[['Writer','Bill Bryson.'],['Tone','Humorous, self-deprecating and observational.'],['Recurring trait','Forgetfulness and practical clumsiness during travel.'],['Logan Airport','Carry-on bag/zipper disaster and exaggerated panic.'],['Plane episode','Repeated spill and other awkward behaviour.'],['Ending','Ticket name B. Bryson versus card name W. Bryson.']],
discussion:['Travel light is a golden rule to make your journeys easier. Discuss the idea with examples from the chapter.'],activities:['Do a project work on the modes of transportation.'],extra:'The supplied Chapter 6 pages show Literature, A. Let’s Answer, B. Let’s Discuss and C. Let’s Do. No separate grammar exercise is shown, so none has been invented.'};
const practice=[
q('Who wrote The Accidental Tourist?',['Bill Bryson','M. Asaduddin','Ruskin Bond','U. R. Anantha Murthy'],0,'The chapter credits Bill Bryson.'),q('How does Bryson describe himself?',['Poor at living in the real world','An expert pilot','A professional mechanic','A railway officer'],0,'His self-description establishes the comic tone.'),q('Where does an important luggage incident happen?',['Logan Airport in Boston','Saharanpur Station','Chittor','Rohana'],0,'The airport episode is set at Logan Airport in Boston.'),q('What causes trouble with the carry-on bag?',['The zipper','A broken wheel','Rain','A lost ticket'],0,'The zipper creates the main luggage problem.'),q('What gets caught in the zipper?',['His finger','His passport','His shoe','His watch'],0,'He catches a finger in the zipper.'),q('How does he react?',['With exaggerated panic','With complete calm','By leaving the airport','By calling a lawyer'],0,'His reaction is deliberately comic and exaggerated.'),q('Who often reacts to his travel mishaps?',['His wife','The station master','A teacher','A tour guide'],0,'His wife provides a recurring reaction to his behaviour.'),q('What happens to a soft drink?',['He spills it on a woman’s lap','He loses it at check-in','He throws it away','A child drinks it'],0,'He knocks the drink onto a woman’s lap.'),q('What happens after the flight attendant brings a replacement?',['He spills that drink too','He drinks it immediately','He gives it away','He leaves the plane'],0,'The repeated spill escalates the comedy.'),q('What does Bryson often expect while travelling?',['A catastrophe','A promotion','A prize','A quiet holiday'],0,'He says he always has catastrophes in mind when he travels.'),q('What does he forget to ask about?',['Frequent-flyer miles','The weather','The train platform','His passport number'],0,'He jokes about never remembering to ask about his miles.'),q('What name appears on the card?',['W. Bryson','B. Smith','William Bond','J. Bryson'],0,'The final mix-up involves W. Bryson and B. Bryson.'),q('What name appears on the ticket?',['B. Bryson','W. Bryson','Bill Smith','Bryson W.'],0,'The airline system treats B. Bryson as different.'),q('What is the main style of the chapter?',['Humorous travel memoir','Historical biography','Mystery story','Science report'],0,'The chapter turns travel mistakes into humour.'),q('What is a key character trait shown?',['Forgetfulness','Cruelty','Silence','Arrogance'],0,'Forgetfulness repeatedly causes his travel problems.')];
const challenge=[
q('Why is self-mockery central to the chapter?', ['Bryson turns his own failures into the source of humour rather than blaming everyone else','It proves he dislikes travel','It removes all detail from the story','It makes his wife the main narrator'],0,'His willingness to laugh at himself lets ordinary mistakes become entertaining.'),
q('What makes the Logan Airport event more than a luggage problem?', ['The chain of small mistakes and exaggerated panic creates a comic disaster','The bag contains something dangerous','The airport closes because of him','A flight is cancelled'],0,'The comedy comes from escalation, embarrassment and self-awareness.'),
q('How does exaggeration work in the finger incident?', ['Bryson presents a small mishap as if it were a catastrophe','He invents a medical report','He hides what happened','He blames the airport staff'],0,'His dramatic reaction is intentionally disproportionate.'),
q('Why are the wife’s reactions important?', ['They provide an outside measure of how unusual his behaviour is','They explain the airline rules','They replace the main plot','They show that she caused every accident'],0,'Her disbelief acts as a second comic perspective.'),
q('What is the effect of repeated accidents?', ['Each new mishap increases the comic pressure and makes the next one more predictable','The story becomes a tragedy','The narrator becomes a better traveller','The journey ends quickly'],0,'Repetition and escalation are major comic devices here.'),
q('Why does the spilled-drink episode work as physical comedy?', ['A simple mistake is followed by a replacement and then the same mistake happens again','The woman starts laughing immediately','The flight attendant leaves the plane','The drink is unusually expensive'],0,'The repetition creates an escalating visual joke.'),
q('How does the cramped airplane setting support the humour?', ['Small movements and accidents affect nearby passengers and become harder to hide','It gives Bryson more space','It prevents any interaction','It makes the plane silent'],0,'The tight setting magnifies minor mistakes.'),
q('What does Bryson’s travel anxiety tell us about his narrative voice?', ['He notices his own weaknesses and converts them into humour','He is trying to frighten readers','He wants to present himself as heroic','He refuses to admit mistakes'],0,'Self-awareness is the basis of his humorous narration.'),
q('Why is the frequent-flyer detail funny?', ['A practical benefit becomes another thing he forgets to manage','He refuses to travel by air','He gets too many points','The airline gives him free tickets'],0,'His forgetfulness extends even to something designed for regular travellers.'),
q('What is the comic point of B. Bryson versus W. Bryson?', ['A small naming difference is treated by the airline as a serious distinction','Bill and William are two different people','Bryson has changed his identity','The ticket belongs to his wife'],0,'The bureaucratic distinction clashes with ordinary common sense.'),
q('How does the chapter portray bureaucracy?', ['Rules can become absurd when a system ignores obvious human equivalence','Rules always solve every travel problem','Airlines never make mistakes','Paperwork is more important than people'],0,'The final episode highlights the gap between system rules and common sense.'),
q('Why does the chapter stay entertaining despite repeated embarrassment?', ['The narrator controls the tone through humour, exaggeration and self-observation','Nothing actually goes wrong','The wife tells jokes throughout','Travel is presented as perfect'],0,'The comic voice transforms embarrassment into entertainment.'),
q('What is the best meaning of accidental tourist in this context?', ['A traveller whose journey repeatedly becomes accidental rather than smoothly planned','Someone who never leaves home','A professional travel agent','A tourist who dislikes cities'],0,'The title captures the mismatch between planned travel and accidental mishaps.'),
q('How do small practical failures reveal character?', ['They show Bryson as forgetful, clumsy, anxious and able to laugh at himself','They prove he is dishonest','They make him seem cruel','They show he hates his family'],0,'The accidents are character-building details.'),
q('Why is the title effective?', ['It combines the ordinary idea of a tourist with the accidental nature of his behaviour','It refers to a lost passport only','It names an airport','It describes a professional pilot'],0,'The title captures the chapter’s comic identity.'),
q('What does the chapter suggest about travel etiquette?', ['Small lapses can affect other passengers, so awareness and care matter','Etiquette has no value','Passengers should ignore everyone','Only staff need to behave well'],0,'The spills and awkward behaviour affect people nearby.'),
q('Which device links several episodes together?', ['A recurring pattern of mistake, embarrassment and self-aware narration','A single mystery clue','A historical timeline','A series of poems'],0,'The chapter repeats a comic narrative pattern.'),
q('Why does Bryson mention his wife’s patience?', ['It contrasts his repeated accidents with someone who has learned to expect them','It proves she caused the accidents','It explains the airline policy','It changes the story to romance'],0,'Her tolerance reinforces the comic portrayal of his clumsiness.'),
q('What is the role of surprise in the chapter?', ['Readers expect trouble but cannot predict the exact form each new mishap will take','The story has no surprises','Surprise is used only once','Every event is perfectly planned'],0,'The recurring pattern prepares readers for trouble while keeping each incident distinct.'),
q('How does the chapter balance truth and comic exaggeration?', ['Realistic travel situations are presented with exaggerated reactions for humorous effect','Everything is described as impossible fantasy','The narrator gives only statistics','The story avoids personal experience'],0,'The incidents are everyday problems made funny by the narrator’s style.'),
q('Why does the final airline episode fit the rest of the chapter?', ['It turns an ordinary practical detail into another absurd travel problem','It introduces a new hero','It ends with an action scene','It abandons the humour'],0,'The ticket-name mix-up is another everyday problem amplified by bureaucracy.'),
q('What makes Bryson a reliable comic narrator despite his mistakes?', ['He openly admits his errors and invites readers to laugh with him','He claims never to make mistakes','He blames every passenger','He hides the embarrassing events'],0,'His honesty and self-mockery build comic credibility.'),
q('What does the chapter imply about “real world” competence?', ['People may appear organised, while some practical tasks can be unexpectedly difficult for others','Everyone handles all practical tasks equally','Competence is only about intelligence','Travel has no connection with daily life'],0,'Bryson contrasts his difficulty with the apparent ease of others.'),
q('Why can ordinary objects such as zippers and drinks carry so much narrative weight?', ['Small objects become triggers for a chain of accidents and reactions','They are magical objects','They symbolise political power','They are never used directly'],0,'The chapter builds comedy from ordinary travel objects.'),
q('Which conclusion best captures the chapter?', ['Travel exposes Bryson’s practical weaknesses, but humour turns those failures into an engaging portrait of everyday life','Travel proves that Bryson is a perfect traveller','The chapter is mainly about airline engineering','The wife is the only source of humour'],0,'The combined episodes create a humorous portrait of the writer as an accidental tourist.')];
const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`final-${i}`}));
export function EnglishReaderChapter6({initialMode='learn',onBack,addXp,finishSession}){return <EnglishReaderEngine study={{...study,practice,challenge,finalTest}} initialMode={initialMode} onBack={onBack} addXp={addXp} finishSession={finishSession}/>;}
export const englishReaderChapter6Meta={title:study.title,author:'Bill Bryson',sourceNote:study.sourceNote,modeCounts:{practice:practice.length,challenge:challenge.length,final:finalTest.length}};
export {study as englishReaderChapter6Study};
