import React,{useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import {PHASE4_BANKS} from './EnglishGenericLanguageSkillsBanks.jsx';
import './EnglishDeterminersTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Determiner क्या है?',simple:'Determiner noun से पहले आकर यह बताता है कि हम किस व्यक्ति/वस्तु की बात कर रहे हैं, कितनी मात्रा या संख्या है, या noun किसके साथ जुड़ा है।',meaning:'A determiner comes before a noun and helps identify, limit, quantify or indicate it.',structure:'determiner + noun  |  the book • some water • my pen • these students',examples:['The book is useful. → “the” particular book को identify करता है।','Some water is left. → “some” मात्रा बताता है।','My pen is blue. → “my” possession बताता है।'],clue:'पहले noun खोजो, फिर देखो उसके पहले कौन-सा word noun को identify/limit कर रहा है।'},
{n:'02',group:'CORE',title:'Articles — a / an / the',simple:'a और an किसी एक, non-specific singular countable noun के साथ आते हैं। the किसी particular या already identified noun के साथ आता है।',meaning:'a/an are indefinite articles; the is the definite article.',structure:'a/an + singular countable noun  |  the + identified/specific noun',examples:['I saw a dog. → कोई एक dog, पहली बार।','She ate an apple. → vowel sound से पहले an।','The dog followed me. → अब dog identified है।'],clue:'पहली बार/unspecified = a/an; known, particular या context से identified = the.'},
{n:'03',group:'ARTICLES',title:'a या an — spelling नहीं, sound',simple:'a/an का चुनाव letter देखकर नहीं, pronunciation देखकर होता है। vowel sound से पहले an और consonant sound से पहले a आता है।',meaning:'Article choice depends on sound, not simply on the first written letter.',structure:'consonant sound → a | vowel sound → an',examples:['a university → /juː/ consonant sound','an hour → vowel sound','a useful book → /juː/ sound','an honest man → vowel sound'],clue:'u अगर “you” sound दे तो a; silent h से vowel sound हो तो an.'},
{n:'04',group:'ARTICLES',title:'the — particular, unique और known nouns',simple:'the तब उपयोगी है जब noun particular हो, पहले mention हो चुका हो, context से clear हो, या unique reference हो।',meaning:'The commonly marks a specific or uniquely identifiable reference.',structure:'the + specific noun',examples:['I saw a house. The house had a red gate.','Please close the door. → context में कौन-सा door clear है।','The sun rises in the east. → unique reference'],clue:'“कौन-सा?” का answer context से मिल रहा हो तो the की संभावना जाँचो।'},
{n:'05',group:'ARTICLES',title:'Zero article — article कब नहीं?',simple:'Plural nouns और uncountable nouns को general meaning में कई बार बिना article के लिखा जाता है। लेकिन specific reference होने पर the आ सकता है।',meaning:'No article can express a general plural or uncountable reference.',structure:'Ø + plural/uncountable noun (general)',examples:['Books are useful. → books in general','Water is essential. → water in general','The books on this table are mine. → specific books'],clue:'General vs specific contrast exam में बहुत महत्वपूर्ण है।'},
{n:'06',group:'QUANTITY',title:'Some और any',simple:'some का प्रयोग affirmative sentences में quantity/reference बताने के लिए common है। any questions/negatives में बहुत common है, और questions में offers/requests के context में some भी आ सकता है।',meaning:'Some and any are common quantity determiners for indefinite amounts or numbers.',structure:'some + plural/uncountable noun | any + plural/uncountable noun',examples:['I bought some books.','We need some water.','I do not have any money.','Are there any questions?'],clue:'Blank से पहले sentence affirmative, negative या question है—यह check करो।'},
{n:'07',group:'QUANTITY',title:'Much, many, a lot of',simple:'many plural countable nouns के साथ और much uncountable nouns के साथ आता है। a lot of दोनों के साथ हो सकता है।',meaning:'Many modifies plural countable nouns; much modifies uncountable nouns; a lot of works with both.',structure:'many + plural countable | much + uncountable | a lot of + both',examples:['many students / many books','much water / much time','a lot of students / a lot of water'],clue:'Noun countable है या uncountable? यही पहला decision है।'},
{n:'08',group:'QUANTITY',title:'Few, a few, little, a little',simple:'few और little कम मात्रा/संख्या का sense देते हैं। a few और a little आमतौर पर “कुछ/थोड़ी मात्रा, लेकिन enough” का more positive sense देते हैं।',meaning:'Few/a few are used with plural countables; little/a little with uncountables.',structure:'few/a few + plural countable | little/a little + uncountable',examples:['Few students understood the warning. → बहुत कम','A few students stayed back. → कुछ students','There is little hope. → बहुत कम मात्रा','There is a little hope. → थोड़ी hope है'],clue:'Plural countable → few/a few; uncountable → little/a little.'},
{n:'09',group:'QUANTITY',title:'Fewer और less',simple:'Traditional school grammar में fewer plural countable nouns के साथ और less uncountable nouns के साथ पढ़ाया जाता है।',meaning:'Use fewer with plural countable nouns and less with uncountable nouns in standard school-grammar contrasts.',structure:'fewer + plural countable | less + uncountable',examples:['fewer mistakes','fewer students','less water','less time'],clue:'“books, students, mistakes” count कर सकते हो → fewer. “water, time, money” → less.'},
{n:'10',group:'DISTRIBUTIVE',title:'Each और every',simple:'each और every singular countable noun के साथ आते हैं। each individual members पर focus करता है; every group के members को one-by-one sense में generalise करता है।',meaning:'Each and every are normally followed by singular countable nouns.',structure:'each/every + singular countable noun + singular verb',examples:['Each student has a notebook.','Every child needs care.','Each of the boys is ready.'],clue:'“each students” और “every students” गलत—noun singular रखो।'},
{n:'11',group:'DISTRIBUTIVE',title:'Either, neither, both',simple:'either = दो में से कोई एक; neither = दो में से कोई भी नहीं; both = दोनों। इनके साथ number और verb pattern पर ध्यान दो।',meaning:'These determiners distribute or refer to members of a pair.',structure:'either/neither + singular noun | both + plural noun',examples:['Either answer is acceptable.','Neither boy was absent.','Both answers are correct.','Both of the boys are ready.'],clue:'either/neither → singular noun; both → plural noun.'},
{n:'12',group:'DEMONSTRATIVE',title:'This, that, these, those',simple:'Demonstratives distance और number दोनों बताते हैं। this/these पास, that/those दूर; this/that singular और these/those plural होते हैं।',meaning:'Demonstratives point to nouns using distance and number.',structure:'this/that + singular noun | these/those + plural noun',examples:['This book is mine.','That building is old.','These books are new.','Those trees are tall.'],clue:'पहले singular/plural तय करो, फिर near/far।'},
{n:'13',group:'POSSESSIVE',title:'My, your, his, her, its, our, their',simple:'Possessive determiners noun के साथ possession या association दिखाते हैं। इनके बाद सामान्यतः noun आता है; ये standalone possessive pronouns से अलग हैं।',meaning:'Possessive determiners modify nouns to show possession or association.',structure:'my/your/his/her/its/our/their + noun',examples:['My book is here.','Their school is nearby.','Its colour is bright.','Our teacher explained the rule.'],clue:'my book ✅; mine book ❌. Possessive pronoun अलग structure में आता है।'},
{n:'14',group:'NUMBER',title:'Cardinal और ordinal numbers',simple:'Numbers भी noun को determine कर सकते हैं। cardinal number exact quantity बताता है; ordinal order/rank बताता है।',meaning:'Cardinal numbers express quantity; ordinal numbers express order.',structure:'two books | five students | the first chapter | my second attempt',examples:['Three students answered. → quantity','The first question is easy. → order','She won the second prize. → position'],clue:'How many? → cardinal. Which position/order? → ordinal.'},
{n:'15',group:'INTERROGATIVE',title:'Which, what, whose',simple:'Interrogative determiners noun से पहले प्रश्न बनाते हैं। which अक्सर limited choice, what broader choice और whose possession पूछता है।',meaning:'Which, what and whose can function as determiners before nouns in questions.',structure:'which/what/whose + noun',examples:['Which book do you want?','What subject do you like?','Whose bag is this?'],clue:'Question में इनके बाद noun directly आ रहा है तो determiner role जाँचो।'},
{n:'16',group:'MIXED',title:'Determiner + noun agreement',simple:'Determiner चुनने के बाद noun की number और countability check करना जरूरी है।',meaning:'Determiners must fit the number and countability of the noun they modify.',structure:'determiner ↔ noun number/countability',examples:['many books ✅ / many book ❌','much water ✅ / much waters ❌','each student ✅ / each students ❌','these ideas ✅ / this ideas ❌'],clue:'Blank भरते समय option ही नहीं, उसके बाद आने वाले noun को भी पढ़ो।'},
{n:'17',group:'MIXED',title:'Determiner traps — exam में कहाँ फँसते हैं?',simple:'Common traps: a/an sound, much/many, less/fewer, each/every + singular, few/a few का meaning, और general vs specific noun।',meaning:'Most determiner errors come from number, countability, specificity, sound or meaning contrasts.',structure:'sound → number → countability → specificity → meaning',examples:['an honest officer ✅','much information ✅','fewer mistakes ✅','each student ✅','the books on the desk ✅'],clue:'एक ही rule देखकर answer मत दो; noun + sentence context पूरा पढ़ो।'},
{n:'18',group:'ADVANCED',title:'Determiners in real sentence analysis',simple:'एक sentence में कई determiner types मिल सकते हैं। हर noun phrase के साथ पूछो: article? quantity? demonstrative? possessive? number? और noun countable है या नहीं?',meaning:'Real sentences may contain different determiner systems across noun phrases.',structure:'[determiner + modifier + noun] + verb + [determiner + noun]',examples:['Those two students completed their project.','The few mistakes in my answer were corrected.','Each of the four teams had its own captain.'],clue:'पूरे noun phrase को bracket करो, फिर determiner की category और reason लिखो।'},
{n:'19',group:'EXAM CONTROL',title:'Hindi → English में determiner choice',simple:'हिंदी sentence में “एक”, “कुछ”, “हर”, “दोनों”, “यह/वह”, “मेरा/उसका” जैसे clues determiner चुनने में मदद करते हैं; लेकिन English noun की countability भी देखनी है।',meaning:'Translation requires meaning plus English noun-number and countability control.',structure:'Hindi clue → noun type → determiner → noun form',examples:['कुछ पानी → some water','कई छात्र → many students','हर छात्र → every student','दोनों किताबें → both books'],clue:'Hindi word का direct translation पर्याप्त नहीं; English noun behavior भी जाँचो।'},
{n:'20',group:'FINAL AUDIT',title:'Final Determiner Audit',simple:'Final checklist: noun identify करो, singular/plural देखो, countable/uncountable तय करो, specific/general context देखो, sound check करो, फिर determiner और noun form दोनों verify करो।',meaning:'Accurate determiner selection is a multi-step decision, not a guess from one word.',structure:'noun → number → countability → specificity → meaning/sound → determiner → noun form',examples:['an hour ✅','many students ✅','much information ✅','the books on this desk ✅','every student ✅'],clue:'Exam में final read-back करो: determiner + noun pair natural और grammatically correct है या नहीं?'}
];

const nextMode=mode=>mode==='practice'?'challenge':mode==='challenge'?'test':'practice';
const rotate=(questions,mode)=>{const shift=mode==='challenge'?1:mode==='test'?2:0;return questions.map((item,qi)=>{const[q,opts,a,e]=item;const move=(a+shift+qi)%opts.length;const next=Array(opts.length);for(let i=0;i<opts.length;i++)next[(i+move-a+opts.length)%opts.length]=opts[i];return[q,next,move,e]})};

export default function EnglishDeterminersTopic({onBack,addXp,finishSession}){
 const [mode,setMode]=useState('learn');
 const [lesson,setLesson]=useState(0);
 const tabs=[['learn','Learn'],['practice','Practice'],['challenge','Challenge'],['test','Final Test']];
 const bank=useMemo(()=>{const source=PHASE4_BANKS.determiners?.[mode]||[];return mode==='learn'?[]:rotate(source,mode)},[mode]);
 const changeMode=m=>setMode(m);
 return <main className="determiners-page">
  <header className="determiners-top">
   <button type="button" onClick={onBack}>← Language &amp; Skills</button>
   <div className="determiners-hero">
    <div className="determiners-hero-main">
     <span>ENGLISH • LANGUAGE &amp; SKILLS</span>
     <h1>Determiners</h1>
     <p>Articles, quantity, number, possession and reference — rule को context से जोड़ो, फिर exam में apply करो.</p>
     <div className="determiners-hero-stats"><b>20</b><small>lessons</small><b>3</b><small>assessment levels</small><b>Class 9</b><small>exam focus</small></div>
    </div>
    <aside className="determiners-hero-card">
     <strong>MASTER THE DECISION</strong>
     <span>Number</span><span>Countability</span><span>Specificity</span><span>Meaning + sound</span>
    </aside>
   </div>
  </header>
  <nav className="determiners-tabs" aria-label="Determiners learning modes">
   {tabs.map(([id,label],i)=><button key={id} type="button" className={mode===id?'active':''} onClick={()=>changeMode(id)}><i>{['◫','✦','⚡','✓'][i]}</i><span>{label}</span></button>)}
  </nav>
  {mode==='learn'?<section className="determiners-learning">
    <div className="determiners-progress"><div><span>LEARNING PROGRESS</span><strong>Lesson {lesson+1} / {LESSONS.length}</strong></div><b>{LESSONS[lesson].group}</b><div className="determiners-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></div>
    <aside className="determiners-map"><strong>LESSON PATH</strong><div>{LESSONS.map((item,i)=><button type="button" key={item.n} className={lesson===i?'active':''} onClick={()=>setLesson(i)}><em>{item.n}</em><b>{item.title}</b><small>{item.group}</small></button>)}</div></aside>
    <article className="determiners-lesson">
      <div className="determiners-kicker"><span>{LESSONS[lesson].group}</span><b>{LESSONS[lesson].n}</b></div>
      <h2>{LESSONS[lesson].title}</h2>
      <div className="determiners-simple"><b>सरल हिंदी</b><p>{LESSONS[lesson].simple}</p></div>
      <section><label>Core idea</label><p className="determiners-meaning">{LESSONS[lesson].meaning}</p></section>
      <section><label>Rule / structure</label><div className="determiners-structure"><code>{LESSONS[lesson].structure}</code></div></section>
      <section className="determiners-examples"><label>Examples</label>{LESSONS[lesson].examples.map((x,i)=><div key={i}><b>{i+1}</b><span>{x}</span></div>)}</section>
      <div className="determiners-clue"><b>EXAM CLUE</b><span>{LESSONS[lesson].clue}</span></div>
      <div className="determiners-nav"><button type="button" disabled={lesson===0} onClick={()=>setLesson(v=>v-1)}>← Previous</button><button type="button" disabled={lesson===LESSONS.length-1} onClick={()=>setLesson(v=>v+1)}>Next lesson →</button></div>
    </article>
   </section>:<div className="determiners-assessment"><EnglishTimedQuiz key={mode} title="Determiners" mode={mode} questions={bank} onModeChange={changeMode} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession} onNextLevel={m=>changeMode(nextMode(m))}/></div>}
 </main>
}
