import {poem8Part1} from './EnglishPanoramaPoem8Source1.js';import {poem8Part2} from './EnglishPanoramaPoem8Source2.js';import {poem8Part3} from './EnglishPanoramaPoem8Source3.js';import {poem8Part3b} from './EnglishPanoramaPoem8Source3b.js';import {poem8Part4} from './EnglishPanoramaPoem8Source4.js';import {poem8Part5} from './EnglishPanoramaPoem8Source5.js';import {poem8Part6} from './EnglishPanoramaPoem8Source6.js';import {poem8Part7} from './EnglishPanoramaPoem8Source7.js';import {poem8Part8} from './EnglishPanoramaPoem8Source8.js';import {poem8Part9} from './EnglishPanoramaPoem8Source9.js';import {poem8Part10} from './EnglishPanoramaPoem8Source10.js';import {poem8Part11} from './EnglishPanoramaPoem8Source11.js';import {poem8Part12} from './EnglishPanoramaPoem8Source12.js';import {poem8Part13} from './EnglishPanoramaPoem8Source13.js';import {poem8Part14} from './EnglishPanoramaPoem8Source14.js';
export const poem8SourceLines=[...poem8Part1,...poem8Part2,...poem8Part3,...poem8Part3b,...poem8Part4,...poem8Part5,...poem8Part6,...poem8Part7,...poem8Part8,...poem8Part9,...poem8Part10,...poem8Part11,...poem8Part12,...poem8Part13,...poem8Part14];
export const poem8Sections=[
 ['Truth and goodness','संसार में अन्याय और असत्य को समझते हुए भी अच्छाई, नायकत्व, समर्पित नेतृत्व और मित्रता पर विश्वास बनाए रखना।'],
 ['Honest work and resilience','ईमानदार कमाई, हार से सीखना, जीत का आनंद लेना और ईर्ष्या से बचना चरित्र-निर्माण के आधार हैं।'],
 ['Books and nature','किताबों के आश्चर्य और पक्षियों, मधुमक्खियों तथा फूलों की प्रकृति को देखने-समझने के लिए शांत समय देना।'],
 ['Integrity and independent thought','ईमानदारी से असफल होना cheating से बेहतर है और बच्चे को अपने विचारों पर विश्वास करना चाहिए।'],
 ['Kindness and critical listening','सज्जन लोगों के प्रति gentle और कठिन लोगों के प्रति tough रहना, भीड़ का अंधानुकरण न करना तथा सुनी हुई बातों को filter करना।'],
 ['Emotion and values','दुःख में भी हँसना, आँसुओं को शर्म न मानना, cynics से सावधान रहना और अपने heart and soul को बेचने से बचना।'],
 ['Courage, patience and faith','सही लगने वाली बात के लिए खड़े होना, कठिनाई से मजबूत होना, courage और patience दोनों रखना तथा self और mankind में sublime faith विकसित करना।']
];
export const poem8Glossary=[['scoundrel','a person who has no moral principles; a villain'],['envy','a feeling of discontent caused by another’s good fortune'],['lick','pass the tongue over something / defeat'],['ponder','think deeply about something'],['scoff','speak contemptuously; mock'],['cynic','a person who believes people act mainly for selfish advantage'],['howling','very fierce or extremely loud'],['sublime','of the greatest or most admirable kind'],['cuddle','hold someone closely and lovingly'],['eternal','without beginning or end; lasting forever']];
export const poem8Long=[['Why did Abraham Lincoln write a letter to his son’s teacher?','He wanted the teacher to help shape his son into a truthful, courageous, independent and humane person who could face both the good and bad in society.'],['What does Lincoln mean by saying that for every scoundrel there is a hero and for every selfish Politician there is a dedicated leader?','He wants the child to judge society fairly rather than becoming cynical: wrongdoing exists, but goodness and dedication exist as well.'],['A child should be treated gently but not cuddled. Give your opinion.','Care is necessary, but overprotection can prevent a child from learning independence, patience and resilience through manageable challenges.'],['All men are not just, all men are not true. Comment.','The statement recognises human imperfections. It is not a reason for hopelessness because the letter immediately balances it with examples of heroes, leaders and friends.'],['Why should the child be steered away from envy and learn quiet laughter?','Envy harms character, while quiet laughter suggests calmness, humility and the ability to enjoy life without unhealthy comparison.'],['Why should Lincoln not want his son to follow the crowd?','He wants him to think independently and resist social pressure when the crowd is moving in a direction he believes is wrong.'],['What qualities did Lincoln want his son’s teacher to teach him?','Truthfulness, courage, independent thinking, kindness, resilience, critical judgment, emotional strength, appreciation of books and nature, honesty, patience and faith in humanity.']];
export const poem8WordStudy=[['Correct spellings','pander → pander; envi → envy; mistry → mystery; braoh → brawn; mab → mob; paitense → patience'],['Synonyms','big → large; enemy → foe; enjoy → relish; wonder → amazement; howl → wail']];
export const poem8Grammar={title:'Prepositions',text:'The lesson uses on to establish relationships such as “price-tag” and “heart and soul”, and “to” in “ears to a howling mob”. Prepositions show relations of time, place, position, direction and other connections. Examples from the lesson include above, under, below, towards, to, from, on and at. The exercise asks students to find more prepositions and state their types.'};
export const poem8Activity='Do a project on the Gurukul, the ancient system of education in India.';
export const poem8Translation=['मुझे अंग्रेजी सीखना होगा','सफलता का अंग्रेजी अनुवाद करनी होगी','रोजगार के लिए अंग्रेजी सीखनी होगी','सभी लोग दयालु नहीं होते','सभी बदमाश में एक नायक होता है','बुराई में अच्छाई भी होती है','प्रत्येक दुश्मन में एक दोस्त होता है','उसे आराम से अंग्रेजी सीखने दो','अगर पढ़ा सकते हो तो किताब के महत्व के बारे में बताओ','मैं भी माँ को अंग्रेजी सिखाने की कोशिश करता हूँ'];
