import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-panorama-poetry.css';

const poem={
 title:"Abraham Lincoln’s Letter to His Son’s Teacher",poet:'Abraham Lincoln',book:'The Panorama • Poetry Chapter 8',
 context:'A father asks a teacher to shape his son through truth, courage, independent thinking, kindness, honest work, resilience, love of books and nature, and faith in humanity.',
 stanzas:[
 {title:'Part 1 — Truth, goodness and earned value',range:'Lines 1–10',poemLines:['He will have to learn, I know,','that all men are not just,','all men are not true.','But teach him also that','for every scoundrel there is a hero;','that for every selfish Politician,','there is a dedicated leader...','Teach him for every enemy there is','a friend.','It will take time, I know;'],explanation:'पिता चाहते हैं कि बेटा संसार के अन्याय और असत्य को समझे, लेकिन अच्छाई और अच्छे लोगों पर विश्वास भी बनाए रखे। उसे यह भी समझना चाहिए कि ईमानदारी और मित्रता कठिन परिस्थितियों में महत्त्वपूर्ण हैं।',vocab:[['scoundrel','दुष्ट व्यक्ति'],['hero','नायक'],['dedicated','समर्पित'],['enemy','शत्रु']]},
 {title:'Part 2 — Honest work, losing and quiet laughter',range:'Lines 11–20',poemLines:['but teach him if you can,','that a dollar earned is of far more value than five','pound...','Teach him to learn to lose...','and also to enjoy winning.','Steer him away from envy,','if you can,','teach him the secret of','quiet laughter.','Let him learn early that'],explanation:'ईमानदारी से कमाई गई वस्तु का मूल्य अधिक है। बच्चे को हार से सीखना और जीत का स्वस्थ आनंद लेना, ईर्ष्या से बचना और शांत हास्य सीखना चाहिए।',vocab:[['earned','कमाया हुआ'],['lose','हारना'],['winning','जीत'],['envy','ईर्ष्या'],['laughter','हँसी']]},
 {title:'Part 3 — Courage, books and nature',range:'Lines 21–30',poemLines:['the bullies are the easiest to lick...','Teach him, if you can,','the wonder of books...','But also give him quiet time','to ponder the eternal mystery of birds in the sky,','