import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-panorama-poetry.css';

const poem={
 title:'Self-Introduction',poet:'Neerada Suresh',book:'The Panorama • Poetry Chapter 6',
 sourceNote:'Built from the supplied Bihar Board Class 9 Panorama pages 112–116. The poem text and chapter activities are presented from the supplied source pages, with explanations and assessment support.',
 context:'The speaker presents herself as an ordinary woman whose creativity and individuality have been confined to domestic responsibilities. The poem moves from ordinary domestic work, through a decade of emotional suffering and silence, to a final desire for that trapped identity to break through.',
 structure:'Three six-line movements. The first describes domestic confinement, the second describes sensitivity hardening into silence, and the third reconsiders the label of ordinariness and imagines becoming extraordinary at the cost of a few tears.',
 stanzas:[
  {title:'Stanza 1 — An ordinary woman',range:'Lines 1–6',poemLines:['I am','an ordinary woman','with a creativity confined','To home and children.','To juxtaposing of carpets and curios,','Labelling books, tying up shoe laces.'],explanation:'पहले stanza में वक्ता स्वयं को “ordinary woman” कहती है। उसकी creativity घर और बच्चों तक सीमित है। उसके कामों में carpets और curios को साथ सजाना, किताबों पर labels लगाना और जूतों के फीते बाँधना जैसे घरेलू कार्य शामिल हैं। इससे उसकी प्रतिभा और पहचान के सीमित दायरे का पता चलता है।',vocab:[['ordinary','साधारण'],['creativity','रचनात्मकता'],['confined','सीमित / बंद'],['juxtaposing','पास-पास रखकर तुलना या सजाना'],['curios','दिलचस्प सजावटी वस्तुएँ'],['labelling','नाम/पहचान के लेबल लगाना']],exam:'मुख्य विचार: घरेलू भूमिकाओं में creativity और व्यक्तिगत पहचान का सीमित हो जाना।',key:'Focus = domestic confinement | Tone = restrained self-description'},
  {title:'Stanza 2 — Sensitivity turned into silence',range:'Lines 7–12',poemLines:['My sensitivity','suffering silent blows','through a decade of togetherness','hardening to a tortoise shell.','My soul entrapped,','Flaps itself into silence.'],explanation:'दूसरे stanza में वक्ता बताती है कि उसकी sensitivity ने लंबे समय तक चोटें सही हैं। “a decade of togetherness” के बाद उसकी संवेदनशीलता tortoise shell की तरह कठोर हो गई। उसकी soul trapped है और वह अपनी आवाज़ को silence में समेटती हुई दिखाई देती है।',vocab:[['sensitivity','संवेदनशीलता'],['suffering','पीड़ा सहना'],['silent blows','बिना बोले मिली मानसिक चोटें'],['decade','दस वर्ष की अवधि'],['togetherness','साथ रहने की अवस्था'],['entrapped','फँसी हुई']],exam:'मुख्य विचार: लंबे समय के भावनात्मक दबाव से sensitivity का कठोर होना और आत्म-अभिव्यक्ति का मौन हो जाना।',key:'Image = tortoise shell | Result = silence and entrapment'},
  {title:'Stanza 3 — Beyond the label of ordinariness',range:'Lines 13–18',poemLines:['My ordinariness','A tag to bind me conveniently','To a home and children','To be made extraordinary perhaps','At the cost of a few sad tears','That might dare to crack through!'],explanation:'तीसरे stanza में “ordinariness” को एक tag कहा गया है, जो वक्ता को सुविधाजनक ढंग से घर और बच्चों की भूमिका से बाँध देता है। लेकिन उसी ordinary identity के भीतर extraordinary बनने की संभावना भी है। अंत में sad tears के “crack through” करने की छवि दबे हुए भावों के बाहर आने और परिवर्तन की संभावना दिखाती है।',vocab:[['ordinariness','साधारण होने की अवस्था'],['tag','पहचान बताने वाला चिन्ह/लेबल'],['bind','बाँधना'],['conveniently','सुविधा के अनुसार'],['extraordinary','असाधारण'],['crack through','दरार बनाकर बाहर आना']],exam:'मुख्य विचार: सामाजिक लेबल से बँधी पहचान के भीतर परिवर्तन और आत्म-अभिव्यक्ति की संभावना।',key:'Contrast = ordinary ↔ extraordinary | Image = tears cracking through'}
 ],
 words:[['ordinary','साधारण'],['creativity','रचनात्मकता'],['confined','सीमित'],['juxtaposing','पास-पास रखना'],['curios','सजावटी वस्तुएँ'],['sensitivity','संवेदनशीलता'],['decade','दस वर्ष'],['entrapped','फँसा हुआ'],['ordinariness','साधारणता'],['conveniently','सुविधा के अनुसार'],['extraordinary','असाधारण'],['crack through','दरार बनाकर बाहर निकलना']],
 devices:[['Metaphor','Ordinariness is called a “tag” that binds the speaker to a domestic role.'],['Simile','The hardened sensitivity is compared to a tortoise shell.'],['Imagery','Domestic objects, a tortoise shell, a trapped soul and tears breaking through create strong images.'],['Personification','The soul is shown as something that can be entrapped and flap itself into silence.'],['Contrast','Ordinary and extraordinary identities are placed against each other.'],['Symbolism','The tortoise shell symbolises emotional hardening; tears symbolise suppressed feeling seeking release.']],
 themes:['gender roles','domestic confinement','identity','silencing','emotional suffering','women’s self-expression','ordinary versus extraordinary'],
 textbookAnswers:[
  ['Why does the woman call herself ordinary?','She describes herself as ordinary because her creativity and life are confined to home and children.'],
  ['To what is an ordinary woman’s creativity confined?','It is confined to domestic work involving home, children and household arrangements.'],
  ['Why does the sensitivity of the ordinary woman suffer blows?','Years of togetherness and social/domestic pressures repeatedly hurt her sensitivity.'],
  ['How long has the woman been living with her husband?','The poem refers to a decade of togetherness.'],
  ['Why is the woman unable to express her anguish?','Her emotional suffering has hardened her sensitivity and trapped her soul in silence.'],
  ['What is the tag attached to an ordinary woman?','The tag is “ordinariness,” which binds her conveniently to home and children.'],
  ['With what jobs has the woman been associated?','She is associated with domestic jobs such as arranging carpets and curios, labelling books and tying shoe laces.'],
  ['How might the woman be made extraordinary?','The poem suggests that suppressed feelings may break through, allowing her identity to move beyond the imposed ordinary role.'],
  ['How does the woman visualise this transformation?','She imagines a few sad tears daring to crack through the silence and the label that confines her.']
 ],
 longAnswers:[
  ['Who is the speaker and how does she introduce herself?','The speaker is a woman who introduces herself as ordinary and explains that her creativity has been confined to home and children. Her self-description establishes the tension between personal potential and domestic limitation.'],
  ['Explain the second stanza about mental and physical pain.','The second stanza presents long-term emotional suffering. Her sensitivity receives “silent blows” through a decade of togetherness, eventually hardening like a tortoise shell. Her soul feels entrapped and turns inward toward silence.'],
  ['Does the ordinary woman become rebellious? Which line suggests it?','The final stanza suggests a possible inner revolt against the imposed identity. The image of sad tears that “might dare to crack through” indicates suppressed feeling beginning to break the silence.'],
  ['Write a summary of the poem in your own words.','The poem presents a woman whose creativity is restricted by domestic expectations. Years of emotional pressure make her sensitive self hard and silent, but she still retains the possibility of becoming extraordinary by allowing her suppressed identity and feelings to emerge.'],
  ['The poem depicts the plight of housewives in general. Do you agree?','The poem can be read as a critique of how domestic roles may limit women’s creativity and self-expression. It foregrounds emotional labour, confinement and the pressure of being defined only through home and children.'],
  ['Comment on the juxtaposition of carpets and curios.','The phrase places ordinary household arrangement beside the speaker’s idea of creativity. It shows how her creative energy is channelled into decorative and domestic tasks rather than broader personal expression.'],
  ['What is the deeper meaning of ordinariness in the poem?','Ordinariness is more than a description; it becomes a social label or “tag” that makes the speaker’s confinement appear convenient and acceptable. The final stanza questions that label and opens the possibility of transformation.']
 ],
 groupDiscussion:['Gender discrimination has been taking place since time immemorial. Discuss the statement and give reasons.','How far will reservation for women in different walks of life help elevate their status in society? Give arguments.'],
 composition:['The role of a housewife is more difficult than that of a working woman. Write a paragraph of about 100 words.','Behind the success of a man there is always a woman. Write a paragraph of about 100 words.'],
 wordStudy:[
  {title:'Dictionary Use — Correct the spelling',text:'Correct the spelling of: Jukstaposing, labeling, sensetivity, entraped, conveniently, ordinaryness, dair.'},
  {title:'Dictionary Use — Multiple meanings',text:'Find at least two meanings for ordinary, cost, blows, suffering, laces, silence, bind and conveniently. Use each in lesson context and in a more common context.'},
  {title:'Word Formation',text:'From the root word “create” the book gives forms such as creatively, creation, creator, creative, creativity, creativeness, creatively, creature. Build as many related words as possible from ordinary, home, sense, sad, cost and silence.'},
  {title:'Word Meaning',text:'Match meanings from the poem using endings supplied by the textbook: normal/usual; restricted or imprisoned; placing side by side; cord for lacing shoes; moves up and down, beats; tie or fasten tightly; label; drop secreted by glands from the eye.'}
 ],
 grammar:[
  {title:'Forms of “bind”',text:'Study: bind – bound – bound – binding – binds. Give the different forms of: tie, lie, make, hide, wind, create, swear, dare, spend, suffer.'},
  {title:'“with” as a preposition',text:'The source lesson uses “with” to show association or company and also possession, e.g. a man with rare talent and a man with long beards.'},
  {title:'Prepositions',text:'Complete sentences using appropriate prepositions: What is wrong __ you?; She has fallen in love __ me; Don’t make friendship __ bad boys; He doesn’t agree __ me; He agreed __ my proposal; He is known __ me; You should not laugh __ the poor; She is living __ her mother; Please handle this machine __ care; He prevented me __ smoking.'}
 ],
 activities:['Meet working women in your locality and write a profile of them.','Visit a slum and write a report on the condition under which the women are living there.'],
 translation:'Translate the poem into Hindi or your mother tongue.'
};

const q=(question,options,answer,explanation)=>({q:question,o:options,a:answer,e:explanation});
const practice=[
q("Who wrote 'Self-Introduction'?",['Neerada Suresh','Rajani Parulekar','Robert Herrick','William Shakespeare'],0,'The supplied chapter identifies Neerada Suresh as the poet.'),
q('How does the speaker first describe herself?',['As an ordinary woman','As a famous writer','As a school teacher','As a politician'],0,'The poem opens with the speaker calling herself an ordinary woman.'),
q('To what is the speaker’s creativity confined?',['Home and children','The workplace','A classroom','A garden only'],0,'She says her creativity is confined to home and children.'),
q('Which domestic activities are mentioned?',['Juxtaposing carpets and curios, labelling books and tying shoe laces','Cooking food and washing clothes only','Teaching children to read only','Gardening and farming'],0,'These three activities are explicitly named in the first stanza.'),
q('What is a “curio”?',['An interesting or decorative object','A type of shoe lace','A school book','A family member'],0,'A curio is an interesting, often decorative object.'),
q('How long has the speaker lived in “togetherness”?',['A decade','A week','A month','A century'],0,'The poem explicitly says “through a decade of togetherness”.'),
q('What happens to the speaker’s sensitivity?',['It hardens like a tortoise shell','It disappears immediately','It becomes musical','It becomes stronger through travel'],0,'The second stanza compares the hardening to a tortoise shell.'),
q('What is the state of the speaker’s soul?',['It is entrapped','It is celebrated','It is travelling','It is carefree'],0,'The poem says “My soul entrapped”.'),
q('Into what does the soul flap itself?',['Silence','Laughter','Music','The garden'],0,'The poem ends the second stanza with the soul flapping itself into silence.'),
q('What does “ordinariness” become for the speaker?',['A tag that binds her conveniently','A medal of honour','A school subject','A family celebration'],0,'The third stanza calls ordinariness a tag that binds her.'),
q('To what does this tag bind her?',['A home and children','A city and school','A garden and books','A job and office'],0,'The tag binds her to a home and children.'),
q('What possibility is suggested by the word “extraordinary”?',['The woman may move beyond the imposed ordinary role','She must leave her family','She becomes famous immediately','She stops feeling anything'],0,'The poem imagines her being made extraordinary perhaps.'),
q('What might crack through?',['A few sad tears','The carpets','The books','The shoe laces'],0,'The final image is of a few sad tears daring to crack through.'),
q('Which image represents emotional hardening?',['A tortoise shell','A carpet','A shoe lace','A label'],0,'The tortoise shell is the poem’s image for hardened sensitivity.'),
q('What is a central theme of “Self-Introduction”?',['Domestic confinement and women’s self-expression','Weather and seasons','Travel and adventure','School examinations'],0,'The poem focuses on confinement, identity and the possibility of self-expression.')
];

const challenge=[
q('Why is “ordinary woman” more than a neutral description in the poem?',['It becomes a social label that helps confine her identity to domestic roles','It proves she lacks creativity','It means she has no emotions','It identifies her profession'],0,'The poem later turns ordinariness into a binding “tag”.'),
q('What is the effect of listing carpets, curios, books and shoe laces?',['It makes the domestic confinement concrete and visible','It celebrates professional success','It creates a travel scene','It explains a scientific process'],0,'Specific household tasks make the limitation of her creative life vivid.'),
q('How does “a decade of togetherness” contribute to the poem?',['It shows that the emotional pressure has lasted for a long time','It refers to ten minutes of silence','It shows the woman has travelled for ten years','It describes her childhood'],0,'The decade establishes duration and accumulated emotional strain.'),
q('Why is a tortoise shell an effective comparison?',['It suggests protection outside but hardness and withdrawal inside','It suggests speed and freedom','It suggests wealth and comfort','It suggests musical talent'],0,'The image captures emotional hardening and retreat into a protective shell.'),
q('What does “silent blows” suggest?',['Harm or pressure that may be invisible yet emotionally damaging','Physical exercise','Loud music','Public praise'],0,'The phrase conveys unseen emotional injury.'),
q('What does “My soul entrapped” imply?',['The speaker feels that her inner self lacks freedom','She is physically locked in a room','She is travelling alone','She has no imagination'],0,'The entrapment is primarily emotional and personal.'),
q('Why does the poet make the soul “flap” into silence?',['It suggests a struggling inner self that cannot find open expression','It describes a bird literally','It celebrates silence as easy','It refers to a school bell'],0,'The movement suggests effort followed by silencing.'),
q('What is the function of the word “tag” in the final stanza?',['It shows how a convenient social label can define and restrict a person','It names a piece of jewellery','It shows academic achievement','It describes a household tool'],0,'Tag conveys an imposed identity attached to the woman.'),
q('What does “conveniently” suggest?',['The label benefits the surrounding social arrangement by keeping roles simple','The woman is physically comfortable','She enjoys every restriction','The family is travelling'],0,'The word hints that the domestic label is convenient for others.'),
q('Why is “extraordinary” significant at the end?',['It introduces the possibility that the supposedly ordinary woman has unrealised potential','It rejects the idea of creativity','It means she becomes wealthy','It signals a change of setting'],0,'The final stanza opens a possibility beyond the imposed ordinary identity.'),
q('What do the “few sad tears” symbolise?',['Suppressed feelings and the possibility of release or change','Happiness at domestic work','Physical illness only','Rain outside the house'],0,'Tears are a poetic sign of inner emotion breaking outward.'),
q('What is implied by “dare to crack through”?',['The speaker’s suppressed voice may finally break the barriers around her','The house will literally collapse','The woman will stop thinking','A child will leave home'],0,'Cracking through suggests resistance to confinement.'),
q('Which contrast shapes the final stanza?',['Ordinary versus extraordinary','Summer versus winter','City versus village','Teacher versus student'],0,'The speaker’s ordinary label is contrasted with the possibility of becoming extraordinary.'),
q('How does the poem critique gender expectations?',['It shows how a woman may be valued mainly through home and children while her individual creativity is restricted','It praises unequal roles','It ignores women’s lives','It focuses on sports'],0,'The poem directly connects the woman’s identity with domestic confinement.'),
q('How does the poem’s first-person voice affect the reader?',['It makes the social and emotional pressure feel personal and immediate','It makes the poem scientific','It removes emotion','It creates a comic narrator'],0,'The repeated “I” and “My” make the experience intimate.'),
q('Which poetic device appears in “hardening to a tortoise shell”?',['Simile','Pun','Alliteration only','Irony'],0,'The comparison uses “to” to connect the hardened sensitivity with a tortoise shell.'),
q('Which device is used when “ordinariness” is called a tag?',['Metaphor','Onomatopoeia','Hyperbole','Rhyme'],0,'Ordinariness is metaphorically presented as a tag that binds the woman.'),
q('What is suggested by “creativity confined”?',['The speaker has creative potential but limited space or permission to express it','She has no creativity','She is studying art at school','She works as a professional painter'],0,'The phrase establishes potential alongside restriction.'),
q('Why does the poem use household work as evidence of confinement?',['Because those tasks show how creativity is channelled into expected domestic roles','Because the poem is a cooking manual','Because the speaker dislikes books','Because the house is empty'],0,'The domestic list grounds the social critique in everyday work.'),
q('What is the role of silence in the poem?',['Silence is both the result of emotional pressure and a barrier to self-expression','Silence is a celebration','Silence is a season','Silence is a school subject'],0,'The second stanza explicitly ends in silence, while the final stanza hints at breaking through it.'),
q('What broader issue does the poem raise?',['The relationship between social expectations, identity and freedom of self-expression','The price of carpets','The history of books','The weather in a city'],0,'Its domestic imagery points toward questions of identity and social roles.'),
q('What is the best interpretation of the title “Self-Introduction”?',['The speaker introduces her socially defined role while also revealing the hidden self beneath it','It is only a list of household objects','It introduces a city','It is a biography of the poet'],0,'The title fits the first-person act of describing identity and confinement.'),
q('Which section of the source asks learners to discuss gender discrimination?',['C.2 Group Discussion','D.1 Dictionary Use','E. Grammar','G. Translation'],0,'The gender-discrimination prompt is listed under C.2 Group Discussion.'),
q('Which grammar topic begins with bind–bound–bound–binding–binds?',['Verb forms','Reported speech','Articles','Degrees of comparison'],0,'The grammar section asks learners to study and reproduce the forms of bind.'),
q('What does the final source task ask the learner to translate?',['The poem into Hindi or the learner’s mother tongue','Only the glossary','Only the questions','The author biography only'],0,'The final section is a translation of the poem into Hindi or the learner’s mother tongue.')
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function Learn({onMode,onBack}){
 return <div className="poem-shell">
  <button className="poem-exit" onClick={onBack}>← Exit Poetry</button>
  <div className="poem-hero"><span>THE PANORAMA • POETRY CHAPTER 6</span><h1>{poem.title}</h1><p>{poem.poet}</p><p>{poem.context}</p></div>
  <div className="poem-panel poem-context"><div><span className="poem-section-label">ABOUT THE POEM</span><h2>What to understand</h2><p>{poem.structure}</p></div><div className="poem-fact-grid"><div><b>Poet</b><span>{poem.poet}</span></div><div><b>Focus</b><span>Identity • domestic roles • silence • self-expression</span></div></div></div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">STANZA-BY-STANZA</span><h2>Actual poem → simple explanation → vocabulary</h2></div><span>3 complete source blocks</span></div><div className="poem-stanza-grid">{poem.stanzas.map(stanza=><article className="poem-stanza-card" key={stanza.title}><span className="poem-card-kicker">{stanza.range}</span><h3>{stanza.title}</h3><span className="poem-actual-label">ACTUAL POEM</span><div className="poem-actual-stanza">{stanza.poemLines.map(line=><div key={line}>{line}</div>)}</div><span className="poem-simple-label">SIMPLE EXPLANATION</span><p className="poem-stanza-explanation">{stanza.explanation}</p><div className="poem-vocab-block"><span className="poem-simple-label">VOCABULARY</span><div className="poem-word-grid">{stanza.vocab.map(([w,m])=><div key={w}><b>{w}</b><span>{m}</span></div>)}</div></div><div className="poem-stanza-key"><b>Exam focus:</b> {stanza.exam}<br/><b>Key:</b> {stanza.key}</div></article>)}</div></div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">POETRY TOOLKIT</span><h2>Devices and meaning</h2></div></div><div className="poem-device-grid">{poem.devices.map(([d,e])=><article key={d}><b>{d}</b><p>{e}</p></article>)}</div></div>
  <div className="poem-panel poem-two-col"><div><span className="poem-section-label">WORDS TO KNOW</span><h2>Glossary</h2><div className="poem-word-grid">{poem.words.map(([w,m])=><div key={w}><b>{w}</b><span>{m}</span></div>)}</div></div><div><span className="poem-section-label">THEMES</span><h2>Core themes</h2><div className="poem-theme-list">{poem.themes.map(t=><span key={t}>{t}</span>)}</div></div></div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">TEXTBOOK QUESTIONS</span><h2>Very brief + long-answer preparation</h2></div><span>Source-based support</span></div><div className="poem-answer-list">{poem.textbookAnswers.map(([q,a])=><article key={q}><b>{q}</b><p>{a}</p></article>)}</div><h2 style={{marginTop:20}}>Long Answers</h2><div className="poem-answer-list">{poem.longAnswers.map(([q,a])=><article key={q}><b>{q}</b><p>{a}</p></article>)}</div></div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">GROUP DISCUSSION • COMPOSITION</span><h2>Writing and discussion</h2></div></div>{poem.groupDiscussion.map(x=><div className="poem-exam-box" key={x}><p>{x}</p></div>)}{poem.composition.map(x=><div className="poem-exam-box" key={x}><p>{x}</p></div>)}</div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">WORD STUDY</span><h2>Dictionary, word formation and word meaning</h2></div></div>{poem.wordStudy.map(x=><div className="poem-exam-box" key={x.title}><b>{x.title}</b><p>{x.text}</p></div>)}</div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">GRAMMAR</span><h2>Grammar from the chapter</h2></div></div>{poem.grammar.map(x=><div className="poem-exam-box" key={x.title}><b>{x.title}</b><p>{x.text}</p></div>)}</div>
  <div className="poem-panel"><div className="poem-section-heading"><div><span className="poem-section-label">ACTIVITIES • TRANSLATION</span><h2>Think, observe and translate</h2></div></div>{poem.activities.map(x=><div className="poem-exam-box" key={x}><p>{x}</p></div>)}<div className="poem-exam-box"><b>TRANSLATION</b><p>{poem.translation}</p></div></div>
  <div className="poem-modebar"><div><span className="poem-section-label">ASSESSMENT</span><h2>Test what you learned</h2><p>15 Practice • 25 Challenge • 20-question Final Test • timed shared engine</p></div><div className="poem-mode-buttons"><button className="primary" onClick={()=>onMode('practice')}>Practice →</button><button onClick={()=>onMode('challenge')}>Challenge →</button><button onClick={()=>onMode('test')}>Final Test →</button></div></div>
 </div>;
}

export function EnglishPanoramaPoem6({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode==='learn'?'':initialMode);
 if(mode)return <PanoramaTimedQuiz mode={mode} title={poem.title} bank={mode==='practice'?practice:mode==='challenge'?challenge:finalTest} onBack={()=>setMode('')} addXp={addXp} finishSession={finishSession}/>;
 return <Learn onMode={setMode} onBack={onBack}/>;
}
