import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
 title:'The Gift of the Magi',
 author:'O. Henry',
 sourceNote:'Class 9 English • The Panorama • Prose Chapter 9',
 intro:'O. Henry’s story of Jim and Della Young presents Christmas giving as an expression of love. A poor young couple each sacrifices a precious possession to buy a gift for the other, and the final comparison with the Magi gives the story its deeper meaning.',
 authorNote:'The supplied Chapter 9 Panorama pages identify O. Henry (William Sydney Porter) and present the story with comprehension, long-answer, discussion, word-study, Active and Passive Voice, activities and translation work.',
 sections:[
  {title:'Part 1 — Della’s small savings',flow:'Della has only one dollar and eighty-seven cents for Jim’s Christmas present. She counts the money carefully, but the amount is too small for the kind of gift she wants to buy. This opening establishes the couple’s limited financial position.',explanation:'डेला के पास जिम के क्रिसमस उपहार के लिए केवल एक डॉलर और सत्तासी सेंट हैं। वह पैसे को बार-बार गिनती है, लेकिन अपनी पसंद का अच्छा उपहार खरीदने के लिए यह रकम बहुत कम है।',vocabulary:[['savings','बचत'],['cents','सेंट'],['laboriously','बहुत मेहनत से'],['inconsequential','बहुत कम महत्व का'],['prosperity','समृद्धि']],exam:'Opening fact: Della has $1.87. The shortage of money creates the central problem.',think:'Why does the exact amount make Della’s difficulty feel urgent?'},
  {title:'Part 2 — The modest home and their treasures',flow:'Della returns to the couple’s furnished flat, which costs eight dollars a week. The story emphasizes how simple their life is while also introducing the two possessions of which they are most proud: Della’s beautiful hair and Jim’s gold watch.',explanation:'डेला आठ डॉलर प्रति सप्ताह वाले अपने साधारण सुसज्जित फ्लैट में लौटती है। उनके पास धन कम है, लेकिन दोनों के पास एक-एक बहुत कीमती वस्तु है—डेला के सुंदर बाल और जिम की सोने की घड़ी।',vocabulary:[['furnished','सुसज्जित'],['shabby','पुराना / मैला'],['possession','संपत्ति / प्रिय वस्तु'],['fob','घड़ी की छोटी चेन'],['precious','बहुमूल्य']],exam:'Know the setting, the $8 weekly rent, Della’s hair and Jim’s inherited watch.',think:'How does the modest home make their later sacrifices more meaningful?'},
  {title:'Part 3 — Della decides to sell her hair',flow:'Della looks at her long, shining hair and decides that it can provide the money she needs. She goes to a shop that buys hair and sells it for twenty dollars. The decision is painful because her hair is her most prized physical possession.',explanation:'डेला अपने लंबे और चमकदार बालों को देखकर उन्हें बेचने का फैसला करती है। वह बाल खरीदने वाली दुकान जाती है और अपने बालों के बदले बीस डॉलर पाती है। यह त्याग उसके लिए आसान नहीं है।',vocabulary:[['cascade','झरने जैसी लट'],['slender','पतला'],['shining','चमकदार'],['sacrifice','त्याग'],['adornments','सजावट की वस्तुएँ']],exam:'Della sells her hair for $20 because she wants to buy Jim a suitable Christmas gift.',think:'What does this decision reveal about Della’s priorities?'},
  {title:'Part 4 — The platinum fob chain',flow:'Della searches for Jim’s present and finds a platinum fob chain. Jim’s gold watch has been passed down from his father and grandfather, so she wants a chain worthy of such a valuable family possession. The chain costs twenty-one dollars.',explanation:'डेला जिम के लिए प्लैटिनम की घड़ी-चेन खरीदती है। जिम की सोने की घड़ी पिता और दादा से विरासत में मिली है, इसलिए वह उस घड़ी के योग्य चेन चाहती है। इसकी कीमत इक्कीस डॉलर है।',vocabulary:[['platinum','प्लैटिनम'],['fob chain','घड़ी की चेन'],['inheritance','विरासत'],['worthy','योग्य'],['sterling','बहुत अच्छा / उच्च गुणवत्ता वाला']],exam:'Della chooses a platinum chain because Jim’s watch is a treasured family inheritance.',think:'Why is the chain important beyond its price?'},
  {title:'Part 5 — Della waits for Jim',flow:'After buying the chain, Della prepares herself for Jim’s return. She worries about how he will react to her short hair and asks God to let him think she is still pretty. Her anxiety shows how deeply she values Jim’s feelings.',explanation:'चेन खरीदने के बाद डेला जिम के आने की प्रतीक्षा करती है। वह अपने छोटे बालों को लेकर चिंतित है और चाहती है कि जिम उसे अब भी सुंदर समझे।',vocabulary:[['nervously','घबराहट से'],['assertion','दृढ़ कथन'],['primp','सजना-सँवरना'],['intoxication','अत्यधिक उल्लास / नशे की अवस्था'],['curiously','जिज्ञासा से']],exam:'Della’s nervousness comes from love and fear of Jim’s reaction, not from regret about the gift.',think:'Why is Jim’s opinion so important to Della at this moment?'},
  {title:'Part 6 — Jim comes home',flow:'Jim arrives and stands silently before Della. His expression is serious and he looks at her hair. Della explains that she sold it because she loves him and wanted to give him a Christmas present. The scene builds suspense before Jim reveals his own sacrifice.',explanation:'जिम घर आता है और डेला को देखकर गंभीर हो जाता है। डेला बताती है कि उसने प्रेम के कारण अपने बाल बेचे हैं ताकि वह जिम के लिए क्रिसमस का उपहार खरीद सके।',vocabulary:[['stunned','स्तब्ध'],['introspection','आत्मनिरीक्षण'],['sobs','सिसकियाँ'],['sniffles','सुड़कने की आवाजें'],['impression','प्रभाव / धारणा']],exam:'Jim’s silent reaction creates the story’s emotional tension.',think:'Why does the writer delay the explanation of Jim’s expression?'},
  {title:'Part 7 — Jim’s sacrifice',flow:'Jim has sold the gold watch that meant so much to him. With the money, he has bought Della a set of beautiful tortoiseshell combs that she had admired in a shop window. Since Della has cut off her hair, the combs cannot be used immediately.',explanation:'जिम अपनी प्रिय सोने की घड़ी बेचकर डेला के लिए कछुए के खोल की सुंदर कंघियों का सेट खरीदता है। डेला के बाल छोटे हो चुके हैं, इसलिए कंघियाँ अभी उपयोगी नहीं हैं। यही कहानी की मुख्य विडंबना है।',vocabulary:[['tortoiseshell','कछुए के खोल का पदार्थ'],['combs','कंघियाँ'],['coveted','जिसकी बहुत इच्छा की गई हो'],['craved','जिसकी तीव्र इच्छा हो'],['irony','विडंबना']],exam:'Jim gives up his inherited watch so that Della can have the combs she has long wanted.',think:'How is Jim’s sacrifice parallel to Della’s?'},
  {title:'Part 8 — The gifts become temporarily useless',flow:'Della and Jim each owns a gift that has become temporarily useless because the possession connected with that gift has been sacrificed. Della’s short hair makes the combs unusable for now, while Jim’s missing watch leaves the chain without its intended purpose.',explanation:'दोनों उपहारों की उपयोगिता फिलहाल समाप्त हो जाती है, क्योंकि जिन वस्तुओं के लिए वे खरीदे गए थे, उन्हीं वस्तुओं का त्याग कर दिया गया है। यही स्थिति कहानी की विडंबना को गहरा करती है।',vocabulary:[['unusable','उपयोग में न आने वाला'],['purpose','उद्देश्य'],['discreet','सावधान / विवेकपूर्ण'],['meticulously','बहुत सावधानी से'],['predominating','प्रधान / नियंत्रित करने वाला']],exam:'The irony is practical; the emotional value of the gifts remains very high.',think:'Why do the gifts still matter even though they cannot be used immediately?'},
  {title:'Part 9 — The narrator and the Magi',flow:'The narrator compares Jim and Della with the Magi, the three wise men of the East who brought a gift to the infant Christ. The comparison explains the title and suggests that wise giving is not about wealth or usefulness but about love and self-sacrifice.',explanation:'कथाकार जिम और डेला की तुलना मगियों से करता है—उन तीन ज्ञानी पुरुषों से जिन्होंने बालक ईसा के लिए उपहार लाया था। इससे शीर्षक का अर्थ स्पष्ट होता है और त्यागपूर्ण प्रेम को सच्ची बुद्धिमत्ता से जोड़ा जाता है।',vocabulary:[['Magi','बालक ईसा के लिए उपहार लाने वाले तीन ज्ञानी'],['wisdom','बुद्धिमत्ता'],['gift-giving','उपहार देना'],['privilege','विशेष अधिकार'],['enfolded','बाँहों में लेना / समेटना']],exam:'The title is understood through the final comparison of Jim and Della with the Magi.',think:'Why can Jim and Della be called wise after making apparently impractical choices?'},
  {title:'Part 10 — Love, sacrifice and the final message',flow:'The story ends by placing the value of love above possessions. Jim and Della are poor, but each gives up something precious for the other. Their actions show that the essence of love is sacrifice and that generosity can survive even in helpless circumstances.',explanation:'कहानी का मुख्य संदेश यह है कि प्रेम भौतिक वस्तुओं से बड़ा है। जिम और डेला दोनों अपनी सबसे कीमती वस्तु त्यागते हैं और इसी कारण उनका उपहार सच्चे प्रेम का प्रतीक बन जाता है।',vocabulary:[['essence','सार / मूल तत्व'],['selfless','निःस्वार्थ'],['generosity','उदारता'],['helplessness','असमर्थता'],['prudence','विवेक']],exam:'For long answers, connect three ideas: love, sacrifice and the significance of the title.',think:'What does the story teach about the real value of a gift?'}
 ],
 wordStudy:{title:'Word Study',spelling:[['reflection','reflection'],['laboriously','laboriously'],['prosperity','prosperity'],['inconsequential','inconsequential'],['nervously','nervously'],['assertion','assertion'],['worshiped','worshiped'],['yarned','yarned'],['privilege','privilege']],forms:[['predominate','predominating'],['appear','appearance'],['disappear','disappearance'],['generous','generosity'],['mathematics','mathematical'],['privilege','privileged']],matches:[['agile','active'],['cascade','waterfall'],['janitor','doorkeeper'],['appertaining','belonging to'],['predominating','controlling'],['shabby','soiled'],['terrified','scared'],['assertion','statement'],['enfolded','embraced'],['discreet','careful']],phrases:['on account of','cut off','pull out','hold out','wriggle off','all over']},
 grammar:{title:'Active and Passive Voice',intro:'The supplied Chapter 9 PDF has a dedicated Active and Passive Voice section. It explains how the object of the Active sentence becomes the subject of the Passive sentence, how the original subject may become the agent, and how the Passive form uses V³ with a suitable form of “be”.',types:[['Active Voice','The subject does something.','She saw it.'],['Passive Voice','The subject receives the action.','It was seen by her.'],['Past Participle','Passive Voice uses the past participle (V³) with a suitable form of “be”.','He was called Jim.'],['Object → Subject','The Active object becomes the Passive subject.','People called him Jim. → He was called Jim.']]},
 composition:['Discuss the significance of the title “The Gift of the Magi”.','How can you say that Jim and Della loved each other very much?','Describe the family status and the life of Jim and Della.','Who invented the art of giving Christmas gifts and why are Jim and Della called the Magi?','The essence of love is sacrifice. Justify this statement with reference to the lesson.','Do you think that to sell their possessions for Christmas gifts was wise? Give your own opinion.'],
 activities:['Do a project on well-known lovers in the history of human civilization such as Laila–Majnu, Shiri–Farhad, Romeo–Juliet and Heer–Ranjha.','Make some gift items for your best friend.','Discuss in groups: Christmas and its importance.','Discuss in pairs: Love overrides helplessness.'],
 translationPractice:['Some children were playing football in the field.','All the chairs were broken by Mohan.','Can this work be done by tomorrow?','Why have the thieves not been sent to jail?','The two cars were badly damaged in the accident.','Five persons will be sent to help the injured persons.','Jim and Della loved each other very much.','The door opened and Jim stepped in and closed it.','She had a habit of saying little spins.','A new overcoat was needed by Jim.'],
 examPrep:['What is the significance of the title “The Gift of the Magi”?','How can you say that Jim and Della loved each other very much?','Describe the family status and family life of Jim and Della.','Who invented the art of giving Christmas gifts and why are Jim and Della called the Magi?','The essence of love is sacrifice. Justify this statement with reference to the lesson.','Do you think that to sell their possessions for Christmas gifts was wise? Give your own opinion.','Why does Della ask God to make Jim think she is still pretty?','Why does Jim say that their gifts are too nice to use at present?']
};

const practice=[
 {q:'How much money did Della have at the beginning?',o:['One dollar and eighty-seven cents','Twenty dollars','Twenty-one dollars','Eight dollars'],a:0,e:'The story begins with Della having one dollar and eighty-seven cents.'},
 {q:'How much was the rent of Jim and Della’s flat?',o:['Eight dollars a week','Twenty dollars a week','One dollar a week','Ten dollars a month'],a:0,e:'Their modest furnished flat costs eight dollars a week.'},
 {q:'What did Della sell?',o:['Her beautiful hair','Jim’s watch','The flat','The combs'],a:0,e:'Della sells her long, beautiful hair to raise money for Jim’s gift.'},
 {q:'How much did Della receive for her hair?',o:['Twenty dollars','One dollar','Twenty-one dollars','Eight dollars'],a:0,e:'The hair brings Della twenty dollars.'},
 {q:'What did Della buy for Jim?',o:['A platinum fob chain','A new overcoat','Tortoiseshell combs','A gold watch'],a:0,e:'Della buys a platinum fob chain for Jim’s treasured watch.'},
 {q:'Why was Jim’s watch special?',o:['It was a family inheritance','It was newly bought','It belonged to Della','It was a prize from school'],a:0,e:'The watch had belonged to Jim’s father and grandfather.'},
 {q:'What did Jim sell?',o:['His gold watch','His coat','Della’s hair','The apartment'],a:0,e:'Jim sells his gold watch to buy Della’s gift.'},
 {q:'What did Jim buy for Della?',o:['Tortoiseshell combs','A platinum chain','A dress','A necklace'],a:0,e:'Jim buys the set of combs Della had admired.'},
 {q:'Why could Della not use the combs immediately?',o:['Her hair had been cut short','The combs were broken','She lost them','They did not fit the mirror'],a:0,e:'Della has sold her hair, so the combs are temporarily useless.'},
 {q:'Why could Jim not immediately use Della’s chain?',o:['He had sold the watch for which it was bought','The chain was broken','He disliked platinum','It was too long'],a:0,e:'Jim sold his watch before receiving the chain.'},
 {q:'Who are the Magi?',o:['The three wise men who brought a gift to the infant Christ','Jim’s relatives','Railway workers','The shopkeepers'],a:0,e:'The glossary explains the Magi as the three wise men of the East.'},
 {q:'What is the central theme of the story?',o:['Love expressed through selfless sacrifice','Wealth brings happiness','Gifts must be practical','Poverty should be hidden'],a:0,e:'The story places selfless love above material usefulness.'},
 {q:'What worried Della before Jim arrived?',o:['Jim’s reaction to her short hair','The railway schedule','The rent collector','The shopkeeper’s opinion'],a:0,e:'Della fears that Jim may not find her pretty after the haircut.'},
 {q:'What is the significance of $1.87?',o:['It shows how little money Della has','It is the price of the watch','It is the weekly rent','It is the price of the combs'],a:0,e:'The amount establishes Della’s financial difficulty at the start.'},
 {q:'What does the ending emphasize?',o:['The value of love and sacrifice over possessions','The importance of expensive objects','The power of wealth','The uselessness of Christmas'],a:0,e:'The final moral values love, sacrifice and wise giving.'}
];

const challenge=[
 {q:'Why is the opening amount of Della’s money important?',o:['It creates the financial problem that drives the plot','It proves Jim is rich','It explains the Magi immediately','It gives the price of the watch'],a:0,e:'Della’s tiny savings make a suitable Christmas gift difficult to buy.'},
 {q:'How does the modest flat contribute to the story?',o:['It establishes the couple’s limited means and makes their sacrifices more significant','It proves they dislike each other','It explains why Della cuts her hair','It shows they are wealthy'],a:0,e:'The simple home establishes the economic background of the couple.'},
 {q:'Why does Della decide to sell her hair?',o:['Her hair is her most valuable possession and can provide money for Jim’s gift','She dislikes having long hair','Jim tells her to sell it','She wants to become a hairdresser'],a:0,e:'She willingly gives up a treasured possession for Jim.'},
 {q:'Why is Jim’s watch emotionally valuable?',o:['It is an inherited family treasure','It is the newest object in the house','It belongs to Della','It was found in the street'],a:0,e:'The watch has passed through Jim’s family.'},
 {q:'What does Della’s choice of a platinum chain reveal?',o:['She wants a gift worthy of Jim’s cherished inheritance','She cares only about expensive objects','She does not understand Jim’s watch','She wants to sell the chain'],a:0,e:'The chain is chosen because it suits the importance of the watch.'},
 {q:'Why is Della nervous about her appearance?',o:['She fears Jim’s reaction to her short hair','She wants to enter a beauty contest','She plans to sell more hair','She expects the shopkeeper to visit'],a:0,e:'Her concern shows her emotional dependence on Jim’s opinion.'},
 {q:'Why is Jim’s first reaction difficult for Della to understand?',o:['His serious expression gives her no clear clue about his feelings','He refuses to enter the flat','He immediately leaves','He begins laughing'],a:0,e:'The unexplained expression creates suspense before the reveal.'},
 {q:'What creates the central irony?',o:['Each spouse sacrifices the possession needed to use the other spouse’s gift','The shopkeepers give the wrong gifts','Jim and Della refuse to exchange presents','The couple forgets Christmas'],a:0,e:'Della sells her hair before receiving the combs; Jim sells his watch before using the chain.'},
 {q:'Why do the apparently useless gifts still have great value?',o:['They represent deep love and sacrifice','They are secretly very expensive','The Magi take them away','They can be exchanged for money later'],a:0,e:'Their emotional meaning is greater than their immediate practical use.'},
 {q:'Why are Jim and Della compared with the Magi?',o:['Their gift-giving is presented as wise because it is selfless','They are actually biblical kings','They travel to the East','They own great wealth'],a:0,e:'The final comparison connects their sacrifices to wise giving.'},
 {q:'What does “wise” mean in the final paragraph?',o:['Giving with love and willingness to sacrifice','Owning expensive possessions','Never wasting money','Choosing the most useful object'],a:0,e:'The story redefines wisdom through selfless love.'},
 {q:'Why is the title stronger than simply calling the story “Christmas Gifts”?',o:['It connects Jim and Della with the wise Magi and the tradition of meaningful giving','It describes the weekly rent','It names the hair shop','It tells the reader who Jim is'],a:0,e:'The title carries the story’s final moral meaning.'},
 {q:'How does the narrator make a domestic story universal?',o:['He uses the couple’s sacrifices to explore love, generosity and giving','He changes the story into a historical account','He removes Christmas from the plot','He introduces a royal family'],a:0,e:'A small household event becomes a lesson about human relationships.'},
 {q:'Why can the couple’s choices be called both foolish and wise?',o:['The gifts lose practical usefulness but the sacrifices express profound love','They never exchange gifts','They become wealthy immediately','They deceive the shopkeepers'],a:0,e:'The irony is foolish materially but wise emotionally and morally.'},
 {q:'What does the story suggest about material possessions?',o:['Their value may be less important than the relationships for which people sacrifice them','Possessions always create happiness','Possessions determine wisdom','Inherited objects should never be sold'],a:0,e:'Jim and Della surrender what they value most for each other.'},
 {q:'Why does the story repeat Della’s counting of money?',o:['It emphasizes how small her resources are','It proves she cannot count','It gives the price of the combs','It explains the Magi'],a:0,e:'The repeated counting makes her financial problem concrete.'},
 {q:'What makes Della’s decision a sacrifice?',o:['She gives up something she considers beautiful and precious','She gives away something broken','She inherits money afterwards','She receives a reward from the shop'],a:0,e:'Her long hair is one of her most valued possessions.'},
 {q:'What makes Jim’s action parallel to Della’s?',o:['He gives up his most precious possession to buy something Della wanted','He sells her hair','He buys a present for himself','He spends exactly one dollar'],a:0,e:'Both spouses surrender prized possessions for the other.'},
 {q:'What is the story’s view of Christmas giving?',o:['A gift matters most when it expresses genuine concern for another person','Only expensive gifts matter','Christmas giving depends on wealth','Useful gifts are always better than loving gifts'],a:0,e:'The lesson values motive, love and sacrifice.'},
 {q:'Why are Jim and Della shown as deeply devoted?',o:['Their actions show that each is willing to lose something precious for the other','They live in a large house','They never worry about money','They buy identical gifts'],a:0,e:'Their sacrifices provide the strongest evidence of devotion.'},
 {q:'What is the strongest conclusion for an examination answer?',o:['True wisdom in giving comes from selfless love rather than price or usefulness','The best gift is always the most expensive','Wealth is the main theme','Christmas gifts should never be exchanged'],a:0,e:'This conclusion joins the story’s title, irony and theme.'},
 {q:'Why does the Magi reference come at the end?',o:['The reader first sees the sacrifices and then understands their larger meaning','The narrator forgets the title','Jim meets the Magi','The setting changes to a palace'],a:0,e:'The final comparison makes the earlier actions look like wise, selfless giving.'},
 {q:'How does the story balance disappointment and tenderness?',o:['The gifts are practically disappointing, but the sacrifices reveal deep mutual love','The ending is only comic','The couple becomes rich','The narrator removes emotion from the ending'],a:0,e:'Irony and tenderness operate together in the final scene.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function Learn({onMode}){
 return <div className="pg-shell">
  <div className="pg-hero"><span className="pg-kicker">{study.sourceNote}</span><h1>{study.title}</h1><p>O. Henry • short story • love, sacrifice, Christmas giving and irony</p><div className="pg-hero-stats"><span>10 Guided Parts</span><span>Word Study</span><span>Language Focus</span><span>Exam Prep</span></div></div>
  <div className="pg-modebar">{[['learn','LEARN','Guided learning'],['practice','PRACTICE • 15 QUESTIONS • 11:15','Easy → Moderate'],['challenge','CHALLENGE • 23 QUESTIONS • 23:00','Moderate → Hard'],['test','FINAL TEST • 20 QUESTIONS • 25:00','Exam Level']].map(([m,label,sub])=><button key={m} className={m==='learn'?'active':''} onClick={()=>onMode(m)}><b>{label}</b><span>{sub}</span></button>)}</div>
  <div className="pg-panel"><div className="pg-panel-title"><small>LESSON OVERVIEW</small><h2>{study.title}</h2><p>{study.intro}</p></div><div className="pg-author"><b>Author • {study.author}</b><div>{study.authorNote}</div></div></div>
  <div className="pg-anchorbar">{study.sections.map((s,i)=><a key={s.title} href={`#part-${i+1}`}>Part {i+1}</a>)}<a href="#word-study">Word Study</a><a href="#grammar">Language Focus</a><a href="#exam-prep">Exam Prep</a></div>
  <section><div className="pg-section-heading"><span>01</span><div><small>GUIDED READING</small><h2>Understand the story step by step</h2><p>English summary • हिन्दी व्याख्या • vocabulary • exam focus</p></div></div>
   <div className="pg-reading-stack">{study.sections.map((s,i)=><article className="pg-reading-card" id={`part-${i+1}`} key={s.title}><div className="pg-card-top"><div className="pg-num">{String(i+1).padStart(2,'0')}</div><div><span>PART {i+1}</span><h3>{s.title.replace(/^Part \d+ — /,'')}</h3></div></div><div className="pg-flow"><div className="pg-flow-label">English summary</div><p>{s.flow}</p></div><div className="pg-hindi"><div className="pg-flow-label">हिन्दी व्याख्या</div><p>{s.explanation}</p></div><div className="pg-vocab-head">Key vocabulary</div><div className="pg-vocab-grid">{s.vocabulary.map(([w,m])=><div className="pg-vocab" key={w}><b>{w}</b><span>{m}</span></div>)}</div><div className="pg-bottom-grid"><div className="pg-exam"><b>Exam Focus</b><span>{s.exam}</span></div><div className="pg-think"><b>Think</b><span>{s.think}</span></div></div></article>)}</div>
  </section>
  <section id="word-study"><div className="pg-section-heading compact"><span>02</span><div><small>WORD STUDY</small><h2>{study.wordStudy.title}</h2><p>Spelling, word formation, meanings and useful phrases from the supplied Chapter 9 pages.</p></div></div><div className="pg-tool-grid"><div className="pg-panel"><h3>Dictionary spelling</h3><div className="pg-spelling">{study.wordStudy.spelling.map(([a,b])=><div key={a}><b>{b}</b></div>)}</div></div><div className="pg-panel"><h3>Word formation</h3><div className="pg-pillgrid">{study.wordStudy.forms.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></div></div><div className="pg-two-col"><div className="pg-panel"><h3>Match meanings</h3><div className="pg-match">{study.wordStudy.matches.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></div><div className="pg-panel"><h3>Useful phrases</h3><div className="pg-phrasegrid">{study.wordStudy.phrases.map(p=><div key={p}><b>{p}</b><span>Write the meaning and use the phrase in your own sentence.</span></div>)}</div></div></div><div className="pg-panel"><h3>Dictionary meanings to study</h3><div className="pg-match">{['instigate — to provoke or cause something to happen','unassuming — modest and not drawing attention to oneself','intoxication — a state of being strongly affected or excited','hysterical — extremely emotional or uncontrolled','adornments — decorative objects used to make someone or something attractive'].map(x=><div key={x}><span>{x}</span></div>)}</div></div></section>
  <section id="grammar"><div className="pg-section-heading compact"><span>03</span><div><small>LANGUAGE FOCUS</small><h2>{study.grammar.title}</h2><p>{study.grammar.intro}</p></div></div><div className="pg-panel"><div className="pg-grammar-grid">{study.grammar.types.map(([t,d,e])=><div key={t}><b>{t}</b><span>{d}</span><code>{e}</code></div>)}</div><div className="pg-rulebox"><b>Study rule</b><span>The supplied exercise explains that the Active object becomes the Passive subject; the original subject becomes the agent where needed; and a suitable form of “be” is used with the past participle.</span></div><div className="pg-match">{['Ram made this mistake. → This mistake was made by Ram.','No one can solve this problem. → This problem cannot be solved.','People called him Jim. → He was called Jim.'].map(x=><div key={x}><span>{x}</span></div>)}</div></div></section>
  <section id="exam-prep"><div className="pg-section-heading compact"><span>04</span><div><small>EXAM PREP</small><h2>Long-answer, discussion and activity practice</h2><p>These tasks follow the supplied Chapter 9 exercise pages.</p></div></div><div className="pg-exam-grid"><div className="pg-panel"><h3>Important questions</h3><ol>{study.examPrep.map(q=><li key={q}>{q}</li>)}</ol></div><div className="pg-panel"><h3>Composition & discussion</h3><ol>{study.composition.map(q=><li key={q}>{q}</li>)}</ol><h3>Activities</h3><div className="pg-activitygrid">{study.activities.map((q,i)=><div key={q}><span>{i+1}</span><p>{q}</p></div>)}</div></div></div></section>
  <section><div className="pg-panel"><h3>Translation Practice</h3><p className="pg-muted">The supplied PDF asks learners to translate these sentences into Hindi / their mother tongue.</p><div className="pg-translation">{study.translationPractice.map((q,i)=><div key={q}><span>{i+1}</span><b>{q}</b><em>Translate into Hindi / your mother tongue.</em></div>)}</div></div></section>
  <section><div className="pg-panel pg-revision"><h3>Rapid Revision</h3><div className="pg-revision-grid"><div><b>Problem</b><span>Della has only $1.87 for Jim’s Christmas gift.</span></div><div><b>First sacrifice</b><span>Della sells her beautiful hair for $20.</span></div><div><b>Jim’s treasure</b><span>His gold watch is a family inheritance.</span></div><div><b>Gifts</b><span>Platinum fob chain and tortoiseshell combs.</span></div><div><b>Irony</b><span>Each gift becomes temporarily useless because of the sacrifice.</span></div><div><b>Message</b><span>Love, generosity, wise giving and self-sacrifice.</span></div></div></div></section>
 </div>;
}

export function EnglishPanoramaChapter9({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode||'learn');
 const bank=mode==='practice'?practice:mode==='challenge'?challenge:mode==='test'?finalTest:null;
 if(mode!=='learn')return <PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession}/>;
 return <Learn onMode={setMode}/>;
}

export default EnglishPanoramaChapter9;
