import {EnglishReaderEngine} from './EnglishReaderChapter.jsx';
const q=(q,o,a,e)=>({q,o,a,e});

const study={
 chapter:4,
 title:'The Eyes Are Not Here',
 subtitle:'Ruskin Bond • Supplementary Reader-IX',
 sourceNote:'Source: supplied English Reader PDF, Chapter 4, pp. 18–22. The lesson includes the story and the supplied Let’s Answer, Let’s Discuss and Let’s Do exercises.',
 intro:'Ruskin Bond’s short story follows a blind narrator who meets a girl in a train compartment. Their conversation creates a brief, imaginative connection, while both conceal important facts from each other. The ending turns the narrator’s guesses into an ironic reveal and supports the lesson’s idea that insight can be more important than eyesight.',
 sections:[
  {title:'A girl joins the narrator’s compartment',flow:'The narrator has the compartment to himself up to Rohana. Then a girl enters, apparently seen off by her parents. Her family gives her detailed safety instructions. After the train leaves, the narrator listens to the girl’s voice and the sound of her slippers because he cannot see what she looks like.',explanation:'Rohana तक narrator के compartment में वह अकेला था। फिर एक लड़की आती है। उसके parents उसे सावधान रहने की बातें बताते हैं। Narrator पूरी तरह देख नहीं सकता, इसलिए वह लड़की के रूप-रंग के बजाय उसकी आवाज़ और slippers की आवाज़ पर ध्यान देता है।',vocabulary:[['compartment','रेल का डिब्बा/कूपे'],['anxious','चिंतित'],['slippers','चप्पल'],['narrator','कहानी सुनाने वाला']],exam:'Explain how the narrator first experiences the girl without seeing her.',think:'What does the narrator notice because sight is unavailable to him?'},
  {title:'The narrator’s blindness and first question',flow:'The narrator says he is totally blind, with his eyes sensitive only to light and darkness. He asks whether the girl is going all the way to Dehra. His voice startles her because he had been sitting in a dark corner, and she had not known anyone else was there.',explanation:'Narrator बताता है कि वह पूरी तरह blind है और उसकी eyes केवल light और darkness महसूस करती हैं। वह Dehra जाने के बारे में पूछता है। अँधेरे कोने में बैठे होने के कारण उसकी आवाज़ लड़की को अचानक चौंका देती है।',vocabulary:[['totally blind','पूरी तरह दृष्टिहीन'],['sensitive','संवेदनशील'],['startled','अचानक चौंका हुआ'],['dark corner','अँधेरा कोना']],exam:'Remember the narrator’s blindness and why his voice startles the girl.',think:'How does darkness work both literally and psychologically in this opening?'},
  {title:'Dehra, Saharanpur and Mussoorie',flow:'The girl says she is getting down at Saharanpur, where her aunt will meet her. The narrator says he is going to Dehra and then Mussoorie. She says she loves the hills, especially in October. The narrator responds from memory, describing the hills, wild dahlias, sunshine, a log fire and quiet roads.',explanation:'लड़की Saharanpur उतरने वाली है और उसकी aunt वहाँ मिलेगी। Narrator Dehra और फिर Mussoorie जा रहा है। लड़की को October में hills पसंद हैं। Narrator भी memory के आधार पर October की पहाड़ियों और शांत वातावरण का वर्णन करता है।',vocabulary:[['formidable','प्रभावशाली/भय उत्पन्न करने वाला'],['hills','पहाड़ियाँ'],['wild dahlias','जंगली डहेलिया फूल'],['deserted','लगभग सुनसान']],exam:'Explain how the conversation about Mussoorie creates a sense of shared interest.',think:'Why can memory substitute for direct observation in the narrator’s description?'},
  {title:'A question that reveals a secret',flow:'The girl asks, “What is it like?” after the narrator’s description. The narrator wonders whether his words have touched her but then realises that she may already be aware that he cannot see. Her next question, asking why he does not look out of the window, increases his concern about being discovered.',explanation:'Mussoorie की बात पर लड़की पूछती है कि वहाँ कैसा है। Narrator सोचता है कि शायद लड़की ने समझ लिया है कि वह देख नहीं सकता। “Why don’t you look out of the window?” उसका अगला प्रश्न narrator की चिंता बढ़ा देता है।',vocabulary:[['pretense','दिखावा'],['landscape','प्राकृतिक दृश्य'],['reverie','कल्पनाओं/विचारों में खोया हुआ भाव'],['doubt','संदेह']],exam:'Why is the window question important to the narrator?',think:'What does the narrator pretend to be doing at the window?'},
  {title:'Imagining a moving landscape',flow:'The narrator moves to the window and pretends to study the landscape. He hears the engine and wheels and, in his mind’s eye, imagines the telegraph-posts flashing past. He then asks whether the girl has noticed that the trees seem to move while the passengers seem still. She replies that this always happens and asks about animals near Dehra.',explanation:'Narrator खिड़की के पास जाकर landscape देखने का pretense करता है। वह engine और wheels की आवाज़ सुनता है और अपने “mind’s eye” में telegraph-posts को तेजी से गुजरते हुए imagine करता है। लड़की trees की movement और animals के बारे में बात करती है।',vocabulary:[['telegraph-posts','टेलीग्राफ के खंभे'],['fascinating','बहुत आकर्षक'],['remaining senses','दृष्टि के अलावा बची इन्द्रियाँ'],['essential','सबसे आवश्यक']],exam:'Connect the “mind’s eye” with the story’s main contrast between sight and insight.',think:'How does imagination help the narrator participate in visual conversation?'},
  {title:'Flattery, laughter and the short journey',flow:'The narrator tells the girl that she has an interesting face. She laughs and says it is pleasant to be told she has an interesting face because people usually say she is pretty. He then says that an interesting face can also be pretty. She calls him a gallant young man but asks why he is so serious. He feels troubled and lonely even while trying to make her laugh.',explanation:'Narrator लड़की के face को interesting कहता है। लड़की हँसती है और बताती है कि लोग उसे आमतौर पर pretty कहते हैं। बातचीत हल्की होती है, लेकिन narrator भीतर से troubled और lonely महसूस करता है।',vocabulary:[['flattery','प्रशंसा से प्रसन्न करना'],['gallant','शिष्ट/प्रशंसात्मक व्यवहार करने वाला'],['troubled','परेशान'],['lonely','अकेला']],exam:'Describe the emotional contrast between the narrator’s outward conversation and inner loneliness.',think:'Why does laughter not remove the narrator’s loneliness?'},
  {title:'The girl leaves the train',flow:'The train approaches the girl’s station. She says it is good that the journey is short, while the narrator wishes he could keep listening to her. He wonders whether her hair is in a bun, plaited, loose or short. The train reaches the station, and a woman’s high-pitched voice outside seems to belong to the girl’s aunt.',explanation:'Train लड़की के station के पास पहुँचती है। Narrator उसके talking को लंबे समय तक सुनना चाहता है। वह उसके hair के बारे में कल्पना करता है, क्योंकि वह उन्हें देख नहीं सकता। Station पर एक महिला की आवाज़ aunt की लगती है।',vocabulary:[['brief encounter','संक्षिप्त मुलाकात'],['plaited','चोटी की हुई'],['high-pitched','तीखी/ऊँची आवाज़ वाला'],['aunt','मौसी/चाची/बुआ जैसे पारिवारिक संबोधन']],exam:'What does the narrator wonder about the girl’s appearance as she prepares to leave?',think:'Why is the narrator interested in details he cannot actually see?'},
  {title:'The final revelation',flow:'The girl says good-bye and leaves. Another man enters the compartment. The narrator asks whether she kept her hair long or short because he wants to imagine her appearance. The man is puzzled and replies that he remembers her eyes, not her hair, and that she was completely blind. The narrator’s earlier assumptions are overturned by this final reveal.',explanation:'लड़की के जाने के बाद दूसरा आदमी compartment में आता है। Narrator उसके hair के बारे में पूछता है, लेकिन आदमी बताता है कि उसने लड़की की eyes notice की थीं और वह भी completely blind थी। यही कहानी का ironic final reveal है।',vocabulary:[['revelation','अचानक खुला हुआ सत्य'],['puzzled','हैरान/उलझन में'],['assumption','अनुमान'],['ironic','अपेक्षित अर्थ को उलट देने वाला']],exam:'Explain why the ending is ironic and how it changes the reader’s understanding of the conversation.',think:'What did both travellers fail to realise about each other?' }
 ],
 glossary:[['insight','अंतर्दृष्टि/गहरी समझ'],['eyesight','दृष्टि'],['compartment','रेल का डिब्बा'],['sensitive','संवेदनशील'],['landscape','प्राकृतिक दृश्य'],['reverie','कल्पना में खोया भाव'],['fascinating','आकर्षक'],['gallant','शिष्ट और प्रशंसात्मक'],['encounter','मुलाकात'],['revelation','अचानक प्रकट हुआ सत्य'],['irony','परिणाम और अपेक्षा के बीच अर्थपूर्ण विरोध']],
 wordStudy:[['taken in','समझना/ध्यान में लेना'],['make a mistake','गलती करना'],['in my mind’s eye','कल्पना में देखना'],['break into my reverie','कल्पना/विचार से बाहर ला देना'],['keep her hair long or short','उसके रूप के एक दृश्य विवरण के बारे में अनुमान करना'],['appearance is deceptive','दिखावट से वास्तविकता का सही अनुमान नहीं लगाया जा सकता']],
 textbookAnswers:[
  ['Why did the writer ask the man about the girl’s hair? What does the man reply? What hint does it throw on the similarity of the two?','The narrator wanted to imagine the girl’s appearance because he could not see her. The man says he noticed her eyes, not her hair, and reveals that she was completely blind. The narrator and the girl therefore share blindness, although neither realises it during their meeting.'],
  ['How will you describe the experience of the narrator: interesting, dull or instructive? Describe a similar experience of your own.','It is interesting and instructive because a brief conversation becomes meaningful despite the absence of sight, and the ending changes how we interpret it. A personal example may be given from a situation where first impressions proved incomplete.'],
  ['Describe the personality of the writer on the basis of the story.','The narrator appears observant through sound and conversation, imaginative, humorous, self-aware and somewhat lonely. He also tries to hide his blindness and uses imagination to participate in the conversation.'],
  ['Was the girl a lover of natural scenes and situations? Describe her behaviour highlighting what strikes you as odd.','Yes. She says she loves the hills, especially in October, and talks about trees and animals. Her easy conversation is striking, and the final revelation that she too is blind makes her earlier remarks about scenery especially ironic.'],
  ['Why were the girl’s beautiful eyes of no use to her? Attempt a character sketch of the girl.','The story says she was completely blind, so her beautiful eyes could not provide ordinary sight. She appears friendly, confident, interested in nature, responsive to conversation and capable of engaging the narrator playfully.'],
  ['What light does the story throw on human behaviour?','It shows that people often rely on assumptions about appearance and may fail to notice what is most important. It also shows how imagination, conversation and remaining senses can shape human connection.']
 ],
 revision:[['Author','Ruskin Bond.'],['Setting','A train compartment and the journey around Rohana, Saharanpur, Dehra and Mussoorie.'],['Narrator','A man who is completely blind and experiences the world through other senses and imagination.'],['Girl','Friendly and interested in hills, October, trees and animals; she is also revealed to be blind.'],['Key device','Irony: both narrator and girl are blind, but neither realises it during the encounter.'],['Central idea','Insight can be superior to eyesight; appearance and first impressions can mislead.']],
 discussion:['“Appearance is deceptive.” Discuss this statement with reference to the story.'],
 activities:['Do a project work on the problems and challenges faced by a physically challenged man.'],
 extra:'The supplied pages show Literature followed by A. Let’s Answer, B. Let’s Discuss and C. Let’s Do. No separate grammar section is shown, so none has been invented.'
};

const practice=[
 q('Who wrote “The Eyes Are Not Here”?',['Ruskin Bond','Najmul Hasan','Kabir','R.K. Narayan'],0,'The supplied chapter credits Ruskin Bond as the author.'),
 q('What is the narrator unable to do?', ['See properly because he is blind','Hear the train','Speak to the girl','Travel to Dehra'],0,'The narrator says he is totally blind.'),
 q('Where does the girl say she will get down?', ['Saharanpur','Rohana','Dehra','Mussoorie'],0,'She says her aunt is meeting her at Saharanpur.'),
 q('Where is the narrator going after Dehra?', ['Mussoorie','Delhi','Saharanpur','Bombay'],0,'The narrator says he is going to Dehra and then to Mussoorie.'),
 q('What season does the girl especially like in the hills?', ['October','January','April','June'],0,'She says she loves the hills especially in October.'),
 q('What does the narrator hear that helps him experience the journey?', ['The engine and wheels','Only birds','A school bell','A church organ'],0,'He hears the engine and the rumble and rhythm of the wheels.'),
 q('What does the narrator imagine flashing past?', ['Telegraph-posts','Mountains','Animals','Houses'],0,'In his mind’s eye he imagines telegraph-posts flashing by.'),
 q('What does the girl ask when the narrator is at the window?', ['Why don’t you look out of the window?','Why are you going to Delhi?','Do you know my aunt?','Have you seen the train?'],0,'Her question makes the narrator worry that she may notice his blindness.'),
 q('How does the narrator describe the girl’s face?', ['Interesting','Frightening','Unfriendly','Angry'],0,'He calls it an interesting face.'),
 q('Why does the narrator feel troubled and lonely?', ['He cannot genuinely laugh and knows the journey will soon end','He dislikes trains','He is angry with the girl','He has missed his station'],0,'The story says the thought of laughter makes him feel troubled and lonely.'),
 q('What does the narrator wonder about just before the girl leaves?', ['Whether her hair is long, plaited, loose or short','Whether she owns a house','Whether her aunt is young','Whether she likes music'],0,'He imagines several possibilities about her hair.'),
 q('Who enters the compartment after the girl leaves?', ['Another man','Her parents','Her aunt','A guard'],0,'A man getting into the compartment speaks to the narrator.'),
 q('What does the narrator ask the man?', ['Whether the girl kept her hair long or short','Where the train stops','Why the girl was travelling','What her name was'],0,'He asks specifically about the length of her hair.'),
 q('What does the man say he noticed?', ['Her eyes','Her hair','Her slippers','Her dress'],0,'He says he noticed her eyes, not her hair.'),
 q('What final fact about the girl is revealed?', ['She was completely blind','She was a famous singer','She was the narrator’s relative','She had never travelled before'],0,'The final line reveals that she too was completely blind.')
];

const challenge=[
 q('Why is the ending of the story especially ironic?', ['Both the narrator and the girl are blind, but neither realises it during their conversation','The train never reaches a station','The narrator already knows everything about the girl','The girl dislikes the hills'],0,'The ending reverses the reader’s assumptions by revealing a shared condition neither traveller noticed.'),
 q('What does “insight is superior to eyesight” suggest in the context of the story?', ['Understanding can come from imagination, hearing and attention even when sight is absent','Sight is always useless','Blind people cannot understand anything','Only physical appearance matters'],0,'The story values perception and understanding beyond ordinary vision.'),
 q('Why does the narrator focus on the girl’s voice and slippers?', ['They provide information about her presence and personality when sight is unavailable','He is annoyed by the sounds','He wants to leave the train','He thinks slippers are more important than people'],0,'His remaining senses become the main route to experiencing her.'),
 q('What does the narrator’s “mind’s eye” show?', ['He can create a mental picture even without ordinary sight','He secretly has perfect eyesight','He is looking through the window','He has forgotten the journey'],0,'The phrase signals imaginative visualisation rather than physical sight.'),
 q('Why does the window question make the narrator anxious?', ['He suspects the girl may discover that he cannot see','He is afraid of trains','He wants to change compartments','He thinks the window is broken'],0,'He worries that her question may expose his blindness.'),
 q('How does the story use the discussion of natural scenery?', ['It allows the narrator and girl to build apparent common ground while also highlighting the irony of their blindness','It gives a detailed travel guide','It proves the narrator can see','It explains how trains work'],0,'The shared talk about hills, trees and animals creates connection while preparing the final irony.'),
 q('What does the narrator’s question about the girl’s hair reveal about his character?', ['He is curious and imaginative but can only guess at visual details','He already knows her appearance','He dislikes conversation','He wants to embarrass her'],0,'He imagines several possible hairstyles because he cannot actually see them.'),
 q('Why is the girl’s statement that she loves the hills particularly significant after the ending?', ['It becomes ironic because she also cannot see the hills in the ordinary visual sense','It proves she is the aunt','It shows she is pretending to travel','It explains why she leaves early'],0,'The ending changes how the earlier nature conversation is understood.'),
 q('Which contrast best structures the story?', ['Sight versus insight','Rich versus poor','City versus village','Past versus future'],0,'The story repeatedly contrasts physical eyesight with deeper perception.'),
 q('Why does the narrator describe his journey as a fascinating game after looking from the window?', ['Guessing what is outside becomes a mental game when direct visual access is unavailable','He is playing with the guard','He is counting passengers','He is planning a new journey'],0,'He experiences the outside world through imagination and inference.'),
 q('What does the girl’s behaviour suggest before the final revelation?', ['She is friendly, conversational and interested in nature','She is silent and hostile','She is frightened of the narrator','She wants to avoid all strangers'],0,'She engages naturally in conversation and discusses the hills, trees and animals.'),
 q('Why does the narrator’s loneliness remain even during a pleasant conversation?', ['The encounter is brief and his blindness separates him from ordinary visual connection','The girl insults him','The train is empty','He wants to sleep'],0,'His inner loneliness continues despite the temporary pleasure of conversation.'),
 q('What does the man’s puzzled response to the narrator’s hair question add to the story?', ['It creates the final shift from the narrator’s assumptions to the truth about the girl','It introduces a new plot unrelated to the girl','It proves the narrator can see','It explains the timetable'],0,'The man’s response supplies the information the narrator lacked and completes the irony.'),
 q('What common limitation does the ending reveal?', ['Both travellers make incomplete assumptions because they do not know the other person’s condition','Both travellers cannot hear','Both travellers are lost','Both travellers dislike nature'],0,'Neither realises that the other is also blind.'),
 q('How does the story make sound important?', ['Sound replaces many functions of sight for the narrator and helps shape the encounter','Sound is used only for comic effect','Sound proves the girl is a singer','Sound has no role in the ending'],0,'Voice, slippers, engine, wheels and other sounds carry information throughout the story.'),
 q('Why is the narrator’s pretend action at the window important?', ['It shows his effort to hide his blindness and maintain an ordinary conversation','It means he suddenly recovers his sight','It is required by the guard','It proves the girl is lying'],0,'The narrator deliberately pretends to study the landscape so the girl will not know he is blind.'),
 q('Which statement best captures the story’s comment on appearance?', ['People may construct images of others from incomplete clues and can be wrong','Appearance always gives complete truth','Only hair determines personality','Physical appearance is more important than conversation'],0,'The narrator imagines the girl’s looks, while the final revelation shows how unreliable those assumptions are.'),
 q('Why can the narrator’s memory of Mussoorie still feel vivid?', ['Memory and imagination let him recreate a visual world through thought','He secretly sees photographs during the journey','The girl tells him everything in detail','The guard describes it'],0,'The story explicitly describes him calling on his memories and using his mind’s eye.'),
 q('What is the effect of making both characters blind without either knowing it?', ['It turns an ordinary meeting into a carefully built piece of irony and deepens the theme of insight','It removes all tension from the plot','It makes the story purely comic','It proves that the train is unreal'],0,'The shared blindness is the key structural surprise and thematic device.'),
 q('Which quality is most evident in the narrator’s conversation?', ['Imagination','Carelessness','Cruelty','Indifference'],0,'He repeatedly uses imagination to picture what he cannot see and keep the conversation flowing.'),
 q('What does the question about animals contribute to the story?', ['It extends the natural-scene conversation and shows the girl’s interest in the world around Dehra','It identifies the narrator’s profession','It reveals the aunt’s identity','It ends the conversation immediately'],0,'The girl asks about animals near Dehra as part of the discussion of nature.'),
 q('Why does the narrator call the girl’s face interesting rather than simply pretty?', ['He wants to respond safely and honestly without pretending to know her physical appearance','He has seen her clearly','He dislikes pretty faces','He is quoting the aunt'],0,'He cannot see her and chooses a description that does not require visual knowledge.'),
 q('What is the strongest explanation of “appearance is deceptive” for this story?', ['The narrator’s assumptions about the girl’s visible appearance are overturned by the fact that she is blind','The train changes colour','The girl is not really a traveller','The narrator has perfect eyesight'],0,'The final reveal shows that surface assumptions can be misleading.'),
 q('Which exam conclusion best explains the story’s human-behaviour lesson?', ['People should not rely blindly on appearances; careful attention and insight can reveal a different reality','People should avoid talking to strangers','Sight alone gives perfect knowledge','Memory is always unreliable'],0,'The story’s final irony is designed to question assumptions based on outward appearance.'),
 q('Why is the narrator’s brief encounter meaningful even though it lasts only part of a journey?', ['Conversation creates a strong imagined connection that stays with him after the girl leaves','The girl gives him a valuable object','The train journey lasts for several days','They become business partners'],0,'He says the encounter will stay with him beyond the short journey.'),
 q('How does the story combine humour and loneliness?', ['Light, playful conversation exists alongside the narrator’s private awareness of blindness and the shortness of the encounter','The story has no emotional contrast','The humour removes every serious idea','Loneliness appears only in the final sentence'],0,'The narrator’s playful remarks do not erase his inner loneliness, creating emotional complexity.')
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`final-${i}`}));

export function EnglishReaderChapter4({initialMode='learn',onBack,addXp,finishSession}){
 return <EnglishReaderEngine study={{...study}} initialMode={initialMode} onBack={onBack} addXp={addXp} finishSession={finishSession}/>;
}
export const englishReaderChapter4Meta={title:study.title,author:'Ruskin Bond',sourceNote:study.sourceNote,modeCounts:{practice:practice.length,challenge:challenge.length,final:finalTest.length}};
export {study as englishReaderChapter4Study};
