import React,{useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishMessageWritingTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Message Writing क्या है?',simple:'Message एक short written note है जो किसी अनुपस्थित व्यक्ति तक जरूरी information पहुँचाता है। इसमें brevity, accuracy और clarity सबसे important हैं।',meaning:'A message is a brief written note that communicates important information to someone who is absent.',structure:'recipient → date/time → essential information → sender/name',examples:['Phone call message','School meeting message','Urgent visit/update message'],clue:'Message को letter या essay मत बनाओ; केवल जरूरी information रखो।'},
{n:'02',group:'FOUNDATION',title:'Message के 5 सवाल',simple:'हर message लिखने से पहले पूछो: किसके लिए? किसने information दी? क्या हुआ? कब/कहाँ? क्या action चाहिए?',meaning:'These questions identify the people, event, time, place and required action.',structure:'WHO + FROM WHOM + WHAT + WHEN/WHERE + ACTION',examples:['For: Riya | From: Mother | Dentist appointment | 4 p.m. | Call back'],clue:'जो detail receiver के काम की नहीं है, उसे हटाया जा सकता है।'},
{n:'03',group:'FORMAT',title:'MESSAGE heading',simple:'School exam format में ऊपर साफ़ “MESSAGE” heading देना useful है।',meaning:'A clear heading identifies the text as a message.',structure:'MESSAGE',examples:['MESSAGE'],clue:'Heading को long sentence बनाने की जरूरत नहीं।'},
{n:'04',group:'FORMAT',title:'Date और time',simple:'Message में date/time context बहुत useful है, खासकर जब information किसी visit, meeting या call से जुड़ी हो।',meaning:'Date and time establish when the message was written and help prevent confusion.',structure:'date + time',examples:['12 September 2026, 5:30 p.m.'],clue:'कौन-सा time किस event का है, यह wording से clear होना चाहिए।'},
{n:'05',group:'CONTENT',title:'Essential information चुनना',simple:'Message में event, person, time, place, reason और required action जैसी relevant details रखो।',meaning:'Include only information needed to understand and act on the message.',structure:'event + key details + required action',examples:['The meeting is at 11 a.m. in Room 4. Please bring your notebook.'],clue:'Background story बढ़ाने की बजाय actionable facts लिखो।'},
{n:'06',group:'LANGUAGE',title:'Short और clear sentences',simple:'Message की language simple, direct और easy-to-read होनी चाहिए। बहुत लंबे sentences से बचो।',meaning:'Short, direct sentences reduce misunderstanding.',structure:'one idea → one clear sentence',examples:['Mr Sharma called. Please meet him at 3 p.m.'],clue:'एक sentence में कई unrelated details ठूँसने से clarity कम होती है।'},
{n:'07',group:'LANGUAGE',title:'Indirect information को सही लिखना',simple:'अगर caller ने कोई specific instruction या request दी है तो उसे meaning बदले बिना concise रूप में लिखो।',meaning:'Transfer the caller’s instruction accurately without changing its meaning.',structure:'reported information → exact action/request',examples:['Father asked you to call him after 7 p.m.'],clue:'अपनी तरफ से नई instruction मत जोड़ो।'},
{n:'08',group:'TONE',title:'Formal और neutral tone',simple:'Message आमतौर पर polite और neutral होता है। “Hey!!! Hurry!!!” जैसी casual wording से बचो, जब तक context अलग न हो।',meaning:'A neutral, polite tone keeps the message appropriate and dependable.',structure:'polite + direct + neutral',examples:['Please call me when you return.','Kindly attend the meeting at 10 a.m.'],clue:'Tone receiver और situation के हिसाब से रखो।'},
{n:'09',group:'PRECISION',title:'Who, when, where और action',simple:'Receiver को अगर आगे कुछ करना है तो action साफ़ लिखो—call, visit, bring, submit, attend आदि।',meaning:'A useful message makes the required next action explicit.',structure:'who → when → where → action',examples:['Please submit the form to the office by 2 p.m.'],clue:'सिर्फ “He called” लिखकर रुक जाना कई situations में incomplete होगा।'},
{n:'10',group:'COMMON TYPES',title:'Common message situations',simple:'Phone calls, invitations, appointments, school notices, reminders, travel updates और urgent information common practice situations हैं।',meaning:'Different situations change the details, but the concise structure remains similar.',structure:'situation → key facts → action',examples:['Missed call','Parent’s message','Meeting reminder','Appointment update'],clue:'Situation पहचानो और वही details चुनो जो receiver को चाहिए।'},
{n:'11',group:'COMMON ERRORS',title:'Common mistakes',simple:'Heading missing, sender/receiver unclear, date-time omitted, unnecessary story, ambiguous pronouns और missing action common mistakes हैं।',meaning:'Most mistakes come from incomplete or unclear information.',structure:'heading → context → essentials → action → sender',examples:['Weak: “Call me later.”','Better: “Amit called at 4 p.m. Please call him after 6 p.m.”'],clue:'हर message के बाद पूछो: क्या receiver बिना दोबारा पूछे समझ जाएगा?'},
{n:'12',group:'FORMAT CONTROL',title:'Sender का नाम और ending',simple:'अंत में message लिखने वाले का नाम देना useful है ताकि receiver जान सके information किसने pass की।',meaning:'A sender name identifies who recorded or delivered the message.',structure:'information → sender/name',examples:['— Neha','From: Rahul'],clue:'Sender वही होना चाहिए जिसने message note किया है, न कि automatically caller।'},
{n:'13',group:'GUIDED BUILD',title:'Message step-by-step बनाओ',simple:'पहले facts note करो। फिर MESSAGE heading, date/time, receiver/context, essential information, action और sender जोड़ो।',meaning:'A fixed sequence makes message writing quick and accurate under exam pressure.',structure:'facts → heading → details → action → sender → audit',examples:['Caller: Mr Verma | Call: 2 p.m. | Event: meeting | Action: bring file'],clue:'पहले rough facts लिखना grammar mistakes भी कम करता है।'},
{n:'14',group:'EXAM CONTROL',title:'Word economy और accuracy',simple:'Message short रखते हुए essential detail नहीं हटानी है। Short ≠ incomplete. हर word का काम होना चाहिए।',meaning:'Brevity means removing unnecessary words while keeping all essential facts.',structure:'remove repetition → keep facts → preserve meaning',examples:['Long: “He told me to inform you that you should...” → Short: “He asked you to...”'],clue:'Length कम करने के चक्कर में time, place या action मत हटाओ।'},
{n:'15',group:'FINAL AUDIT',title:'Final Message Audit',simple:'Submit करने से पहले check करो: heading है? receiver/context clear है? कौन, क्या, कब, कहाँ clear हैं? action दिया है? sender का नाम है? भाषा concise है?',meaning:'The final audit checks clarity, completeness and brevity.',structure:'HEADING ✓ WHO ✓ WHAT ✓ WHEN ✓ WHERE ✓ ACTION ✓ SENDER ✓',examples:['Heading ✓','Essential facts ✓','Action ✓','Sender ✓'],clue:'Message पढ़कर receiver को तुरंत पता चलना चाहिए कि क्या हुआ और अब क्या करना है।'}
];

const BANKS={
practice:[
['What is the main purpose of a message?',['to communicate important information briefly','to narrate a long story','to write a personal diary','to describe a poem'],0,'A message communicates necessary information to another person briefly.'],
['Which heading is suitable?',['MESSAGE','ESSAY','STORY','NOTICE BOARD'],0,'MESSAGE clearly identifies the format.'],
['Which detail is usually essential?',['time of the event or call','the writer’s favourite colour','a long family history','an unrelated joke'],0,'Time often helps the receiver understand or act on the information.'],
['Which sentence is clear and concise?',['Please call Father after 7 p.m.','I just wanted to tell you that maybe at some point you could perhaps call him.','Call.','Father.'],0,'The first sentence communicates a complete action clearly.'],
['A good message should mainly use…',['direct and neutral language','confusing slang','long descriptions','fictional dialogue'],0,'Direct, neutral language makes information easy to use.'],
['What should the sender include?',['their name or identifying sign-off','a full autobiography','a poem','an unrelated opinion'],0,'The sender name identifies who recorded or passed the message.'],
['Which question checks message completeness?',['What action should the receiver take?','What is my favourite movie?','How many jokes can I add?','Can I make it a story?'],0,'Action is often essential to a useful message.'],
['Which is a good final check?',['who, what, when, where, action and sender','only difficult vocabulary','only handwriting size','only the heading'],0,'A complete audit checks the key information and sender.']
],
challenge:[
['A message says “He called. Tell her.” What is the main weakness?',['the people and required information are unclear','the heading is too long','there are too many details','the sender is overexplained'],0,'Ambiguous pronouns and missing context can make a message unusable.'],
['Which is the strongest message content for a meeting?',['Mr Khan called. The meeting is at 11 a.m. in Room 5. Please bring the project file.','There is a meeting and many things happened.','Meeting!!! Hurry!!!','Mr Khan is a nice person.'],0,'It identifies the caller, time, place and action.'],
['Which edit improves “Please kindly be informed that I am writing to tell you that your father wants you to call him”?',['Father asked you to call him.','Your father has requested the action of making a call.','Call maybe.','Your father is somewhere.'],0,'The first option keeps the meaning while removing unnecessary wording.'],
['What should you remove first when shortening a message?',['repetition and unnecessary background','time and place','the required action','the key event'],0,'Remove repetition first, not essential facts.'],
['Which phrase best gives a clear action?',['Please submit the form by 2 p.m.','Something about the form.','You know what to do.','The form exists.'],0,'The first sentence specifies both action and deadline.'],
['A caller gives an exact appointment time. What should the message writer do?',['record the time accurately','replace it with “later”','omit it','guess another time'],0,'Accuracy is essential when transferring information.'],
['Which ending best identifies the message writer?',['— Rahul','Once upon a time','Best wishes for a long essay','Anonymous story'],0,'A simple sender name identifies who recorded the message.'],
['Why is brevity important in message writing?',['the receiver should find the needed information quickly','short messages can contain no facts','longer is always worse','messages must be exactly one sentence'],0,'The goal is quick, accurate communication of essential information.']
],
test:[
['Which best describes message writing?',['brief communication of essential information to another person','a detailed essay','a diary entry','a fictional story'],0,'A message is short, practical and information-focused.'],
['Which heading is correct for this format?',['MESSAGE','REPORT','APPLICATION','ARTICLE'],0,'MESSAGE is the standard identifying heading in school practice.'],
['Which set of facts is most useful?',['who, what, when, where and action','only feelings','only adjectives','only greetings'],0,'These facts let the receiver understand and respond.'],
['Which is the clearest sentence?',['Please meet the principal at 10 a.m. in the office.','Maybe principal office sometime.','Meeting thing.','You know.'],0,'The first gives person, time and place clearly.'],
['What should a message avoid?',['unnecessary story and repetition','essential details','clear action','accurate time'],0,'Messages should be concise and purposeful.'],
['If a caller says “Bring the science file,” the message should…',['keep that action accurately','change it to “Bring any file”','omit it','add a different instruction'],0,'The message should preserve the caller’s intended instruction.'],
['Why is a sender name useful?',['it shows who recorded or passed the information','it makes the message longer for no reason','it replaces the main information','it gives a personal essay'],0,'The sender name provides clear attribution.'],
['Which final line is strongest?',['Please call him after 6 p.m. — Neha','He called and stuff.','Anyway, that is all.','I had a great day.'],0,'It gives a clear action and identifies the sender.'],
['What does “short ≠ incomplete” mean?',['remove unnecessary words but keep all essential facts','delete important details','write only one word','avoid time and action'],0,'Brevity should improve efficiency without losing required information.'],
['Which final audit is best?',['heading, people, event, time/place, action and sender','only spelling','only punctuation','only word count'],0,'These checks cover the essential message-writing requirements.']
]};

const EXAMPLES=[
{title:'Example 1 — Phone Call',topic:'Your mother is out. Mr Sharma calls to say that the parent meeting is tomorrow at 10 a.m. in the school auditorium and asks her to bring the student record.',parts:['MESSAGE','12 September 2026, 5:30 p.m.','Mr Sharma called to inform you that the parent meeting is tomorrow at 10 a.m. in the school auditorium. Please bring the student record.','— Neha']},
{title:'Example 2 — Appointment Update',topic:'Your brother is absent. A doctor’s clinic calls to confirm an appointment at 4 p.m. on Monday.',parts:['MESSAGE','14 September 2026, 11:00 a.m.','The clinic called to confirm your appointment on Monday at 4 p.m. Please reach the clinic on time.','— Rahul']},
{title:'Example 3 — School Meeting',topic:'Your friend is away. The class teacher calls to ask him to meet her tomorrow at 9 a.m. and bring his project file.',parts:['MESSAGE','15 September 2026, 3:15 p.m.','The class teacher called. She asked you to meet her tomorrow at 9 a.m. and bring your project file.','— Amit']}
];

const SUBJECTIVE=[
'Your father is away. His colleague calls to say that the office meeting has been shifted to 3 p.m. tomorrow. Write the message.',
'Your sister is not at home. A friend calls to invite her to a study group at 5 p.m. on Sunday at the library. Write the message.',
'Your class teacher calls while you are at home and asks a classmate to submit the science project by 10 a.m. tomorrow. Write the message.',
'Your mother is away. The doctor’s clinic calls to confirm an appointment for Friday at 4 p.m. Write the message.',
'Your brother is absent. His coach calls to remind him to bring his sports kit for practice at 6 a.m. tomorrow. Write the message.',
'A neighbour calls while your father is out and asks him to attend a residents’ meeting at 7 p.m. on Saturday in the community hall. Write the message.',
'Your friend is away. The school office calls to tell her that certificates can be collected from the office tomorrow between 11 a.m. and 1 p.m. Write the message.',
'Write a message informing your classmate that the group meeting has moved from Room 3 to Room 7 at 2 p.m. today and everyone should bring their notes.'
];

const shuffle=(arr)=>{const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};

export default function EnglishMessageWritingTopic({onBack,addXp,finishSession}){
 const[lesson,setLesson]=useState(0);const[mode,setMode]=useState('learn');const[quizKey,setQuizKey]=useState(0);const[done,setDone]=useState(false);const data=LESSONS[lesson];
 const bank=useMemo(()=>shuffle(BANKS[mode==='practice'?'practice':mode==='challenge'?'challenge':'test'].map((q,i)=>{const opts=q[1].map((text,idx)=>({text,correct:idx===q[2]}));return{question:q[0],options:shuffle(opts),explanation:q[3],id:`message-${mode}-${i}`}})),[mode,quizKey]);
 const start=(m)=>{setMode(m);if(m!=='learn'){setDone(false);setQuizKey(k=>k+1)}};
 const handleFinish=(result)=>{setDone(true);addXp?.(result?.score?Math.max(5,Math.round(result.score)):5);finishSession?.({subject:'English',topic:'Message Writing',mode,score:result?.score??0,total:result?.total??bank.length,at:new Date().toISOString()})};
 const back=()=>{if(onBack)onBack();else{const p=new URLSearchParams();p.set('page','language-skills');p.set('subject','english');p.set('languageSkills','1');p.delete('topic');p.delete('mode');window.location.assign(`${window.location.pathname}?${p.toString()}${window.location.hash||''}`)}};
 return <main className="message-topic-shell"><header className="message-topic-hero"><button type="button" className="message-topic-back" onClick={back}>← Language &amp; Skills</button><div className="message-topic-kicker">ENGLISH • WRITING</div><h1>Message Writing</h1><p>Learn to write short, accurate and exam-ready messages.</p></header>
 <nav className="message-topic-tabs" aria-label="Message Writing modes">{[['learn','Learn'],['practice','Practice'],['challenge','Challenge'],['test','Final Test']].map(([m,label])=><button key={m} type="button" className={`message-mode-tab ${mode===m?'active':''}`} onClick={()=>start(m)}>{label}</button>)}</nav>
 {mode==='learn'?<>
 <section className="message-progress"><div><strong>Lesson {data.n} of {LESSONS.length}</strong><span>{data.group}</span></div><div className="message-progress-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></section>
 <section className="message-lesson-card"><div className="message-number">{data.n}</div><div className="message-lesson-content"><div className="message-badge">{data.group}</div><h2>{data.title}</h2><p className="message-simple">{data.simple}</p><div className="message-grid"><div><h3>In English</h3><p>{data.meaning}</p></div><div><h3>Structure</h3><p className="message-structure">{data.structure}</p></div></div><div className="message-block"><h3>Examples</h3>{data.examples.map((x,i)=><div key={i} className="message-example">{x}</div>)}</div><div className="message-clue"><strong>Exam clue:</strong> {data.clue}</div></div></section>
 <div className="message-nav"><button type="button" onClick={()=>setLesson(Math.max(0,lesson-1))} disabled={lesson===0}>← Previous</button><span>{lesson+1}/{LESSONS.length}</span><button type="button" onClick={()=>setLesson(Math.min(LESSONS.length-1,lesson+1))} disabled={lesson===LESSONS.length-1}>Next →</button></div>
 <section className="message-examples-section"><h2>Model Messages</h2><p>Simple patterns you can adapt in an exam.</p>{EXAMPLES.map((ex,i)=><article className="message-model" key={i}><h3>{ex.title}</h3><p className="message-prompt"><strong>Situation:</strong> {ex.topic}</p><div className="message-paper">{ex.parts.map((part,j)=><p key={j} className={j===0?'message-heading':''}>{part}</p>)}</div></article>)}</section>
 <section className="message-subjective"><h2>Subjective Practice — Write Yourself</h2><p>इनका answer खुद लिखो; ये timed MCQ score में include नहीं हैं।</p>{SUBJECTIVE.map((q,i)=><div className="message-writing-task" key={i}><span>{i+1}</span><p>{q}</p></div>)}</section>
 <section className="message-audit"><h2>Quick Audit</h2><div className="message-audit-grid">{['MESSAGE heading','Who / what','Date or time','Place / context','Required action','Sender name','Concise language'].map(x=><div key={x}>✓ {x}</div>)}</div></section>
 </>:<section className="message-quiz-wrap"><EnglishTimedQuiz key={quizKey} title={mode==='practice'?'Message Writing Practice':mode==='challenge'?'Message Writing Challenge':'Message Writing Final Test'} questions={bank} onFinish={handleFinish} durationSeconds={mode==='practice'?300:mode==='challenge'?360:480}/>{done&&<div className="message-complete">Assessment submitted. Review your answers above and retry for another attempt.</div>}</section>}
 </main>
}