import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
 title:'The Gift of the Magi',
 author:'O. Henry',
 sourceNote:'Class 9 English • The Panorama • Prose Chapter 9',
 intro:'O. Henry’s story follows Jim and Della Young, a young married couple whose love is shown through selfless Christmas gifts. Their most valuable possessions are sacrificed so that each can buy a gift for the other.',
 authorNote:'The supplied Chapter 9 textbook pages identify O. Henry and present the story together with comprehension, word study, grammar, activities and translation exercises.',
 sections:[
  {title:'Part 1 — Della’s one dollar and eighty-seven cents',flow:'Della has saved only one dollar and eighty-seven cents for Christmas. She has counted the money carefully, but it is far less than she needs to buy a suitable gift for Jim. Her small savings show how limited the couple’s finances are.',explanation:'डेला के पास क्रिसमस के लिए केवल एक डॉलर और सत्तासी सेंट हैं। उसने पैसे को कई बार गिना है, लेकिन जिम के लिए अच्छा उपहार खरीदने के लिए यह रकम बहुत कम है। इससे दंपति की आर्थिक कठिनाई स्पष्ट होती है।',vocabulary:[['counted','गिना'],['savings','बचत'],['suitable','उपयुक्त'],['finances','आर्थिक स्थिति'],['need','जरूरत']],exam:'Remember the opening amount: $1.87. It establishes the problem and Della’s financial difficulty.',think:'Why does the exact amount make Della’s problem immediately convincing?'},
  {title:'Part 2 — Their small flat',flow:'Della returns home to their modest flat at eight dollars a week. She looks around at the furnishings and notices that the house is comfortable only in a limited way. The setting emphasizes that Jim and Della are a young couple with little money but a shared home.',explanation:'डेला आठ डॉलर प्रति सप्ताह किराए वाले छोटे फ्लैट में लौटती है। घर की साज-सज्जा साधारण है और उनके सीमित साधनों को दिखाती है। फिर भी यह जिम और डेला का साझा घर है।',vocabulary:[['furnished','सुसज्जित'],['modest','साधारण'],['flat','फ्लैट / मकान'],['furnishings','घर का सामान'],['comfortable','आरामदायक']],exam:'The inexpensive flat provides the social and economic background for the story.',think:'How does the setting help us understand the couple before the gifts are exchanged?'},
  {title:'Part 3 — Della sees her beautiful hair',flow:'Della looks at herself in the mirror and realizes that her long, shining hair is her greatest possession. She decides to sell it so that she can raise enough money for Jim’s Christmas gift. She goes to a shop that buys hair and receives twenty dollars.',explanation:'डेला आईने में अपने लंबे, चमकदार बाल देखती है और तय करती है कि वह इन्हें बेच देगी। वह बाल खरीदने वाली दुकान पर जाती है और इसके बदले बीस डॉलर प्राप्त करती है।',vocabulary:[['shining','चमकदार'],['cascade','झरने जैसी लट'],['precious','कीमती'],['sell','बेचना'],['receive','प्राप्त करना']],exam:'Della sacrifices her beautiful hair to obtain money for Jim’s gift.',think:'Why can a person willingly give up a treasured possession for someone they love?'},
  {title:'Part 4 — Della chooses Jim’s gift',flow:'With the money from her hair, Della searches for a special present for Jim. She finds a beautiful platinum fob chain made for the gold watch that had belonged to his father and grandfather. She pays twenty-one dollars and feels that the chain is worthy of Jim and his precious watch.',explanation:'बाल बेचकर मिली रकम से डेला जिम के लिए प्लैटिनम की सुंदर घड़ी-चेन खरीदती है। जिम की सोने की घड़ी पारिवारिक विरासत है, इसलिए डेला को लगता है कि यह उपहार उसके लिए उपयुक्त है।',vocabulary:[['platinum','प्लैटिनम'],['fob chain','घड़ी की चेन'],['inheritance','विरासत'],['worthy','योग्य / उपयुक्त'],['precious','अमूल्य']],exam:'Jim’s watch is valuable because it is a family inheritance; Della wants a chain worthy of it.',think:'What does the chain reveal about Della’s understanding of Jim’s values?'},
  {title:'Part 5 — Della prepares before Jim returns',flow:'Della reaches home before Jim arrives. She works to make her short hair look neat, curls it and prepares for his reaction. Although she is anxious, she is also excited because she believes her sacrifice has secured a meaningful gift for her husband.',explanation:'जिम के आने से पहले डेला घर लौटती है। वह अपने छोटे बालों को सँवारती और कर्ल करती है तथा जिम की प्रतिक्रिया को लेकर चिंतित रहती है। फिर भी वह अपने उपहार को लेकर उत्साहित है।',vocabulary:[['anxious','चिंतित'],['curl','बालों को घुंघराला करना'],['primp','सजना-सँवरना'],['reaction','प्रतिक्रिया'],['eagerly','उत्सुकता से']],exam:'Della’s anxiety comes from love and anticipation, not from regret about helping Jim.',think:'Why is Della more worried about Jim’s response than about her own changed appearance?'},
  {title:'Part 6 — Jim sees Della’s hair',flow:'Jim arrives and stares at Della. His expression is serious and difficult for her to understand. Della quickly explains that she sold her hair because she loves him and wanted to buy him a Christmas present. She asks him not to judge her until they have exchanged gifts.',explanation:'जिम घर आता है और डेला को देखकर चकित तथा गंभीर हो जाता है। डेला तुरंत बताती है कि उसने उससे प्रेम के कारण अपने बाल बेच दिए। वह चाहती है कि जिम पहले उपहार देखे और फिर प्रतिक्रिया दे।',vocabulary:[['stare','टकटकी लगाकर देखना'],['astonished','चकित'],['judgment','निर्णय / राय'],['explain','समझाना'],['sacrifice','त्याग करना']],exam:'Jim’s silence is important because it creates the tension before the gift exchange.',think:'Why does the author delay the explanation of Jim’s reaction?'},
  {title:'Part 7 — Jim’s surprising gift',flow:'Jim finally reveals that he has sold the gold watch that was so important to him. He has used the money to buy Della an expensive set of tortoiseshell combs that she had long admired in a shop window. The combs are useless to her now because she has cut off her hair, creating the story’s central irony.',explanation:'जिम ने अपनी विरासत की सोने की घड़ी बेचकर डेला के लिए सुंदर कछुए के खोल वाली कंघियों का सेट खरीदा था। डेला के छोटे बाल होने के कारण वे कंघियाँ फिलहाल उपयोग में नहीं आ सकतीं। यही स्थिति कहानी की विडंबना को जन्म देती है।',vocabulary:[['tortoiseshell','कछुए के खोल का पदार्थ'],['combs','कंघियाँ'],['admire','पसंद करना'],['irony','विडंबना'],['useless','अनुपयोगी']],exam:'Both gifts have become temporarily unusable because each spouse sold the possession connected with the other’s gift.',think:'Why is the uselessness of the gifts also evidence of their love?'},
  {title:'Part 8 — Christmas gifts and selfless love',flow:'Della and Jim exchange gifts even though each has sacrificed the possession that made the other’s gift useful. Their actions reveal that the purpose of giving was love, not practical benefit. The story turns the disappointing material result into an emotionally meaningful one.',explanation:'डेला और जिम जानते हैं कि उनके उपहार फिलहाल उपयोगी नहीं हैं, फिर भी वे एक-दूसरे के प्रेम को समझते हैं। उन्होंने उपयोगिता के लिए नहीं, बल्कि प्रेम के लिए अपनी कीमती वस्तुएँ त्यागीं।',vocabulary:[['selfless','निःस्वार्थ'],['devotion','समर्पण'],['generosity','उदारता'],['meaningful','अर्थपूर्ण'],['benefit','लाभ']],exam:'The central idea is that true giving is measured by sacrifice and love rather than usefulness.',think:'What makes a gift meaningful even when its practical value is reduced?'},
  {title:'Part 9 — Why the Magi matter',flow:'The narrator compares Jim and Della with the Magi, the wise men who brought gifts to the infant Christ. The comparison shifts the story from a small domestic exchange to a universal idea of wise giving. Jim and Della are called foolish in one sense, yet the story suggests that their loving sacrifice makes them truly wise.',explanation:'कथाकार जिम और डेला की तुलना मगियों से करता है, जिन्होंने बालक ईसा के लिए उपहार लाए थे। यह तुलना बताती है कि सच्ची बुद्धिमत्ता प्रेम और त्याग में है।',vocabulary:[['Magi','ईसा के लिए उपहार लाने वाले तीन ज्ञानी'],['wise','बुद्धिमान'],['gift','उपहार'],['wisdom','बुद्धिमत्ता'],['sacrifice','त्याग']],exam:'The title becomes clear through the final comparison with the Magi.',think:'Why does the narrator call the couple the “wise” gift-givers after showing that their gifts cannot be used immediately?'},
  {title:'Part 10 — Love above possessions',flow:'The story finally values Jim and Della’s love above material possessions. Their willingness to sacrifice what was most precious to them proves the depth of their relationship. The ending also suggests that selfless giving, not wealth, is what makes Christmas meaningful.',explanation:'कहानी के अंत में जिम और डेला का प्रेम उनकी संपत्ति से अधिक महत्वपूर्ण बनकर सामने आता है। दोनों ने अपनी सबसे कीमती वस्तुएँ त्यागकर एक-दूसरे के प्रति सच्चा प्रेम दिखाया।',vocabulary:[['possession','संपत्ति / वस्तु'],['selfless giving','निःस्वार्थ देना'],['precious','बहुमूल्य'],['relationship','संबंध'],['meaningful','अर्थपूर्ण']],exam:'For exams, connect three ideas: sacrifice, love and the significance of the title.',think:'How does the ending redefine what “wise” giving means?'}
 ],
 wordStudy:{title:'Word Study',spelling:[['reflection','reflection'],['laboriously','laboriously'],['prosperity','prosperity'],['inconsequential','inconsequential'],['nervously','nervously'],['assertion','assertion'],['worshiped','worshiped'],['yarned','yarned'],['privilege','privilege']],forms:[['predominate','predominating'],['appear','appearance'],['disappear','disappearance'],['generous','generosity'],['mathematics','mathematical'],['privilege','privileged']],matches:[['agile','active'],['cascade','waterfall'],['janitor','doorkeeper'],['appertaining','belonging to'],['predominating','controlling'],['shabby','soiled'],['terrified','scared'],['assertion','statement'],['enfolded','embraced'],['discreet','careful']],phrases:['on account of','cut off','pull out','hold out','wriggle off','all over']},
 grammar:{title:'Active and Passive Voice',intro:'The supplied Chapter 9 PDF gives a dedicated Active and Passive Voice lesson and practice. The examples move between Active and Passive forms and emphasize the object–subject change.',types:[['Active Voice','The subject does something.','She saw it.'],['Passive Voice','Something is done to the subject.','It was seen by her.'],['Past Participle','In the Passive Voice the verb uses its V³ form with a form of “be”.','He was called Jim.'],['Object → Subject','The object of the Active sentence becomes the subject of the Passive.','People called him Jim. → He was called Jim.']]},
 composition:['Discuss the significance of the title “The Gift of the Magi”.','How can you say that Jim and Della loved each other very much?','Describe the family status and the life of Jim and Della.','Who invented the art of giving Christmas gifts and why are Jim and Della called the Magi?','Justify the sentence “The essence of love is sacrifice” with reference to the lesson.','Do you think that to sell their possessions for Christmas gifts was wise? Give your own opinion.'],
 activities:[
  'Do a project on the well-known lovers in the history of human civilization, such as Laila–Majnu, Shiri–Farhad, Romeo–Juliet and Heer–Ranjha.',
  'Make some gift items for your best friend.',
  'Discuss in groups: Christmas and its importance.',
  'Discuss in pairs: Love overrides helplessness.'
 ],
 translationPractice:['Some children were playing football in the field.','All the chairs were broken by Mohan.','Can this work be done by tomorrow?','Why have the thieves not been sent to jail?','The two cars were badly damaged in the accident.','Five persons will be sent to help the injured persons.','Jim and Della loved each other very much.','The door opened and Jim stepped in and closed it.','She had a habit of saying little spins.','A new overcoat was needed by Jim.'],
 examPrep:[
  'What is the significance of the title “The Gift of the Magi”?',
  'How can you say that Jim and Della loved each other very much?',
  'Describe the family status and as well as family life of Jim and Della.',
  'Who invented the art of giving Christmas gifts and why are Jim and Della called the Magi?',
  'The essence of love is sacrifice. Justify this statement with reference to the lesson.',
  'Do you think that to sell their possessions for Christmas gifts was wise? Give your own opinion.',
  'Why does Della say, “Please God, make him think I am still pretty”?',
  'Why does Jim say that their gifts are “too nice to use at present”?'
 ]
};

const practice=[
 {q:'How much money did Della have at the beginning?',o:['One dollar and eighty-seven cents','Twenty dollars','Twenty-one dollars','Eight dollars'],a:0,e:'Della has saved one dollar and eighty-seven cents for Christmas.'},
 {q:'How much was the rent of Jim and Della’s flat?',o:['Eight dollars a week','Twenty dollars a week','One dollar a week','Ten dollars a month'],a:0,e:'The story describes their furnished flat as costing eight dollars a week.'},
 {q:'What did Della sell?',o:['Her beautiful hair','Jim’s watch','The apartment','A set of combs'],a:0,e:'Della sells her long hair so that she can buy Jim a Christmas present.'},
 {q:'How much did Della receive for her hair?',o:['Twenty dollars','One dollar','Twenty-one dollars','Eight dollars'],a:0,e:'The hair seller gives Della twenty dollars.'},
 {q:'What did Della buy for Jim?',o:['A platinum fob chain for his watch','A new overcoat','A set of combs','A gold watch'],a:0,e:'She buys a platinum chain suited to Jim’s inherited gold watch.'},
 {q:'Whose watch did Jim possess?',o:['His father’s and grandfather’s inherited watch','Della’s father’s watch','The shopkeeper’s watch','A railway watch'],a:0,e:'The watch is described as a family inheritance from Jim’s father and grandfather.'},
 {q:'What did Jim sell?',o:['His gold watch','His coat','Della’s hair','The flat'],a:0,e:'Jim sells the gold watch so that he can buy Della’s desired combs.'},
 {q:'What did Jim buy for Della?',o:['A set of tortoiseshell combs','A platinum chain','A new dress','A silver watch'],a:0,e:'Jim buys the combs Della had admired in the shop window.'},
 {q:'Why were Jim’s combs not immediately useful?',o:['Della had cut off her hair','They were broken','Jim had lost them','They were too small'],a:0,e:'Della’s hair is now short because she sold it.'},
 {q:'Why were Della’s chain and Jim’s watch temporarily mismatched?',o:['Jim had sold the watch','The chain was too short','Della disliked platinum','The watch was broken'],a:0,e:'Jim sold the watch to buy Della’s combs.'},
 {q:'Who are the Magi in the title?',o:['The wise men who brought gifts to the infant Christ','Jim’s relatives','The shopkeepers','The railway workers'],a:0,e:'The glossary identifies the Magi as the three wise men of the East who offered a gift to the infant Christ.'},
 {q:'What is a central idea of the story?',o:['Love is shown through selfless sacrifice','Money always brings happiness','Gifts must always be practical','Young couples should avoid Christmas'],a:0,e:'Jim and Della show love by sacrificing possessions for each other.'},
 {q:'What was Della worried about before Jim came home?',o:['How Jim would react to her short hair','Whether the train would arrive','Whether the rent was due','Whether the shop was open'],a:0,e:'She is anxious about Jim’s reaction to her changed appearance.'},
 {q:'What does the exact amount $1.87 mainly establish?',o:['Della’s financial difficulty','Jim’s wealth','The price of the watch','The cost of the flat'],a:0,e:'The small savings amount sets up the problem that leads to Della’s sacrifice.'},
 {q:'What does the ending suggest about wealth?',o:['Love and sacrifice can matter more than possessions','Wealth is the only source of wisdom','Possessions should never be shared','Christmas gifts are unimportant'],a:0,e:'The story values selfless love above material possessions.'}
];

const challenge=[
 {q:'Why is the opening sentence about Della’s money important to the plot?',o:['It immediately creates the problem she must solve to buy Jim a gift','It proves Jim is wealthy','It explains the Magi in detail','It shows that the couple has many servants'],a:0,e:'The tiny savings amount creates the practical problem that leads to Della’s sacrifice.'},
 {q:'How does the small flat support the story’s theme?',o:['It shows that the couple has limited means, making each sacrifice more significant','It proves they are unhappy','It explains why Jim sells his watch','It shows that Della dislikes her home'],a:0,e:'Their modest home establishes the financial context in which the gifts become costly sacrifices.'},
 {q:'Why does Della choose to sell her hair?',o:['It is her most valuable possession and can provide money quickly for Jim’s gift','She dislikes her hair','Jim asks her to sell it','The shop refuses to sell anything else'],a:0,e:'Her hair is her greatest possession and selling it gives her enough money to buy the present.'},
 {q:'Why is Jim’s watch especially significant?',o:['It is a family inheritance, so selling it involves an emotional sacrifice','It is a cheap watch','It belongs to Della','It was bought that morning'],a:0,e:'The text stresses that the watch had passed through Jim’s family.'},
 {q:'What does Della’s choice of the platinum chain show?',o:['She wants Jim’s gift to match the importance of his inherited watch','She only wants a costly object','She does not understand Jim','She plans to sell the chain later'],a:0,e:'She judges the chain by its suitability for the cherished watch.'},
 {q:'Why does Della worry about being “still pretty”?',o:['She fears that cutting her hair may affect Jim’s feelings, showing her emotional vulnerability','She wants to enter a contest','She wants to sell more hair','She dislikes Christmas'],a:0,e:'Her concern is about Jim’s opinion and their emotional bond.'},
 {q:'Why is Jim’s first reaction difficult for Della to interpret?',o:['His expression is serious and unusual, so she cannot tell whether he is angry, surprised or disappointed','He refuses to enter the house','He is asleep','He leaves immediately'],a:0,e:'The serious look delays the reader’s understanding of his reaction and builds suspense.'},
 {q:'What creates the central irony of the story?',o:['Each spouse sacrifices the possession that would have made the other’s gift useful','They refuse to exchange gifts','The couple secretly dislike one another','The shopkeeper gives them the wrong objects'],a:0,e:'The gifts are loving but temporarily unusable because of the sacrifices behind them.'},
 {q:'Why does the uselessness of the presents not make the story meaningless?',o:['The sacrifices themselves express the depth of Jim and Della’s love','The objects are secretly worthless','The Magi take the gifts away','The narrator forgets the gifts'],a:0,e:'The value of the gifts lies in the love and sacrifice, not merely in practical use.'},
 {q:'Why are Jim and Della compared with the Magi?',o:['Their giving is presented as wise because it is motivated by selfless love','They are actually the biblical Magi','They travel to the East','They are wealthy kings'],a:0,e:'The final comparison extends the story’s small domestic act into a larger idea of wise giving.'},
 {q:'What is the deeper meaning of “wise” in the ending?',o:['Wisdom is connected with love, generosity and willingness to sacrifice','Wisdom means owning expensive things','Wisdom means never giving gifts','Wisdom means earning more money'],a:0,e:'The narrator redefines wisdom through selfless giving.'},
 {q:'Why is the title more effective than a title such as “Christmas Gifts”?',o:['It links Jim and Della’s sacrifices with the tradition of wise gift-giving represented by the Magi','It gives the couple biblical names','It explains the apartment rent','It focuses only on Della’s hair'],a:0,e:'The title captures the story’s final moral and its comparison to the Magi.'},
 {q:'How does the narrator turn an ordinary domestic problem into a universal message?',o:['He uses the couple’s sacrifice to discuss love, generosity and the true value of giving','He removes the Christmas setting','He adds a historical war','He describes a royal palace'],a:0,e:'A small household exchange becomes an example of a wider human value.'},
 {q:'Why can the couple’s decisions be called foolish and wise at the same time?',o:['They lose practical usefulness but gain a deeper expression of love','They make no decisions at all','They become wealthy immediately','They trick the shopkeepers'],a:0,e:'From a practical point of view the gifts are unusable; morally, the sacrifices show wisdom of love.'},
 {q:'What does the story suggest about material possessions?',o:['Their value can be less important than the relationships for which people are willing to give them up','They always guarantee happiness','They should never be inherited','They determine moral worth'],a:0,e:'The most prized possessions are surrendered for the sake of the relationship.'},
 {q:'Why is Della’s money-counting repeated?',o:['It emphasizes how small her resources are and how serious her gift problem is','It proves she cannot do mathematics','It explains the Magi','It shows Jim has taken the money'],a:0,e:'Repeated counting makes the shortage concrete and urgent.'},
 {q:'What makes Della’s sacrifice emotionally powerful?',o:['She gives up a physical feature she is proud of without expecting a material reward for herself','She sells something she dislikes','She receives a large inheritance','Jim forces her to do it'],a:0,e:'She sacrifices something precious because she wants to please Jim.'},
 {q:'What makes Jim’s sacrifice parallel to Della’s?',o:['He gives up his most precious possession for a gift he believes will make Della happy','He spends the same amount of money','He sells her hair','He buys a gift for himself'],a:0,e:'Both spouses surrender their greatest possessions for the other’s happiness.'},
 {q:'Which statement best explains the story’s view of Christmas giving?',o:['Giving becomes meaningful when it expresses genuine concern for another person','The expensive gift is always the best gift','Christmas giving depends on wealth','Useful gifts are the only gifts that matter'],a:0,e:'The story prioritizes motive, love and sacrifice over practical usefulness.'},
 {q:'What is the strongest reason to call Jim and Della devoted to each other?',o:['Each is willing to lose something precious so the other can receive a meaningful gift','They live in a large house','They never disagree','They buy matching clothes'],a:0,e:'Their actions, not merely their words, prove their devotion.'},
 {q:'What is the best exam conclusion for the story?',o:['True wisdom in giving comes from selfless love rather than the price or usefulness of the gift','Christmas gifts should always be expensive','The story mainly celebrates wealth','The couple should not have exchanged gifts'],a:0,e:'This conclusion captures the title, irony and central theme together.'},
 {q:'Why is the Magi reference placed at the end rather than the beginning?',o:['The reader first experiences the sacrifices and only then understands their larger moral significance','The author forgets the title until the end','The story changes its setting to the East','The couple meets the Magi in the flat'],a:0,e:'The final comparison makes the reader reinterpret the earlier actions as acts of wise giving.'},
 {q:'How does the story balance sadness and tenderness?',o:['The practical result is disappointing, but the sacrifices reveal deep mutual love','The ending is entirely comic','The couple becomes rich','The narrator removes all emotion'],a:0,e:'The irony of the gifts is softened and deepened by the tenderness of the sacrifices.'},
 {q:'Which interpretation best connects the title, gifts and sacrifices?',o:['The finest gifts are those in which the giver willingly sacrifices something precious for another person','The finest gifts are always rare metals','The Magi bought the same presents as Jim and Della','Only wealthy people can give wisely'],a:0,e:'The story’s title and final paragraph unite the ideas of gift-giving and self-sacrifice.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function Learn({onMode}){
 return <div className="pg-shell">
  <div className="pg-hero"><span className="pg-kicker">{study.sourceNote}</span><h1>{study.title}</h1><p>O. Henry • short story • love, sacrifice, Christmas giving and irony</p><div className="pg-hero-stats"><span>10 Guided Parts</span><span>Word Study</span><span>Language Focus</span><span>Exam Prep</span></div></div>
  <div className="pg-modebar">{[['learn','LEARN','Guided learning'],['practice','PRACTICE • 15 QUESTIONS • 11:15','Easy → Moderate'],['challenge','CHALLENGE • 23 QUESTIONS • 23:00','Moderate → Hard'],['test','FINAL TEST • 20 QUESTIONS • 25:00','Exam Level']].map(([m,label,sub])=><button key={m} className={m==='learn'?'active':''} onClick={()=>onMode(m)}><b>{label}</b><span>{sub}</span></button>)}</div>
  <div className="pg-panel"><div className="pg-panel-title"><small>LESSON OVERVIEW</small><h2>{study.title}</h2><p>{study.intro}</p></div><div className="pg-author"><b>Author • {study.author}</b><div>{study.authorNote}</div></div></div>
  <div className="pg-anchorbar">{study.sections.map((s,i)=><a key={s.title} href={`#part-${i+1}`}>Part {i+1}</a>)}<a href="#word-study">Word Study</a><a href="#grammar">Language Focus</a><a href="#exam-prep">Exam Prep</a></div>
  <section><div className="pg-section-heading"><span>01</span><div><small>GUIDED READING</small><h2>Understand the story step by step</h2><p>English summary • हिन्दी व्याख्या • vocabulary • exam focus</p></div></div>
   <div className="pg-reading-stack">{study.sections.map((s,i)=><article className="pg-reading-card" id={`part-${i+1}`} key={s.title}><div className="pg-card-top"><div className="pg-num">{String(i+1).padStart(2,'0')}</div><div><span>PART {i+1}</span><h3>{s.title.replace(/^Part \d+ — /,'')}</h3></div></div><div className="pg-flow"><div className="pg-flow-label">English summary</div><p>{s.flow}</p></div><div className="pg-hindi"><div className="pg-flow-label">हिन्दी व्याख्या</div><p>{s.explanation}</p></div><div className="pg-vocab-head">Key vocabulary</div><div className="pg-vocab-grid">{s.vocabulary.map(([w,m])=><div className="pg-vocab" key={w}><b>{w}</b><span>{m}</span></div>)}</div><div className="pg-bottom-grid"><div className="pg-exam"><b>Exam Focus</b><span>{s.exam}</span></div><div className="pg-think"><b>Think</b><span>{s.think}</span></div></div></article>)}</div>
  </section>
  <section id="word-study"><div className="pg-section-heading compact"><span>02</span><div><small>WORD STUDY</small><h2>{study.wordStudy.title}</h2><p>Spelling, word formation, meanings and useful phrases from the supplied Chapter 9 exercise pages.</p></div></div><div className="pg-tool-grid"><div className="pg-panel"><h3>Dictionary spelling</h3><div className="pg-spelling">{study.wordStudy.spelling.map(([a,b])=><div key={a}><b>{b}</b></div>)}</div></div><div className="pg-panel"><h3>Word formation</h3><div className="pg-pillgrid">{study.wordStudy.forms.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></div></div><div className="pg-two-col"><div className="pg-panel"><h3>Match meanings</h3><div className="pg-match">{study.wordStudy.matches.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></div><div className="pg-panel"><h3>Useful phrases</h3><div className="pg-phrasegrid">{study.wordStudy.phrases.map(p=><div key={p}><b>{p}</b><span>Write the meaning and use the phrase in your own sentence.</span></div>)}</div></div></div><div className="pg-panel"><h3>Two meanings to study</h3><div className="pg-match">{['instigate — to provoke or cause something to happen; to urge someone to act','unassuming — modest and not claiming attention; simple in manner','intoxication — a state caused by alcohol or strong excitement; overwhelming delight','hysterical — wildly emotional; suffering from a condition of uncontrolled emotion','adornments — decorative objects; things used to make someone or something attractive'].map(x=><div key={x}><span>{x}</span></div>)}</div></div></section>
  <section id="grammar"><div className="pg-section-heading compact"><span>03</span><div><small>LANGUAGE FOCUS</small><h2>{study.grammar.title}</h2><p>{study.grammar.intro}</p></div></div><div className="pg-panel"><div className="pg-grammar-grid">{study.grammar.types.map(([t,d,e])=><div key={t}><b>{t}</b><span>{d}</span><code>{e}</code></div>)}</div><div className="pg-rulebox"><b>Study rule</b><span>In the supplied exercise, the object of the Active Voice becomes the subject of the Passive Voice, the original subject becomes the agent, and the Passive verb uses V³ with a suitable form of “be”.</span></div><div className="pg-match">{['Ram made this mistake. → This mistake was made by Ram.','No one can solve this problem. → This problem cannot be solved.','People called him Jim. → He was called Jim.'].map(x=><div key={x}><span>{x}</span></div>)}</div></div></section>
  <section id="exam-prep"><div className="pg-section-heading compact"><span>04</span><div><small>EXAM PREP</small><h2>Practise the long-answer and discussion questions</h2><p>These prompts are taken from or closely organized around the supplied Chapter 9 textbook exercises.</p></div></div><div className="pg-exam-grid"><div className="pg-panel"><h3>Important questions</h3><ol>{study.examPrep.map(q=><li key={q}>{q}</li>)}</ol></div><div className="pg-panel"><h3>Composition & discussion</h3><ol>{study.composition.map(q=><li key={q}>{q}</li>)}</ol><h3>Activities</h3><div className="pg-activitygrid">{study.activities.map((q,i)=><div key={q}><span>{i+1}</span><p>{q}</p></div>)}</div></div></div></section>
  <section><div className="pg-panel"><h3>Translation Practice</h3><p className="pg-muted">The supplied PDF asks learners to translate these sentences into Hindi / their mother tongue. They are also useful for Active–Passive revision.</p><div className="pg-translation">{study.translationPractice.map((q,i)=><div key={q}><span>{i+1}</span><b>{q}</b><em>Translate into Hindi / your mother tongue.</em></div>)}</div></div></section>
  <section><div className="pg-panel pg-revision"><h3>Rapid Revision</h3><div className="pg-revision-grid"><div><b>Problem</b><span>Della has only $1.87 for Jim’s Christmas present.</span></div><div><b>Sacrifice</b><span>Della sells her hair and Jim sells his inherited watch.</span></div><div><b>Gifts</b><span>Platinum chain for the watch; tortoiseshell combs for Della.</span></div><div><b>Irony</b><span>Each gift becomes temporarily unusable because of the sacrifice.</span></div><div><b>Theme</b><span>Love, generosity, selfless giving and sacrifice.</span></div><div><b>Title</b><span>Jim and Della are compared with the wise Magi.</span></div></div></div></section>
 </div>;
}

export function EnglishPanoramaChapter9({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode||'learn');
 const bank=mode==='practice'?practice:mode==='challenge'?challenge:mode==='test'?finalTest:null;
 if(mode!=='learn')return <PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession}/>;
 return <Learn onMode={setMode}/>;
}

export default EnglishPanoramaChapter9;
