import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
  title:'My Childhood',
  author:'A. P. J. Abdul Kalam',
  sourceNote:'Class 9 English • The Panorama • Prose Chapter 8',
  intro:'An autobiographical account of Abdul Kalam’s childhood in Rameswaram. The lesson follows his family life, friendships across religious communities, his first wages during the Second World War, and two school experiences that shaped his understanding of equality and social harmony.',
  authorNote:'Dr. A. P. J. Abdul Kalam (1931–2015) was an Indian aerospace scientist and later the 11th President of India. This lesson is drawn from his autobiographical writing and focuses on formative childhood experiences.',
  sections:[
    {title:'Part 1 — Rameswaram and a secure childhood',flow:'Kalam recalls his childhood in Rameswaram, where he lived with his parents and siblings in a modest but secure family environment. His ancestral house, built in the middle of the nineteenth century, stood on Mosque Street.',explanation:'कलाम अपने बचपन को रामेश्वरम् के सुरक्षित पारिवारिक वातावरण से याद करते हैं। वे अपने माता-पिता और भाई-बहनों के साथ रहते थे। उनका पुश्तैनी घर उन्नीसवीं शताब्दी के मध्य में बना था और मस्जिद वाली गली में स्थित था।',vocabulary:[['ancestral','पुश्तैनी'],['secure','सुरक्षित'],['modest','सादा / साधारण'],['environment','परिवेश'],['siblings','भाई-बहन']],exam:'Remember the setting: Rameswaram, family life, and the ancestral house on Mosque Street.',think:'How can a simple but secure home influence a child’s confidence?'},
    {title:'Part 2 — Parents and inherited values',flow:'Kalam describes his father Jainulabdeen as wise and generous and his mother Ashiamma as kind and caring. From his father he inherited honesty and self-discipline; from his mother he inherited faith in goodness and deep kindness.',explanation:'कलाम अपने पिता जैनुलाब्दीन को बुद्धिमान और उदार तथा अपनी माता आशिअम्मा को दयालु और स्नेही बताते हैं। उन्होंने पिता से ईमानदारी और आत्म-अनुशासन तथा माता से अच्छाई में विश्वास और गहरी दयालुता सीखी।',vocabulary:[['wisdom','बुद्धिमत्ता'],['generous','उदार'],['honesty','ईमानदारी'],['self-discipline','आत्म-अनुशासन'],['kindness','दयालुता']],exam:'A major exam point is the direct connection between parents and Kalam’s character.',think:'Why does Kalam connect personal character with family influence?'},
    {title:'Part 3 — Faiths living together',flow:'The family participated in local religious life and Kalam grew up hearing stories from both the Ramayana and the life of the Prophet. His childhood therefore included different religious traditions without treating them as barriers.',explanation:'कलाम के परिवार का स्थानीय धार्मिक जीवन से जुड़ाव था। वे रामायण की कथाएँ और पैगंबर के जीवन से जुड़ी कथाएँ सुनते हुए बड़े हुए। उनके बचपन में अलग-अलग धार्मिक परंपराएँ विभाजन नहीं, बल्कि परिचय का हिस्सा थीं।',vocabulary:[['tradition','परंपरा'],['religious','धार्मिक'],['barrier','बाधा / विभाजन'],['upbringing','पालन-पोषण'],['harmony','सामंजस्य']],exam:'The lesson repeatedly contrasts religious difference with shared human relationships.',think:'What does Kalam’s childhood suggest about learning tolerance from everyday life?'},
    {title:'Part 4 — Three close friends',flow:'Kalam had three close friends: Ramanadha Sastry, Aravindan and Sivaprakasan. They came from orthodox Hindu Brahmin families, yet the boys did not feel separated by religion during childhood.',explanation:'कलाम के तीन घनिष्ठ मित्र रमानाध शास्त्री, अरविंदन और शिवप्रकाशन थे। वे रूढ़िवादी हिंदू ब्राह्मण परिवारों से थे, फिर भी बचपन में धार्मिक भिन्नता ने उनकी मित्रता में दूरी पैदा नहीं की।',vocabulary:[['orthodox','रूढ़िवादी'],['friendship','मित्रता'],['difference','भिन्नता'],['community','समुदाय'],['companionship','साथ / मित्रता']],exam:'Know all three names and the central fact that religious difference did not divide them.',think:'Why is childhood friendship presented as stronger than social labels?'},
    {title:'Part 5 — The annual Shri Sita Rama Kalyanam',flow:'During the annual Shri Sita Rama Kalyanam ceremony, Kalam’s family arranged boats with a special platform to carry temple idols to the marriage site in Rama Tirtha, the pond near their home.',explanation:'श्री सीता राम कल्याणम् के वार्षिक समारोह में कलाम का परिवार मंदिर की मूर्तियों को पास के राम तीर्थ तालाब में विवाह-स्थल तक ले जाने के लिए विशेष मंच वाली नावों की व्यवस्था करता था।',vocabulary:[['ceremony','समारोह'],['idol','मूर्ति'],['platform','मंच'],['pond','तालाब'],['marriage site','विवाह-स्थल']],exam:'The ceremony detail shows cooperation between Kalam’s Muslim family and the wider local religious community.',think:'How does this ceremony support the chapter’s idea of shared community life?'},
    {title:'Part 6 — The Second World War reaches his childhood',flow:'The Second World War broke out in 1939, when Kalam was eight. The distant war initially had little effect on isolated Rameswaram, but the situation later changed when India was drawn into the Allied war effort.',explanation:'द्वितीय विश्व युद्ध 1939 में शुरू हुआ, तब कलाम आठ वर्ष के थे। आरंभ में दूरस्थ रामेश्वरम् पर युद्ध का प्रभाव कम था, लेकिन बाद में स्थिति बदली जब भारत मित्र राष्ट्रों के युद्ध प्रयास में शामिल हो गया।',vocabulary:[['outbreak','आरंभ / प्रकोप'],['Allied Forces','मित्र राष्ट्रों की सेना'],['isolated','अलग-थलग'],['emergency','आपात स्थिति'],['impact','प्रभाव']],exam:'1939 and Kalam’s age of eight are important factual details.',think:'How can a global event gradually affect an apparently distant local community?'},
    {title:'Part 7 — Tamarind seeds and early work',flow:'As a child, Kalam noticed a sudden demand for tamarind seeds. He collected them and sold them to a provision shop, earning one anna for a day’s collection. This was an early experience of earning through his own effort.',explanation:'बचपन में कलाम ने इमली के बीजों की अचानक बढ़ी माँग देखी। वे बीज इकट्ठा करके एक किराने की दुकान पर बेचते थे और एक दिन के संग्रह के बदले एक आना कमाते थे। यह अपने श्रम से कमाई का शुरुआती अनुभव था।',vocabulary:[['demand','माँग'],['collect','इकट्ठा करना'],['provision shop','किराने की दुकान'],['earn','कमाना'],['anna','आने का पुराना मुद्रा-मान']],exam:'Do not confuse the tamarind-seed work with his later newspaper-bundle job.',think:'What might a first small earning teach a child about work and responsibility?'},
    {title:'Part 8 — Newspaper bundles and first wages',flow:'When the train stopped halting at Rameswaram, newspaper bundles were thrown from the moving train. Kalam’s cousin Samsuddin, who distributed newspapers, needed help catching the bundles. Kalam joined him and earned his first wages.',explanation:'जब रामेश्वरम् स्टेशन पर ट्रेन का ठहराव बंद हुआ तो अखबारों के बंडल चलती ट्रेन से बाहर फेंके जाने लगे। अखबार बाँटने वाले उनके चचेरे भाई सम्सुद्दीन को बंडल पकड़ने के लिए सहायता चाहिए थी। कलाम ने यह काम किया और पहली मजदूरी कमाई।',vocabulary:[['bundle','बंडल'],['distribute','वितरित करना'],['wages','मजदूरी'],['suspension','स्थगन / बंद होना'],['pride','गौरव']],exam:'Samsuddin + moving train + newspaper bundles + first wages = a key sequence.',think:'Why did this small job become such a memorable event for Kalam?'},
    {title:'Part 9 — A friendship challenged at school',flow:'In fifth standard, a new teacher noticed Kalam sitting in the front row beside Ramanadha Sastry, the son of a Hindu priest. The teacher objected to their seating because of religious prejudice and ordered Kalam to the backbench.',explanation:'पाँचवीं कक्षा में एक नए शिक्षक ने कलाम को हिंदू पुजारी के बेटे रमानाध शास्त्री के साथ आगे बैठे देखा। धार्मिक पूर्वाग्रह के कारण शिक्षक ने इस साथ बैठने को स्वीकार नहीं किया और कलाम को पीछे की बेंच पर भेज दिया।',vocabulary:[['prejudice','पूर्वाग्रह'],['backbench','पीछली बेंच'],['sacred thread','जनेऊ'],['front row','आगे की पंक्ति'],['discriminate','भेदभाव करना']],exam:'The episode illustrates communal intolerance entering an otherwise harmonious childhood.',think:'Why is the teacher’s action presented as a social problem rather than merely a seating change?'},
    {title:'Part 10 — Ramanadha’s grief',flow:'Kalam felt deeply hurt and Ramanadha was equally upset. Ramanadha’s tears when Kalam moved to the last row left a lasting impression on the narrator.',explanation:'कलाम को बहुत दुःख हुआ और रमानाध भी अत्यंत दुखी हुआ। जब कलाम पीछे की पंक्ति में गए तो रमानाध का रोना लेखक के मन पर स्थायी प्रभाव छोड़ गया।',vocabulary:[['downcast','बहुत उदास'],['lasting','स्थायी'],['impression','प्रभाव'],['grief','दुःख'],['solidarity','एकजुटता']],exam:'The image of Ramanadha weeping is the emotional centre of this incident.',think:'How does Ramanadha’s reaction reveal the depth of their friendship?'},
    {title:'Part 11 — Lakshmana Sastry challenges discrimination',flow:'Ramanadha’s father, Pakshi Lakshmana Sastry, was the high priest of the Rameswaram temple. He confronted the teacher, rejected social inequality and communal intolerance, and demanded an apology or the teacher’s departure.',explanation:'रमानाध के पिता पाक्षी लक्ष्मण शास्त्री रामेश्वरम् मंदिर के उच्च पुजारी थे। उन्होंने शिक्षक का विरोध करते हुए सामाजिक असमानता और सांप्रदायिक असहिष्णुता को बच्चों के मन में फैलने से रोकने की बात कही और शिक्षक से क्षमा माँगने या विद्यालय छोड़ने को कहा।',vocabulary:[['high priest','मुख्य पुजारी'],['inequality','असमानता'],['intolerance','असहिष्णुता'],['apologise','क्षमा माँगना'],['confront','सामना करना']],exam:'Lakshmana Sastry represents moral authority used to protect equality and friendship.',think:'Why was an adult’s intervention necessary in this situation?'},
    {title:'Part 12 — A science teacher tests social barriers',flow:'Kalam’s science teacher Sivasubramania Iyer wanted to challenge rigid social divisions. He invited Kalam to his home for a meal, even though his wife initially objected to serving a Muslim boy.',explanation:'कलाम के विज्ञान शिक्षक शिवसुब्रह्मण्यम अय्यर कठोर सामाजिक विभाजनों को चुनौती देना चाहते थे। उन्होंने कलाम को घर पर भोजन के लिए बुलाया, जबकि उनकी पत्नी ने शुरू में एक मुस्लिम बच्चे को भोजन कराने पर आपत्ति की।',vocabulary:[['rigid','कठोर'],['social division','सामाजिक विभाजन'],['invite','आमंत्रित करना'],['object','आपत्ति करना'],['reform','सुधार करना']],exam:'Iyer’s action is important because he deliberately challenged inherited social prejudice.',think:'What makes a teacher influential beyond the classroom?'},
    {title:'Part 13 — The dinner invitation changes the situation',flow:'Iyer did not withdraw his invitation. He served Kalam himself and then persuaded his wife to reconsider. The next time, she served Kalam without resistance. The episode shows that attitudes can change through contact and example.',explanation:'अय्यर ने अपना निमंत्रण वापस नहीं लिया। उन्होंने स्वयं कलाम को भोजन कराया और बाद में अपनी पत्नी को अपनी सोच पर पुनर्विचार करने के लिए प्रेरित किया। अगली बार उनकी पत्नी ने बिना विरोध के कलाम को भोजन परोसा।',vocabulary:[['reconsider','पुनर्विचार करना'],['resistance','विरोध'],['attitude','दृष्टिकोण'],['example','उदाहरण'],['change','परिवर्तन']],exam:'The second meal shows a change in attitude; remember this as evidence that social habits can change.',think:'Why can personal example be more effective than an argument alone?'},
    {title:'Part 14 — Friends grow into different professions',flow:'As adults, the three friends followed different careers: Ramanadha became the priest of the Rameswaram temple, Aravindan worked in transport for pilgrims, and Sivaprakasan became a catering contractor for the Southern Railways.',explanation:'बड़े होने पर तीनों मित्रों ने अलग-अलग पेशे अपनाए। रमानाध रामेश्वरम् मंदिर के पुजारी बने, अरविंदन तीर्थयात्रियों के परिवहन के काम में गए और शिवप्रकाशन दक्षिणी रेलवे के लिए खानपान ठेकेदार बने।',vocabulary:[['profession','पेशा'],['pilgrim','तीर्थयात्री'],['transport','परिवहन'],['catering contractor','खानपान ठेकेदार'],['career','व्यवसायिक जीवन']],exam:'These adult professions are a common short-answer fact.',think:'How does the chapter show that friendship can continue despite different careers?'},
    {title:'Part 15 — Moving toward higher studies and a larger world',flow:'Kalam eventually moved beyond Rameswaram for higher education. Looking back, he connects those early experiences with the values that prepared him for a wider life: discipline, kindness, curiosity, equality and communal harmony.',explanation:'बाद में उच्च शिक्षा के लिए कलाम रामेश्वरम् से आगे बढ़े। पीछे मुड़कर देखने पर वे समझते हैं कि बचपन के अनुभवों ने अनुशासन, दयालुता, जिज्ञासा, समानता और सांप्रदायिक सद्भाव जैसे मूल्यों को मजबूत किया।',vocabulary:[['higher studies','उच्च शिक्षा'],['curiosity','जिज्ञासा'],['equality','समानता'],['harmony','सद्भाव'],['formative','निर्माणकारी']],exam:'The concluding idea is that childhood experiences can shape a person’s values and later life.',think:'Which experiences in the chapter most clearly prepare Kalam for the life he later describes?'},
  ],
  wordStudy:{title:'WORD STUDY',items:[['rebel','विद्रोह करना / विद्रोही'],['marriage','विवाह'],['pilgrim','तीर्थयात्री'],['temple','मंदिर'],['allied','मित्र राष्ट्रों से संबंधित'],['wages','मजदूरी'],['business','व्यवसाय'],['religious','धार्मिक'],['prejudice','पूर्वाग्रह'],['harmony','सद्भाव']]},
  grammar:{title:'GRAMMAR / LANGUAGE LAB — Synthesis & Conjunctions',intro:'Sentence synthesis joins ideas without changing their essential meaning. This chapter is especially useful for practising conjunctions and recognizing Simple, Compound and Complex sentences.',points:[['Coordinating conjunctions','and, but, or, so, yet can join independent clauses.'],['Subordinating conjunctions','because, although, when, while, if and since introduce dependent clauses.'],['Correlative conjunctions','either…or, neither…nor, both…and, not only…but also work in pairs.'],['Simple sentence','one independent clause.'],['Compound sentence','two independent clauses joined by a coordinating conjunction.'],['Complex sentence','one independent clause plus at least one dependent clause.'],['Clause identification','A clause has a subject and a verb; its function in the sentence matters.']]},
  examPrep:{title:'EXAM BOOSTER',veryShort:[['Who were Kalam’s parents?','Jainulabdeen and Ashiamma.'],['When did the Second World War break out?','In 1939.'],['Who were Kalam’s three close friends?','Ramanadha Sastry, Aravindan and Sivaprakasan.'],['Who was Lakshmana Sastry?','The high priest of the Rameswaram temple.'],['Who was Samsuddin?','Kalam’s cousin who distributed newspapers in Rameswaram.']],short:[['Describe the qualities Kalam inherited from his parents.','He associates his father with honesty and self-discipline and his mother with faith in goodness and deep kindness.'],['How did Kalam earn his first wages?','He helped his cousin Samsuddin catch newspaper bundles thrown from a moving train and was paid for the work.'],['How did the new teacher discriminate against Kalam?','He made Kalam leave the front row beside Ramanadha Sastry and move to the backbench because of religious prejudice.'],['How was the teacher challenged?','Lakshmana Sastry demanded that the teacher apologise or leave rather than spread social inequality and communal intolerance.']],long:[['How does My Childhood present communal harmony?','The chapter combines Kalam’s friendship with Hindu Brahmin boys, shared local traditions, the Shri Sita Rama Kalyanam ceremony, and teachers who challenged prejudice. Together these experiences show that social and religious differences need not divide people.'],['Explain the role of teachers in Kalam’s childhood.','One teacher created a painful experience of discrimination, while Lakshmana Sastry and Sivasubramania Iyer challenged that prejudice. Their contrasting actions helped Kalam understand equality, dignity and social responsibility.']],discussion:['Can a child’s school experience change their understanding of society? Discuss using the chapter.','How are family values, friendship and education connected in Kalam’s childhood?'],},
  composition:{title:'WRITING / COMPOSITION',prompts:['Write a short paragraph on “The values I learned from my family.”','Write about an incident in which friendship helped overcome a difference.','Describe why equality and religious harmony are important in a school.']},
  translationPractice:['कलाम ने अपने माता-पिता से अच्छे गुण सीखे।','द्वितीय विश्व युद्ध 1939 में शुरू हुआ।','सम्सुद्दीन समाचार-पत्र बाँटता था।','रमानाध शास्त्री कलाम का घनिष्ठ मित्र था।','शिक्षक ने कलाम को पीछे की बेंच पर बैठने को कहा।','लक्ष्मण शास्त्री ने भेदभाव का विरोध किया।','अय्यर ने कलाम को अपने घर भोजन के लिए बुलाया।','पहली मजदूरी पाकर कलाम को बहुत गर्व हुआ।','सच्ची मित्रता धार्मिक भेदभाव से ऊपर होती है।','बचपन के अनुभव हमारे जीवन को प्रभावित कर सकते हैं।'],
  activities:[{title:'Timeline activity',instruction:'Make a timeline with: 1939 war → tamarind seeds → newspaper bundles → fifth-standard discrimination → Lakshmana Sastry’s intervention → Iyer’s dinner invitation → higher studies.'},{title:'Character comparison',instruction:'Compare the new teacher, Lakshmana Sastry and Sivasubramania Iyer. Identify the social attitude represented by each.'},{title:'Reflection',instruction:'Write three ways a classroom can ensure that students are treated equally.'}],
};

const practice=[
{q:'Who were Abdul Kalam’s parents?',o:['Jainulabdeen and Ashiamma','Samsuddin and Ashiamma','Lakshmana Sastry and Ashiamma','Jalaluddin and Sivaprakasan'],a:0,e:'Kalam names his father as Jainulabdeen and his mother as Ashiamma.'},
{q:'Where was Kalam’s ancestral house located?',o:['Mosque Street, Rameswaram','Temple Road, Madurai','Railway Road, Chennai','Rama Tirtha Road, Delhi'],a:0,e:'The ancestral house stood on Mosque Street in Rameswaram.'},
{q:'When did the Second World War break out?',o:['1939','1942','1945','1947'],a:0,e:'The chapter states that the war broke out in 1939, when Kalam was eight.'},
{q:'Which quality did Kalam associate with his father?',o:['Self-discipline','Fame','Ambition for wealth','Fear of change'],a:0,e:'Kalam says he inherited honesty and self-discipline from his father.'},
{q:'Who were Kalam’s three close friends?',o:['Ramanadha Sastry, Aravindan and Sivaprakasan','Samsuddin, Jalaluddin and Aravindan','Lakshmana Sastry, Samsuddin and Iyer','Ramanadha, Bismillah Khan and Sivaprakasan'],a:0,e:'These three boys were his close childhood friends.'},
{q:'What did Kalam’s family arrange during Shri Sita Rama Kalyanam?',o:['Boats with a special platform for carrying idols','A railway service for pilgrims','A school examination','A newspaper shop'],a:0,e:'His family arranged boats with a special platform to carry temple idols to the marriage site.'},
{q:'What did Kalam collect and sell as a child when demand suddenly rose?',o:['Tamarind seeds','Newspapers','Silver ornaments','Flutes'],a:0,e:'He collected tamarind seeds and sold them to a provision shop.'},
{q:'Who helped Kalam earn his first wages?',o:['His cousin Samsuddin','His friend Aravindan','His science teacher','Lakshmana Sastry'],a:0,e:'Samsuddin distributed newspapers and needed help catching bundles thrown from the moving train.'},
{q:'Why was Kalam moved to the backbench by the new teacher?',o:['Religious prejudice','Poor marks','Late attendance','Lack of books'],a:0,e:'The teacher objected to Kalam sitting beside the son of a Hindu priest because of religious prejudice.'},
{q:'Who was Ramanadha Sastry’s father?',o:['Pakshi Lakshmana Sastry','Jainulabdeen','Samsuddin','Sivasubramania Iyer'],a:0,e:'Pakshi Lakshmana Sastry was the high priest of the Rameswaram temple.'},
{q:'What did Ramanadha do when Kalam was sent to the last row?',o:['He wept and became deeply upset','He laughed','He left the school immediately','He ignored the event'],a:0,e:'Ramanadha’s grief and tears left a lasting impression on Kalam.'},
{q:'What did Lakshmana Sastry demand from the new teacher?',o:['An apology or that the teacher leave','A new textbook','A transfer to another class','A prize for Kalam'],a:0,e:'He rejected social inequality and communal intolerance and demanded an apology or departure.'},
{q:'Which teacher invited Kalam home for a meal?',o:['Sivasubramania Iyer','Ramanadha Sastry','Samsuddin','The new fifth-standard teacher'],a:0,e:'The science teacher Sivasubramania Iyer deliberately challenged social barriers.'},
{q:'What did Iyer’s wife initially do?',o:['She objected to serving Kalam','She sent Kalam to school','She invited Ramanadha instead','She gave Kalam a newspaper job'],a:0,e:'She initially objected, but her attitude changed later.'},
{q:'What central value connects the childhood incidents?',o:['Equality and communal harmony','Competition between friends','Luxury and wealth','Avoiding education'],a:0,e:'The experiences repeatedly highlight dignity, equality, friendship and harmony.'},
];

const challenge=[
{q:'Why is Kalam’s first wage more than a money-related detail in the lesson?',o:['It marks an early experience of responsibility and pride','It proves that he wanted to become a businessman','It shows that school was unnecessary','It explains why he disliked newspapers'],a:0,e:'The first wage becomes memorable because it connects effort, responsibility and personal pride.'},
{q:'What is the strongest contrast between Kalam’s home life and the new teacher’s classroom action?',o:['His home normalized shared traditions, while the teacher imposed religious separation','His home was wealthy, while the teacher was poor','His home rejected education, while the teacher encouraged it','His home was urban, while the teacher was rural'],a:0,e:'Kalam’s home included stories and community traditions from different faiths, whereas the teacher imposed division.'},
{q:'Why does Ramanadha’s reaction matter for the chapter’s theme?',o:['It shows that the discrimination harmed friendship as well as Kalam','It proves Ramanadha wanted to change schools','It shows that Ramanadha feared teachers','It explains why Kalam stopped studying'],a:0,e:'His tears make clear that prejudice affects relationships, not just the targeted student.'},
{q:'What makes Lakshmana Sastry’s response especially powerful?',o:['He uses social authority to defend equality and reject intolerance','He punishes Kalam for breaking a rule','He asks the boys to stop being friends','He ignores the teacher'],a:0,e:'As the temple’s high priest and a parent, he directly challenges the teacher’s prejudice.'},
{q:'Why is Sivasubramania Iyer’s dinner invitation a turning point?',o:['It turns a stated belief in equality into a practical social experiment','It gives Kalam a scholarship','It ends the Second World War','It changes the boys’ professions'],a:0,e:'Iyer tests whether everyday contact can break a social barrier.'},
{q:'What does the change in Iyer’s wife suggest?',o:['Attitudes may change through experience and example','Social prejudice is permanent','Children cannot influence adults','Teachers should avoid family life'],a:0,e:'Her later willingness to serve Kalam shows that attitudes are capable of change.'},
{q:'Which event best demonstrates that local life was connected to the wider world?',o:['The effect of the Second World War on the newspaper system','The ancestral house being old','Ramanadha becoming a priest','The family telling stories'],a:0,e:'The war changed railway and newspaper arrangements even in distant Rameswaram.'},
{q:'How are Kalam’s three friends an example of social diversity without social division?',o:['They came from different religious backgrounds but maintained close friendship','They all followed the same profession','They studied in different countries','They refused to discuss religion'],a:0,e:'Their friendship crossed religious background without erasing their individual identities.'},
{q:'Why does the author include the professions of his childhood friends?',o:['To show that friendship continued while their adult paths differed','To prove one friend was more successful','To explain why they left Rameswaram together','To compare their salaries'],a:0,e:'The different careers emphasize continuity of friendship alongside different life choices.'},
{q:'Which sequence best captures the lesson’s movement?',o:['Family values → friendship → prejudice → resistance → broader harmony','War → wealth → competition → isolation → failure','School marks → punishment → transfer → fame → wealth','Travel → music → food → shopping → homecoming'],a:0,e:'The chapter develops from family formation to social conflict and then toward equality and harmony.'},
{q:'If the new teacher had treated Kalam and Ramanadha equally, which theme would still remain central?',o:['The value of family, friendship and shared community life','The importance of railway timetables','The value of collecting tamarind seeds only','The superiority of one religion'],a:0,e:'The chapter contains broader themes beyond the discrimination episode, especially family values and harmony.'},
{q:'Why is the chapter autobiographical rather than merely instructional?',o:['Kalam explains ideas through remembered personal incidents','It gives only dictionary definitions','It presents a fictional kingdom','It is written as a newspaper report'],a:0,e:'The author uses his own childhood memories as evidence for the values he discusses.'},
{q:'What does the chapter suggest about the role of education?',o:['Education can either reproduce prejudice or challenge it, depending on the teacher','Education has no relation to social attitudes','Education only provides jobs','Education prevents friendship'],a:0,e:'The contrasting teachers show two possible effects of education on social attitudes.'},
{q:'Why are the stories from the Ramayana and the Prophet’s life significant?',o:['They show that multiple traditions were part of Kalam’s early moral world','They prove Kalam wanted to become a priest','They explain his newspaper work','They describe the Second World War'],a:0,e:'The stories show a childhood where different traditions could coexist within family life.'},
{q:'What is the best interpretation of Kalam’s “secure childhood”?',o:['He had necessities, emotional support and stable family values even without luxury','He lived in material luxury','He never faced any difficulty','He was isolated from society'],a:0,e:'Security in the chapter is material enough for needs and, importantly, emotional and moral.'},
{q:'Why does the teacher’s discriminatory act leave a lasting memory?',o:['It exposes how an adult can suddenly turn a normal friendship into an unequal social relationship','It gave Kalam his first wages','It ended his friendship with Ramanadha','It caused the war to begin'],a:0,e:'The incident was a sharp break from the inclusive relationships of his childhood.'},
{q:'Which response best fits the lesson’s model of constructive social change?',o:['Challenge prejudice firmly while preserving dignity and relationship','Ignore discrimination completely','Repay unfairness with unfairness','Separate all communities permanently'],a:0,e:'Lakshmana Sastry and Iyer model direct but constructive resistance to prejudice.'},
{q:'What is the most important link between the family and teachers in Kalam’s development?',o:['Both can shape values, but their influence depends on the example they set','Both only affected his marks','Neither affected his adult life','Only teachers mattered'],a:0,e:'The chapter shows family values and contrasting teacher examples shaping the young Kalam.'},
{q:'Which detail best shows Kalam’s growing independence?',o:['Earning his own wages through work during the newspaper distribution period','Hearing bedtime stories','Living in an ancestral house','Having three close friends'],a:0,e:'The newspaper job gives him direct responsibility and the pride of earning.'},
{q:'What broader lesson can be inferred from the contrast between the two teachers?',o:['Institutions become more humane when authority is used to protect inclusion rather than exclusion','All teachers are biased','Children cannot change society','School rules are always harmful'],a:0,e:'Authority can reinforce prejudice or defend dignity; the chapter highlights the latter as constructive.'},
{q:'Why does the chapter end by connecting childhood with later growth?',o:['It frames childhood experiences as formative influences on character and life direction','It suggests childhood should be forgotten','It proves adult careers are determined by religion','It returns to the newspaper story only'],a:0,e:'The memoir looks backward to explain how early values contributed to later development.'},
{q:'Which statement best distinguishes prejudice from ordinary disagreement in the chapter?',o:['Prejudice judges a person through a social label rather than individual character','Prejudice means having different hobbies','Disagreement always causes violence','Prejudice is simply a school rule'],a:0,e:'The teacher’s decision was based on religious identity rather than the children’s actual behavior.'},
{q:'What makes the chapter suitable for studying conjunctions and synthesis?',o:['Its incidents naturally contain cause, contrast, time and consequence relationships','It contains only dialogue','It avoids complex sentences','It uses no connecting ideas'],a:0,e:'The narrative includes clear relationships such as when, because, although, and so, which are useful for synthesis practice.'},
{q:'Which comparison is most accurate?',o:['Lakshmana Sastry confronted prejudice publicly, while Iyer challenged it through personal example','Both teachers separated Kalam from friends','Iyer demanded the teacher leave the school','Lakshmana Sastry refused community cooperation'],a:0,e:'The two adults oppose discrimination in different but complementary ways.'},
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function StudySection({data}){return <section className="pg-study-section"><h3>{data.title}</h3>{data.flow&&<p>{data.flow}</p>}{data.explanation&&<div className="pg-explain"><strong>हिंदी में समझें</strong><p>{data.explanation}</p></div>}{data.vocabulary&&<div className="pg-vocab"><strong>Vocabulary</strong><div>{data.vocabulary.map(([a,b])=><span key={a}><b>{a}</b> — {b}</span>)}</div></div>}{data.exam&&<div className="pg-exam"><strong>Exam Point</strong><p>{data.exam}</p></div>}{data.think&&<div className="pg-think"><strong>Think</strong><p>{data.think}</p></div>}</section>}

export function EnglishPanoramaChapter8Final({initialMode='learn',onBack,addXp,finishSession}){
  const [mode,setMode]=useState(initialMode);
  const [showQuiz,setShowQuiz]=useState(initialMode!=='learn');
  const setStage=m=>{setMode(m);setShowQuiz(m!=='learn')};
  const bank=mode==='practice'?practice:mode==='challenge'?challenge:finalTest;
  return <div className="pg-shell"><div className="pg-wrap">
    <button className="pg-back" onClick={onBack}>← Back to English</button>
    <header className="pg-hero"><span>THE PANORAMA • PROSE 8</span><h1>{study.title}</h1><p>by {study.author}</p><small>{study.sourceNote}</small></header>
    <div className="pg-stage-grid">
      {['learn','practice','challenge','test'].map(m=><button key={m} className={`pg-stage-card ${mode===m?'active':''}`} onClick={()=>setStage(m)}><strong>{m==='learn'?'Learn':m==='practice'?'Practice':m==='challenge'?'Challenge':'Final Test'}</strong><small>{m==='learn'?'Guided study':m==='practice'?'15 questions • 11:15':m==='challenge'?'23 questions • 23:00':'20 questions • 25:00'}</small></button>)}
    </div>
    {showQuiz?<PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>setShowQuiz(false)} addXp={addXp} finishSession={finishSession}/>:<>
      <section className="pg-about"><div><span>ABOUT THE CHAPTER</span><h2>{study.title}</h2><p>{study.intro}</p><p>{study.authorNote}</p></div><div className="pg-about-facts"><b>Chapter 8</b><span>Autobiographical prose</span><span>Hindi-medium support</span><span>Learn + Timed Assessments</span></div></section>
      <section className="pg-study-section"><h3>GUIDED READING</h3><div className="pg-study-grid">{study.sections.map(s=><StudySection key={s.title} data={s}/>)}</div></section>
      <section className="pg-study-section"><h3>{study.wordStudy.title}</h3><div className="pg-vocab pg-vocab-wide">{study.wordStudy.items.map(([a,b])=><span key={a}><b>{a}</b> — {b}</span>)}</div></section>
      <section className="pg-study-section"><h3>{study.grammar.title}</h3><p>{study.grammar.intro}</p>{study.grammar.points.map(([a,b])=><div className="pg-language-point" key={a}><b>{a}</b><span>{b}</span></div>)}</section>
      <section className="pg-study-section"><h3>{study.examPrep.title}</h3><h4>Very Short Answer</h4>{study.examPrep.veryShort.map(([q,a])=><div className="pg-qna" key={q}><b>{q}</b><p>{a}</p></div>)}<h4>Short Answer</h4>{study.examPrep.short.map(([q,a])=><div className="pg-qna" key={q}><b>{q}</b><p>{a}</p></div>)}<h4>Long Answer</h4>{study.examPrep.long.map(([q,a])=><div className="pg-qna" key={q}><b>{q}</b><p>{a}</p></div>)}<h4>Discussion</h4>{study.examPrep.discussion.map(q=><div className="pg-qna" key={q}><b>{q}</b></div>)}</section>
      <section className="pg-study-section"><h3>{study.composition.title}</h3>{study.composition.prompts.map(p=><div className="pg-activity" key={p}><b>{p}</b><p>Plan your response with a clear opening, specific chapter connection, and short conclusion.</p></div>)}</section>
      <section className="pg-study-section"><h3>TRANSLATION PRACTICE</h3><div className="pg-language-list">{study.translationPractice.map((x,i)=><span key={i}>{i+1}. {x}</span>)}</div></section>
      <section className="pg-study-section"><h3>ACTIVITIES</h3>{study.activities.map(a=><div className="pg-activity" key={a.title}><b>{a.title}</b><p>{a.instruction}</p></div>)}</section>
      <section className="pg-study-section"><h3>QUICK REVISION</h3><div className="pg-revision"><span>Parents → Jainulabdeen + Ashiamma</span><span>Friends → Ramanadha Sastry + Aravindan + Sivaprakasan</span><span>War → 1939, age eight</span><span>First wages → newspaper bundles with Samsuddin</span><span>Discrimination → fifth-standard teacher</span><span>Resistance → Lakshmana Sastry + Sivasubramania Iyer</span><span>Core theme → equality, dignity and communal harmony</span></div></section>
      <div className="pg-mode-cta"><button onClick={()=>setStage('practice')}>Start Practice →</button><button onClick={()=>setStage('challenge')}>Take Challenge →</button><button onClick={()=>setStage('test')}>Final Test →</button></div>
    </>}
  </div></div>;
}

export default EnglishPanoramaChapter8Final;
