import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
 title:'My Childhood',author:'A. P. J. Abdul Kalam',sourceNote:'Class 9 English • The Panorama • Prose Chapter 8',
 intro:'An autobiographical account of Abdul Kalam’s childhood in Rameswaram. It connects family values, interfaith friendship, early work, school experiences and the importance of equality and social harmony.',
 sections:[
 {title:'Part 1 — Rameswaram and family life',flow:'Kalam begins with childhood memories of Rameswaram. He grew up with his parents, brothers and sister in a modest but secure home. His ancestral house had been built in the middle of the nineteenth century.',explanation:'कलाम रामेश्वरम् में अपने बचपन और पारिवारिक जीवन को याद करते हैं। वे माता-पिता, भाई-बहनों के साथ एक साधारण लेकिन सुरक्षित वातावरण में पले-बढ़े। उनका पुश्तैनी घर उन्नीसवीं शताब्दी के मध्य में बना था।',vocabulary:[['ancestral','पुश्तैनी'],['secure','सुरक्षित'],['modest','सादा'],['siblings','भाई-बहन'],['childhood','बचपन']],exam:'Setting: Rameswaram; the ancestral house; a simple but secure childhood.',think:'What can a secure family environment give a child besides material comfort?'},
 {title:'Part 2 — Jainulabdeen and Ashiamma',flow:'Kalam describes his father Jainulabdeen as wise and generous and his mother Ashiamma as caring and kind. He links his own character to these parental qualities.',explanation:'कलाम अपने पिता जैनुलाब्दीन को बुद्धिमान और उदार तथा माता आशिअम्मा को स्नेही और दयालु बताते हैं। वे अपने चरित्र को माता-पिता से मिले गुणों से जोड़ते हैं।',vocabulary:[['wisdom','बुद्धिमत्ता'],['generous','उदार'],['honesty','ईमानदारी'],['self-discipline','आत्म-अनुशासन'],['kindness','दयालुता']],exam:'From his father: honesty and self-discipline. From his mother: faith in goodness and deep kindness.',think:'Why does Kalam treat character as something learned from example?'},
 {title:'Part 3 — A childhood without religious barriers',flow:'Kalam’s mother and grandmother told children stories from the Ramayana as well as stories connected with the life of the Prophet. Local religious life was part of a shared community setting.',explanation:'कलाम की माता और दादी रामायण तथा पैगंबर के जीवन से जुड़ी कथाएँ सुनाती थीं। इस प्रकार अलग-अलग धार्मिक परंपराएँ उनके बचपन के साझा परिवेश का हिस्सा थीं।',vocabulary:[['tradition','परंपरा'],['religious','धार्मिक'],['barrier','बाधा'],['shared','साझा'],['harmony','सद्भाव']],exam:'The lesson uses childhood stories and community practices to illustrate coexistence.',think:'How can stories shape a child’s attitude toward people from another tradition?'},
 {title:'Part 4 — Three close friends',flow:'Kalam’s closest childhood friends were Ramanadha Sastry, Aravindan and Sivaprakasan. They came from orthodox Hindu Brahmin families, yet their friendship was not divided by religion.',explanation:'कलाम के तीन घनिष्ठ मित्र रमानाध शास्त्री, अरविंदन और शिवप्रकाशन थे। वे रूढ़िवादी हिंदू ब्राह्मण परिवारों से थे, लेकिन धर्म के कारण उनकी मित्रता में कोई दूरी नहीं थी।',vocabulary:[['orthodox','रूढ़िवादी'],['friendship','मित्रता'],['upbringing','पालन-पोषण'],['difference','भिन्नता'],['community','समुदाय']],exam:'Memorise all three names and the point that religious difference did not divide the boys.',think:'What makes a friendship stronger than a social label?'},
 {title:'Part 5 — Shri Sita Rama Kalyanam',flow:'During the annual Shri Sita Rama Kalyanam ceremony, Kalam’s family arranged boats with a special platform to carry temple idols to the marriage site in Rama Tirtha.',explanation:'श्री सीता राम कल्याणम् समारोह में कलाम का परिवार विशेष मंच वाली नावों की व्यवस्था करता था, जिनसे मंदिर की मूर्तियों को राम तीर्थ स्थित विवाह-स्थल तक ले जाया जाता था।',vocabulary:[['ceremony','समारोह'],['idol','मूर्ति'],['platform','मंच'],['pond','तालाब'],['marriage site','विवाह-स्थल']],exam:'This detail shows practical cooperation across the local community.',think:'Why is this ceremony important to the chapter’s message of social harmony?'},
 {title:'Part 6 — The Second World War begins',flow:'The Second World War broke out in 1939, when Kalam was eight years old. Rameswaram was initially relatively untouched by the distant war, but later wartime measures changed everyday life.',explanation:'द्वितीय विश्व युद्ध 1939 में शुरू हुआ, जब कलाम आठ वर्ष के थे। प्रारंभ में रामेश्वरम् पर उसका प्रभाव कम था, लेकिन बाद में युद्धकालीन परिस्थितियों ने दैनिक जीवन को प्रभावित किया।',vocabulary:[['outbreak','आरंभ'],['wartime','युद्धकालीन'],['emergency','आपात स्थिति'],['impact','प्रभाव'],['distant','दूरस्थ']],exam:'Key fact: 1939; Kalam was eight.',think:'How can a world event slowly change life in a small town?'},
 {title:'Part 7 — Tamarind seeds and early earnings',flow:'A sudden demand for tamarind seeds gave Kalam a small earning opportunity. He collected the seeds and sold them to a provision shop, learning early that effort could produce his own income.',explanation:'इमली के बीजों की अचानक बढ़ी माँग से कलाम को छोटी-सी कमाई का अवसर मिला। वे बीज इकट्ठा कर किराने की दुकान में बेचते थे। इससे उन्होंने अपने श्रम से कमाने का अनुभव प्राप्त किया।',vocabulary:[['demand','माँग'],['collect','इकट्ठा करना'],['provision shop','किराने की दुकान'],['earning','कमाई'],['effort','प्रयास']],exam:'Keep this separate from the later newspaper job: both involve work, but the circumstances differ.',think:'What does a first earning teach about effort and independence?'},
 {title:'Part 8 — Newspapers and first wages',flow:'When the train’s halt at Rameswaram was suspended, newspaper bundles had to be thrown from the moving train. Kalam’s cousin Samsuddin, who distributed newspapers, needed help catching them. Kalam joined him and earned his first wages.',explanation:'जब रामेश्वरम् में ट्रेन का ठहराव बंद हुआ तो अखबारों के बंडल चलती ट्रेन से फेंके जाने लगे। अखबार बाँटने वाले चचेरे भाई सम्सुद्दीन को मदद की जरूरत थी। कलाम ने बंडल पकड़ने का काम किया और पहली मजदूरी कमाई।',vocabulary:[['bundle','बंडल'],['distribute','बाँटना'],['halt','ठहराव'],['wages','मजदूरी'],['pride','गौरव']],exam:'Sequence: suspended train halt → moving newspaper bundles → Samsuddin → Kalam’s first wages.',think:'Why did earning his own wages make such a strong impression on him?'},
 {title:'Part 9 — The new teacher’s prejudice',flow:'In fifth standard, Kalam sat in the front row beside Ramanadha Sastry, who wore the sacred thread. A new teacher objected to a Muslim boy sitting beside a Hindu priest’s son and ordered Kalam to the backbench.',explanation:'पाँचवीं कक्षा में कलाम रमानाध शास्त्री के साथ आगे की पंक्ति में बैठते थे। नए शिक्षक ने धार्मिक पूर्वाग्रह के कारण कलाम को पीछे की बेंच पर भेज दिया।',vocabulary:[['prejudice','पूर्वाग्रह'],['discrimination','भेदभाव'],['backbench','पीछली बेंच'],['sacred thread','जनेऊ'],['front row','आगे की पंक्ति']],exam:'This is the central discrimination incident of the chapter.',think:'Why is the teacher’s action harmful even though it changes only seating?'},
 {title:'Part 10 — Ramanadha’s response',flow:'Kalam felt deeply hurt, and Ramanadha Sastry became equally distressed. Ramanadha’s tears as Kalam moved to the last row remained a lasting memory for the author.',explanation:'कलाम बहुत दुखी हुए और रमानाध भी अत्यंत दुखी हुआ। कलाम के पीछे जाने पर रमानाध के आँसू लेखक की स्मृति में स्थायी रूप से रह गए।',vocabulary:[['distressed','व्यथित'],['downcast','बहुत उदास'],['lasting','स्थायी'],['memory','स्मृति'],['solidarity','एकजुटता']],exam:'Ramanadha’s tears demonstrate the human cost of prejudice.',think:'How do tears communicate solidarity without words?'},
 {title:'Part 11 — Lakshmana Sastry intervenes',flow:'Ramanadha’s father, Pakshi Lakshmana Sastry, was the high priest of the Rameswaram temple. He confronted the teacher and rejected social inequality and communal intolerance in front of the community.',explanation:'रमानाध के पिता पाक्षी लक्ष्मण शास्त्री रामेश्वरम् मंदिर के उच्च पुजारी थे। उन्होंने शिक्षक का सामना किया और सामाजिक असमानता तथा सांप्रदायिक असहिष्णुता का विरोध किया।',vocabulary:[['high priest','उच्च पुजारी'],['inequality','असमानता'],['intolerance','असहिष्णुता'],['confront','सामना करना'],['apology','क्षमा-याचना']],exam:'He demanded that the teacher apologise or leave rather than spread prejudice among children.',think:'How can responsible authority be used to protect fairness?'},
 {title:'Part 12 — Sivasubramania Iyer’s challenge',flow:'Kalam’s science teacher Sivasubramania Iyer also opposed rigid social barriers. He invited Kalam to his house for a meal, turning equality into a practical action.',explanation:'विज्ञान शिक्षक शिवसुब्रह्मण्यम अय्यर कठोर सामाजिक भेदभाव के विरुद्ध थे। उन्होंने कलाम को भोजन के लिए घर बुलाकर समानता की बात को व्यवहार में उतारा।',vocabulary:[['science teacher','विज्ञान शिक्षक'],['rigid','कठोर'],['social barrier','सामाजिक बाधा'],['invite','आमंत्रित करना'],['equality','समानता']],exam:'Iyer’s invitation is a major example of a teacher shaping social values.',think:'What is more powerful: teaching equality in words or practising it?'},
 {title:'Part 13 — The second meal',flow:'Iyer’s wife initially resisted the idea of serving Kalam. Iyer nevertheless served him and later persuaded her to reconsider. At the next meal, she served Kalam herself.',explanation:'अय्यर की पत्नी ने शुरू में कलाम को भोजन कराने का विरोध किया। अय्यर ने स्वयं भोजन कराया और बाद में उन्हें अपनी सोच पर पुनर्विचार करने के लिए प्रेरित किया। अगली बार उन्होंने स्वयं कलाम को भोजन परोसा।',vocabulary:[['resist','विरोध करना'],['reconsider','पुनर्विचार करना'],['attitude','दृष्टिकोण'],['persuade','समझाना'],['acceptance','स्वीकार्यता']],exam:'The two-meal sequence shows that attitudes can change through experience and example.',think:'Why can repeated contact change a social attitude?'},
 {title:'Part 14 — Adult lives of the friends',flow:'As they grew up, the three friends followed different occupations. Ramanadha took over the temple priesthood, Aravindan worked in transport for visiting pilgrims, and Sivaprakasan became a Southern Railways catering contractor.',explanation:'बड़े होने पर तीनों मित्र अलग-अलग पेशों में गए। रमानाध मंदिर के पुजारी बने, अरविंदन तीर्थयात्रियों के परिवहन के काम में गए और शिवप्रकाशन दक्षिणी रेलवे के खानपान ठेकेदार बने।',vocabulary:[['occupation','पेशा'],['pilgrim','तीर्थयात्री'],['transport','परिवहन'],['priesthood','पुजारी का पद'],['catering','खानपान सेवा']],exam:'These adult professions are a useful short-answer set.',think:'What does different career choice tell us about friendship?'},
 {title:'Part 15 — From childhood to a larger life',flow:'Kalam eventually moved beyond Rameswaram for higher studies. Looking back, he presents childhood as a formative period in which family values, friendships and teachers helped shape his sense of discipline, equality and communal harmony.',explanation:'बाद में उच्च शिक्षा के लिए कलाम रामेश्वरम् से आगे बढ़े। पीछे मुड़कर वे अपने बचपन को चरित्र-निर्माण का समय मानते हैं, जिसमें परिवार, मित्रता और शिक्षकों ने अनुशासन, समानता और सद्भाव की भावना विकसित की।',vocabulary:[['formative','निर्माणकारी'],['higher studies','उच्च शिक्षा'],['discipline','अनुशासन'],['equality','समानता'],['harmony','सद्भाव']],exam:'Central message: childhood experiences can shape values that guide later life.',think:'Which childhood influence seems strongest in the chapter: family, friendship or teachers?'},
 ],
 wordStudy:{title:'WORD STUDY',items:[['rebel','विद्रोह करना'],['marriage','विवाह'],['pilgrim','तीर्थयात्री'],['temple','मंदिर'],['allied','मित्र राष्ट्रों से संबंधित'],['wages','मजदूरी'],['business','व्यवसाय'],['prejudice','पूर्वाग्रह'],['harmony','सद्भाव']]},
 grammar:{title:'GRAMMAR / LANGUAGE LAB — Synthesis & Conjunctions',intro:'Practise joining ideas through coordinating, subordinating and correlative conjunctions. Also identify Simple, Compound and Complex sentences and their clauses.',points:[['and / but / or / so','Common coordinating conjunctions for joining equal ideas or showing contrast, choice or result.'],['because / although / when / while','Subordinating conjunctions that introduce dependent clauses and relationships such as cause, contrast and time.'],['either…or / neither…nor / both…and','Correlative conjunctions used in pairs.'],['Simple sentence','One independent clause.'],['Compound sentence','Two independent clauses joined by a coordinating conjunction.'],['Complex sentence','One independent clause plus at least one dependent clause.'],['Synthesis','Combine two or more short sentences while preserving the intended relationship and meaning.']]},
 examPrep:{veryShort:[['Who were Kalam’s parents?','Jainulabdeen and Ashiamma.'],['When did the Second World War break out?','1939.'],['Who were Kalam’s three close friends?','Ramanadha Sastry, Aravindan and Sivaprakasan.'],['Who was Samsuddin?','Kalam’s cousin who distributed newspapers.'],['Who was Lakshmana Sastry?','The high priest of the Rameswaram temple.']],short:[['What qualities did Kalam inherit from his parents?','Honesty and self-discipline from his father; faith in goodness and deep kindness from his mother.'],['How did Kalam earn his first wages?','He helped Samsuddin catch newspaper bundles thrown from a moving train.'],['What did the new teacher do?','He separated Kalam from Ramanadha Sastry and sent Kalam to the backbench because of religious prejudice.'],['How did Lakshmana Sastry respond?','He opposed social inequality and communal intolerance and demanded an apology or the teacher’s departure.']],long:[['How does the chapter teach communal harmony?','It presents shared community traditions, close friendship between boys of different religious backgrounds, and teachers who actively challenged prejudice.'],['Compare the contrasting teachers in Kalam’s childhood.','One teacher imposed discrimination, while Lakshmana Sastry and Sivasubramania Iyer acted against social prejudice in different ways.']],discussion:['How can schools help children learn equality in everyday life?','Which childhood experience in the chapter is most formative, and why?']},
 composition:['Write a paragraph on “Values I learned from my family.”','Describe an incident that shows friendship beyond social or religious differences.','Write a short note on the role of teachers in building an inclusive classroom.'],
 translationPractice:['कलाम का बचपन रामेश्वरम् में बीता।','उनके पिता बुद्धिमान और उदार थे।','उनकी माता दयालु और स्नेही थीं।','द्वितीय विश्व युद्ध 1939 में शुरू हुआ।','कलाम ने इमली के बीज बेचकर कमाई की।','सम्सुद्दीन अखबार बाँटते थे।','कलाम ने अपनी पहली मजदूरी कमाई।','नए शिक्षक ने कलाम को पीछे बैठने को कहा।','रमानाध शास्त्री कलाम के घनिष्ठ मित्र थे।','लक्ष्मण शास्त्री ने भेदभाव का विरोध किया।'],
 activities:[{title:'Timeline',instruction:'Arrange the key events from childhood, war, first wages, school discrimination, Lakshmana Sastry’s intervention and Iyer’s dinner invitation.'},{title:'Character study',instruction:'Compare the new teacher, Lakshmana Sastry and Sivasubramania Iyer in a three-column table.'},{title:'Classroom charter',instruction:'Write five practical rules for an equal and respectful classroom.'}]
};

const practice=[
{q:'Who were Abdul Kalam’s parents?',o:['Jainulabdeen and Ashiamma','Samsuddin and Ashiamma','Jalaluddin and Ramanadha','Iyer and Ashiamma'],a:0,e:'Kalam identifies Jainulabdeen as his father and Ashiamma as his mother.'},
{q:'Where was Kalam’s ancestral house?',o:['Mosque Street, Rameswaram','Railway Road, Madurai','Temple Road, Chennai','Rama Tirtha Road, Delhi'],a:0,e:'The ancestral house stood on Mosque Street in Rameswaram.'},
{q:'How old was Kalam when the Second World War broke out?',o:['Eight','Six','Ten','Twelve'],a:0,e:'The chapter states that the war began in 1939 when Kalam was eight.'},
{q:'Which quality did Kalam inherit from his father?',o:['Self-discipline','Fame','Luxury','Ambition for wealth'],a:0,e:'He associates his father with honesty and self-discipline.'},
{q:'Which quality did Kalam inherit from his mother?',o:['Deep kindness','Business skill','Military training','Public speaking'],a:0,e:'He says his mother gave him faith in goodness and deep kindness.'},
{q:'Who were Kalam’s three close friends?',o:['Ramanadha Sastry, Aravindan and Sivaprakasan','Samsuddin, Iyer and Ramanadha','Aravindan, Bismillah and Samsuddin','Jalaluddin, Aravindan and Iyer'],a:0,e:'These were Kalam’s three close childhood friends.'},
{q:'What did Kalam’s family arrange during Shri Sita Rama Kalyanam?',o:['Boats with a special platform for carrying idols','A railway ticket for every pilgrim','A school examination','A newspaper delivery route'],a:0,e:'The family arranged special boats for carrying the temple idols.'},
{q:'What did Kalam collect and sell during childhood?',o:['Tamarind seeds','Flutes','Silver jewellery','Railway tickets'],a:0,e:'He collected tamarind seeds and sold them to a provision shop.'},
{q:'Who distributed newspapers in Rameswaram?',o:['Samsuddin','Ramanadha Sastry','Lakshmana Sastry','Sivasubramania Iyer'],a:0,e:'Samsuddin was Kalam’s cousin and a newspaper distributor.'},
{q:'How did Kalam earn his first wages?',o:['By helping catch newspaper bundles from a moving train','By selling temple idols','By teaching younger children','By working in a railway kitchen'],a:0,e:'He helped Samsuddin catch newspaper bundles and earned wages.'},
{q:'Why was Kalam sent to the backbench?',o:['The new teacher was prejudiced about religion','He had failed a test','He was late to class','He had no textbook'],a:0,e:'The teacher objected to a Muslim boy sitting beside a Hindu priest’s son.'},
{q:'What was Ramanadha Sastry’s reaction?',o:['He became deeply upset and wept','He laughed at the change','He left the school immediately','He ignored Kalam'],a:0,e:'Ramanadha’s tears became a lasting memory for Kalam.'},
{q:'Who was the high priest of the Rameswaram temple?',o:['Pakshi Lakshmana Sastry','Samsuddin','Jainulabdeen','Sivasubramania Iyer'],a:0,e:'Lakshmana Sastry was the high priest and Ramanadha’s father.'},
{q:'Which teacher invited Kalam home for a meal?',o:['Sivasubramania Iyer','The new fifth-standard teacher','Samsuddin','Ramanadha Sastry'],a:0,e:'The science teacher Iyer invited Kalam home to challenge social barriers.'},
{q:'What is a central message of the chapter?',o:['Equality and communal harmony','Competition between religions','Luxury in childhood','Avoiding difficult questions'],a:0,e:'The memoir repeatedly emphasizes dignity, equality, friendship and harmony.'},
];

const challenge=[
{q:'Why is Kalam’s secure childhood important to his later reflection?',o:['It shows that stability and values can coexist without luxury','It proves he never faced difficulty','It shows he wanted to remain isolated','It explains his dislike of education'],a:0,e:'Kalam distinguishes emotional and moral security from material luxury.'},
{q:'What is the strongest contrast between Kalam’s family environment and the new teacher’s attitude?',o:['Family life allowed shared traditions while the teacher imposed religious separation','Family life rejected religion while the teacher promoted it','Family life was urban while the teacher was rural','Family life valued money while the teacher valued sport'],a:0,e:'The home environment normalized shared traditions; the teacher introduced prejudice.'},
{q:'Why does the Ramayana and Prophet-story detail matter?',o:['It shows that different traditions were part of Kalam’s early moral world','It explains the newspaper route','It proves Kalam wanted to become a priest','It describes the war'],a:0,e:'The detail supports the theme of coexistence and shared community life.'},
{q:'Why is Ramanadha’s weeping more significant than simple sadness?',o:['It demonstrates solidarity with a friend who was being discriminated against','It shows fear of the teacher’s punishment','It proves he wanted a different seat','It explains his later profession'],a:0,e:'His reaction shows that prejudice damages friendship and shared dignity.'},
{q:'What makes Lakshmana Sastry’s intervention effective?',o:['He directly rejects inequality and uses his authority to demand accountability','He avoids confronting the teacher','He separates the boys permanently','He asks Kalam to leave school'],a:0,e:'He uses moral and social authority to challenge communal intolerance.'},
{q:'Why does Iyer invite Kalam home?',o:['To turn the principle of equality into a practical action','To give Kalam a scholarship','To discuss newspaper prices','To prepare him for a railway job'],a:0,e:'The meal becomes a practical test of social prejudice.'},
{q:'What does the second meal at Iyer’s house suggest?',o:['Attitudes can change through experience and example','Prejudice is always permanent','Children cannot influence adults','Teachers should never question customs'],a:0,e:'The later meal shows a visible shift from resistance to acceptance.'},
{q:'How did the war indirectly create Kalam’s first-wage opportunity?',o:['It changed the train’s halt and the way newspapers were delivered','It closed all schools in Rameswaram','It created a new temple ceremony','It sent Kalam abroad'],a:0,e:'Wartime railway changes led to newspaper bundles being thrown from a moving train.'},
{q:'Why does Kalam mention his friends’ adult professions?',o:['To show that different careers did not erase childhood friendship','To rank the careers','To compare their incomes','To explain why they stopped studying'],a:0,e:'Their varied occupations show continuity of friendship despite different adult paths.'},
{q:'Which sequence best represents the chapter’s moral development?',o:['Family values → friendship → prejudice → resistance → harmony','Wealth → competition → war → travel → fame','School marks → punishment → transfer → failure → success','Food → shopping → music → travel → homecoming'],a:0,e:'The memoir moves from childhood values through conflict toward social equality.'},
{q:'What does the newspaper episode reveal about work?',o:['Small responsibilities can create pride, discipline and independence','Work is useful only when it pays a lot','Children should avoid responsibility','Newspapers were more important than school'],a:0,e:'Kalam remembers the pride of earning through useful work.'},
{q:'Why is the seating incident a social issue rather than a classroom-management issue?',o:['The seating decision is based on identity instead of behavior or merit','The seats were uncomfortable','The class had no teacher','The students arrived late'],a:0,e:'The teacher judged students through religious labels.'},
{q:'How do Lakshmana Sastry and Iyer challenge prejudice differently?',o:['One confronts it publicly while the other challenges it through personal example','Both punish Kalam','One separates the boys and the other ignores them','Both support the new teacher'],a:0,e:'Their methods differ, but both work against social discrimination.'},
{q:'Which statement best explains the chapter’s view of education?',o:['Education can reproduce prejudice or help dismantle it depending on conduct','Education has no connection to social values','Education is only about earning money','Education prevents friendship'],a:0,e:'The contrasting teachers show how education can shape social attitudes in opposite ways.'},
{q:'Why can childhood friendships cross religious boundaries in the lesson?',o:['The boys relate as people before social labels define them','They all secretly follow the same religion','Their families never met','The school prevented them from speaking'],a:0,e:'The friendship grows naturally before prejudice is imposed from outside.'},
{q:'What makes the first wages a formative memory?',o:['They are the first money Kalam remembers earning through his own effort','They were a gift from a teacher','They came from winning a prize','They were inherited from his parents'],a:0,e:'The pride comes from personal effort and responsibility.'},
{q:'What does Kalam’s description of his parents suggest about leadership?',o:['Personal character can grow from everyday examples at home','Leadership comes only from public position','Family has no influence on character','Leadership is mainly financial'],a:0,e:'The qualities he inherited become part of the ethical foundation of his life.'},
{q:'How is social harmony shown through action rather than slogans?',o:['Through shared ceremonies, friendship, intervention and a shared meal','Through posters alone','Through competitive examinations','Through avoiding all religious discussion'],a:0,e:'The chapter relies on concrete incidents rather than abstract claims alone.'},
{q:'Which idea best links the family and school episodes?',o:['Adults can either widen or reduce social barriers faced by children','Adults should never influence children','Families and schools teach exactly the same lessons','School life is unrelated to home life'],a:0,e:'The chapter compares the effects of family and teacher behavior on a child.'},
{q:'Why does the author look back on these incidents?',o:['To explain how early experiences shaped his values and identity','To list only historical dates','To prove every childhood event is pleasant','To avoid discussing later life'],a:0,e:'The memoir uses reflection to connect childhood experience with later character.'},
{q:'Which statement most clearly separates prejudice from ordinary difference?',o:['Prejudice assigns value or treatment based on a group label rather than individual character','Difference always means conflict','Prejudice is just another word for friendship','Ordinary difference is always unfair'],a:0,e:'The teacher’s decision rests on communal identity rather than conduct.'},
{q:'Why is the chapter useful for studying synthesis and conjunctions?',o:['Its events naturally show cause, time, contrast and result','It contains no connected ideas','It is only a list of names','It avoids dependent clauses'],a:0,e:'Narrative events provide many examples of joining ideas with meaningful relationships.'},
{q:'What is the broadest lesson of My Childhood?',o:['Personal dignity, equality and kindness can be learned through everyday experiences','Only professional success matters','Religious labels determine friendship','Childhood experiences have no lasting effect'],a:0,e:'Kalam presents childhood as formative for a life guided by ethical values.'},
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function StudyBlock({s}){return <article className="pg-study-section"><h3>{s.title}</h3><p>{s.flow}</p><div className="pg-explain"><strong>हिंदी में समझें</strong><p>{s.explanation}</p></div><div className="pg-vocab"><strong>Vocabulary</strong><div>{s.vocabulary.map(([a,b])=><span key={a}><b>{a}</b> — {b}</span>)}</div></div><div className="pg-exam"><strong>Exam Point</strong><p>{s.exam}</p></div><div className="pg-think"><strong>Think</strong><p>{s.think}</p></div></article>}

export function EnglishPanoramaChapter8({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode);const [quizOpen,setQuizOpen]=useState(initialMode!=='learn');
 const openMode=m=>{setMode(m);setQuizOpen(m!=='learn')};
 const bank=mode==='practice'?practice:mode==='challenge'?challenge:finalTest;
 return <div className="pg-shell"><div className="pg-wrap"><button className="pg-back" onClick={onBack}>← Back to English</button>
 <header className="pg-hero"><span>THE PANORAMA • PROSE 8</span><h1>{study.title}</h1><p>by {study.author}</p><small>{study.sourceNote}</small></header>
 <div className="pg-stage-grid">{[['learn','Learn','Guided study'],['practice','Practice','15 questions • 11:15'],['challenge','Challenge','23 questions • 23:00'],['test','Final Test','20 questions • 25:00']].map(([m,label,sub])=><button key={m} className={`pg-stage-card ${mode===m?'active':''}`} onClick={()=>openMode(m)}><strong>{label}</strong><small>{sub}</small></button>)}</div>
 {quizOpen?<PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>setQuizOpen(false)} addXp={addXp} finishSession={finishSession}/>:<>
 <section className="pg-about"><div><span>ABOUT THE CHAPTER</span><h2>{study.title}</h2><p>{study.intro}</p><p>This memoir presents family influence, religious harmony, social prejudice, responsible authority and the role of education through remembered childhood incidents.</p></div><div className="pg-about-facts"><b>Chapter 8</b><span>Autobiographical prose</span><span>Hindi explanations</span><span>Timed practice + tests</span></div></section>
 <section className="pg-study-section"><h3>GUIDED READING</h3><div className="pg-study-grid">{study.sections.map(s=><StudyBlock key={s.title} s={s}/>)}</div></section>
 <section className="pg-study-section"><h3>{study.wordStudy.title}</h3><div className="pg-vocab pg-vocab-wide">{study.wordStudy.items.map(([a,b])=><span key={a}><b>{a}</b> — {b}</span>)}</div></section>
 <section className="pg-study-section"><h3>{study.grammar.title}</h3><p>{study.grammar.intro}</p>{study.grammar.points.map(([a,b])=><div className="pg-language-point" key={a}><b>{a}</b><span>{b}</span></div>)}</section>
 <section className="pg-study-section"><h3>EXAM BOOSTER</h3>{['veryShort','short','long'].map(k=><div key={k}><h4>{k==='veryShort'?'Very Short Answer':k==='short'?'Short Answer':'Long Answer'}</h4>{study.examPrep[k].map(([q,a])=><div className="pg-qna" key={q}><b>{q}</b><p>{a}</p></div>)}</div>)}<h4>Discussion</h4>{study.examPrep.discussion.map(q=><div className="pg-qna" key={q}><b>{q}</b></div>)}</section>
 <section className="pg-study-section"><h3>WRITING / COMPOSITION</h3>{study.composition.map(x=><div className="pg-activity" key={x}><b>{x}</b><p>Use a clear introduction, chapter-based evidence, and a brief conclusion.</p></div>)}</section>
 <section className="pg-study-section"><h3>TRANSLATION PRACTICE</h3><div className="pg-language-list">{study.translationPractice.map((x,i)=><span key={i}>{i+1}. {x}</span>)}</div></section>
 <section className="pg-study-section"><h3>ACTIVITIES</h3>{study.activities.map(a=><div className="pg-activity" key={a.title}><b>{a.title}</b><p>{a.instruction}</p></div>)}</section>
 <section className="pg-study-section"><h3>QUICK REVISION</h3><div className="pg-revision"><span>Parents → Jainulabdeen + Ashiamma</span><span>Friends → Ramanadha Sastry + Aravindan + Sivaprakasan</span><span>1939 → World War II begins; Kalam was 8</span><span>First wages → newspaper bundles with Samsuddin</span><span>School discrimination → fifth-standard teacher</span><span>Resistance → Lakshmana Sastry + Sivasubramania Iyer</span><span>Core message → equality, dignity and communal harmony</span></div></section>
 <div className="pg-mode-cta"><button onClick={()=>openMode('practice')}>Start Practice →</button><button onClick={()=>openMode('challenge')}>Take Challenge →</button><button onClick={()=>openMode('test')}>Final Test →</button></div>
 </>}</div></div>;
}
export default EnglishPanoramaChapter8;
