import React,{useMemo,useState}from'react';
import './EnglishTensesTopic.css';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';

const LESSONS=[
 {id:'01',group:'FOUNDATION',title:'What is a tense?',meaning:'Tense tells us when an action happens. First ask: present, past or future? Then ask whether the action is a habit, happening now, completed, or continuing for a period.',structure:'Think in two layers: TIME + ACTION VIEW. Example: “I study” = present + habit. “I am studying” = present + action in progress.',examples:[['I go to school every day.','मैं रोज़ स्कूल जाता हूँ।'],['She is reading now.','वह अभी पढ़ रही है।'],['I finished my homework yesterday.','मैंने कल अपना गृहकार्य पूरा किया।'],['I have finished my homework.','मैं अपना गृहकार्य कर चुका हूँ।'],['I will finish my homework tomorrow.','मैं अपना गृहकार्य कल पूरा करूँगा।']],clue:'often • usually • every day • now • yesterday • already • tomorrow'},
 {id:'02',group:'PRESENT',title:'Simple Present',meaning:'Use it for habits, routines, facts, general truths and regular events.',structure:'Affirmative: S + V1(s/es) + O. Negative: S + do/does not + V1. Question: Do/Does + S + V1?',examples:[['She goes to school every day.','वह रोज़ स्कूल जाती है।'],['The sun rises in the east.','सूर्य पूर्व में उगता है।'],['I play cricket on Sundays.','मैं रविवार को क्रिकेट खेलता हूँ।'],['Water boils at 100°C.','पानी 100°C पर उबलता है।'],['He does not waste time.','वह समय बर्बाद नहीं करता है।']],clue:'every day • usually • always • often • sometimes'},
 {id:'03',group:'PRESENT',title:'Present Continuous',meaning:'Use it for an action happening now, around now, or a temporary situation.',structure:'Affirmative: S + am/is/are + V-ing. Negative: S + am/is/are not + V-ing. Question: Am/Is/Are + S + V-ing?',examples:[['She is reading now.','वह अभी पढ़ रही है।'],['I am writing a letter at the moment.','मैं इस समय एक पत्र लिख रहा हूँ।'],['They are playing football.','वे फुटबॉल खेल रहे हैं।'],['We are staying with our relatives this week.','हम इस सप्ताह अपने रिश्तेदारों के साथ रह रहे हैं।'],['Are you listening to me?','क्या तुम मेरी बात सुन रहे हो?']],clue:'now • at the moment • look! • currently • today'},
 {id:'04',group:'PRESENT',title:'Present Perfect',meaning:'Use it when a past action matters to the present, or when the time period is not finished.',structure:'Affirmative: S + has/have + V3. Negative: S + has/have not + V3. Question: Has/Have + S + V3?',examples:[['I have finished my homework.','मैं अपना गृहकार्य कर चुका हूँ।'],['She has just arrived.','वह अभी-अभी पहुँची है।'],['We have visited Delhi twice.','हम दिल्ली दो बार जा चुके हैं।'],['Have you ever seen the Taj Mahal?','क्या तुमने कभी ताजमहल देखा है?'],['He has not completed the project yet.','उसने अभी तक परियोजना पूरी नहीं की है।']],clue:'already • just • yet • ever • never • so far'},
 {id:'05',group:'PRESENT',title:'Present Perfect Continuous',meaning:'Use it when an activity has continued up to now and duration is important.',structure:'S + has/have been + V-ing + since/for. Since = starting point. For = duration.',examples:[['I have been studying for two hours.','मैं दो घंटे से पढ़ रहा हूँ।'],['She has been living here since 2022.','वह 2022 से यहाँ रह रही है।'],['They have been waiting for thirty minutes.','वे तीस मिनट से इंतज़ार कर रहे हैं।'],['It has been raining since morning.','सुबह से बारिश हो रही है।'],['How long have you been learning English?','तुम कितने समय से अंग्रेज़ी सीख रहे हो?']],clue:'since • for • all morning • how long'},
 {id:'06',group:'PAST',title:'Simple Past',meaning:'Use it for a completed event at a definite past time.',structure:'Affirmative: S + V2. Negative: S + did not + V1. Question: Did + S + V1?',examples:[['I visited Patna yesterday.','मैं कल पटना गया था।'],['She bought a new book last week.','उसने पिछले सप्ताह एक नई किताब खरीदी।'],['We watched the match on Sunday.','हमने रविवार को मैच देखा।'],['He did not attend the class.','वह कक्षा में उपस्थित नहीं हुआ।'],['Did you meet your friend yesterday?','क्या तुम कल अपने मित्र से मिले थे?']],clue:'yesterday • last week • ago • in 2024'},
 {id:'07',group:'PAST',title:'Past Continuous',meaning:'Use it for an action that was in progress at a past time, often interrupted by another event.',structure:'S + was/were + V-ing. Common frame: I was studying when he came.',examples:[['I was sleeping when you came.','जब तुम आए, मैं सो रहा था।'],['She was cooking at 8 p.m.','वह रात 8 बजे खाना बना रही थी।'],['They were playing when it started to rain.','जब बारिश शुरू हुई, वे खेल रहे थे।'],['While I was reading, my brother was watching TV.','जब मैं पढ़ रहा था, मेरा भाई टीवी देख रहा था।'],['Were you studying at that time?','क्या तुम उस समय पढ़ रहे थे?']],clue:'when • while • at that time • at 8 p.m.'},
 {id:'08',group:'PAST',title:'Past Perfect',meaning:'Use it to show which of two past actions happened earlier.',structure:'S + had + V3. Example frame: The train had left before we arrived.',examples:[['The train had left before we arrived.','हम पहुँचे तो ट्रेन जा चुकी थी।'],['She had finished the work before dinner.','रात के खाने से पहले उसने काम पूरा कर लिया था।'],['I had never seen snow before that trip.','उस यात्रा से पहले मैंने कभी बर्फ नहीं देखी थी।'],['They had gone home when I called.','जब मैंने फोन किया तब वे घर जा चुके थे।'],['Had you completed the assignment before the teacher asked?','क्या शिक्षक के पूछने से पहले तुमने असाइनमेंट पूरा कर लिया था?']],clue:'before • after • by the time • already'},
 {id:'09',group:'PAST',title:'Past Perfect Continuous',meaning:'Use it for an activity that continued for a period before another past reference point.',structure:'S + had been + V-ing + since/for.',examples:[['They had been waiting for an hour before the bus came.','बस आने से पहले वे एक घंटे से इंतज़ार कर रहे थे।'],['She had been studying for three hours when I called.','जब मैंने फोन किया तब वह तीन घंटे से पढ़ रही थी।'],['He had been working there since 2019 before he moved.','स्थान बदलने से पहले वह 2019 से वहाँ काम कर रहा था।'],['It had been raining for two hours before the match began.','मैच शुरू होने से पहले दो घंटे से बारिश हो रही थी।'],['How long had you been waiting before the train arrived?','ट्रेन आने से पहले तुम कितनी देर से इंतज़ार कर रहे थे?']],clue:'for • since • before • how long'},
 {id:'10',group:'FUTURE',title:'Future Simple',meaning:'Use will for predictions, promises, quick decisions and future facts.',structure:'S + will + V1. Negative: S + will not + V1. Question: Will + S + V1?',examples:[['I will help you.','मैं तुम्हारी मदद करूँगा।'],['I think it will rain tonight.','मुझे लगता है आज रात बारिश होगी।'],['I will call you tomorrow.','मैं तुम्हें कल फोन करूँगा।'],['Don’t worry; I will carry the bag.','चिंता मत करो; मैं बैग उठा दूँगा।'],['Will you join us next week?','क्या तुम अगले सप्ताह हमारे साथ शामिल होगे?']],clue:'tomorrow • next week • soon • I think • probably'},
 {id:'11',group:'FUTURE',title:'Other future meanings',meaning:'Future meaning is not limited to will. Be going to often marks a plan or evidence-based prediction; Present Continuous can mark a fixed arrangement; Simple Present can mark a timetable.',structure:'going to + V1 • am/is/are + V-ing (arrangement) • Simple Present (timetable)',examples:[['I am going to visit my grandmother this weekend.','मैं इस सप्ताहांत अपनी दादी से मिलने वाला हूँ।'],['Look at those clouds. It is going to rain.','उन बादलों को देखो। बारिश होने वाली है।'],['We are meeting the teacher tomorrow.','हम कल शिक्षक से मिल रहे हैं।'],['The train leaves at 6 a.m. tomorrow.','ट्रेन कल सुबह 6 बजे रवाना होती है।'],['She is flying to Delhi next Monday.','वह अगले सोमवार दिल्ली जा रही है।']],clue:'plan • evidence • arrangement • timetable'},
 {id:'12',group:'CONTROL',title:'Negative, questions and translation',meaning:'Build the sentence from the auxiliary. Then choose the correct verb form. This is the safest exam method for Hindi → English translation.',structure:'Step 1 Subject → Step 2 time/reference → Step 3 action type → Step 4 auxiliary → Step 5 V1/V2/V3/V-ing → Step 6 object/complement → Step 7 articles/prepositions → Step 8 final audit.',examples:[['वह रोज़ स्कूल नहीं जाती है। → She does not go to school every day.','Negative + Simple Present'],['क्या तुम कल गए थे? → Did you go yesterday?','Question + Simple Past'],['वह अभी नहीं पढ़ रही है। → She is not studying now.','Negative + Present Continuous'],['क्या तुमने काम पूरा कर लिया है? → Have you finished the work?','Question + Present Perfect'],['वे दो घंटे से इंतज़ार नहीं कर रहे हैं। → They have not been waiting for two hours.','Negative + Present Perfect Continuous']],clue:'auxiliary first • verb form second • check time clue'}
];

const QUESTIONS=[
 ['मैं रोज़ स्कूल जाता हूँ।',['I am going to school every day.','I went to school every day.','I have gone to school every day.','I go to school every day.'],3,'Routine → Simple Present.'],
 ['वह अभी खाना खा रही है।',['She ate food now.','She has eaten food now.','She is eating food now.','She eats food now.'],2,'Now + action in progress → Present Continuous.'],
 ['मैंने अपना काम कर लिया है।',['I am finish my work.','I have finished my work.','I finished my work yesterday.','I had finish my work.'],1,'Completed result linked to the present → Present Perfect.'],
 ['मैं दो घंटे से पढ़ रहा हूँ।',['I have been studying for two hours.','I studied for two hours.','I am studied for two hours.','I had study two hours.'],0,'Duration continuing to now → Present Perfect Continuous.'],
 ['मैंने उसे कल देखा।',['I have seen him yesterday.','I see him yesterday.','I was see him yesterday.','I saw him yesterday.'],3,'Finished definite past time → Simple Past.'],
 ['जब तुम आए, मैं पढ़ रहा था।',['I studied when you came.','I had study when you came.','I was studying when you came.','I am studying when you came.'],2,'Action in progress at a past moment → Past Continuous.'],
 ['हम पहुँचे तो ट्रेन जा चुकी थी।',['The train was left before we arrived.','The train had left before we arrived.','The train has left before we arrived.','The train left before we arrive.'],1,'Earlier of two past actions → Past Perfect.'],
 ['मैं तुम्हारी मदद करूँगा।',['I will help you.','I will helped you.','I will helping you.','I help you yesterday.'],0,'will takes V1.'],
 ['Which sentence is correct?',['She does not plays cricket.','She do not play cricket.','She did not plays cricket.','She does not play cricket.'],3,'After does not use the base verb.'],
 ['Which question is correct?',['Did you gone there?','Did you going there?','Did you go there?','Did you went there?'],2,'After did use V1.'],
 ['Since introduces a…',['timetable','starting point','duration','finished year'],1,'Since = starting point.'],
 ['For usually introduces a…',['duration','starting point','person','place'],0,'For = duration.'],
 ['Which is best for “every day”?',['Present Perfect Continuous','Past Perfect','Future Perfect','Simple Present'],3,'Every day commonly points to routine/habit.'],
 ['Which is best for “now”?',['Past Perfect','Future Simple','Present Continuous','Simple Past'],2,'Now commonly points to an action in progress.'],
 ['Which is best for “yesterday”?',['Future Simple','Simple Past','Present Perfect','Present Continuous'],1,'Yesterday is a definite finished past time.']
];

const ANSWERED_LABELS={practice:'PRACTICE',challenge:'CHALLENGE',test:'FINAL TEST'};

export default function EnglishTensesTopic({onBack,addXp=()=>{},finishSession=()=>{}}){
 const [section,setSection]=useState('learn');
 const [lesson,setLesson]=useState(0);
 const [question,setQuestion]=useState(0);
 const [selected,setSelected]=useState(null);
 const [score,setScore]=useState(0);
 const [done,setDone]=useState(false);
 const bank=useMemo(()=>section==='practice'?QUESTIONS:section==='challenge'?[...QUESTIONS.slice(3),...QUESTIONS.slice(0,3),...QUESTIONS.slice(7,12)]:QUESTIONS,[section]);
 const current=bank[question];
 const pick=i=>{if(selected!==null)return;setSelected(i);if(i===current[2])setScore(s=>s+1)};
 const next=()=>{if(question+1<bank.length){setQuestion(n=>n+1);setSelected(null);return}const final=score+(selected===current[2]?1:0);setDone(true);addXp(Math.max(5,final*2));finishSession({kind:'language-skills',topic:'tenses',mode:section,score:final,total:bank.length,at:Date.now()})};
 const startMode=m=>{setSection(m);setQuestion(0);setSelected(null);setScore(0);setDone(false);window.history.pushState({},'',`${window.location.pathname}?page=language-skills&subject=english&languageSkills=1&topic=tenses&mode=${m}`)};
 const openLesson=i=>{setSection('learn');setLesson(i);window.scrollTo({top:0,behavior:'smooth'})};
 if(section!=='learn')return <EnglishTimedQuiz title="Tenses" mode={section} getBank={m=>m==='practice'?QUESTIONS:m==='challenge'?[...QUESTIONS.slice(3),...QUESTIONS.slice(0,3),...QUESTIONS.slice(7,12)]:QUESTIONS} onModeChange={startMode} onBack={()=>setSection('learn')} addXp={addXp} finishSession={finishSession}/>;
 return <div className="tenses-hub">
   <header className="tenses-header"><button onClick={onBack}>← Language & Skills</button><span>ENGLISH • GRAMMAR • TENSES</span></header>
   <section className="tenses-hero"><div><span className="tenses-eyebrow">MASTER TENSES STEP BY STEP</span><h1>Tenses</h1><p>Build the meaning first, choose the time second, then choose the verb form. Learn each tense as a usable sentence pattern—not as a table to memorise.</p><div className="tenses-stats"><b>12</b><span>core lessons</span><b>5</b><span>examples / lesson</span><b>15</b><span>practice questions</span></div></div><div className="tenses-hero-card"><strong>TIME → ACTION</strong><span>Reference time</span><span>↓</span><span>Action type</span><span>↓</span><span>Verb structure</span></div></section>
   <nav className="tenses-modebar"><button className={section==='learn'?'active':''} onClick={()=>setSection('learn')}>Learn</button><button className={section==='practice'?'active':''} onClick={()=>startMode('practice')}>Practice</button><button className={section==='challenge'?'active':''} onClick={()=>startMode('challenge')}>Challenge</button><button className={section==='test'?'active':''} onClick={()=>startMode('test')}>Final Test</button></nav>
   {section==='learn'?<><div className="tenses-progress"><div><span>LEARNING PATH</span><strong>{lesson+1} / {LESSONS.length}</strong></div><div className="tenses-progress-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></div><main className="tenses-learning"><aside><span>LESSON MAP</span>{LESSONS.map((x,i)=><button key={x.id} className={lesson===i?'active':''} onClick={()=>openLesson(i)}><em>{x.id}</em><b>{x.title}</b><small>{x.group}</small></button>)}</aside><article className="tenses-lesson"><div className="tenses-lesson-top"><span>{LESSONS[lesson].group}</span><b>Lesson {LESSONS[lesson].id}</b></div><h2>{LESSONS[lesson].title}</h2><p className="tenses-meaning">{LESSONS[lesson].meaning}</p><section><span>STRUCTURE</span><p className="tenses-structure">{LESSONS[lesson].structure}</p></section><section className="tenses-example"><span>EXAMPLES</span>{LESSONS[lesson].examples.map((ex,i)=><div className="tenses-example-item" key={i}><strong>{i+1}. {ex[0]}</strong><b>{ex[1]}</b></div>)}</section><div className="tenses-clue"><span>CLUE WORDS / MEMORY HOOK</span><b>{LESSONS[lesson].clue}</b></div><div className="tenses-lesson-nav"><button disabled={lesson===0} onClick={()=>openLesson(lesson-1)}>← Previous</button><button onClick={()=>lesson===LESSONS.length-1?startMode('practice'):openLesson(lesson+1)}>{lesson===LESSONS.length-1?'Start Practice':'Next Lesson →'}</button></div></article></main></>:<main className="tenses-assessment"><div className="tenses-assessment-top"><div><span>{ANSWERED_LABELS[section]}</span><h2>{done?'Assessment complete':'Check your understanding'}</h2></div><strong>{done?score:`${question+1}/${bank.length}`}</strong></div>{done?<div className="tenses-result"><div className="tenses-result-score">{score}<small>/ {bank.length}</small></div><h3>Good work. Review the lessons where your answer was uncertain.</h3><button onClick={()=>startMode(section)}>Retry {ANSWERED_LABELS[section]}</button></div>:<div className="tenses-question"><span>Question {question+1}</span><h2>{current[0]}</h2><div className="tenses-options">{current[1].map((opt,i)=><button key={i} className={selected===i?(i===current[2]?'correct':'wrong'):selected!==null&&i===current[2]?'correct':''} onClick={()=>pick(i)}>{String.fromCharCode(65+i)} <span>{opt}</span></button>)}</div>{selected!==null&&<div className="tenses-feedback"><strong>{selected===current[2]?'✓ Correct':'Review this one'}</strong><span>{current[3]}</span></div>}<button className="tenses-next" disabled={selected===null} onClick={next}>{question+1===bank.length?'Finish':'Next question →'}</button></div>}</main>}
   <footer className="tenses-footer"><button onClick={()=>onBack?.()}>← Exit Tenses</button><span>Study pattern → examples → translation → practice → challenge → final test</span></footer>
 </div>
}