import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
  title:'Too Many People, Too Few Trees',
  author:'Moti Nisani',
  sourceNote:'Class 9 English • The Panorama • Prose Chapter 4',
  intro:'“Too Many People, Too Few Trees” gives a brief introduction to the twin problems of overpopulation and deforestation. It connects rapid population growth with pressure on food, resources, pollution and forests, and closes by stressing the need for human responsibility and hope.',
  authorNote:'The textbook introduces Moti Nisani as a teacher at Wayne State University, USA, with an interdisciplinary background and publications in genetics, ecology, politics, science, education and language instruction. The essay focuses on the linked problems of overpopulation and deforestation.',
  sections:[
    {title:'Part 1 — Population in earlier human history',flow:'For most of human existence, births were only slightly higher than deaths, so population increased slowly. Better nutrition and sanitation changed this balance, helping people live longer and allowing more people to reach reproductive age.',explanation:'मानव इतिहास के अधिकांश समय में जन्मों की संख्या मृत्यु से केवल थोड़ी अधिक थी, इसलिए जनसंख्या धीरे बढ़ती थी। पोषण और स्वच्छता में सुधार से लोग अधिक समय तक जीने लगे और अधिक लोग प्रजनन आयु तक पहुँचने लगे।',vocabulary:[['existence','अस्तित्व'],['nutrition','पोषण'],['sanitation','स्वच्छता'],['reproductive age','प्रजनन आयु'],['balance','संतुलन']],exam:'Learn the cause chain: improved nutrition and sanitation → longer life → more people reaching reproductive age.',think:'How can improvements in living conditions change population growth?'},
    {title:'Part 2 — Why rapid growth creates an ecological limit',flow:'More people may appear beneficial because people can create inventions and profit, but the lesson argues that the world is finite. From an ecological point of view, unlimited population growth puts increasing pressure on food, resources and the environment.',explanation:'अधिक लोगों की संख्या लाभदायक लग सकती है क्योंकि मनुष्य आविष्कार और आर्थिक लाभ ला सकते हैं, लेकिन पृथ्वी सीमित है। पाठ के अनुसार असीमित जनसंख्या वृद्धि भोजन, संसाधनों और पर्यावरण पर बढ़ता दबाव डालती है।',vocabulary:[['finite','सीमित'],['ecological','पारिस्थितिक'],['overpopulated','अधिक जनसंख्या वाला'],['resource','संसाधन'],['pressure','दबाव']],exam:'Distinguish the apparent benefits of more people from the ecological limits described by the author.',think:'Why does a finite planet make unlimited growth difficult?'},
    {title:'Part 3 — Food, land and crowding pressures',flow:'As population rises, the need for food, land and other resources rises too. Towns and countries become more crowded, and pressure to clear forests grows. The chapter presents population growth as a factor that can intensify several connected problems.',explanation:'जनसंख्या बढ़ने पर भोजन, भूमि और अन्य संसाधनों की आवश्यकता भी बढ़ती है। शहर और देश अधिक भीड़भाड़ वाले हो जाते हैं और वनों को साफ करने का दबाव बढ़ता है। पाठ जनसंख्या वृद्धि को कई जुड़ी समस्याओं को गंभीर बनाने वाले कारक के रूप में प्रस्तुत करता है।',vocabulary:[['crowded','भीड़भाड़ वाला'],['deforestation','वनों की कटाई'],['density','घनत्व'],['demand','माँग'],['intensify','और गंभीर करना']],exam:'Connect population growth with greater food demand, resource use and forest pressure.',think:'How can one increase in population create several different pressures at once?'},
    {title:'Part 4 — Pollution and quality of life',flow:'The lesson connects population density with pollution of rivers, lakes, air, water and soil. It also says that quality of life can fall when crowding and environmental stress become severe, and it mentions possible social problems such as crime, ethnic conflict and warfare.',explanation:'पाठ जनसंख्या घनत्व को नदियों, झीलों, वायु, जल और मिट्टी के प्रदूषण से जोड़ता है। भीड़भाड़ और पर्यावरणीय दबाव बढ़ने पर जीवन की गुणवत्ता कम हो सकती है। पाठ अपराध, जातीय संघर्ष और युद्ध जैसी संभावित सामाजिक समस्याओं का भी उल्लेख करता है।',vocabulary:[['pollution','प्रदूषण'],['quality of life','जीवन की गुणवत्ता'],['ethnic','जातीय'],['conflict','संघर्ष'],['warfare','युद्ध']],exam:'Remember both environmental and social effects of very high population density.',think:'Why does the lesson treat population density as more than just a number?'},
    {title:'Part 5 — Air pollution and public health',flow:'The American example in the lesson shows how pollution can worsen respiratory illness and asthma. The point is not only environmental damage: polluted surroundings can directly affect human health. The author uses this link to strengthen the argument for controlling harmful pressures.',explanation:'पाठ में दिए गए अमेरिकी उदाहरण से पता चलता है कि प्रदूषण श्वसन संबंधी रोगों और अस्थमा को बढ़ा सकता है। समस्या केवल पर्यावरण की नहीं है; प्रदूषित वातावरण सीधे मानव स्वास्थ्य को प्रभावित कर सकता है। लेखक इस संबंध से हानिकारक दबावों को नियंत्रित करने के पक्ष को मजबूत करता है।',vocabulary:[['respiratory','श्वसन संबंधी'],['asthma','अस्थमा'],['aggravate','और गंभीर करना'],['incidence','प्रचलन / घटना'],['public health','जनस्वास्थ्य']],exam:'Use the pollution example to connect environmental quality with human health.',think:'Why is an environmental problem also a public-health problem?'},
    {title:'Part 6 — Global environmental changes',flow:'The essay expands the discussion to desertification, depletion of non-renewable resources, acid rain, loss of wild species, ozone-layer depletion and the greenhouse effect. A United Nations document cited by the lesson links population size and growth rates with environmental change.',explanation:'निबंध पर्यावरणीय समस्याओं की सूची को मरुस्थलीकरण, अनवीकरणीय संसाधनों की कमी, अम्लीय वर्षा, वन्य प्रजातियों की हानि, ओजोन परत के क्षय और ग्रीनहाउस प्रभाव तक बढ़ाता है। पाठ में उद्धृत संयुक्त राष्ट्र दस्तावेज जनसंख्या के आकार और वृद्धि दर को पर्यावरणीय परिवर्तन से जोड़ता है।',vocabulary:[['desertification','मरुस्थलीकरण'],['non-renewable','अनवीकरणीय'],['acid rain','अम्लीय वर्षा'],['species','प्रजाति'],['greenhouse effect','ग्रीनहाउस प्रभाव']],exam:'Be ready to name several global environmental problems explicitly listed in the chapter.',think:'Why does the author move from local pressure to global environmental change?'},
    {title:'Part 7 — Population control and social factors',flow:'The chapter says restoring the biosphere depends partly on slowing population growth. Germany, Sweden, China, Thailand and Egypt are given as examples. Education, literacy, media campaigns, family planning and opportunities for women are among the factors listed to explain slower growth.',explanation:'अध्याय के अनुसार जीवमंडल को सँभालने के लिए जनसंख्या वृद्धि को धीमा करना एक महत्त्वपूर्ण कदम है। जर्मनी, स्वीडन, चीन, थाईलैंड और मिस्र उदाहरण के रूप में दिए गए हैं। शिक्षा, साक्षरता, मीडिया अभियान, परिवार नियोजन तथा महिलाओं के अवसर जैसे कारणों का उल्लेख किया गया है।',vocabulary:[['biosphere','जीवमंडल'],['literacy','साक्षरता'],['campaign','अभियान'],['family planning','परिवार नियोजन'],['opportunity','अवसर']],exam:'Memorise both the country examples and the social factors listed in the source.',think:'How can education and women’s opportunities influence population trends?'},
    {title:'Part 8 — Poverty and forest clearance',flow:'The author explains that poverty and related conditions can force people in poorer countries to clear, burn or cultivate tropical forests. Nepal is used as an example of pressure on trees and forests for fuel and livelihood needs.',explanation:'लेखक बताते हैं कि गरीबी और उससे जुड़ी परिस्थितियाँ गरीब देशों के लोगों को उष्णकटिबंधीय वनों को काटने, जलाने या खेती के लिए उपयोग करने पर मजबूर कर सकती हैं। नेपाल का उदाहरण ईंधन और जीवन-यापन के लिए पेड़ों पर बढ़ते दबाव को दिखाता है।',vocabulary:[['tropical','उष्णकटिबंधीय'],['clear','वन हटाना'],['cultivate','खेती करना'],['fuel','ईंधन'],['livelihood','जीवन-यापन']],exam:'Explain how poverty can create direct pressure on tropical forests.',think:'Why might people clear forests even when forest loss is harmful in the long term?'},
    {title:'Part 9 — Affluence and consumer demand',flow:'Deforestation is not driven only by poverty. The lesson also points to affluent consumers and demand for products such as hamburgers, mahogany furniture, newspapers and paper. Consumption in one place can therefore contribute to forest clearance elsewhere.',explanation:'वनों की कटाई केवल गरीबी के कारण नहीं होती। पाठ समृद्ध उपभोक्ताओं की माँग और हैमबर्गर, महोगनी फर्नीचर, समाचारपत्र तथा कागज जैसे उत्पादों का उदाहरण भी देता है। इसलिए एक स्थान की खपत दूसरे स्थान के वनों की कटाई में योगदान कर सकती है।',vocabulary:[['affluent','समृद्ध'],['consumer demand','उपभोक्ता माँग'],['mahogany','महोगनी'],['clearance','सफाई / कटाई'],['consumption','खपत']],exam:'The chapter deliberately presents poverty-driven and consumption-driven pressures together.',think:'Why is it important to discuss both poverty and affluence when explaining deforestation?'},
    {title:'Part 10 — Consequences of deforestation and the final choice',flow:'The lesson describes forest loss as a cause of greenhouse effects, irreversible species loss, landslides, soil erosion, siltation, droughts and extreme weather. It ends by contrasting passive hope with responsible action: people can continue damaging forests or work to hold back and reverse deforestation.',explanation:'पाठ वनों की हानि को ग्रीनहाउस प्रभाव, प्रजातियों की अपरिवर्तनीय हानि, भूस्खलन, मृदा अपरदन, गाद जमने, सूखे और चरम मौसम से जोड़ता है। अंत में केवल उम्मीद करने के बजाय जिम्मेदार कार्रवाई का विकल्प रखा गया है—वनों की क्षति को रोकना और उसे उलटने का प्रयास करना।',vocabulary:[['irreversible','जिसे वापस पहले जैसा न किया जा सके'],['landslide','भूस्खलन'],['soil erosion','मृदा अपरदन'],['siltation','गाद का जमाव'],['reverse','स्थिति को सुधारना / उलटना']],exam:'The conclusion combines a warning about consequences with a call for responsible action.',think:'Why does the final paragraph make human choice central to the environmental message?'}
  ],
  glossary:[['flux','continuous flow — लगातार परिवर्तन / प्रवाह'],['existence','the state of being real or living — अस्तित्व'],['sanitation','improvement in sanitary methods — स्वच्छता व्यवस्था'],['species','group having some common characteristics — प्रजाति'],['sobering','adjective meaning serious or thought-provoking — गंभीर चेताने वाला'],['vanish','disappear — गायब होना'],['tantamount','equivalent — समान / बराबर'],['exacerbate','make sore and bitter / worsen — और खराब करना'],['ethnic','pertaining to races — जातीय'],['erode','destroy gradually — धीरे-धीरे नष्ट करना'],['desertification','the process of becoming or making something a desert — मरुस्थलीकरण'],['decay','rot / become rotten — सड़ना'],['campaign','organised course of action — अभियान'],['arable','fit for cultivation — कृषि योग्य'],['tropical','pertaining to the tropics — उष्णकटिबंधीय'],['pastures','land for grazing cattle — चरागाह'],['landslides','falling of rocks and stones from mountains — भूस्खलन'],['devastating','causing destruction — विनाशकारी'],['hamper','to hinder — बाधा डालना'],['affluent','wealthy — समृद्ध'],['insatiable','never satisfied — अतृप्त'],['felled','cut down — काटा गया'],['sustain','to support — बनाए रखना / सहारा देना']],
  wordStudy:{
    spellings:[['existense','existence'],['continueu','continue'],['resorses','resources'],['specis','species'],['eventuely','eventually'],['allready','already'],['fourty','forty'],['compain','campaign'],['decissive','decisive']],
    forms:[['rise','rises / rising'],['lose','loses / losing'],['go','goes / going'],['grow','grows / growing']],
    match:[['grim','severe, horrible'],['decisive','deciding'],['affluent','wealthy'],['insatiable','unsatisfied'],['felled','cut down'],['sustain','to support']],
    notes:[['more and more','shows increasing quantity or degree — लगातार बढ़ती मात्रा'],['population growth','increase in the number of people — जनसंख्या वृद्धि'],['environmental change','change in natural surroundings — पर्यावरणीय परिवर्तन'],['forest covered','land under forests — वन से ढकी भूमि']]
  },
  grammar:{title:'Modal Auxiliaries',intro:'The chapter teaches modal auxiliaries such as can, may, shall, will, could, might, should, would, must, dare, need, used to and ought to. Their meanings depend on context, especially possibility, permission, ability, duty, compulsion, strong possibility, advice and past ability.',rules:[
    ['can — ability / capacity / permission','Can may show power or ability, and in informal usage it can also show permission.','Ravi can solve this problem. • You can take this pen.'],
    ['could — past ability / polite request / indirect speech','Could may refer to ability in the past, a polite request, or what someone said in indirect speech.','When Rohit was young, he could run twenty miles. • Could you help me?'],
    ['may — possibility / wish / permission','May commonly expresses possibility or permission.','It may rain today. • May I come in?'],
    ['might — weaker possibility','Might can indicate a less certain possibility.','He might catch a cobra.'],
    ['must — compulsion / strong possibility','Must can express duty or compulsion, and it may also express strong possibility.','You must do as you are told. • He must be tired.'],
    ['should — duty / advice / obligation / instruction','Should commonly expresses duty, advice or what is considered proper.','We should love our country.'],
    ['will / shall — intention, future or determination','The chapter lists will and shall among modals used to express future meaning, intention or determination according to context.','I shall return. • We will work hard.'],
    ['would — preference / polite request / past habit or future-in-the-past','Would is used in several contexts, including polite requests and conditional or past-related meanings.','Would you help me?'],
    ['need / dare / used to / ought to','These are also listed by the chapter as modal or semi-modal forms. Need can express necessity; dare can express courage; used to past habit; ought to duty or desirability.','You ought to obey your parents. • We used to live here.']
  ]},
  composition:['Write a letter to your friend emphasising the need for population control.'],
  activities:[
    'Make a list of major changes you observe in your surroundings after discussing them with three experienced people in your locality.',
    'Ask your geography teacher to explain desertification and its impact on human life.',
    'Do a project on the devastation caused by floods.'
  ],
  translationPractice:[
    ['तुम्हें माता-पिता की आज्ञा माननी चाहिए।','You should obey your parents.'],
    ['तुम घर जा सकते हो।','You may go home.'],
    ['हमें सत्य बोलना चाहिए।','We should speak the truth.'],
    ['सोहन परीक्षा में उत्तीर्ण हो सकता।','Sohan could pass the examination.'],
    ['क्या तुम मेरी मदद कर सकते हो?','Can you help me?'],
    ['क्या आज वर्षा होगी?','May it rain today?'],
    ['उसे वहाँ जाने की जरूरत नहीं है।','He need not go there.'],
    ['क्या मैं आपकी मदद कर सकता हूँ?','May I help you?'],
    ['हमें जल प्रदूषण नहीं करना चाहिए।','We should not pollute water.'],
    ['हमलोग कल बाढ़ पीड़ितों की सेवा करने जायेंगे।','We shall go to serve the flood victims tomorrow.']
  ],
  examPrep:[
    'Why have human populations always been in flux?',
    'What does the term reproductive age mean in the chapter?',
    'Why can unlimited population growth not continue on a finite planet?',
    'How does higher population density affect quality of life?',
    'What pollution problem is discussed through the American example?',
    'Name the major environmental problems listed in the chapter.',
    'Which countries are given as examples of slowed population growth?',
    'What factors does the lesson give for slower population growth?',
    'Why are people in some poorer countries forced to clear tropical forests?',
    'How does affluence also contribute to deforestation?',
    'How does deforestation in Nepal affect the wider region?',
    'Why is the productivity and general health of the world’s forests threatened?',
    'How does deforestation affect the ability of the biosphere to sustain life?',
    'How does the final paragraph balance warning with hope?',
    'Explain the grammar uses of can, may, could, must and should.',
    'Write a letter emphasising the need for population control.'
  ]
};

const practice=[
 {q:'Who wrote “Too Many People, Too Few Trees”?',o:['Moti Nisani','Kunal Varma','Arjun Dev Charan','C. Rajagopalachari'],a:0,e:'The title page credits Moti Nisani as the writer.'},
 {q:'What two linked problems are introduced in the essay?',o:['Overpopulation and deforestation','Floods and earthquakes','Tourism and transport','Noise and music'],a:0,e:'The introduction calls overpopulation and deforestation the twin problems.'},
 {q:'For most of human existence, world population grew:',o:['very slowly','at an unlimited rate','only in cities','only after 2000'],a:0,e:'Births were only slightly higher than deaths, so growth was slow.'},
 {q:'Which developments helped change the balance between births and deaths?',o:['Nutrition and sanitation','Television and cinema','Railways and ports','Tourism and trade'],a:0,e:'The lesson specifically mentions advances in nutrition and sanitation.'},
 {q:'What is one result of more people reaching reproductive age?',o:['Rapid population growth','Less food demand','Less resource use','Automatic forest recovery'],a:0,e:'More people reaching reproductive age contributed to rapid population growth.'},
 {q:'The chapter says the world is already overpopulated from an:',o:['ecological point of view','artistic point of view','musical point of view','historical museum point of view'],a:0,e:'The author says ecologists are convinced the world is already overpopulated.'},
 {q:'As population goes up, people need:',o:['more food','less food','no resources','fewer services'],a:0,e:'The passage explicitly says more people will need more food.'},
 {q:'Which environmental media are named as becoming more polluted?',o:['Rivers, lakes, air, water and soil','Only forests','Only oceans','Only roads'],a:0,e:'The chapter lists rivers, lakes, air, water and soil.'},
 {q:'Higher population density is said to be likely to exacerbate:',o:['crime, ethnic conflicts and warfare','rainfall only','music and art','sports injuries'],a:0,e:'These social problems are named in the passage.'},
 {q:'Which health problem is highlighted in the American example?',o:['Asthma aggravated by air pollution','Broken bones','Tooth decay','Hearing loss'],a:0,e:'The chapter discusses asthma deaths aggravated by air pollution.'},
 {q:'Which of the following is listed as a global environmental problem?',o:['Desertification','Book printing','School uniforms','Stage lighting'],a:0,e:'Desertification appears in the chapter’s list of global problems.'},
 {q:'Which countries are named as examples where population growth has slowed considerably?',o:['Germany, Sweden, China, Thailand and Egypt','India, Nepal, Brazil, France and Japan','Canada, Peru, Kenya, Spain and Iran','Australia, Mexico, Italy, Bhutan and Chile'],a:0,e:'These five countries are named in paragraph 6.'},
 {q:'Which factor is given as helping slow population growth?',o:['Education and literacy','Less information','More crowding','Fewer opportunities for women'],a:0,e:'Education and literacy are explicitly listed.'},
 {q:'What may force many people in poorer countries to clear tropical forests?',o:['Poverty and other conditions','Excess rainfall only','Music festivals','School examinations'],a:0,e:'The lesson connects tropical forest clearing with poverty and other conditions.'},
 {q:'According to the chapter, what may be cleared to satisfy affluent consumers?',o:['Forests','Classrooms','Railway stations','Museums'],a:0,e:'The author describes forests being cleared for consumer demand.'}
];

const challenge=[
 {q:'Why did improvements in nutrition and sanitation contribute to a rapid rise in population?',o:['They helped people live longer and allowed more people to reach reproductive age','They reduced the number of births','They made forests grow faster','They eliminated all disease'],a:0,e:'The text links longer life and more people reaching reproductive age to rapid growth.'},
 {q:'Why does the author reject the simple idea that “more people is always better”?',o:['Ecological limits mean additional population increases pressure on food, resources and the environment','People have no value','Technology has no benefits','Profit never exists'],a:0,e:'The essay acknowledges benefits but stresses that a finite world imposes ecological limits.'},
 {q:'What is the strongest reason that population growth increases deforestation pressure?',o:['More people need more food, land, fuel and resources','Trees create population growth','Forests cause all pollution','Population growth reduces the need for land'],a:0,e:'The passage connects increased needs with pressure to clear forests.'},
 {q:'How can higher population density affect quality of life?',o:['Crowding and environmental stress can worsen pollution and social problems','It automatically removes crime','It guarantees cleaner rivers','It always increases free land'],a:0,e:'The lesson connects density with crowding, pollution and possible conflict.'},
 {q:'Why is the air-pollution example important to the article’s argument?',o:['It demonstrates that environmental damage can directly affect human health','It proves population has no effect on health','It is unrelated to pollution','It concerns only road traffic rules'],a:0,e:'The example turns an environmental issue into a public-health concern.'},
 {q:'What does the statement that population size and growth rates are key elements in environmental change imply?',o:['Both the total number of people and how quickly numbers increase matter','Only city population matters','Population growth never affects resources','Only forests matter'],a:0,e:'The statement stresses both population size and rate of growth.'},
 {q:'Why are education, literacy and women’s opportunities included in the discussion of population control?',o:['They can support informed family planning and give people more choices about family size','They increase pollution automatically','They cause forest fires','They eliminate the need for education'],a:0,e:'The lesson explicitly links these social factors with slower growth.'},
 {q:'How can poverty drive deforestation?',o:['People may clear, burn or cultivate forests to meet basic economic and livelihood needs','Poorer people never use forests','Poverty increases rainfall','Poverty plants more trees'],a:0,e:'The passage says poverty and other conditions can force forest clearing.'},
 {q:'How can affluence also contribute to deforestation?',o:['Consumer demand can encourage forest clearance for food, furniture and paper products','Rich consumers always protect every forest','Affluence removes the need for resources','Only poor countries buy goods'],a:0,e:'The essay gives consumer demand as another pressure on forests.'},
 {q:'Why is Nepal used as an example in the deforestation discussion?',o:['More people may mean more demand for fuel and more pressure to cut forests','Nepal has no forests','Nepal causes all global pollution','It is the only country with deserts'],a:0,e:'The text says population pressure can increase forest cutting for fuel.'},
 {q:'Which chain best describes a major deforestation effect described in the chapter?',o:['Forest loss → soil erosion and river siltation → greater environmental damage','Forest loss → more forests → less erosion','Forest loss → cleaner air automatically','Forest loss → no effect on rivers'],a:0,e:'The chapter lists soil erosion and siltation among the consequences of forest destruction.'},
 {q:'Why does the author mention irreversible loss of species?',o:['Some consequences of deforestation cannot simply be undone once species are lost','Species always return immediately','Species loss is unrelated to forests','It describes a grammar rule'],a:0,e:'The word irreversible underscores the permanence of some damage.'},
 {q:'What does the final choice in the essay suggest about human responsibility?',o:['People can either ignore the damage or take action to slow and reverse deforestation','Nature alone will solve every problem','Nothing can be changed','Only governments have responsibility'],a:0,e:'The conclusion presents human action as a meaningful choice.'},
 {q:'Which statement best explains “the more people the world has, the more severe these problems are likely to become”?',o:['More people can mean greater energy use, resource consumption and environmental stress','More people always mean less resource use','Population has no environmental effect','Only weather controls environmental stress'],a:0,e:'The paragraph directly connects population size with energy, resources and stress.'},
 {q:'What does “insatiable” mean in the context of the chapter?',o:['Never satisfied','Very poor','Carefully planned','Cut down'],a:0,e:'The glossary gives insatiable as never satisfied.'},
 {q:'What does “tantamount” mean?',o:['Equivalent','Sudden','Tropical','Polluted'],a:0,e:'The glossary defines tantamount as equivalent.'},
 {q:'Which word means “to hinder”?',o:['Hamper','Erode','Vanish','Sustain'],a:0,e:'The glossary defines hamper as to hinder.'},
 {q:'Which word means “cut down” in the word study section?',o:['Felled','Affluent','Decisive','Grim'],a:0,e:'The matching exercise pairs felled with cut down.'},
 {q:'Which noun is formed by adding “-ity” to “possible” in the chapter’s word-study pattern?',o:['Possibility','Possibleness','Possibity','Possibly'],a:0,e:'The word-formation activity in the chapter focuses on related noun forms; possibility is the standard noun from possible.'},
 {q:'Which modal best expresses permission in “May I come in?”',o:['may','must','should','could'],a:0,e:'The chapter explicitly uses may for permission.'},
 {q:'Which modal indicates past ability in “When Rohit was young, he could run twenty miles”?',o:['could','must','may','shall'],a:0,e:'Could is used for past ability in the example.'},
 {q:'Which modal expresses duty in “We should love our country”?',o:['should','might','can','would'],a:0,e:'The grammar section labels should as duty, obligation, advice or instruction.'},
 {q:'Which modal can express strong possibility in “He must be tired”?',o:['must','may','can','shall'],a:0,e:'The grammar notes that must can indicate strong possibility.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`panorama-too-many-people-final-${i}`}));

function StudyView(){return <div className="pg-learn">
  <div className="pg-callout pg-no-book"><b>📘 Complete Guided Study</b><span>Chapter flow, आसान हिन्दी explanation, vocabulary, word study, grammar, activities, translation और exam preparation एक ही जगह।</span></div>
  <section className="pg-panel"><div className="pg-panel-title"><span>ABOUT THE LESSON</span><h2>Chapter का basic idea</h2></div><p>{study.intro}</p><div className="pg-author"><b>लेखक / स्रोत परिचय</b><p>{study.authorNote}</p></div></section>
  <div className="pg-anchorbar"><a href="#guided">Guided Reading</a><a href="#words">Word Study</a><a href="#grammar">Grammar</a><a href="#exam">Exam Prep</a></div>
  <section id="guided" className="pg-section-heading"><span>01</span><div><small>READ • UNDERSTAND • REMEMBER</small><h2>Guided Reading</h2><p>हर block chapter के flow को आसान English में समझाता है और फिर हिन्दी में उसका अर्थ स्पष्ट करता है।</p></div></section>
  <div className="pg-reading-stack">{study.sections.map((s,i)=><article className="pg-reading-card" key={s.title}><div className="pg-card-top"><div className="pg-num">{String(i+1).padStart(2,'0')}</div><div><span>CHAPTER FLOW</span><h3>{s.title}</h3></div></div><div className="pg-flow"><div className="pg-flow-label">सरल English में पढ़ें</div><p>{s.flow}</p></div><div className="pg-hindi"><div className="pg-flow-label">हिन्दी में समझें</div><p>{s.explanation}</p></div><div className="pg-vocab-head">Vocabulary</div><div className="pg-vocab-grid">{s.vocabulary.map(([w,m])=><div className="pg-vocab" key={w}><b>{w}</b><span>{m}</span></div>)}</div><div className="pg-bottom-grid"><div className="pg-exam"><b>🎯 Exam Point</b><span>{s.exam}</span></div><div className="pg-think"><b>💡 Think</b><span>{s.think}</span></div></div></article>)}</div>
  <section id="words" className="pg-section-heading compact"><span>02</span><div><small>LANGUAGE BUILDING</small><h2>Word Study</h2><p>Glossary, spelling, word forms और matching revise करें।</p></div></section>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>Glossary</h3><div className="pg-glossary">{study.glossary.map(([w,m])=><div key={w}><b>{w}</b><span>{m}</span></div>)}</div></section><section className="pg-panel"><h3>Correct the spelling</h3><div className="pg-spelling">{study.wordStudy.spellings.map(([bad,good])=><div key={bad}><del>{bad}</del><b>→ {good}</b></div>)}</div></section></div>
  <section className="pg-panel"><h3>Word Forms</h3><p className="pg-muted">Chapter के D.2 में rise, lose, go और grow के suitable forms practise किए गए हैं।</p><div className="pg-pillgrid">{study.wordStudy.forms.map(([w,m])=><div key={w}><b>{w}</b><span>→ {m}</span></div>)}</div></section>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>Meaning Match</h3><div className="pg-match">{study.wordStudy.match.map(([q,a])=><div key={q}><span>{q}</span><b>{a}</b></div>)}</div></section><section className="pg-panel"><h3>Quick Notes</h3><div className="pg-match">{study.wordStudy.notes.map(([q,a])=><div key={q}><span>{q}</span><b>{a}</b></div>)}</div></section></div>
  <section id="grammar" className="pg-section-heading compact"><span>03</span><div><small>GRAMMAR LAB</small><h2>{study.grammar.title}</h2><p>{study.grammar.intro}</p></div></section>
  <section className="pg-panel"><h3>Core rules</h3><div className="pg-grammar-grid">{study.grammar.rules.map(([t,e,x])=><div key={t}><b>{t}</b><span>{e}</span>{x&&<em>{x}</em>}</div>)}</div><div className="pg-rulebox"><b>Golden Rule</b><span>Modal meaning depends on context. Check whether the sentence expresses ability, permission, possibility, duty, advice, compulsion or another meaning before choosing the modal.</span></div></section>
  <section className="pg-panel"><h3>Quick modal examples</h3><div className="pg-phrasegrid"><div><b>May I come in?</b><span>Permission.</span></div><div><b>It may rain today.</b><span>Possibility.</span></div><div><b>Ravi can solve it.</b><span>Ability.</span></div><div><b>He could run twenty miles.</b><span>Past ability.</span></div><div><b>You must do as told.</b><span>Compulsion / duty.</span></div><div><b>We should love our country.</b><span>Duty / advice.</span></div></div></section>
  <section className="pg-section-heading compact"><span>04</span><div><small>WRITING • ACTIVITIES • TRANSLATION</small><h2>Composition & Activities</h2><p>Chapter के practical tasks को exam-ready format में देखें।</p></div></section>
  <section className="pg-tool-grid"><section className="pg-panel"><h3>Composition</h3><ol>{study.composition.map(x=><li key={x}>{x}</li>)}</ol></section><section className="pg-panel"><h3>Activities</h3><div className="pg-activitygrid">{study.activities.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div></section></section>
  <section className="pg-panel"><h3>Translation Practice</h3><div className="pg-translation">{study.translationPractice.map(([h,e],i)=><div key={h}><span>{String(i+1).padStart(2,'0')}</span><b>{h}</b><em>{e}</em></div>)}</div></section>
  <section id="exam" className="pg-section-heading compact"><span>05</span><div><small>EXAM MODE</small><h2>Exam Preparation</h2><p>इन questions पर short answer, long answer, grammar और writing practice करें।</p></div></section>
  <section className="pg-exam-grid"><section className="pg-panel"><h3>Important Questions</h3><ol>{study.examPrep.map(x=><li key={x}>{x}</li>)}</ol></section><section className="pg-panel pg-revision"><h3>One-minute revision</h3><div className="pg-revision-grid"><div><b>Core issue</b><span>Overpopulation + deforestation.</span></div><div><b>Cause</b><span>Longer life and more people reaching reproductive age.</span></div><div><b>Pressures</b><span>Food, energy, resources, pollution and crowding.</span></div><div><b>Population examples</b><span>Germany, Sweden, China, Thailand, Egypt.</span></div><div><b>Forest pressures</b><span>Poverty, fuel needs and affluent consumer demand.</span></div><div><b>Consequences</b><span>Species loss, erosion, landslides, siltation and extreme weather.</span></div></div></section></section>
  <section className="pg-panel"><h3>Chapter Checklist</h3><div className="pg-activitygrid"><div><span>✓</span><p>Can you explain why population grew rapidly?</p></div><div><span>✓</span><p>Can you connect population density with food, pollution and social pressure?</p></div><div><span>✓</span><p>Can you name the countries and social factors linked with slower growth?</p></div><div><span>✓</span><p>Can you explain both poverty-driven and consumption-driven deforestation?</p></div><div><span>✓</span><p>Can you use can, may, could, must and should correctly?</p></div><div><span>✓</span><p>Can you translate the 10 Hindi sentences into English?</p></div></div></section>
</div>}

export function EnglishPanoramaChapter4({initialMode=null,onBack,addXp,finishSession}){
  const[mode,setMode]=useState(initialMode||'learn');
  const begin=nextMode=>setMode(nextMode);
  if(mode==='learn'||mode===null)return <div className="pg-shell"><button className="pg-back" onClick={onBack}>← वापस</button><header className="pg-hero"><div className="pg-kicker">THE PANORAMA • PROSE CHAPTER 4</div><h1>{study.title}</h1><p>Written by {study.author}</p><div className="pg-hero-stats"><span>10 guided parts</span><span>15 Practice questions</span><span>23 Challenge questions</span><span>20 Final Test questions</span></div></header><div className="pg-modebar"><button className="active" onClick={()=>begin('learn')}><b>LEARN</b><span>Guided study • vocabulary • grammar</span></button><button onClick={()=>begin('practice')}><b>15 Practice</b><span>11:15 min • Easy → Moderate</span></button><button onClick={()=>begin('challenge')}><b>23 Challenge</b><span>23:00 min • Moderate → Hard</span></button><button onClick={()=>begin('test')}><b>20 Final Test</b><span>25:00 min • Exam Level</span></button></div><StudyView/></div>;
  const bank=mode==='practice'?practice:mode==='challenge'?challenge:finalTest;
  return <PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>begin('learn')} addXp={addXp} finishSession={payload=>finishSession?.({subject:'english',book:'The Panorama',...payload})}/>;
}

export const englishPanoramaChapter4={title:study.title,author:study.author};
