import React,{useEffect,useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-panorama-poetry.css';

const poem={
 title:'On His Blindness',poet:'John Milton',book:'The Panorama • Poetry Chapter 2',
 sourceNote:'Built from the supplied Bihar Board Class 9 Panorama source pages 91–96.',
 context:'In this Petrarchan sonnet, Milton reflects on the loss of his eyesight and worries about how he can serve God with the talent he has received. Patience answers his doubt by explaining that God does not measure service only by visible activity; faithful endurance and waiting can also be service.',
 structure:'Petrarchan sonnet: the first eight lines form the octave and the final six lines form the sestet. The argument turns from anxious questioning to patient consolation.',
 stanzas:[
  {title:'Octave — प्रश्न, पीड़ा और सेवा की चिंता',range:'Octave • Lines 1–8',poemLines:['When I consider how my light is spent','Ere half my days, in this dark world and wide,','And that one talent which is death to hide,','Lodged with me useless, though my soul more bent','To serve therewith my Maker, and present','My true account, lest He returning chide;','“Doth God exact day-labour, light denied?”','I fondly ask; but Patience to prevent'],explanation:'मिल्टन अपनी आँखों की रोशनी खोने और जीवन के आधे समय से पहले अंधकार में पड़ जाने पर विचार करता है। उसे चिंता है कि उसके भीतर मिला talent कहीं बेकार न रह जाए और वह God की सेवा तथा अपना account प्रस्तुत न कर पाए। वह पूछता है कि जब उसकी light ही denied है, तब क्या God उससे day-labour की अपेक्षा करते हैं। अंत में Patience उसके भीतर उठे इस murmur को रोकने के लिए उत्तर देने आती है।',vocab:[['light','यहाँ eyesight/दृष्टि का संकेत'],['spent','समाप्त या कम हो जाना'],['ere','before / पहले'],['talent','ईश्वर से मिला उपहार या क्षमता'],['lodged','स्थित / भीतर रखा हुआ'],['Maker','God / सृष्टिकर्ता'],['chide','डाँटना'],['exact','माँग करना / अपेक्षा करना'],['day-labour','दैनिक परिश्रम'],['denied','वंचित / न दिया गया']],exam:'मुख्य बिंदु: lost eyesight, talent, service to God, account और God से किया गया rhetorical question.',key:'Movement = चिंता और प्रश्न | Form = Octave | Turning point = Patience का उत्तर शुरू होने से पहले'} ,
  {title:'Sestet — धैर्य का उत्तर और निष्कर्ष',range:'Sestet • Lines 9–14',poemLines:['That murmur, soon replies, “God doth not need','Either man’s work, or His own gifts; who best','Bear His mild yoke, they serve Him best, His state','Is kingly: thousands at His bidding speed,','And post o’er land and ocean without rest;','They also serve who only stand and wait.”'],explanation:'Patience समझाती है कि God को मनुष्य के काम या उनके दिए हुए gifts की कमी नहीं है। जो व्यक्ति God का mild yoke धैर्य से उठाता है, वही अच्छी तरह सेवा करता है। God का state kingly है और हजारों लोग उनके bidding पर सक्रिय हैं; इसलिए हर सेवा का रूप एक जैसा नहीं होता। अंतिम पंक्ति बताती है कि जो लोग केवल stand and wait करते हैं, वे भी ईश्वर की सेवा करते हैं।',vocab:[['murmur','धीमी शिकायत / मन की बड़बड़ाहट'],['replies','उत्तर देती है'],['need','आवश्यकता होना'],['bear','सहन करना / उठाना'],['mild yoke','हल्का या सहनीय दायित्व'],['state','स्थिति / राजसी व्यवस्था'],['kingly','राजसी'],['bidding','आदेश'],['post','तेजी से जाना'],['stand and wait','धैर्य से प्रतीक्षा करना']],exam:'मुख्य बिंदु: Patience, mild yoke, kingly state और “stand and wait” वाला निष्कर्ष.',key:'Movement = consolation और acceptance | Form = Sestet | Message = quiet endurance can also be service'}
 ],
 words:[['light','दृष्टि / रोशनी'],['spent','समाप्त'],['ere','पहले'],['talent','उपहार / क्षमता'],['lodged','स्थित'],['useless','बेकार'],['Maker','ईश्वर'],['chide','डाँटना'],['exact','माँग करना'],['murmur','धीमी शिकायत'],['Patience','धैर्य'],['bear','सहन करना'],['yoke','दायित्व'],['kingly','राजसी'],['bidding','आदेश'],['post','तेजी से जाना']],
 devices:[['Petrarchan sonnet','कविता 14 पंक्तियों की sonnet form में है और 8-line octave तथा 6-line sestet में बँटी है।'],['Personification','Patience को उत्तर देने वाली मानवीय शक्ति के रूप में प्रस्तुत किया गया है।'],['Rhetorical question','“Doth God exact day-labour, light denied?” कवि के भीतर की चिंता को प्रश्न के रूप में रखता है।'],['Metaphor','“light” eyesight के साथ जुड़ा है और “mild yoke” सेवा/कर्तव्य के दायित्व का रूपक है।'],['Allusion','“talent” भाषा ईसाई बाइबिल परंपरा के talent idea की ओर संकेत करती है।'],['Contrast','मानवीय active work और “stand and wait” के बीच अंतर से सेवा की व्यापक अवधारणा सामने आती है।']],
 themes:['faith despite disability','service to God','patience and acceptance','inner strength','duty without visible action'],
 textbookAnswers:[['Poet’s concern','Milton worries that blindness may prevent him from using his talent in God’s service.'],['Meaning of light','“Light” refers primarily to the poet’s eyesight and also connects with his ability to serve.'],['Who is Patience?','Patience is personified as the consoling voice that answers Milton’s anxious question.'],['God’s requirement','The answer explains that God does not require visible labour from everyone in the same way.'],['Mild yoke','It suggests a duty or burden that a faithful person accepts and bears.'],['Final message','People who patiently stand and wait can also serve God.'],['Why the kingly state?','God’s majesty and power mean that countless servants can act at His command.'],['Lesson from the poem','Human worth and service are not measured only by physical activity or outward achievement.']]
};

const q=(question,options,answer,explanation)=>({q:question,o:options,a:answer,e:explanation});
const practice=[
q('Who wrote “On His Blindness”?',['John Milton','Ray Young Bear','William Wordsworth','Robert Frost'],0,'The supplied Panorama source identifies John Milton as the poet.'),
q('What kind of sonnet is “On His Blindness” described as?',['Petrarchan sonnet','Shakespearean sonnet','Ballad','Ode'],0,'The source describes it as a Petrarchan sonnet.'),
q('How many lines are in the octave?',['Eight','Six','Ten','Four'],0,'A sonnet octave has eight lines.'),
q('How many lines are in the sestet?',['Six','Eight','Four','Twelve'],0,'A sonnet sestet has six lines.'),
q('What does “my light is spent” primarily refer to?',['Loss of eyesight','Loss of money','Loss of a book','Loss of time only'],0,'The poem is about Milton’s blindness; “light” points to eyesight.'),
q('What does the poet fear about his talent?',['That it may remain unused','That it may make him famous','That it may belong to someone else','That it may disappear in sleep'],0,'He worries that the talent lodged in him may remain useless.'),
q('Who is the “Maker” in the poem?',['God','A king','A teacher','A friend'],0,'Milton calls God his Maker.'),
q('What does the poet ask about day-labour?',['Whether God expects work even when his light is denied','Whether labour should stop forever','Whether he should travel','Whether Patience is working'],0,'The rhetorical question asks whether God exacts day-labour despite blindness.'),
q('Who answers the poet’s murmur?',['Patience','Anger','Fortune','Pride'],0,'Patience is personified as the answering voice.'),
q('What does Patience say God does not need?',['Either man’s work, or His own gifts','More money','A new kingdom','A longer day'],0,'The sestet says God does not need man’s work or even His own gifts.'),
q('What do those who bear God’s “mild yoke” do?',['They serve Him best','They avoid all duty','They become rulers','They stop believing'],0,'Patience says those who bear the mild yoke serve God best.'),
q('What does the word “bidding” mean here?',['Command','Gift','Question','Silence'],0,'Bidding refers to an order or command.'),
q('What happens to thousands at God’s bidding?',['They speed and work across land and ocean','They sleep all day','They leave God’s service','They become poets'],0,'The poem imagines thousands moving at God’s command.'),
q('What does the last line teach?',['Standing and waiting patiently can also be service','Only physical work matters','Blindness prevents all service','Waiting is always useless'],0,'The final line states that those who stand and wait also serve.'),
q('What is the central idea of the poem?',['Faithful service is not limited to visible physical work','Travel is more important than faith','Talent should always be hidden','Kings need no servants'],0,'The poem resolves Milton’s fear by redefining service through patience and faith.')];
const challenge=[
q('Why is “light” a powerful word in the octave?',['It joins physical eyesight with the idea of ability to serve','It refers only to sunlight','It describes a lamp in Milton’s room','It names a person'],0,'Light works on both the literal and symbolic levels of the poem.'),
q('What does “ere half my days” communicate?',['The poet lost his sight before the expected span of life','He lived for half a day','He travelled for half a year','He worked only in the morning'],0,'The phrase stresses that the blindness came before half his life had passed.'),
q('Why does the poet worry about presenting a “true account”?',['He wants to answer for how he used his God-given talent','He wants to calculate money','He wants to write a school report','He wants to report a journey'],0,'The account is a spiritual reckoning about the use of his talent.'),
q('What does “talent” most strongly suggest in the poem?',['A God-given ability or gift','A salary','A piece of land','A school prize'],0,'The word identifies an ability entrusted to the poet.'),
q('What makes the poet’s question rhetorical?',['It expresses inner doubt rather than asking for ordinary information','It is a request for directions','It is a scientific question','It asks Patience for a date'],0,'The question reveals the poet’s anxiety and sets up the answer in the sestet.'),
q('Why is Patience personified?',['To turn an inner quality into a comforting voice','To introduce a historical character','To create a comic scene','To describe a journey'],0,'Personification lets patience directly answer Milton’s fear.'),
q('How does the poem change after the turn?',['It moves from anxious self-questioning to calm acceptance','It changes from history to geography','It becomes angry and violent','It abandons the subject of service'],0,'The sestet provides the consolation the octave lacks.'),
q('What does “mild yoke” imply?',['A duty that can be accepted and carried faithfully','A heavy punishment','A physical chain','A royal crown'],0,'The yoke is a metaphor for a duty or burden accepted in faith.'),
q('Why does the poem mention people moving over land and ocean?',['To show the range of active service already carried out at God’s command','To describe Milton’s travels','To celebrate trade','To compare two countries'],0,'The image establishes that God has many active servants.'),
q('What contrast supports the final message?',['Active labour versus patient waiting','Summer versus winter','Rich versus poor','Sea versus mountain'],0,'The poem contrasts visible activity with patient waiting to broaden the idea of service.'),
q('What is the function of the sestet in the sonnet?',['It answers and resolves the concern raised in the octave','It introduces unrelated characters','It tells a new travel story','It repeats every line of the octave'],0,'The sestet gives the poem its consolation and conclusion.'),
q('Which statement best describes the sonnet’s structure?',['Eight-line octave followed by six-line sestet','Six-line octave followed by eight-line sestet','Seven lines followed by seven lines','Four equal sections'],0,'The source explicitly explains the octave and sestet division.'),
q('What does “His state is kingly” emphasize?',['God’s majestic power and authority','Milton’s social position','The poet’s wealth','The size of England'],0,'The kingly image stresses God’s sovereign majesty.'),
q('What does “post” mean in the context of the poem?',['To move or travel quickly','To write a letter','To stop','To rest'],0,'Here “post” means to hurry or travel quickly.'),
q('Which emotion dominates the octave?',['Anxiety about usefulness and duty','Joy at receiving a gift','Anger at a friend','Excitement about travel'],0,'Milton’s fear of being unable to serve shapes the octave.'),
q('Which emotion dominates the sestet?',['Patience, consolation and acceptance','Fear and panic','Jealousy','Humour'],0,'The answering voice calms the poet’s anxiety.'),
q('How does blindness function beyond the literal condition?',['It creates a test of faith, purpose and self-worth','It becomes a travel guide','It proves the poet dislikes work','It changes the poem into a comedy'],0,'The poem uses blindness to explore how service and purpose should be understood.'),
q('What is the strongest interpretation of “stand and wait”?',['Faithful readiness and patient endurance have spiritual value','People should never act','Waiting is better than all work','The poet wants to avoid responsibility'],0,'The line praises patient fidelity, not laziness or refusal to act.'),
q('Which literary feature is clearly present in the poem?',['Rhetorical questioning','Comic dialogue','Epic battle','Narrative suspense'],0,'Milton uses a direct rhetorical question in the octave.'),
q('Which word is closest in meaning to “chide”?',['Scold','Praise','Follow','Remember'],0,'To chide means to scold or rebuke.'),
q('Which word means “to tolerate or carry a burden”?',['Bear','Post','Exact','Spend'],0,'Bear means to carry, endure or tolerate.'),
q('Which phrase suggests obedience to God’s command?',['At His bidding','Dark world and wide','Half my days','My true account'],0,'“At His bidding” means according to His command.'),
q('What is the role of contrast in the conclusion?',['It shows that service may take both active and quiet forms','It proves one side is useless','It removes the religious theme','It makes the poem humorous'],0,'The contrast allows the final line to include patient waiting as service.'),
q('What practical lesson can a student take from the poem?',['A limitation does not automatically make one’s abilities or efforts worthless','Only perfect performance has value','Failure means a person cannot serve others','Visible action is the only useful action'],0,'The poem encourages purpose, patience and faithful use of whatever abilities remain.'),
q('Why is the final line memorable?',['It resolves the poet’s fear in a compact statement about patient service','It introduces a new character','It changes the setting to the sea','It repeats the title'],0,'The final line gives the poem its lasting spiritual conclusion.')];
const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function StanzaCard({stanza}){return <article className="poem-stanza-card"><div className="poem-card-kicker">{stanza.range}</div><h3>{stanza.title}</h3><div className="poem-actual-label">ACTUAL STANZA</div><div className="poem-actual-stanza">{stanza.poemLines.map((line,i)=><div key={i}>{line}</div>)}</div><div className="poem-simple-label">SIMPLE EXPLANATION</div><p className="poem-stanza-explanation">{stanza.explanation}</p><div className="poem-vocab-block"><div className="poem-simple-label">VOCABULARY</div><div className="poem-word-grid">{stanza.vocab.map(([word,meaning])=><div key={word}><b>{word}</b><span>{meaning}</span></div>)}</div></div><div className="poem-exam-box"><b>EXAM FOCUS</b><p>{stanza.exam}</p><div className="poem-stanza-key"><b>Memory key:</b> {stanza.key}</div></div></article>}

function Learn({onMode}){return <div className="poem-shell">
 <button className="poem-exit" onClick={()=>onMode('exit')}>← Exit Poetry</button>
 <section className="poem-hero"><span>THE PANORAMA • POETRY CHAPTER 2</span><h1>{poem.title}</h1><p>John Milton • Petrarchan sonnet • blindness, faith, service and patient acceptance</p></section>
 <section className="poem-panel poem-context"><div><div className="poem-section-label">CONTEXT</div><h2>Understanding the poem</h2><p>{poem.context}</p><p>{poem.structure}</p></div><div className="poem-fact-grid"><div><b>POET</b><span>{poem.poet}</span></div><div><b>FORM</b><span>Petrarchan sonnet</span></div><div><b>PARTS</b><span>Octave: 8 lines • Sestet: 6 lines</span></div><div><b>TURN</b><span>Patience answers the poet’s anxious question.</span></div></div></section>
 <section className="poem-panel"><div className="poem-section-heading"><div><div className="poem-section-label">STANZA-BY-STANZA</div><h2>Actual stanza → simple explanation → vocabulary</h2></div><span>2-part sonnet map</span></div><div className="poem-stanza-grid">{poem.stanzas.map(s=><StanzaCard key={s.range} stanza={s}/>)}</div></section>
 <section className="poem-panel"><div className="poem-section-label">POETRY TOOLKIT</div><h2>Form, structure and meaning</h2><div className="poem-tool-grid"><article><h3>Octave</h3><p>The first eight lines present Milton’s doubt, loss of eyesight and fear that his talent may remain unused.</p></article><article><h3>Sestet</h3><p>The final six lines provide Patience’s response and the poem’s consoling conclusion.</p></article><article><h3>Volta / turn</h3><p>The emotional argument turns when Patience answers the poet’s murmur.</p></article><article><h3>Central resolution</h3><p>God values faithful service; outward physical activity is not the only form of service.</p></article></div></section>
 <section className="poem-panel"><div className="poem-section-label">POETIC DEVICES</div><h2>What makes the poem powerful?</h2><div className="poem-device-grid">{poem.devices.map(([name,meaning])=><article key={name}><b>{name}</b><p>{meaning}</p></article>)}</div></section>
 <section className="poem-panel poem-two-col"><div><div className="poem-section-label">WORDS TO KNOW</div><h2>Quick vocabulary</h2><div className="poem-word-grid">{poem.words.map(([word,meaning])=><div key={word}><b>{word}</b><span>{meaning}</span></div>)}</div></div><div><div className="poem-section-label">THEMES</div><h2>Big ideas</h2><div className="poem-theme-list">{poem.themes.map(t=><span key={t}>{t}</span>)}</div><div className="poem-exam-box"><b>ONE-LINE REVISION</b><p>Milton learns that God does not demand the same visible work from every person; patient faith and readiness can also be service.</p></div></div></section>
 <section className="poem-panel"><div className="poem-section-label">TEXTBOOK QUICK ANSWERS</div><h2>Exam-ready answers</h2><div className="poem-answer-list">{poem.textbookAnswers.map(([q,a])=><article key={q}><b>{q}</b><p>{a}</p></article>)}</div></section>
 <section className="poem-panel"><div className="poem-section-label">TEXTBOOK EXTENSION</div><h2>Word Study • Grammar • Translation</h2><div className="poem-tool-grid"><article><h3>Word Study</h3><p>Practise corrected spellings and meaning pairs using the chapter vocabulary: sonnet, lessen, yoke, fear, education, and related glossary words.</p></article><article><h3>Conditional Clauses</h3><p>Use <b>if</b>, <b>unless</b>, <b>provided</b>, and <b>supposing</b> to express conditions. Example pattern: <b>If he comes, I shall help him.</b></p></article><article><h3>Advanced Conditionals</h3><p>Notice past/unreal patterns such as <b>Had I not seen this with my own eyes, I would not have believed it.</b> and relative/adverb patterns such as <b>Whatever happens, I must go.</b></p></article><article><h3>Translation Focus</h3><p>Translate conditional Hindi sentences into English while preserving tense and condition. Practise “यदि…” and “अगर…” with the chapter’s sentence patterns.</p></article></div></section>
 <section className="poem-modebar"><div><div className="poem-section-label">ASSESSMENT</div><h2>Test yourself</h2><p>15 Practice • 25 Challenge • 20 Final Test • shared timed engine</p></div><div className="poem-mode-buttons"><button onClick={()=>onMode('practice')}>Practice · 15</button><button onClick={()=>onMode('challenge')}>Challenge · 25</button><button className="primary" onClick={()=>onMode('test')}>Final Test · 20</button></div></section>
 </div>}

export function EnglishPanoramaPoem2({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode||'learn');
 useEffect(()=>{if(initialMode)setMode(initialMode)},[initialMode]);
 if(mode==='exit'){onBack();return null;}
 if(mode==='learn')return <Learn onMode={setMode}/>;
 const bank=mode==='practice'?practice:mode==='challenge'?challenge:finalTest;
 return <PanoramaTimedQuiz mode={mode} title={poem.title} bank={bank} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession}/>;
}

export default EnglishPanoramaPoem2;
