import {EnglishReaderEngine} from './EnglishReaderChapter.jsx';
const q=(q,o,a,e)=>({q,o,a,e});

const study={
 chapter:4,
 title:'The Eyes Are Not Here',
 subtitle:'Ruskin Bond • Supplementary Reader-IX',
 sourceNote:'Source: supplied English Reader PDF, Chapter 4, pp. 18–22. The lesson includes the story and its Let’s Answer, Let’s Discuss and Let’s Do exercises.',
 intro:'A blind narrator meets a girl in a train compartment. Their brief conversation is shaped by sound, memory and imagination, while both make assumptions about the other. The final revelation that the girl is also completely blind creates the story’s central irony and supports its idea that insight can be more important than eyesight.',
 sections:[
  {title:'The girl enters at Rohana',flow:'The narrator has the compartment to himself until Rohana. A girl then enters, apparently seen off by her parents, who give her safety instructions. The narrator cannot see her appearance, so he notices her voice and the sound of her slippers.',explanation:'Rohana तक narrator अकेला था। फिर एक लड़की आती है और उसके parents उसे सावधान रहने की बातें बताते हैं। Narrator उसकी appearance नहीं देख सकता, इसलिए उसकी आवाज़ और slippers की आवाज़ उसके लिए महत्वपूर्ण बनती है।',vocabulary:[['compartment','रेल का डिब्बा/कूपे'],['anxious','चिंतित'],['slippers','चप्पल'],['narrator','कहानी सुनाने वाला']],exam:'How does the narrator first notice the girl without seeing her?',think:'What does the absence of sight make the narrator notice instead?'},
  {title:'The narrator’s blindness',flow:'The narrator explains that he is totally blind and his eyes are sensitive only to light and darkness. He asks the girl whether she is going all the way to Dehra. His voice startles her because he has been sitting in a dark corner.',explanation:'Narrator बताता है कि वह पूरी तरह blind है और उसकी eyes केवल light और darkness के प्रति sensitive हैं। वह Dehra जाने के बारे में पूछता है। अँधेरे कोने में बैठे होने से उसकी आवाज़ लड़की को चौंका देती है।',vocabulary:[['totally blind','पूरी तरह दृष्टिहीन'],['sensitive','संवेदनशील'],['startled','अचानक चौंका हुआ'],['dark corner','अँधेरा कोना']],exam:'Remember why the narrator’s voice startles the girl.',think:'How does literal darkness prepare for the story’s later revelation?'},
  {title:'Saharanpur and Mussoorie',flow:'The girl says she will get down at Saharanpur, where her aunt will meet her. The narrator says he is going to Dehra and then Mussoorie. She loves the hills, especially in October, and the narrator responds from memory with details of the hills, wild dahlias, sunshine, a log fire and quiet roads.',explanation:'लड़की Saharanpur उतरने वाली है जहाँ उसकी aunt मिलेगी। Narrator Dehra और फिर Mussoorie जा रहा है। लड़की को October में hills पसंद हैं और narrator अपनी memory से वहाँ के प्राकृतिक वातावरण की कल्पना करता है।',vocabulary:[['hills','पहाड़ियाँ'],['wild dahlias','जंगली डहेलिया फूल'],['deserted','लगभग सुनसान'],['memories','स्मृतियाँ']],exam:'Explain how the talk about Mussoorie creates common ground between the two travellers.',think:'How does memory help the narrator take part in a visual conversation?'},
  {title:'The window question',flow:'The girl asks “What is it like?” and later asks why the narrator does not look out of the window. He suspects that she may have noticed that he cannot see. He moves to the window and pretends to study the landscape.',explanation:'लड़की Mussoorie के बारे में “What is it like?” पूछती है और फिर पूछती है कि narrator window से बाहर क्यों नहीं देखता। Narrator को डर लगता है कि शायद उसका blind होना समझ लिया गया है, इसलिए वह देखने का दिखावा करता है।',vocabulary:[['pretense','दिखावा'],['landscape','प्राकृतिक दृश्य'],['doubt','संदेह'],['pretend','दिखावा करना']],exam:'Why is the question about the window important?',think:'What is the narrator trying to hide?'},
  {title:'The mind’s eye and moving trees',flow:'At the window the narrator hears the engine and wheels. In his mind’s eye he imagines the telegraph-posts flashing past. He asks whether the trees seem to move while the passengers seem still. The girl says this always happens and asks about animals near Dehra.',explanation:'Narrator window पर जाकर engine और wheels की आवाज़ सुनता है। “Mind’s eye” में वह telegraph-posts को गुजरते हुए imagine करता है। वह trees और animals की बात करके अपनी visual limitation को छिपाए रखता है।',vocabulary:[['mind’s eye','कल्पना में देखने की क्षमता'],['telegraph-posts','टेलीग्राफ के खंभे'],['fascinating','आकर्षक'],['animals','जानवर']],exam:'Connect “mind’s eye” with the theme of insight.',think:'How can imagination replace direct sight in this scene?'},
  {title:'An interesting face and inner loneliness',flow:'The narrator says the girl has an interesting face. She laughs and says people usually tell her she has a pretty face. He says an interesting face can also be pretty. She calls him a gallant young man but asks why he is so serious. Though he tries to make her laugh, he still feels troubled and lonely.',explanation:'Narrator लड़की के face को interesting कहता है। लड़की हँसती है और बताती है कि लोग उसे pretty कहते हैं। वह उसे gallant young man कहती है, लेकिन narrator के भीतर loneliness बनी रहती है।',vocabulary:[['flattery','प्रशंसा'],['gallant','शिष्ट और प्रशंसात्मक'],['troubled','परेशान'],['lonely','अकेला']],exam:'Describe the contrast between the narrator’s playful remarks and inner loneliness.',think:'Why does conversation not fully remove his loneliness?'},
  {title:'The girl prepares to leave',flow:'The narrator wishes the journey could continue because he wants to keep listening to the girl. He wonders whether her hair is in a bun, plaited, loose or cut short. The train moves into the station, with porters, vendors and a high-pitched female voice that seems to belong to the girl’s aunt.',explanation:'लड़की के जाने का समय आता है और narrator चाहता है कि वह उससे सुनता रहे। वह उसके hair के बारे में कई कल्पनाएँ करता है। Station पर aunt जैसी high-pitched female voice सुनाई देती है।',vocabulary:[['brief encounter','संक्षिप्त मुलाकात'],['plaited','चोटी की हुई'],['high-pitched','ऊँची/तीखी आवाज़ वाला'],['vendors','विक्रेता']],exam:'What does the narrator wonder about the girl’s appearance?',think:'Why is hair important to him when he cannot actually see it?'},
  {title:'The final revelation',flow:'After the girl says good-bye, another man enters the compartment. The narrator asks whether the girl kept her hair long or short. The man says he remembers her eyes, not her hair, and then reveals that she was completely blind. The final fact overturns the narrator’s assumptions and makes the encounter ironic.',explanation:'लड़की के जाने के बाद दूसरा आदमी आता है। Narrator उसके hair के बारे में पूछता है, लेकिन वह कहता है कि उसने उसकी eyes notice की थीं और लड़की completely blind थी। इससे पता चलता है कि narrator और लड़की दोनों blind थे, फिर भी वे एक-दूसरे की वास्तविक स्थिति नहीं जान सके।',vocabulary:[['revelation','अचानक प्रकट हुआ सत्य'],['puzzled','हैरान/उलझन में'],['assumption','अनुमान'],['irony','अपेक्षा और वास्तविकता के बीच अर्थपूर्ण विरोध']],exam:'Why is the ending ironic?',think:'What did the narrator and the girl fail to realise about each other?'}
 ],
 glossary:[['insight','अंतर्दृष्टि/गहरी समझ'],['eyesight','दृष्टि'],['compartment','रेल का डिब्बा'],['narrator','कथावाचक'],['landscape','प्राकृतिक दृश्य'],['reverie','कल्पना में खोया भाव'],['fascinating','आकर्षक'],['gallant','शिष्ट और प्रशंसात्मक'],['encounter','मुलाकात'],['revelation','खुला हुआ सत्य'],['irony','विडंबना'],['assumption','अनुमान']],
 wordStudy:[['taken in','समझना/ध्यान देना'],['make a mistake','गलती करना'],['in my mind’s eye','कल्पना में देखना'],['break into my reverie','कल्पना से बाहर लाना'],['brief encounter','संक्षिप्त मुलाकात'],['appearance is deceptive','दिखावट से सही निष्कर्ष न निकलना']],
 textbookAnswers:[
  ['Why did the writer ask the man about the girl’s hair? What does the man reply? What hint does it throw on the similarity of the two?','The narrator asks because he wants to imagine the girl’s appearance. The man says he noticed her eyes, not her hair, and reveals that she was completely blind. The narrator and the girl are therefore similar in being blind, although neither realises it during the encounter.'],
  ['How will you describe the experience of the narrator: interesting, dull or instructive? Describe a similar experience of your own.','It is interesting and instructive because a brief conversation becomes meaningful through imagination and remaining senses, while the final revelation changes its meaning. A student may describe a personal experience in which a first impression proved incomplete.'],
  ['Describe the personality of the writer on the basis of the story.','The narrator appears observant, imaginative, humorous, self-aware and lonely. He uses conversation and memory creatively and tries to hide his blindness.'],
  ['Was the girl a lover of natural scenes and situations? Describe her behaviour highlighting what strikes you as odd.','Yes. She talks warmly about the hills, especially in October, and asks about trees and animals. Her interest in scenery becomes strikingly ironic because the story later reveals that she too was blind.'],
  ['Why were the girl’s beautiful eyes of no use to her? Attempt a character sketch of the girl.','Her eyes were of no use to her for ordinary sight because the story reveals that she was completely blind. She appears friendly, confident, conversational and interested in natural scenes.'],
  ['What light does the story throw on human behaviour?','The story suggests that people can rely on incomplete assumptions about appearance. It also shows the value of imagination, attention and conversation in forming human connections.']
 ],
 revision:[['Author','Ruskin Bond.'],['Opening point','A girl joins the narrator’s compartment after Rohana.'],['Narrator','Totally blind; relies on sound, memory and imagination.'],['Girl','Friendly, interested in hills and nature; later revealed to be blind.'],['Key device','Irony created by the shared blindness neither traveller recognises.'],['Central idea','Insight may be deeper than eyesight and appearance can mislead.']],
 discussion:['“Appearance is deceptive.” Discuss this statement with reference to the story.'],
 activities:['Do a project work on the problems and challenges faced by a physically challenged man.'],
 extra:'The supplied pages show Literature followed by A. Let’s Answer, B. Let’s Discuss and C. Let’s Do. No separate grammar exercise is shown, so none has been invented.'
};

const practice=[
 q('Who wrote “The Eyes Are Not Here”?',['Ruskin Bond','Najmul Hasan','Saint Kabir','R.K. Narayan'],0,'The chapter credits Ruskin Bond.'),
 q('What is the narrator unable to do?', ['See because he is blind','Hear the train','Speak to the girl','Travel to Dehra'],0,'The narrator says he is totally blind.'),
 q('Where does the girl say she will get down?', ['Saharanpur','Rohana','Dehra','Mussoorie'],0,'Her aunt is meeting her at Saharanpur.'),
 q('Where is the narrator going after Dehra?', ['Mussoorie','Saharanpur','Bombay','Delhi'],0,'He says he is going to Dehra and then Mussoorie.'),
 q('Which month does the girl especially like in the hills?', ['October','January','March','June'],0,'She says she loves the hills, especially in October.'),
 q('Which sense becomes especially important to the narrator?', ['Hearing','Taste','Smell of food','Touch of books'],0,'He notices the girl’s voice and slippers and hears the train sounds.'),
 q('What does the narrator imagine in his “mind’s eye”?', ['Telegraph-posts flashing by','A crowded market','A school building','A ship at sea'],0,'He imagines the telegraph-posts flashing past.'),
 q('What does the girl ask about the window?', ['Why don’t you look out of the window?','Can you close the window?','Is the window broken?','Who opened the window?'],0,'Her question makes the narrator worry about being discovered.'),
 q('What does the narrator call the girl’s face?', ['Interesting','Angry','Frightening','Boring'],0,'He calls it an interesting face.'),
 q('What does the girl call the narrator?', ['A gallant young man','A strict teacher','A railway guard','A careless traveller'],0,'She calls him a gallant young man.'),
 q('What does the narrator wonder about before she leaves?', ['Her hair','Her ticket number','Her shoes only','Her aunt’s job'],0,'He wonders whether her hair is long, plaited, loose or short.'),
 q('Who enters after the girl leaves?', ['Another man','Her aunt','Her parents','A porter'],0,'Another man enters the compartment.'),
 q('What does the narrator ask the man?', ['Whether the girl kept her hair long or short','Where the train will stop','Whether the girl likes Dehra','Why the train is late'],0,'He asks about her hair.'),
 q('What does the man say he noticed?', ['Her eyes','Her hair','Her slippers','Her dress'],0,'He says he noticed her eyes, not her hair.'),
 q('What final fact is revealed about the girl?', ['She was completely blind','She was a singer','She was the narrator’s relative','She had never travelled'],0,'The final reveal says she was completely blind.')
];

const challenge=[
 q('Why is the ending of the story especially ironic?', ['Both the narrator and the girl are blind, yet neither realises it during the encounter','The train never reaches a station','The narrator can secretly see everything','The girl refuses to speak'],0,'The shared blindness overturns the assumptions built during the conversation.'),
 q('What does the story’s phrase “insight is superior to eyesight” most strongly imply?', ['Understanding can depend on imagination, attention and other senses, not only physical sight','Sight has no value at all','Blind people cannot understand others','Appearance always gives the truth'],0,'The story values deeper perception rather than physical vision alone.'),
 q('Why does the narrator focus on the girl’s voice and slippers?', ['They give him clues about her presence when sight is unavailable','He dislikes silence','He wants to leave the compartment','He is studying shoes'],0,'His remaining senses become his main way of noticing her.'),
 q('What does “in my mind’s eye” reveal about the narrator?', ['He can create mental images from memory and imagination','He has recovered his eyesight','He is reading a book','He is looking through binoculars'],0,'The phrase describes imagined rather than physical seeing.'),
 q('Why does the narrator pretend to study the landscape?', ['He wants to hide his blindness and keep the conversation natural','He wants to impress the guard','He is searching for his luggage','He is trying to count stations'],0,'The pretence helps him avoid revealing that he cannot see.'),
 q('How does the discussion of Mussoorie help the plot?', ['It creates a shared conversational topic and prepares the irony of the final reveal','It explains the train timetable','It introduces the narrator’s profession','It proves the girl is from Mussoorie'],0,'The nature conversation builds connection while later becoming ironic.'),
 q('Why is the girl’s love of the hills significant after the final reveal?', ['Her visual interest in scenery becomes ironic because she is also blind','It proves she is the aunt','It shows she owns a hotel','It means she is a mountaineer'],0,'The revelation changes how the earlier scenery talk is read.'),
 q('What does the narrator’s hair question reveal about his character?', ['He is curious and imaginative about details he cannot see','He is uninterested in the girl','He already knows her appearance','He wants to frighten her'],0,'He creates possible images of her hair despite not being able to see it.'),
 q('Which contrast is central to the story?', ['Eyesight and insight','City and village','Youth and old age','School and home'],0,'The chapter frames sight against deeper perception.'),
 q('Why can the narrator still describe the journey as fascinating?', ['Guessing and imagining what is outside becomes a mental game','He has perfect visual access','The train provides a television','The girl gives him a map'],0,'He turns the absence of direct sight into a game of mental reconstruction.'),
 q('What does the narrator’s loneliness add to the conversation scenes?', ['It shows that pleasant talk does not remove his deeper sense of isolation','It proves he dislikes the girl','It makes the journey longer','It explains the railway route'],0,'His inner loneliness remains even while the conversation is enjoyable.'),
 q('Why is the man puzzled by the narrator’s hair question?', ['The man remembers the girl’s eyes rather than her hair and does not share the narrator’s assumption about seeing her','He does not know how hair works','He has never met the girl','He is the station master'],0,'His response exposes the narrator’s mistaken assumption.'),
 q('What common fact about the two travellers is hidden until the end?', ['Both are blind','Both are going to Mussoorie','Both are travelling with relatives','Both are writers'],0,'The final revelation shows they share blindness.'),
 q('How does sound function in the story?', ['It supplies information that sight would normally provide for the narrator','It is used only as background','It distracts the girl from the conversation','It identifies the aunt’s profession'],0,'Voice, slippers, engine and wheels help the narrator experience the journey.'),
 q('What is the importance of the narrator’s memory of Mussoorie?', ['It enables him to participate in a visual topic without actually seeing the scenery','It proves he is from Mussoorie','It shows he has a photographic memory','It gives the girl directions'],0,'Memory lets him create and describe an imagined landscape.'),
 q('Why is the story’s irony stronger than a simple surprise ending?', ['Earlier details about appearance, scenery and the window all gain a new meaning after the shared blindness is revealed','Nothing in the earlier story relates to the ending','The ending introduces a completely different setting','The narrator already knows the truth'],0,'The reveal changes the interpretation of many earlier details.'),
 q('What does the girl’s friendly behaviour show before the reveal?', ['She is confident, conversational and comfortable discussing nature','She wants to avoid all contact','She is angry with the narrator','She is trying to catch a thief'],0,'She engages naturally and talks about hills, trees and animals.'),
 q('Why does the narrator call the girl’s face “interesting”?', ['It lets him respond without pretending to know her exact appearance','He has studied her photograph','He dislikes the word pretty','He wants to insult her'],0,'He cannot actually see her face, so “interesting” is safer than a visual description.'),
 q('What does the story suggest about first impressions?', ['They may be built from incomplete clues and can be misleading','They are always accurate','They do not matter in human relationships','They depend only on clothing'],0,'The final revelation exposes the limits of the narrator’s assumptions.'),
 q('Why does the narrator wish the journey could continue?', ['He enjoys listening to the girl and knows the brief encounter is about to end','He has missed Dehra','He wants to meet the aunt','He is afraid of stations'],0,'He says he is prepared to sit for almost any length of time just to listen to her.'),
 q('How does the final man function in the story’s structure?', ['His reply supplies the missing information that completes the irony','He changes the train route','He gives the narrator a job','He explains the weather'],0,'His observation about the girl’s eyes creates the final revelation.'),
 q('What does the phrase “appearance is deceptive” mean in this story?', ['Outward assumptions about a person can hide an important truth','Physical appearance always reveals character','Hair is more important than eyes','Travel conversations are meaningless'],0,'The narrator constructs an image that is overturned by the girl’s blindness.'),
 q('What is the best explanation of the narrator’s self-consciousness?', ['He wants to hide his blindness so the girl will not treat the conversation differently','He wants to hide his ticket','He fears the train guard','He dislikes speaking'],0,'His actions at the window show an effort to conceal his blindness.'),
 q('Why is the girl’s question about animals useful to the story?', ['It extends the nature conversation and helps maintain the appearance that both can discuss scenery normally','It identifies the narrator’s hometown','It introduces a new animal character','It explains the station timetable'],0,'The question keeps the conversation focused on the outside world while the irony develops.'),
 q('Which quality best describes the narrator’s method of knowing the world?', ['Observation through remaining senses plus imagination','Complete dependence on strangers','Indifference to his surroundings','Pure guesswork without memory'],0,'He listens carefully and combines sensory information with memory and imagination.'),
 q('What is the most defensible lesson about human behaviour from the chapter?', ['People should question assumptions and look beyond appearances when understanding others','People should never talk to strangers','Physical beauty determines personality','Only eyesight creates knowledge'],0,'The final reveal encourages a deeper view of how people interpret one another.'),
 q('Why is the short encounter emotionally significant to the narrator?', ['The girl’s voice and conversation stay with him beyond the brief journey','She gives him money','She changes his destination','She becomes his relative'],0,'He says the encounter will remain with him for some time after she leaves.'),
 q('How do memory, imagination and sound work together?', ['They allow the narrator to build a meaningful experience despite blindness','They prove he can actually see','They prevent him from speaking','They make the girl leave early'],0,'These are the main tools through which he experiences and interprets the journey.')
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`final-${i}`}));

export function EnglishReaderChapter4({initialMode='learn',onBack,addXp,finishSession}){
 return <EnglishReaderEngine study={study} initialMode={initialMode} onBack={onBack} addXp={addXp} finishSession={finishSession}/>;
}
export const englishReaderChapter4Meta={title:study.title,author:'Ruskin Bond',sourceNote:study.sourceNote,modeCounts:{practice:practice.length,challenge:challenge.length,final:finalTest.length}};
export {study as englishReaderChapter4Study};
