import React,{useMemo,useState,useEffect}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishTranslationTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Translation means meaning first',simple:'Hindi → English translation is not word-for-word copying. First understand the message, time, person and action; then build a natural English sentence.',hindi:'पहले पूरा अर्थ समझो, फिर English sentence बनाओ। Hindi के हर शब्द को उसी order में बदलना जरूरी नहीं है।',meaning:'Good translation preserves meaning while producing correct, natural English.',structure:'meaning → sentence pattern → word forms → final check',examples:['मैं रोज़ पढ़ता हूँ। → I study every day.','वह अभी पढ़ रही है। → She is studying now.'],clue:'Before choosing a verb form, ask what the Hindi sentence actually means.'},
{n:'02',group:'METHOD',title:'The 8-step translation method',simple:'Use a repeatable process: identify subject, time, action type, auxiliary, verb form, object/complement, small words, then audit the full sentence.',hindi:'8 steps याद रखो: Subject → Time → Action → Auxiliary → Verb form → Object → Articles/Prepositions → Final audit.',meaning:'A fixed process reduces avoidable grammar mistakes.',structure:'1 subject → 2 time → 3 action → 4 auxiliary → 5 verb → 6 object → 7 small words → 8 audit',examples:['वे दो घंटे से पढ़ रहे हैं। → subject: they; duration: two hours; action ongoing.','मैं कल बाजार गया। → past reference: yesterday; simple past: went.'],clue:'Do not change the verb before deciding the tense.'},
{n:'03',group:'TENSE',title:'Simple Present in translation',simple:'Use Simple Present for habits, routines, repeated actions, general truths and many regular facts. Watch third-person singular forms.',hindi:'“रोज़, हमेशा, अक्सर, प्रत्येक दिन” जैसे clues habit/routine दिखाते हैं। He/She/It के साथ verb पर s/es याद रखो।',meaning:'Habitual or general meaning usually maps to the Simple Present.',structure:'I/You/We/They + V1 | He/She/It + V1(s/es)',examples:['वह रोज़ स्कूल जाता है। → He goes to school every day.','सूरज पूर्व में उगता है। → The sun rises in the east.'],clue:'After does/does not, return to the base verb: Does he go? not Does he goes?'},
{n:'04',group:'TENSE',title:'Present Continuous',simple:'Present Continuous usually expresses an action happening now or around the present moment. Hindi forms such as “रहा है / रही है / रहे हैं” often provide the clue.',hindi:'“अभी… रहा है/रही है/रहे हैं” दिखे तो am/is/are + V-ing को check करो।',meaning:'The key idea is an action in progress.',structure:'S + am/is/are + V-ing',examples:['मैं अभी लिख रहा हूँ। → I am writing now.','वे खेल रहे हैं। → They are playing.'],clue:'Choose the subject-linked auxiliary correctly: I am, he/she is, we/they are.'},
{n:'05',group:'TENSE',title:'Present Perfect',simple:'Present Perfect is used for completed actions connected with the present or an unfinished time period. It uses has/have + V3.',hindi:'“कर लिया है / हो चुका है” जैसे contexts में present result/relevance हो सकती है। Finished definite time जैसे “yesterday” के साथ इसे बिना reason के मत लगाओ।',meaning:'The form connects a past action to the present context.',structure:'S + has/have + V3',examples:['मैं अपना काम कर चुका हूँ। → I have finished my work.','उसने खाना खा लिया है। → She has eaten the food.'],clue:'Present Perfect is not simply “any past action”; the present connection matters.'},
{n:'06',group:'TENSE',title:'Present Perfect Continuous + since/for',simple:'Use Present Perfect Continuous when an activity continues up to now and duration matters. Since gives a starting point; for gives a duration.',hindi:'“से… कर रहा हूँ” में since/for की जरूरत समझो: Monday से = since Monday; two hours से = for two hours.',meaning:'The form focuses on activity plus duration up to the present.',structure:'S + has/have been + V-ing + since/for',examples:['मैं दो घंटे से पढ़ रहा हूँ। → I have been studying for two hours.','वह सुबह से काम कर रही है। → She has been working since morning.'],clue:'Since = starting point; for = length of time.'},
{n:'07',group:'TENSE',title:'Simple Past',simple:'Use Simple Past for completed past events, especially with finished time references such as yesterday, last week and ago.',hindi:'“कल, पिछले साल, दो दिन पहले” जैसे finished past clues अक्सर V2 मांगते हैं।',meaning:'Completed past events are normally expressed with the simple past.',structure:'S + V2',examples:['मैंने उसे कल देखा। → I saw him yesterday.','वे पिछले सप्ताह पटना गए। → They went to Patna last week.'],clue:'After did/did not, use V1: Did you go? not Did you went?'},
{n:'08',group:'METHOD',title:'Questions and negatives',simple:'In translation, first identify the auxiliary pattern. Do/does/did, am/is/are, has/have and will each control the verb form that follows.',hindi:'Question या negative में auxiliary पहचानो। उसी के हिसाब से main verb का सही form चुनो।',meaning:'Auxiliaries carry tense and structure information.',structure:'Do/Does/Did + V1 | be + V-ing | have/has + V3 | will + V1',examples:['वह नहीं खेलता है। → He does not play.','क्या तुम गए? → Did you go?','क्या वह पढ़ रही है? → Is she studying?'],clue:'Never add the tense ending twice: does not plays, did not went are wrong.'},
{n:'09',group:'METHOD',title:'Articles: a, an, the',simple:'Hindi often omits articles, so English translation requires an extra decision. Use a/an for many singular countable nouns when non-specific; use the for a specific or known referent.',hindi:'Hindi में article अक्सर नहीं दिखता। English में singular countable noun के साथ context देखकर a/an/the की जरूरत check करो।',meaning:'Articles encode definiteness and countability that Hindi may express differently or not at all.',structure:'a/an + singular countable non-specific noun | the + specific/known noun',examples:['मेरे पास एक किताब है। → I have a book.','दरवाज़ा बंद करो। → Close the door.'],clue:'Choose an by sound: an hour, an honest person.'},
{n:'10',group:'METHOD',title:'Prepositions and fixed patterns',simple:'Directly replacing Hindi postpositions can create unnatural English. Learn common English patterns for time, place and verb/adjective combinations.',hindi:'Hindi के “में, पर, से, को” का एक ही fixed English word नहीं होता। Context और English pattern देखो।',meaning:'Prepositions depend on the relationship and the English collocation.',structure:'at + precise time | on + day/date | in + month/year | adjective/verb + fixed preposition',examples:['सोमवार को → on Monday','2012 में → in 2012','वह गणित में अच्छा है। → He is good at mathematics.'],clue:'Memorise useful patterns as chunks: interested in, good at, depend on, listen to.'},
{n:'11',group:'WORD ORDER',title:'Hindi order vs English order',simple:'Hindi commonly places the verb later, while basic English often uses Subject + Verb + Object. Rebuild the sentence rather than translating position by position.',hindi:'Hindi का S–O–V order देखकर English में भी verb end में मत रखो। Basic English में S–V–O check करो।',meaning:'Translation requires English sentence order, not Hindi word order.',structure:'Hindi meaning → English S + V + O/complement',examples:['राम किताब पढ़ता है। → Ram reads a book.','मैं पानी पी रहा हूँ। → I am drinking water.'],clue:'The English verb normally belongs in the sentence pattern, not wherever the Hindi verb appears.'},
{n:'12',group:'WORD FORMS',title:'Pronouns and agreement',simple:'Choose English pronouns carefully and make the finite verb agree with the subject. Hindi context can leave the exact English pronoun implicit.',hindi:'मैं/हम/वह/वे का English pronoun context से तय करो और फिर verb agreement check करो।',meaning:'Correct person and number are essential to grammatical translation.',structure:'subject pronoun → agreement → verb form',examples:['वह रोज़ पढ़ती है। → She studies every day.','वे तैयार हैं। → They are ready.'],clue:'Do not choose he/she from habit alone; use the context of the sentence.'},
{n:'13',group:'ASPECT',title:'Habit vs action vs completion vs duration',simple:'Several Hindi sentences can use forms that look similar to learners but express different English meanings. Decide whether the action is habitual, in progress, completed, or continuing for a duration.',hindi:'एक ही verb की चार forms को meaning से compare करो: habit, now/in progress, completed result, duration.',meaning:'Meaning—not one Hindi suffix alone—selects the English aspect.',structure:'habit → simple | in progress → continuous | present result → perfect | duration → perfect continuous',examples:['वह पढ़ता है। → He studies.','वह पढ़ रहा है। → He is studying.','उसने पढ़ लिया है। → He has studied.','वह दो घंटे से पढ़ रहा है। → He has been studying for two hours.'],clue:'Translate the whole situation, not just the final verb word.'},
{n:'14',group:'COMPARISON',title:'Past and future contrasts',simple:'Use meaning and time reference to distinguish Simple Past, Past Continuous, Past Perfect and Future forms. Future meaning may also be expressed with be going to or Present Continuous in suitable contexts.',hindi:'Past में event complete था या किसी दूसरे past event के समय चल रहा था? Future में plan, arrangement या prediction क्या है?',meaning:'Time relationships determine the most natural tense/aspect.',structure:'past event | past background | earlier past | future plan/prediction',examples:['जब तुम आए, मैं पढ़ रहा था। → I was studying when you came.','हम पहुँचे तो ट्रेन जा चुकी थी। → The train had left before we arrived.','मैं कल तुमसे मिलूँगा। → I will meet you tomorrow.'],clue:'Look for a reference point when choosing perfect or continuous forms.'},
{n:'15',group:'MIXED',title:'Modals and auxiliaries in translation',simple:'Translate ability, permission, advice, possibility and obligation with the appropriate modal. Modals take the base verb.',hindi:'सकता है = can, चाहिए = should, शायद = may/might, करना होगा = must/have to जैसे meanings को context से चुनो।',meaning:'Modal choice depends on the force of the Hindi meaning.',structure:'modal + V1',examples:['तुम्हें मेहनत करनी चाहिए। → You should work hard.','वह तैर सकता है। → He can swim.','शायद वह आए। → He might come.'],clue:'Do not use a modal + to + V1 unless the construction specifically requires it.'},
{n:'16',group:'COMPLEX SENTENCES',title:'Connectors: because, although, when, if',simple:'Hindi clauses must be mapped to the correct English relationship. Identify reason, contrast, time or condition before choosing a connector.',hindi:'पहले relationship पहचानो: कारण = because, contrast = although/however, time = when/after/before, condition = if/unless.',meaning:'The connector should represent the actual logical relationship between clauses.',structure:'relationship → connector → clause grammar',examples:['बारिश हुई इसलिए हम रुके। → We stopped because it rained.','जब वह आया, मैं पढ़ रहा था। → I was studying when he arrived.','अगर बारिश होगी, हम घर पर रहेंगे। → If it rains, we will stay at home.'],clue:'Do not choose connectors only by memorised one-word translations.'},
{n:'17',group:'ADVANCED',title:'Natural English vs literal English',simple:'A grammatically possible translation can still sound unnatural. Prefer standard English expressions and collocations when they convey the same meaning.',hindi:'Word-to-word translation कई बार awkward हो जाती है। Natural English phrase चुनो, लेकिन मूल meaning न बदलो।',meaning:'Accuracy includes natural expression, not only word matching.',structure:'literal draft → meaning check → natural English revision',examples:['मुझे ठंड लग रही है। → I am feeling cold.','उसे देर हो गई। → He got late. (context may call for “He got delayed” or “He was late.”)'],clue:'Ask: “Would an English speaker naturally say this?” while preserving the original sense.'},
{n:'18',group:'EXAM CONTROL',title:'Translation audit and scoring strategy',simple:'Before finalising, check meaning, tense, subject–verb agreement, verb form, articles, prepositions, word order, spelling and punctuation.',hindi:'Final audit: Meaning ✓ Tense ✓ Subject ✓ Verb form ✓ Article ✓ Preposition ✓ Word order ✓ Spelling ✓ Punctuation.',meaning:'A systematic audit catches small errors after the main translation is complete.',structure:'meaning → tense → grammar → word order → small words → spelling',examples:['Wrong: He did not went.','Correct: He did not go.','Wrong: She is go.','Correct: She is going.'],clue:'Do a final read from the beginning; do not check only the last verb.'}
];

const MODELS=[
['Routine','मैं रोज़ सुबह जल्दी उठता हूँ।','I get up early every morning.','habit → Simple Present → routine time phrase'],
['Action Now','मैं अभी अपना होमवर्क कर रहा हूँ।','I am doing my homework now.','action in progress → Present Continuous'],
['Present Result','उसने अपना काम पूरा कर लिया है।','She has completed her work.','completed action with present relevance → Present Perfect'],
['Duration','वे दो घंटे से इंतज़ार कर रहे हैं।','They have been waiting for two hours.','duration up to now → Present Perfect Continuous'],
['Past Event','मैंने उसे कल बाजार में देखा।','I saw him in the market yesterday.','finished definite past → Simple Past'],
['Past Background','जब शिक्षक आए, छात्र लिख रहे थे।','When the teacher arrived, the students were writing.','background action + interrupting event → Past Continuous + Simple Past'],
['Condition','अगर बारिश होगी, हम घर पर रहेंगे।','If it rains, we will stay at home.','condition → present simple in if-clause + future result'],
['Advice','तुम्हें परीक्षा से पहले अपने उत्तर जाँचने चाहिए।','You should check your answers before the examination.','advice → should + base verb']
];

const TRAPS=['Word-for-word translation that changes the natural English order.','Wrong auxiliary + verb form: did went, does plays, will goes.','Ignoring articles because Hindi often does not show them.','Using a preposition only because it is the nearest dictionary equivalent.','Confusing habit, ongoing action, completed result and duration.','Changing tense without checking the time reference.','Adding or removing meaning to make a sentence sound more dramatic.','Skipping the final audit for spelling, agreement and punctuation.'];
const TASKS=['Translate: मैं रोज़ शाम को पुस्तकालय जाता हूँ।','Translate: वह अभी अपनी बहन से बात कर रही है।','Translate: मैंने अपना प्रोजेक्ट पूरा कर लिया है।','Translate: वे सुबह से मैदान में अभ्यास कर रहे हैं।','Translate: जब मैं पहुँचा, बस जा चुकी थी।','Translate: अगर तुम मेहनत करोगे, तुम सफल हो जाओगे।','Translate: तुम्हें अपने शिक्षक की बात ध्यान से सुननी चाहिए।','Translate: बारिश के कारण हम देर से पहुँचे।'];

const BANKS={practice:[
['“मैं रोज़ पढ़ता हूँ।”',['I study every day.','I am study every day.','I studied every day now.','I will studied every day.'],0,'“रोज़” shows a habitual action, so Simple Present fits.'],
['“वह अभी खाना खा रही है।”',['She is eating food now.','She eats food now.','She has eat food now.','She eating food now.'],0,'“अभी…रही है” signals an action in progress.'],
['“मैंने उसे कल देखा।”',['I saw him yesterday.','I have seen him yesterday.','I see him yesterday.','I was see him yesterday.'],0,'“कल” here is a finished past time, so Simple Past is used.'],
['“मैं दो घंटे से पढ़ रहा हूँ।”',['I have been studying for two hours.','I am studying since two hours.','I studied for two hours now.','I have studied since two hours.'],0,'Duration continuing up to now calls for Present Perfect Continuous.'],
['After “does not” the main verb should be…',['V1/base form','V2','V3','V-ing only'],0,'Does not takes the base verb: does not play.'],
['Which is correct?',['Did you go there?','Did you went there?','Did you gone there?','Did you going there?'],0,'Did already carries the past tense, so the main verb returns to V1.'],
['“एक घंटा” as a duration is normally expressed with…',['for an hour','since an hour','at an hour','on an hour'],0,'For introduces duration.'],
['“सोमवार को” is normally…',['on Monday','in Monday','at Monday','to Monday'],0,'On is used with days and dates.'],
['Which needs an article?',['I have a book.','I have books.','Books are useful.','Water is important.'],0,'A is used with a singular countable noun when non-specific.'],
['Basic English word order is commonly…',['Subject + Verb + Object','Object + Subject + Verb','Verb + Object + Subject','Object + Verb + Subject'],0,'English basic clause order is commonly SVO.'],
['“वह गणित में अच्छा है।”',['He is good at mathematics.','He is good in mathematics.','He good at mathematics.','He is good to mathematics.'],0,'Good at is the standard collocation here.'],
['“तुम्हें मेहनत करनी चाहिए।”',['You should work hard.','You should to work hard.','You should working hard.','You should worked hard.'],0,'A central modal is followed by the base verb.'],
['Which sentence shows a reason?',['We stayed inside because it rained.','We stayed inside although it rained.','We stayed inside if it rained.','We stayed inside when it rained every reason.'],0,'Because introduces a reason.'],
['Which is the natural translation of “सूरज पूर्व में उगता है।”',['The sun rises in the east.','The sun is rising in the east every day now.','The sun rose in the east yesterday.','The sun will rise in the east yesterday.'],0,'It is a general truth, so Simple Present fits.'],
['“शायद वह कल आए।”',['He might come tomorrow.','He might to come tomorrow.','He comes might tomorrow.','He might came tomorrow.'],0,'Might + base verb expresses possibility.'],
['Which is correct for a specific known object?',['Close the door.','Close a door.','Close door the.','Close an door.'],0,'The is used when the referent is specific/known in context.'],
['Which shows an earlier past action?',['The train had left before we arrived.','The train has left before we arrived.','The train leaves before we arrived.','The train will leave before we arrived.'],0,'Past Perfect marks the earlier of two past references.'],
['Which is correct?',['She is reading now.','She is read now.','She reading now.','She does reading now.'],0,'Present Continuous uses is + V-ing.'],
['The best first step in translation is to…',['understand the complete meaning','translate the first word','choose an article','add -s to a verb'],0,'Meaning comes before word-by-word conversion.'],
['Final translation checking should include…',['tense, agreement, word order, small words and spelling','only the last word','only punctuation','only the title'],0,'A whole-sentence audit catches multiple error types.']
],challenge:[
['Which translation best preserves habit?',['वह हर रविवार तैरता है। → He swims every Sunday.','He is swimming every Sunday now.','He swam every Sunday yesterday.','He has swim every Sunday.'],0,'Every Sunday indicates a repeated habit.'],
['Which sentence best translates an action in progress at a past moment?',['जब मैं पहुँचा, वह सो रही थी। → When I arrived, she was sleeping.','When I arrived, she slept now.','When I arrived, she has slept.','When I arrived, she is sleep.'],0,'Past Continuous gives the background action.'],
['Which translation correctly expresses present result?',['उसने दरवाज़ा बंद कर दिया है। → She has closed the door.','She closed the door yesterday has.','She is close the door.','She had close the door now.'],0,'Has + V3 connects a completed action with the present context.'],
['Which is the best translation?',['वे सुबह से काम कर रहे हैं। → They have been working since morning.','They are working since morning.','They have working for morning.','They worked since morning now.'],0,'Since gives the starting point and perfect continuous shows ongoing duration.'],
['Which sentence correctly uses “did”?',['Did he finish the work?','Did he finished the work?','Did he finishing the work?','Did he has finished the work?'],0,'Did + V1 is the standard question pattern.'],
['Which article choice is best?',['She bought an umbrella.','She bought a umbrella.','She bought umbrella an.','She bought the umbrella when no specific umbrella exists.'],0,'Umbrella begins with a vowel sound, so an is appropriate for a non-specific singular count noun.'],
['Which preposition fits? “He was born ___ 2012.”',['in','on','at','to'],0,'In is used with years.'],
['Which translation best matches a condition?',['अगर वह आएगा, मैं उससे मिलूँगा। → If he comes, I will meet him.','If he will come, I will meet him.','If he came, I will meet him tomorrow.','If he comes, I met him.'],0,'In a standard first conditional, the if-clause uses present simple and the result uses will.'],
['Which sentence is more natural English?',['I was late because the bus was delayed.','I late became because bus delayed.','I was late by the bus delayed.','Because late I bus was.'],0,'Natural translation rebuilds the Hindi meaning into English syntax.'],
['Which best translates “हालाँकि बारिश हो रही थी, हम बाहर गए।”',['Although it was raining, we went outside.','Because it was raining, we went outside.','If it was raining, we went outside.','When it was raining, but we went outside.'],0,'Although marks contrast.'],
['Which sentence shows advice rather than obligation?',['You should revise your answers.','You must revise your answers.','You can revise your answers.','You might revise your answers.'],0,'Should normally expresses advice.'],
['Which is the best translation of “वह अब तक नहीं आया है।”',['He has not arrived yet.','He did not arrived yet.','He is not arrive yet.','He has not arrive yesterday.'],0,'Has not + V3 with yet expresses an unfinished situation up to now.'],
['Which sentence correctly translates a fixed future arrangement?',['We are meeting the teacher tomorrow.','We are meet the teacher tomorrow.','We met the teacher tomorrow.','We are meeting the teacher yesterday.'],0,'Present Continuous can express a fixed arrangement.'],
['Which translation best preserves two past time points?',['जब हम पहुँचे, ट्रेन जा चुकी थी। → When we arrived, the train had left.','When we arrive, the train had left.','When we arrived, the train has left.','When we arrived, the train leaves.'],0,'The earlier past action takes Past Perfect.'],
['Which is grammatically correct?',['He does not understand the question.','He does not understands the question.','He do not understand the question.','He not does understand the question.'],0,'Does not takes the base form understand.'],
['Which translation correctly handles pronoun and agreement?',['वह रोज़ किताब पढ़ती है। → She reads a book every day.','She read a book every day now.','She reads a book yesterday.','He reads a book every day.'],0,'She requires reads in Simple Present and the context indicates a female subject.'],
['Which sentence best translates a cause?',['बारिश के कारण मैच रद्द हो गया। → The match was cancelled because of the rain.','The match was cancelled although the rain.','The match was cancelled if the rain.','The match cancelled the rain.'],0,'Because of + noun phrase expresses cause naturally.'],
['Which is the better translation of “मुझे ठंड लग रही है।”',['I am feeling cold.','I am colding.','I feel to cold.','Cold is happening to me.'],0,'English uses a natural expression rather than translating the Hindi structure literally.'],
['Which translation best matches possibility?',['शायद वह देर से आए। → He may arrive late.','He must arrive late for possibility.','He should to arrive late.','He may arrived late.'],0,'May + base verb expresses possibility.'],
['A translation is correct in tense but awkward in word order. The best fix is to…',['rebuild the sentence in natural English while preserving meaning','move every word into Hindi order','add difficult vocabulary','change the tense randomly'],0,'Translation requires both grammatical accuracy and natural English.']
],test:[
['Translate: “मैं रोज़ समय पर स्कूल जाता हूँ।”',['I go to school on time every day.','I am go to school every day.','I went to school tomorrow.','I have go to school every day.'],0,'The sentence expresses a routine, so Simple Present is appropriate.'],
['Translate: “वह अभी पत्र लिख रही है।”',['She is writing a letter now.','She writes a letter now.','She is write a letter now.','She has writing a letter now.'],0,'“अभी…रही है” expresses an ongoing present action.'],
['Translate: “हमने अपना काम पूरा कर लिया है।”',['We have completed our work.','We completed our work yesterday has.','We are completed our work.','We have complete our work.'],0,'Present Perfect uses have + V3.'],
['Translate: “वह तीन घंटे से पढ़ रहा है।”',['He has been studying for three hours.','He is studying since three hours.','He studied for three hours now.','He has been study three hours.'],0,'The action continues with duration up to now.'],
['Translate: “मैंने उसे पिछले रविवार देखा।”',['I saw him last Sunday.','I have seen him last Sunday.','I see him last Sunday.','I was see him last Sunday.'],0,'A finished definite past time calls for Simple Past.'],
['Translate: “जब तुम आए, मैं सो रहा था।”',['When you came, I was sleeping.','When you came, I slept now.','When you come, I was sleeping.','When you came, I am sleeping.'],0,'The background action is Past Continuous; the arriving event is Simple Past.'],
['Translate: “हम पहुँचने से पहले ट्रेन जा चुकी थी।”',['The train had left before we arrived.','The train has left before we arrived.','The train left before we arrive.','The train had leave before we arrived.'],0,'Past Perfect marks the earlier past event.'],
['Translate: “मैं कल तुम्हारी मदद करूँगा।”',['I will help you tomorrow.','I will helped you tomorrow.','I am help you tomorrow.','I helped you tomorrow.'],0,'Will takes the base verb and expresses future action.'],
['Translate: “वह सोमवार को शिक्षक से मिल रही है।”',['She is meeting the teacher on Monday.','She is meet the teacher on Monday.','She met the teacher next Monday.','She meets the teacher now Monday.'],0,'Present Continuous can express a fixed future arrangement.'],
['Which is the correct translation of “तुम्हें रोज़ अभ्यास करना चाहिए।”',['You should practise every day.','You should to practise every day.','You should practised every day.','You should practising every day.'],0,'Should + base verb is used for advice.'],
['Translate: “शायद वह आज नहीं आएगा।”',['He may not come today.','He may not comes today.','He does may not come today.','He may not came today.'],0,'May not + base verb expresses possibility.'],
['Translate: “अगर बारिश होगी, हम नहीं जाएँगे।”',['If it rains, we will not go.','If it will rain, we will not go.','If it rains, we do not went.','If it rained, we will not goes.'],0,'The standard conditional uses present simple in the if-clause and will in the result.'],
['Translate: “हालाँकि वह थका था, उसने काम पूरा किया।”',['Although he was tired, he completed the work.','Because he was tired, he completed the work.','If he was tired, he completed the work.','Although tired he was, completed work the.'],0,'Although expresses contrast.'],
['Translate: “वह गणित में अच्छा है।”',['He is good at mathematics.','He is good in mathematics.','He good at mathematics.','He is good to mathematics.'],0,'Good at is the standard prepositional collocation.'],
['Which article is best? “उसने ___ छाता खरीदा।”',['She bought an umbrella.','She bought a umbrella.','She bought umbrella.','She bought an umbrellas.'],0,'An is used before a singular countable noun beginning with a vowel sound.'],
['Translate: “मेरे पास एक पुराना बैग है।”',['I have an old bag.','I have a old bag.','I have the old bag when it is not specific.','I have old a bag.'],0,'An is used before old because it begins with a vowel sound.'],
['Translate: “वे सुबह से इंतज़ार कर रहे हैं।”',['They have been waiting since morning.','They are waiting since morning.','They have waiting from morning.','They waited since morning now.'],0,'Since gives the starting point, and the activity continues to now.'],
['Translate: “दरवाज़ा बंद करो।”',['Close the door.','Close a door always.','Close door the.','Closed the door.'],0,'The referent is treated as specific in this ordinary instruction.'],
['Which translation keeps the Hindi meaning but uses natural English?',['मुझे ठंड लग रही है। → I am feeling cold.','I am becoming cold-feeling.','Cold is coming on me.','I am doing cold.'],0,'Natural English does not copy Hindi structure word-for-word.'],
['Which is the best final translation audit?',['meaning → tense → agreement → verb form → articles/prepositions → word order → spelling','only check the first word','only count nouns','only choose a longer synonym'],0,'The audit should cover both meaning and language mechanics.'],
['Which error is present in “He does not goes to school”?',['double tense marking after does not','wrong article only','wrong preposition only','wrong noun only'],0,'Does already carries the present auxiliary, so the main verb must be go.'],
['Which sentence is correct?',['She has finished her homework.','She has finish her homework.','She have finished her homework.','She has finishing her homework.'],0,'Has + V3 is the correct Present Perfect pattern.'],
['Which sentence correctly uses “for”?',['They have been studying for two hours.','They have been studying since two hours.','They studied for Monday.','They are studying for 2012.'],0,'For introduces duration.'],
['Which sentence correctly uses “since”?',['She has been working since morning.','She has been working since two hours.','She worked since Monday yesterday.','She is working since 2012.'],0,'Since introduces a starting point.'],
['Which principle best defines exam-ready translation?',['Preserve the meaning, choose the right English structure, and audit grammar carefully.','Translate every word in the Hindi order.','Use the hardest possible words.','Change the meaning to sound impressive.'],0,'Strong translation is accurate, grammatical, natural and task-focused.']
]};

const rotate=(questions,mode)=>{const shift=mode==='challenge'?1:mode==='test'?2:0;return questions.map((item,i)=>{const[q,opts,a,e]=item;const next=[...opts];const move=(a+shift+i)%next.length;const correct=next[a];next.splice(a,1);next.splice(move,0,correct);return[q,next,move,e]})};
const readMode=()=>{if(typeof window==='undefined')return'practice';const m=new URLSearchParams(window.location.search).get('mode');return['practice','challenge','test'].includes(m)?m:'practice'};
const nextMode=m=>m==='practice'?'challenge':m==='challenge'?'test':'practice';

export default function EnglishTranslationTopic({onBack=()=>{},addXp=()=>{},finishSession=()=>{}}){
 const[mode,setMode]=useState(readMode);const[lesson,setLesson]=useState(0);
 useEffect(()=>{const sync=()=>setMode(readMode());window.addEventListener('popstate',sync);sync();return()=>window.removeEventListener('popstate',sync)},[]);
 const bank=useMemo(()=>rotate(BANKS[mode]||BANKS.practice,mode),[mode]);
 const go=m=>{const p=new URLSearchParams(window.location.search);p.set('subject','english');p.set('languageSkills','1');p.set('topic','translation');if(m==='learn')p.delete('mode');else p.set('mode',m);window.history.pushState({},'',`${window.location.pathname}?${p}`);window.dispatchEvent(new PopStateEvent('popstate'))};
 const current=LESSONS[lesson];
 const assessment=['practice','challenge','test'].includes(mode)&&new URLSearchParams(window.location.search).get('mode')===mode;
 if(assessment)return <EnglishTimedQuiz title="Translation: Hindi → English" mode={mode} getBank={()=>bank} onModeChange={go} onBack={()=>go('learn')} addXp={addXp} finishSession={finishSession} onNextLevel={()=>go(nextMode(mode))} secondsPerQuestion={mode==='test'?55:50}/>;
 return <main className="et-shell">
 <header className="et-hero"><div><button type="button" className="et-back" onClick={onBack}>← Language</button><span className="et-kicker">ENGLISH • LANGUAGE • TRANSLATION</span><h1>Translation: Hindi → English</h1><p>Build accurate, natural English from Hindi meaning, structure and context.</p></div><div className="et-stat"><strong>{LESSONS.length}</strong><span>guided lessons</span></div></header>
 <nav className="et-modebar"><button className="active" type="button">Learn</button><button type="button" onClick={()=>go('practice')}>Practice</button><button type="button" onClick={()=>go('challenge')}>Challenge</button><button type="button" onClick={()=>go('test')}>Final Test</button></nav>
 <section className="et-progress"><div><span>Lesson {lesson+1} of {LESSONS.length}</span><b>{Math.round((lesson+1)*100/LESSONS.length)}%</b></div><div className="et-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></section>
 <div className="et-layout"><aside className="et-map"><div className="et-map-title">Lesson map</div>{LESSONS.map((x,i)=><button type="button" key={x.n} className={i===lesson?'selected':''} onClick={()=>setLesson(i)}><span>{x.n}</span><div><strong>{x.title}</strong><small>{x.group}</small></div></button>)}</aside>
 <section><article className="et-lesson"><span className="et-badge">{current.group}</span><h2>{current.title}</h2><p className="et-simple">{current.simple}</p><div className="et-inline-guide"><span>समझने का आसान तरीका</span><p>{current.hindi}</p></div><div className="et-grid"><section><h3>Core meaning</h3><p>{current.meaning}</p></section><section><h3>Structure</h3><p>{current.structure}</p></section></div><section className="et-examples"><h3>Quick examples</h3>{current.examples.map((x,i)=><div key={i}>{x}</div>)}</section><div className="et-clue"><strong>Exam clue</strong><p>{current.clue}</p></div></article>
 <div className="et-lesson-nav"><button type="button" disabled={lesson===0} onClick={()=>setLesson(v=>Math.max(0,v-1))}>← Previous lesson</button><span>{lesson+1} / {LESSONS.length}</span><button type="button" onClick={()=>setLesson(v=>Math.min(LESSONS.length-1,v+1))}>{lesson===LESSONS.length-1?'Review audit':'Next lesson →'}</button></div>
 <section className="et-method"><h2>Translation workflow</h2><div className="et-method-grid">{['Understand the Hindi sentence','Identify time and action type','Choose English sentence pattern','Select auxiliary + verb form','Add articles and prepositions','Audit meaning + grammar'].map((x,i)=><div key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></section>
 <section className="et-models"><div className="et-models-head"><span>MODEL TRANSLATIONS</span><h2>See the Hindi Meaning → English Build</h2><p>Each example shows the source sentence, natural English and the controlling structure.</p></div><div className="et-model-grid">{MODELS.map(([kind,hi,en,why])=><article key={hi}><small>{kind}</small><h3>{hi}</h3><div className="et-arrow">↓</div><p className="et-model-en">{en}</p><p className="et-model-why">{why}</p></article>)}</div></section>
 <section className="et-errors"><h2>Common errors</h2><div className="et-error-grid">{TRAPS.slice(0,6).map((x,i)=><div key={i}>{x}</div>)}</div></section>
 <section className="et-writing"><h2>Translate it yourself</h2><p>Use the current lesson as your translation target.</p><div className="et-task">{TASKS[lesson%TASKS.length]}</div><div className="et-checks"><span>✓ Meaning understood</span><span>✓ Tense selected</span><span>✓ Verb form checked</span><span>✓ Word order checked</span><span>✓ Small words checked</span><span>✓ Final audit done</span></div></section>
 </section></div>
 <section className="et-audit"><div><span>FINAL AUDIT</span><h2>Ready to translate under exam conditions?</h2><p>Meaning → tense → structure → verb form → articles/prepositions → natural English → final check.</p></div><button type="button" onClick={()=>go('practice')}>Start Practice →</button></section>
 </main>;
}
