import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
 title:'My Childhood',
 author:'A. P. J. Abdul Kalam',
 sourceNote:'Class 9 English • The Panorama • Prose Chapter 8',
 intro:'An autobiographical account of Abdul Kalam’s childhood in Rameswaram, showing family values, early responsibility, friendship, religious harmony, social prejudice, and the influence of teachers and elders.',
 authorNote:'The supplied Chapter 8 pages identify A. P. J. Abdul Kalam and present the lesson as an extract from his autobiography Wings of Fire, centred on his childhood experiences.',
 sections:[
  {title:'Part 1 — Rameswaram and family',flow:'Kalam was born in Rameswaram into a middle-class Tamil family. His father Jainulabdeen had little formal education or wealth, but he was wise and generous. The family lived in their ancestral house on Mosque Street.',explanation:'कलाम का जन्म रामेश्वरम् में एक मध्यमवर्गीय तमिल परिवार में हुआ। उनके पिता जैनुलाब्दीन के पास औपचारिक शिक्षा और अधिक धन नहीं था, फिर भी वे बुद्धिमान और उदार थे। परिवार मॉस्क स्ट्रीट के पुश्तैनी घर में रहता था।',vocabulary:[['middle-class','मध्यमवर्गीय'],['ancestral','पुश्तैनी'],['innate','जन्मजात'],['generosity','उदारता'],['wisdom','बुद्धिमत्ता']],exam:'Remember the setting, family background and qualities of Jainulabdeen.',think:'Why can wisdom and generosity be more important than wealth?'},
  {title:'Part 2 — A secure childhood',flow:'Kalam describes a simple childhood without unnecessary luxuries. Yet the family provided food, medicine, clothes and emotional security. His memories show that a secure life does not require luxury.',explanation:'कलाम बताते हैं कि उनके बचपन में अनावश्यक विलासिता नहीं थी, लेकिन भोजन, दवा, कपड़े और परिवार का स्नेह पर्याप्त था। इसलिए उनका बचपन भौतिक और भावनात्मक रूप से सुरक्षित था।',vocabulary:[['necessity','आवश्यकता'],['luxury','विलासिता'],['secure','सुरक्षित'],['materially','भौतिक रूप से'],['emotionally','भावनात्मक रूप से']],exam:'The phrase materially and emotionally secure is a key idea for long-answer questions.',think:'How is security different from luxury?'},
  {title:'Part 3 — War and first earnings',flow:'The Second World War began in 1939 when Kalam was eight. The war changed daily life and created a sudden demand for tamarind seeds, which Kalam collected and sold. Jalaluddin also helped him understand the wider war.',explanation:'1939 में द्वितीय विश्व युद्ध शुरू हुआ, तब कलाम आठ वर्ष के थे। युद्ध के कारण इमली के बीजों की माँग बढ़ी और कलाम उन्हें इकट्ठा करके बेचते थे। जलालुद्दीन उन्हें युद्ध की बातें बताते थे।',vocabulary:[['outbreak','प्रारंभ / प्रकोप'],['demand','माँग'],['tamarind seeds','इमली के बीज'],['collect','इकट्ठा करना'],['distant','दूर का']],exam:'Key facts: 1939, age eight, tamarind seeds, Jalaluddin.',think:'How can a world event affect a child’s ordinary life?'},
  {title:'Part 4 — Newspaper work and first wages',flow:'The train halt at Rameswaram was suspended. Newspaper bundles were thrown from a moving train, and Kalam’s cousin Samsuddin needed help catching them. Kalam’s work earned him his first wages.',explanation:'रामेश्वरम् में ट्रेन का ठहराव बंद होने के बाद अखबारों के बंडल चलती ट्रेन से फेंके जाते थे। सम्सुद्दीन को बंडल पकड़ने में मदद चाहिए थी। कलाम ने यह काम किया और अपनी पहली मजदूरी कमाई।',vocabulary:[['suspension','ठहराव का बंद होना'],['bundle','बंडल'],['distributor','वितरक'],['wages','मजदूरी'],['moving train','चलती ट्रेन']],exam:'Sequence: suspended halt → thrown bundles → help for Samsuddin → first wages.',think:'Why were the first wages emotionally important to Kalam?'},
  {title:'Part 5 — Friends and social harmony',flow:'Kalam’s three close friends were Ramanadha Sastry, Aravindan and Sivaprakasan. They came from orthodox Hindu Brahmin families, yet their friendship crossed religious boundaries naturally.',explanation:'कलाम के तीन घनिष्ठ मित्र रमानाध शास्त्री, अरविंदन और शिवप्रकाशन थे। तीनों रूढ़िवादी हिंदू ब्राह्मण परिवारों से थे, फिर भी धार्मिक भिन्नता ने उनकी मित्रता को नहीं बाँटा।',vocabulary:[['orthodox','रूढ़िवादी'],['friendship','मित्रता'],['pilgrim','तीर्थयात्री'],['priest','पुजारी'],['harmony','सामंजस्य']],exam:'Learn the three names and the chapter’s emphasis on communal harmony.',think:'What makes a friendship stronger than social labels?'},
  {title:'Part 6 — Shared traditions',flow:'During Shri Sita Rama Kalyanam, Kalam’s family arranged boats with a special platform for the temple idols. At home, his mother and grandmother told children stories from the Ramayana and the life of the Prophet.',explanation:'श्री सीता राम कल्याणम् के समय कलाम का परिवार मंदिर की मूर्तियों के लिए विशेष मंच वाली नावों की व्यवस्था करता था। घर में रामायण और पैगंबर के जीवन की कथाएँ सुनाई जाती थीं।',vocabulary:[['annual','वार्षिक'],['ceremony','समारोह'],['platform','मंच'],['idol','मूर्ति'],['tradition','परंपरा']],exam:'This part illustrates shared traditions and everyday religious coexistence.',think:'How do family traditions encourage mutual respect?'},
  {title:'Part 7 — The new teacher’s prejudice',flow:'In the fifth standard, Kalam sat beside Ramanadha Sastry in the front row. A new teacher objected because Kalam was a Muslim and Ramanadha was the son of a Hindu priest. Kalam was ordered to move to the back bench, upsetting both friends.',explanation:'पाँचवीं कक्षा में कलाम रमानाध शास्त्री के साथ आगे बैठते थे। नए शिक्षक ने धार्मिक पूर्वाग्रह के कारण कलाम को पीछे की बेंच पर भेज दिया। इससे कलाम और रमानाध दोनों बहुत दुखी हुए।',vocabulary:[['prejudice','पूर्वाग्रह'],['discrimination','भेदभाव'],['downcast','उदास'],['back bench','पीछली बेंच'],['identity','पहचान']],exam:'The seating decision is a clear example of discrimination based on religious identity.',think:'Why is this unfair even though the students had done nothing wrong?'},
  {title:'Part 8 — Lakshmana Sastry’s intervention',flow:'Kalam and Ramanadha told their parents. Pakshi Lakshmana Sastry, the temple’s high priest and Ramanadha’s father, summoned the teacher. He rejected social inequality and communal intolerance and demanded corrective action.',explanation:'कलाम और रमानाध ने घटना अपने माता-पिता को बताई। रमानाध के पिता और मंदिर के उच्च पुजारी पाक्षी लक्ष्मण शास्त्री ने शिक्षक को बुलाकर सामाजिक असमानता और सांप्रदायिक असहिष्णुता का विरोध किया।',vocabulary:[['high priest','उच्च पुजारी'],['inequality','असमानता'],['intolerance','असहिष्णुता'],['apologise','माफी माँगना'],['reform','सुधार करना']],exam:'Lakshmana Sastry uses authority to defend equality and dignity.',think:'What should responsible authority do when it sees discrimination?'},
  {title:'Part 9 — Sivasubramania Iyer breaks barriers',flow:'Kalam’s science teacher Sivasubramania Iyer was an orthodox Brahmin but opposed social barriers. He invited Kalam home for a meal. When his wife initially refused to serve a Muslim boy, Iyer served Kalam himself. On the next visit, she served Kalam herself.',explanation:'विज्ञान शिक्षक शिवसुब्रह्मण्यम अय्यर रूढ़िवादी ब्राह्मण थे, लेकिन सामाजिक भेदभाव के विरोधी थे। उन्होंने कलाम को घर भोजन पर बुलाया। पत्नी के प्रारंभिक विरोध पर अय्यर ने स्वयं भोजन परोसा; अगली बार पत्नी ने स्वयं भोजन कराया।',vocabulary:[['conservative','रूढ़िवादी'],['barrier','बाधा'],['refuse','मना करना'],['attitude','दृष्टिकोण'],['example','उदाहरण']],exam:'Iyer demonstrates equality through action and personal example.',think:'Why can an example change attitudes more effectively than a lecture?'},
  {title:'Part 10 — Freedom and higher studies',flow:'As India moved towards freedom after the war, Kalam’s father allowed him to leave Rameswaram for further study at Ramanathapuram. His childhood experiences became part of the foundation of his future life and ambition.',explanation:'युद्ध के बाद भारत की स्वतंत्रता निकट थी। कलाम के पिता ने उन्हें आगे की पढ़ाई के लिए रामनाथपुरम् जाने की अनुमति दी। उनके बचपन के अनुभव उनके भावी जीवन और महत्वाकांक्षा की नींव बने।',vocabulary:[['imminent','शीघ्र होने वाला'],['freedom','स्वतंत्रता'],['ambition','महत्त्वाकांक्षा'],['further study','आगे की पढ़ाई'],['foundation','नींव']],exam:'The ending links childhood values with education, freedom and future ambition.',think:'How can childhood experiences shape a person’s future?'},
 ],
 wordStudy:{title:'Word Study',spelling:[['Rameswaram','Rameswaram'],['Jainulabdeen','Jainulabdeen'],['Ramanadha','Ramanadha'],['Sivasubramania','Sivasubramania'],['Sivaprakasan','Sivaprakasan']],forms:[['collect','collected / collecting'],['distribute','distributed / distributing'],['inherit','inherited / inheriting'],['apologise','apologised / apologising'],['reform','reformed / reforming']],matches:[['secure','safe and protected'],['prejudice','an unfair judgement formed in advance'],['intolerance','refusal to accept difference'],['imminent','likely to happen soon'],['segregation','keeping a group apart']],phrases:['break out','sit beside','move to the back','stand for','look after']},
 grammar:{title:'Language Focus',intro:'The supplied Chapter 8 pages do not show a separate grammar exercise page. The following sentence-joining work is clearly marked as supplementary practice.',types:[['Cause','because, since, as','Kalam remembered the war because it changed local life.'],['Contrast','although, though, but','Although the teacher was unfair, others challenged the prejudice.'],['Time','when, while, after','When the train halt was suspended, newspaper bundles were thrown.'],['Result','so, therefore','The seating was discriminatory, so Ramanadha became deeply upset.']]},
 examPrep:['Elucidate the circumstances leading to a materially and emotionally secure childhood of Dr. A. P. J. Abdul Kalam.','Describe the circumstances which helped Kalam in earning his first wages during the outbreak of the Second World War.','What relationship did Kalam have with Ramanadha Sastry, Aravindan and Sivaprakasan?','Describe the circumstances that led to Kalam being moved to the back bench in standard fifth.','How did Lakshmana Sastry react to the teacher’s discriminatory action?','How did Sivasubramania Iyer try to break social barriers?','Why did Iyer invite Kalam to his house and what happened at the first meal?','How do the childhood experiences in the chapter help explain Kalam’s later ambitions?'],
 composition:['Write a letter to your friend describing Kalam’s childhood and the values you learn from it.','Write a paragraph on the importance of religious harmony in school life.'],
 activities:['Discuss in pairs: Should a student ever be treated differently because of religion or caste?','Create a timeline of the war, Kalam’s first wages, the classroom incident, Lakshmana Sastry’s intervention and Iyer’s meal.','Compare the responses of the prejudiced teacher, Lakshmana Sastry and Sivasubramania Iyer.'],
 translationPractice:['कलाम का जन्म रामेश्वरम् में हुआ था।','उनका बचपन भौतिक और भावनात्मक रूप से सुरक्षित था।','द्वितीय विश्व युद्ध 1939 में शुरू हुआ।','कलाम ने इमली के बीज बेचकर पैसे कमाए।','सम्सुद्दीन अखबार बाँटते थे।','कलाम ने अपनी पहली मजदूरी कमाई।','रमानाध शास्त्री उनके घनिष्ठ मित्र थे।','लक्ष्मण शास्त्री ने भेदभाव का विरोध किया।','अय्यर ने सामाजिक बाधाओं को तोड़ने का प्रयास किया।','कलाम आगे की पढ़ाई के लिए रामनाथपुरम् गए।']
};

const practice=[
 {q:'Who wrote “My Childhood”?',o:['A. P. J. Abdul Kalam','Vikram Seth','O. Henry','Moti Nisani'],a:0,e:'The chapter is written by A. P. J. Abdul Kalam.'},
 {q:'Where was Kalam’s ancestral house?',o:['Mosque Street, Rameswaram','Railway Road, Madurai','Temple Road, Delhi','Station Road, Chennai'],a:0,e:'The ancestral house was on Mosque Street in Rameswaram.'},
 {q:'How old was Kalam when the Second World War broke out?',o:['Eight','Six','Ten','Twelve'],a:0,e:'The lesson states that Kalam was eight in 1939.'},
 {q:'Which seeds did Kalam collect and sell?',o:['Tamarind seeds','Mango seeds','Lotus seeds','Sunflower seeds'],a:0,e:'The chapter mentions the sudden demand for tamarind seeds.'},
 {q:'Who was Samsuddin?',o:['Kalam’s cousin and a newspaper distributor','His science teacher','The temple priest','His headmaster'],a:0,e:'Samsuddin distributed newspapers and involved Kalam in the work.'},
 {q:'How did Kalam earn his first wages?',o:['By helping catch newspaper bundles','By teaching children','By working in a shop','By selling books'],a:0,e:'He helped catch newspaper bundles thrown from a moving train.'},
 {q:'Who were Kalam’s three close friends?',o:['Ramanadha Sastry, Aravindan and Sivaprakasan','Jalaluddin, Samsuddin and Iyer','Ramanadha, Lakshmana and Jalaluddin','Samsuddin, Iyer and Aravindan'],a:0,e:'These three are named as Kalam’s close childhood friends.'},
 {q:'Why was Kalam moved to the back bench?',o:['A teacher objected to his religious identity beside a Hindu priest’s son','He failed a test','He arrived late','He was talking in class'],a:0,e:'The teacher’s action was based on communal prejudice.'},
 {q:'Who intervened against the teacher’s prejudice?',o:['Pakshi Lakshmana Sastry','Samsuddin','Jalaluddin','Aravindan'],a:0,e:'Lakshmana Sastry challenged the discriminatory behaviour.'},
 {q:'Which teacher invited Kalam home for a meal?',o:['Sivasubramania Iyer','The new fifth-standard teacher','Lakshmana Sastry','Jalaluddin'],a:0,e:'Iyer invited Kalam home and personally served him.'},
 {q:'What was the main reason for Iyer’s invitation?',o:['To challenge social barriers and practise equality','To give Kalam homework','To discuss railway work','To sell newspapers'],a:0,e:'His invitation was part of his effort to break social barriers.'},
 {q:'What did Iyer’s wife do at the first meal?',o:['She initially refused to serve Kalam','She welcomed him immediately','She left the town','She called the headmaster'],a:0,e:'She initially refused to serve a Muslim boy in her kitchen.'},
 {q:'What happened at the next meal?',o:['Iyer’s wife served Kalam herself','Kalam refused to eat','The meal was cancelled','Ramanadha served the meal'],a:0,e:'At the next visit, Iyer’s wife served Kalam herself.'},
 {q:'Which quality is associated with Jainulabdeen?',o:['Wisdom and generosity','Luxury and fame','Anger and pride','Wealth and status'],a:0,e:'Kalam remembers his father for wisdom and generosity.'},
 {q:'What is a central message of the chapter?',o:['Equality and social harmony','Religious separation','Material luxury','Avoiding education'],a:0,e:'The chapter strongly emphasizes equality, harmony and dignity.'}
];

const challenge=[
 {q:'Why does Kalam call his childhood materially and emotionally secure?',o:['Essential needs and family care were provided despite a simple lifestyle','His family lived in luxury','He never faced difficulties','He was educated abroad'],a:0,e:'Security came from meeting needs and receiving emotional support, not from luxury.'},
 {q:'What does Jainulabdeen’s description suggest?',o:['Wisdom and character do not depend on wealth or formal schooling','Wealth always creates wisdom','Education is unnecessary for everyone','Parents should not guide children'],a:0,e:'Kalam admires his father’s qualities despite limited formal education and wealth.'},
 {q:'Why is the 1939 date important?',o:['It marks the outbreak of the Second World War during Kalam’s childhood','It marks Indian independence','It marks Kalam’s first school','It marks his graduation'],a:0,e:'The lesson places the war within Kalam’s childhood and notes that he was eight.'},
 {q:'How did the war affect local life in Rameswaram?',o:['The train halt was suspended and newspaper bundles were thrown from a moving train','Schools closed permanently','The family moved to Delhi','Temple ceremonies stopped'],a:0,e:'The chapter calls the suspension of the train halt the first local casualty of the war.'},
 {q:'Why are Kalam’s first wages significant?',o:['They gave him pride in his own effort and responsibility','They made him rich','They were an inheritance','They came as a school prize'],a:0,e:'The memory carries a strong sense of personal pride.'},
 {q:'Why is the friendship with Ramanadha important?',o:['It shows that religious difference did not naturally divide the children','It shows the boys were rivals','It was arranged by teachers','It ended before the classroom incident'],a:0,e:'Their friendship establishes the harmony that prejudice later disturbs.'},
 {q:'What does the family’s participation in Shri Sita Rama Kalyanam show?',o:['Shared community life could cross religious boundaries','Kalam rejected tradition','Only Muslims managed the ceremony','The family avoided all religious customs'],a:0,e:'The family helped with a Hindu religious ceremony while also preserving its own traditions.'},
 {q:'Why is the new teacher’s behaviour discriminatory?',o:['He separates children because of religious identity rather than conduct','He changes seating for better visibility','He rewards the front row','He wants students to be quiet'],a:0,e:'The stated reason for moving Kalam is his religion and Ramanadha’s background.'},
 {q:'Why does Ramanadha become deeply upset?',o:['His close friend is humiliated and separated because of religion','He loses a book','He fails an exam','He wants the back bench'],a:0,e:'His reaction shows the emotional harm caused by discrimination.'},
 {q:'Why is Lakshmana Sastry’s intervention important?',o:['He uses authority to reject inequality and communal intolerance','He ignores the teacher','He separates the boys permanently','He punishes Kalam'],a:0,e:'He directly challenges discriminatory authority with principled authority.'},
 {q:'How does Iyer challenge prejudice through action?',o:['He invites Kalam home, serves him himself and persists until his wife changes her attitude','He only gives a lecture','He transfers Kalam','He stops teaching science'],a:0,e:'Iyer demonstrates equality in his own home and behaviour.'},
 {q:'What does the second meal suggest?',o:['People’s attitudes can change through experience and example','Prejudice is impossible to change','Children cannot influence adults','Traditions can never change'],a:0,e:'The change in Iyer’s wife indicates that attitudes can be transformed.'},
 {q:'How do the two teacher episodes contrast?',o:['One imposes prejudice while the other actively breaks social barriers','Both support discrimination','Both ignore religion','Both punish Kalam'],a:0,e:'The contrast is deliberate and central to the lesson.'},
 {q:'Which sequence best matches the chapter?',o:['Family life → war → first wages → friendship → prejudice → intervention → higher study','War → university → childhood → friendship → retirement','Friendship → presidency → school → war → family','School exam → newspaper → independence → birth'],a:0,e:'This sequence follows the major remembered episodes in the supplied pages.'},
 {q:'Why does the chapter mention the later professions of Kalam’s friends?',o:['To show that different adult paths grew from a shared childhood background','To rank their wealth','To prove they stopped speaking','To compare exam marks'],a:0,e:'The later occupations reinforce the continuity of their lives beyond childhood.'},
 {q:'What does the shared storytelling of the Ramayana and the Prophet’s life suggest?',o:['Different religious traditions could coexist in the family environment','Only one tradition was accepted','Kalam rejected religion','The family avoided stories'],a:0,e:'The detail highlights a plural and harmonious cultural environment.'},
 {q:'Why is “segregation” a useful idea for the classroom incident?',o:['The teacher tries to keep children apart on the basis of identity','It means cooperation','It means friendship','It refers to school transport'],a:0,e:'Segregation means separation of a group; the teacher attempts it on religious grounds.'},
 {q:'Which detail best proves Iyer’s approach was practical?',o:['He sat beside Kalam and served him food himself','He wrote a speech','He left the school','He changed the timetable'],a:0,e:'His own conduct directly challenged the social barrier.'},
 {q:'How does the ending connect childhood with the future?',o:['Kalam leaves for further study as India moves towards freedom','The family stops schooling','The war begins again','The friends separate permanently'],a:0,e:'The conclusion moves from childhood memories to future education and national change.'},
 {q:'What is the best inference about family influence?',o:['Early values and support can shape later character and ambition','Family never affects education','Parents only choose careers','Values matter only for wealthy children'],a:0,e:'Kalam’s memories repeatedly connect family life with his later character.'},
 {q:'What is the best inference about responsible authority?',o:['Authority should protect dignity and fairness','Authority should preserve every custom','Authority is only punishment','Authority should ignore discrimination'],a:0,e:'Lakshmana Sastry models authority used to defend equality.'},
 {q:'What broader lesson follows from Kalam’s experience?',o:['Equality becomes meaningful when people practise it in ordinary life','Harmony means avoiding all differences','Religion should determine friendship','Education and social values are unrelated'],a:0,e:'The chapter presents equality through everyday actions, not only through ideas.'},
 {q:'Why does the lesson work as an autobiography?',o:['Kalam uses remembered childhood experiences to explain his values','It is a fictional fairy tale','It contains no personal memories','It is only a history lesson'],a:0,e:'The narration is a personal reflection on childhood experiences.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function Learn({onMode}){
 return <div className="pg-shell">
  <div className="pg-hero"><span className="pg-kicker">{study.sourceNote}</span><h1>{study.title}</h1><p>A. P. J. Abdul Kalam • autobiography • family, work, friendship and social harmony</p><div className="pg-hero-stats"><span>10 Guided Parts</span><span>Word Study</span><span>Language Focus</span><span>Exam Prep</span></div></div>
  <div className="pg-modebar">{[['learn','LEARN','Guided learning'],['practice','PRACTICE • 15 QUESTIONS • 11:15','Easy → Moderate'],['challenge','CHALLENGE • 23 QUESTIONS • 23:00','Moderate → Hard'],['test','FINAL TEST • 20 QUESTIONS • 25:00','Exam Level']].map(([m,label,sub])=><button key={m} className={m==='learn'?'active':''} onClick={()=>onMode(m)}><b>{label}</b><span>{sub}</span></button>)}</div>
  <div className="pg-panel"><div className="pg-panel-title"><small>LESSON OVERVIEW</small><h2>{study.title}</h2><p>{study.intro}</p></div><div className="pg-author"><b>Author • {study.author}</b><div>{study.authorNote}</div></div></div>
  <div className="pg-anchorbar">{study.sections.map((s,i)=><a key={s.title} href={`#part-${i+1}`}>Part {i+1}</a>)}<a href="#word-study">Word Study</a><a href="#grammar">Language Focus</a><a href="#exam-prep">Exam Prep</a></div>
  <section><div className="pg-section-heading"><span>01</span><div><small>GUIDED READING</small><h2>Understand the chapter step by step</h2><p>English summary • हिन्दी व्याख्या • vocabulary • exam focus</p></div></div><div className="pg-reading-stack">{study.sections.map((s,i)=><article className="pg-reading-card" id={`part-${i+1}`} key={s.title}><div className="pg-card-top"><div className="pg-num">{String(i+1).padStart(2,'0')}</div><div><span>PART {i+1}</span><h3>{s.title.replace(/^Part \d+ — /,'')}</h3></div></div><div className="pg-flow"><div className="pg-flow-label">English summary</div><p>{s.flow}</p></div><div className="pg-hindi"><div className="pg-flow-label">हिन्दी व्याख्या</div><p>{s.explanation}</p></div><div className="pg-vocab-head">Key vocabulary</div><div className="pg-vocab-grid">{s.vocabulary.map(([w,m])=><div className="pg-vocab" key={w}><b>{w}</b><span>{m}</span></div>)}</div><div className="pg-bottom-grid"><div className="pg-exam"><b>Exam Focus</b><span>{s.exam}</span></div><div className="pg-think"><b>Think</b><span>{s.think}</span></div></div></article>)}</div></section>
  <section id="word-study"><div className="pg-section-heading compact"><span>02</span><div><small>WORD STUDY</small><h2>{study.wordStudy.title}</h2><p>Spelling, forms, meanings and useful expressions connected with the chapter.</p></div></div><div className="pg-tool-grid"><div className="pg-panel"><h3>Dictionary spelling</h3><div className="pg-spelling">{study.wordStudy.spelling.map(([a,b])=><div key={a}><del>{a}</del><b>{b}</b></div>)}</div></div><div className="pg-panel"><h3>Verb forms</h3><div className="pg-pillgrid">{study.wordStudy.forms.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></div></div><div className="pg-two-col"><div className="pg-panel"><h3>Match meanings</h3><div className="pg-match">{study.wordStudy.matches.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></div><div className="pg-panel"><h3>Useful phrases</h3><div className="pg-phrasegrid">{study.wordStudy.phrases.map(p=><div key={p}><b>{p}</b><span>Use the expression in a new sentence of your own.</span></div>)}</div></div></div></section>
  <section id="grammar"><div className="pg-section-heading compact"><span>03</span><div><small>LANGUAGE FOCUS</small><h2>{study.grammar.title}</h2><p>{study.grammar.intro}</p></div></div><div className="pg-panel"><div className="pg-grammar-grid">{study.grammar.types.map(([t,d,e])=><div key={t}><b>{t}</b><span>{d}</span><code>{e}</code></div>)}</div><div className="pg-rulebox"><b>Study note</b><span>These sentence-joining examples are supplementary practice and are not presented as a separate textbook exercise.</span></div></div></section>
  <section id="exam-prep"><div className="pg-section-heading compact"><span>04</span><div><small>EXAM PREP</small><h2>Practise long answers and composition</h2><p>Questions and tasks are based on the supplied Chapter 8 pages and its themes.</p></div></div><div className="pg-exam-grid"><div className="pg-panel"><h3>Important questions</h3><ol>{study.examPrep.map(q=><li key={q}>{q}</li>)}</ol></div><div className="pg-panel"><h3>Composition</h3><ol>{study.composition.map(q=><li key={q}>{q}</li>)}</ol><h3>Activities</h3><div className="pg-activitygrid">{study.activities.map((q,i)=><div key={q}><span>{i+1}</span><p>{q}</p></div>)}</div></div></div></section>
  <section><div className="pg-panel"><h3>Supplementary Translation Practice</h3><p className="pg-muted">Translate each Hindi sentence into clear English.</p><div className="pg-translation">{study.translationPractice.map((q,i)=><div key={q}><span>{i+1}</span><b>{q}</b><em>Translate into English.</em></div>)}</div></div></section>
  <section><div className="pg-panel pg-revision"><h3>Rapid Revision</h3><div className="pg-revision-grid"><div><b>Family</b><span>Jainulabdeen + Ashiamma; simple but secure childhood</span></div><div><b>Early work</b><span>Tamarind seeds; newspaper bundles; first wages</span></div><div><b>Friendship</b><span>Ramanadha Sastry + Aravindan + Sivaprakasan</span></div><div><b>Conflict</b><span>Religious prejudice in the fifth-standard classroom</span></div><div><b>Resistance</b><span>Lakshmana Sastry and Sivasubramania Iyer</span></div><div><b>Future</b><span>Freedom approaching; higher studies at Ramanathapuram</span></div></div></div></section>
 </div>;
}

export function EnglishPanoramaChapter8({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode||'learn');
 const bank=mode==='practice'?practice:mode==='challenge'?challenge:mode==='test'?finalTest:null;
 if(mode!=='learn')return <PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>setMode('learn')} addXp={addXp} finishSession={finishSession}/>;
 return <Learn onMode={setMode}/>;
}

export default EnglishPanoramaChapter8;
