import React,{useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import {IDIOMS_BANKS} from './EnglishIdiomsPhrasesQuestionBank.jsx';
import './EnglishIdiomsPhrasesTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Idiom क्या होता है?',simple:'Idiom ऐसा fixed expression है जिसका अर्थ उसके individual words के literal अर्थ से अलग या broader हो सकता है। इसलिए idiom को phrase + meaning के रूप में सीखो।',meaning:'An idiom is a fixed expression whose intended meaning is not always the literal meaning of its words.',structure:'idiom → intended meaning → sentence context',examples:['a piece of cake → very easy','spill the beans → reveal a secret','under the weather → feel unwell'],clue:'पहले पूरा phrase पहचानो; हर word को अलग-अलग translate करके answer मत निकालो.'},
{n:'02',group:'MEANING',title:'Literal meaning vs idiomatic meaning',simple:'“Break the ice” का literal अर्थ बर्फ तोड़ना हो सकता है, लेकिन idiomatic meaning friendly interaction शुरू करना है। Exam में intended meaning पूछा जाता है।',meaning:'Idioms must usually be interpreted by their conventional meaning, not word-by-word translation.',structure:'literal words ≠ intended meaning',examples:['break the ice → start friendly interaction','cost an arm and a leg → be very expensive'],clue:'क्या literal reading context में sensible है? नहीं तो idiomatic meaning check करो.'},
{n:'03',group:'CORE',title:'Common idioms of ease and difficulty',simple:'Easy/difficult situations के idioms बार-बार आते हैं: a piece of cake, a hard nut to crack, walk in the park आदि।',meaning:'Some idioms describe how easy or difficult a task is.',structure:'task + idiom → degree of ease/difficulty',examples:['a piece of cake → very easy','a hard nut to crack → difficult to understand/solve'],clue:'Question में task/problem की difficulty identify करो.'},
{n:'04',group:'CORE',title:'Frequency and time expressions',simple:'Once in a blue moon, at the drop of a hat, sooner or later जैसे phrases frequency या timing दिखा सकते हैं।',meaning:'Time-related idioms often describe frequency, immediacy or eventuality.',structure:'phrase → frequency / timing / eventual result',examples:['once in a blue moon → very rarely','at the drop of a hat → immediately','sooner or later → eventually'],clue:'Very rarely, immediately, eventually जैसे meaning clues ढूँढो.'},
{n:'05',group:'CORE',title:'Secrets and information',simple:'Spill the beans, let the cat out of the bag और keep something under wraps information और secrecy से जुड़े useful idioms हैं।',meaning:'Idioms can describe revealing, hiding or controlling information.',structure:'information context → reveal / hide / protect',examples:['spill the beans → reveal a secret','let the cat out of the bag → reveal secret information','keep it under wraps → keep it secret'],clue:'Secret reveal हुआ है या secret hide किया जा रहा है?'},
{n:'06',group:'CORE',title:'Happiness, sadness and feelings',simple:'On cloud nine, over the moon, under the weather जैसे phrases feelings express करते हैं। Context से positive/negative emotion पहचानो।',meaning:'Emotion idioms describe a person’s emotional or physical state.',structure:'person/state + idiom → emotional meaning',examples:['on cloud nine → extremely happy','over the moon → extremely pleased','under the weather → feeling unwell'],clue:'Context में emotion/state को पहले नाम दो, फिर idiom match करो.'},
{n:'07',group:'CORE',title:'Trouble, difficulty and consequences',simple:'In hot water, face the music, get into a mess जैसे idioms trouble या consequences के context में आते हैं।',meaning:'Some idioms describe being in trouble or dealing with consequences.',structure:'problem → trouble / consequence → response',examples:['in hot water → in trouble','face the music → accept consequences','out of the woods → out of difficulty'],clue:'Problem की स्थिति है या problem से बाहर निकलने की स्थिति?'},
{n:'08',group:'CORE',title:'Agreement and disagreement',simple:'See eye to eye agreement दिखाता है; agree to disagree difference of opinion को handle करने का expression है।',meaning:'Idioms can express agreement, shared views or disagreement.',structure:'people + opinions → agree / differ',examples:['see eye to eye → agree','agree to disagree → accept different opinions'],clue:'क्या दोनों people same view रखते हैं?'},
{n:'09',group:'CORE',title:'Effort, progress and success',simple:'Go the extra mile, burn the midnight oil, by leaps and bounds और hit the nail on the head exam contexts में useful हैं।',meaning:'These idioms express effort, rapid progress or exactness.',structure:'action/result → effort / progress / accuracy',examples:['go the extra mile → make extra effort','burn the midnight oil → work late','by leaps and bounds → very rapidly','hit the nail on the head → identify exactly'],clue:'Effort, speed या accuracy—कौन-सा semantic field है?'},
{n:'10',group:'CORE',title:'Money and practical life',simple:'Cost an arm and a leg, make ends meet और cut corners money/resources से जुड़े common expressions हैं।',meaning:'Some idioms describe high cost, financial management or doing something cheaply/carelessly.',structure:'money/resources → cost / manage / economise',examples:['cost an arm and a leg → be very expensive','make ends meet → manage financially','cut corners → skip proper steps to save time/money'],clue:'Cost बहुत high है, budget manage हो रहा है, या quality sacrifice हो रही है?'},
{n:'11',group:'CONTEXT',title:'Context is the real key',simple:'एक ही idiom को अलग context में समझने के बजाय sentence का पूरा situation पढ़ो। इससे close options के बीच सही choice मिलती है।',meaning:'Context disambiguates the intended idiomatic meaning.',structure:'sentence → situation → idiom sense → option',examples:['The task was simple; it was a piece of cake.','The reveal was accidental; he let the cat out of the bag.'],clue:'Phrase को अकेला देखकर नहीं; sentence का cause/result पढ़कर answer करो.'},
{n:'12',group:'CONTEXT',title:'Idiom in a sentence',simple:'Meaning याद होना पर्याप्त नहीं। यह भी देखो कि idiom sentence में grammatically और semantically natural लग रहा है या नहीं।',meaning:'Correct use requires both idiomatic meaning and a natural sentence context.',structure:'subject + idiom phrase + context',examples:['I was under the weather, so I stayed home.','She was on cloud nine after the result.'],clue:'Meaning सही है, लेकिन sentence में usage भी natural होना चाहिए.'},
{n:'13',group:'PATTERNS',title:'Fixed form matters',simple:'कई idioms fixed wording रखते हैं। Option में एक word बदलने से expression unnatural या incorrect हो सकता है।',meaning:'Idioms often have conventional forms that should not be freely rearranged.',structure:'fixed expression → conventional wording',examples:['see eye to eye ✅','see eye with eye ❌','spill the beans ✅','spill the bean ❌ in the idiom'],clue:'Known idiom की standard wording पहचानो.'},
{n:'14',group:'PATTERNS',title:'Verb + particle idioms',simple:'कुछ phrases phrasal/idiomatic combinations जैसे give up, carry on, turn down से मिलते-जुलते होते हैं। Meaning context से अलग हो सकता है।',meaning:'Verb-based expressions can acquire meanings beyond their literal verb sense.',structure:'verb + particle/object → idiomatic meaning',examples:['give up → stop trying','carry on → continue','turn down → reject/refuse'],clue:'Literal movement meaning नहीं; sentence में actual action क्या है?'},
{n:'15',group:'APPLICATION',title:'Hindi → English idiom choice',simple:'Hindi meaning को पहले simple English idea में बदलो, फिर matching idiom चुनो। Word-for-word Hindi translation से idiom नहीं बनता।',meaning:'Translation should target the intended sense first, then select the conventional English idiom.',structure:'Hindi sense → simple English meaning → idiom',examples:['बहुत महँगा → very expensive → cost an arm and a leg','बहुत कम → very rarely → once in a blue moon'],clue:'पहले sense पकड़ो, फिर idiom; reverse process कम reliable है.'},
{n:'16',group:'ERROR CONTROL',title:'Common literal-translation traps',simple:'“Break the ice” को बर्फ तोड़ना और “make ends meet” को ends जोड़ना literal translation की गलती होगी।',meaning:'Literal translation often produces a wrong interpretation of an idiom.',structure:'literal reading ✗ → contextual interpretation ✓',examples:['break the ice → not literally break ice','make ends meet → manage financially'],clue:'क्या option phrase का literal picture बता रहा है? ऐसे distractor से सावधान.'},
{n:'17',group:'ADVANCED',title:'Close idioms: meaning shades',simple:'See eye to eye = agree; hit the nail on the head = exactly identify; go the extra mile = make additional effort. Similar positive context होने पर भी meanings अलग हैं।',meaning:'Advanced questions distinguish idioms with related but different semantic roles.',structure:'context role → precise idiom',examples:['agreement → see eye to eye','accuracy → hit the nail on the head','extra effort → go the extra mile'],clue:'Broad mood नहीं; exact action/relationship पहचानो.'},
{n:'18',group:'ADVANCED',title:'Proverb-like expressions and advice',simple:'Actions speak louder than words और put all your eggs in one basket जैसे expressions advice/general truth देते हैं।',meaning:'Some idiomatic expressions function like advice or general observations.',structure:'situation → principle/advice → expression',examples:['actions speak louder than words → actions can matter more than claims','put all your eggs in one basket → do not depend on one option'],clue:'क्या expression किसी decision या behaviour पर general advice दे रहा है?'},
{n:'19',group:'EXAM CONTROL',title:'MCQ elimination strategy',simple:'चार options में literal distractor, opposite meaning, unrelated meaning और correct idiomatic meaning पहचानना सीखो।',meaning:'Strong MCQ solving combines context, semantic field and option elimination.',structure:'context → eliminate literal/opposite/unrelated → verify idiom',examples:['under the weather → feeling unwell, not weather location','in hot water → in trouble, not bathing'],clue:'पहले wrong type हटाओ, फिर surviving meaning को sentence में fit करो.'},
{n:'20',group:'FINAL AUDIT',title:'Final Idioms & Phrases Audit',simple:'Final checklist: phrase पहचानो → literal trap हटाओ → context पढ़ो → exact meaning चुनो → sentence fit check करो। इसी sequence से exam accuracy बढ़ती है।',meaning:'Reliable idiom answers come from phrase recognition, context and precise meaning—not literal translation.',structure:'recognise → interpret → contextualise → eliminate → verify',examples:['a piece of cake → easy','once in a blue moon → rarely','spill the beans → reveal a secret','go the extra mile → extra effort'],clue:'Final answer देने से पहले पूछो: “इस sentence में speaker exactly क्या कहना चाहता है?”'}
];

export default function EnglishIdiomsPhrasesTopic({onBack,addXp,finishSession}){
 const initialMode=typeof window!=='undefined'?(new URLSearchParams(window.location.search).get('mode')||'learn'):'learn';
 const [mode,setMode]=useState(['learn','practice','challenge','test'].includes(initialMode)?initialMode:'learn');
 const [lesson,setLesson]=useState(0);
 const tabs=[['learn','Learn'],['practice','Practice'],['challenge','Challenge'],['test','Final Test']];
 const bank=useMemo(()=>mode==='learn'?[]:IDIOMS_BANKS[mode],[mode]);
 const changeMode=m=>{setMode(m);const p=new URLSearchParams(window.location.search);p.set('mode',m);p.set('topic','idioms');p.set('languageSkills','1');p.set('subject','english');window.history.replaceState({},'',`${window.location.pathname}?${p}${window.location.hash||''}`)};
 return <main className="idioms-page">
  <header className="idioms-top"><button type="button" onClick={onBack}>← Language &amp; Skills</button><div className="idioms-hero"><div className="idioms-hero-main"><span>ENGLISH • LANGUAGE &amp; SKILLS</span><h1>Idioms &amp; Phrases</h1><p>Meaning को context से पढ़ो, literal trap से बचो और exam में exact expression चुनो.</p><div className="idioms-hero-stats"><b>20</b><small>lessons</small><b>3</b><small>assessment levels</small><b>Class 9</b><small>exam focus</small></div></div><aside className="idioms-hero-card"><strong>MASTER THE MEANING</strong><span>Phrase recognition</span><span>Context control</span><span>Hindi → English</span><span>Exam elimination</span></aside></div></header>
  <nav className="idioms-tabs" aria-label="Idioms and Phrases learning modes">{tabs.map(([id,label],i)=><button key={id} type="button" className={mode===id?'active':''} onClick={()=>changeMode(id)}><i>{['◫','✦','⚡','✓'][i]}</i><span>{label}</span></button>)}</nav>
  {mode==='learn'?<section className="idioms-learning">
   <div className="idioms-progress"><div><span>Learning progress</span><div className="idioms-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></div><b>{lesson+1} / {LESSONS.length}</b></div>
   <aside className="idioms-map"><strong>Lesson path</strong><div>{LESSONS.map((x,i)=><button key={x.n} type="button" className={lesson===i?'active':''} onClick={()=>setLesson(i)}><em>{x.n}</em><span><b>{x.title}</b><small>{x.group}</small></span></button>)}</div></aside>
   <article className="idioms-lesson"><div className="idioms-kicker"><span>{LESSONS[lesson].group} • LESSON {LESSONS[lesson].n}</span><b>Class 9</b></div><h2>{LESSONS[lesson].title}</h2><div className="idioms-simple"><strong>सरल समझ</strong><p>{LESSONS[lesson].simple}</p></div><section><label>Meaning</label><p className="idioms-meaning">{LESSONS[lesson].meaning}</p></section><section><label>Structure / control</label><div className="idioms-structure"><code>{LESSONS[lesson].structure}</code></div></section><section><label>Examples</label><div className="idioms-examples">{LESSONS[lesson].examples.map((x,i)=><div key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></section><div className="idioms-clue"><b>EXAM CLUE</b><span>{LESSONS[lesson].clue}</span></div><div className="idioms-nav"><button type="button" onClick={()=>setLesson(i=>Math.max(0,i-1))} disabled={lesson===0}>← Previous lesson</button><button type="button" onClick={()=>setLesson(i=>Math.min(LESSONS.length-1,i+1))} disabled={lesson===LESSONS.length-1}>Next lesson →</button></div></article>
  </section>:<EnglishTimedQuiz title="Idioms & Phrases" mode={mode} questions={bank} onModeChange={changeMode} onBack={()=>changeMode('learn')} addXp={addXp} finishSession={finishSession} onNextLevel={m=>changeMode(m)}/>} 
 </main>
}
