import React,{useEffect,useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishTranslationTopic.css';

const LESSONS=[
['01','FOUNDATION','Meaning before words','Translation starts with the whole meaning. Identify who acts, what happens, when it happens and what the speaker intends before choosing English words.','पहले पूरे sentence का meaning पकड़ो। हर Hindi word को अलग-अलग replace करना जरूरी नहीं है।','meaning → situation → English sentence → audit',['मैं रोज़ पढ़ता हूँ। → I study every day.','वह अभी पढ़ रही है। → She is studying now.'],'Never choose a verb form before you understand the time and action.'],
['02','METHOD','The 8-step translation method','Use a fixed sequence: subject, time, action, auxiliary, verb form, object/complement, small words and final audit.','8 steps: Subject → Time → Action → Auxiliary → Verb → Object → Small words → Final audit.','subject → time → action → auxiliary → verb → object → small words → check',['वे दो घंटे से पढ़ रहे हैं। → subject: they; duration: two hours.','मैं कल बाजार गया। → past reference: yesterday; verb: went.'],'A repeatable method prevents small errors from accumulating.'],
['03','TENSE','Simple Present','Use Simple Present for habits, routines, repeated actions, general truths and regular facts.','“रोज़, हमेशा, अक्सर” जैसे clues habit दिखाते हैं। He/She/It के साथ s/es देखो।','subject + V1(s/es)',['वह रोज़ स्कूल जाता है। → He goes to school every day.','सूरज पूर्व में उगता है। → The sun rises in the east.','मेरी बहन किताबें पढ़ती है। → My sister reads books.'],'After does/does not, return to V1.'],
['04','TENSE','Present Continuous','Present Continuous shows an action in progress now or around the present moment.','“अभी… रहा है/रही है/रहे हैं” दिखे तो am/is/are + V-ing check करो।','S + am/is/are + V-ing',['मैं अभी लिख रहा हूँ। → I am writing now.','वे खेल रहे हैं। → They are playing.','अध्यापक समझा रहे हैं। → The teacher is explaining.'],'Match the auxiliary to the subject: I am; he/she is; we/they are.'],
['05','TENSE','Present Perfect','Use Present Perfect for a completed action connected with the present or an unfinished time period.','“कर लिया है / हो चुका है” वाले contexts में present relevance देखो।','S + has/have + V3',['मैं अपना काम कर चुका हूँ। → I have finished my work.','उसने खाना खा लिया है। → She has eaten the food.','हमने कमरा साफ कर दिया है। → We have cleaned the room.'],'Do not pair it blindly with a finished definite time such as yesterday.'],
['06','TENSE','Present Perfect Continuous','Use this form when an activity continues up to now and duration matters. Since gives a starting point; for gives duration.','Starting point = since; duration = for.','S + has/have been + V-ing + since/for',['मैं दो घंटे से पढ़ रहा हूँ। → I have been studying for two hours.','वह सुबह से काम कर रही है। → She has been working since morning.','वे सोमवार से अभ्यास कर रहे हैं। → They have been practising since Monday.'],'Since and for are not interchangeable.'],
['07','TENSE','Simple Past','Use Simple Past for completed past events, especially with yesterday, last week and ago.','“कल, पिछले साल, पहले” जैसे finished-past clues अक्सर V2 मांगते हैं।','S + V2',['मैंने उसे कल देखा। → I saw him yesterday.','वे पिछले सप्ताह पटना गए। → They went to Patna last week.','हम दो दिन पहले लौटे। → We returned two days ago.'],'After did/did not, use V1.'],
['08','TENSE','Past Continuous and Past Perfect','Past Continuous gives background action; Past Perfect marks the earlier of two past events.','एक past action चल रही थी या उससे भी पहले कोई action complete हो गया था—यह फर्क पहचानो।','was/were + V-ing | had + V3',['जब मैं पहुँचा, वे खाना खा रहे थे। → When I arrived, they were eating.','मेरे आने से पहले वह जा चुका था। → He had left before I came.'],'Look for the past reference point.'],
['09','METHOD','Questions and negatives','Auxiliaries control the structure in questions and negatives.','Question/negative में auxiliary पहचानो; main verb का form उसी के अनुसार तय करो।','Do/Does/Did + V1 | Be + V-ing | Have/Has + V3',['वह नहीं खेलता है। → He does not play.','क्या तुम गए? → Did you go?','क्या वे समाप्त कर चुके हैं? → Have they finished?'],'Avoid double marking: does not plays and did not went are wrong.'],
['10','METHOD','Articles: a, an, the','Hindi often omits articles, so English translation needs an extra definiteness/countability decision.','Singular countable noun के साथ context देखकर a/an/the check करो।','a/an + singular non-specific | the + specific/known',['मेरे पास एक किताब है। → I have a book.','उसने एक छाता खरीदा। → She bought an umbrella.','दरवाज़ा बंद करो। → Close the door.'],'Choose an by sound: an hour, an honest person.'],
['11','METHOD','Prepositions and collocations','English prepositions depend on relationship and collocation, not on one fixed Hindi equivalent.','“में/पर/से/को” के लिए context और English pattern देखो।','at + time | on + day/date/surface | in + period/place',['सोमवार को → on Monday','2012 में → in 2012','वह गणित में अच्छा है। → He is good at mathematics.'],'Memorise chunks such as good at, interested in, listen to and depend on.'],
['12','WORD ORDER','Hindi order vs English order','Hindi commonly uses Subject–Object–Verb while basic English commonly uses Subject–Verb–Object. Rebuild the sentence in English order.','Hindi में verb अंत में आ सकता है; English में S–V–O pattern check करो।','subject + verb + object/complement',['राम किताब पढ़ता है। → Ram reads a book.','मैं पानी पी रहा हूँ। → I am drinking water.','सीमा ने दरवाज़ा खोला। → Seema opened the door.'],'Do not translate word positions mechanically.'],
['13','WORD FORMS','Pronouns and agreement','Choose pronouns from context and ensure the finite verb agrees with the subject.','मैं/हम/वह/वे का English pronoun context से तय करो और agreement check करो।','pronoun → agreement → verb form',['वह रोज़ पढ़ती है। → She studies every day.','वे तैयार हैं। → They are ready.','हम देर से हैं। → We are late.'],'Do not choose he/she from habit without checking context.'],
['14','ASPECT','Habit vs action vs result vs duration','Several Hindi verb forms can look similar. Decide whether the action is habitual, in progress, completed with present relevance or continuing for a duration.','चार meanings compare करो: habit, action now, completed result, duration.','simple | continuous | perfect | perfect continuous',['वह पढ़ता है। → He studies.','वह पढ़ रहा है। → He is studying.','उसने पढ़ लिया है। → He has studied.','वह दो घंटे से पढ़ रहा है। → He has been studying for two hours.'],'Meaning selects aspect, not one Hindi ending alone.'],
['15','FUTURE','Future meaning and plans','Future can be expressed with will, be going to, Present Continuous and timetable-like Simple Present depending on meaning.','Prediction, prior plan, fixed arrangement और timetable को अलग पहचानो।','will + V1 | be going to + V1 | be + V-ing',['मैं कल तुमसे मिलूँगा। → I will meet you tomorrow.','हम रविवार को यात्रा कर रहे हैं। → We are travelling on Sunday.','वे अगले सप्ताह नई योजना शुरू करने वाले हैं। → They are going to start a new plan next week.'],'Choose the form from meaning, not only from “गा/गी/गे”.'],
['16','MIXED','Modals in translation','Translate ability, permission, advice, possibility and obligation with appropriate modals. Modals take the base verb.','सकता है, चाहिए, शायद, करना होगा जैसे meanings को context से चुनो।','modal + V1',['वह तैर सकता है। → He can swim.','तुम्हें मेहनत करनी चाहिए। → You should work hard.','शायद वह आए। → He might come.','तुम्हें समय पर पहुँचना होगा। → You must arrive on time.'],'Central modals normally take the base verb without to.'],
['17','CLAUSES','Reason, contrast, time and condition','Map Hindi clause relationships to English connectors: because, although, when, before, after, if and unless.','पहले relationship पहचानो—कारण, contrast, time या condition।','relationship → connector → clause pattern',['बारिश हुई इसलिए हम रुके। → We stopped because it rained.','हालाँकि वह थका था, उसने काम पूरा किया। → Although he was tired, he completed the work.','अगर बारिश होगी, हम घर पर रहेंगे। → If it rains, we will stay at home.'],'Connector choice follows the relationship, not a one-word memory trick.'],
['18','ADVANCED','Natural English and collocation','A translation can be grammatically possible but unnatural. Prefer standard English expressions while preserving the original sense.','Literal translation awkward हो तो natural phrase चुनो, meaning बदलो मत।','meaning → literal draft → natural revision',['मुझे भूख लगी है। → I am hungry.','मुझे ठंड लग रही है। → I am feeling cold.','उसे देर हो गई। → He was late.'],'Accuracy includes natural expression, not just word matching.'],
['19','ADVANCED','Relative and embedded clauses','Long Hindi sentences often contain a clause describing or identifying a noun. Keep that relationship attached in English.','जो/जिसने/जिसे/जहाँ जैसे words देखकर relative clause पहचानो।','noun + who/which/that/where + clause',['जो लड़की गा रही है वह मेरी बहन है। → The girl who is singing is my sister.','यह वह किताब है जिसे मैंने खरीदा। → This is the book that I bought.','यह वही जगह है जहाँ हम मिले थे। → This is the place where we met.'],'Check that the relative pronoun refers to the intended noun.'],
['20','FINAL AUDIT','Full translation audit','A final translation should be checked for meaning, tense, agreement, verb form, articles, prepositions, order, naturalness, spelling and punctuation.','अंतिम audit में sentence को पूरा पढ़ो—सिर्फ last verb को नहीं।','meaning → tense → agreement → form → small words → naturalness → punctuation',['मैंने उसे कल नहीं देखा। → I did not see him yesterday.','क्या उन्होंने काम पूरा कर लिया है? → Have they finished the work?','अगर तुम मेहनत करोगे, तुम सफल हो जाओगे। → If you work hard, you will succeed.'],'Read the final English sentence once as a reader.']
].map(x=>({n:x[0],group:x[1],title:x[2],simple:x[3],hindi:x[4],meaning:x[3],structure:x[5],examples:x[6],clue:x[7]}));

const EXAMPLES=[
['मैं रोज़ जल्दी उठता हूँ।','I get up early every day.'],['वह अक्सर अपने कमरे को साफ करती है।','She often cleans her room.'],['सूरज पूर्व में उगता है।','The sun rises in the east.'],['मैं अभी अपना गृहकार्य कर रहा हूँ।','I am doing my homework now.'],['वे इस समय क्रिकेट खेल रहे हैं।','They are playing cricket at the moment.'],['मैंने अपना प्रोजेक्ट पूरा कर लिया है।','I have completed my project.'],['उसने अभी-अभी खाना खाया है।','She has just eaten.'],['हम दो घंटे से इंतज़ार कर रहे हैं।','We have been waiting for two hours.'],['मैंने उसे कल फोन किया।','I called him yesterday.'],['जब शिक्षक आए, छात्र लिख रहे थे।','When the teacher arrived, the students were writing.'],['मेरे पहुँचने से पहले ट्रेन जा चुकी थी।','The train had left before I arrived.'],['मैं कल तुम्हारी मदद करूँगा।','I will help you tomorrow.'],['हम रविवार को यात्रा कर रहे हैं।','We are travelling on Sunday.'],['मैंने एक सेब खरीदा।','I bought an apple.'],['दरवाज़ा बंद कर दो।','Close the door.'],['वह मेज़ पर बैठा है।','He is sitting at the table.'],['राम अपने मित्र से बात करता है।','Ram talks to his friend.'],['क्या तुम मुझे जानते हो?','Do you know me?'],['वह यहाँ नहीं रहती है।','She does not live here.'],['क्या उन्होंने काम पूरा कर लिया है?','Have they finished the work?'],['तुम्हें सावधान रहना चाहिए।','You should be careful.'],['शायद वह आज आए।','He may come today.'],['हालाँकि वह थका था, उसने काम पूरा किया।','Although he was tired, he completed the work.'],['अगर बारिश होगी, हम घर पर रहेंगे।','If it rains, we will stay at home.'],['जो लड़का जीता, वह मेरा भाई है।','The boy who won is my brother.'],['कृपया मुझे पानी दे दीजिए।','Please give me some water.'],['मुझे भूख लगी है।','I am hungry.'],['मुझे देर हो गई।','I am late.'],['यह वह किताब है जिसे मैंने खरीदा।','This is the book that I bought.'],['तुम्हें नियमित अभ्यास करना चाहिए।','You should practise regularly.'],['हम समय पर स्कूल पहुँच गए।','We reached school on time.'],['वह गणित में अच्छी है।','She is good at mathematics.'],['मैंने वह किताब पहले पढ़ी है।','I have read that book before.'],['क्या आप मेरी मदद करेंगे?','Could you help me?'],['कृपया खिड़की बंद कर दीजिए।','Please close the window.'],['वे सोमवार से अभ्यास कर रहे हैं।','They have been practising since Monday.'],['वह पिछले सप्ताह पटना गया।','He went to Patna last week.'],['मुझे नहीं पता।','I do not know.'],['हमने रास्ता बदल दिया क्योंकि सड़क बंद थी।','We changed the route because the road was closed.'],['जब तक तुम लौटोगे, मैं काम खत्म कर चुका होऊँगा।','By the time you return, I will have finished the work.']
];

const TASKS=['Translate: मैं हर सुबह समाचार पढ़ता हूँ।','Translate: वह अभी अपनी बहन से बात कर रही है।','Translate: मैंने यह कहानी पहले पढ़ी है।','Translate: वे सुबह से मैदान में अभ्यास कर रहे हैं।','Translate: जब मैं पहुँचा, बस जा चुकी थी।','Translate: अगर तुम नियमित अभ्यास करोगे, तुम्हारी अंग्रेज़ी सुधरेगी।','Translate: तुम्हें अपने शिक्षक की बात ध्यान से सुननी चाहिए।','Translate: बारिश के कारण हम देर से पहुँचे।','Translate: जो छात्र मेहनत करता है वह आगे बढ़ता है।','Translate: कृपया मुझे यह प्रश्न समझा दीजिए।'];

const Q=[
['“मैं रोज़ स्कूल जाता हूँ।”',['I go to school every day.','I am go to school every day.','I went to school every day now.','I have go to school every day.'],0,'“रोज़” shows a habit, so Simple Present is correct.'],
['“वह अभी पढ़ रही है।”',['She is studying now.','She studies now.','She studied now.','She has study now.'],0,'“अभी…रही है” shows an action in progress.'],
['“मैंने उसे कल देखा।”',['I saw him yesterday.','I have seen him yesterday.','I see him yesterday.','I was see him yesterday.'],0,'Yesterday is a finished past reference.'],
['“वे दो घंटे से पढ़ रहे हैं।”',['They have been studying for two hours.','They are studying since two hours.','They studied for two hours now.','They have studied since two hours.'],0,'Duration continuing to now calls for Present Perfect Continuous + for.'],
['After “does not”, use…',['the base verb','V2','V3','V-ing'],0,'Does not already carries the auxiliary structure.'],
['Which is correct?',['Did you go there?','Did you went there?','Did you gone there?','Did you going there?'],0,'Did + V1.'],
['“एक घंटा” as duration is…',['for an hour','since an hour','on an hour','at an hour'],0,'For introduces duration.'],
['“सोमवार को” is normally…',['on Monday','in Monday','at Monday','to Monday'],0,'On is used with days.'],
['Which article is correct?',['an umbrella','a umbrella','an umbrellas','umbrella an'],0,'An is chosen before the vowel sound in umbrella.'],
['Basic English order is commonly…',['Subject + Verb + Object','Object + Subject + Verb','Verb + Object + Subject','Object + Verb + Subject'],0,'English basic clause order is commonly SVO.'],
['“वह गणित में अच्छा है।”',['He is good at mathematics.','He is good in mathematics.','He good at mathematics.','He is good to mathematics.'],0,'Good at is the standard pattern.'],
['“तुम्हें मेहनत करनी चाहिए।”',['You should work hard.','You should to work hard.','You should worked hard.','You should working hard.'],0,'Should takes the base verb.'],
['“शायद वह आए।”',['He might come.','He might to come.','He might came.','He comes might.'],0,'Might + V1 expresses possibility.'],
['Which connector shows reason?',['because','although','if','when'],0,'Because introduces a reason.'],
['Which connector shows contrast?',['although','because','if','when'],0,'Although introduces contrast.'],
['Which connector shows condition?',['if','although','because','when'],0,'If introduces a condition.'],
['Which sentence is correct?',['She has finished her homework.','She has finish her homework.','She have finished her homework.','She has finishing her homework.'],0,'Present Perfect = has/have + V3.'],
['Which uses “since” correctly?',['She has been working since morning.','She has been working since two hours.','She worked since morning yesterday.','She is working since 2012.'],0,'Since introduces a starting point.'],
['Which uses “for” correctly?',['They have been waiting for two hours.','They have been waiting since two hours.','They waited for Monday.','They are waiting for 2012.'],0,'For introduces duration.'],
['Which translation preserves natural word order?',['Ram reads a book.','Ram a book reads.','Ram reading book.','Reads Ram a book.'],0,'Natural English uses subject + verb + object.'],
['Which is correct for a polite request?',['Could you help me?','Could you to help me?','Did you help me?','Could you helped me?'],0,'Could + base verb is a polite request.'],
['“जो लड़की गा रही है…” begins a…',['relative clause','time clause','condition clause','result clause'],0,'Who/which/that can introduce relative clauses.'],
['Which is the natural translation of “मुझे भूख लगी है”?',['I am hungry.','I am having hunger.','I have hungry.','I am hunger.'],0,'English uses the adjective hungry.'],
['Which is best for “मुझे देर हो गई”?',['I am late.','I am late yesterday.','I do late.','I geted late.'],0,'I am late is natural English for the state.'],
['Which sentence keeps past tense consistent?',['When I arrived, she was sleeping.','When I arrive, she was sleeping.','When I arrived, she is sleeping.','When I arrive, she slept yesterday now.'],0,'The narrative reference is in the past.'],
['Which shows the earlier past event?',['The train had left before we arrived.','The train has left before we arrived.','The train leaves before we arrived.','The train will leave before we arrived.'],0,'Had left marks the earlier past event.'],
['Which is a correct first conditional?',['If it rains, we will stay home.','If it will rain, we will stay home.','If it rains, we stayed home.','If it raining, we will stayed home.'],0,'Present simple follows if; will + V1 is used in the result clause.'],
['Which sentence is grammatically correct?',['He does not understand the question.','He does not understands the question.','He do not understand the question.','He not does understand the question.'],0,'Does not + V1.'],
['Which sentence correctly translates an arrangement?',['We are meeting the teacher tomorrow.','We are meet the teacher tomorrow.','We met the teacher tomorrow.','We are meeting teacher yesterday.'],0,'Present Continuous can express a fixed arrangement.'],
['Which sentence uses a modal correctly?',['You must finish the work.','You must to finish the work.','You must finished the work.','You must finishing the work.'],0,'Central modals take the base verb.'],
['Which sentence best preserves contrast?',['Although he was tired, he completed the work.','Because he was tired, he completed the work.','If he was tired, he completed the work.','When he was tired, but completed the work.'],0,'Although expresses contrast.'],
['Which sentence correctly uses “the”?',['Close the door.','Close a door the.','Close an door.','Close door the.'],0,'The points to a specific/known referent.'],
['Which is correct?',['The girl who won is my sister.','The girl which won is my sister.','The girl who win is my sister.','The girl won who is my sister.'],0,'Who refers to a person.'],
['Which translation is natural?',['We changed the route because the road was closed.','We changed route because road closed was.','We route changed because the road close.','Because road closed, route we changed.'],0,'Natural English preserves the reason relationship while using English order.'],
['What should be checked first in a difficult translation?',['the whole meaning and time reference','the longest synonym','the final punctuation only','the first noun only'],0,'Meaning and reference time guide the rest of the translation.'],
['What does a final audit include?',['meaning, tense, agreement, word order and small words','only spelling','only the verb','only the title'],0,'A complete audit checks the whole sentence.'],
['Which statement is true?',['Literal translation can be grammatical but unnatural.','Literal translation is always best.','Hindi word order should never change.','English never uses articles.'],0,'Good translation may require restructuring for natural English.'],
['Which translation uses “at” correctly?',['The class starts at 9 a.m.','The class starts on 9 a.m.','The class starts in 9 a.m.','The class starts to 9 a.m.'],0,'At is used with a precise time.'],
['Which sentence uses “in” correctly?',['He was born in 2012.','He was born on 2012.','He was born at 2012.','He was born to 2012.'],0,'In is used with years.'],
['Which sentence uses “on” correctly?',['We met on Monday.','We met in Monday.','We met at Monday.','We met to Monday.'],0,'On is used with days.'],
['Which is correct for a vowel sound?',['an honest person','a honest person','an persons','a honest'],0,'Honest begins with a vowel sound.'],
['Which sentence expresses advice?',['You should revise your answers.','You must revise your answers.','You may revise your answers.','You can revise your answers.'],0,'Should commonly expresses advice.'],
['Which sentence expresses possibility?',['He may arrive late.','He must arrive late.','He should arrive late because certainty.','He can arrived late.'],0,'May + V1 expresses possibility.'],
['Which sentence expresses ability?',['She can swim.','She can to swim.','She can swimming.','She can swam.'],0,'Can + base verb expresses ability.'],
['Which phrase is more natural?',['I am hungry.','I am having hunger.','I have hungry.','I am hunger.'],0,'English normally uses the adjective hungry.'],
['Which translation keeps the original tone of “कृपया बैठिए”?',['Please sit down.','Sit down now!','Please to sit down.','Please sat down.'],0,'Please + base verb preserves the polite request.'],
['Which is correct?',['They have already arrived.','They have already arrive.','They already has arrived.','They are already arrived.'],0,'Have + V3 forms the Present Perfect.'],
['Which is correct?',['I did not see him yesterday.','I did not saw him yesterday.','I did not seen him yesterday.','I do not saw him yesterday.'],0,'Did not + V1.'],
['Which is correct?',['He is good at mathematics.','He is good to mathematics.','He good at mathematics.','He is good on mathematics.'],0,'Good at is the standard collocation.'],
['Which best translates “वह यहाँ नहीं रहती है”?',['She does not live here.','She does not lives here.','She is not live here.','She did not lives here.'],0,'Simple Present negative uses does not + V1.'],
['Which sentence best translates “हम समय पर पहुँच गए”?',['We arrived on time.','We arrive on time yesterday.','We were arrive on time.','We have arrived on time yesterday.'],0,'A completed past event takes arrived.'],
['Which sentence best translates “मैंने वह किताब पहले पढ़ी है”?',['I have read that book before.','I read that book yesterday before.','I have readed that book.','I am read that book before.'],0,'Present Perfect expresses an unspecified past experience with present relevance.'],
['Which is the best translation strategy for a long sentence?',['identify clause relationships and rebuild the English sentence','translate every word in the same order','ignore connectors','use difficult vocabulary'],0,'Long sentences are safer when their relationships are analysed first.']
];

const BANKS={practice:Q.slice(0,30),challenge:Q.slice(10,45),test:Q};
const rotate=(questions,mode)=>{const shift=mode==='challenge'?1:mode==='test'?2:0;return questions.map((item,i)=>{const[q,opts,a,e]=item;const out=[...opts];const correct=out[a];const move=(a+shift+i)%out.length;out.splice(a,1);out.splice(move,0,correct);return[q,out,move,e]})};
const readMode=()=>{if(typeof window==='undefined')return'learn';const m=new URLSearchParams(window.location.search).get('mode');return['practice','challenge','test'].includes(m)?m:'learn'};

export default function EnglishTranslationTopicComplete({onBack=()=>{},addXp=()=>{},finishSession=()=>{}}){
 const[mode,setMode]=useState(readMode);const[lesson,setLesson]=useState(0);
 useEffect(()=>{const sync=()=>setMode(readMode());window.addEventListener('popstate',sync);sync();return()=>window.removeEventListener('popstate',sync)},[]);
 const bank=useMemo(()=>rotate(BANKS[mode]||BANKS.practice,mode),[mode]);
 const go=m=>{const p=new URLSearchParams(window.location.search);p.set('page','language-skills');p.set('subject','english');p.set('languageSkills','1');p.set('topic','translation');if(m==='learn')p.delete('mode');else p.set('mode',m);window.history.pushState({},'',`${window.location.pathname}?${p}${window.location.hash||''}`);window.dispatchEvent(new PopStateEvent('popstate'))};
 const nextMode=mode==='practice'?'challenge':mode==='challenge'?'test':'practice';const current=LESSONS[lesson];
 if(['practice','challenge','test'].includes(mode)&&new URLSearchParams(window.location.search).get('mode')===mode)return <EnglishTimedQuiz title="Hindi → English Translation" mode={mode} getBank={()=>bank} onModeChange={go} onBack={()=>go('learn')} addXp={addXp} finishSession={finishSession} onNextLevel={()=>go(nextMode)} secondsPerQuestion={mode==='test'?55:50}/>;
 return <main className="et-shell">
 <header className="et-hero"><div><button type="button" className="et-back" onClick={onBack}>← Language</button><span className="et-kicker">ENGLISH • LANGUAGE • TRANSLATION</span><h1>Hindi → English Translation</h1><p>Understand the meaning, choose the English structure, and audit the final sentence.</p></div><div className="et-stat"><strong>{LESSONS.length}</strong><span>guided lessons</span></div></header>
 <nav className="et-modebar"><button className="active" type="button">Learn</button><button type="button" onClick={()=>go('practice')}>Practice</button><button type="button" onClick={()=>go('challenge')}>Challenge</button><button type="button" onClick={()=>go('test')}>Final Test</button></nav>
 <section className="et-progress"><div><span>Lesson {lesson+1} of {LESSONS.length}</span><b>{Math.round((lesson+1)*100/LESSONS.length)}%</b></div><div className="et-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></section>
 <div className="et-layout"><aside className="et-map"><div className="et-map-title">Lesson map</div>{LESSONS.map((x,i)=><button type="button" key={x.n} className={i===lesson?'selected':''} onClick={()=>setLesson(i)}><span>{x.n}</span><div><strong>{x.title}</strong><small>{x.group}</small></div></button>)}</aside>
 <section><article className="et-lesson"><span className="et-badge">{current.group}</span><h2>{current.title}</h2><p className="et-simple">{current.simple}</p><div className="et-inline-guide"><span>समझने का आसान तरीका</span><p>{current.hindi}</p></div><div className="et-grid"><section><h3>Core idea</h3><p>{current.meaning}</p></section><section><h3>Structure</h3><p>{current.structure}</p></section></div><section className="et-examples"><h3>Quick examples</h3>{current.examples.map((x,i)=><div key={i}>{x}</div>)}</section><div className="et-clue"><strong>Exam clue</strong><p>{current.clue}</p></div></article>
 <div className="et-lesson-nav"><button type="button" disabled={lesson===0} onClick={()=>setLesson(v=>Math.max(0,v-1))}>← Previous lesson</button><span>{lesson+1} / {LESSONS.length}</span><button type="button" onClick={()=>setLesson(v=>Math.min(LESSONS.length-1,v+1))}>{lesson===LESSONS.length-1?'Review audit':'Next lesson →'}</button></div>
 <section className="et-method"><h2>Translation workflow</h2><div className="et-method-grid">{['Understand the complete Hindi meaning','Identify time and action type','Choose the English pattern','Select auxiliary + verb form','Add articles and prepositions','Audit naturalness and correctness'].map((x,i)=><div key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></section>
 <section className="et-models"><div className="et-models-head"><span>TRANSLATION LAB</span><h2>40+ worked translation examples</h2><p>Read the Hindi source, compare the English build, then identify the grammar decision.</p></div><div className="et-model-grid">{EXAMPLES.map(([hi,en],i)=><article key={i}><small>PAIR {String(i+1).padStart(2,'0')}</small><h3>{hi}</h3><div className="et-arrow">↓</div><p className="et-model-en">{en}</p><p className="et-model-why">Check: meaning • tense • order • small words • naturalness</p></article>)}</div></section>
 <section className="et-errors"><h2>Common translation traps</h2><div className="et-error-grid"><div>Word-for-word copying can destroy natural English order.</div><div>After did/does, use V1.</div><div>Since = starting point; for = duration.</div><div>Do not add articles automatically; decide from context.</div><div>Hindi postpositions do not map to one English preposition every time.</div><div>Modal + base verb: can go, should study, may come.</div><div>Check tense consistency across connected clauses.</div><div>Preserve polite or negative meaning rather than changing tone.</div></div></section>
 <section className="et-writing"><h2>Translate it yourself</h2><p>Draft without looking at the models, then audit the result.</p><div className="et-task">{TASKS[lesson%TASKS.length]}</div><div className="et-checks"><span>✓ Meaning</span><span>✓ Time / tense</span><span>✓ Agreement</span><span>✓ Verb form</span><span>✓ Word order</span><span>✓ Articles / prepositions</span><span>✓ Natural English</span><span>✓ Punctuation</span></div></section>
 </section></div>
 <section className="et-audit"><div><span>FINAL AUDIT</span><h2>Ready to translate under exam conditions?</h2><p>Understand → choose structure → build → revise → submit.</p></div><button type="button" onClick={()=>go('practice')}>Start Practice →</button></section>
 </main>;
}
