import React,{useState} from 'react';
import PanoramaTimedQuiz from './PanoramaTimedQuiz.jsx';
import './english-reader.css';
import './english-panorama.css';

const study={
 title:'The Gift of the Magi',author:'O. Henry',sourceNote:'Class 9 English • The Panorama • Prose Chapter 9',
 intro:'A short story about Jim and Della, a young married couple with little money but deep love. On Christmas Eve, each secretly gives up a treasured possession to buy a gift for the other. The ending uses irony to show that love, sacrifice and thoughtful giving can be more valuable than material wealth.',
 sections:[
 {title:'Part 1 — Della’s problem',flow:'Della wants to buy Jim a Christmas present, but after careful saving she has only one dollar and eighty-seven cents. She counts the money three times because it is not enough for the gift she wants.',explanation:'डेला जिम के लिए क्रिसमस का उपहार खरीदना चाहती है, लेकिन उसके पास केवल 1 डॉलर 87 सेंट हैं। वह पैसे को तीन बार गिनती है क्योंकि यह रकम उसके मनचाहे उपहार के लिए पर्याप्त नहीं है।',vocabulary:[['meagre','बहुत कम'],['saving','बचत'],['count','गिनना'],['Christmas Eve','क्रिसमस की पूर्व संध्या'],['expense','खर्च']],exam:'Key fact: Della has $1.87 and counts it three times.',think:'Why does the small amount create the central conflict?'},
 {title:'Part 2 — Jim and Della’s home',flow:'Jim and Della live in a modest furnished flat. Their income is limited, so there is little money left after ordinary expenses. The story contrasts financial hardship with emotional richness.',explanation:'जिम और डेला एक साधारण सुसज्जित फ्लैट में रहते हैं। उनकी आय सीमित है और सामान्य खर्चों के बाद बहुत कम पैसा बचता है। फिर भी उनका प्रेम गहरा है।',vocabulary:[['modest','सादा'],['furnished','सुसज्जित'],['income','आय'],['hardship','कठिनाई'],['affection','स्नेह']],exam:'Remember the contrast: little money, strong affection.',think:'How can people be emotionally rich while being financially poor?'},
 {title:'Part 3 — Della’s treasured hair',flow:'Della is proud of her long, beautiful hair. It is one of the couple’s most valuable possessions and becomes the means by which she can raise money for Jim’s gift.',explanation:'डेला अपने लंबे और सुंदर बालों पर गर्व करती है। यह उनकी बहुमूल्य संपत्तियों में से एक है और इसी को बेचकर वह जिम के लिए पैसे जुटाती है।',vocabulary:[['treasured','बहुमूल्य माना हुआ'],['possession','संपत्ति'],['proud','गर्वित'],['raise money','पैसे जुटाना'],['sacrifice','त्याग']],exam:'Della sacrifices her hair because Jim’s happiness matters more to her.',think:'Why does a personal possession make the sacrifice meaningful?'},
 {title:'Part 4 — Jim’s gold watch',flow:'Jim owns a valuable gold watch inherited through his family. Like Della’s hair, it is a treasured possession, and its later sale creates the second half of the story’s parallel.',explanation:'जिम के पास परिवार से मिली हुई बहुमूल्य सोने की घड़ी है। डेला के बालों की तरह घड़ी भी उसकी प्रिय संपत्ति है और बाद में इसका त्याग कहानी के समानांतर को पूरा करता है।',vocabulary:[['inherited','विरासत में मिला'],['gold watch','सोने की घड़ी'],['valuable','मूल्यवान'],['heirloom','पारिवारिक विरासत'],['precious','बहुमूल्य']],exam:'The gold watch is Jim’s great treasured possession.',think:'Why can an heirloom have emotional value beyond its price?'},
 {title:'Part 5 — Della’s decision',flow:'Della decides to sell her hair so that she can buy Jim a suitable Christmas gift. She goes to Madame Sofronie, who buys her hair.',explanation:'डेला जिम के लिए उपयुक्त क्रिसमस उपहार खरीदने के लिए अपने बाल बेचने का निर्णय लेती है। वह मैडम सोफ्रोनी के पास जाती है, जो उसके बाल खरीद लेती है।',vocabulary:[['decision','निर्णय'],['suitable','उपयुक्त'],['sell','बेचना'],['buyer','खरीदार'],['determination','दृढ़ता']],exam:'Sequence: money shortage → decision → Madame Sofronie → hair sold.',think:'What does Della’s decision reveal about her priorities?'},
 {title:'Part 6 — Buying Jim’s present',flow:'After selling her hair, Della looks for something suitable for Jim. She finds a simple platinum fob chain that matches the quality of his treasured watch.',explanation:'बाल बेचने के बाद डेला जिम के लिए उपयुक्त उपहार खोजती है। उसे एक सादी लेकिन मूल्यवान प्लैटिनम फोब चेन मिलती है जो उसकी घड़ी के लिए उपयुक्त है।',vocabulary:[['platinum','प्लैटिनम'],['fob chain','घड़ी की चेन'],['quality','गुणवत्ता'],['suitable','उपयुक्त'],['purchase','खरीदना']],exam:'Della buys a platinum fob chain for Jim’s watch.',think:'What does her choice tell us about how carefully she thinks about Jim?'},
 {title:'Part 7 — Anxiety before Jim arrives',flow:'Della returns home and worries about Jim’s reaction to her changed appearance. She prepares herself for his arrival and hopes that he will understand why she cut her hair.',explanation:'डेला घर लौटकर अपनी बदली हुई शक्ल को लेकर चिंतित होती है। वह जिम के आने की प्रतीक्षा करती है और चाहती है कि वह उसके निर्णय को समझे।',vocabulary:[['anxiety','चिंता'],['appearance','दिखावट'],['reaction','प्रतिक्रिया'],['prepare','तैयार करना'],['understand','समझना']],exam:'The waiting scene creates suspense.',think:'How does the author use waiting to build tension?'},
 {title:'Part 8 — Jim’s strange reaction',flow:'When Jim enters, he looks at Della with a strange, fixed expression. Della cannot immediately understand his reaction and becomes nervous.',explanation:'जिम घर आता है और डेला को एक अजीब भाव से देखता है। डेला उसकी प्रतिक्रिया को तुरंत नहीं समझ पाती और घबरा जाती है।',vocabulary:[['fixed','स्थिर'],['expression','भाव-भंगिमा'],['nervous','घबराया हुआ'],['stare','एकटक देखना'],['suspense','रोमांच / उत्सुकता']],exam:'Jim’s reaction is deliberately delayed before the explanation.',think:'Why does the author delay the meaning of Jim’s expression?'},
 {title:'Part 9 — Jim’s gift: the combs',flow:'Jim has brought Della a beautiful set of combs that she had admired for a long time. The gift was chosen for her long hair, which she has already sold.',explanation:'जिम डेला के लिए सुंदर कंघियों का सेट लाता है, जिसे डेला लंबे समय से चाहती थी। लेकिन डेला अपने लंबे बाल बेच चुकी है, इसलिए उपहार में विडंबना पैदा होती है।',vocabulary:[['combs','कंघियाँ'],['admire','पसंद से देखना'],['delight','प्रसन्न करना'],['irony','विडंबना'],['long for','बहुत इच्छा करना']],exam:'The combs were meant for Della’s long hair.',think:'Why does the gift remain meaningful although it cannot be used immediately?'},
 {title:'Part 10 — Jim has sold the watch',flow:'Jim reveals that he sold his gold watch to buy Della’s gift. Therefore Della’s platinum chain cannot be used with the watch she expected him to have.',explanation:'जिम बताता है कि उसने डेला के लिए उपहार खरीदने के लिए अपनी सोने की घड़ी बेच दी। इसलिए डेला की खरीदी हुई चेन फिलहाल घड़ी के बिना रह जाती है।',vocabulary:[['reveal','प्रकट करना'],['sold','बेचा'],['sacrifice','त्याग'],['temporarily','फिलहाल'],['purpose','उद्देश्य']],exam:'Jim’s sold watch is the matching irony to Della’s sold hair.',think:'How do the two sacrifices mirror each other?'},
 {title:'Part 11 — The two sacrifices',flow:'Della gives up her hair to buy Jim a chain; Jim gives up his watch to buy Della combs. Each person sacrifices the object that makes the other person’s gift useful.',explanation:'डेला जिम के लिए चेन खरीदने हेतु अपने बाल त्यागती है और जिम डेला के लिए कंघियाँ खरीदने हेतु घड़ी त्यागता है। दोनों त्याग एक-दूसरे के समानांतर हैं।',vocabulary:[['parallel','समानांतर'],['mutual','पारस्परिक'],['selfless','निस्वार्थ'],['useful','उपयोगी'],['devotion','समर्पण']],exam:'The central structural device is the parallel sacrifice.',think:'Why is the parallel more powerful than only one character sacrificing?'},
 {title:'Part 12 — Gifts versus usefulness',flow:'The gifts are temporarily unusable, but this does not make them worthless. Their real significance comes from the thought and sacrifice behind them.',explanation:'दोनों उपहार अभी तुरंत उपयोगी नहीं हैं, लेकिन इससे उनका मूल्य कम नहीं होता। उनका वास्तविक महत्व प्रेम, विचार और त्याग में है।',vocabulary:[['usefulness','उपयोगिता'],['significance','महत्त्व'],['intention','भावना / उद्देश्य'],['worth','मूल्य'],['meaningful','अर्थपूर्ण']],exam:'Material usefulness is different from emotional value.',think:'Can a gift be valuable even when it is not immediately useful?'},
 {title:'Part 13 — The Magi',flow:'The narrator compares Jim and Della with the Magi, the traditional wise gift-givers associated with the birth of Christ. The comparison focuses on wisdom in giving rather than wealth.',explanation:'कथावाचक जिम और डेला की तुलना Magi से करता है, जिन्हें बुद्धिमान उपहार देने वालों के रूप में जाना जाता है। यह तुलना धन की नहीं बल्कि समझदारी से देने की है।',vocabulary:[['Magi','बुद्धिमान उपहार देने वाले'],['wise','बुद्धिमान'],['giving','देने की भावना'],['Christ','मसीह'],['comparison','तुलना']],exam:'The title becomes clear through the final comparison.',think:'Why are they called wise even though their gifts become impractical?'},
 {title:'Part 14 — Love expressed through sacrifice',flow:'Jim and Della demonstrate that love is shown through concern for the other person. They willingly surrender possessions they value in order to make each other happy.',explanation:'जिम और डेला यह दिखाते हैं कि प्रेम दूसरे व्यक्ति की खुशी और चिंता से प्रकट होता है। दोनों अपनी प्रिय वस्तुएँ स्वेच्छा से त्याग देते हैं।',vocabulary:[['concern','चिंता / परवाह'],['surrender','त्याग देना'],['happiness','खुशी'],['generosity','उदारता'],['devotion','समर्पण']],exam:'Core theme: selfless love and sacrifice.',think:'What is the difference between expensive giving and selfless giving?'},
 {title:'Part 15 — Irony, title and message',flow:'The story ends with a tender irony: the gifts cannot serve their intended purpose at once, yet they are priceless evidence of love. The title emphasizes the wisdom of selfless giving.',explanation:'कहानी एक कोमल विडंबना के साथ समाप्त होती है। उपहार तुरंत उपयोगी नहीं हैं, फिर भी वे प्रेम के अमूल्य प्रमाण हैं। शीर्षक निस्वार्थ देने की बुद्धिमत्ता को सामने लाता है।',vocabulary:[['irony','विडंबना'],['tender','स्नेहपूर्ण'],['priceless','अमूल्य'],['evidence','प्रमाण'],['message','संदेश']],exam:'Long-answer focus: explain the title, irony and central message.',think:'What makes the final irony both humorous and deeply affectionate?'}
 ],
 wordStudy:{title:'Word Study',items:[['meagre','very small in amount'],['parsimony','extreme unwillingness to spend money'],['imputation','attribution of blame or fault'],['fob chain','a chain attached to a pocket watch'],['platinum','a valuable silver-white metal'],['discreet','careful and unobtrusive'],['intoxicate','to delight greatly'],['meretricious','showy but lacking real value'],['sacrifice','giving up something valuable for another purpose'],['priceless','too valuable to be measured by money']],formation:['love → lovely','beauty → beautiful','value → valuable','care → careful','thought → thoughtful','self → selfless']},
 grammar:{title:'Grammar Lab — Active and Passive Voice',intro:'The chapter’s language work can be practised through active and passive constructions. The tense remains unchanged while the object of the active sentence becomes the subject of the passive sentence.',points:[['Present simple','Della buys a gift. → A gift is bought by Della.'],['Past simple','Jim sold his watch. → His watch was sold by Jim.'],['Modal','They can use the chain. → The chain can be used by them.'],['Past perfect','Della had sold her hair. → Her hair had been sold by Della.'],['Key rule','Use the correct form of be + past participle (V3), and use “by” only when the doer is useful to mention.']]},
 examPrep:{veryShort:[['How much money did Della have?','$1.87.'],['Who bought Della’s hair?','Madame Sofronie.'],['What did Della buy?','A platinum fob chain.'],['What did Jim buy?','A set of combs.']],short:[['Why did Della sell her hair?','To raise money for Jim’s Christmas gift.'],['Why was the chain temporarily useless?','Jim had sold his watch.'],['Why were the combs temporarily useless?','Della had sold her long hair.'],['What is the central irony?','Each gift is meant for a possession that the giver has already sacrificed.']],long:[['Explain the title “The Gift of the Magi”.','Jim and Della are compared with the wise Magi because their gifts express thoughtful, selfless love and sacrifice rather than mere wealth.'],['Describe the role of sacrifice in the story.','Both characters give up cherished possessions for each other, making sacrifice the clearest evidence of their love.']],discussion:['Is a gift judged by price or by the intention behind it? Discuss with reference to the story.','How does O. Henry use irony to strengthen the ending?']},
 composition:['Write a letter to a friend explaining what Jim and Della teach us about love and sacrifice.','Write a paragraph on: “The value of a gift lies in the feeling behind it.”'],
 translationPractice:[['डेला जिम के लिए एक उपहार खरीदना चाहती थी।','Della wanted to buy a gift for Jim.'],['उसने अपने बाल बेच दिए।','She sold her hair.'],['जिम ने अपनी घड़ी बेच दी थी।','Jim had sold his watch.'],['उनके उपहार तुरंत उपयोगी नहीं थे।','Their gifts were not immediately useful.'],['प्रेम धन से अधिक मूल्यवान है।','Love is more valuable than money.'],['यह चेन जिम की घड़ी के लिए खरीदी गई थी।','This chain was bought for Jim’s watch.']],
 activities:[{title:'Sacrifice Chart',instruction:'Make a two-column chart showing what Della gives up, what Jim gives up, and what each buys.'},{title:'Theme Discussion',instruction:'Discuss whether the emotional value of a gift can be greater than its material price.'},{title:'Title Analysis',instruction:'Explain why the final comparison with the Magi is appropriate.'}],
};

const practice=[
 {q:'How much money did Della have?',o:['$1.87','$2.87','$1.17','$3.87'],a:0,e:'Della had one dollar and eighty-seven cents.'},
 {q:'How many times did Della count her money?',o:['Once','Twice','Three times','Four times'],a:2,e:'She counted the money three times.'},
 {q:'Who were Jim and Della?',o:['Brother and sister','Husband and wife','Friends','Neighbours'],a:1,e:'They were a young married couple.'},
 {q:'What was Della proud of?',o:['A gold watch','A platinum chain','Her long hair','A new dress'],a:2,e:'Her long hair was one of her prized possessions.'},
 {q:'What was Jim’s precious possession?',o:['A gold watch','A ring','A coat','A necklace'],a:0,e:'Jim owned a valuable gold watch.'},
 {q:'Why did Della sell her hair?',o:['To pay rent','To buy food','To buy Jim a gift','To travel'],a:2,e:'She needed money for Jim’s Christmas present.'},
 {q:'Who bought Della’s hair?',o:['Madame Sofronie','Jim','A grocer','A friend'],a:0,e:'Madame Sofronie bought her hair.'},
 {q:'What did Della buy for Jim?',o:['A platinum fob chain','A set of combs','A watch','A ring'],a:0,e:'She bought a platinum fob chain for his watch.'},
 {q:'What did Jim buy for Della?',o:['A dress','A set of combs','A necklace','A book'],a:1,e:'Jim bought a beautiful set of combs.'},
 {q:'What did Jim do with his watch?',o:['Repaired it','Lost it','Sold it','Hid it'],a:2,e:'He sold the watch to buy Della’s gift.'},
 {q:'Why was the chain temporarily useless?',o:['It was broken','Jim had sold the watch','It was too short','Della lost it'],a:1,e:'The watch it was meant for had been sold.'},
 {q:'Why were the combs temporarily useless?',o:['They were broken','Della lost them','Della had sold her long hair','Jim returned them'],a:2,e:'Della no longer had her long hair.'},
 {q:'What is the main theme?',o:['Competition','Selfless love and sacrifice','Travel','Social status'],a:1,e:'The story focuses on selfless love and sacrifice.'},
 {q:'Why are Jim and Della compared to the Magi?',o:['They were wealthy','They were famous','They gave thoughtful gifts through sacrifice','They were kings'],a:2,e:'Their wise giving through sacrifice links them to the Magi.'},
 {q:'What makes the gifts valuable?',o:['Their size','Their colour','The love and sacrifice behind them','Their market price'],a:2,e:'Their emotional meaning is greater than their material usefulness.'}
];

const challenge=[
 {q:'Why does Della count her money three times?',o:['She wants to spend less','She hopes it may somehow be enough','She is practising arithmetic','She checks Jim’s income'],a:1,e:'The repeated counting shows her anxiety over the small amount.'},
 {q:'What does the couple’s limited income establish?',o:['They are careless','They are financially comfortable','They must make difficult choices about spending','They dislike Christmas'],a:2,e:'Financial difficulty creates the practical problem behind the story.'},
 {q:'Why is Della’s hair an effective symbol?',o:['It is cheap','It represents a treasured personal possession','It belongs to Jim','It is needed for work'],a:1,e:'The hair has personal value, so giving it up demonstrates sacrifice.'},
 {q:'Why is Jim’s watch an heirloom?',o:['It was bought that day','It came through his family','It belonged to Della','It was made of platinum'],a:1,e:'The watch was inherited through Jim’s family.'},
 {q:'What happens at Madame Sofronie’s shop?',o:['Della buys a watch','Della gets money for her hair','Della meets Jim','Della loses her purse'],a:1,e:'Her hair is sold so she can raise money.'},
 {q:'Why is Della anxious after cutting her hair?',o:['She hates Christmas','She fears Jim’s reaction','She lost the chain','She has no home'],a:1,e:'She worries about how Jim will feel about her changed appearance.'},
 {q:'Which quality best describes Della’s choice?',o:['Selfishness','Indifference','Self-sacrifice','Dishonesty'],a:2,e:'She gives up a valued possession for Jim.'},
 {q:'What is the key irony involving the combs?',o:['They are broken','They were meant for long hair Della has sold','They belong to Jim','They are cheap'],a:1,e:'Jim buys combs for hair that Della no longer has.'},
 {q:'What is the key irony involving the platinum chain?',o:['It is too cheap','It is meant for a watch Jim has sold','It is made of wood','It belongs to Madame Sofronie'],a:1,e:'The chain’s intended watch is gone.'},
 {q:'Why should the gifts not be judged only by usefulness?',o:['They are ordinary','Their emotional intention gives them greater meaning','They are expensive','Christmas is unimportant'],a:1,e:'The story emphasizes emotional value rather than practical usefulness.'},
 {q:'What does the parallel sacrifice show?',o:['Only Della sacrifices','Only Jim sacrifices','Both put the other first','Neither understands love'],a:2,e:'Both characters surrender treasured possessions for each other.'},
 {q:'How does suspense work before Jim explains his reaction?',o:['It reveals the ending early','It makes readers wait for the reason','It removes the conflict','It introduces a new setting'],a:1,e:'The delayed explanation creates curiosity.'},
 {q:'What does the story suggest about poverty?',o:['It prevents all happiness','Financial hardship can exist with deep emotional wealth','Poor people cannot love','Money is the only form of security'],a:1,e:'Jim and Della have little money but strong affection.'},
 {q:'Why is the title clearer after the ending?',o:['It names their house','The final comparison links them with the Magi','It names the shop','It has no connection to the plot'],a:1,e:'The title is explained by the final comparison.'},
 {q:'Which contrast is central to the story?',o:['Old and new','City and village','Material price and emotional value','Youth and age'],a:2,e:'The story contrasts price with the emotional worth of a gift.'},
 {q:'Why can the gifts be called wise?',o:['They are expensive','They show careful knowledge of what the other desired','They can be resold','They are fashionable'],a:1,e:'Each gift is based on the other person’s cherished desire.'},
 {q:'What does Jim’s purchase reveal?',o:['He ignores Della’s wishes','He knew Della had long wanted the combs','He wants to embarrass her','He dislikes gifts'],a:1,e:'He chose something he knew Della had admired.'},
 {q:'Which phrase best describes the ending?',o:['Purely tragic','Ironically tender','Completely comic','Unrelated to the title'],a:1,e:'The ending combines irony with tenderness.'},
 {q:'What would most weaken the central theme?',o:['Both sacrifice','The gifts reflect personal knowledge','They buy gifts only to impress strangers','They face financial difficulty'],a:2,e:'The story depends on personal, selfless concern.'},
 {q:'Why is the $1.87 amount important beyond arithmetic?',o:['It proves wealth','It creates pressure that leads to sacrifice','It tells Jim’s age','It describes the shop'],a:1,e:'The small amount motivates Della’s sacrifice.'},
 {q:'What does sacrifice mean in this story?',o:['Spending money on oneself','Giving up something valuable for another person’s happiness','Avoiding Christmas','Buying expensive things'],a:1,e:'Both spouses give up cherished possessions for the other.'},
 {q:'Why are Jim and Della called Magi rather than simply generous?',o:['They were kings','The comparison highlights wise, meaningful giving','They were merchants','They knew astrology'],a:1,e:'The Magi comparison elevates their selfless giving.'},
 {q:'What is the strongest inference from the ending?',o:['Objects have no value','The worth of a gift can lie chiefly in intention, love and sacrifice','Money never matters','Useful gifts are always better'],a:1,e:'The story places emotional meaning above practical usefulness.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)];

function StudyBlock({s}){return <article className="pg-study-section"><h3>{s.title}</h3><p>{s.flow}</p><div className="pg-explain"><strong>हिंदी में समझें</strong><p>{s.explanation}</p></div><div className="pg-vocab"><strong>Vocabulary</strong><div>{s.vocabulary.map(([a,b])=><span key={a}><b>{a}</b> — {b}</span>)}</div></div><div className="pg-exam"><strong>Exam Point</strong><p>{s.exam}</p></div><div className="pg-think"><strong>Think</strong><p>{s.think}</p></div></article>}

export function EnglishPanoramaChapter9({initialMode='learn',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode);const [quizOpen,setQuizOpen]=useState(initialMode!=='learn');
 const openMode=m=>{setMode(m);setQuizOpen(m!=='learn')};
 const bank=mode==='practice'?practice:mode==='challenge'?challenge:finalTest;
 return <div className="pg-shell"><div className="pg-wrap"><button className="pg-back" onClick={onBack}>← Back to English</button>
 <header className="pg-hero"><span>THE PANORAMA • PROSE 9</span><h1>{study.title}</h1><p>by {study.author}</p><small>{study.sourceNote}</small></header>
 <div className="pg-stage-grid">{[['learn','Learn','Guided study'],['practice','Practice','15 questions • 11:15'],['challenge','Challenge','23 questions • 23:00'],['test','Final Test','20 questions • 25:00']].map(([m,label,sub])=><button key={m} className={`pg-stage-card ${mode===m?'active':''}`} onClick={()=>openMode(m)}><strong>{label}</strong><small>{sub}</small></button>)}</div>
 {quizOpen?<PanoramaTimedQuiz mode={mode} title={study.title} bank={bank} onBack={()=>setQuizOpen(false)} addXp={addXp} finishSession={finishSession}/>:<>
 <section className="pg-about"><div><span>ABOUT THE CHAPTER</span><h2>{study.title}</h2><p>{study.intro}</p><p>This story uses financial hardship, mutual sacrifice, irony and thoughtful giving to show that love can give ordinary objects extraordinary meaning.</p></div><div className="pg-about-facts"><b>Chapter 9</b><span>O. Henry short story</span><span>Hindi explanations</span><span>Timed practice + tests</span></div></section>
 <section className="pg-study-section"><h3>GUIDED READING</h3><div className="pg-study-grid">{study.sections.map(s=><StudyBlock key={s.title} s={s}/>)}</div></section>
 <section className="pg-study-section"><h3>{study.wordStudy.title}</h3><div className="pg-vocab pg-vocab-wide">{study.wordStudy.items.map(([a,b])=><span key={a}><b>{a}</b> — {b}</span>)}</div><div className="pg-language-point"><b>Word formation</b><span>{study.wordStudy.formation.join(' • ')}</span></div></section>
 <section className="pg-study-section"><h3>{study.grammar.title}</h3><p>{study.grammar.intro}</p>{study.grammar.points.map(([a,b])=><div className="pg-language-point" key={a}><b>{a}</b><span>{b}</span></div>)}</section>
 <section className="pg-study-section"><h3>EXAM BOOSTER</h3>{['veryShort','short','long'].map(k=><div key={k}><h4>{k==='veryShort'?'Very Short Answer':k==='short'?'Short Answer':'Long Answer'}</h4>{study.examPrep[k].map(([q,a])=><div className="pg-qna" key={q}><b>{q}</b><p>{a}</p></div>)}</div>)}<h4>Discussion</h4>{study.examPrep.discussion.map(q=><div className="pg-qna" key={q}><b>{q}</b></div>)}</section>
 <section className="pg-study-section"><h3>WRITING / COMPOSITION</h3>{study.composition.map(x=><div className="pg-activity" key={x}><b>{x}</b><p>Use a clear introduction, chapter-based evidence, and a brief conclusion.</p></div>)}</section>
 <section className="pg-study-section"><h3>TRANSLATION PRACTICE</h3><div className="pg-language-list">{study.translationPractice.map(([a,b],i)=><span key={i}>{i+1}. <b>Hindi:</b> {a} <br/><b>English:</b> {b}</span>)}</div></section>
 <section className="pg-study-section"><h3>ACTIVITIES</h3>{study.activities.map(a=><div className="pg-activity" key={a.title}><b>{a.title}</b><p>{a.instruction}</p></div>)}</section>
 <section className="pg-study-section"><h3>QUICK REVISION</h3><div className="pg-revision"><span>Della → $1.87 → sells long hair</span><span>Jim → inherited gold watch → sells it</span><span>Della’s gift → platinum fob chain</span><span>Jim’s gift → set of combs</span><span>Main irony → each gift loses its immediate use</span><span>Core theme → love, sacrifice and thoughtful giving</span><span>Title → Jim and Della are compared with the Magi</span></div></section>
 <div className="pg-mode-cta"><button onClick={()=>openMode('practice')}>Start Practice →</button><button onClick={()=>openMode('challenge')}>Take Challenge →</button><button onClick={()=>openMode('test')}>Final Test →</button></div>
 </>}</div></div>;
}
export default EnglishPanoramaChapter9;
