import React,{useMemo,useState} from 'react';
import './english-reader.css';
import './english-panorama.css';

const study={
  title:'Yayati',
  author:'C. Rajagopalachari',
  sourceNote:'Class 9 English • The Panorama • Prose Chapter 2',
  intro:'“Yayati” is a story from the Mahabharata, rendered in English by C. Rajagopalachari. The chapter presents Emperor Yayati, his premature old age, his desire to recover youth, the responses of his sons, and the change in his understanding of desire. The lesson also includes telegram writing, word study, word formation, phrases, sequence of tenses and translation practice.',
  authorNote:'The source page says the story is taken from Spiritual Stories of India, compiled and edited by Chaman Lal and published by the Publication Division, Ministry of Information and Broadcasting, Government of India. It states that the story has been rendered in English by C. Rajagopalachari.',
  sections:[
    {title:'Part 1 — Emperor Yayati and his fall into old age',flow:'Yayati is introduced as a powerful ruler and an ancestor of the Pandavas. He is described as a king who follows the shastras, honours the gods and serves his subjects. His life changes when he is cursed by Sukracharya and becomes prematurely old.',explanation:'ययाति एक शक्तिशाली राजा और पांडवों के पूर्वज के रूप में प्रस्तुत किए गए हैं। वे शास्त्रों का पालन करते हैं, देवताओं का सम्मान करते हैं और प्रजा के कल्याण के लिए काम करते हैं। शुक्राचार्य के शाप के कारण उन्हें समय से पहले वृद्धावस्था प्राप्त हो जाती है।',vocabulary:[['ancestor','पूर्वज'],['dictate','आदेश देना / निर्देश देना'],['venerate','गहराई से सम्मान करना'],['prematurely','समय से पहले'],['curse','शाप']],exam:'Remember the contrast: a respected ruler becomes old before his natural time.',think:'Why does premature old age become the turning point of the story?'},
    {title:'Part 2 — Yayati’s suffering and desire for youth',flow:'Yayati is troubled by the weakness and misery of old age. Although he has become old, his desire for sensual enjoyment remains strong. He therefore looks for a way to regain the vigour of youth.',explanation:'ययाति वृद्धावस्था की कमजोरी और पीड़ा से परेशान हैं। वृद्ध होने के बाद भी उनके भीतर सांसारिक सुखों की इच्छा बनी रहती है। इसलिए वे फिर से युवावस्था का बल पाने का उपाय खोजते हैं।',vocabulary:[['vigour','शक्ति / जोश'],['pityful','दया उत्पन्न करने वाला'],['sensual','इंद्रिय-सुख से संबंधित'],['restraint','संयम'],['pleasure','सुख']],exam:'Explain the conflict between physical old age and continuing desire.',think:'Does getting what we want always remove the desire for more?'},
    {title:'Part 3 — Yayati asks his sons',flow:'Yayati calls his sons and asks one of them to exchange youth for his old age. His eldest son refuses, saying that he cannot accept such a burden. The next sons also give reasons for refusing the request.',explanation:'ययाति अपने पुत्रों को बुलाकर उनमें से किसी एक से अपनी वृद्धावस्था लेने और अपनी युवावस्था देने का अनुरोध करते हैं। सबसे बड़ा पुत्र इस भारी जिम्मेदारी को स्वीकार करने से मना करता है। अगले पुत्र भी अलग-अलग कारण देकर इनकार करते हैं।',vocabulary:[['bidding','आदेश / आग्रह'],['mock','उपहास करना'],['maiden','कुमारी / युवती'],['consent','सहमति देना'],['burden','भार']],exam:'The first three sons do not agree to their father’s proposal; know the reasons given in the text.',think:'What do the different refusals reveal about the sons?'},
    {title:'Part 4 — The fourth son’s response',flow:'The fourth son also finds the request difficult. Yayati becomes angry and sorrowful after the refusals. The story then turns to the youngest son, Puru, who is ready to help his father.',explanation:'चौथा पुत्र भी इस अनुरोध को स्वीकार नहीं कर पाता। लगातार इनकार से ययाति दुखी और क्रोधित होते हैं। इसके बाद कथा सबसे छोटे पुत्र पुरु की ओर मुड़ती है, जो पिता की सहायता के लिए तैयार होता है।',vocabulary:[['refusal','इनकार'],['sorrow','दुःख'],['appeal','अनुरोध / पुकार'],['youngest','सबसे छोटा'],['filial','पुत्र का / पुत्रधर्म से संबंधित']],exam:'Be able to compare the first three sons, the fourth son and Puru.',think:'Why does Puru’s response change the direction of the story?'},
    {title:'Part 5 — Puru accepts the burden',flow:'Puru willingly offers his youth and accepts his father’s old age. Yayati accepts the exchange and becomes young again. Puru bears the old age while Yayati returns to the life and vigour he wanted.',explanation:'पुरु स्वेच्छा से अपनी युवावस्था पिता को देने और उनकी वृद्धावस्था स्वीकार करने के लिए तैयार होते हैं। ययाति इस विनिमय को स्वीकार कर फिर से युवा हो जाते हैं। पुरु वृद्धावस्था का भार अपने ऊपर लेते हैं।',vocabulary:[['relieve','मुक्त करना / राहत देना'],['bestow','प्रदान करना'],['exchange','विनिमय'],['vigour','यौवन-शक्ति'],['accept','स्वीकार करना']],exam:'Puru’s filial love is central to the turning point of the story.',think:'Was Puru’s decision an act of love, duty, sacrifice, or all three?'},
    {title:'Part 6 — Youth does not end the desire',flow:'Yayati again enjoys worldly pleasures and later visits the garden of Kubera. Even after receiving youth, he is not satisfied. The experience gradually makes him realise that desire cannot be permanently quenched by indulgence.',explanation:'यौवन वापस मिलने के बाद ययाति फिर सांसारिक सुखों का आनंद लेते हैं और बाद में कुबेर के बगीचे में जाते हैं। लेकिन उनकी इच्छाएँ पूरी तरह समाप्त नहीं होतीं। अनुभव से उन्हें समझ आने लगता है कि केवल भोग से इच्छा स्थायी रूप से शांत नहीं होती।',vocabulary:[['indulgence','अति-भोग / मनमाना सुख-भोग'],['quench','शांत करना / बुझाना'],['desire','इच्छा'],['satisfied','संतुष्ट'],['garden','उद्यान']],exam:'The garden episode helps prepare the lesson’s central realisation.',think:'Why can repeated pleasure fail to produce lasting satisfaction?'},
    {title:'Part 7 — Yayati understands the nature of desire',flow:'Yayati finally understands that desire can grow rather than disappear through indulgence. He tells Puru that no object such as wealth or pleasure can completely satisfy a person. Peace requires a mental state beyond attachment and dislike.',explanation:'ययाति अंततः समझते हैं कि इच्छाएँ भोग से समाप्त होने के बजाय बढ़ सकती हैं। वे पुरु से कहते हैं कि धन, वस्तु या सांसारिक सुख मनुष्य को पूरी तरह संतुष्ट नहीं कर सकते। शांति के लिए आसक्ति और द्वेष से ऊपर उठी हुई मानसिक अवस्था आवश्यक है।',vocabulary:[['attachment','आसक्ति'],['dislike','अरुचि / द्वेष'],['wealth','धन'],['peace','शांति'],['mental state','मानसिक अवस्था']],exam:'This is the key message: indulgence is not a reliable cure for desire.',think:'What change happens in Yayati’s thinking by the end?'},
    {title:'Part 8 — Returning youth and responsibility',flow:'Yayati gives Puru his youth back and takes back his own old age. Puru then rules the kingdom wisely and becomes renowned. Yayati retires to the forest, spends his time in austerities and ultimately attains heaven.',explanation:'ययाति पुरु को उसकी युवावस्था वापस कर देते हैं और अपनी वृद्धावस्था फिर स्वीकार कर लेते हैं। इसके बाद पुरु बुद्धिमानी से राज्य करते हैं और प्रसिद्ध होते हैं। ययाति वन में चले जाते हैं, तप करते हैं और अंततः स्वर्ग प्राप्त करते हैं।',vocabulary:[['austerities','तप / कठोर साधना'],['renowned','प्रसिद्ध'],['retire','सेवानिवृत्त होना / पीछे हटना'],['wisely','बुद्धिमानी से'],['attain','प्राप्त करना']],exam:'Know the ending: Puru rules; Yayati retires and turns to austerity.',think:'How does the ending complete the lesson’s movement from desire to restraint?'}
  ],
  glossary:[['ancestors','people from whom one is descended — पूर्वज'],['dictate','to order or command — आदेश देना'],['venerated','respected deeply — गहरा सम्मान किया गया'],['prematurely','before the usual or proper time — समय से पहले'],['curse','solemn invocation of divine wrath — शाप'],['wronged','treated unjustly — अन्याय किया'],['bidding','command — आदेश'],['mock','ridicule — उपहास करना'],['plight','an unfortunate condition or state — दयनीय स्थिति'],['supplicated','addressed humbly — विनम्रतापूर्वक प्रार्थना की']],
  wordStudy:{
    spellings:[['vigor','vigour'],['pityful','pityful'],['relieve','relieve'],['bestouw','bestow'],['indulience','indulgence']],
    less:[['joyless','बिना आनंद के'],['prestigeless','बिना प्रतिष्ठा के'],['fameless','बिना प्रसिद्धि के'],['population-less','जनसंख्या से रहित'],['vigourless','बिना शक्ति के'],['dangerless','बिना खतरे के'],['courageless','बिना साहस के'],['labourless','बिना श्रम के'],['pitiless','बिना दया के'],['victoryless','बिना विजय के']],
    meanings:[['morally good','virtuous'],['painful feeling','pity'],['person from whom one is descended','ancestor'],['respected deeply','venerated'],['command','bidding']],
    phrases:[['have had','पहले से होना / अनुभव होना'],['fill of','पूरी मात्रा या भरपूर'],['by no means','किसी भी तरह नहीं'],['take upon oneself','अपने ऊपर लेना'],['take up','स्वीकार करना / शुरू करना'],['give back','वापस देना'],['in due course','उचित समय पर'],['in the full vigour of youth','यौवन की पूरी शक्ति में']]
  },
  grammar:{title:'Sequence of Tenses',intro:'The chapter explains how the tense in a subordinate clause relates to the tense of the principal clause, with important exceptions.',rules:[['Present/Future principal clause','The subordinate clause may use the tense required by the sense.'],['Past principal clause','The subordinate clause generally follows the past-tense sequence.'],['Universal truth','A present-tense truth may remain in the present even after a past reporting verb.'],['than','After “than”, the subordinate verb may take the tense needed by meaning.'],['Adverbial clause','Place or reason clauses may use the tense required by the sense.'],['lest','“Lest” is followed by “should”.'],['as if / as though','Use “were” or a suitable past form according to the structure and meaning.']]},
  telegram:{intro:'The source explains that a telegram is a brief emergency message. Because the message is charged by the word, only key words are used; clarity, simplicity and brevity are important.',example:'Mother serious (stop) Come soon (stop)',tasks:['Your mother is seriously ill. Your father is on an official tour. Write a short telegram informing him.','Your friend Amit has passed NTS examination. Write a congratulatory telegram to his parents in not more than 10 words.','You planned to reach home on 30th September but will reach on 5th October. Inform your parents by telegram.']},
  translation:[['Rajeev was going to market when it started raining.','राजीव बाजार जा रहा था जब बारिश शुरू हो गई।'],['Seema is cooking food now.','सीमा अभी खाना बना रही है।'],['When the doorbell rang, Abhinav was working on his homework.','जब दरवाज़े की घंटी बजी, अभिनव अपना गृहकार्य कर रहा था।'],['Sita is trying to go abroad for studies.','सीता पढ़ाई के लिए विदेश जाने की कोशिश कर रही है।'],['Does he want to go to market with his mother?','क्या वह अपनी माँ के साथ बाजार जाना चाहता है?'],['Mr. Shah is going out for fishing with his son today.','श्री शाह आज अपने बेटे के साथ मछली पकड़ने जा रहे हैं।'],['Ashu is a naughty boy, isn’t he?','आशु शरारती लड़का है, है न?'],['Oh! What a hot day it is!','ओह! आज कितना गर्म दिन है!'],['To err is human; to forgive is divine.','गलती करना मानवीय है; क्षमा करना दिव्य है।'],['Were you ready to come and play with me?','क्या तुम मेरे साथ आने और खेलने के लिए तैयार थे?'],['Sita said, “I am feeling hungry.”','सीता ने कहा, “मुझे भूख लग रही है।”'],['Rajeev told Mira that he was going out of town during the summer vacation.','राजीव ने मीरा से कहा कि वह गर्मी की छुट्टियों में शहर से बाहर जा रहा था।']]
};

const practice=[
 {q:'Who is the central ruler in the story?',o:['Puru','Yayati','Sukracharya','Kubera'],a:1,e:'The story centres on Emperor Yayati.'},
 {q:'Why did Yayati become prematurely old?',o:['Because of a curse','Because of a battle','Because he retired','Because of travel'],a:0,e:'The source says Sukracharya cursed Yayati, causing premature old age.'},
 {q:'What did Yayati ask his sons to give him?',o:['Their kingdom','Their wealth','Their youth','Their horses'],a:2,e:'He wanted one son to exchange youth for his old age.'},
 {q:'Who agreed to take Yayati’s old age?',o:['The eldest son','The second son','The fourth son','Puru'],a:3,e:'Puru, the youngest son, accepted the exchange.'},
 {q:'What happened after Puru accepted the exchange?',o:['Yayati became young again','Puru became king immediately','Yayati went to the forest at once','The curse disappeared without an exchange'],a:0,e:'Yayati regained youth while Puru accepted old age.'},
 {q:'What did Yayati realise about desire?',o:['It always disappears after pleasure','It can be increased by indulgence','It has no connection with the mind','It is cured by wealth'],a:1,e:'His experience leads him to see that indulgence does not permanently quench desire.'},
 {q:'Which quality best describes Puru’s response?',o:['Filial love and willingness to sacrifice','Anger at his father','Fear of the kingdom','Indifference'],a:0,e:'Puru willingly gives his youth for his father.'},
 {q:'What is one key idea in Yayati’s final teaching?',o:['Gold satisfies everyone','Desire is best answered by endless indulgence','Peace requires going beyond attachment and dislike','Youth should never be returned'],a:2,e:'Yayati connects peace with a mental state beyond likes and dislikes.'},
 {q:'What did Puru do after receiving his youth back?',o:['He left the kingdom','He ruled the kingdom wisely','He became a hermit immediately','He visited Kubera'],a:1,e:'The source says Puru ruled wisely and became renowned.'},
 {q:'What happened to Yayati at the end?',o:['He became a merchant','He returned to his sons','He retired to the forest and practised austerities','He remained young forever'],a:2,e:'Yayati returned to old age, retired to the forest and practised austerities.'},
 {q:'What does “prematurely” mean?',o:['after a long delay','before the usual time','with great joy','without permission'],a:1,e:'Prematurely means before the proper or usual time.'},
 {q:'What does “bidding” mean in the glossary?',o:['command','garden','pleasure','wrinkle'],a:0,e:'The glossary gives “command” for bidding.'},
 {q:'What is the main purpose of the telegram section?',o:['To teach long letter writing','To practise brief, clear emergency messages','To explain poetry','To describe a kingdom'],a:1,e:'The source stresses brevity, simplicity and key words in telegrams.'},
 {q:'Which grammar topic is taught in this chapter?',o:['Articles','Sequence of Tenses','Reported speech only','Prepositions only'],a:1,e:'The chapter explicitly teaches Sequence of Tenses.'},
 {q:'Which word is formed from “enjoy” with the suffix “-ment”?',o:['enjoyful','enjoyment','enjoyous','enjoyless'],a:1,e:'The source explains that enjoyment is formed from enjoy + ment.'}
];

const challenge=[
 {q:'Why is Yayati’s premature old age important to the story?',o:['It creates the conflict between physical old age and continuing desire','It ends the story immediately','It makes Puru king at once','It removes all desire'],a:0,e:'The curse creates the central conflict and motivates Yayati’s request.'},
 {q:'What does the refusal of the first sons reveal?',o:['They are unwilling to accept the burden of premature old age','They have already become old','They do not know their father','They want to leave the kingdom for war'],a:0,e:'Each refusal shows unwillingness to take on the old age requested by Yayati.'},
 {q:'Why is Puru’s decision a major turning point?',o:['He accepts the sacrifice that the others reject','He defeats Sukracharya','He takes Kubera’s garden','He refuses to help Yayati'],a:0,e:'Puru’s acceptance makes the youth-for-old-age exchange possible.'},
 {q:'What tension drives Yayati after he becomes young again?',o:['He has youth but still has desire for further pleasure','He has no kingdom','He cannot speak','He has forgotten his sons'],a:0,e:'Youth returns, but his desire for sensual enjoyment continues.'},
 {q:'What does Yayati’s experience suggest about indulgence?',o:['Indulgence can fail to end desire and may intensify it','It always creates peace','It removes attachment immediately','It makes everyone satisfied'],a:0,e:'His final insight is that desire is not permanently quenched by more indulgence.'},
 {q:'Why does the story move from external pleasure to a mental state?',o:['Yayati learns that lasting peace cannot depend only on objects of desire','The story changes into a travel narrative','The kingdom becomes poor','Puru rejects the throne'],a:0,e:'The ending shifts the focus from objects to the mind and its attachments.'},
 {q:'Which contrast best captures the lesson’s development?',o:['desire and restraint','winter and summer','city and village','music and silence'],a:0,e:'The story moves from strong desire toward restraint and inner peace.'},
 {q:'Why is Puru’s sacrifice connected with filial love?',o:['He accepts his father’s old age willingly','He refuses to speak to his father','He demands the kingdom first','He mocks the other sons'],a:0,e:'Puru’s action is presented as filial love and willingness to help his father.'},
 {q:'What does the final exchange between Yayati and Puru show?',o:['Yayati eventually recognises the need to restore the natural order','Yayati wants to keep youth forever','Puru refuses responsibility','The curse becomes stronger'],a:0,e:'Yayati returns youth to Puru and accepts old age again.'},
 {q:'Why is Puru’s later rule relevant to the moral structure?',o:['His sacrifice is followed by wise and renowned rule','He abandons the kingdom','He becomes a merchant','He never returns to youth'],a:0,e:'The source says Puru ruled wisely and acquired great renown.'},
 {q:'Which statement best describes Yayati’s character arc?',o:['He moves from attachment to a deeper understanding of desire','He moves from wisdom to ignorance only','He never changes his view','He becomes interested only in warfare'],a:0,e:'The ending shows a change in Yayati’s understanding of desire and peace.'},
 {q:'If a person keeps seeking more pleasure after getting what they wanted, what idea from the story applies?',o:['Desire may not be satisfied by repeated indulgence','All pleasure is harmful','Youth is permanent','Wealth is unnecessary in every case'],a:0,e:'Yayati’s experience supports the first conclusion.'},
 {q:'What is the role of the sons’ different answers?',o:['They create a comparison that makes Puru’s sacrifice clearer','They explain the telegram format','They teach spelling only','They remove the main conflict'],a:0,e:'The different responses prepare the contrast with Puru.'},
 {q:'What does “take upon oneself” mean in the chapter’s phrase study?',o:['accept responsibility or a burden','give something away','travel quickly','make a joke'],a:0,e:'The phrase means to accept something as one’s own responsibility.'},
 {q:'Why is “by no means” useful for students to learn?',o:['It is a fixed phrase expressing strong negation','It names a character','It means “very quickly”','It is a suffix'],a:0,e:'“By no means” is a phrase used to express that something is not true at all.'},
 {q:'Which is the best reason for keeping a telegram brief?',o:['The source says telegrams were charged by the word','Long messages were more polite','Telegram messages were poems','Only rulers could send them'],a:0,e:'The source explicitly connects brevity with word-based charges.'},
 {q:'In “He failed because he has poor health”, why can the subordinate clause use present tense?',o:['The reason may be a continuing fact according to the sense','Because all past clauses must be present','Because “because” always changes tense','Because the sentence is a question'],a:0,e:'The grammar section allows the tense needed by the sense in such an adverbial clause.'},
 {q:'What is the exception illustrated by “The teacher said that the earth is round”?',o:['A universal or habitual truth may remain in the present tense','All reported speech must be present','Past tense is never used','Only questions can use present tense'],a:0,e:'The source specifically gives a universal truth as an exception.'},
 {q:'What does the “lest” rule require?',o:['should','would','has','did'],a:0,e:'The source states that “lest” is followed by “should”.'},
 {q:'Why does the source discuss “as if” and “as though”?',o:['They can require “were” or a past form according to the structure','They are telegram phrases','They are suffixes for nouns','They introduce direct speech only'],a:0,e:'The grammar section gives examples with as if/as though and “were” or a past form.'},
 {q:'Which study strategy best fits this chapter?',o:['Connect the plot, Puru’s sacrifice, Yayati’s realisation and the language sections','Memorise only the title','Skip the grammar because it is separate','Study only the illustration'],a:0,e:'The chapter combines literature, word study, grammar, composition and translation.'},
 {q:'Why is the garden of Kubera significant in the lesson?',o:['It is part of the stage in which Yayati continues to seek pleasure before his final realisation','It is where Puru refuses the throne','It is where the telegram is written','It is where Sukracharya gives the curse'],a:0,e:'The garden episode occurs while Yayati is still enjoying life and is not satisfied.'},
 {q:'What broader lesson follows from Yayati’s final words?',o:['Inner peace cannot be secured simply by collecting or consuming desired objects','Everyone must reject every pleasure','Old age is always better than youth','Kings should never rule'],a:0,e:'Yayati’s conclusion points toward a mental state beyond attachment and dislike.'}
];

const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)].map((x,i)=>({...x,id:`panorama-yayati-final-${i}`}));

function shuffleQuestion(q){
  const indexed=q.o.map((option,index)=>({option,index}));
  for(let i=indexed.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[indexed[i],indexed[j]]=[indexed[j],indexed[i]];}
  const o=indexed.map(item=>item.option);
  const a=indexed.findIndex(item=>item.index===q.a);
  return {...q,o,a};
}

function StudyView(){return <div className="pg-learn">
  <div className="pg-callout pg-no-book"><b>📘 Complete Guided Study</b><span>Chapter flow, आसान हिन्दी explanation, vocabulary, word study, grammar, telegram writing, translation और exam preparation एक ही जगह।</span></div>
  <section className="pg-panel"><div className="pg-panel-title"><span>ABOUT THE LESSON</span><h2>Chapter का basic idea</h2></div><p>{study.intro}</p><div className="pg-author"><b>लेखक / स्रोत परिचय</b><p>{study.authorNote}</p></div></section>
  <div className="pg-anchorbar"><a href="#guided">Guided Reading</a><a href="#words">Word Study</a><a href="#grammar">Grammar</a><a href="#exam">Exam Prep</a></div>
  <section id="guided" className="pg-section-heading"><span>01</span><div><small>READ • UNDERSTAND • REMEMBER</small><h2>Guided Reading</h2><p>हर block कहानी के flow को आसान English में समझाता है और फिर हिन्दी में उसका अर्थ स्पष्ट करता है।</p></div></section>
  <div className="pg-reading-stack">{study.sections.map((s,i)=><article className="pg-reading-card" key={s.title}><div className="pg-card-top"><div className="pg-num">{String(i+1).padStart(2,'0')}</div><div><span>CHAPTER FLOW</span><h3>{s.title}</h3></div></div><div className="pg-flow"><div className="pg-flow-label">सरल English में पढ़ें</div><p>{s.flow}</p></div><div className="pg-hindi"><div className="pg-flow-label">हिन्दी में समझें</div><p>{s.explanation}</p></div><div className="pg-vocab-head">Vocabulary</div><div className="pg-vocab-grid">{s.vocabulary.map(([w,m])=><div className="pg-vocab" key={w}><b>{w}</b><span>{m}</span></div>)}</div><div className="pg-bottom-grid"><div className="pg-exam"><b>🎯 Exam Point</b><span>{s.exam}</span></div><div className="pg-think"><b>💡 Think</b><span>{s.think}</span></div></div></article>)}</div>
  <section id="words" className="pg-section-heading compact"><span>02</span><div><small>LANGUAGE BUILDING</small><h2>Word Study</h2><p>Glossary, spelling, suffix-based word formation, meanings और important phrases revise करें।</p></div></section>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>Glossary</h3><div className="pg-glossary">{study.glossary.map(([w,m])=><div key={w}><b>{w}</b><span>{m}</span></div>)}</div></section><section className="pg-panel"><h3>Correct the spelling</h3><div className="pg-spelling">{study.wordStudy.spellings.map(([bad,good])=><div key={bad}><del>{bad}</del><b>→ {good}</b></div>)}</div></section></div>
  <div className="pg-tool-grid"><section className="pg-panel"><h3>-less Word Formation</h3><p className="pg-muted">“-less” का अर्थ “बिना” है। Chapter के exercise pattern को समझने के लिए examples देखें।</p><div className="pg-pillgrid">{study.wordStudy.less.map(([w,m])=><div key={w}><b>{w}</b><span>{m}</span></div>)}</div></section><section className="pg-panel"><h3>Meaning Match</h3><div className="pg-match">{study.wordStudy.meanings.map(([q,a])=><div key={q}><span>{q}</span><b>{a}</b></div>)}</div></section></div>
  <section className="pg-panel"><h3>Important Phrases</h3><div className="pg-phrasegrid">{study.wordStudy.phrases.map(([p,m])=><div key={p}><b>{p}</b><span>{m}</span></div>)}</div></section>
  <section id="grammar" className="pg-section-heading compact"><span>03</span><div><small>GRAMMAR LAB</small><h2>{study.grammar.title}</h2><p>{study.grammar.intro}</p></div></section>
  <section className="pg-panel"><h3>Core rules</h3><div className="pg-grammar-grid">{study.grammar.rules.map(([t,e])=><div key={t}><b>{t}</b><span>{e}</span></div>)}</div><div className="pg-rulebox"><b>Golden Rule</b><span>Principal clause और subordinate clause के tense को केवल mechanical rule से नहीं, sentence के sense के अनुसार समझें; universal truths और special conjunction structures exceptions दे सकते हैं।</span></div></section>
  <section className="pg-panel"><h3>Grammar examples from the source</h3><div className="pg-phrasegrid"><div><b>I know / I shall know</b><span>what he does / is doing / has done / had done / will do and other tense forms according to sense.</span></div><div><b>Past principal clause</b><span>“I knew what he was doing.” — past sequence example.</span></div><div><b>Universal truth</b><span>“The teacher said that the earth is round.” — present remains because the fact is universal.</span></div><div><b>lest</b><span>“He worked hard lest he should fail.”</span></div><div><b>as if / as though</b><span>“He speaks as if he were mad.” / “He fought as though he were a tiger.”</span></div></div></section>
  <section className="pg-panel"><h3>Message: Telegram</h3><p>{study.telegram.intro}</p><div className="pg-callout"><b>Model format idea</b><span>Address → MESSAGE in key words → sender’s name and address. The source illustrates the stop convention and stresses brevity.</span></div><div className="pg-phrasegrid"><div><b>Source example</b><span>{study.telegram.example}</span></div>{study.telegram.tasks.map((t,i)=><div key={t}><b>Exercise {i+1}</b><span>{t}</span></div>)}</div></section>
  <section id="exam" className="pg-section-heading compact"><span>04</span><div><small>BSEB-STYLE PREPARATION</small><h2>Exam Booster</h2><p>Short answers, long answers, discussion, composition और translation—chapter के source tasks के अनुसार तैयारी करें।</p></div></section>
  <div className="pg-exam-grid"><section className="pg-panel"><h3>Short-answer checklist</h3><ul><li>Yayati कौन थे और उन्हें समय से पहले वृद्धावस्था क्यों मिली?</li><li>पहले तीन पुत्रों ने क्या उत्तर दिए?</li><li>पुरु ने पिता की अपील पर क्या किया?</li><li>ययाति ने इच्छा और भोग के बारे में क्या समझा?</li><li>पुरु और ययाति के अंत में क्या हुआ?</li></ul></section><section className="pg-panel"><h3>Long-answer themes</h3><ul><li>Yayati’s premature old age and his reaction.</li><li>Why Puru accepted the exchange and whether the act was right.</li><li>The responses of the first three sons.</li><li>The lesson Yayati learns about desire and indulgence.</li><li>The relationship between parents and sons.</li></ul></section></div>
  <section className="pg-panel"><h3>Group Discussion</h3><p>“Elderly people are assets to our nation.” Source के discussion prompt पर अपने पक्ष में कारण दें और उदाहरणों से विचार स्पष्ट करें।</p></section>
  <section className="pg-panel"><h3>Composition</h3><p>Source task: लगभग 100 words में “Relation between parents and sons” पर paragraph लिखें। Answer में respect, responsibility, affection और mutual understanding जैसे विचार context के अनुसार विकसित करें।</p></section>
  <section className="pg-panel"><h3>Translation Practice</h3><p className="pg-muted">पहले खुद translate करें, फिर दिए गए अर्थ से check करें।</p><div className="pg-translation">{study.translation.map(([en,hi],i)=><div key={en}><span>{i+1}</span><b>{en}</b><em>{hi}</em></div>)}</div></section>
  <section className="pg-panel pg-revision"><h3>⚡ 30-second Revision</h3><div className="pg-revision-grid"><div><b>Curse</b><span>Sukracharya के curse से premature old age.</span></div><div><b>Yayati</b><span>Youth की इच्छा और बाद में desire पर realisation.</span></div><div><b>Puru</b><span>पिता के लिए youth देने वाला पुत्र.</span></div><div><b>Indulgence</b><span>अति-भोग desire को स्थायी रूप से शांत नहीं करता.</span></div><div><b>Peace</b><span>Attachment और dislike से ऊपर mental state.</span></div><div><b>Grammar</b><span>Sequence of Tenses + important exceptions.</span></div></div></section>
</div>}

export function EnglishPanoramaChapter2({initialMode=null,onBack,addXp,finishSession}){
 const [mode,setMode]=useState(initialMode||'learn');
 const [idx,setIdx]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[result,setResult]=useState(null),[shuffleNonce,setShuffleNonce]=useState(0);
 const bank=useMemo(()=>mode==='practice'?practice:mode==='challenge'?challenge:mode==='test'?finalTest:[],[mode]);
 const randomizedBank=useMemo(()=>bank.map(q=>shuffleQuestion(q)),[bank,shuffleNonce]);
 const current=randomizedBank[idx]||null;
 const begin=m=>{setMode(m);setIdx(0);setSelected(null);setScore(0);setResult(null);setShuffleNonce(n=>n+1)};
 const choose=n=>{if(selected!==null||!current)return;setSelected(n);if(n===current.a)setScore(s=>s+1)};
 const next=()=>{if(idx===bank.length-1){const finalScore=score+(selected===current.a?1:0);const pct=Math.round(finalScore/bank.length*100);setResult({score:finalScore,total:bank.length,pct});finishSession?.({chapter:study.title,mode,score:finalScore,total:bank.length,percent:pct,completed:true});}else{setIdx(i=>i+1);setSelected(null)}};
 if(mode==='learn')return <div className="pg-shell"><div className="pg-hero"><span className="badge">CLASS 9 • THE PANORAMA • PROSE 2</span><h1>{study.title}</h1><p>{study.author} • Guided learning</p></div><div className="pg-modebar"><button className="active" onClick={()=>begin('learn')}><b>Learn</b><span>पूरा chapter समझें</span></button><button onClick={()=>begin('practice')}><b>Practice</b><span>15 questions</span></button><button onClick={()=>begin('challenge')}><b>Challenge</b><span>23 thinking questions</span></button><button onClick={()=>begin('test')}><b>Final Test</b><span>20 mixed questions</span></button></div><button className="pg-back" onClick={onBack}>← English books</button><StudyView/></div>;
 if(result)return <div className="pg-shell"><div className="pg-quiz-wrap"><button className="pg-back" onClick={()=>begin('learn')}>← Back to Learn</button><div className="pg-panel"><span className="pg-qtag">RESULT</span><h2>{study.title}</h2><div className="result-score">{result.score}<small>/ {result.total}</small></div><div className="result-percent">{result.pct}% correct</div><p>{result.pct===100?'Excellent! 🎉':result.pct>=70?'Very good! 💪':'Keep practising 📚'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={()=>begin(mode)}>Try Again</button><button className="primary-btn pressable" onClick={onBack}>Back to English →</button></div></div></div></div>;
 const progress=Math.round(((idx+(selected!==null?1:0))/bank.length)*100);
 return <div className="pg-shell"><div className="pg-quiz-wrap"><button className="pg-back" onClick={()=>begin('learn')}>← Back to Learn</button><div className="pg-quiz-head"><div><span>{mode==='practice'?'PRACTICE':mode==='challenge'?'CHALLENGE':'FINAL TEST'}</span><h2>{study.title}</h2></div><b>{idx+1}/{bank.length}</b></div><div className="pg-progress"><i style={{width:`${progress}%`}}/></div><div className="pg-question-card"><span className="pg-qtag">Question {idx+1}</span><h3>{current.q}</h3><div className="pg-options">{current.o.map((o,i)=>{const cls=selected===null?'':i===current.a?'correct':i===selected?'wrong':'';return <button key={o} className={`pg-option ${cls}`} onClick={()=>choose(i)} disabled={selected!==null}><span>{String.fromCharCode(65+i)}</span><b>{o}</b></button>})}</div>{selected!==null&&<div className={`pg-feedback ${selected===current.a?'good':'bad'}`}><b>{selected===current.a?'✓ Correct':'✗ Not quite'}</b><p>{current.e}</p><button className="pg-next" onClick={next}>{idx===bank.length-1?'View Result':'Next Question →'}</button></div>}</div></div></div>;
}

export const englishPanoramaChapter2Meta={title:study.title,author:study.author,book:'The Panorama',type:'Prose'};
export const englishPanoramaChapter2Study=study;
