import React,{useMemo}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import './EnglishClausesTopic.css';

const LESSONS=[
{n:'01',title:'Clause क्या है?',simple:'Clause वाक्य का वह भाग है जिसमें subject और verb का संबंध होता है। कुछ clauses अपने-आप पूरा अर्थ देते हैं, जबकि कुछ दूसरे clause पर निर्भर रहते हैं।',meaning:'A clause is a group of words with a subject–verb relationship.',structure:'Subject + Verb (+ other words)',examples:['Ravi studies hard. → “Ravi studies hard” is a clause.','when Ravi studies → इसमें subject और verb हैं, लेकिन यह अपने-आप पूरा विचार नहीं देता।'],clue:'पहला कदम: clause में subject और finite verb पहचानो।'},
{n:'02',title:'Independent और Dependent Clause',simple:'Independent clause पूरा विचार देता है। Dependent clause पूरा विचार नहीं देता और मुख्य clause पर निर्भर करता है। हिंदी में इसे मुख्य और आश्रित भाग की तरह समझ सकते हो।',meaning:'Independent = complete thought; dependent = incomplete thought.',structure:'Independent: S + V + complete idea | Dependent: connector + S + V + incomplete idea',examples:['I went home. → independent','because it was late → dependent'],clue:'क्या यह भाग अकेले पूरा sentence बन सकता है?'},
{n:'03',title:'Main Clause और Subordinate Clause',simple:'Main clause को मुख्य clause कह सकते हैं। Subordinate clause उसके साथ जुड़कर अतिरिक्त या आवश्यक जानकारी देता है।',meaning:'The main clause carries the central statement; the subordinate clause depends on it.',structure:'Main clause + subordinate clause / Subordinate clause + main clause',examples:['I stayed inside because it was raining.','Because it was raining, I stayed inside.'],clue:'Connector देखकर पहले यह मत मानो कि पूरा sentence वहीं खत्म हो गया।'},
{n:'04',title:'Noun Clause — पहचान',simple:'Noun clause sentence में noun की तरह काम करता है। यानी subject, object या complement की जगह आ सकता है।',meaning:'A noun clause functions like a noun.',structure:'main clause + [noun clause]',examples:['I know what he wants. → “what he wants” is the object.','What she said was true. → noun clause is the subject.'],clue:'पूछो: यह clause किस चीज़/किस बात को represent कर रहा है?'},
{n:'05',title:'Noun Clause — that, what, whether/if',simple:'that, what, whether/if जैसे words noun clause शुरू कर सकते हैं। “what” का अर्थ अक्सर “जो कुछ/जो बात” होता है।',meaning:'Common noun-clause markers include that, what, whether and if.',structure:'verb + that/what/whether/if + clause',examples:['I believe that he is honest.','Tell me what you need.','I wonder whether she will come.'],clue:'Noun clause में पूरा clause मिलकर noun का काम करता है।'},
{n:'06',title:'Noun Clause — प्रश्न और word order',simple:'Reported question में noun clause के अंदर statement order आता है। इसलिए “where he lives” सही है, “where does he live” नहीं।',meaning:'Embedded questions use statement word order.',structure:'main verb + wh-word + subject + verb',examples:['I know where he lives.','Tell me why she left.'],clue:'Embedded question ≠ direct question. Auxiliary inversion नहीं।'},
{n:'07',title:'Adverb Clause — समय',simple:'Time clause बताता है कि काम कब हुआ या कब होगा। when, while, before, after, until, as soon as आदि आम markers हैं।',meaning:'Adverb clauses of time show when an action happens.',structure:'when/while/before/after/until + S + V',examples:['When the bell rang, the students left.','Wait here until I return.','After he arrived, we started.'],clue:'कब? कितनी देर तक? किस घटना के बाद/पहले? — ऐसे सवाल पूछो।'},
{n:'08',title:'Adverb Clause — कारण और परिणाम',simple:'because, since, as कारण बताते हैं। so...that और such...that जैसे patterns परिणाम दिखा सकते हैं।',meaning:'Reason clauses explain why; result clauses explain what happened as a consequence.',structure:'because/since/as + clause | so + adjective + that + clause',examples:['We stayed home because it rained.','He was so tired that he slept early.'],clue:'Why? पूछने पर reason clause अक्सर मिल जाता है।'},
{n:'09',title:'Adverb Clause — Condition',simple:'Condition clause किसी शर्त को बताता है। if, unless, provided that, as long as जैसे words उपयोगी हैं।',meaning:'Conditional clauses express a condition for another action or result.',structure:'if/unless + condition, result',examples:['If you work hard, you will improve.','Unless you hurry, you will miss the bus.'],clue:'अगर/जब तक नहीं/इस शर्त पर — condition पहचानने के clues हैं।'},
{n:'10',title:'Conditional clause में tense control',simple:'School grammar में first conditional में if-clause में सामान्यतः present form और main clause में will + V1 मिलता है। “If it rains, we will stay home.”',meaning:'In a common first conditional pattern, present form appears in the if-clause and will in the main clause.',structure:'If + present, will + V1',examples:['If she studies, she will pass.','If it is late, we will leave.'],clue:'If-clause में सीधे “will” लगाने की आदत से बचो, जब standard first-conditional pattern पूछा गया हो।'},
{n:'11',title:'Relative Clause क्या करती है?',simple:'Relative clause किसी noun या pronoun के बारे में extra पहचान या information देती है। इसे adjective clause भी कहा जाता है।',meaning:'A relative clause modifies a noun or pronoun.',structure:'noun + who/whom/which/that/whose/where + clause',examples:['The boy who won is my friend.','This is the book that I bought.'],clue:'किस noun के बारे में जानकारी दी जा रही है? वही antecedent है।'},
{n:'12',title:'Who, whom, which, that, whose, where',simple:'who आमतौर पर people के subject के लिए, whom object के लिए, which things/animals के लिए, whose possession के लिए और where place के लिए मिलता है। that कई defining contexts में people/things दोनों के साथ आता है।',meaning:'Relative words are chosen by the role and the noun being described.',structure:'antecedent + relative word + clause',examples:['The girl who helped me smiled.','The man whom I met was kind.','The house whose roof is red is old.','The town where I live is quiet.'],clue:'सिर्फ noun देखकर नहीं; relative clause के अंदर word का grammatical role भी देखो।'},
{n:'13',title:'Defining Relative Clause',simple:'Defining clause noun की पहचान तय करने के लिए जरूरी information देता है। इसके बिना meaning अधूरा या बदल सकता है। आमतौर पर commas नहीं लगते।',meaning:'A defining relative clause identifies which person or thing is meant.',structure:'noun + relative clause',examples:['The students who studied passed the test.','The book that you gave me is useful.'],clue:'कौन-से students? कौन-सी book? — answer clause में है।'},
{n:'14',title:'Non-defining Relative Clause',simple:'Non-defining clause सिर्फ extra information देता है। Main noun पहले से identify है, इसलिए commas का प्रयोग होता है। “that” non-defining clause में सामान्यतः नहीं आता।',meaning:'A non-defining relative clause adds non-essential information and is set off by commas.',structure:'noun, relative clause, ...',examples:['My brother, who lives in Delhi, is a doctor.','Patna, which is in Bihar, is a major city.'],clue:'Clause हटाने पर basic identity बनी रहती है? तो non-defining हो सकता है।'},
{n:'15',title:'Clause position और punctuation',simple:'Dependent clause पहले या बाद में आ सकता है। Introductory dependent clause के बाद comma अक्सर लगाया जाता है।',meaning:'Clause order can change, and punctuation helps show the relationship.',structure:'Dependent clause, main clause. / Main clause + dependent clause.',examples:['Although it was cold, we went outside.','We went outside although it was cold.'],clue:'पहले clause का काम और sentence rhythm देखकर punctuation जाँचो।'},
{n:'16',title:'Phrase और Clause में अंतर',simple:'Phrase में subject–finite verb relationship जरूरी नहीं होता; clause में subject और verb relationship होता है। यह difference exam में बहुत पूछा जाता है।',meaning:'A clause has a subject–verb relationship; a phrase does not necessarily.',structure:'Clause: because he was tired | Phrase: because of his tiredness',examples:['after he arrived → clause','after the arrival → phrase','in the morning → phrase'],clue:'Subject + finite verb मिल रहा है? हाँ, तो clause होने की strong संभावना है।'},
{n:'17',title:'Clause पहचानने की तेज exam method',simple:'Sentence को छोटे grammatical blocks में बाँटो। हर block में subject + verb खोजो, फिर connector और function देखो।',meaning:'Use a repeatable parsing method instead of guessing from one word.',structure:'1 subject/verb → 2 connector → 3 function → 4 complete/incomplete',examples:['I know [that she studies hard]. → noun clause','[When the rain stopped], we left. → adverb clause','The boy [who won] smiled. → relative clause'],clue:'पहले structure, फिर label. केवल connector देखकर answer मत दो।'},
{n:'18',title:'Mixed clauses — एक sentence में कई layers',simple:'एक sentence में main clause के साथ noun, relative और adverb clauses भी हो सकते हैं। हर clause का अलग काम पहचानो।',meaning:'Complex sentences may contain more than one subordinate clause.',structure:'Main clause + one or more subordinate clauses',examples:['I know that the boy who won is happy because he worked hard.','Main = I know; noun clause = that...; relative = who won; adverb = because...'],clue:'एक sentence में एक से ज़्यादा clauses देखकर confuse मत हो; उन्हें bracket करके अलग करो।'},
{n:'19',title:'Advanced clause reduction और meaning control',simple:'कुछ relative/adverb clauses context के अनुसार reduced form ले सकते हैं, लेकिन school-level transformation में meaning और subject relationship सबसे पहले जाँचो।',meaning:'Reduced clauses can shorten structures when the grammatical relationship remains clear.',structure:'students who are waiting → students waiting',examples:['The man who is standing there is my uncle. → The man standing there is my uncle.','After he finished the work, he left. → After finishing the work, he left.'],clue:'Subject mismatch होने पर reduction खतरनाक हो सकती है।'},
{n:'20',title:'Final clause audit',simple:'अंतिम checklist: clause पहचानो, main/dependent तय करो, function बताओ, connector जाँचो, relative punctuation देखो, और sentence का पूरा meaning verify करो।',meaning:'Final accuracy comes from structure + function + punctuation + meaning.',structure:'Clause type → function → connector → punctuation → meaning',examples:['She knows what I need. → noun clause','The girl who won smiled. → relative clause','Because it rained, we stayed in. → adverb clause'],clue:'Exam में सबसे पहले “यह clause क्या काम कर रहा है?” पूछना सबसे उपयोगी है।'}
];

const QUESTION_BANK=[
['A clause normally contains…',['a subject–verb relationship','only a noun','only an adjective','only a preposition'],0,'Clause की पहचान subject और verb के संबंध से होती है।'],
['Which is an independent clause?',['because it was raining','when he arrived','We stayed home.','although she was tired'],2,'“We stayed home” अपने-आप पूरा अर्थ देता है।'],
['“I know what he wants.” The noun clause is…',['I know','what he wants','he wants','know what'],1,'“what he wants” object की तरह काम कर रहा है।'],
['Choose the correct embedded question.',['I know where does he live.','I know where he lives.','I know where he live does.','I know where is he live.'],1,'Reported/embedded question में statement order रहता है: where + subject + verb.'],
['Which is a time clause?',['because he was late','when the bell rang','who won the match','what she said'],1,'“when the bell rang” समय बताता है।'],
['Which word commonly introduces a condition?',['unless','because','who','which'],0,'“unless” condition देता है और अर्थ होता है “if not”.'],
['In “If you study, you will improve”, the if-clause is…',['a noun clause','a relative clause','an adverb clause of condition','a main clause'],2,'यह शर्त बताता है, इसलिए adverb clause of condition है।'],
['Which sentence follows the common first conditional pattern?',['If it will rain, we stay home.','If it rains, we will stay home.','If it rained, we will stay home.','If it rain, we stayed home.'],1,'Common pattern: If + present, will + V1.'],
['A relative clause usually modifies…',['a noun or pronoun','a conjunction only','a punctuation mark','an auxiliary only'],0,'Relative/adjective clause noun या pronoun का description देता है।'],
['Which relative word usually refers to a place?',['whose','where','whom','what'],1,'“where” place से जुड़ी relative clause में मिलता है।'],
['Which is a defining relative clause?',['My brother, who lives in Delhi, is a doctor.','The students who studied passed.','Patna, which is in Bihar, is large.','Ravi, who won, smiled.'],1,'“who studied” बताता है कि कौन-से students।'],
['Which sentence uses a non-defining relative clause?',['The boy who won smiled.','The book that I bought is new.','My sister, who lives here, is a teacher.','The students who worked passed.'],2,'Extra information commas के बीच है।'],
['“After he arrived, we started.” The opening clause expresses…',['reason','time','condition','noun function'],1,'“after” समय-क्रम दिखाता है।'],
['Which is a phrase rather than a clause?',['because he was tired','after she arrived','in the morning','when they left'],2,'“in the morning” में subject–finite verb relationship नहीं है।'],
['The safest first step in clause identification is to find…',['the longest word','subject and finite verb','only the connector','the punctuation only'],1,'पहले grammatical blocks में subject + finite verb खोजो।'],
['Which sentence has a noun clause?',['The boy who won smiled.','We left when it rained.','She knows that I am ready.','The room is large.'],2,'“that I am ready” noun clause है और “knows” का object है।'],
['Which sentence has an adverb clause of reason?',['I know what he wants.','We stayed because it rained.','The man who came is kind.','The book is new.'],1,'“because it rained” कारण बताता है।'],
['Which sentence has a relative clause?',['I wonder whether he came.','The girl who helped me is here.','We left after lunch.','He studied hard.'],1,'“who helped me” girl को modify करता है।'],
['Which punctuation is standard for a non-defining relative clause?',['No punctuation','Commas','A colon always','A semicolon inside the clause'],1,'Non-defining relative clause commas से अलग किया जाता है।'],
['In “The list that you gave me is useful”, the relative clause modifies…',['list','gave','useful','me'],0,'“that you gave me” list के बारे में जानकारी देता है।'],
['“What she said was true.” The clause “What she said” acts as…',['subject','adverb','adjective','preposition'],0,'पूरा noun clause subject की जगह है।'],
['Which word is commonly used for possession in a relative clause?',['whose','where','when','that'],0,'“whose” possession दर्शाता है।'],
['Which is correct?',['Tell me why did she leave.','Tell me why she left.','Tell me why left she.','Tell me why does she left.'],1,'Embedded question में inversion नहीं होती।'],
['Unless you hurry, you will miss the bus. “Unless” is closest in meaning to…',['if not','because','although','when'],0,'Unless = if not.'],
['Which sentence puts a dependent clause first correctly?',['Because it rained, we stayed in.','Because it rained we stayed, in.','We because it rained stayed in.','It rained because we stayed in.'],0,'Introductory dependent clause के बाद comma standard है।'],
['A clause that functions like a noun is called…',['adverb clause','noun clause','relative clause','prepositional phrase'],1,'Noun clause noun की grammatical role निभाता है।'],
['A clause that gives information about a noun is often called…',['noun clause','adverb clause','relative/adjective clause','main clause'],2,'Relative clause noun को describe करता है।'],
['Which connector commonly introduces a reason?',['because','who','where','unless'],0,'because कारण बताता है।'],
['Which connector commonly introduces time?',['before','whose','that','because of'],0,'before time relationship बताता है।'],
['Which sentence contains two subordinate clauses?',['I left.','I know that the boy who won is happy.','She smiled.','They arrived.'],1,'“that…” noun clause के अंदर “who won” relative clause है।'],
['In “The man standing there is my uncle”, the reduced clause modifies…',['man','there','uncle','is'],0,'“standing there” man को describe करता है।'],
['A key danger in clause reduction is…',['using a shorter sentence','subject mismatch','using commas','using a connector'],1,'Reduced clause का understood subject main noun से मेल खाना चाहिए।'],
['Which sentence contains an adverb clause of time?',['When the class ended, we left.','What he said was true.','The boy who came smiled.','I know that he came.'],0,'“When the class ended” time clause है।'],
['Which sentence contains a conditional clause?',['If she studies, she will pass.','She knows what I need.','The girl who won smiled.','He left after lunch.'],0,'“If she studies” condition बताता है।'],
['Which is non-defining?',['The car that I bought is red.','My uncle, who is a doctor, lives here.','The boy who won smiled.','Students who work succeed.'],1,'“who is a doctor” extra information है।'],
['Which is defining?',['Ravi, who lives here, is my friend.','The books that are on the table are mine.','Patna, which is in Bihar, is large.','My sister, who teaches, called.'],1,'“that are on the table” बताता है कौन-सी books।'],
['In “She knows what I need”, “what I need” is…',['noun clause','time clause','relative clause','phrase'],0,'यह “knows” का object है।'],
['In “Although he was tired, he worked”, “Although he was tired” expresses…',['contrast/concession','place','possession','noun function'],0,'although concession/contrast देता है।'],
['Which sentence has a reason clause after the main clause?',['We stayed inside because it rained.','Because it rained, we stayed inside.','What he said was true.','The boy who won smiled.'],0,'Main clause के बाद because-clause reason देता है।'],
['Which question best helps identify a relative clause?',['When?','Why?','Which person/thing?','How much?'],2,'Relative clause किसी noun/person/thing की पहचान या description देता है।'],
['Which clause type often answers “what?” as a noun role?',['noun clause','adverb clause','relative clause','main clause'],0,'Noun clause noun की तरह काम करता है और what/which idea का उत्तर दे सकता है।'],
['Which word can introduce a noun clause?',['whether','quickly','under','very'],0,'whether noun clause के अंदर alternative/uncertainty introduce कर सकता है।'],
['Which statement is correct about non-defining clauses?',['They always use that.','They normally use commas.','They cannot modify nouns.','They must come first.'],1,'Non-defining relative clauses normally commas से set off होते हैं।'],
['Which is the best clause-audit order?',['Guess → label → stop','Find subject/verb → classify function → check connector/meaning','Count words → choose longest clause','Find comma only'],1,'Structure और function से systematic analysis ज्यादा reliable है।'],
['Which sentence shows a phrase replacing a clause?',['because he was tired','because of his tiredness','when he arrived','although she left'],1,'because of his tiredness phrase है; subject–finite verb clause नहीं।'],
['Which sentence has a main clause + relative clause + adverb clause?',['I know him.','The boy who won smiled because he trained hard.','What he said was true.','When he came, we left.'],1,'“who won” relative और “because he trained hard” adverb clause हैं।'],
['In “After finishing the work, he left”, the opening reduced structure is based on…',['an adverbial time relationship','a noun clause','a non-defining relative clause','a direct question'],0,'यह “After he finished the work…” जैसी time relationship को reduce करता है।'],
['Which sentence is a complete independent clause?',['although she tried','because they arrived','She solved the problem.','when we met'],2,'यह complete thought है।']
];

function bankFor(mode){if(mode==='practice')return QUESTION_BANK.slice(0,15);if(mode==='challenge')return QUESTION_BANK.slice(15,27);return QUESTION_BANK.slice(27,47)}

export default function EnglishClausesTopic({onBack,addXp,finishSession}){
 const [mode,setMode]=React.useState('learn');
 const [lesson,setLesson]=React.useState(0);
 const selected=useMemo(()=>bankFor(mode),[mode]);
 const tabs=[['learn','Learn'],['practice','Practice'],['challenge','Challenge'],['test','Final Test']];
 return <main className="clauses-page">
  <div className="clauses-top"><button onClick={onBack}>← Language & Skills</button><div><span>ENGLISH • LANGUAGE & SKILLS</span><h1>Clauses — Structure, Function & Meaning</h1><p>Clause को सिर्फ नाम से नहीं, उसके काम से समझो — पहले simple examples, फिर mixed analysis.</p></div></div>
  <nav className="clauses-tabs">{tabs.map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}>{label}</button>)}</nav>
  {mode==='learn'?<section className="clauses-learn">
   <div className="clauses-progress"><strong>Lesson {lesson+1} / {LESSONS.length}</strong><span>{LESSONS[lesson].title}</span></div>
   <article className="clause-lesson-card"><div className="lesson-num">{LESSONS[lesson].n}</div><h2>{LESSONS[lesson].title}</h2><div className="hindi-box"><b>सरल हिंदी:</b> {LESSONS[lesson].simple}</div><div className="meaning"><b>English idea:</b> {LESSONS[lesson].meaning}</div><div className="structure"><b>Structure:</b><code>{LESSONS[lesson].structure}</code></div><div className="examples"><b>Examples</b>{LESSONS[lesson].examples.map((x,i)=><div key={i}>{x}</div>)}</div><div className="clue"><b>Exam clue:</b> {LESSONS[lesson].clue}</div></article>
   <div className="lesson-actions"><button disabled={!lesson} onClick={()=>setLesson(v=>Math.max(0,v-1))}>← Previous</button>{lesson<LESSONS.length-1?<button onClick={()=>setLesson(v=>v+1)}>Next lesson →</button>:<button onClick={()=>setMode('practice')}>Start Practice →</button>}</div>
   <section className="clauses-map"><h3>Learning path</h3><div>{LESSONS.map((l,i)=><button key={l.n} className={i===lesson?'current':''} onClick={()=>setLesson(i)}><b>{l.n}</b><span>{l.title}</span></button>)}</div></section>
  </section>:<EnglishTimedQuiz key={mode} title={mode==='practice'?'Clauses Practice':mode==='challenge'?'Clauses Challenge':'Clauses Final Test'} subtitle={mode==='practice'?'Build accuracy with guided clause identification.':'Use full exam-style clause analysis with timer and complete review.'} questions={selected} mode={mode} secondsPerQuestion={mode==='practice'?45:mode==='challenge'?60:50} addXp={addXp} finishSession={finishSession} onRetry={()=>setMode(mode)} onNextLevel={()=>setMode(mode==='practice'?'challenge':mode==='challenge'?'test':'learn')} />}
 </main>
}
