import React,{useMemo,useState}from'react';
import EnglishTimedQuiz from './EnglishTimedQuiz.jsx';
import {PREPOSITION_BANKS} from './EnglishPrepositionsQuestionBank.jsx';
import './EnglishPrepositionsTopic.css';

const LESSONS=[
{n:'01',group:'FOUNDATION',title:'Preposition क्या है?',simple:'Preposition ऐसा word है जो noun/pronoun का संबंध दूसरे word से बताता है—जैसे place, time, direction या relationship।',meaning:'A preposition shows the relationship of a noun or pronoun to another word.',structure:'preposition + noun/pronoun  |  in the room • after lunch • with me',examples:['The book is on the table. → place','We met after school. → time','She went to Patna. → direction'],clue:'पूछो: कौन-सा place/time/direction/relationship दिखाया जा रहा है?'},
{n:'02',group:'TIME',title:'At, on, in — time',simple:'At exact time के लिए, on days/dates के लिए और in months, years, seasons तथा longer periods के लिए common है।',meaning:'Use at for precise times, on for days/dates, and in for longer periods.',structure:'at + clock time | on + day/date | in + month/year/period',examples:['at 6 p.m.','on Monday / on 15 August','in 2026 / in July / in winter'],clue:'Time expression की unit पहचानो: point, day/date या longer period?'},
{n:'03',group:'TIME',title:'Since और for',simple:'Since starting point बताता है; for duration बताता है। दोनों अक्सर perfect/perfect continuous structures के साथ आते हैं।',meaning:'Since marks a starting point; for marks a duration.',structure:'since + starting point | for + duration',examples:['since 2019','since Monday','for two hours','for three weeks'],clue:'“कब से?” → since; “कितने समय से?” → for.'},
{n:'04',group:'TIME',title:'By, until, till',simple:'By किसी deadline या latest time को बताता है। Until/till बताता है कि कोई action/state किस समय तक जारी रहता है।',meaning:'By marks a deadline; until/till marks continuation up to a time.',structure:'by + deadline | until/till + end point',examples:['Finish the work by Friday.','Wait until evening.','She stayed till noon.'],clue:'Deadline है तो by; action/state उस समय तक चलता है तो until/till.'},
{n:'05',group:'PLACE',title:'At, in, on — place',simple:'At किसी point/location को, in enclosed area या larger area को और on surface को दिखा सकता है।',meaning:'At often marks a point/location, in an area or enclosed space, and on a surface.',structure:'at + point | in + area/container | on + surface',examples:['at the station','in the room','on the wall'],clue:'Point, inside area, या surface—तीनों में फर्क देखो।'},
{n:'06',group:'PLACE',title:'Between और among',simple:'Between आमतौर पर दो identifiable persons/things के relation में और among group या more than two में common है।',meaning:'Between commonly relates identifiable pairs; among commonly relates members of a group.',structure:'between + two identifiable things | among + group',examples:['between Ram and Ravi','between the river and road','among the students'],clue:'Entities clearly separated हैं या group sense है?'},
{n:'07',group:'PLACE',title:'Under, over, above, below',simple:'Under नीचे, over ऊपर/पार, above higher position और below lower position दिखाते हैं।',meaning:'These prepositions express vertical position or movement with different relations.',structure:'under ↕ over ↕ above ↕ below',examples:['under the table','over the wall','above the clouds','below the line'],clue:'Position है या movement? और relation exactly क्या है?'},
{n:'08',group:'MOVEMENT',title:'Into और out of',simple:'Into बाहर से अंदर movement दिखाता है; out of अंदर से बाहर movement दिखाता है।',meaning:'Into expresses movement to the inside; out of expresses movement to the outside.',structure:'move into + place | move out of + place',examples:['The boy ran into the room.','She walked out of the house.'],clue:'Movement है तो in और into को confuse मत करो.'},
{n:'09',group:'MOVEMENT',title:'To, from, towards',simple:'To destination, from starting point और towards direction बताता है।',meaning:'To marks destination, from marks origin, and towards marks direction.',structure:'from + origin → to + destination | towards + direction',examples:['from Patna to Delhi','walk towards the gate','send it to my teacher'],clue:'Start कहाँ? Destination कहाँ? केवल direction है या exact destination?'},
{n:'10',group:'MOVEMENT',title:'Across, through, along, over',simple:'Across एक side से दूसरी side, through अंदर से होकर, along किसी line/path के साथ और over ऊपर से/पार movement दिखाते हैं।',meaning:'These prepositions distinguish different paths of movement.',structure:'across + surface/area | through + inside | along + line | over + above',examples:['walk across the road','pass through the tunnel','walk along the river','jump over the wall'],clue:'Movement path को imagine करके preposition चुनो।'},
{n:'11',group:'CAUSE/PURPOSE',title:'Because of, due to, for',simple:'Because of और due to noun phrase के साथ cause बताते हैं। For कई contexts में purpose भी बता सकता है।',meaning:'Because of and due to can express cause; for can express purpose in suitable structures.',structure:'because of + noun phrase | due to + noun phrase | for + purpose',examples:['The match stopped because of rain.','The delay was due to fog.','This room is for study.'],clue:'Reason है या purpose? क्योंकि + noun phrase हो तो because of देखें।'},
{n:'12',group:'COLLOCATION',title:'Common adjective + preposition',simple:'कुछ adjectives के साथ preposition fixed या strongly preferred होती है। इन्हें collocation की तरह सीखना useful है।',meaning:'Many adjectives have common preposition patterns.',structure:'adjective + preposition',examples:['good at maths','interested in science','afraid of dogs','proud of her work'],clue:'Adjective के बाद कौन-सा preposition natural fixed pair बनाता है?'},
{n:'13',group:'COLLOCATION',title:'Common verb + preposition',simple:'कई verbs के साथ standard prepositions आती हैं। Translation में direct Hindi mapping से गलती हो सकती है।',meaning:'Many verbs take conventional prepositions that must be learned as patterns.',structure:'verb + preposition + object/gerund',examples:['depend on parents','listen to music','belong to me','insist on going'],clue:'Verb की standard pairing याद रखो; सिर्फ Hindi का direct translation मत करो।'},
{n:'14',group:'COLLOCATION',title:'Common noun + preposition',simple:'कुछ nouns के साथ भी fixed combinations आते हैं, जैसे reason for, solution to, exception to।',meaning:'Nouns also form common prepositional patterns.',structure:'noun + preposition',examples:['reason for the delay','solution to the problem','exception to the rule','interest in science'],clue:'Noun phrase को पूरा पढ़ो; preposition अक्सर fixed pattern का हिस्सा है।'},
{n:'15',group:'ERROR CONTROL',title:'Enter, discuss, reach — extra preposition traps',simple:'कुछ verbs को unnecessary preposition की जरूरत नहीं होती। Enter the room, discuss the issue, reach the station जैसे forms याद रखो।',meaning:'Some transitive verbs normally take an object directly without an extra preposition.',structure:'enter + place | discuss + object | reach + place',examples:['enter the room ✅','discuss the issue ✅','reach the station ✅'],clue:'Verb transitive है? तो object से पहले extra preposition की जरूरत हो भी सकती है या नहीं—check करो।'},
{n:'16',group:'ERROR CONTROL',title:'Preposition + gerund',simple:'कुछ prepositions के बाद verb आए तो -ing form common होता है।',meaning:'A preposition followed by a verb normally takes the gerund form.',structure:'preposition + V-ing',examples:['interested in learning','good at drawing','before leaving','without speaking'],clue:'in, at, before, after, without जैसे prepositions के बाद verb हो तो V-ing देखें।'},
{n:'17',group:'ADVANCED',title:'Formal choices — in spite of, despite, although',simple:'In spite of और despite के बाद noun/gerund phrase आता है; although के बाद clause आता है। तीनों contrast दिखा सकते हैं।',meaning:'In spite of/despite take noun phrases or gerunds; although takes a clause.',structure:'despite/in spite of + noun/V-ing | although + clause',examples:['Despite the rain, we played.','In spite of being tired, she worked.','Although it rained, we played.'],clue:'इसके बाद noun phrase है या complete clause? उसी से form चुनो।'},
{n:'18',group:'APPLICATION',title:'Prepositions in Hindi → English translation',simple:'पहले relation identify करो—time, place, movement, reason, instrument, possession या collocation। फिर English pattern लगाओ।',meaning:'Translation improves when the intended relationship is identified before selecting the English preposition.',structure:'relation → English pattern → preposition → sentence audit',examples:['वह सोमवार को आया। → He came on Monday.','वह दो घंटे से पढ़ रहा है। → He has been studying for two hours.','वह पटना से दिल्ली गया। → He went from Patna to Delhi.'],clue:'Hindi में “से/पर/में/तक/के लिए” देखकर direct one-word mapping मत करो।'},
{n:'19',group:'EXAM CONTROL',title:'Mixed preposition audit',simple:'Option देखकर तुरंत answer मत दो। Noun/verb/adjective, meaning, time/place relation और collocation—all four check करो।',meaning:'Reliable preposition choice combines structure, meaning and collocation.',structure:'context → grammar pattern → meaning → collocation → final check',examples:['prefer tea to coffee','senior to me','responsible for the work','prevented me from going'],clue:'एक rule fail हो तो दूसरे evidence से answer verify करो।'},
{n:'20',group:'FINAL AUDIT',title:'Final Preposition Audit',simple:'Final checklist: relation पहचानो, exact preposition pattern देखो, object/gerund check करो, fixed collocation जाँचो, फिर पूरा sentence aloud/read-back करो।',meaning:'Final accuracy comes from relation + grammar pattern + collocation + sentence meaning.',structure:'relation → pattern → preposition → complement → meaning',examples:['at 7:30 ✅','on Monday ✅','in 2026 ✅','interested in science ✅','prefer tea to coffee ✅'],clue:'Exam में preposition को अकेले नहीं; उसके पूरे phrase के साथ verify करो।'}
];

const rotate=(questions,mode)=>{const shift=mode==='challenge'?1:mode==='test'?2:0;return questions.map((item,qi)=>{const[q,opts,a,e]=item;const move=(a+shift+qi)%opts.length;const next=Array(opts.length);for(let i=0;i<opts.length;i++)next[(i+move-a+opts.length)%opts.length]=opts[i];return[q,next,move,e]})};

export default function EnglishPrepositionsTopic({onBack,addXp,finishSession}){
 const initialMode=typeof window!=='undefined'?(new URLSearchParams(window.location.search).get('mode')||'learn'):'learn';
 const [mode,setMode]=useState(['learn','practice','challenge','test'].includes(initialMode)?initialMode:'learn');
 const [lesson,setLesson]=useState(0);
 const tabs=[['learn','Learn'],['practice','Practice'],['challenge','Challenge'],['test','Final Test']];
 const bank=useMemo(()=>mode==='learn'?[]:rotate(PREPOSITION_BANKS[mode],mode),[mode]);
 const changeMode=m=>{setMode(m);const p=new URLSearchParams(window.location.search);p.set('mode',m);p.set('topic','prepositions');p.set('languageSkills','1');p.set('subject','english');window.history.replaceState({},'',`${window.location.pathname}?${p}${window.location.hash||''}`)};
 return <main className="prepositions-page">
  <header className="prepositions-top"><button type="button" onClick={onBack}>← Language &amp; Skills</button><div className="prepositions-hero"><div className="prepositions-hero-main"><span>ENGLISH • LANGUAGE &amp; SKILLS</span><h1>Prepositions</h1><p>Time, place, movement, cause and collocation — rule को context से जोड़ो, फिर exam में apply करो.</p><div className="prepositions-hero-stats"><b>20</b><small>lessons</small><b>3</b><small>assessment levels</small><b>Class 9</b><small>exam focus</small></div></div><aside className="prepositions-hero-card"><strong>MASTER THE RELATION</strong><span>Time</span><span>Place + movement</span><span>Collocation</span><span>Exam control</span></aside></div></header>
  <nav className="prepositions-tabs" aria-label="Prepositions learning modes">{tabs.map(([id,label],i)=><button key={id} type="button" className={mode===id?'active':''} onClick={()=>changeMode(id)}><i>{['◫','✦','⚡','✓'][i]}</i><span>{label}</span></button>)}</nav>
  {mode==='learn'?<section className="prepositions-learning"><div className="prepositions-progress"><div><span>LEARNING PROGRESS</span><strong>Lesson {lesson+1} / {LESSONS.length}</strong></div><b>{LESSONS[lesson].group}</b><div className="prepositions-track"><i style={{width:`${((lesson+1)/LESSONS.length)*100}%`}}/></div></div><aside className="prepositions-map"><strong>LESSON PATH</strong><div>{LESSONS.map((item,i)=><button type="button" key={item.n} className={lesson===i?'active':''} onClick={()=>setLesson(i)}><em>{item.n}</em><b>{item.title}</b><small>{item.group}</small></button>)}</div></aside><article className="prepositions-lesson"><div className="prepositions-kicker"><span>{LESSONS[lesson].group}</span><b>{LESSONS[lesson].n}</b></div><h2>{LESSONS[lesson].title}</h2><div className="prepositions-simple"><strong>सरल हिंदी</strong><p>{LESSONS[lesson].simple}</p></div><section><label>Core idea</label><p className="prepositions-meaning">{LESSONS[lesson].meaning}</p></section><section><label>Structure</label><div className="prepositions-structure"><code>{LESSONS[lesson].structure}</code></div></section><section><label>Examples</label><div className="prepositions-examples">{LESSONS[lesson].examples.map((x,i)=><div key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></section><div className="prepositions-clue"><b>EXAM CLUE</b><span>{LESSONS[lesson].clue}</span></div><div className="prepositions-nav"><button type="button" disabled={lesson===0} onClick={()=>setLesson(v=>Math.max(0,v-1))}>← Previous</button><button type="button" onClick={()=>setLesson(v=>Math.min(LESSONS.length-1,v+1))} disabled={lesson===LESSONS.length-1}>Next lesson →</button></div></article></section>:<EnglishTimedQuiz key={mode} title="Prepositions" mode={mode} questions={bank} onBack={()=>changeMode('learn')} addXp={addXp} finishSession={finishSession} timePerQuestion={mode==='practice'?50:60}/>} 
 </main>;
}
