from pathlib import Path

path = Path('src/english/EnglishParagraphEssayTopic.jsx')
s = path.read_text(encoding='utf-8')

models = r'''const MODEL_WRITINGS=[
['Paragraph','Value of Time','Time is one of the most valuable resources in human life. Unlike money or material possessions, time cannot be stored for later use. Every student receives the same twenty-four hours in a day, but the results depend greatly on how those hours are planned. A student who follows a simple timetable can divide time among schoolwork, revision, reading, exercise, family responsibilities and rest. Such planning reduces last-minute pressure and makes difficult tasks easier to manage.\n\nWasting time, on the other hand, often leads to unfinished work and unnecessary stress. Spending every free moment on distractions can leave little time for important goals. This does not mean that students should study every minute; recreation and rest are also necessary. The real lesson is to give each activity an appropriate place.\n\nTherefore, we should respect time and use it wisely. Small habits such as preparing a daily plan, avoiding unnecessary delay and completing tasks on schedule can make a major difference. Good time management develops discipline and helps students use their abilities more effectively.'],
['Paragraph','A Responsible Student','A responsible student understands that education is not limited to attending classes or completing examinations. Responsibility begins with regular habits. Such a student listens carefully in class, brings the necessary books, completes assignments on time and asks questions when a concept is not clear. Instead of waiting for someone else to solve every difficulty, the student makes an honest effort to understand the work and correct mistakes.\n\nResponsibility also includes behaviour towards other people and shared spaces. A responsible student respects teachers, classmates and school property. Keeping the classroom clean, following school rules and helping others when appropriate are small actions, but together they create a positive learning environment. Being responsible also means admitting an error rather than making excuses for it.\n\nA responsible student therefore combines academic effort with good conduct. These habits make school life more meaningful and gradually prepare young people for larger responsibilities at home, in their community and in their future work. Responsibility is not a single act; it is a daily practice.'],
['Paragraph','Importance of Trees','Trees are an essential part of a healthy environment. They provide shade, support birds and other living organisms, and make public spaces more pleasant. In towns and cities, trees can make surroundings more comfortable by providing greenery and reducing the harshness of heavily built-up areas. They also contribute to the quality of the local environment and give people spaces where they can experience nature.\n\nHowever, valuable trees are often removed without considering their wider importance. Unplanned cutting can reduce green cover and disturb local habitats. Protecting trees therefore requires more than planting a few saplings once a year. Existing trees need care, young plants need protection and suitable species should be selected for local conditions. Schools can also encourage students to understand why conservation matters.\n\nEvery citizen can contribute by avoiding unnecessary damage to trees, supporting responsible planting and keeping public green areas clean. Tree conservation is not only an environmental duty; it is an investment in healthier and more pleasant communities. Protecting trees today helps preserve a greener future.'],
['Paragraph','A Rainy Morning','The rain began early in the morning and changed the usual appearance of the neighbourhood. Grey clouds covered the sky while drops of water gathered on leaves, roofs and window panes. The roads became wet and small puddles formed near the sides. People stepped outside with umbrellas and raincoats, and vehicles moved more slowly because the streets were slippery. The cool air made the morning feel very different from an ordinary day.\n\nAs the rain became heavier, shopkeepers protected their goods and pedestrians searched for covered places. The sound of raindrops mixed with the movement of traffic and the calls of people making their way to school and work. After some time, the shower became lighter. The clouds opened slightly and the wet roads reflected the soft morning light.\n\nA rainy morning can create inconvenience, but it can also bring a special beauty to ordinary surroundings. The washed leaves, fresh air and quiet moments between showers make the scene memorable. At the same time, people must travel carefully and avoid unsafe roads or waterlogged areas.'],
['Essay','Clean and Green School','A clean and green school provides a healthier, more pleasant and more effective environment for learning. Students spend many hours on the school campus, so the condition of classrooms, corridors, playgrounds and surrounding spaces directly affects their daily experience. Cleanliness also teaches an important civic lesson: shared places remain useful only when everyone takes responsibility for them.\n\nThe first step towards a clean school is proper waste management. Dustbins should be placed at practical locations and students should be encouraged to use them correctly. Where facilities permit, different kinds of waste can be separated. Regular cleaning of classrooms and common areas is also necessary. However, cleanliness cannot depend only on cleaners. Students, teachers and other staff members should avoid littering and should encourage one another to maintain good habits.\n\nA green campus can complement these efforts. Trees, gardens and suitable plants make the surroundings more attractive and provide opportunities for students to learn about nature. School gardening activities can also build cooperation and care. Plants should be protected after planting, and water should be used responsibly. Clean and green surroundings are created through regular action rather than a single cleanliness drive.\n\nIn conclusion, a clean and green school is a shared achievement. When students learn to dispose of waste properly, protect plants, keep common spaces clean and respect school property, the entire campus benefits. Such habits improve the immediate learning environment and also prepare students to behave responsibly in the wider community.'],
['Essay','The Value of Education','Education is one of the most important foundations of individual and social development. It gives learners knowledge, develops useful skills and helps them understand the world more carefully. Through education, students learn not only facts from different subjects but also how to ask questions, compare ideas, solve problems and communicate clearly. These abilities remain useful far beyond the classroom.\n\nThe value of education cannot be measured only by examination marks. A good education develops habits such as discipline, cooperation, curiosity and responsibility. When students learn to evaluate information before accepting it, they become better prepared to make thoughtful decisions. Schools also bring people together, allowing learners to work with classmates, understand different viewpoints and practise respectful discussion.\n\nEducation is closely connected with opportunity, but learning should continue throughout life. Reading books, listening to experienced people, practising skills and reflecting on mistakes can all extend what a student learns in school. A person who remains willing to learn can adapt more confidently when circumstances change.\n\nTherefore, education should be seen as preparation for both academic progress and responsible citizenship. Teachers, families and educational institutions all have roles to play, but the learner also has an important responsibility to remain curious and disciplined. Strong education helps individuals build useful abilities and gives communities informed, capable and responsible citizens.'],
['Essay','Reducing Plastic Waste','Plastic has many useful applications, but unnecessary plastic waste creates a serious environmental challenge. Many plastic items are used for a short period and then discarded. When waste is thrown carelessly, streets and public spaces become dirty, drains may become blocked and animals can be exposed to harmful litter. The problem cannot be solved by one person or one cleanliness campaign; it requires consistent habits from households, schools, businesses and local communities.\n\nOne practical approach is to reduce the use of unnecessary single-use items. Students can carry reusable water bottles and lunch containers, while families can prefer reusable bags when possible. Schools can place clearly labelled waste bins and teach students how correct disposal supports cleanliness. Awareness programmes are useful, but they become more effective when they are connected with practical facilities and regular action.\n\nCommunities can also support better waste collection and recycling systems where such facilities are available. Shops and organisations can examine whether some packaging can be reduced without creating new problems. The aim should not be to blame individuals but to make responsible choices easier and more regular.\n\nIn conclusion, reducing plastic waste is a shared responsibility. Small changes such as refusing unnecessary items, reusing useful containers, disposing of waste properly and supporting sensible local measures can reduce avoidable litter. When these habits are followed consistently, they can help keep our surroundings cleaner and encourage a more responsible attitude towards the environment.'],
['Essay','Should Homework Be Limited on Weekends?','Homework can strengthen classroom learning, but weekend homework should be planned with care. Students need time to revise lessons, read, practise difficult skills and complete meaningful projects. At the same time, they need adequate rest, family time, physical activity and opportunities to take part in other useful interests. When large amounts of repetitive homework are given every weekend, students may have difficulty balancing these different needs.\n\nA balanced policy does not mean that students should stop learning on weekends. Focused revision, reading or a carefully designed project can be valuable. The important question is whether the task has a clear learning purpose. Teachers can avoid unnecessary repetition and give work that helps students practise a key concept or prepare for the next lesson. Clear instructions and realistic deadlines can also make weekend study more manageable.\n\nStudents, too, have a responsibility. Limited homework is useful only when learners use the available time properly. A student can plan the weekend, complete important work early and keep some time for rest. This balance can make study more sustainable and may help students return to school with better concentration.\n\nTherefore, weekend homework should be limited when necessary but should not be removed completely. The best approach is purposeful, reasonable work rather than maximum quantity. A balanced schedule can support academic progress while recognising that rest, family life and healthy activities are also important parts of a student’s development.']
];
'''

hindi = r'''const HINDI_GUIDE=[
['What is a paragraph?','Paragraph एक ही मुख्य विचार पर आधारित वाक्यों का संगठित समूह है। हर वाक्य उसी central idea को समझाए, स्पष्ट करे या support करे।'],
['What is an essay?','Essay किसी बड़े विषय पर क्रमबद्ध ढंग से लिखा जाता है: Introduction में विषय की दिशा, Body में अलग-अलग points और Conclusion में समापन।'],
['Topic + controlling idea','Topic बताता है कि हम किस विषय पर लिख रहे हैं, जबकि controlling idea बताता है कि उस विषय के बारे में हमारा exact focus क्या है।'],
['Topic sentence','Topic sentence paragraph की मुख्य दिशा बताता है। इसे पढ़कर reader को पता चल जाना चाहिए कि आगे किस विचार को develop किया जाएगा।'],
['Supporting sentences','Supporting sentences मुख्य विचार को reason, example, fact, explanation या detail से मजबूत करते हैं। केवल वही बातें लिखें जो topic से जुड़ी हों।'],
['Unity','Unity का अर्थ है कि paragraph का हर sentence एक ही central idea के साथ जुड़ा रहे। अलग या attractive लेकिन unrelated बात भी focus बिगाड़ सकती है।'],
['Coherence','Coherence का मतलब ideas का logical flow है। विचार ऐसे क्रम में आएँ कि reader को बीच का connection समझने के लिए अनुमान न लगाना पड़े।'],
['Cohesive devices','First, next, however, therefore, because, for example जैसे connectors ideas के बीच संबंध दिखाते हैं। Connector तभी लगाएँ जब उसका meaning वास्तव में सही हो।'],
['Development patterns','Description, narration, cause-effect, problem-solution, comparison और argument अलग-अलग writing purposes हैं। Question देखकर सही pattern चुनना चाहिए।'],
['Introduction','Introduction में topic का context और essay की direction स्पष्ट होती है। “I am going to write…” जैसे mechanical openings से बचें।'],
['Body paragraph control','Essay के प्रत्येक body paragraph का एक clear function होना चाहिए। एक paragraph में बहुत सारे unrelated points न मिलाएँ।'],
['Examples and evidence','Example point को clearer बनाता है; वह reasoning की जगह नहीं लेता। बिना आधार के exact statistics लिखने से बचें।'],
['Argument writing','Argument में clear position, reasons, support और जरूरत पड़ने पर counterpoint होता है। सिर्फ emotion नहीं, reasoned explanation महत्वपूर्ण है।'],
['Cause and effect','Cause यानी “क्यों हुआ” और effect यानी “उसके परिणाम में क्या हुआ”। इसलिए cause और effect को उलटकर नहीं लिखना चाहिए।'],
['Problem–solution','पहले problem को स्पष्ट करें, फिर उसका impact या cause बताकर practical solution और उसका expected benefit दें।'],
['Conclusion','Conclusion में developed idea का purposeful closure होना चाहिए। बिल्कुल नया बड़ा argument अन्त में अचानक शुरू न करें।'],
['Language and editing','Ideas के बाद grammar, spelling, punctuation, articles, subject-verb agreement और sentence boundaries check करें।'],
['Exam audit','Final check में task, purpose, unity, coherence, support, language और required length देखें। कठिन vocabulary से ज्यादा clarity और relevance महत्वपूर्ण हैं।']
];
'''

start = s.index('const MODEL_WRITINGS=')
end = s.index('const TRAPS=', start)
s = s[:start] + hindi + '\n' + models + '\n' + s[end:]

needle = '<section className="pe-models">'
if 'className="pe-hindi"' not in s:
    insert = '''<section className="pe-hindi"><div className="pe-hindi-head"><span>समझो हिंदी में</span><h2>Hindi Support — Concept Clear Karo</h2><p>ये explanations केवल समझने के लिए हैं। Actual paragraph और essay examples नीचे English में ही दिए गए हैं.</p></div><div className="pe-hindi-grid">{HINDI_GUIDE.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>\n    ''' + needle
    s = s.replace(needle, insert, 1)

path.write_text(s, encoding='utf-8')
print('Paragraph/Essay content patch applied')
