import fs from 'node:fs';
const file='src/english/EnglishPanoramaChapter3.jsx';
const text=fs.readFileSync(file,'utf8');
const sections=`    {title:'Part 1 — The idea behind SMS',flow:'SMS was conceived as part of the Global System for Mobile Communication, or GSM, digital standard. The lesson presents it as a service created for exchanging short alphanumeric messages through mobile networks.',explanation:'SMS को Global System for Mobile Communication यानी GSM डिजिटल मानक के एक भाग के रूप में विकसित किया गया। पाठ इसे मोबाइल नेटवर्क के माध्यम से छोटे alphanumeric संदेशों के आदान-प्रदान की सेवा के रूप में प्रस्तुत करता है।',vocabulary:[['conceived','कल्पित / विकसित किया गया'],['GSM','Global System for Mobile Communication'],['alphanumeric','अक्षर और अंकयुक्त'],['exchange','आदान-प्रदान'],['standard','मानक']],exam:'Remember the full form of SMS and the GSM standard named in the lesson.',think:'Why was a standard important for a mobile communication service?'},
    {title:'Part 2 — SMS as a store-and-forward service',flow:'SMS is described as a store-and-forward service. A message can be kept within the network and forwarded when the destination becomes available. This makes the service useful even when the receiver is temporarily unreachable.',explanation:'SMS को store-and-forward सेवा कहा गया है। संदेश नेटवर्क में रखा जा सकता है और प्राप्तकर्ता उपलब्ध होने पर आगे भेजा जा सकता है। इसलिए प्राप्तकर्ता कुछ समय के लिए पहुँच से बाहर हो तब भी संदेश उपयोगी रहता है।',vocabulary:[['store-and-forward','संग्रह करके आगे भेजना'],['destination','गंतव्य'],['reachable','पहुँच में उपलब्ध'],['temporarily','अस्थायी रूप से'],['forward','आगे भेजना']],exam:'The store-and-forward model is the core operational idea of SMS in the article.',think:'What problem does storing a message solve?'},
    {title:'Part 3 — The work of the SMSC',flow:'Messages are routed through a Short Messaging Service Centre, or SMSC, operated by the service provider. The SMSC can store a message and forward it when the destination phone is switched on or returns to coverage.',explanation:'संदेश सेवा प्रदाता के Short Messaging Service Centre यानी SMSC से होकर भेजे जाते हैं। SMSC संदेश को सुरक्षित रख सकता है और मोबाइल चालू होने या coverage में लौटने पर उसे आगे भेज सकता है।',vocabulary:[['routed','मार्ग से भेजा गया'],['SMSC','Short Messaging Service Centre'],['provider','सेवा प्रदाता'],['coverage','सेवा उपलब्ध क्षेत्र'],['destination','गंतव्य']],exam:'Know the role of the SMSC: routing, storage and forwarding.',think:'Why is an intermediate centre useful in a store-and-forward system?'},
    {title:'Part 4 — SMS during a voice call',flow:'The lesson says a short message can be sent or received while a voice call is taking place. A voice call uses a dedicated radio channel while short messages use the signalling path, allowing the two services to coexist.',explanation:'पाठ के अनुसार voice call के दौरान भी SMS भेजा या प्राप्त किया जा सकता है। Voice call के लिए dedicated radio channel और short messages के लिए signalling path का उल्लेख किया गया है, इसलिए दोनों सेवाएँ साथ चल सकती हैं।',vocabulary:[['simultaneously','एक ही समय में'],['dedicated','विशेष रूप से निर्धारित'],['radio channel','रेडियो चैनल'],['signalling path','सिग्नलिंग मार्ग'],['coexist','साथ-साथ मौजूद रहना']],exam:'Use the channel distinction when answering why SMS can coexist with a voice call.',think:'What would happen if both services had to occupy exactly the same resource?'},
    {title:'Part 5 — Delivery, alerts and congestion',flow:'The lesson discusses delivery confirmation and alerts, while also noting that actual delivery can be delayed by congestion. Thus the communication process can provide feedback quickly even when the message itself takes longer to reach the destination.',explanation:'पाठ delivery confirmation और alerts की चर्चा करता है, लेकिन यह भी बताता है कि congestion के कारण वास्तविक delivery में देरी हो सकती है। इसलिए feedback जल्दी मिल सकता है, जबकि संदेश को पहुँचने में अधिक समय लग सकता है।',vocabulary:[['confirmation','पुष्टि'],['alert','सूचना / चेतावनी'],['congestion','नेटवर्क दबाव'],['delay','देरी'],['delivery','संदेश पहुँचाना']],exam:'Congestion is the reason given in the lesson for possible delivery delays.',think:'Why is confirmation not always the same thing as final delivery?'},
    {title:'Part 6 — SMS and Instant Messaging',flow:'SMS is contrasted with Instant Messaging. The article explains that IM can support virtually real-time conversations among people who are simultaneously logged on to the Internet, whereas SMS is based on store-and-forward messaging.',explanation:'SMS की तुलना Instant Messaging से की गई है। लेख के अनुसार IM में Internet पर एक साथ logged-on लोग लगभग real-time बातचीत कर सकते हैं, जबकि SMS store-and-forward model पर आधारित है।',vocabulary:[['instant messaging','तुरंत संदेश सेवा'],['virtually','लगभग'],['real time','लगभग उसी समय'],['logged on','इंटरनेट से जुड़ा हुआ'],['contrast','अंतर / विरोध']],exam:'State the central difference between SMS and Instant Messaging in the lesson.',think:'Why does being logged on together matter to the IM comparison?'},
    {title:'Part 7 — Early advantages and limitations',flow:'The launch of SMS opened a new vista in text communication, but early users also faced limitations. The article mentions a 160-character limit and the tedious process of typing on small handset keypads.',explanation:'SMS के आने से text communication में नया अवसर खुला, लेकिन शुरुआती उपयोग में सीमाएँ भी थीं। लेख 160-character limit और छोटे handset keypads पर typing की कठिनाई का उल्लेख करता है।',vocabulary:[['vista','नया अवसर / व्यापक दृष्टिकोण'],['limitation','सीमा'],['character','अक्षर'],['tedious','थकाऊ'],['keypad','बटनयुक्त input panel']],exam:'The 160-character limit and difficult keypad typing are important exam facts from the source.',think:'How might a strict character limit affect the way people write messages?'},
    {title:'Part 8 — The spread of the SMS revolution',flow:'The article says the SMS revolution took roots in Europe and then spread to other parts of the world, especially Asia. It uses a historical detail about December 1992 and a PC-to-mobile message on the Vodafone GSM network in the UK.',explanation:'लेख के अनुसार SMS क्रांति ने पहले यूरोप में जड़ें जमाईं और फिर दुनिया के अन्य हिस्सों, विशेषकर एशिया, में फैली। इसमें दिसंबर 1992 तथा UK के Vodafone GSM network पर PC से mobile को भेजे गए संदेश का ऐतिहासिक उल्लेख है।',vocabulary:[['roots','प्रारंभिक आधार / जड़ें'],['spread','फैलाव'],['historical','ऐतिहासिक'],['network','संचार तंत्र'],['UK','United Kingdom']],exam:'Remember the lesson’s historical marker: December 1992 and the UK Vodafone GSM network.',think:'Why does a communication technology spread beyond the place where it first develops?'},
    {title:'Part 9 — Industry response and language compatibility',flow:'SMS started quietly but its potential soon attracted the mobile industry. The lesson mentions growing interest and gives a Hindi-compatible Nokia handset as an example of how changing technology and user needs shaped the market.',explanation:'SMS की शुरुआत शांत ढंग से हुई, लेकिन इसकी संभावनाओं ने जल्दी ही मोबाइल उद्योग का ध्यान आकर्षित किया। पाठ Hindi-compatible Nokia handset का उदाहरण देता है, जो बदलती तकनीक और उपयोगकर्ता की जरूरतों को दिखाता है।',vocabulary:[['potential','संभावना / क्षमता'],['industry','उद्योग'],['compatible','अनुकूल'],['market','बाजार'],['adoption','अपनाया जाना']],exam:'The handset example illustrates adaptation to wider users and markets.',think:'Why is language compatibility important for communication technology?'},
    {title:'Part 10 — From SMS to MMS',flow:'The lesson closes by showing the next stage in messaging: MMS. Multimedia Messaging Service could carry pictures, sounds and longer text through multimedia-capable terminals and addresses. The ending shows technology moving from short text towards richer forms of communication.',explanation:'पाठ का अंत messaging की अगली अवस्था MMS से होता है। Multimedia Messaging Service pictures, sounds और longer text भेज सकती थी और multimedia-capable terminals तथा addresses का उपयोग करती थी। इससे technology के अधिक समृद्ध communication की ओर बढ़ने का संकेत मिलता है।',vocabulary:[['MMS','Multimedia Messaging Service'],['multimedia','बहु-माध्यमीय'],['terminal','संचार उपकरण'],['longer text','लंबा पाठ'],['evolution','क्रमिक विकास']],exam:'The final movement is SMS → wider adoption → MMS and multimedia communication.',think:'How does the shift from SMS to MMS show the evolution of communication technology?'}
  ]`;
const re=/sections:\[\n[\s\S]*?\n  \],\n  glossary:/;
if(!re.test(text)) throw new Error('Chapter 3 sections block not found');
const next=text.replace(re,`sections:[\n${sections}\n  ],\n  glossary:`).replace(/8 guided parts/g,'10 guided parts');
fs.writeFileSync(file,next);
console.log('Chapter 3 migrated to 10 guided parts.');
