import fs from 'node:fs';

const files = {
  'src/english/EnglishPanoramaChapter2.jsx': [
`    {title:'Part 1 — Yayati as a respected ruler',flow:'Yayati is introduced as a powerful emperor and an ancestor of the Pandavas. The lesson presents him as a ruler who follows the shastras, honours the gods and serves his subjects. This establishes the respected position from which his later crisis begins.',explanation:'ययाति एक शक्तिशाली सम्राट और पांडवों के पूर्वज के रूप में प्रस्तुत किए गए हैं। वे शास्त्रों का पालन करते हैं, देवताओं का सम्मान करते हैं और अपनी प्रजा की सेवा करते हैं। इसी प्रतिष्ठित स्थिति से आगे उनके जीवन में संकट शुरू होता है।',vocabulary:[['emperor','सम्राट'],['ancestor','पूर्वज'],['shastras','शास्त्र'],['venerate','गहराई से सम्मान करना'],['subjects','प्रजा']],exam:'Remember Yayati’s starting position: powerful ruler, respected by his people and guided by the shastras.',think:'Why is it useful to know Yayati’s character before the curse changes his life?'},
    {title:'Part 2 — The curse and premature old age',flow:'Sukracharya’s curse changes Yayati’s condition and makes him old before the natural time. The sudden physical change becomes the central problem of the story because his desire for worldly enjoyment has not disappeared with youth.',explanation:'शुक्राचार्य के शाप से ययाति समय से पहले वृद्ध हो जाते हैं। यह अचानक आया परिवर्तन कहानी की मुख्य समस्या बन जाता है, क्योंकि युवावस्था के साथ-साथ उनकी सांसारिक सुखों की इच्छा समाप्त नहीं हुई है।',vocabulary:[['curse','शाप'],['premature','समय से पहले'],['old age','वृद्धावस्था'],['condition','स्थिति'],['worldly','सांसारिक']],exam:'The curse creates the central conflict: old age has arrived, but desire for enjoyment remains.',think:'Why does physical age and inner desire become an important contrast here?'},
    {title:'Part 3 — Yayati cannot accept the loss of youth',flow:'Yayati suffers from the weakness and misery of old age. He is distressed because his body can no longer support the life of pleasure he still wants. Instead of accepting the situation immediately, he searches for a way to regain youth.',explanation:'ययाति वृद्धावस्था की कमजोरी और पीड़ा से दुखी हैं। उनका शरीर उस सुखमय जीवन का साथ नहीं देता जिसे वे अभी भी चाहते हैं। इसलिए वे तुरंत परिस्थिति को स्वीकार करने के बजाय फिर से युवावस्था पाने का उपाय खोजते हैं।',vocabulary:[['misery','दुःख / कष्ट'],['distressed','व्यथित'],['vigour','शक्ति / जोश'],['regain','फिर से प्राप्त करना'],['pleasure','सुख']],exam:'Know why Yayati wants his youth back instead of simply accepting old age.',think:'What does Yayati’s reaction tell us about his attachment to youth?'},
    {title:'Part 4 — The request to his sons',flow:'Yayati calls his sons and asks one of them to exchange youth for his old age. The request places a serious burden on the sons, because accepting it means losing their own youth for their father’s sake.',explanation:'ययाति अपने पुत्रों को बुलाकर उनमें से किसी एक से अपनी वृद्धावस्था लेने और अपनी युवावस्था देने का अनुरोध करते हैं। यह पुत्रों के सामने एक भारी जिम्मेदारी रख देता है, क्योंकि उन्हें पिता के लिए अपनी युवावस्था छोड़नी होगी।',vocabulary:[['request','अनुरोध'],['exchange','विनिमय'],['burden','भार'],['youth','युवावस्था'],['bidding','आदेश / आग्रह']],exam:'Understand exactly what Yayati asks his sons to exchange.',think:'Would such a request be easy for a young person to accept? Why?'},
    {title:'Part 5 — The sons refuse for different reasons',flow:'The elder sons do not agree to take Yayati’s old age. Their replies create a contrast within the family and show how difficult it is for them to sacrifice youth. The sequence of refusals prepares the reader for Puru’s very different response.',explanation:'बड़े पुत्र ययाति की वृद्धावस्था लेने के लिए तैयार नहीं होते। उनके अलग-अलग उत्तर यह दिखाते हैं कि युवावस्था त्यागना उनके लिए कितना कठिन है। इन इनकारों के बाद पुरु की अलग प्रतिक्रिया और भी स्पष्ट हो जाती है।',vocabulary:[['refuse','इनकार करना'],['sacrifice','त्याग'],['elder','बड़ा'],['response','प्रतिक्रिया'],['contrast','विरोध / अंतर']],exam:'Compare the refusals of the elder sons with Puru’s later willingness.',think:'Why does the story present several refusals instead of only one?'},
    {title:'Part 6 — Puru accepts the sacrifice',flow:'Puru, the youngest son, agrees to take his father’s old age and give his youth to him. His willingness removes the obstacle that the other sons could not overcome. Yayati therefore becomes young again while Puru bears the burden of old age.',explanation:'सबसे छोटे पुत्र पुरु अपने पिता की वृद्धावस्था स्वीकार करने और अपनी युवावस्था उन्हें देने के लिए तैयार हो जाते हैं। उनके इस त्याग से वह बाधा दूर हो जाती है जिसे दूसरे पुत्र पार नहीं कर पाए थे। ययाति फिर युवा हो जाते हैं और पुरु वृद्धावस्था का भार उठाते हैं।',vocabulary:[['youngest','सबसे छोटा'],['willingness','इच्छा से तैयार होना'],['filial','पुत्रधर्म से संबंधित'],['burden','भार'],['sacrifice','बलिदान / त्याग']],exam:'Puru’s filial love is the decisive turning point of the narrative.',think:'What makes Puru’s decision different from that of his brothers?'},
    {title:'Part 7 — Youth returns, but desire remains',flow:'With youth restored, Yayati again experiences worldly pleasures. The change in his body does not remove the desire within his mind. The story therefore tests whether more pleasure can actually produce lasting satisfaction.',explanation:'युवावस्था वापस मिलने के बाद ययाति फिर सांसारिक सुखों का अनुभव करते हैं। शरीर तो युवा हो जाता है, लेकिन मन की इच्छाएँ समाप्त नहीं होतीं। इस प्रकार कहानी यह प्रश्न उठाती है कि क्या अधिक सुख वास्तव में स्थायी संतोष दे सकता है।',vocabulary:[['restore','वापस स्थापित करना'],['worldly','सांसारिक'],['desire','इच्छा'],['satisfaction','संतोष'],['experience','अनुभव']],exam:'Do not stop the story at the exchange; the later experience is essential to the moral.',think:'Why is getting youth back not enough for Yayati?'},
    {title:'Part 8 — The experience of continued indulgence',flow:'Yayati continues to enjoy life and visits the garden of Kubera. Even with youth and opportunity for pleasure, he finds that desire does not simply disappear. This experience gives him the evidence needed for his final insight.',explanation:'ययाति जीवन के सुखों का आनंद लेते रहते हैं और कुबेर के बगीचे में जाते हैं। युवावस्था और सुख के अवसर मिलने पर भी इच्छाएँ अपने-आप समाप्त नहीं होतीं। यही अनुभव उन्हें आगे मिलने वाली अंतिम समझ तक पहुँचाता है।',vocabulary:[['indulgence','अति-भोग'],['quench','शांत करना / बुझाना'],['garden','उद्यान'],['evidence','प्रमाण'],['insight','गहरी समझ']],exam:'The continued search for pleasure is the bridge between restored youth and Yayati’s realisation.',think:'What does repeated indulgence teach Yayati that a single pleasure could not?'},
    {title:'Part 9 — Yayati learns the nature of desire',flow:'Yayati realises that desire may grow instead of disappearing when it is repeatedly indulged. Wealth and pleasure cannot by themselves create complete peace. He begins to understand the importance of moving beyond attachment and dislike.',explanation:'ययाति समझते हैं कि बार-बार भोग करने से इच्छाएँ समाप्त होने के बजाय बढ़ सकती हैं। केवल धन और सांसारिक सुख पूर्ण शांति नहीं दे सकते। वे आसक्ति और द्वेष से ऊपर उठने के महत्व को समझने लगते हैं।',vocabulary:[['attachment','आसक्ति'],['dislike','द्वेष / अरुचि'],['wealth','धन'],['restraint','संयम'],['peace','शांति']],exam:'This part contains the central moral idea of the lesson: indulgence is not a permanent cure for desire.',think:'How does Yayati’s experience change the way he understands happiness?'},
    {title:'Part 10 — Returning youth and accepting responsibility',flow:'Yayati finally gives Puru his youth back and accepts old age again. Puru rules the kingdom wisely and becomes renowned, while Yayati retires to the forest and practises austerities. The ending connects personal realisation with responsibility and restraint.',explanation:'अंत में ययाति पुरु को उसकी युवावस्था वापस कर अपनी वृद्धावस्था स्वीकार कर लेते हैं। पुरु बुद्धिमानी से राज्य करते हैं और प्रसिद्ध होते हैं। ययाति वन में जाकर तप करते हैं। इस प्रकार अंत में आत्मबोध, जिम्मेदारी और संयम एक साथ जुड़ जाते हैं।',vocabulary:[['renowned','प्रसिद्ध'],['austerities','तप / साधना'],['responsibility','जिम्मेदारी'],['restraint','संयम'],['retire','वन / एकांत में जाना']],exam:'Know the complete ending: Puru rules wisely; Yayati returns to old age and austerity.',think:'How does the ending complete Yayati’s movement from desire toward restraint?'}
`
  ],
  'src/english/EnglishPanoramaChapter3.jsx': [
`    {title:'Part 1 — The idea behind SMS',flow:'SMS was conceived as part of the Global System for Mobile Communication, or GSM, digital standard. The lesson presents it as a service created for exchanging short alphanumeric messages through mobile networks.',explanation:'SMS को Global System for Mobile Communication यानी GSM डिजिटल मानक के एक भाग के रूप में विकसित किया गया। पाठ इसे मोबाइल नेटवर्क के माध्यम से छोटे alphanumeric संदेशों के आदान-प्रदान की सेवा के रूप में प्रस्तुत करता है।',vocabulary:[['conceived','कल्पित / विकसित किया गया'],['GSM','Global System for Mobile Communication'],['alphanumeric','अक्षर और अंकयुक्त'],['exchange','आदान-प्रदान'],['standard','मानक']],exam:'Remember the full form of SMS and the GSM standard named in the lesson.',think:'Why was a standard important for a mobile communication service?'},
    {title:'Part 2 — SMS as a store-and-forward service',flow:'SMS is described as a store-and-forward service. A message can be kept within the network and forwarded when the destination becomes available. This makes the service useful even when the receiver is temporarily unreachable.',explanation:'SMS को store-and-forward सेवा कहा गया है। संदेश नेटवर्क में रखा जा सकता है और प्राप्तकर्ता उपलब्ध होने पर आगे भेजा जा सकता है। इसलिए प्राप्तकर्ता कुछ समय के लिए पहुँच से बाहर हो तब भी संदेश उपयोगी रहता है।',vocabulary:[['store-and-forward','संग्रह करके आगे भेजना'],['destination','गंतव्य'],['reachable','पहुँच में उपलब्ध'],['temporarily','अस्थायी रूप से'],['forward','आगे भेजना']],exam:'The store-and-forward model is the core operational idea of SMS in the article.',think:'What problem does storing a message solve?'},
    {title:'Part 3 — The work of the SMSC',flow:'Messages are routed through a Short Messaging Service Centre, or SMSC, operated by the service provider. The SMSC can store a message and forward it when the destination phone is switched on or returns to coverage.',explanation:'संदेश सेवा प्रदाता के Short Messaging Service Centre यानी SMSC से होकर भेजे जाते हैं। SMSC संदेश को सुरक्षित रख सकता है और मोबाइल चालू होने या coverage में लौटने पर उसे आगे भेज सकता है।',vocabulary:[['routed','मार्ग से भेजा गया'],['SMSC','Short Messaging Service Centre'],['provider','सेवा प्रदाता'],['coverage','सेवा उपलब्ध क्षेत्र'],['destination','गंतव्य']],exam:'Know the role of the SMSC: routing, storage and forwarding.',think:'Why is an intermediate centre useful in a store-and-forward system?'},
    {title:'Part 4 — SMS during a voice call',flow:'The lesson says a short message can be sent or received while a voice call is taking place. A voice call uses a dedicated radio channel while short messages use the signalling path, allowing the two services to coexist.',explanation:'पाठ के अनुसार voice call के दौरान भी SMS भेजा या प्राप्त किया जा सकता है। Voice call के लिए dedicated radio channel और short messages के लिए signalling path का उल्लेख किया गया है, इसलिए दोनों सेवाएँ साथ चल सकती हैं।',vocabulary:[['simultaneously','एक ही समय में'],['dedicated','विशेष रूप से निर्धारित'],['radio channel','रेडियो चैनल'],['signalling path','सिग्नलिंग मार्ग'],['coexist','साथ-साथ मौजूद रहना']],exam:'Use the channel distinction when answering why SMS can coexist with a voice call.',think:'What would happen if both services had to occupy exactly the same resource?'},
    {title:'Part 5 — Delivery, alerts and congestion',flow:'The lesson discusses delivery confirmation and alerts, while also noting that actual delivery can be delayed by congestion. Thus the communication process can provide feedback quickly even when the message itself takes longer to reach the destination.',explanation:'पाठ delivery confirmation और alerts की चर्चा करता है, लेकिन यह भी बताता है कि congestion के कारण वास्तविक delivery में देरी हो सकती है। इसलिए feedback जल्दी मिल सकता है, जबकि संदेश को पहुँचने में अधिक समय लग सकता है।',vocabulary:[['confirmation','पुष्टि'],['alert','सूचना / चेतावनी'],['congestion','नेटवर्क दबाव'],['delay','देरी'],['delivery','संदेश पहुँचाना']],exam:'Congestion is the reason given in the lesson for possible delivery delays.',think:'Why is confirmation not always the same thing as final delivery?'},
    {title:'Part 6 — SMS and Instant Messaging',flow:'SMS is contrasted with Instant Messaging. The article explains that IM can support virtually real-time conversations among people who are simultaneously logged on to the Internet, whereas SMS is based on store-and-forward messaging.',explanation:'SMS की तुलना Instant Messaging से की गई है। लेख के अनुसार IM में Internet पर एक साथ logged-on लोग लगभग real-time बातचीत कर सकते हैं, जबकि SMS store-and-forward model पर आधारित है।',vocabulary:[['instant messaging','तुरंत संदेश सेवा'],['virtually','लगभग'],['real time','लगभग उसी समय'],['logged on','इंटरनेट से जुड़ा हुआ'],['contrast','अंतर / विरोध']],exam:'State the central difference between SMS and Instant Messaging in the lesson.',think:'Why does being logged on together matter to the IM comparison?'},
    {title:'Part 7 — Early advantages and limitations',flow:'The launch of SMS opened a new vista in text communication, but early users also faced limitations. The article mentions a 160-character limit and the tedious process of typing on small handset keypads.',explanation:'SMS के आने से text communication में नया अवसर खुला, लेकिन शुरुआती उपयोग में सीमाएँ भी थीं। लेख 160-character limit और छोटे handset keypads पर typing की कठिनाई का उल्लेख करता है।',vocabulary:[['vista','नया अवसर / व्यापक दृष्टिकोण'],['limitation','सीमा'],['character','अक्षर'],['tedious','थकाऊ'],['keypad','बटनयुक्त input panel']],exam:'The 160-character limit and difficult keypad typing are important exam facts from the source.',think:'How might a strict character limit affect the way people write messages?'},
    {title:'Part 8 — The spread of the SMS revolution',flow:'The article says the SMS revolution took roots in Europe and then spread to other parts of the world, especially Asia. It uses a historical detail about December 1992 and a PC-to-mobile message on the Vodafone GSM network in the UK.',explanation:'लेख के अनुसार SMS क्रांति ने पहले यूरोप में जड़ें जमाईं और फिर दुनिया के अन्य हिस्सों, विशेषकर एशिया, में फैली। इसमें दिसंबर 1992 तथा UK के Vodafone GSM network पर PC से mobile को भेजे गए संदेश का ऐतिहासिक उल्लेख है।',vocabulary:[['roots','प्रारंभिक आधार / जड़ें'],['spread','फैलाव'],['historical','ऐतिहासिक'],['network','संचार तंत्र'],['UK','United Kingdom']],exam:'Remember the lesson’s historical marker: December 1992 and the UK Vodafone GSM network.',think:'Why does a communication technology spread beyond the place where it first develops?'},
    {title:'Part 9 — Industry response and language compatibility',flow:'SMS started quietly but its potential soon attracted the mobile industry. The lesson mentions growing interest and gives a Hindi-compatible Nokia handset as an example of how changing technology and user needs shaped the market.',explanation:'SMS की शुरुआत शांत ढंग से हुई, लेकिन इसकी संभावनाओं ने जल्दी ही मोबाइल उद्योग का ध्यान आकर्षित किया। पाठ Hindi-compatible Nokia handset का उदाहरण देता है, जो बदलती तकनीक और उपयोगकर्ता की जरूरतों को दिखाता है।',vocabulary:[['potential','संभावना / क्षमता'],['industry','उद्योग'],['compatible','अनुकूल'],['market','बाजार'],['adoption','अपनाया जाना']],exam:'The handset example illustrates adaptation to wider users and markets.',think:'Why is language compatibility important for communication technology?'},
    {title:'Part 10 — From SMS to MMS',flow:'The lesson closes by showing the next stage in messaging: MMS. Multimedia Messaging Service could carry pictures, sounds and longer text through multimedia-capable terminals and addresses. The ending shows technology moving from short text towards richer forms of communication.',explanation:'पाठ का अंत messaging की अगली अवस्था MMS से होता है। Multimedia Messaging Service pictures, sounds और longer text भेज सकती थी और multimedia-capable terminals तथा addresses का उपयोग करती थी। इससे technology के अधिक समृद्ध communication की ओर बढ़ने का संकेत मिलता है।',vocabulary:[['MMS','Multimedia Messaging Service'],['multimedia','बहु-माध्यमीय'],['terminal','संचार उपकरण'],['longer text','लंबा पाठ'],['evolution','क्रमिक विकास']],exam:'The final movement is SMS → wider adoption → MMS and multimedia communication.',think:'How does the shift from SMS to MMS show the evolution of communication technology?'}
`
  ],
  'src/english/EnglishPanoramaChapter4.jsx': [
`    {title:'Part 1 — Population in earlier human history',flow:'For most of human existence, births were only slightly higher than deaths, so population increased slowly. Better nutrition and sanitation changed this balance, helping people live longer and allowing more people to reach reproductive age.',explanation:'मानव इतिहास के अधिकांश समय में जन्मों की संख्या मृत्यु से केवल थोड़ी अधिक थी, इसलिए जनसंख्या धीरे बढ़ती थी। पोषण और स्वच्छता में सुधार से लोग अधिक समय तक जीने लगे और अधिक लोग प्रजनन आयु तक पहुँचने लगे।',vocabulary:[['existence','अस्तित्व'],['nutrition','पोषण'],['sanitation','स्वच्छता'],['reproductive age','प्रजनन आयु'],['balance','संतुलन']],exam:'Learn the cause chain: improved nutrition and sanitation → longer life → more people reaching reproductive age.',think:'How can improvements in living conditions change population growth?'},
    {title:'Part 2 — Why rapid growth creates an ecological limit',flow:'More people may appear beneficial because people can create inventions and profit, but the lesson argues that the world is finite. From an ecological point of view, unlimited population growth puts increasing pressure on food, resources and the environment.',explanation:'अधिक लोगों की संख्या लाभदायक लग सकती है क्योंकि मनुष्य आविष्कार और आर्थिक लाभ ला सकते हैं, लेकिन पृथ्वी सीमित है। पाठ के अनुसार असीमित जनसंख्या वृद्धि भोजन, संसाधनों और पर्यावरण पर बढ़ता दबाव डालती है।',vocabulary:[['finite','सीमित'],['ecological','पारिस्थितिक'],['overpopulated','अधिक जनसंख्या वाला'],['resource','संसाधन'],['pressure','दबाव']],exam:'Distinguish the apparent benefits of more people from the ecological limits described by the author.',think:'Why does a finite planet make unlimited growth difficult?'},
    {title:'Part 3 — Food, land and crowding pressures',flow:'As population rises, the need for food, land and other resources rises too. Towns and countries become more crowded, and pressure to clear forests grows. The chapter presents population growth as a factor that can intensify several connected problems.',explanation:'जनसंख्या बढ़ने पर भोजन, भूमि और अन्य संसाधनों की आवश्यकता भी बढ़ती है। शहर और देश अधिक भीड़भाड़ वाले हो जाते हैं और वनों को साफ करने का दबाव बढ़ता है। पाठ जनसंख्या वृद्धि को कई जुड़ी समस्याओं को गंभीर बनाने वाले कारक के रूप में प्रस्तुत करता है।',vocabulary:[['crowded','भीड़भाड़ वाला'],['deforestation','वनों की कटाई'],['density','घनत्व'],['demand','माँग'],['intensify','और गंभीर करना']],exam:'Connect population growth with greater food demand, resource use and forest pressure.',think:'How can one increase in population create several different pressures at once?'},
    {title:'Part 4 — Pollution and quality of life',flow:'The lesson connects population density with pollution of rivers, lakes, air, water and soil. It also says that quality of life can fall when crowding and environmental stress become severe, and it mentions possible social problems such as crime, ethnic conflict and warfare.',explanation:'पाठ जनसंख्या घनत्व को नदियों, झीलों, वायु, जल और मिट्टी के प्रदूषण से जोड़ता है। भीड़भाड़ और पर्यावरणीय दबाव बढ़ने पर जीवन की गुणवत्ता कम हो सकती है। पाठ अपराध, जातीय संघर्ष और युद्ध जैसे संभावित सामाजिक समस्याओं का भी उल्लेख करता है।',vocabulary:[['pollution','प्रदूषण'],['quality of life','जीवन की गुणवत्ता'],['ethnic','जातीय'],['conflict','संघर्ष'],['warfare','युद्ध'],exam:'Remember both environmental and social effects of very high population density.',think:'Why does the lesson treat population density as more than just a number?'},
    {title:'Part 5 — Air pollution and public health',flow:'The American example in the lesson shows how pollution can worsen respiratory illness and asthma. The point is not only environmental damage: polluted surroundings can directly affect human health. The author uses this link to strengthen the argument for controlling harmful pressures.',explanation:'पाठ में दिए गए अमेरिकी उदाहरण से पता चलता है कि प्रदूषण श्वसन संबंधी रोगों और अस्थमा को बढ़ा सकता है। समस्या केवल पर्यावरण की नहीं है; प्रदूषित वातावरण सीधे मानव स्वास्थ्य को प्रभावित कर सकता है। लेखक इस संबंध से हानिकारक दबावों को नियंत्रित करने के पक्ष को मजबूत करता है।',vocabulary:[['respiratory','श्वसन संबंधी'],['asthma','अस्थमा'],['aggravate','और गंभीर करना'],['incidence','प्रचलन / घटना'],['public health','जनस्वास्थ्य']],exam:'Use the pollution example to connect environmental quality with human health.',think:'Why is an environmental problem also a public-health problem?'},
    {title:'Part 6 — Global environmental changes',flow:'The essay expands the discussion to desertification, depletion of non-renewable resources, acid rain, loss of wild species, ozone-layer depletion and the greenhouse effect. A United Nations document cited by the lesson links population size and growth rates with environmental change.',explanation:'निबंध पर्यावरणीय समस्याओं की सूची को मरुस्थलीकरण, अनवीकरणीय संसाधनों की कमी, अम्लीय वर्षा, वन्य प्रजातियों की हानि, ओजोन परत के क्षय और ग्रीनहाउस प्रभाव तक बढ़ाता है। पाठ में उद्धृत संयुक्त राष्ट्र दस्तावेज जनसंख्या के आकार और वृद्धि दर को पर्यावरणीय परिवर्तन से जोड़ता है।',vocabulary:[['desertification','मरुस्थलीकरण'],['non-renewable','अनवीकरणीय'],['acid rain','अम्लीय वर्षा'],['species','प्रजाति'],['greenhouse effect','ग्रीनहाउस प्रभाव']],exam:'Be ready to name several global environmental problems explicitly listed in the chapter.',think:'Why does the author move from local pressure to global environmental change?'},
    {title:'Part 7 — Population control and social factors',flow:'The chapter says restoring the biosphere depends partly on slowing population growth. Germany, Sweden, China, Thailand and Egypt are given as examples. Education, literacy, media campaigns, family planning and opportunities for women are among the factors listed to explain slower growth.',explanation:'अध्याय के अनुसार जीवमंडल को सँभालने के लिए जनसंख्या वृद्धि को धीमा करना एक महत्त्वपूर्ण कदम है। जर्मनी, स्वीडन, चीन, थाईलैंड और मिस्र उदाहरण के रूप में दिए गए हैं। शिक्षा, साक्षरता, मीडिया अभियान, परिवार नियोजन तथा महिलाओं के अवसर जैसे कारणों का उल्लेख किया गया है।',vocabulary:[['biosphere','जीवमंडल'],['literacy','साक्षरता'],['campaign','अभियान'],['family planning','परिवार नियोजन'],['opportunity','अवसर']],exam:'Memorise both the country examples and the social factors listed in the source.',think:'How can education and women’s opportunities influence population trends?'},
    {title:'Part 8 — Poverty and forest clearance',flow:'The author explains that poverty and related conditions can force people in poorer countries to clear, burn or cultivate tropical forests. Nepal is used as an example of pressure on trees and forests for fuel and livelihood needs.',explanation:'लेखक बताते हैं कि गरीबी और उससे जुड़ी परिस्थितियाँ गरीब देशों के लोगों को उष्णकटिबंधीय वनों को काटने, जलाने या खेती के लिए उपयोग करने पर मजबूर कर सकती हैं। नेपाल का उदाहरण ईंधन और जीवन-यापन के लिए पेड़ों पर बढ़ते दबाव को दिखाता है।',vocabulary:[['tropical','उष्णकटिबंधीय'],['clear','वन हटाना'],['cultivate','खेती करना'],['fuel','ईंधन'],['livelihood','जीवन-यापन']],exam:'Explain how poverty can create direct pressure on tropical forests.',think:'Why might people clear forests even when forest loss is harmful in the long term?'},
    {title:'Part 9 — Affluence and consumer demand',flow:'Deforestation is not driven only by poverty. The lesson also points to affluent consumers and demand for products such as hamburgers, mahogany furniture, newspapers and paper. Consumption in one place can therefore contribute to forest clearance elsewhere.',explanation:'वनों की कटाई केवल गरीबी के कारण नहीं होती। पाठ समृद्ध उपभोक्ताओं की माँग और हैमबर्गर, महोगनी फर्नीचर, समाचारपत्र तथा कागज जैसे उत्पादों का उदाहरण भी देता है। इसलिए एक स्थान की खपत दूसरे स्थान के वनों की कटाई में योगदान कर सकती है।',vocabulary:[['affluent','समृद्ध'],['consumer demand','उपभोक्ता माँग'],['mahogany','महोगनी'],['clearance','सफाई / कटाई'],['consumption','खपत']],exam:'The chapter deliberately presents poverty-driven and consumption-driven pressures together.',think:'Why is it important to discuss both poverty and affluence when explaining deforestation?'},
    {title:'Part 10 — Consequences of deforestation and the final choice',flow:'The lesson describes forest loss as a cause of greenhouse effects, irreversible species loss, landslides, soil erosion, siltation, droughts and extreme weather. It ends by contrasting passive hope with responsible action: people can continue damaging forests or work to hold back and reverse deforestation.',explanation:'पाठ वनों की हानि को ग्रीनहाउस प्रभाव, प्रजातियों की अपरिवर्तनीय हानि, भूस्खलन, मृदा अपरदन, गाद जमने, सूखे और चरम मौसम से जोड़ता है। अंत में केवल उम्मीद करने के बजाय जिम्मेदार कार्रवाई का विकल्प रखा गया है—वनों की क्षति को रोकना और उसे उलटने का प्रयास करना।',vocabulary:[['irreversible','जिसे वापस पहले जैसा न किया जा सके'],['landslide','भूस्खलन'],['soil erosion','मृदा अपरदन'],['siltation','गाद का जमाव'],['reverse','स्थिति को सुधारना / उलटना']],exam:'The conclusion combines a warning about consequences with a call for responsible action.',think:'Why does the final paragraph make human choice central to the environmental message?'}
`
  ]
};

for (const [file, replacements] of Object.entries(files)) {
  const text = fs.readFileSync(file, 'utf8');
  const sectionPattern = /sections:\[\n[\s\S]*?\n  \],\n  glossary:/;
  if (!sectionPattern.test(text)) throw new Error(`Phase 2: section block not found in ${file}`);
  const next = text.replace(sectionPattern, `sections:[\n${replacements.join(',\n')}\n  ],\n  glossary:`)
    .replace(/8 guided parts/g, '10 guided parts');
  fs.writeFileSync(file, next);
}

const ch2 = fs.readFileSync('src/english/EnglishPanoramaChapter2.jsx','utf8');
if (!ch2.includes('<span>10 Guided Parts</span>')) {
  fs.writeFileSync('src/english/EnglishPanoramaChapter2.jsx', ch2.replace('<span>Complete Chapter Study</span>', '<span>10 Guided Parts</span><span>Complete Chapter Study</span>'));
}

console.log('Phase 2 pedagogy migration applied: Chapters 2–4 now have 10 guided reading parts each, with the existing assessment/UI architecture preserved.');
