import fs from 'node:fs';
const file='src/english/EnglishPanoramaChapter4.jsx';
const text=fs.readFileSync(file,'utf8');
const sections=`    {title:'Part 1 — Population in earlier human history',flow:'For most of human existence, births were only slightly higher than deaths, so population increased slowly. Better nutrition and sanitation changed this balance, helping people live longer and allowing more people to reach reproductive age.',explanation:'मानव इतिहास के अधिकांश समय में जन्मों की संख्या मृत्यु से केवल थोड़ी अधिक थी, इसलिए जनसंख्या धीरे बढ़ती थी। पोषण और स्वच्छता में सुधार से लोग अधिक समय तक जीने लगे और अधिक लोग प्रजनन आयु तक पहुँचने लगे।',vocabulary:[['existence','अस्तित्व'],['nutrition','पोषण'],['sanitation','स्वच्छता'],['reproductive age','प्रजनन आयु'],['balance','संतुलन']],exam:'Learn the cause chain: improved nutrition and sanitation → longer life → more people reaching reproductive age.',think:'How can improvements in living conditions change population growth?'},
    {title:'Part 2 — Why rapid growth creates an ecological limit',flow:'More people may appear beneficial because people can create inventions and profit, but the lesson argues that the world is finite. From an ecological point of view, unlimited population growth puts increasing pressure on food, resources and the environment.',explanation:'अधिक लोगों की संख्या लाभदायक लग सकती है क्योंकि मनुष्य आविष्कार और आर्थिक लाभ ला सकते हैं, लेकिन पृथ्वी सीमित है। पाठ के अनुसार असीमित जनसंख्या वृद्धि भोजन, संसाधनों और पर्यावरण पर बढ़ता दबाव डालती है।',vocabulary:[['finite','सीमित'],['ecological','पारिस्थितिक'],['overpopulated','अधिक जनसंख्या वाला'],['resource','संसाधन'],['pressure','दबाव']],exam:'Distinguish the apparent benefits of more people from the ecological limits described by the author.',think:'Why does a finite planet make unlimited growth difficult?'},
    {title:'Part 3 — Food, land and crowding pressures',flow:'As population rises, the need for food, land and other resources rises too. Towns and countries become more crowded, and pressure to clear forests grows. The chapter presents population growth as a factor that can intensify several connected problems.',explanation:'जनसंख्या बढ़ने पर भोजन, भूमि और अन्य संसाधनों की आवश्यकता भी बढ़ती है। शहर और देश अधिक भीड़भाड़ वाले हो जाते हैं और वनों को साफ करने का दबाव बढ़ता है। पाठ जनसंख्या वृद्धि को कई जुड़ी समस्याओं को गंभीर बनाने वाले कारक के रूप में प्रस्तुत करता है।',vocabulary:[['crowded','भीड़भाड़ वाला'],['deforestation','वनों की कटाई'],['density','घनत्व'],['demand','माँग'],['intensify','और गंभीर करना']],exam:'Connect population growth with greater food demand, resource use and forest pressure.',think:'How can one increase in population create several different pressures at once?'},
    {title:'Part 4 — Pollution and quality of life',flow:'The lesson connects population density with pollution of rivers, lakes, air, water and soil. It also says that quality of life can fall when crowding and environmental stress become severe, and it mentions possible social problems such as crime, ethnic conflict and warfare.',explanation:'पाठ जनसंख्या घनत्व को नदियों, झीलों, वायु, जल और मिट्टी के प्रदूषण से जोड़ता है। भीड़भाड़ और पर्यावरणीय दबाव बढ़ने पर जीवन की गुणवत्ता कम हो सकती है। पाठ अपराध, जातीय संघर्ष और युद्ध जैसी संभावित सामाजिक समस्याओं का भी उल्लेख करता है।',vocabulary:[['pollution','प्रदूषण'],['quality of life','जीवन की गुणवत्ता'],['ethnic','जातीय'],['conflict','संघर्ष'],['warfare','युद्ध']],exam:'Remember both environmental and social effects of very high population density.',think:'Why does the lesson treat population density as more than just a number?'},
    {title:'Part 5 — Air pollution and public health',flow:'The American example in the lesson shows how pollution can worsen respiratory illness and asthma. The point is not only environmental damage: polluted surroundings can directly affect human health. The author uses this link to strengthen the argument for controlling harmful pressures.',explanation:'पाठ में दिए गए अमेरिकी उदाहरण से पता चलता है कि प्रदूषण श्वसन संबंधी रोगों और अस्थमा को बढ़ा सकता है। समस्या केवल पर्यावरण की नहीं है; प्रदूषित वातावरण सीधे मानव स्वास्थ्य को प्रभावित कर सकता है। लेखक इस संबंध से हानिकारक दबावों को नियंत्रित करने के पक्ष को मजबूत करता है।',vocabulary:[['respiratory','श्वसन संबंधी'],['asthma','अस्थमा'],['aggravate','और गंभीर करना'],['incidence','प्रचलन / घटना'],['public health','जनस्वास्थ्य']],exam:'Use the pollution example to connect environmental quality with human health.',think:'Why is an environmental problem also a public-health problem?'},
    {title:'Part 6 — Global environmental changes',flow:'The essay expands the discussion to desertification, depletion of non-renewable resources, acid rain, loss of wild species, ozone-layer depletion and the greenhouse effect. A United Nations document cited by the lesson links population size and growth rates with environmental change.',explanation:'निबंध पर्यावरणीय समस्याओं की सूची को मरुस्थलीकरण, अनवीकरणीय संसाधनों की कमी, अम्लीय वर्षा, वन्य प्रजातियों की हानि, ओजोन परत के क्षय और ग्रीनहाउस प्रभाव तक बढ़ाता है। पाठ में उद्धृत संयुक्त राष्ट्र दस्तावेज जनसंख्या के आकार और वृद्धि दर को पर्यावरणीय परिवर्तन से जोड़ता है।',vocabulary:[['desertification','मरुस्थलीकरण'],['non-renewable','अनवीकरणीय'],['acid rain','अम्लीय वर्षा'],['species','प्रजाति'],['greenhouse effect','ग्रीनहाउस प्रभाव']],exam:'Be ready to name several global environmental problems explicitly listed in the chapter.',think:'Why does the author move from local pressure to global environmental change?'},
    {title:'Part 7 — Population control and social factors',flow:'The chapter says restoring the biosphere depends partly on slowing population growth. Germany, Sweden, China, Thailand and Egypt are given as examples. Education, literacy, media campaigns, family planning and opportunities for women are among the factors listed to explain slower growth.',explanation:'अध्याय के अनुसार जीवमंडल को सँभालने के लिए जनसंख्या वृद्धि को धीमा करना एक महत्त्वपूर्ण कदम है। जर्मनी, स्वीडन, चीन, थाईलैंड और मिस्र उदाहरण के रूप में दिए गए हैं। शिक्षा, साक्षरता, मीडिया अभियान, परिवार नियोजन तथा महिलाओं के अवसर जैसे कारणों का उल्लेख किया गया है।',vocabulary:[['biosphere','जीवमंडल'],['literacy','साक्षरता'],['campaign','अभियान'],['family planning','परिवार नियोजन'],['opportunity','अवसर']],exam:'Memorise both the country examples and the social factors listed in the source.',think:'How can education and women’s opportunities influence population trends?'},
    {title:'Part 8 — Poverty and forest clearance',flow:'The author explains that poverty and related conditions can force people in poorer countries to clear, burn or cultivate tropical forests. Nepal is used as an example of pressure on trees and forests for fuel and livelihood needs.',explanation:'लेखक बताते हैं कि गरीबी और उससे जुड़ी परिस्थितियाँ गरीब देशों के लोगों को उष्णकटिबंधीय वनों को काटने, जलाने या खेती के लिए उपयोग करने पर मजबूर कर सकती हैं। नेपाल का उदाहरण ईंधन और जीवन-यापन के लिए पेड़ों पर बढ़ते दबाव को दिखाता है।',vocabulary:[['tropical','उष्णकटिबंधीय'],['clear','वन हटाना'],['cultivate','खेती करना'],['fuel','ईंधन'],['livelihood','जीवन-यापन']],exam:'Explain how poverty can create direct pressure on tropical forests.',think:'Why might people clear forests even when forest loss is harmful in the long term?'},
    {title:'Part 9 — Affluence and consumer demand',flow:'Deforestation is not driven only by poverty. The lesson also points to affluent consumers and demand for products such as hamburgers, mahogany furniture, newspapers and paper. Consumption in one place can therefore contribute to forest clearance elsewhere.',explanation:'वनों की कटाई केवल गरीबी के कारण नहीं होती। पाठ समृद्ध उपभोक्ताओं की माँग और हैमबर्गर, महोगनी फर्नीचर, समाचारपत्र तथा कागज जैसे उत्पादों का उदाहरण भी देता है। इसलिए एक स्थान की खपत दूसरे स्थान के वनों की कटाई में योगदान कर सकती है।',vocabulary:[['affluent','समृद्ध'],['consumer demand','उपभोक्ता माँग'],['mahogany','महोगनी'],['clearance','सफाई / कटाई'],['consumption','खपत']],exam:'The chapter deliberately presents poverty-driven and consumption-driven pressures together.',think:'Why is it important to discuss both poverty and affluence when explaining deforestation?'},
    {title:'Part 10 — Consequences of deforestation and the final choice',flow:'The lesson describes forest loss as a cause of greenhouse effects, irreversible species loss, landslides, soil erosion, siltation, droughts and extreme weather. It ends by contrasting passive hope with responsible action: people can continue damaging forests or work to hold back and reverse deforestation.',explanation:'पाठ वनों की हानि को ग्रीनहाउस प्रभाव, प्रजातियों की अपरिवर्तनीय हानि, भूस्खलन, मृदा अपरदन, गाद जमने, सूखे और चरम मौसम से जोड़ता है। अंत में केवल उम्मीद करने के बजाय जिम्मेदार कार्रवाई का विकल्प रखा गया है—वनों की क्षति को रोकना और उसे उलटने का प्रयास करना।',vocabulary:[['irreversible','जिसे वापस पहले जैसा न किया जा सके'],['landslide','भूस्खलन'],['soil erosion','मृदा अपरदन'],['siltation','गाद का जमाव'],['reverse','स्थिति को सुधारना / उलटना']],exam:'The conclusion combines a warning about consequences with a call for responsible action.',think:'Why does the final paragraph make human choice central to the environmental message?'}
  ]`;
const re=/sections:\[\n[\s\S]*?\n  \],\n  glossary:/;
if(!re.test(text)) throw new Error('Chapter 4 sections block not found');
const next=text.replace(re,`sections:[\n${sections}\n  ],\n  glossary:`).replace(/8 guided parts/g,'10 guided parts');
fs.writeFileSync(file,next);
console.log('Chapter 4 migrated to 10 guided parts.');
