import fs from'node:fs';import path from'node:path';const root=process.cwd();const read=p=>fs.readFileSync(path.join(root,p),'utf8');const ok=(v,m)=>{if(!v)throw new Error(`English poetry 8 QA: ${m}`)};
const files=Array.from({length:14},(_,i)=>`src/english/EnglishPanoramaPoem8Source${i+1}.js`).concat(['src/english/EnglishPanoramaPoem8Source3b.js']);for(const f of files)ok(fs.existsSync(path.join(root,f)),`missing ${f}`);
const content=read('src/english/EnglishPanoramaPoem8Content.js'),ui=read('src/english/EnglishPanoramaPoem8.jsx'),nav=read('src/english/EnglishSubjectSection.jsx'),shell=read('src/AppWithChapter5.jsx');
const expected=['He will have to learn, I know,','that all men are not just,','all men are not true.','for every scoundrel there is a hero;','that a dollar earned is of far more value than five','Teach him to learn to lose...','the wonder of books...','it is far more honourable to fail','Teach him to have faith','they are wrong...','the strength not to follow the crowd when everyone is getting on','all he hears on a screen truth,','on his heart and soul.','to a howling mob','of fire makes fine steel.','to have sublime faith in himself,','sublime faith in mankind.','This is a big order,','but see what you can do...','He is such a fine fellow...','my son!'];
for(const x of expected)ok(content.includes(x)||ui.includes(x),`source line missing: ${x}`);
const lengths={1:10,2:10,3:5,4:4,5:4,6:4,7:4,8:4,9:4,10:4,11:4,12:4,13:4,14:3};for(const [n,len] of Object.entries(lengths)){const p=n==='3'?read('src/english/EnglishPanoramaPoem8Source3.js'):read(`src/english/EnglishPanoramaPoem8Source${n}.js`);ok((p.match(/,/g)||[]).length>=len,`source chunk ${n} looks incomplete`)}
const practice=[read('src/english/EnglishPanoramaPoem8Practice1.js'),read('src/english/EnglishPanoramaPoem8Practice2.js')].join('');const challenge=[1,2,3,4,5].map(n=>read(`src/english/EnglishPanoramaPoem8Challenge${n}.js`)).join('');ok((practice.match(/\['/g)||[]).length===15,'Practice bank must contain 15 questions');ok((challenge.match(/\['/g)||[]).length===25,'Challenge bank must contain 25 questions');ok(ui.includes('const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)]'),'Final Test derivation missing');
ok(ui.includes('COMPLETE SOURCE TEXT'),'complete source section missing');ok(ui.includes('poem8SourceLines.map'),'source line rendering missing');ok(ui.includes('15 Practice • 25 Challenge • 20-question Final Test'),'assessment contract missing');ok(ui.includes('function Learn'),'Learn mode missing');ok(ui.includes('onBack={()=>setMode(\'\')}'),'Back to Learn behavior missing');ok(nav.includes('poetry>=1&&poetry<=8'),'Poetry 8 navigation range missing');ok(nav.includes('Abraham Lincoln’s Letter to His Son’s Teacher'),'Poetry 8 registry entry missing');ok(shell.includes("panoramaPoetry8")&&shell.includes('return 24')&&shell.includes('chapter===24'),'Poetry 8 runtime route missing');
console.log('English poetry Chapter 8 QA passed: complete source-text chunks, 15 Practice, 25 Challenge, derived 20 Final Test, continuous Learn UI, navigation and runtime route.');
