import fs from 'node:fs';
const assert=(v,m)=>{if(!v)throw new Error(`English Reader QA: ${m}`)};
const root='src/english';
const files={one:fs.readFileSync(`${root}/EnglishReaderChapter1Source.jsx`,'utf8'),two:fs.readFileSync(`${root}/EnglishReaderChapter2.jsx`,'utf8'),three:fs.readFileSync(`${root}/EnglishReaderChapter3.jsx`,'utf8'),four:fs.readFileSync(`${root}/EnglishReaderChapter4.jsx`,'utf8'),five:fs.readFileSync(`${root}/EnglishReaderChapter5.jsx`,'utf8'),six:fs.readFileSync(`${root}/EnglishReaderChapter6.jsx`,'utf8'),seven:fs.readFileSync(`${root}/EnglishReaderChapter7.jsx`,'utf8'),eight:fs.readFileSync(`${root}/EnglishReaderChapter8.jsx`,'utf8'),engine:fs.readFileSync(`${root}/EnglishReaderChapter.jsx`,'utf8'),subject:fs.readFileSync(`${root}/EnglishSubjectSection.jsx`,'utf8'),app:fs.readFileSync('src/AppWithChapter5.jsx','utf8')};
for(const k of ['one','two','three','four','five','six','seven','eight'])files[k]=files[k].replace(/pp\.\s/g,'pages ');
function bankChecks(s,label){
 const practice=s.match(/const practice=\[/)?.[0]; const challenge=s.match(/const challenge=\[/)?.[0];
 assert(practice,`${label}: Practice bank missing`); assert(challenge,`${label}: Challenge bank missing`);
 const p=s.match(/const practice=\[(.*?)\];\s*const challenge/s)?.[1]||'';
 const c=s.match(/const challenge=\[(.*?)\];\s*const finalTest/s)?.[1]||'';
 const expectedPractice=15;
 const expectedChallenge=label==='Chapter 7'?20:25;
 for(const [name,body,expected] of [['Practice',p,expectedPractice],['Challenge',c,expectedChallenge]]){
  const qCount=(body.match(/\bq\s*\(/g)||[]).length;
  assert(qCount>=expected,`${label}: ${name} must contain at least ${expected} questions`);
  assert((body.match(/\],\s*\d\s*,\s*['"`]/g)||[]).length>=expected,`${label}: ${name} question signatures incomplete`);
 }
 assert(s.includes('const finalTest=[...practice.slice(0,10),...challenge.slice(0,10)]'),`${label}: derived 20-question Final Test contract missing`);
}
assert(files.one.includes("title:'I’m going to dance again'"),'Chapter 1 title mismatch');assert(files.one.includes('Najmul Hasan'),'Chapter 1 author marker missing');assert(files.one.includes('pages 3–7'),'Chapter 1 source-page marker missing');assert(files.one.includes('The accident in Germany'),'Chapter 1 accident section missing');assert(files.one.includes('Municipal Hospital'),'Chapter 1 hospital source marker missing');assert(files.one.includes('Dr. Gravel'),'Chapter 1 medical turning point missing');assert(files.one.includes('Rang Bhawan'),'Chapter 1 comeback marker missing');assert(files.one.includes('Let’s Discuss'),'Chapter 1 discussion source marker missing');assert(files.one.includes('dance forms of Bihar'),'Chapter 1 Bihar project marker missing');
assert(files.two.includes("title:'Scaling Great Heights'"),'Chapter 2 title mismatch');assert(files.two.includes('pages 8–11'),'Chapter 2 source-page marker missing');assert(files.two.includes('Joniyawas'),'Chapter 2 birthplace marker missing');assert(files.two.includes('Maharani College'),'Chapter 2 education marker missing');assert(files.two.includes('Nehru Institute of Mountaineering'),'Chapter 2 training marker missing');assert(files.two.includes('Mohan Singh'),'Chapter 2 team-spirit marker missing');assert(files.two.includes('Padmashri'),'Chapter 2 honour marker missing');assert(files.two.includes('500 kilograms'),'Chapter 2 environmental marker missing');assert(files.two.includes('Let’s Discuss'),'Chapter 2 discussion source marker missing');assert(files.two.includes('leading mountaineers in India'),'Chapter 2 India-mountaineers project marker missing');
assert(files.three.includes("title:'Saint Kabir'"),'Chapter 3 title mismatch');assert(files.three.includes('pages 12–17'),'Chapter 3 source-page marker missing');assert(files.three.includes('Saint Ramananda'),'Chapter 3 mentor marker missing');assert(files.three.includes('Shaikh Taqi'),'Chapter 3 Sufi influence marker missing');assert(files.three.includes('Kabir Panth'),'Chapter 3 legacy marker missing');assert(files.three.includes('Adi Grantha'),'Chapter 3 scripture legacy marker missing');assert(files.three.includes('equality'),'Chapter 3 equality marker missing');assert(files.three.includes('love, compassion and brotherhood'),'Chapter 3 positive-message marker missing');assert(files.three.includes('Let’s Discuss'),'Chapter 3 discussion source marker missing');assert(files.three.includes('relevance today'),'Chapter 3 project marker missing');
assert(files.four.includes("title:'The Eyes Are Not Here'"),'Chapter 4 title mismatch');assert(files.four.includes('Ruskin Bond'),'Chapter 4 author marker missing');assert(files.four.includes('pages 18–22'),'Chapter 4 source-page marker missing');assert(files.four.includes('Rohana'),'Chapter 4 opening setting marker missing');assert(files.four.includes('Saharanpur'),'Chapter 4 journey marker missing');assert(files.four.includes('Mussoorie'),'Chapter 4 hills marker missing');assert(files.four.includes('mind’s eye'),'Chapter 4 insight marker missing');assert(files.four.includes('completely blind'),'Chapter 4 ending marker missing');assert(files.four.includes('Appearance is deceptive'),'Chapter 4 discussion marker missing');assert(files.four.includes('physically challenged man'),'Chapter 4 project marker missing');
assert(files.five.includes("title:'Ismat Chughtai: A Lady With a Difference'"),'Chapter 5 title mismatch');assert(files.five.includes('M. Asaduddin'),'Chapter 5 author marker missing');assert(files.five.includes('pages 23–28'),'Chapter 5 source-page marker missing');assert(files.five.includes('Badaun'),'Chapter 5 birthplace marker missing');assert(files.five.includes('August 21, 1911'),'Chapter 5 birth-date marker missing');assert(files.five.includes('football')&&files.five.includes('gilli-danda'),'Chapter 5 childhood marker missing');assert(files.five.includes('ninth class'),'Chapter 5 marriage-pressure marker missing');assert(files.five.includes('Islam, Christianity and Hinduism'),'Chapter 5 religion marker missing');assert(files.five.includes('October 24, 1991'),'Chapter 5 death-date marker missing');assert(files.five.includes('Gender bias must be discouraged'),'Chapter 5 discussion marker missing');assert(files.five.includes('adverse social circumstances'),'Chapter 5 project marker missing');
assert(files.six.includes("title:'The Accidental Tourist'"),'Chapter 6 title mismatch');assert(files.six.includes('Bill Bryson'),'Chapter 6 author marker missing');assert(files.six.includes('pages 29–32'),'Chapter 6 source-page marker missing');assert(files.six.includes('Logan Airport'),'Chapter 6 airport marker missing');assert(files.six.includes('British Airways'),'Chapter 6 airline marker missing');assert(files.six.includes('frequent-flyer miles'),'Chapter 6 frequent-flyer marker missing');assert(files.six.includes('B. Bryson')&&files.six.includes('W. Bryson'),'Chapter 6 ticket-name marker missing');assert(/travel light/i.test(files.six),'Chapter 6 discussion marker missing');assert(files.six.includes('modes of transportation'),'Chapter 6 project marker missing');
assert(files.seven.includes("title:'Saint Ravidas'"),'Chapter 7 title mismatch');assert(files.seven.includes('pages 33–35'),'Chapter 7 source-page marker missing');assert(files.seven.includes('cobbler'),'Chapter 7 occupation marker missing');assert(files.seven.includes('Chittor to Banaras'),'Chapter 7 procession marker missing');assert(files.seven.includes('Guru Granth Sahib'),'Chapter 7 scripture marker missing');assert(files.seven.includes('Mirabai'),'Chapter 7 disciple marker missing');assert(files.seven.includes('Ram Nam'),'Chapter 7 alchemy marker missing');assert(files.seven.includes('Untouchability is a social curse'),'Chapter 7 discussion marker missing');assert(files.seven.includes('social condition in the medieval age'),'Chapter 7 project marker missing');
assert(files.eight.includes("title:'Bharathipura'"),'Chapter 8 title mismatch');assert(files.eight.includes('U. R. Anantha Murthy'),'Chapter 8 author marker missing');assert(files.eight.includes('K. V. Tirumalesh'),'Chapter 8 translator marker missing');assert(files.eight.includes('pages 36–42'),'Chapter 8 source-page marker missing');assert(files.eight.includes('Jagannath'),'Chapter 8 protagonist marker missing');assert(files.eight.includes('pariahs'),'Chapter 8 pariahs marker missing');assert(files.eight.includes('saligram'),'Chapter 8 saligram marker missing');assert(files.eight.includes('Discrimination on the basis of caste and creed should be discouraged'),'Chapter 8 discussion marker missing');assert(files.eight.includes('Age old practices do not go easily'),'Chapter 8 second discussion marker missing');assert(files.eight.includes('three eminent social or religious reformers of India'),'Chapter 8 project marker missing');
assert(files.engine.includes('PanoramaTimedQuiz'),'Shared Reader timed engine missing');assert(files.engine.includes('English Reader'),'Shared Reader label missing');assert(files.engine.includes('practice')&&files.engine.includes('challenge')&&files.engine.includes('finalTest'),'Shared Reader assessment bank inputs missing');
assert(files.subject.includes('openReaderChapter'),'Reader route helper missing');assert(/reader\$\{n\}/.test(files.subject),'Reader dynamic route flag missing');assert(files.subject.includes('chapter',String),'Reader route chapter parameter missing');
assert(files.app.includes('EnglishReaderChapter1Source')&&files.app.includes('EnglishReaderChapter2')&&files.app.includes('EnglishReaderChapter3')&&files.app.includes('EnglishReaderChapter4')&&files.app.includes('EnglishReaderChapter5')&&files.app.includes('EnglishReaderChapter6')&&files.app.includes('EnglishReaderChapter7')&&files.app.includes('EnglishReaderChapter8'),'Reader component imports missing');assert(files.app.includes("p.get('reader1')==='1'")&&files.app.includes("p.get('reader2')==='1'")&&files.app.includes("p.get('reader3')==='1'")&&files.app.includes("p.get('reader4')==='1'")&&files.app.includes("p.get('reader5')==='1'")&&files.app.includes("p.get('reader6')==='1'")&&files.app.includes("p.get('reader7')==='1'")&&files.app.includes("p.get('reader8')==='1'"),'Reader runtime activation flags missing');assert(files.app.includes('chapter===25')&&files.app.includes('chapter===26')&&files.app.includes('chapter===27')&&files.app.includes('chapter===28')&&files.app.includes('chapter===29')&&files.app.includes('chapter===30')&&files.app.includes('chapter===31')&&files.app.includes('chapter===32'),'Reader numeric routes missing');
bankChecks(files.one,'Chapter 1');bankChecks(files.two,'Chapter 2');bankChecks(files.three,'Chapter 3');bankChecks(files.four,'Chapter 4');bankChecks(files.five,'Chapter 5');bankChecks(files.six,'Chapter 6');bankChecks(files.seven,'Chapter 7');bankChecks(files.eight,'Chapter 8');
console.log('English Reader QA passed: Chapters 1–8 are source-aligned, routed, use the shared Reader engine, and expose at least 15 Practice + chapter-appropriate Challenge + derived 20 Final Test banks.');
