import React,{useMemo,useState} from 'react';
import {SANSKRIT_GRAMMAR_UNITS} from './sanskritGrammarRuntime.mjs';
import {SANSKRIT_GRAMMAR_STUDY_CONTENT} from './sanskritGrammarStudyContent.mjs';
import './sanskrit-grammar.css';

const getDetail=(unit)=>SANSKRIT_GRAMMAR_STUDY_CONTENT[unit.id]||Object.values(SANSKRIT_GRAMMAR_STUDY_CONTENT).find(x=>unit.title.startsWith(x.title.split(' — ')[0]))||null;

function ActualContent({unit}){const d=getDetail(unit);if(!d)return null;return <section className="sg-actual-content"><div className="sg-section-title"><div><span className="sanskrit-kicker">Actual Study Content</span><h3>{d.title}</h3></div><span>{d.lessons.length} detailed lessons</span></div>{d.overview&&<article className="sg-deep-card sg-overview-card"><h4>अध्याय का मूल विचार</h4><p>{d.overview}</p></article>}<div className="sg-lesson-stack">{d.lessons.map((lesson,i)=><article className="sg-deep-card sg-lesson-card" key={`${unit.id}-lesson-${i}`}><div className="sg-lesson-index">{String(i+1).padStart(2,'0')}</div><div><h4>{lesson.title}</h4><p>{lesson.body}</p>{lesson.examples&&<div className="sg-example-block"><b>उदाहरण</b>{lesson.examples.map((x,j)=><code key={j}>{x}</code>)}</div>}{lesson.table&&<div className="sg-table-wrap"><table><tbody>{lesson.table.map((row,r)=><tr key={r}>{row.map((cell,c)=>r===0?<th key={c}>{cell}</th>:<td key={c}>{cell}</td>)}</tr>)}</tbody></table></div>}</div></article>)}</div></section>}

function UnitStudy({unit}){return <div className="sg-deep-grid"><article className="sg-deep-card"><h4>क्या पढ़ना है</h4><ul>{unit.subtopics.map(x=><li key={x}>{x}</li>)}</ul></article><article className="sg-deep-card"><h4>हल करने की विधि</h4><ol>{unit.method.map(x=><li key={x}>{x}</li>)}</ol></article><article className="sg-deep-card sg-warning-card"><h4>सामान्य गलतियाँ</h4><ul>{unit.mistakes.map(x=><li key={x}>{x}</li>)}</ul></article><article className="sg-deep-card"><h4>Board Exam Tips</h4><ul>{unit.tips.map(x=><li key={x}>{x}</li>)}</ul></article></div>}

function TopicQuiz({unit,onFinish}){const[picked,setPicked]=useState({}),[checked,setChecked]=useState(false);const score=useMemo(()=>unit.questions.reduce((n,q,i)=>n+(picked[i]===q.answer?1:0),0),[picked,unit.questions]);const answered=Object.keys(picked).length;const submit=()=>{setChecked(true);onFinish(unit.id)};return <div className="sg-topic-panel"><div className="sg-panel-head"><div><span>{unit.tag}</span><h3>{unit.title}</h3></div><strong>{checked?`${score}/${unit.questions.length}`:`${answered}/${unit.questions.length}`}</strong></div><div className="sg-rule-card"><b>Core Rule</b><p>{unit.rule}</p></div><p className="sg-quiz-note"><b>अब MCQ में लागू करें:</b> ऊपर का वास्तविक अध्ययन-सामग्री पढ़कर ही प्रश्न हल करें।</p><div className="sg-question-list">{unit.questions.map((q,i)=><article className="sg-question" key={`${unit.id}-${i}`}><div className="sg-q-meta"><span>{q.level}</span><small>प्रश्न {i+1}/15</small></div><h4>{q.q}</h4><div className="sg-options">{q.options.map((o,j)=><button type="button" key={o} disabled={checked} className={`sg-option ${picked[i]===j?'picked':''} ${checked&&j===q.answer?'correct':''} ${checked&&picked[i]===j&&j!==q.answer?'wrong':''}`} onClick={()=>setPicked(v=>({...v,[i]:j}))}>{String.fromCharCode(65+j)}. {o}</button>)}</div>{checked&&<p className="sg-explain"><b>व्याख्या:</b> {q.explain}</p>}</article>)}</div><div className="sg-actions"><button type="button" className="primary-btn pressable" disabled={answered!==15||checked} onClick={submit}>{checked?'अभ्यास पूरा ✓':'15 उत्तर जाँचें'}</button>{checked&&<button type="button" className="secondary-btn pressable" onClick={()=>{setPicked({});setChecked(false)}}>फिर से हल करें</button>}</div>{checked&&<div className="sg-result"><strong>{score>=13?'उत्कृष्ट तैयारी':score>=10?'अच्छी तैयारी':'वास्तविक पाठ और उदाहरण दोहराएँ'}</strong><span>स्कोर: {score}/15 · {Math.round(score/15*100)}%</span></div>}</div>}

function Coverage({active,onPick}){return <section className="sg-syllabus"><div className="sg-section-title"><div><span className="sanskrit-kicker">Syllabus Map</span><h3>कक्षा 9 संस्कृत — व्याकरण एवं भाषा-प्रयोग</h3></div><span>11 units · 165 MCQs</span></div><div className="sg-coverage-grid">{SANSKRIT_GRAMMAR_UNITS.map((u,i)=><button type="button" key={u.id} className={active===u.id?'active':''} onClick={()=>onPick(u.id)}><b>{String(i+1).padStart(2,'0')}</b><span>{u.title}</span><small>15 MCQs</small></button>)}</div></section>}

export function SanskritGrammarLab(){const[active,setActive]=useState(SANSKRIT_GRAMMAR_UNITS[0].id),[completed,setCompleted]=useState(()=>new Set());const unit=SANSKRIT_GRAMMAR_UNITS.find(x=>x.id===active)||SANSKRIT_GRAMMAR_UNITS[0];const completedCount=completed.size;return <section className="sanskrit-grammar-lab"><div className="sg-hero"><div><span className="sanskrit-kicker">Grammar Lab · Class IX · BSEB/SCERT</span><h2>संस्कृत व्याकरण प्रयोगशाला</h2><p>शब्दरूप से लेकर धातुरूप, लकार, कारक, उपसर्ग, प्रत्यय, सन्धि, समास, अव्यय, संख्या और भाषा-प्रयोग तक syllabus-mapped अध्ययन एवं अभ्यास।</p></div><div className="sg-hero-stat"><b>{completedCount}/{SANSKRIT_GRAMMAR_UNITS.length}</b><span>units complete</span></div></div><div className="sg-progress"><div><strong>कुल प्रगति</strong><span>{completedCount===SANSKRIT_GRAMMAR_UNITS.length?'Grammar syllabus complete ✓':`${completedCount} units mastered`}</span></div><div className="sg-progress-track"><span style={{width:`${completedCount/SANSKRIT_GRAMMAR_UNITS.length*100}%`}} /></div></div><Coverage active={active} onPick={setActive}/><div className="sg-unit-head"><span className="sanskrit-kicker">Unit {SANSKRIT_GRAMMAR_UNITS.findIndex(x=>x.id===active)+1}</span><h3>{unit.title}</h3><p>{unit.intro}</p></div><ActualContent unit={unit}/><UnitStudy unit={unit}/><TopicQuiz unit={unit} onFinish={(id)=>setCompleted(v=>new Set([...v,id]))}/><div className="sg-final-note"><strong>Study → Practice</strong><span>मूल पाठ → नियम → रूप/उदाहरण → वाक्य-प्रयोग → MCQ → व्याख्या → पुनरावृत्ति</span></div></section>}
