import React,{useMemo,useState} from 'react';
import {chapter9Practice} from './chapter9Practice';
const challenge=[
 {q:'एक समान्तर चतुर्भुज का क्षेत्रफल 96 cm² है। उसी ऊँचाई पर बने दूसरे का आधार पहले का 3/2 है। दूसरे का क्षेत्रफल कितना होगा?',options:['64 cm²','96 cm²','144 cm²','192 cm²'],answer:2,explain:'समान ऊँचाई पर क्षेत्रफल आधार के समानुपाती है। 96×3/2=144 cm²।'},
 {q:'दो त्रिभुजों की ऊँचाई समान है और उनके आधार 7 cm तथा 11 cm हैं। यदि पहले का क्षेत्रफल 35 cm² है, तो दूसरे का क्षेत्रफल कितना होगा?',options:['44 cm²','55 cm²','70 cm²','77 cm²'],answer:1,explain:'समान ऊँचाई पर क्षेत्रफल आधार के समानुपाती है। 35×11/7=55 cm²।'},
 {q:'एक त्रिभुज और समान्तर चतुर्भुज का आधार और ऊँचाई समान हैं। यदि त्रिभुज का क्षेत्रफल 42 cm² है, तो समान्तर चतुर्भुज का क्षेत्रफल कितना होगा?',options:['21 cm²','42 cm²','84 cm²','126 cm²'],answer:2,explain:'समान आधार और ऊँचाई पर त्रिभुज का क्षेत्रफल समान्तर चतुर्भुज का आधा होता है। इसलिए 84 cm²।'},
 {q:'एक समान्तर चतुर्भुज का क्षेत्रफल 150 cm² है। आधार 25% बढ़ाया और ऊँचाई 20% घटाई गई। नया क्षेत्रफल कितना होगा?',options:['120 cm²','150 cm²','180 cm²','187.5 cm²'],answer:1,explain:'नया क्षेत्रफल = 150×1.25×0.80 = 150 cm²।'},
 {q:'एक समान्तर चतुर्भुज का क्षेत्रफल 180 cm² है। एक आधार 15 cm और उसकी लंबवत ऊँचाई 12 cm है। दूसरी भुजा को आधार लेने पर ऊँचाई 9 cm है। दूसरी भुजा कितनी होगी?',options:['15 cm','18 cm','20 cm','24 cm'],answer:2,explain:'दूसरी आधार = क्षेत्रफल÷नई ऊँचाई = 180÷9 = 20 cm।'}
];
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function AreaEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const questions=useMemo(()=>isTest?shuffle(chapter9Practice).slice(0,15):mode==='challenge'?challenge:chapter9Practice,[mode,isTest]);
 const[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index],points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points)}}};
 const next=()=>{if(selected===null||!current)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">क्षेत्रफल • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0)}}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">गणित • क्षेत्रफल</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className="question-actions"><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>
}
