export const chapter3Practice = [
 {q:'निर्देशांक (3,5) में x-coordinate क्या है?',options:['3','5','8','2'],answer:0,explain:'Ordered pair (x,y) में पहला मान x-coordinate होता है, इसलिए x = 3।'},
 {q:'निर्देशांक (−2,4) में y-coordinate क्या है?',options:['−2','2','4','−4'],answer:2,explain:'(x,y) में दूसरा मान y-coordinate है, इसलिए y = 4।'},
 {q:'मूलबिंदु के निर्देशांक क्या हैं?',options:['(1,0)','(0,1)','(0,0)','(1,1)'],answer:2,explain:'x-axis और y-axis का प्रतिच्छेदन मूलबिंदु O(0,0) है।'},
 {q:'x-coordinate 0 होने पर बिंदु कहाँ होगा?',options:['x-axis','y-axis','I quadrant','origin ही'],answer:1,explain:'(0,y) के सभी बिंदु y-axis पर होते हैं।'},
 {q:'y-coordinate 0 होने पर बिंदु कहाँ होगा?',options:['x-axis','y-axis','II quadrant','origin ही'],answer:0,explain:'(x,0) के सभी बिंदु x-axis पर होते हैं।'},
 {q:'बिंदु (4,3) किस quadrant में है?',options:['I','II','III','IV'],answer:0,explain:'x positive और y positive हैं, इसलिए I quadrant।'},
 {q:'बिंदु (−4,3) किस quadrant में है?',options:['I','II','III','IV'],answer:1,explain:'x negative और y positive हैं, इसलिए II quadrant।'},
 {q:'बिंदु (−4,−3) किस quadrant में है?',options:['I','II','III','IV'],answer:2,explain:'दोनों coordinates negative हैं, इसलिए III quadrant।'},
 {q:'बिंदु (4,−3) किस quadrant में है?',options:['I','II','III','IV'],answer:3,explain:'x positive और y negative हैं, इसलिए IV quadrant।'},
 {q:'(2,5) और (2,−1) में कौन-सा coordinate समान है?',options:['x','y','दोनों','कोई नहीं'],answer:0,explain:'दोनों में x = 2 है, इसलिए वे एक vertical line पर होंगे।'},
 {q:'(−3,4) और (5,4) में कौन-सा coordinate समान है?',options:['x','y','दोनों','कोई नहीं'],answer:1,explain:'दोनों में y = 4 है, इसलिए वे horizontal line पर होंगे।'},
 {q:'A(2,4), B(7,4) के बीच दूरी क्या है?',options:['3','5','6','9'],answer:1,explain:'y समान है, इसलिए horizontal distance = |7−2| = 5 units।'},
 {q:'A(−3,1), B(−3,6) के बीच दूरी क्या है?',options:['3','4','5','7'],answer:2,explain:'x समान है, इसलिए vertical distance = |6−1| = 5 units।'},
 {q:'(3,2) और (2,3) के बारे में सही कथन क्या है?',options:['एक ही बिंदु','अलग-अलग बिंदु','दोनों origin','दोनों axes पर'],answer:1,explain:'Ordered pair में क्रम महत्वपूर्ण है; (3,2) और (2,3) अलग बिंदु हैं।'},
 {q:'बिंदु (0,7) किस axis पर है?',options:['x-axis','y-axis','किसी पर नहीं','दोनों axes'],answer:1,explain:'x = 0 होने के कारण बिंदु y-axis पर है।'},
 {q:'बिंदु (−5,0) किस axis पर है?',options:['x-axis','y-axis','किसी पर नहीं','दोनों axes'],answer:0,explain:'y = 0 होने के कारण बिंदु x-axis पर है।'},
 {q:'यदि x > 0 और y < 0, तो quadrant कौन-सा होगा?',options:['I','II','III','IV'],answer:3,explain:'(+ , −) sign pattern IV quadrant का है।'},
 {q:'यदि x < 0 और y > 0, तो quadrant कौन-सा होगा?',options:['I','II','III','IV'],answer:1,explain:'(− , +) sign pattern II quadrant का है।'},
 {q:'A(1,2), B(5,2) किस तरह aligned हैं?',options:['vertical','horizontal','diagonal only','same point'],answer:1,explain:'y-coordinate दोनों में 2 है, इसलिए horizontal alignment है।'},
 {q:'A(−2,1), B(−2,6) किस तरह aligned हैं?',options:['horizontal','vertical','same point','axis crossing only'],answer:1,explain:'x-coordinate दोनों में −2 है, इसलिए vertical alignment है।'},
 {q:'A(2,4) और B(6,8) का midpoint क्या है?',options:['(4,6)','(2,6)','(6,4)','(8,12)'],answer:0,explain:'M=((2+6)/2,(4+8)/2)=(4,6)।'},
 {q:'A(−2,4) और B(4,4) का midpoint क्या है?',options:['(1,4)','(2,4)','(−1,4)','(4,1)'],answer:0,explain:'M=((−2+4)/2,(4+4)/2)=(1,4)।'},
 {q:'A(3,−2) और B(3,6) के बीच vertical distance क्या है?',options:['4','6','8','9'],answer:2,explain:'|6−(−2)|=8 units।'},
 {q:'A(−5,2) और B(1,2) के बीच horizontal distance क्या है?',options:['4','5','6','7'],answer:2,explain:'|1−(−5)|=6 units।'},
 {q:'यदि किसी बिंदु का x-coordinate positive है, तो वह origin के किस ओर होगा?',options:['बाएँ','दाएँ','ऊपर','नीचे'],answer:1,explain:'Positive x का अर्थ number line पर दाईं दिशा है।'},
 {q:'यदि किसी बिंदु का y-coordinate negative है, तो वह origin के किस ओर होगा?',options:['ऊपर','नीचे','दाएँ','बाएँ'],answer:1,explain:'Negative y का अर्थ vertical direction में नीचे जाना है।'},
 {q:'निम्न में से कौन-सा point II quadrant में है?',options:['(3,−2)','(−3,2)','(−3,−2)','(3,2)'],answer:1,explain:'II quadrant में x negative और y positive होते हैं।'},
 {q:'निम्न में से कौन-सा point IV quadrant में है?',options:['(−3,2)','(3,−2)','(−3,−2)','(3,2)'],answer:1,explain:'IV quadrant में x positive और y negative होते हैं।'},
 {q:'(0,0) के बारे में सही कथन क्या है?',options:['केवल x-axis पर','केवल y-axis पर','दोनों axes पर स्थित मूलबिंदु','III quadrant में'],answer:2,explain:'Origin दोनों axes पर स्थित होता है और किसी quadrant का interior point नहीं है।'},
 {q:'यदि दो points का x-coordinate समान है, तो उनके बीच connecting segment किस दिशा में होगा?',options:['horizontal','vertical','circular','कोई भी'],answer:1,explain:'x समान होने पर केवल y बदलता है, इसलिए segment vertical होता है।'},
 {q:'यदि दो points का y-coordinate समान है, तो segment किस दिशा में होगा?',options:['vertical','horizontal','circular','कोई भी'],answer:1,explain:'y समान होने पर केवल x बदलता है, इसलिए segment horizontal होता है।'},
 {q:'Distance formula में horizontal change किससे मिलता है?',options:['x₂−x₁','y₂−y₁','x₁+y₁','x₂+y₂'],answer:0,explain:'Horizontal difference Δx = x₂−x₁ लिया जाता है।'},
 {q:'Distance formula में vertical change किससे मिलता है?',options:['x₂−x₁','y₂−y₁','x₁+y₂','x₂+y₁'],answer:1,explain:'Vertical difference Δy = y₂−y₁ लिया जाता है।'},
 {q:'दो points (1,1) और (4,5) के बीच Δx का magnitude क्या है?',options:['2','3','4','5'],answer:1,explain:'|4−1| = 3।'},
 {q:'दो points (1,1) और (4,5) के बीच Δy का magnitude क्या है?',options:['2','3','4','5'],answer:3,explain:'|5−1| = 4।'},
 {q:'(1,1) और (4,5) के बीच distance क्या है?',options:['4','5','6','7'],answer:1,explain:'√((4−1)²+(5−1)²)=√(9+16)=5।'},
 {q:'(0,0) और (6,8) के बीच distance क्या है?',options:['8','10','12','14'],answer:1,explain:'√(6²+8²)=√100=10।'},
 {q:'(2,3) और (6,6) का midpoint क्या है?',options:['(4,4.5)','(3,4)','(4,3)','(8,9)'],answer:0,explain:'M=((2+6)/2,(3+6)/2)=(4,4.5)।'},
 {q:'यदि midpoint (5,4) है और एक endpoint (3,2) है, तो दूसरा endpoint क्या होगा?',options:['(7,6)','(8,7)','(2,2)','(6,5)'],answer:0,explain:'(3+x)/2=5 ⇒ x=7 और (2+y)/2=4 ⇒ y=6।'},
 {q:'एक floor grid में सीट D(4,2) और E(4,7) हैं। वे किस दिशा में aligned हैं?',options:['horizontal','vertical','diagonal','एक ही point'],answer:1,explain:'x-coordinate 4 समान है, इसलिए vertical alignment है।'}
];
