export const chapter4Learning = {
  title:'अध्याय 4: दो चरों वाले रैखिक समीकरण',
  goal:'दो चरों वाले रैखिक समीकरण को पहचानें, table और graph बनाएं, slope-intercept रूप समझें और दो रैखिक समीकरणों के युग्म को graph, substitution और elimination से हल करें।',
  lessons:[
    {type:'intro',title:'अध्याय 4 की शुरुआत',body:'सोचिए किसी दुकान में ₹200 की fixed fee है और हर item पर ₹30 लगते हैं। कुल खर्च items की संख्या के साथ बदलता है। ऐसे बदलते संबंधों को variables और linear equations से लिखा जा सकता है।',points:['Variable बदल सकता है।','Equation उस संबंध को संक्षेप में बताता है।'],visual:{type:'flow',title:'Real life से गणित',items:['स्थिति','Variables','Equation','Table','Graph','निष्कर्ष']}},
    {type:'concept',title:'दो चरों वाला रैखिक समीकरण',body:'ऐसा समीकरण जिसमें दो variables हों और variables की highest power 1 हो, दो चरों वाला linear equation कहलाता है। सामान्य रूप ax+by+c=0 है, जहाँ a और b दोनों एक साथ 0 नहीं होते।',points:['2x+3y=12 ✔','x+y=5 ✔','x²+y=5 ✘'],visual:{type:'compare',title:'पहचानने की जाँच',items:['power 1 → linear','दो variables → x और y','x², xy जैसी terms → सावधान']}},
    {type:'concept',title:'Solution का अर्थ',body:'(x,y) का ordered pair तब solution है जब उसे equation में रखने पर equation सत्य हो जाए। एक linear equation in two variables के कई solutions हो सकते हैं।',example:'2x+y=6 में (1,4), (2,2) और (3,0) solutions हैं।',visual:{type:'steps',title:'Solution verify करें',items:['ordered pair लें','x,y substitute करें','दोनों sides सरल करें','बराबर आए → solution']}},
    {type:'concept',title:'Table of values',body:'Graph बनाने के लिए कुछ x-values चुनें और equation से उनके corresponding y-values निकालें। ये ordered pairs graph के points बनते हैं।',example:'x+y=5 में x=0,1,2 लेने पर y=5,4,3।',visual:{type:'compare',title:'Value pairs',items:['0 → 5','1 → 4','2 → 3']}},
    {type:'concept',title:'Equation से straight line',body:'एक linear equation के सभी solutions को coordinate plane पर plot करने पर सामान्यतः एक straight line मिलती है। इसलिए algebra और graph एक ही संबंध को अलग-अलग रूप में दिखाते हैं।',visual:{type:'flow',title:'एक ही संबंध के रूप',items:['Equation','Solutions','Points','Straight line']}},
    {type:'concept',title:'Slope-intercept form',body:'Linear equation को y=mx+c के रूप में लिखा जा सकता है। m slope और c y-intercept है।',points:['m line की steepness और दिशा बताता है।','c बताता है कि line y-axis को कहाँ काटती है।'],visual:{type:'equation',title:'y = mx + c',items:['m = slope','c = y-intercept','x बढ़े 1 → y में m का बदलाव']}},
    {type:'example',title:'Slope को पढ़ें',body:'y=3x+1 में m=3 और c=1 है। इसलिए x में 1 की वृद्धि करने पर y में 3 की वृद्धि होती है।',visual:{type:'steps',title:'y = 3x + 1',items:['m = 3','c = 1','x: 1 → 2','y: 4 → 7']}},
    {type:'concept',title:'दो equations का pair',body:'जब दो linear equations को साथ देखा जाता है, उनका common solution वह ordered pair होता है जो दोनों equations को एक साथ satisfy करता है।',example:'x+y=5 और x−y=1 का common solution (3,2) है।'},
    {type:'concept',title:'Graphical solution',body:'दो lines के graphs का intersection common solution बताता है। Graph देखकर solution की प्रकृति तुरंत समझी जा सकती है।',visual:{type:'compare',title:'Lines क्या बताती हैं?',items:['एक intersection → एक solution','parallel अलग lines → कोई solution नहीं','same line → अनंत solutions']}},
    {type:'concept',title:'Consistency',body:'यदि pair का कम-से-कम एक common solution है तो pair consistent है। यदि कोई common solution नहीं है तो inconsistent है।',points:['एक point पर मिलना → unique solution','same line → infinitely many solutions','parallel lines → no solution']},
    {type:'concept',title:'Substitution method',body:'एक equation से एक variable को दूसरे variable के रूप में लिखें और उस expression को दूसरी equation में substitute करें।',visual:{type:'steps',title:'Substitution recipe',items:['एक variable isolate करें','दूसरी equation में डालें','एक variable solve करें','back-substitute करें']}},
    {type:'example',title:'Substitution worked example',body:'x+y=7 और x−y=1। पहली equation से x=7−y। दूसरी में रखने पर 7−y−y=1 ⇒ 2y=6 ⇒ y=3 और x=4।',visual:{type:'equation',title:'Step by step',items:['x=7−y','7−2y=1','y=3','x=4']}},
    {type:'concept',title:'Elimination method',body:'दो equations को जोड़ या घटाकर किसी एक variable को cancel किया जाता है। यदि coefficients समान नहीं हैं तो पहले suitable multiplication किया जा सकता है।',visual:{type:'steps',title:'Elimination recipe',items:['terms align करें','एक variable के coefficients match करें','add/subtract करें','बचा variable solve करें']}},
    {type:'example',title:'Elimination worked example',body:'2x+y=8 और 2x−y=4 को जोड़ने पर 4x=12 ⇒ x=3। फिर 2(3)+y=8 ⇒ y=2।',visual:{type:'equation',title:'Eliminate करें',items:['2x+y=8','2x−y=4','4x=12 → x=3','y=2']}},
    {type:'concept',title:'Daily-life modelling',body:'Fixed charge + प्रति unit charge जैसे संबंध linear equations बना सकते हैं। Equation बनाने से पहले दोनों variables को स्पष्ट रूप से define करें।',example:'₹50 fixed + ₹12 प्रति km ⇒ C=50+12x।',visual:{type:'flow',title:'Model बनाने के कदम',items:['variable चुनें','fixed part','rate × quantity','total equation']}},
    {type:'concept',title:'Equation, table और graph',body:'एक ही समस्या को equation, table और graph तीनों तरीकों से represent करना समझ को मजबूत करता है। एक representation से दूसरे में बदलना अच्छे problem-solving की निशानी है।',visual:{type:'flow',title:'तीन representations',items:['Equation','Table','Graph']}},
    {type:'concept',title:'सामान्य गलतियाँ',body:'सबसे सामान्य गलतियाँ ordered pair का क्रम बदलना, negative sign भूलना, y=mx+c में m और c उलटना और substitution में पूरा expression bracket में न रखना हैं।',points:['(x,y) में x पहले आता है।','−2x का sign ध्यान से रखें।','m=slope, c=y-intercept।','Substitution में sign और brackets जाँचें।']},
    {type:'check',title:'त्वरित जाँच 1',question:'2x+y=7 में x=2 होने पर y क्या होगा?',options:['2','3','4','5'],answer:1,explain:'4+y=7, इसलिए y=3।'},
    {type:'check',title:'त्वरित जाँच 2',question:'y=4x−3 में slope क्या है?',options:['−3','3','4','7'],answer:2,explain:'y=mx+c में x का coefficient m slope होता है, इसलिए slope 4 है।'}
  ]
};
