export const chapter4Practice = [
  {q:'2x+y=7 में x=2 होने पर y क्या होगा?',options:['2','3','4','5'],answer:1,explain:'2(2)+y=7 ⇒ 4+y=7 ⇒ y=3।'},
  {q:'x+y=10 में x=4 होने पर y क्या होगा?',options:['4','5','6','7'],answer:2,explain:'4+y=10 ⇒ y=6।'},
  {q:'y=3x+2 में slope क्या है?',options:['2','3','−3','5'],answer:1,explain:'y=mx+c में m slope है। यहाँ m=3।'},
  {q:'y=5x−7 में y-intercept क्या है?',options:['5','−7','7','−5'],answer:1,explain:'y=mx+c में c y-intercept है। यहाँ c=−7।'},
  {q:'(2,3) क्या x+y=5 का solution है?',options:['हाँ','नहीं','केवल x के लिए','केवल y के लिए'],answer:0,explain:'2+3=5, इसलिए (2,3) solution है।'},
  {q:'(1,4) और (2,3) में से कौन 2x+y=6 को satisfy करता है?',options:['केवल (1,4)','केवल (2,3)','दोनों','कोई नहीं'],answer:2,explain:'2(1)+4=6 और 2(2)+3=7, इसलिए केवल (1,4) सही है।'},
  {q:'x−y=2 में x=5 होने पर y क्या होगा?',options:['2','3','5','7'],answer:1,explain:'5−y=2 ⇒ y=3।'},
  {q:'कौन-सा दो चरों वाला linear equation है?',options:['x²+y=5','2x+3y=7','xy=6','1/x+y=2'],answer:1,explain:'2x+3y=7 में दोनों variables की highest power 1 है और उनका product नहीं है।'},
  {q:'x²+y=5 linear equation क्यों नहीं है?',options:['क्योंकि इसमें y है','क्योंकि x की power 2 है','क्योंकि 5 constant है','क्योंकि इसमें + है'],answer:1,explain:'दो-चर linear equation में variables की powers 1 होती हैं।'},
  {q:'x+y=4 और x−y=0 का solution क्या है?',options:['(2,2)','(4,0)','(0,4)','(1,3)'],answer:0,explain:'जोड़ने पर 2x=4 ⇒ x=2 और y=2।'},
  {q:'x+y=7 और x−y=1 को जोड़ने पर क्या मिलता है?',options:['2x=8','2y=6','x=8','y=8'],answer:0,explain:'y terms cancel होती हैं और 2x=8 मिलता है।'},
  {q:'3x+y=11 और x=2 होने पर y कितना है?',options:['3','4','5','6'],answer:2,explain:'6+y=11 ⇒ y=5।'},
  {q:'2x+3y=12 में x=0 होने पर y?',options:['2','3','4','6'],answer:2,explain:'3y=12 ⇒ y=4।'},
  {q:'2x+3y=12 में y=0 होने पर x?',options:['4','6','8','12'],answer:1,explain:'2x=12 ⇒ x=6।'},
  {q:'यदि y=2x+1 और x=3, तो y?',options:['5','6','7','8'],answer:2,explain:'y=2(3)+1=7।'},
  {q:'यदि y=−x+5 और x=2, तो y?',options:['2','3','4','5'],answer:2,explain:'y=−2+5=3। इसलिए विकल्प B सही है।'},
  {q:'दो distinct parallel lines के pair का solution क्या होता है?',options:['एक','दो','कोई नहीं','अनंत'],answer:2,explain:'Parallel distinct lines कभी नहीं मिलतीं, इसलिए common solution नहीं होता।'},
  {q:'दो equations की graphs एक ही line हों तो कितने solutions होते हैं?',options:['0','1','2','अनंत अनेक'],answer:3,explain:'एक ही line पर अनंत points होते हैं, और वे दोनों equations को satisfy करते हैं।'},
  {q:'एक intersection point किस प्रकार के solution को दर्शाता है?',options:['No solution','Unique solution','Infinite solutions','Undefined'],answer:1,explain:'दो lines एक point पर मिलें तो वही एक common ordered pair होता है।'},
  {q:'Substitution method में पहला सामान्य कदम क्या है?',options:['दोनों equations multiply करना','एक variable को isolate करना','graph erase करना','constant हटाना'],answer:1,explain:'एक equation से x या y को दूसरे variable के रूप में लिखना substitution को आसान बनाता है।'},
  {q:'Elimination method का लक्ष्य क्या होता है?',options:['दोनों variables बढ़ाना','एक variable cancel करना','equation को fraction बनाना','graph हटाना'],answer:1,explain:'Equations को add/subtract करके एक variable eliminate किया जाता है।'},
  {q:'x+y=9 और x−y=3 में x क्या है?',options:['3','4','6','9'],answer:2,explain:'जोड़ने पर 2x=12 ⇒ x=6।'},
  {q:'x+y=9 और x−y=3 में y क्या है?',options:['2','3','6','12'],answer:1,explain:'x=6 रखने पर 6+y=9 ⇒ y=3।'},
  {q:'2x+y=10 और x−y=2 में x क्या है?',options:['2','3','4','6'],answer:2,explain:'दूसरी equation y=x−2. पहली में रखें: 2x+x−2=10 ⇒ 3x=12 ⇒ x=4।'},
  {q:'ऊपर वाले pair में y क्या है?',options:['1','2','3','4'],answer:1,explain:'x=4 और x−y=2 ⇒ 4−y=2 ⇒ y=2।'},
  {q:'एक taxi में fixed charge ₹50 और ₹12 प्रति km है। x km पर fare का linear equation कौन-सा है?',options:['50x+12','50+12x','12+50x','62x'],answer:1,explain:'Fixed ₹50 + ₹12 प्रति km × x = 50+12x।'},
  {q:'यदि fare C=50+12x है, तो 5 km का fare?',options:['60','100','110','120'],answer:2,explain:'50+12×5=110।'},
  {q:'एक school club ₹200 registration और ₹30 प्रति event लेता है। n events पर cost?',options:['200n+30','30+200n','200+30n','230n'],answer:2,explain:'Fixed 200 + variable 30n = 200+30n।'},
  {q:'y=4x+1 में x 1 से 2 होने पर y कितने से बढ़ेगा?',options:['1','3','4','5'],answer:2,explain:'Slope 4 है, इसलिए x में 1 की वृद्धि से y में 4 की वृद्धि होती है।'},
  {q:'यदि two-variable equation का graph straight line है, तो graph पर हर point क्या दर्शाता है?',options:['केवल x value','Equation का solution','केवल y value','constant'],answer:1,explain:'Graph की line पर स्थित हर ordered pair equation को satisfy करता है।'},
  {q:'x=3 क्या दो चरों वाला linear equation माना जा सकता है?',options:['हाँ, इसे x+0y=3 लिख सकते हैं','नहीं, कभी नहीं','केवल graph में','केवल integer values पर'],answer:0,explain:'x=3 को x+0y−3=0 के रूप में लिखा जा सकता है; इसमें y का coefficient 0 है।'},
  {q:'y=−4 क्या equation है?',options:['y=−4x','दो चरों वाला equation नहीं लिखा जा सकता','इसे 0x+y=−4 लिख सकते हैं','y=4x'],answer:2,explain:'0x+y=−4 एक valid linear equation in two variables है।'},
  {q:'3x+2y=12 में x=2 होने पर y?',options:['2','3','4','5'],answer:1,explain:'6+2y=12 ⇒ 2y=6 ⇒ y=3।'},
  {q:'x+2y=8 में y=3 होने पर x?',options:['1','2','3','4'],answer:0,explain:'x+6=8 ⇒ x=2। इसलिए विकल्प B सही है।'},
  {q:'यदि दो lines का intersection (4,−1) है, तो इसका अर्थ क्या है?',options:['केवल पहली equation satisfy होती है','केवल दूसरी','दोनों equations satisfy होती हैं','कोई नहीं'],answer:2,explain:'Intersection point दोनों graphs पर है, इसलिए वह दोनों equations का common solution है।'},
  {q:'3x−2y=6 को y=mx+c form में बदलने पर slope क्या है?',options:['3/2','−3/2','2/3','−2/3'],answer:0,explain:'2y=3x−6 ⇒ y=(3/2)x−3, इसलिए slope 3/2।'},
  {q:'4x+y=9 को y के रूप में लिखने पर?',options:['y=4x+9','y=9−4x','y=4x−9','y=9+4x'],answer:1,explain:'y=9−4x।'},
  {q:'यदि y=0 किसी linear equation में है, तो graph पर point कहाँ होगा?',options:['y-axis','x-axis','origin हमेशा','Quadrant II हमेशा'],answer:1,explain:'y=0 वाले सभी points x-axis पर स्थित होते हैं।'},
  {q:'यदि x=0 हो, तो point कहाँ होगा?',options:['x-axis','y-axis','origin हमेशा','Quadrant IV'],answer:1,explain:'x=0 वाले सभी points y-axis पर होते हैं।'},
  {q:'कौन-सा pair x+y=6 और x−y=2 का solution है?',options:['(2,4)','(4,2)','(3,3)','(5,1)'],answer:1,explain:'4+2=6 और 4−2=2, इसलिए (4,2) common solution है।'}
];
