export const chapter3Learning = {
  title:'अध्याय 3: निर्देशांक ज्यामिति',
  goal:'निर्देशांक तल, ordered pair, x-अक्ष, y-अक्ष, चतुर्थांश, बिंदुओं की स्थिति और grid पर दूरी की शुरुआती समझ मजबूत करें।',
  lessons:[
    {type:'intro',title:'निर्देशांक ज्यामिति की शुरुआत',body:'मान लीजिए किसी शहर के नक्शे पर हर स्थान को एक code दिया जाए। निर्देशांक ज्यामिति भी यही विचार अपनाती है: किसी बिंदु का स्थान दो संख्याओं से बताया जाता है।',points:['पहली संख्या horizontal दिशा बताती है।','दूसरी संख्या vertical दिशा बताती है।','इन्हें क्रमित युग्म (ordered pair) कहते हैं।'],visual:{type:'grid',title:'एक बिंदु का पता',items:['x = दाएँ/बाएँ','y = ऊपर/नीचे','(x,y) = पूरा पता']}},
    {type:'concept',title:'Cartesian plane क्या है?',body:'दो परस्पर लम्बवत संख्या रेखाएँ—x-अक्ष और y-अक्ष—मिलकर Cartesian coordinate plane बनाती हैं।',points:['x-अक्ष horizontal होता है।','y-अक्ष vertical होता है।','दोनों axes का मिलन बिंदु origin कहलाता है।'],visual:{type:'axes',title:'निर्देशांक तल',items:['x-अक्ष','y-अक्ष','मूलबिंदु O(0,0)']}},
    {type:'concept',title:'मूलबिंदु और ordered pair',body:'मूलबिंदु (0,0) पर दोनों निर्देशांक शून्य होते हैं। किसी बिंदु को (x,y) लिखने में क्रम बहुत महत्वपूर्ण है।',example:'(3,2) और (2,3) एक ही बिंदु नहीं हैं।',visual:{type:'compare',title:'क्रम क्यों जरूरी है?',items:['(3,2) → पहले 3, फिर 2','(2,3) → पहले 2, फिर 3']}},
    {type:'concept',title:'x-coordinate कैसे पढ़ें?',body:'किसी बिंदु (x,y) में x-coordinate बताता है कि origin से horizontal दिशा में कितने units जाना है।',points:['x > 0 → दाईं ओर','x < 0 → बाईं ओर','x = 0 → बिंदु y-अक्ष पर होगा'],visual:{type:'steps',title:'Horizontal move',items:['Origin से शुरू करें','x के अनुसार दाएँ/बाएँ जाएँ','फिर y की ओर ऊपर/नीचे जाएँ']}},
    {type:'concept',title:'y-coordinate कैसे पढ़ें?',body:'y-coordinate vertical position बताता है। x तय करने के बाद y की दिशा में ऊपर या नीचे जाते हैं।',points:['y > 0 → ऊपर','y < 0 → नीचे','y = 0 → बिंदु x-अक्ष पर होगा'],visual:{type:'numberline',title:'Vertical position',items:['ऊपर +2','ऊपर +1','0','नीचे −1','नीचे −2']}},
    {type:'example',title:'बिंदु (4,3) को plot करें',body:'पहले origin से 4 units दाईं ओर जाएँ। फिर 3 units ऊपर जाएँ। वहाँ मिलने वाला बिंदु (4,3) है।',visual:{type:'steps',title:'Plotting recipe',items:['(0,0) से शुरू','4 units right','3 units up','बिंदु = (4,3)']}},
    {type:'example',title:'बिंदु (−2,3) को plot करें',body:'−2 का अर्थ 2 units बाईं ओर और 3 का अर्थ 3 units ऊपर है। इसलिए बिंदु y-अक्ष के बाएँ और x-अक्ष के ऊपर होगा।'},
    {type:'concept',title:'चार चतुर्थांश',body:'x-अक्ष और y-अक्ष समतल को चार quadrants में बाँटते हैं। चतुर्थांश पहचानने के लिए x और y के signs देखें।',points:['I: (+,+)','II: (−,+)','III: (−,−)','IV: (+,−)'],visual:{type:'quadrants',title:'Signs से quadrant पहचानें',items:['I  (+,+)','II (−,+)','III (−,−)','IV (+,−)']}},
    {type:'concept',title:'Axis पर बिंदु',body:'यदि किसी बिंदु का x-coordinate 0 है तो वह y-axis पर है। यदि y-coordinate 0 है तो वह x-axis पर है।',examples:['(0,5) → y-axis','(−4,0) → x-axis','(0,0) → origin']},
    {type:'concept',title:'एक ही coordinate वाला pattern',body:'जिन बिंदुओं का y-coordinate समान हो वे एक horizontal line पर होते हैं। जिनका x-coordinate समान हो वे एक vertical line पर होते हैं।',visual:{type:'compare',title:'Same coordinate patterns',items:['y = 3 → horizontal level','x = −2 → vertical line']}},
    {type:'example',title:'बिंदुओं की तुलना',body:'A(2,5) और B(2,−1) में x-coordinate समान है। इसलिए दोनों एक ही vertical line पर होंगे।',visual:{type:'equation',title:'Pattern पहचानें',items:['A = (2,5)','B = (2,−1)','x समान = vertical alignment']}},
    {type:'concept',title:'दो बिंदुओं के बीच horizontal distance',body:'जब दो बिंदुओं का y-coordinate समान हो, तो उनकी दूरी उनके x-coordinates के अंतर का परिमाण होती है।',example:'A(2,4), B(7,4) ⇒ दूरी = |7−2| = 5 units।'},
    {type:'concept',title:'दो बिंदुओं के बीच vertical distance',body:'जब x-coordinate समान हो, तो दूरी y-coordinates के अंतर का परिमाण होती है।',example:'A(−3,1), B(−3,6) ⇒ दूरी = |6−1| = 5 units।'},
    {type:'concept',title:'Distance formula की ओर पहला कदम',body:'जब दोनों coordinates बदलते हों, तो horizontal और vertical differences महत्वपूर्ण होते हैं। आगे यही विचार distance formula तक पहुँचता है।',visual:{type:'formula',title:'Right triangle idea',items:['Δx = x₂−x₁','Δy = y₂−y₁','distance = √(Δx²+Δy²)']}},
    {type:'concept',title:'Midpoint का विचार',body:'दो बिंदुओं के ठीक बीच का बिंदु उनके x-coordinates का average और y-coordinates का average लेकर पाया जा सकता है।',visual:{type:'formula',title:'Midpoint',items:['x̄ = (x₁+x₂)/2','ȳ = (y₁+y₂)/2','M = (x̄,ȳ)']}},
    {type:'example',title:'Midpoint का आसान उदाहरण',body:'A(2,4) और B(6,8) का midpoint M((2+6)/2,(4+8)/2) = (4,6) है।',visual:{type:'steps',title:'तीन कदम',items:['x values का average','y values का average','दोनों को pair करें → (4,6)']}},
    {type:'concept',title:'Grid और वास्तविक जीवन',body:'फर्श की tiles, seat map, game board और शहर के grid जैसे स्थानों को coordinates से model किया जा सकता है।',visual:{type:'grid',title:'Coordinate thinking',items:['Seat = row + column','Map = east/west + north/south','Game = x + y position']}},
    {type:'concept',title:'सामान्य गलतियाँ',body:'सबसे सामान्य गलती x और y का क्रम बदलना है। दूसरी गलती negative sign को ignore करना और quadrant गलत पहचानना है।',points:['(x,y) में पहले x पढ़ें।','− का sign direction बदलता है।','Axis वाले points में zero coordinate देखें।']},
    {type:'check',title:'त्वरित जाँच 1',question:'बिंदु (−3,4) किस quadrant में है?',options:['I','II','III','IV'],answer:1,explain:'x negative और y positive है, इसलिए बिंदु II quadrant में है।'},
    {type:'check',title:'त्वरित जाँच 2',question:'(0,−5) कहाँ स्थित है?',options:['x-अक्ष पर','y-अक्ष पर','I quadrant में','origin पर'],answer:1,explain:'x-coordinate 0 है, इसलिए बिंदु y-axis पर है।'}
  ]
};
