export const chapter2Practice = [
  {q:'3x²−5x+2 में कुल कितने पद हैं?',options:['1','2','3','4'],answer:2,explain:'3x², −5x और 2 तीन अलग-अलग पद हैं।'},
  {q:'5x³−2x+7 में x³ का गुणांक क्या है?',options:['5','−2','7','3'],answer:0,explain:'x³ के साथ 5 गुणा हो रहा है, इसलिए गुणांक 5 है।'},
  {q:'7x⁴−3x+1 की degree क्या है?',options:['1','3','4','7'],answer:2,explain:'सबसे बड़ी चर-घात 4 है, इसलिए degree 4 है।'},
  {q:'p(x)=x−6 का zero कौन है?',options:['−6','0','6','12'],answer:2,explain:'p(6)=6−6=0, इसलिए 6 zero है।'},
  {q:'−9 किस प्रकार का polynomial है?',options:['linear','quadratic','constant','cubic'],answer:2,explain:'शून्य से अलग constant polynomial की degree 0 होती है।'},
  {q:'x का coefficient क्या है?',options:['0','1','x','−1'],answer:1,explain:'x को 1x लिखा जा सकता है, इसलिए coefficient 1 है।'},
  {q:'−x में coefficient क्या है?',options:['1','−1','x','0'],answer:1,explain:'−x = −1x, इसलिए coefficient −1 है।'},
  {q:'4x²−7x+9 का constant term क्या है?',options:['4','−7','9','2'],answer:2,explain:'जिस term में variable नहीं है, वह constant term है; यहाँ 9 है।'},
  {q:'2x+5 किस degree का polynomial है?',options:['0','1','2','5'],answer:1,explain:'x की highest power 1 है, इसलिए degree 1 है।'},
  {q:'p(x)=x²−3x+2 में p(2) का मान क्या है?',options:['0','1','2','4'],answer:0,explain:'p(2)=4−6+2=0।'},
  {q:'p(x)=2x+3 में x=4 होने पर output क्या होगा?',options:['7','8','11','14'],answer:2,explain:'2×4+3=11।'},
  {q:'निम्न में से कौन polynomial नहीं है?',options:['x²+1','3x−7','1/x+2','5'],answer:2,explain:'1/x में x की power −1 है और variable denominator में है; यह polynomial नहीं है।'},
  {q:'√x+2 polynomial क्यों नहीं है?',options:['क्योंकि constant नहीं है','क्योंकि x की power 1/2 है','क्योंकि इसमें + है','क्योंकि coefficient बड़ा है'],answer:1,explain:'Polynomial में variable की powers non-negative integers होनी चाहिए; 1/2 integer नहीं है।'},
  {q:'x−3 यदि p(x) का factor है तो कौन-सा कथन सही है?',options:['p(3)=0','p(−3)=0','p(0)=3','p(1)=0'],answer:0,explain:'Factor theorem: x−a factor होने पर p(a)=0।'},
  {q:'x²−5x+6 के zeroes कौन हैं?',options:['1 और 6','2 और 3','−2 और −3','5 और 6'],answer:1,explain:'x²−5x+6=(x−2)(x−3), इसलिए zeroes 2 और 3 हैं।'},
  {q:'x²−9 का एक factor कौन-सा है?',options:['x−3','x−9','x+9','x²−3'],answer:0,explain:'x²−9=(x−3)(x+3)।'},
  {q:'यदि p(a)=0, तो a क्या कहलाता है?',options:['coefficient','term','zero','degree'],answer:2,explain:'जिस value पर polynomial का मान 0 हो, वही zero कहलाती है।'},
  {q:'3x²+4x−7 की degree और number of terms क्रमशः क्या हैं?',options:['2 और 3','3 और 2','2 और 2','3 और 3'],answer:0,explain:'Highest power 2 है और तीन terms हैं।'},
  {q:'5x³−x²+7 में x² का coefficient क्या है?',options:['5','−1','1','7'],answer:1,explain:'x² term −x² है, इसलिए उसका coefficient −1 है।'},
  {q:'2x⁴+3x²−8 में कौन-सी power missing है?',options:['4','3','2','0'],answer:1,explain:'x³ term मौजूद नहीं है; polynomial में हर intermediate power का होना जरूरी नहीं है।'},
  {q:'यदि p(x)=x²+1, तो p(−2) क्या होगा?',options:['−3','−1','3','5'],answer:3,explain:'p(−2)=(−2)²+1=4+1=5।'},
  {q:'यदि p(x)=2x−7, तो इसका zero क्या है?',options:['−7','7/2','2/7','7'],answer:1,explain:'2x−7=0 ⇒ 2x=7 ⇒ x=7/2।'},
  {q:'3x+9 की zero क्या है?',options:['3','−3','9','−9'],answer:1,explain:'3x+9=0 ⇒ 3x=−9 ⇒ x=−3।'},
  {q:'यदि p(x)=x²−4, तो कौन-सा pair zeroes का है?',options:['−2 और 2','−4 और 4','0 और 4','1 और 4'],answer:0,explain:'x²−4=(x−2)(x+2), इसलिए zeroes 2 और −2 हैं।'},
  {q:'किसी linear polynomial की सामान्य form क्या है?',options:['ax²+b','ax+b, a≠0','a/x+b','ax³+b'],answer:1,explain:'Degree 1 polynomial की form ax+b होती है, जहाँ a≠0।'},
  {q:'constant polynomial 8 को x की power के रूप में कैसे लिख सकते हैं?',options:['8x','8x²','8x⁰','8x⁻¹'],answer:2,explain:'x⁰=1, इसलिए 8=8x⁰।'},
  {q:'यदि polynomial के consecutive values 3,5,7,9 हैं, तो common difference क्या है?',options:['1','2','3','4'],answer:1,explain:'हर बार 2 बढ़ रहा है: 5−3=2, 7−5=2।'},
  {q:'nth term 2n−1 हो तो 10th term क्या होगी?',options:['17','18','19','20'],answer:2,explain:'2(10)−1=19।'},
  {q:'nth term 3n+2 हो तो n=5 पर value क्या है?',options:['15','17','18','20'],answer:1,explain:'3×5+2=17।'},
  {q:'एक club ₹200 fixed fee और ₹50 प्रति match लेता है। m matches पर cost क्या होगी?',options:['50m','200m+50','200+50m','250m'],answer:2,explain:'Fixed ₹200 + प्रति match ₹50×m = 200+50m।'},
  {q:'यदि C(m)=200+50m, तो 6 matches की cost क्या होगी?',options:['300','450','500','600'],answer:2,explain:'200+50×6=500।'},
  {q:'एक quantity 100 से शुरू होकर हर step में 5 घटती है। n steps के बाद expression क्या हो सकता है?',options:['100+5n','100−5n','5n−100','100n−5'],answer:1,explain:'हर step पर 5 की कमी है, इसलिए 100−5n।'},
  {q:'p(x)=x²−7x+12 में p(3) क्या होगा?',options:['0','3','6','12'],answer:0,explain:'9−21+12=0।'},
  {q:'p(x)=x²−7x+12 में p(4) क्या होगा?',options:['0','1','4','12'],answer:0,explain:'16−28+12=0।'},
  {q:'यदि p(x)=(x−2)(x−5), तो zeroes क्या हैं?',options:['2 और 5','−2 और −5','2 और −5','−2 और 5'],answer:0,explain:'x−2=0 से x=2 और x−5=0 से x=5।'},
  {q:'3x²−12 में common factor निकालने पर क्या मिलेगा?',options:['3(x²−4)','3(x²−12)','x(3x−12)','3x(x−4)'],answer:0,explain:'3x²−12=3(x²−4)।'},
  {q:'x²−16 को factorise करने पर कौन-सा सही है?',options:['(x−4)(x+4)','(x−8)(x+2)','(x−4)²','(x+16)(x−1)'],answer:0,explain:'यह difference of squares है: x²−4²=(x−4)(x+4)।'},
  {q:'यदि p(x)=2x²+3x−5, तो p(1) क्या है?',options:['0','1','5','10'],answer:0,explain:'2+3−5=0।'},
  {q:'किस कथन में zeroes और factors का संबंध सही है?',options:['x+a factor ⇒ zero a','x−a factor ⇒ zero a','x−a factor ⇒ zero −a','factor का zero से कोई संबंध नहीं'],answer:1,explain:'x−a factor होने पर p(a)=0, इसलिए a zero है।'},
  {q:'यदि p(−2)=0, तो कौन-सा factor निश्चित है?',options:['x−2','x+2','x−1','x+1'],answer:1,explain:'p(a)=0 पर x−a factor होता है। यहाँ a=−2, इसलिए factor x+2 है।'},
  {q:'किस polynomial की degree 3 है?',options:['4x+1','x²−3','2x³+x−1','7'],answer:2,explain:'2x³+x−1 में highest power 3 है।'},
  {q:'यदि p(x)=4x²−1, तो p(1/2) का मान क्या होगा?',options:['−1','0','1','2'],answer:1,explain:'4(1/2)²−1=4(1/4)−1=1−1=0।'},
  {q:'यदि p(x)=x²+2x−8, तो कौन-सा factor pair सही है?',options:['(x+4)(x−2)','(x−4)(x+2)','(x+8)(x−1)','(x+2)(x−4)'],answer:0,explain:'x²+2x−8=(x+4)(x−2)।'},
  {q:'2x²−5x+3 के zeroes का योग क्या है?',options:['3/2','5/2','−5/2','2/3'],answer:1,explain:'Quadratic ax²+bx+c के zeroes का sum −b/a होता है। यहाँ −(−5)/2=5/2।'},
  {q:'2x²−5x+3 के zeroes का गुणनफल क्या है?',options:['3/2','5/2','−3/2','2/3'],answer:0,explain:'Quadratic ax²+bx+c में product of zeroes = c/a = 3/2।'},
  {q:'यदि p(x)=x³−8, तो कौन-सा factor सही है?',options:['x−2','x−8','x+2','x²+4'],answer:0,explain:'2³−8=0, इसलिए factor theorem से x−2 factor है।'},
  {q:'यदि किसी polynomial में constant term 0 है, तो कौन-सी बात निश्चित रूप से सही है?',options:['x factor हो सकता है','degree हमेशा 0 होगी','polynomial linear ही होगा','कोई term नहीं होगा'],answer:0,explain:'यदि constant term 0 है, तो polynomial के सभी terms में x common हो सकता है, इसलिए x एक factor होता है (non-zero polynomial की स्थिति में)।'},
  {q:'p(x)=3x²−12x+9 को 3 से factor करने पर अंदर क्या बचेगा?',options:['x²−4x+3','x²−12x+3','3x²−4x+3','x²−4x−3'],answer:0,explain:'3x²−12x+9=3(x²−4x+3)।'},
  {q:'यदि p(x)=x²−1, तो p(−1)+p(1) कितना होगा?',options:['−2','−1','0','2'],answer:2,explain:'p(−1)=0 और p(1)=0, इसलिए योग 0 है।'},
  {q:'यदि p(x)=2x+1 और p(k)=9, तो k क्या है?',options:['3','4','5','9/2'],answer:1,explain:'2k+1=9 ⇒ 2k=8 ⇒ k=4।'},
  {q:'यदि p(x)=x²−9x+20 का एक zero 4 है, तो दूसरा zero क्या होगा?',options:['4','5','9','20'],answer:1,explain:'x²−9x+20=(x−4)(x−5), इसलिए दूसरा zero 5 है।'}
];
