export const chapter4Learning = {
  title:'अध्याय 4: दो चरों वाले रैखिक समीकरण',
  goal:'दो चरों वाले रैखिक समीकरण को पहचानें, table और graph बनाएं, slope-intercept रूप समझें और दो रैखिक समीकरणों के युग्म को graph, substitution और elimination से हल करें।',
  lessons:[
    {type:'intro',title:'अध्याय 4 की शुरुआत',body:'कल्पना कीजिए कि ₹200 की fixed fee है और हर notebook पर ₹30 लगते हैं। कुल खर्च कितनी notebooks पर निर्भर करेगा? ऐसे संबंधों को हम variables और linear equations से लिख सकते हैं।',points:['दो variables एक-दूसरे से जुड़े हो सकते हैं।','Equation उस संबंध को गणित की भाषा देता है।'],visual:{type:'flow',title:'Real life → equation',items:['स्थिति','variables','equation','table','graph','निष्कर्ष']}},
    {type:'concept',title:'दो चरों वाला रैखिक समीकरण क्या है?',body:'ऐसा समीकरण जिसमें दो variables हों और प्रत्येक variable की highest power 1 हो, दो चरों वाला linear equation कहलाता है। सामान्य रूप ax + by + c = 0 है, जहाँ a और b दोनों एक साथ 0 नहीं होते।',points:['2x+3y=12 एक linear equation है।','x+y=5 भी linear equation है।','x²+y=5 linear equation नहीं है क्योंकि x की power 2 है।']},
    {type:'concept',title:'Solution का अर्थ',body:'(x,y) का ordered pair तब solution है जब उसे equation में रखने पर equation सत्य हो जाए। एक equation in two variables के सामान्यतः कई solutions हो सकते हैं।',example:'2x+y=6 में (1,4), (2,2) और (3,0) solutions हैं।',visual:{type:'compare',title:'एक equation, कई solutions',items:['(1,4) → 2(1)+4=6','(2,2) → 2(2)+2=6','(3,0) → 2(3)+0=6']}},
    {type:'example',title:'Solution को verify करें',body:'जाँचने का सबसे सुरक्षित तरीका है x और y की values equation में substitute करना।',visual:{type:'steps',title:'Verification recipe',items:['ordered pair लें','x और y substitute करें','दोनों sides simplify करें','बराबर आए → solution']}},
    {type:'concept',title:'Table of values',body:'कुछ सुविधाजनक x-values चुनकर corresponding y-values निकालने से graph बनाने के लिए points मिलते हैं।',example:'x+y=5 में x=0,1,2 लेने पर y=5,4,3 मिलता है।',visual:{type:'table',title:'Value pairs',items:['x=0 → y=5','x=1 → y=4','x=2 → y=3']}},
    {type:'concept',title:'Graph का विचार',body:'Equation के हर solution को coordinate plane पर एक point के रूप में plot किया जा सकता है। एक linear equation के सभी points मिलकर एक straight line बनाते हैं।',visual:{type:'grid',title:'Equation → graph',items:['solutions','points','straight line']}},
    {type:'concept',title:'Slope-intercept form',body:'Equation को y=mx+c के रूप में लिखा जा सकता है। यहाँ m slope और c y-intercept बताता है।',points:['y=2x+3 में m=2 और c=3।','c बताता है कि line y-axis को कहाँ काटती है।','m बताता है कि x में 1 की वृद्धि पर y कितनी बदलती है।'],visual:{type:'equation',title:'y = mx + c',items:['m = slope','c = y-intercept','y = mx + c']}},
    {type:'example',title:'Line का slope समझें',body:'y=3x+1 में slope 3 है। इसका अर्थ है कि x एक unit बढ़े तो y तीन units बढ़ता है।',visual:{type:'steps',title:'Slope पढ़ें',items:['equation: y=3x+1','m=3','x +1 → y +3','y-intercept = 1']}},
    {type:'concept',title:'दो रैखिक समीकरणों का युग्म',body:'जब दो linear equations को एक साथ देखा जाता है, तो उनका common ordered pair दोनों equations को satisfy करता है।',example:'x+y=5 और x−y=1 में common solution (3,2) है।'},
    {type:'concept',title:'Graphical solution',body:'दो lines के graph को plot करने पर उनका intersection point दोनों equations का common solution देता है।',visual:{type:'compare',title:'दो lines और solution',items:['1 intersection → एक solution','parallel lines → कोई common solution नहीं','same line → अनंत solutions']}},
    {type:'concept',title:'Consistency की शुरुआती समझ',body:'यदि pair का कम-से-कम एक common solution है तो pair consistent कहलाता है। यदि कोई common solution नहीं है तो inconsistent होता है।',points:['एक intersection → unique solution','same line → infinitely many solutions','parallel distinct lines → no solution']},
    {type:'example',title:'Substitution method',body:'एक equation से एक variable को दूसरे के रूप में लिखें और उसे दूसरी equation में substitute करें।',visual:{type:'steps',title:'Substitution',items:['एक variable isolate करें','दूसरी equation में substitute करें','एक variable solve करें','पहले equation में वापस रखें']}},
    {type:'example',title:'Substitution का worked example',body:'x+y=7 और x−y=1 से पहली equation x=7−y देती है। इसे दूसरी में रखने पर 7−y−y=1 ⇒ 2y=6 ⇒ y=3, फिर x=4।',visual:{type:'equation',title:'Solution',items:['x=7−y','7−2y=1','y=3','x=4']}},
    {type:'example',title:'Elimination method',body:'दोनों equations को जोड़ने या घटाने के लिए terms को इस तरह व्यवस्थित करें कि एक variable cancel हो जाए।',visual:{type:'steps',title:'Elimination',items:['equations align करें','एक variable के coefficients match करें','add/subtract करें','बचा variable solve करें']}},
    {type:'example',title:'Elimination का worked example',body:'2x+y=8 और 2x−y=4 को जोड़ने पर 4x=12, इसलिए x=3। पहली equation में रखने पर y=2।',visual:{type:'equation',title:'Eliminate करके हल',items:['2x+y=8','2x−y=4','4x=12 → x=3','y=2']}},
    {type:'concept',title:'Daily-life modelling',body:'Fixed charge + प्रति unit charge जैसे संबंध linear equation बना सकते हैं। Variables को स्पष्ट रूप से define करना सबसे पहला कदम है।',example:'₹200 fixed + ₹50 प्रति match ⇒ C=200+50m।',visual:{type:'flow',title:'Model बनाना',items:['quantity तय करें','fixed part','variable rate','equation']}},
    {type:'concept',title:'Graph और table से सोचें',body:'Equation, table और graph एक ही संबंध के तीन रूप हैं। एक रूप से दूसरे रूप में बदलना concept को मजबूत करता है।',visual:{type:'nested',title:'तीन representations',items:['Equation','↕','Table','↕','Graph']}},
    {type:'concept',title:'सामान्य गलतियाँ',body:'सबसे सामान्य गलतियाँ हैं ordered pair का क्रम बदलना, negative sign छोड़ देना, slope को intercept समझना और substitution में bracket गलत लगाना।',points:['(x,y) में x पहले है।','−2x का sign ध्यान से रखें।','y=mx+c में m slope और c intercept है।','Substitution में पूरे expression को bracket में रखें।']},
    {type:'check',title:'त्वरित जाँच 1',question:'2x+y=7 में x=2 होने पर y क्या होगा?',options:['2','3','4','5'],answer:1,explain:'2(2)+y=7 ⇒ 4+y=7 ⇒ y=3।'},
    {type:'check',title:'त्वरित जाँच 2',question:'y=4x−3 में slope क्या है?',options:['−3','3','4','7'],answer:2,explain:'y=mx+c में m slope होता है। यहाँ m=4।'}
  ]
};
