import React,{useMemo,useState} from 'react';
import {chapter10Practice} from './chapter10Practice';

const challenge=[
 {q:'किसी वृत्त की त्रिज्या 13 cm है और एक जीवा की केंद्र से दूरी 5 cm है। जीवा की लंबाई कितनी होगी?',options:['10 cm','12 cm','24 cm','26 cm'],answer:2,explain:'केंद्र से जीवा के मध्यबिंदु तक 5 cm है। आधी जीवा = √(13²−5²)=12 cm, इसलिए पूरी जीवा = 24 cm।'},
 {q:'एक ही वृत्त में दो जीवाओं की लंबाई बराबर है। पहली जीवा की केंद्र से दूरी 7 cm है। दूसरी जीवा की दूरी क्या होगी?',options:['5 cm','7 cm','14 cm','निर्धारित नहीं'],answer:1,explain:'एक ही वृत्त में बराबर जीवाएँ केंद्र से समान दूरी पर होती हैं।'},
 {q:'एक वृत्त की दो जीवाओं की केंद्र से दूरियाँ 6 cm और 8 cm हैं। कौन-सी जीवा बड़ी होगी?',options:['8 cm दूरी वाली','6 cm दूरी वाली','दोनों बराबर','निर्धारित नहीं'],answer:1,explain:'केंद्र के पास वाली जीवा बड़ी होती है। इसलिए 6 cm दूरी वाली जीवा बड़ी होगी।'},
 {q:'किसी जीवा की लंबाई 24 cm है और केंद्र से उसकी दूरी 5 cm है। वृत्त की त्रिज्या 13 cm है। यह जीवा संभव क्यों है?',options:['क्योंकि 12²+5²=13²','क्योंकि 24+5=13','क्योंकि 12+5=13','क्योंकि 24²−5²=13'],answer:0,explain:'आधी जीवा 12 cm है। समकोण त्रिभुज में 12²+5²=144+25=169=13²।'},
 {q:'यदि केंद्र से किसी जीवा पर खींचा गया लंब जीवा को समद्विभाजित करता है, तो इसके विलोम में क्या कहा जा सकता है?',options:['जीवा का मध्यबिंदु केंद्र से जोड़ने पर जीवा पर लंब मिलता है','जीवा व्यास नहीं है','त्रिज्या शून्य है','चाप आधी हो जाती है'],answer:0,explain:'जीवा के मध्यबिंदु को केंद्र से जोड़ने पर प्राप्त रेखाखंड जीवा पर लंब होता है।'}
];
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function CirclesEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const questions=useMemo(()=>isTest?shuffle(chapter10Practice).slice(0,15):mode==='challenge'?challenge:chapter10Practice,[mode,isTest]);
 const[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index],points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points)}}};
 const next=()=>{if(selected===null||!current)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">वृत्त • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0)}}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">गणित • वृत्त</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className="question-actions"><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>
}
