import React,{useMemo,useState} from 'react';
import {chapter11Practice} from './chapter11Practice';

const challenge=[
 {q:'एक विद्यार्थी को 8 cm रेखाखंड का लंब समद्विभाजक बनाना है। यदि चापों की त्रिज्या 4 cm रखी जाए, तो क्या दो अलग प्रतिच्छेद बिंदु मिलेंगे?',options:['नहीं, क्योंकि त्रिज्या ठीक आधी होने पर अलग प्रतिच्छेद नहीं बनते','हाँ, हमेशा','केवल 90° में','केवल 60° में'],answer:0,explain:'दोनों सिरों से समान त्रिज्या की चापों के अलग-अलग प्रतिच्छेद के लिए त्रिज्या 4 cm से अधिक होनी चाहिए। ठीक 4 cm पर चापें एक ही बिंदु पर मिल सकती हैं।'},
 {q:'किसी कोण की दोनों भुजाओं को पहली चाप P और Q पर काटती है। P और Q से समान त्रिज्या की चापें R पर मिलती हैं। R को शीर्ष से मिलाने पर क्या मिलेगा?',options:['कोण का समद्विभाजक','हमेशा मध्यबिंदु','हमेशा समकोण','कोई निश्चित रेखा नहीं'],answer:0,explain:'P और Q से समान त्रिज्या की चापों का प्रतिच्छेद R दोनों भुजाओं से सममित स्थिति बनाता है। शीर्ष को R से जोड़ने पर कोण का समद्विभाजक प्राप्त होता है।'},
 {q:'तीन दी गई भुजाओं में सबसे बड़ी भुजा 10 cm तथा दूसरी दो 4 cm और 5 cm हैं। चापें क्यों नहीं मिलेंगी?',options:['क्योंकि 4+5<10 है','क्योंकि 4+5=10 है','क्योंकि 10 सबसे बड़ी है','क्योंकि सभी भुजाएँ धनात्मक हैं'],answer:0,explain:'त्रिभुज के लिए किसी भी दो भुजाओं का योग तीसरी भुजा से बड़ा होना चाहिए। यहाँ 9<10 है, इसलिए ऐसा त्रिभुज नहीं बन सकता।'},
 {q:'एक आधार AB के दोनों सिरों पर 50° और 60° के कोण बनाकर दो किरणें खींची जाती हैं। तीसरा शीर्ष T मिलता है। ∠T कितना होगा?',options:['60°','70°','80°','90°'],answer:1,explain:'त्रिभुज के कोणों का योग 180° होता है। 180°−50°−60°=70°।'},
 {q:'यदि सहायक चापों की त्रिज्या बदली गई, लेकिन अंतिम रचना की सभी आवश्यक शर्तें फिर भी पूरी होती हैं, तो क्या रचना आवश्यक रूप से गलत है?',options:['नहीं, आवश्यक है कि अंतिम निर्माण की सभी शर्तें पूरी हों','हाँ, हमेशा','केवल समकोण में','केवल समबाहु त्रिभुज में'],answer:0,explain:'सहायक चाप का आकार परिस्थितिनुसार बदल सकता है। जहाँ समान दूरी की शर्त है वहाँ संबंधित चापों की त्रिज्या समान रखना आवश्यक है, और अंतिम निर्माण को सभी दी गई शर्तें पूरी करनी चाहिए।'}
];

function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}

export function ConstructionsEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const questions=useMemo(()=>isTest?shuffle(chapter11Practice).slice(0,15):mode==='challenge'?challenge:chapter11Practice,[mode,isTest]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index];
 const points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points);}}};
 const next=()=>{if(selected===null)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null);}};
 const reset=()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0);};
 if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">रचनाएँ • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={reset}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">गणित • रचनाएँ</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className="question-actions"><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>;
}
