import React,{useMemo,useState} from 'react';
import {chapter5Practice} from './chapter5Practice';

const challenge=[
 {q:'किसी कथन को theorem बनाने के लिए सबसे आवश्यक बात क्या है?',options:['सुंदर diagram','तार्किक proof','याद करना','calculator'],answer:1,explain:'Theorem वह कथन है जिसे उपलब्ध definitions, axioms, postulates और reasoning से logically prove किया जाता है।'},
 {q:'कौन-सा कथन भूमिका का सही क्रम दिखाता है?',options:['Theorem → definition → axiom','Definition → accepted foundations → reasoning → theorem','Diagram → marks → theorem','Example → axiom → definition'],answer:1,explain:'परिभाषाएँ और accepted foundations आगे की reasoning का आधार बनती हैं, जिससे theorem सिद्ध होती है।'},
 {q:'दो parallel lines को transversal काटती है। कौन-सा विचार इनके संबंध को पहचानने में सबसे उपयोगी है?',options:['angle relationships','circle area','square root','coordinate midpoint'],answer:0,explain:'Parallel lines और transversal के साथ बनने वाले angle relationships geometry में मुख्य संकेत देते हैं।'},
 {q:'यदि किसी छात्र ने केवल तीन specific examples देखकर किसी universal theorem को “सिद्ध” कर दिया, तो कमी क्या है?',options:['examples की संख्या कम है','general logical proof नहीं दिया गया','diagram छोटा है','formula नहीं है'],answer:1,explain:'Examples pattern दिखा सकते हैं, पर सामान्य theorem की validity के लिए general proof चाहिए।'},
 {q:'यदि एक student postulate को theorem कहता है, तो कौन-सा distinction छूट रहा है?',options:['postulate foundation है, theorem derived and proved statement है','theorem foundation है','दोनों हमेशा identical हैं','postulate केवल example है'],answer:0,explain:'Postulate accepted starting point है; theorem reasoning से निकला और सिद्ध किया गया कथन है।'},
 {q:'किस स्थिति में “चित्र देखकर बराबर लग रहा है” पर्याप्त नहीं है?',options:['जब सामान्य mathematical claim prove करना हो','जब notebook सजानी हो','जब title लिखना हो','जब point label करना हो'],answer:0,explain:'Diagram intuition देता है; general claim के लिए logical justification चाहिए।'},
 {q:'किसी proof में “क्यों?” पूछने की आदत किस skill को मजबूत करती है?',options:['rote memory','logical reasoning','handwriting','speed only'],answer:1,explain:'“क्यों?” हर step के पीछे rule या accepted fact खोजने की आदत डालता है।'},
 {q:'यदि AB और CD दोनों 90° के angles हैं, तो Chapter 5 की foundation के अनुसार क्या कहा जा सकता है?',options:['वे बराबर हैं','एक छोटा है','एक obtuse है','कुछ नहीं'],answer:0,explain:'यूक्लिड के चौथे postulate के अनुसार सभी right angles एक-दूसरे के बराबर होते हैं।'},
 {q:'दो points A और B दिए हों। उनके बीच straight segment बनाना किस basic idea से मेल खाता है?',options:['पहला postulate','तीसरा postulate','चौथा postulate','पाँचवाँ postulate'],answer:0,explain:'पहला postulate दो points को join करने वाली straight line बनाने की बात करता है।'},
 {q:'किस कथन से Euclid की approach का सबसे अच्छा सार निकलता है?',options:['पहले conclusion, बाद में कारण','पहले foundations, फिर systematic reasoning','सिर्फ diagrams','सिर्फ formulas'],answer:1,explain:'यूक्लिडीय approach व्यवस्थित foundations से शुरू होकर reasoning और proofs तक जाती है।'}
];
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function EuclidEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const base=chapter5Practice;
 const questions=useMemo(()=>isTest?shuffle(base).slice(0,15):mode==='challenge'?challenge:base,[mode,isTest]);
 const[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index],points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points)}}};
 const next=()=>{if(selected===null||!current)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">यूक्लिड की ज्यामिति • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0)}}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">गणित • यूक्लिड की ज्यामिति</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className="question-actions"><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>
}
