import React from 'react';

export function HindiGenericLearn({lesson,onBack,onModeComplete}){
  if(!lesson)return null;
  const list=(value)=>Array.isArray(value)?value.filter(Boolean):[];
  const pairs=(value)=>list(value).filter(x=>Array.isArray(x)&&x.length>=2);
  const people=list(lesson.characters||lesson.people);
  return <div className="hindi-learn hindi-chapter1-learn">
    <div className="hindi-learn-banner"><span>{lesson.eyebrow||'गोधूली भाग 1 · गद्य'}</span><h2>{lesson.title}</h2><p>{lesson.intro||lesson.overview}</p>{lesson.author&&<div className="hindi-topic-author">✦ {lesson.author}</div>}</div>
    <div className="hindi-ch1-callout"><strong>केंद्रीय बात</strong><p>{lesson.overview||'इस पाठ के मुख्य विचार, संदर्भ और संदेश को क्रम से समझें।'}</p></div>
    {lesson.authorNote&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>👤 लेखक परिचय</h3><span>पाठ की दृष्टि समझें</span></div><p>{lesson.authorNote}</p></section>}
    <section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>📖 पाठ को क्रम से समझें</h3><span>{list(lesson.sections).length} सीखने के पड़ाव</span></div><div className="hindi-learn-grid">{list(lesson.sections).map((item,i)=><section id={`hindi-generic-section-${i}`} key={`${item.title}-${i}`}><h3>{item.title}</h3><p>{item.body}</p>{item.deep&&<div className="hindi-ch1-callout"><strong>🔎 गहराई</strong><p>{item.deep}</p></div>}{item.example&&<div className="hindi-ch1-callout"><strong>🌍 उदाहरण</strong><p>{item.example}</p></div>}{item.exam&&<div className="hindi-ch1-callout"><strong>🎯 परीक्षा संकेत</strong><p>{item.exam}</p></div>}</section>)}</div></section>
    {pairs(lesson.timeline||lesson.storyMap||lesson.waterWisdom||lesson.thesis).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>🧭 विचार-क्रम</h3><span>मुख्य बात कैसे आगे बढ़ती है?</span></div><div className="hindi-ch1-story-map">{pairs(lesson.timeline||lesson.storyMap||lesson.waterWisdom||lesson.thesis).map(([title,body],i)=><article key={`${title}-${i}`}><b>{i+1}</b><div><strong>{title}</strong><p>{body}</p></div></article>)}</div></section>}
    {people.length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>👥 प्रमुख व्यक्ति और संदर्भ</h3><span>कौन · भूमिका · महत्व</span></div><div className="hindi-ch1-characters">{people.map((item,i)=>{const name=item.name||item[0];const role=item.role||item[1];const note=item.note||item[2];return <article key={`${name}-${i}`}><strong>{name}</strong>{role&&<span>{role}</span>}{note&&<p>{note}</p>}</article>})}</div></section>}
    {pairs(lesson.comparison).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>⚖️ तुलना से समझें</h3><span>मुख्य अंतर और संबंध</span></div><div className="hindi-ch1-two-col">{pairs(lesson.comparison).map(([title,a,b,c],i)=><article key={`${title}-${i}`}><strong>{title}</strong><p>{a}</p>{b&&<p><b>अर्थ:</b> {b}</p>}{c&&<p><b>प्रभाव:</b> {c}</p>}</article>)}</div></section>}
    {list(lesson.themes).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>🎯 मुख्य विचार</h3><span>दीर्घ उत्तरों में उपयोग करें</span></div><div className="hindi-ch1-chip-grid">{list(lesson.themes).map(x=><span key={x}>{x}</span>)}</div></section>}
    {pairs(lesson.literaryTools).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>🖊️ भाषा और साहित्यिक उपकरण</h3><span>लेखन की शैली पकड़ें</span></div><div className="hindi-ch1-two-col">{pairs(lesson.literaryTools).map(([title,body],i)=><article key={`${title}-${i}`}><strong>{title}</strong><p>{body}</p></article>)}</div></section>}
    {pairs(lesson.glossary).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>📚 शब्द-संग्रह</h3><span>महत्वपूर्ण शब्दों का अर्थ</span></div><div className="hindi-ch1-glossary">{pairs(lesson.glossary).map(([word,meaning],i)=><article key={`${word}-${i}`}><strong>{word}</strong><p>{meaning}</p></article>)}</div></section>}
    {pairs(lesson.answerFrameworks).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>✍️ उत्तर बनाने के ढाँचे</h3><span>लघु और दीर्घ उत्तर की दिशा</span></div><div className="hindi-ch1-frameworks">{pairs(lesson.answerFrameworks).map(([question,template],i)=><article key={`${question}-${i}`}><strong>{question}</strong><p>{template}</p></article>)}</div></section>}
    {list(lesson.examChecklist).length>0&&<section className="hindi-ch1-panel"><div className="hindi-ch1-panel-head"><h3>✅ परीक्षा checklist</h3><span>Final test से पहले</span></div><ul>{list(lesson.examChecklist).map(x=><li key={x}>{x}</li>)}</ul></section>}
    <div className="hindi-actions"><button type="button" className="secondary-btn pressable" onClick={onBack}>← पीछे</button><button type="button" className="primary-btn pressable" onClick={()=>onModeComplete?.('learn')}>✓ सीखना पूरा करें • +20 XP</button></div>
  </div>;
}
