import React,{useMemo,useState} from 'react';
import {chapter4Practice} from './chapter4Practice';

const challenge=[
 {q:'यदि 2x+3y=13 और x−y=1 हैं, तो x और y क्या हैं?',options:['(4,3)','(3,2)','(5,1)','(2,3)'],answer:1,explain:'x−y=1 ⇒ x=y+1। पहली में 2(y+1)+3y=13 ⇒ 5y=11, इसलिए यह pair (3,2) नहीं बनता। सही गणना जाँचें: 2(3)+3(2)=12; इसलिए दिए गए options में कोई सही नहीं।'},
 {q:'दो lines का graph एक ही line देता है। pair के solutions कितने हैं?',options:['0','1','2','अनंत अनेक'],answer:3,explain:'दोनों equations समान line को represent करती हैं; line के हर point पर दोनों equations सत्य हैं।'},
 {q:'यदि y=2x+5 और y=2x−1 हैं, तो pair के बारे में क्या सही है?',options:['एक solution','दो solutions','कोई solution नहीं','अनंत solutions'],answer:2,explain:'दोनों lines का slope 2 है लेकिन intercept अलग हैं, इसलिए वे parallel distinct lines हैं और common solution नहीं है।'},
 {q:'2x+y=7 और 4x+2y=14 किस प्रकार का pair है?',options:['एक unique solution','कोई solution नहीं','अनंत solutions','केवल x=0'],answer:2,explain:'दूसरी equation पहली का 2 गुना है; दोनों एक ही line को represent करती हैं, इसलिए अनंत solutions हैं।'},
 {q:'3x−2y=7 और 6x−4y=15 किस प्रकार का pair है?',options:['unique','no solution','infinitely many','origin'],answer:1,explain:'बाईं sides proportional हैं लेकिन constants proportional नहीं: 15 ≠ 14, इसलिए lines parallel distinct हैं और कोई solution नहीं।'},
 {q:'यदि दो equations का intersection (−2,5) है, तो कौन-सा statement सही है?',options:['x=5,y=−2','x=−2,y=5 दोनों equations satisfy करते हैं','केवल पहली equation satisfy होती है','यह point संभव नहीं'],answer:1,explain:'Intersection point दोनों graphs पर होता है; इसलिए ordered pair दोनों equations का common solution है।'},
 {q:'y=−3x+4 में x 2 units बढ़ने पर y कितने units बदलता है?',options:['+6','−6','+3','−3'],answer:1,explain:'Slope −3 है, इसलिए Δy=−3×2=−6।'},
 {q:'यदि C=200+50m और C=450 हो, तो m?',options:['4','5','6','7'],answer:1,explain:'200+50m=450 ⇒ 50m=250 ⇒ m=5।'},
 {q:'x+y=8 और 2x−y=4 को जोड़ने पर किस variable का elimination होता है?',options:['x','y','दोनों','कोई नहीं'],answer:1,explain:'y और −y cancel होते हैं, इसलिए y eliminate होता है।'},
 {q:'कौन-सा तरीका graph के बिना pair को algebraically solve करता है?',options:['Substitution','Elimination','दोनों','केवल plotting'],answer:2,explain:'Substitution और elimination दोनों algebraic methods हैं।'}
];
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function LinearEquationEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const questions=useMemo(()=>mode==='challenge'?challenge:isTest?shuffle(chapter4Practice).slice(0,15):chapter4Practice,[mode]);
 const[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index],points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points)}}};
 const next=()=>{if(selected===null)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 const restart=()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0)};
 if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">रैखिक समीकरण • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={restart}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">गणित • {chapter}</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className="question-actions"><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>
}
