import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {getChapterContent} from './chapterContent';
import {StudyEngine} from './StudyEngine';
import {LearningEngine} from './LearningEngine';

const subjects=[
 {id:'math',name:'गणित',icon:'∑',desc:'संख्या, बीजगणित, ज्यामिति और तर्क',chapters:['संख्या पद्धति और बहुपद']},
 {id:'science',name:'विज्ञान',icon:'⚗',desc:'भौतिकी, रसायन और जीव विज्ञान',chapters:['हमारे आसपास के पदार्थ']},
 {id:'hindi',name:'हिन्दी',icon:'अ',desc:'गद्य, पद्य, भाषा और लेखन',chapters:['कहानी के प्लॉट–1']},
 {id:'sst',name:'सामाजिक विज्ञान',icon:'◎',desc:'इतिहास, भूगोल, नागरिक शास्त्र और अर्थशास्त्र',chapters:['भौगोलिक खोजें–भाग 1']},
 {id:'sanskrit',name:'संस्कृत',icon:'ॐ',desc:'पाठ, व्याकरण और अभ्यास',chapters:['ईशस्तुति']},
 {id:'english',name:'अंग्रेज़ी',icon:'A',desc:'पाठ, grammar, vocabulary और writing',chapters:['व्याकरण, काल और शब्दावली']},
 {id:'reasoning',name:'तर्कशक्ति',icon:'?',desc:'तर्क, पैटर्न और समस्या समाधान',chapters:['उन्नत तर्कशक्ति']}
];
const XP_PER_LEVEL=250, initial={xp:0,streak:1,dailyXp:0,goal:100,sessions:[]};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
function App(){
 const[page,setPage]=useState('home'),[subject,setSubject]=useState(null),[chapter,setChapter]=useState(null),[progress,setProgress]=useState(()=>load('class9-progress',initial)),[tutor,setTutor]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem('class9-progress',JSON.stringify(progress)),[progress]);
 const addXp=n=>{setProgress(p=>({...p,xp:p.xp+n,dailyXp:Math.min(p.goal,p.dailyXp+n)}));setToast(`+${n} XP`);setTimeout(()=>setToast(''),1200)};
 const finishSession=m=>setProgress(p=>({...p,sessions:[...(p.sessions||[]),m].slice(-100)}));
 const openSubject=s=>{setSubject(s);setPage('subject')}; const openChapter=c=>{setChapter(c);setPage('chapter')};
 if(page==='classes')return <Classes back={()=>setPage('home')} open={openSubject}/>;
 if(page==='subject')return <SubjectPage subject={subject} back={()=>setPage('classes')} open={openChapter}/>;
 if(page==='chapter')return <ChapterPage subject={subject} chapter={chapter} back={()=>setPage('subject')} addXp={addXp} finishSession={finishSession}/>;
 if(page==='tests')return <Tests back={()=>setPage('home')} start={(s,c)=>{setSubject(s);setChapter(c);setPage('chapter')}}/>;
 if(page==='meter')return <Meter progress={progress} back={()=>setPage('home')}/>;
 if(page==='mistakes')return <Mistakes back={()=>setPage('home')}/>;
 return <Home progress={progress} setPage={setPage} addXp={addXp} tutor={tutor} setTutor={setTutor} toast={toast}/>;
}
function Home({progress,setPage,addXp,tutor,setTutor,toast}){const level=Math.floor(progress.xp/XP_PER_LEVEL)+1,pct=Math.round(progress.xp%XP_PER_LEVEL/XP_PER_LEVEL*100);return <main className="app-shell"><nav className="topbar"><strong className="brand">पढ़ाई</strong><span className="nav-class">कक्षा 9</span><div className="top-stats"><span>🔥 {progress.streak} दिन</span><span>⚡ {progress.xp} XP</span><span>LVL {level}</span></div><button className="tutor-mini pressable" onClick={()=>setTutor(true)}>✦ Smart Tutor</button></nav><header className="hero"><div className="hero-inner"><div className="badge">कक्षा 9 • STUDY SPACE</div><h1>आज की पढ़ाई शुरू करें।</h1><p>ध्यान से पढ़ें, अभ्यास करें और हर कदम पर XP कमाएँ।</p></div></header><section className="dashboard"><div className="progress-strip"><div className="level-badge"><span>LVL</span><strong>{level}</strong></div><div className="level-copy"><div className="level-title"><strong>आपकी सीखने की ऊर्जा</strong><span>{progress.xp%XP_PER_LEVEL} / {XP_PER_LEVEL} XP</span></div><div className="progress-track"><span style={{width:`${pct}%`}}/></div><small>अगले लेवल तक आपकी प्रगति</small></div><div className="daily-goal"><strong>{progress.dailyXp} XP</strong><span>आज का लक्ष्य {progress.goal}</span></div></div><div className="section-heading"><div><span className="eyebrow">कक्षा 9</span><h2>अध्ययन सुविधाएँ</h2></div><span className="focus-label">🎯 Focus Mode</span></div><div className="offering-grid"><button className="offering-card pressable" onClick={()=>setPage('classes')}><span className="offering-icon">▣</span><span className="offering-copy"><strong>सभी कक्षाएँ</strong><small>सभी विषय और अध्याय देखें</small></span><span>›</span></button><button className="offering-card pressable" onClick={()=>setPage('tests')}><span className="offering-icon">✎</span><span className="offering-copy"><strong>सभी टेस्ट</strong><small>अध्याय और मॉडल टेस्ट दें</small></span><span>›</span></button><button className="offering-card pressable" onClick={()=>setPage('meter')}><span className="offering-icon">◔</span><span className="offering-copy"><strong>तैयारी मीटर</strong><small>अपनी वास्तविक तैयारी देखें</small></span><span>›</span></button></div><section className="study-nudge"><div><span className="nudge-icon">⚡</span><div><strong>आज का छोटा मिशन</strong><p>एक focused session शुरू करें और 25 XP कमाएँ।</p></div></div><button className="secondary-btn pressable" onClick={()=>addXp(25)}>+25 XP</button></section><button className="tutor-banner pressable" onClick={()=>setTutor(true)}><span>🤖</span><div><strong>स्मार्ट ट्यूटर AI</strong><small>सवाल पूछें, concepts समझें और study plan बनाएँ।</small></div><b>पूछें →</b></button>{(progress.sessions||[]).length>0&&<button className="review-link pressable" onClick={()=>setPage('mistakes')}>📕 मेरी गलतियाँ देखें</button>}</section>{toast&&<div className="xp-toast">⚡ {toast}</div>}{tutor&&<Tutor close={()=>setTutor(false)} earn={()=>addXp(5)}/>}</main>}
function Classes({back,open}){return <Simple title="सभी कक्षाएँ" back={back}><div className="subject-grid">{subjects.map((s,i)=><button className="subject-tile pressable" key={s.id} onClick={()=>open(s)}><span className="subject-icon">{s.icon}</span><span className="subject-index">{String(i+1).padStart(2,'0')}</span><strong>{s.name}</strong><small>{s.desc}</small><b>अध्याय देखें →</b></button>)}</div></Simple>}
function SubjectPage({subject,back,open}){return <Simple title={subject.name} back={back}><p className="page-lead">{subject.desc}</p><div className="chapter-grid">{subject.chapters.map((c,i)=>{const d=getChapterContent(subject.name,c);return <button className="chapter-card pressable" key={c} onClick={()=>open(c)}><span className="chapter-no">अध्याय {i+1}</span><strong>{c}</strong><small>{d?.goal||'अध्याय अध्ययन सामग्री'}</small><div className="chapter-actions"><span>📖 सीखें</span><span>📝 अभ्यास</span><span>🔥 चुनौती</span><span>🎯 टेस्ट</span></div><b>खोलें →</b></button>})}</div></Simple>}
function ChapterPage({subject,chapter,back,addXp,finishSession}){const[mode,setMode]=useState(null),data=getChapterContent(subject.name,chapter);if(mode==='learn')return <LearningEngine subject={subject} chapter={chapter} data={data} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;if(mode)return <StudyEngine subject={subject} chapter={chapter} mode={mode} onBack={()=>setMode(null)} addXp={addXp}/>;return <Simple title={chapter} back={back}><div className="chapter-hero-card"><span>📚</span><div><strong>{subject.name}</strong><small>{data?.goal}</small></div></div><div className="mode-grid">{[['learn','📖','सीखें','concepts, उदाहरण और quick check'],['practice','📝','अभ्यास','सीखी हुई बातों पर प्रश्न'],['challenge','🔥','चुनौती','कठिन और सोचने वाले प्रश्न'],['test','🎯','टेस्ट','समयबद्ध परीक्षा']].map(([id,ic,t,d])=><button className="mode-card pressable" key={id} onClick={()=>setMode(id)}><span className="mode-icon">{ic}</span><strong>{t}</strong><span>{d}</span><b>→</b></button>)}</div></Simple>}
function Tests({back,start}){return <Simple title="सभी टेस्ट" back={back}><div className="class-list">{['अध्याय टेस्ट','मिश्रित अभ्यास टेस्ट','मॉडल टेस्ट'].map((x,i)=>{const s=subjects[i%subjects.length];return <button className="list-card pressable" key={x} onClick={()=>start(s,s.chapters[0])}><span>0{i+1}</span><div><strong>{x}</strong><small>{s.name} • शुरू करें</small></div><b>→</b></button>})}</div></Simple>}
function Meter({progress,back}){const ss=progress.sessions||[],learn=ss.filter(s=>s.mode==='learn'&&s.completed).length,attempted=ss.reduce((n,s)=>n+(s.attempted||0),0),correct=ss.reduce((n,s)=>n+(s.correct||0),0),accuracy=attempted?Math.round(correct/attempted*100):0,readiness=Math.min(100,Math.round(learn*12+accuracy*.48+Math.min(100,progress.xp/40)*.4));return <Simple title="तैयारी मीटर" back={back}><div className="meter-box"><div className="meter-ring"><span>{readiness}%</span></div><h2>{readiness>=80?'बहुत अच्छी तैयारी':readiness>=50?'अच्छी प्रगति':'अभी और अभ्यास करें'}</h2><p>यह score learning completion, अभ्यास/test accuracy और XP activity से बन रहा है।</p><div className="meter-stats"><span>📖 {learn} lessons</span><span>🎯 {accuracy}% accuracy</span><span>⚡ {progress.xp} XP</span></div></div></Simple>}
function Mistakes({back}){const[items,setItems]=useState(()=>load('class9-mistakes',[])),[open,setOpen]=useState(null);if(open)return <Simple title="गलती समीक्षा" back={()=>setOpen(null)}><div className="review-card"><span className="lesson-type">{open.subject} • {open.chapter}</span><h2>{open.question}</h2><div className="review-row wrong-row"><strong>आपका उत्तर</strong><span>{open.options[open.selected]}</span></div><div className="review-row correct-row"><strong>सही उत्तर</strong><span>{open.options[open.answer]}</span></div><div className="review-explain"><strong>क्यों सही है?</strong><p>{open.explain}</p></div><button className="primary-btn pressable" onClick={()=>setOpen(null)}>समझ गया ✓</button></div></Simple>;return <Simple title="📕 मेरी गलतियाँ" back={back}><div className="review-toolbar"><div><strong>{items.length}</strong><span>सहेजे गए गलत प्रश्न</span></div>{items.length>0&&<button className="secondary-btn pressable" onClick={()=>{localStorage.removeItem('class9-mistakes');setItems([])}}>सब साफ करें</button>}</div>{items.length===0?<div className="empty-review"><span>🎉</span><h2>अभी कोई गलती नहीं</h2><p>Practice या Test में गलत उत्तर देने पर प्रश्न यहाँ आएँगे।</p></div>:<div className="review-list">{items.map((x,i)=><button className="review-item pressable" key={x.id||i} onClick={()=>setOpen(x)}><span className="review-no">{i+1}</span><div><strong>{x.question}</strong><small>आपका: {x.options[x.selected]} • सही: {x.options[x.answer]}</small></div><b>समझें →</b></button>)}</div>}</Simple>}
function Tutor({close,earn}){const[answer,setAnswer]=useState('');const ask=q=>{earn();setAnswer(q.includes('गणित')?'गणित में पहले अवधारणा पढ़ें, फिर solved example और अंत में बिना मदद के 5 practice questions करें।':'आज 25 मिनट focused study करें: 15 मिनट सीखें, 10 मिनट अभ्यास करें और अंत में गलतियों को review करें।')};return <div className="tutor-backdrop" onClick={close}><aside className="tutor-panel" onClick={e=>e.stopPropagation()}><div className="tutor-head"><div><strong>Smart Tutor AI</strong><small>आपकी पढ़ाई का साथी</small></div><button onClick={close}>×</button></div><div className="tutor-body"><div className="tutor-message"><strong>नमस्ते! 👋</strong><p>मैं concepts और study planning में मदद कर सकता हूँ।</p></div>{answer&&<div className="tutor-answer">{answer}</div>}{['मुझे आज क्या पढ़ना चाहिए?','गणित समझाओ','मेरा टेस्ट प्लान बनाओ'].map(q=><button className="suggestion pressable" key={q} onClick={()=>ask(q)}>{q}</button>)}</div><div className="tutor-foot"><input placeholder="अपना सवाल लिखें..." onKeyDown={e=>e.key==='Enter'&&e.currentTarget.value&&ask(e.currentTarget.value)}/><button className="send-btn pressable" onClick={e=>{const i=e.currentTarget.previousSibling;if(i.value)ask(i.value)}}>→</button></div></aside></div>}
function Simple({title,back,children}){return <main className="page"><header className="page-header"><button className="pressable" onClick={back}>← वापस</button><div className="badge">कक्षा 9 • लर्निंग हब</div><h1>{title}</h1></header><section className="page-content">{children}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);
