import React,{lazy,Suspense,useEffect,useState}from'react';
import { createRoot } from 'react-dom/client';
import AppWithChapter5 from './AppWithChapter5.jsx';
import TestCentreSafe from './TestCentreSafe.jsx';
import PreparationMeterPage from './PreparationMeterPage.jsx';
import EnglishGenericLanguageSkillsQuiz from './english/EnglishGenericLanguageSkillsQuiz.jsx';
import EnglishLanguageSkillsPhase2Assessment from './english/EnglishLanguageSkillsPhase2Assessment.jsx';
import EnglishCompositionTopic from './english/EnglishCompositionTopic.jsx';
import EnglishTranslationTopicComplete from './english/EnglishTranslationTopicComplete.jsx';
import EnglishFormalLetterTopic from './english/EnglishFormalLetterTopic.jsx';
import EnglishInformalLetterTopic from './english/EnglishInformalLetterTopic.jsx';
import EnglishNoticeWritingTopic from './english/EnglishNoticeWritingTopic.jsx';
import EnglishReportWritingTopic from './english/EnglishReportWritingTopic.jsx';
import EnglishSpeechWritingTopic from './english/EnglishSpeechWritingTopic.jsx';
import EnglishSpeechWritingAssessment from './english/EnglishSpeechWritingAssessment.jsx';
import EnglishMessageWritingTopic from './english/EnglishMessageWritingTopic.jsx';
import EnglishMessageWritingAssessment from './english/EnglishMessageWritingAssessment.jsx';
import { AppErrorBoundary } from './AppErrorBoundary.jsx';
import SSTRoot from './sst/SSTRoot.jsx';
import {XPCompletionBoundary} from './XPCompletionBoundary.jsx';
import {XPAchievementOverlay} from './XPBadges.jsx';
import './scienceModeRouter.js';
import './subject-overrides.css';
import './home-premium.css';
import './science-navigation.css';
import './science-learn-navigator-fix.css';
import './sst/sst-section.css';
import './subject-progress-ui.js';

const APP_BUILD_VERSION=import.meta.env.VITE_BUILD_VERSION||'';
const BASE_URL=import.meta.env.BASE_URL||'/';
const ASSESSMENT_TOPICS=new Set(['agreement','narration','clauses','determiners','prepositions','idioms','translation','formal-letter','informal-letter','notice','report','speech','message','paragraph-essay','composition','factual-reading','literary-reading','poetry-reading']);
const KEEP_DEDICATED=new Set(['tenses','modals','voice','paragraph-essay','composition','translation','formal-letter','informal-letter','notice','report','speech','message']);
const PHASE2_LANGUAGE_BANK_TOPICS=new Set(['agreement','determiners','prepositions','idioms']);
function BuildVersionRefresh(){useEffect(()=>{if(!APP_BUILD_VERSION)return;let stopped=false;const checkOnce=async()=>{try{const base=BASE_URL.endsWith('/')?BASE_URL:`${BASE_URL}/`;const response=await fetch(`${base}build-version.json?hub_check=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache','Pragma':'no-cache'}});if(!response.ok||stopped)return;const data=await response.json();const remoteVersion=String(data?.version||'');if(remoteVersion&&remoteVersion!==APP_BUILD_VERSION){const next=new URL(window.location.href);next.searchParams.set('__hub_refresh',remoteVersion);window.location.replace(next.toString())}}catch{}};checkOnce();return()=>{stopped=true}},[]);return null;}
function FreshLanguageSkillsNavigation(){useEffect(()=>{const handler=event=>{const target=event.target?.closest?.('button,a');if(!target)return;const p=new URLSearchParams(window.location.search);if(p.get('subject')!=='english'||p.get('languageSkills')!=='1')return;const topic=p.get('topic');if(!topic||KEEP_DEDICATED.has(topic)||!ASSESSMENT_TOPICS.has(topic))return;const text=(target.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();let mode=null;if(text==='practice'||/^practice\b/.test(text))mode='practice';else if(text==='challenge'||/^challenge\b/.test(text))mode='challenge';else if(text==='final test'||/^final test\b/.test(text)||text.includes('final test'))mode='test';if(!mode)return;event.preventDefault();event.stopPropagation();const next=new URLSearchParams(p);next.set('topic',topic);next.set('mode',mode);next.set('languageSkills','1');next.set('subject','english');window.history.pushState({},'',`${window.location.pathname}?${next.toString()}${window.location.hash||''}`);window.dispatchEvent(new PopStateEvent('popstate'))};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[]);useEffect(()=>{const hideReading=()=>{const p=new URLSearchParams(window.location.search);if(p.get('subject')!=='english'||p.get('languageSkills')!=='1'||!p.get('topic'))return;document.querySelectorAll('.english-ls-grid > section').forEach(section=>{const heading=section.querySelector('h2');if(heading?.textContent?.trim()==='Reading')section.hidden=true})};const observer=new MutationObserver(hideReading);observer.observe(document.body,{childList:true,subtree:true});hideReading();return()=>observer.disconnect()},[]);return null;}
function readRoute(){const params=new URLSearchParams(window.location.search);return{subject:params.get('subject')||'',page:params.get('page')||'',topic:params.get('topic')||'',mode:params.get('mode')||'learn',languageSkills:params.get('languageSkills')==='1'}}
function exitLanguageSkills(){const params=new URLSearchParams();params.set('page','language-skills');params.set('subject','english');params.set('languageSkills','1');window.history.pushState({},'',`${window.location.pathname}?${params}${window.location.hash||''}`);window.dispatchEvent(new PopStateEvent('popstate'))}
function RootRouter(){const[route,setRoute]=useState(readRoute);useEffect(()=>{const sync=()=>setRoute(readRoute());window.addEventListener('popstate',sync);window.addEventListener('hashchange',sync);const timer=setInterval(sync,250);sync();return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('hashchange',sync);clearInterval(timer)}},[]);const isSST=route.subject==='sst'||route.page.startsWith('sst-');if(isSST)return <SSTRoot/>;if(route.page==='cbt')return <TestCentreSafe/>;if(route.page==='meter')return <PreparationMeterPage/>;const sharedProps={onBack:exitLanguageSkills,addXp:()=>{},finishSession:()=>{}};if(route.languageSkills&&route.topic==='composition')return <EnglishCompositionTopic onBack={exitLanguageSkills}/>;if(route.languageSkills&&route.topic==='paragraph-essay')return <EnglishCompositionTopic onBack={exitLanguageSkills}/>;if(route.languageSkills&&route.topic==='translation')return <EnglishTranslationTopicComplete onBack={exitLanguageSkills}/>;if(route.languageSkills&&route.topic==='formal-letter')return <EnglishFormalLetterTopic {...sharedProps}/>;if(route.languageSkills&&route.topic==='informal-letter')return <EnglishInformalLetterTopic {...sharedProps}/>;if(route.languageSkills&&route.topic==='notice')return <EnglishNoticeWritingTopic {...sharedProps}/>;if(route.languageSkills&&route.topic==='report')return <EnglishReportWritingTopic {...sharedProps}/>;if(route.languageSkills&&route.topic==='speech')return route.mode==='learn'?<EnglishSpeechWritingTopic {...sharedProps}/>:<EnglishSpeechWritingAssessment mode={route.mode} onBack={exitLanguageSkills} {...sharedProps}/>;if(route.languageSkills&&route.topic==='message')return route.mode==='learn'?<EnglishMessageWritingTopic {...sharedProps}/>:<EnglishMessageWritingAssessment mode={route.mode} onBack={exitLanguageSkills} {...sharedProps}/>;if(route.languageSkills&&PHASE2_LANGUAGE_BANK_TOPICS.has(route.topic)&&route.mode!=='learn')return <EnglishLanguageSkillsPhase2Assessment topicId={route.topic} onBack={exitLanguageSkills} {...sharedProps}/>;const englishAssessment=route.languageSkills&&!KEEP_DEDICATED.has(route.topic)&&ASSESSMENT_TOPICS.has(route.topic)&&route.mode!=='learn';if(englishAssessment)return <EnglishGenericLanguageSkillsQuiz key={`${route.topic}:${route.mode}`} topicId={route.topic}/>;return <AppWithChapter5 key={`${route.subject}:${route.page}:${route.topic}:${route.mode}:${route.languageSkills?'1':'0'}`}/>;}
createRoot(document.getElementById('root')).render(<React.StrictMode><AppErrorBoundary><BuildVersionRefresh/><FreshLanguageSkillsNavigation/><XPCompletionBoundary><RootRouter/></XPCompletionBoundary><XPAchievementOverlay/></AppErrorBoundary></React.StrictMode>);