import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {lessonData} from './lessonData';
import {StudyEngine} from './StudyEngine';

const subjects=[
{id:'math',name:'गणित',icon:'∑',desc:'संख्या, बीजगणित, ज्यामिति और तर्क',chapters:['संख्या पद्धति और बहुपद']},
{id:'science',name:'विज्ञान',icon:'⚗',desc:'भौतिकी, रसायन और जीव विज्ञान',chapters:['हमारे आसपास के पदार्थ']},
{id:'hindi',name:'हिन्दी',icon:'अ',desc:'गद्य, पद्य, भाषा और लेखन',chapters:['कहानी के प्लॉट–1']},
{id:'sst',name:'सामाजिक विज्ञान',icon:'◎',desc:'इतिहास, भूगोल, नागरिक शास्त्र और अर्थशास्त्र',chapters:['भौगोलिक खोजें–भाग 1']},
{id:'sanskrit',name:'संस्कृत',icon:'ॐ',desc:'पाठ, व्याकरण और संस्कृत अभ्यास',chapters:['ईशस्तुति']},
{id:'english',name:'अंग्रेज़ी',icon:'A',desc:'पाठ, grammar, vocabulary और writing',chapters:['व्याकरण, काल और शब्दावली']},
{id:'reasoning',name:'तर्कशक्ति',icon:'?',desc:'तर्क, पैटर्न और समस्या समाधान',chapters:['उन्नत तर्कशक्ति']}];
const XP_PER_LEVEL=250;
const initial={xp:0,streak:1,dailyXp:0,goal:100};
function load(){try{return JSON.parse(localStorage.getItem('class9-progress'))||initial}catch{return initial}}
function App(){const[page,setPage]=useState('home'),[subject,setSubject]=useState(null),[chapter,setChapter]=useState(null),[progress,setProgress]=useState(load),[tutor,setTutor]=useState(false),[toast,setToast]=useState('');useEffect(()=>localStorage.setItem('class9-progress',JSON.stringify(progress)),[progress]);const addXp=n=>{setProgress(p=>({...p,xp:p.xp+n,dailyXp:Math.min(p.goal,p.dailyXp+n)}));setToast(`+${n} XP`);setTimeout(()=>setToast(''),1200)};const openSubject=s=>{setSubject(s);setPage('subject')};const openChapter=c=>{setChapter(c);setPage('chapter')};if(page==='classes')return <Classes back={()=>setPage('home')} open={openSubject}/>;if(page==='subject')return <SubjectPage subject={subject} back={()=>setPage('classes')} open={openChapter}/>;if(page==='chapter')return <ChapterPage subject={subject} chapter={chapter} back={()=>setPage('subject')} addXp={addXp}/>;if(page==='meter')return <Meter progress={progress} back={()=>setPage('home')}/>;if(page==='tests')return <Simple title="सभी टेस्ट" back={()=>setPage('home')}><div className="class-list">{['अध्याय टेस्ट','मासिक टेस्ट','मिश्रित अभ्यास टेस्ट','मॉडल टेस्ट'].map((x,i)=><button className="list-card pressable" key={x} onClick={()=>{setSubject(subjects[i%subjects.length]);setChapter(subjects[i%subjects.length].chapters[0]);setPage('chapter')}}><span>0{i+1}</span><div><strong>{x}</strong><small>टेस्ट शुरू करें</small></div><b>→</b></button>)}</div></Simple>;return <Home progress={progress} setPage={setPage} addXp={addXp} tutor={tutor} setTutor={setTutor} toast={toast}/>}
function Home({progress,setPage,addXp,tutor,setTutor,toast}){const level=Math.floor(progress.xp/XP_PER_LEVEL)+1,pct=Math.round(progress.xp%XP_PER_LEVEL/XP_PER_LEVEL*100);return <main className="app-shell"><nav className="topbar"><strong className="brand">पढ़ाई</strong><span className="nav-class">कक्षा 9</span><div className="top-stats"><span>🔥 {progress.streak} दिन</span><span>⚡ {progress.xp} XP</span><span>LVL {level}</span></div><button className="tutor-mini pressable" onClick={()=>setTutor(true)}>✦ Smart Tutor</button></nav><header className="hero"><div className="hero-inner"><div className="badge">कक्षा 9 • STUDY SPACE</div><h1>आज की पढ़ाई शुरू करें।</h1><p>ध्यान से पढ़ें, अभ्यास करें और हर कदम पर XP कमाएँ।</p></div></header><section className="dashboard"><div className="progress-strip"><div className="level-badge"><span>LVL</span><strong>{level}</strong></div><div className="level-copy"><div className="level-title"><strong>आपकी सीखने की ऊर्जा</strong><span>{progress.xp%XP_PER_LEVEL} / {XP_PER_LEVEL} XP</span></div><div className="progress-track"><span style={{width:`${pct}%`}}/></div><small>अगले लेवल तक आपकी प्रगति</small></div><div className="daily-goal"><strong>{progress.dailyXp} XP</strong><span>आज का लक्ष्य {progress.goal}</span></div></div><div className="section-heading"><div><span className="eyebrow">कक्षा 9</span><h2>अध्ययन सुविधाएँ</h2></div><span className="focus-label">🎯 Focus Mode</span></div><div className="offering-grid"><button className="offering-card pressable" onClick={()=>setPage('classes')}><span className="offering-icon">▣</span><span className="offering-copy"><strong>सभी कक्षाएँ</strong><small>सभी विषय और अध्याय देखें</small></span><span>›</span></button><button className="offering-card pressable" onClick={()=>setPage('tests')}><span className="offering-icon">✎</span><span className="offering-copy"><strong>सभी टेस्ट</strong><small>परीक्षा और अभ्यास टेस्ट दें</small></span><span>›</span></button><button className="offering-card pressable" onClick={()=>setPage('meter')}><span className="offering-icon">◔</span><span className="offering-copy"><strong>तैयारी मीटर</strong><small>अपनी तैयारी और प्रगति देखें</small></span><span>›</span></button></div><section className="study-nudge"><div><span className="nudge-icon">⚡</span><div><strong>आज का छोटा मिशन</strong><p>एक focused session शुरू करें और 25 XP कमाएँ।</p></div></div><button className="secondary-btn pressable" onClick={()=>addXp(25)}>+25 XP</button></section><button className="tutor-banner pressable" onClick={()=>setTutor(true)}><span>🤖</span><div><strong>स्मार्ट ट्यूटर AI</strong><small>सवाल पूछें, concepts समझें और study plan बनाएँ।</small></div><b>पूछें →</b></button></section>{toast&&<div className="xp-toast">⚡ {toast}</div>}{tutor&&<Tutor close={()=>setTutor(false)} earn={()=>addXp(5)}/>}</main>}
function Classes({back,open}){return <Simple title="सभी कक्षाएँ" back={back}><div className="subject-grid">{subjects.map((s,i)=><button className="subject-tile pressable" key={s.id} onClick={()=>open(s)}><span className="subject-icon">{s.icon}</span><span className="subject-index">{String(i+1).padStart(2,'0')}</span><strong>{s.name}</strong><small>{s.desc}</small><b>अध्याय देखें →</b></button>)}</div></Simple>}
function SubjectPage({subject,back,open}){return <Simple title={subject.name} back={back}><p className="page-lead">{subject.desc}</p><div className="chapter-grid">{subject.chapters.map((c,i)=><button className="chapter-card pressable" key={c} onClick={()=>open(c)}><span className="chapter-no">अध्याय {i+1}</span><strong>{c}</strong><div className="chapter-actions"><span>📖 सीखें</span><span>📝 अभ्यास</span><span>🔥 चुनौती</span><span>🎯 टेस्ट</span></div><b>खोलें →</b></button>)}</div></Simple>}
function ChapterPage({subject,chapter,back,addXp}){const[mode,setMode]=useState(null);if(mode==='learn')return <Lesson subject={subject} chapter={chapter} back={()=>setMode(null)} addXp={addXp}/>;if(mode==='practice'||mode==='challenge'||mode==='test')return <StudyEngine subject={subject} chapter={chapter} mode={mode} onBack={()=>setMode(null)} addXp={addXp}/>;const modes=[['learn','📖','सीखें','अवधारणाएँ और उदाहरण',20],['practice','📝','अभ्यास','सीखे हुए concepts पर प्रश्न',15],['challenge','🔥','चुनौती','कठिन और सोचने वाले प्रश्न',25],['test','🎯','टेस्ट','समयबद्ध परीक्षा',15]];return <Simple title={chapter} back={back}><div className="mode-grid">{modes.map(([id,ic,t,d,x])=><button className="mode-card pressable" key={id} onClick={()=>setMode(id)}><span className="mode-icon">{ic}</span><strong>{t}</strong><span>{d}</span><em>+{x} XP</em><b>→</b></button>)}</div></Simple>}
function Lesson({subject,chapter,back,addXp}){const data=lessonData.default.lessons,[i,setI]=useState(0),[done,setDone]=useState(false),item=data[i],last=i===data.length-1;const next=()=>{if(last){if(!done){setDone(true);addXp(20)}else back()}else setI(x=>x+1)};return <Simple title="📖 सीखें" back={back}><div className="lesson-card"><span className="lesson-type">{i+1} / {data.length}</span><h2>{item.title}</h2><p className="lesson-body">{item.body}</p>{item.points&&<ul className="lesson-points">{item.points.map(p=><li key={p}>{p}</li>)}</ul>}{item.question&&<div className="quick-check"><strong>{item.question}</strong>{item.options.map(o=><button className="check-option pressable" key={o} onClick={()=>setDone(true)}>{o}</button>)}</div>}<button className="primary-btn pressable" onClick={next}>{last?(done?'अध्याय पूरा करें':'आगे बढ़ें'):'आगे बढ़ें →'}</button></div></Simple>}
function Meter({progress,back}){const score=Math.min(100,Math.round(progress.xp/4000*100));return <Simple title="तैयारी मीटर" back={back}><div className="meter-box"><div className="meter-ring"><span>{score}%</span></div><h2>आपकी तैयारी प्रगति पर है</h2><p>कुल <strong>{progress.xp} XP</strong> के आधार पर आपकी तैयारी बढ़ रही है।</p><div className="meter-stats"><span>🔥 {progress.streak} दिन</span><span>⚡ {progress.xp} XP</span></div></div></Simple>}
function Tutor({close,earn}){const[answer,setAnswer]=useState('');const ask=t=>{earn();setAnswer(t.includes('गणित')?'गणित में पहले concept समझें, फिर उदाहरण और अंत में practice करें।':'आज 25 मिनट का focused session रखें: 15 मिनट सीखें, 10 मिनट अभ्यास करें और गलतियों को review करें।')};return <div className="tutor-backdrop" onClick={close}><aside className="tutor-panel" onClick={e=>e.stopPropagation()}><div className="tutor-head"><div><strong>Smart Tutor AI</strong><small>आपकी पढ़ाई का साथी</small></div><button onClick={close}>×</button></div><div className="tutor-body"><div className="tutor-message"><strong>नमस्ते! 👋</strong><p>मैं आपकी पढ़ाई में मदद कर सकता हूँ।</p></div>{answer&&<div className="tutor-answer">{answer}</div>}{['मुझे आज क्या पढ़ना चाहिए?','गणित समझाओ','मेरा टेस्ट प्लान बनाओ'].map(x=><button className="suggestion pressable" key={x} onClick={()=>ask(x)}>{x}</button>)}</div><div className="tutor-foot"><input placeholder="अपना सवाल लिखें..." onKeyDown={e=>e.key==='Enter'&&e.currentTarget.value&&ask(e.currentTarget.value)}/><button className="send-btn pressable">→</button></div></aside></div>}
function Simple({title,back,children}){return <main className="page"><header className="page-header"><button className="pressable" onClick={back}>← वापस</button><div className="badge">कक्षा 9 • लर्निंग हब</div><h1>{title}</h1></header><section className="page-content">{children}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);
