import React,{useMemo,useState,useEffect} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import {NUMBER_SYSTEM_LESSONS,NUMBER_SYSTEM_QUESTIONS,NUMBER_SYSTEM_CHALLENGES} from './numberSystemData';
import './number-system.css';

const TEST_SECONDS=12*60;
const shuffle=(items,seed)=>{const a=[...items];let s=seed>>>0;for(let i=a.length-1;i>0;i--){s=(s*1664525+1013904223)>>>0;const j=s%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
const seeded=(seed)=>{let s=seed>>>0;s^=s<<13;s^=s>>>17;s^=s<<5;return s>>>0};
const prepareQuestion=(item,seed,index)=>{const pairs=item.options.map((text,i)=>({text,correct:i===item.answer}));const mixed=shuffle(pairs,seeded(seed+index*2654435761));return {...item,options:mixed.map(x=>x.text),answer:mixed.findIndex(x=>x.correct)}};
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

export function NumberSystemEngine({chapter='संख्या पद्धति',initialMode,onBack,addXp,finishSession}){
 const[mode,setMode]=useState(initialMode||'learn');
 const[lessonIndex,setLessonIndex]=useState(0);
 const[seed,setSeed]=useState(()=>Date.now()>>>0);
 const[questionIndex,setQuestionIndex]=useState(0);
 const[selected,setSelected]=useState(null);
 const[score,setScore]=useState(0);
 const[done,setDone]=useState(false);
 const[earned,setEarned]=useState(0);
 const[mistakes,setMistakes]=useState([]);
 const[remaining,setRemaining]=useState(TEST_SECONDS);
 const currentBank=mode==='challenge'?NUMBER_SYSTEM_CHALLENGES:NUMBER_SYSTEM_QUESTIONS;
 const count=mode==='test'?20:mode==='challenge'?12:15;
 const questions=useMemo(()=>{const bank=mode==='challenge'?shuffle(currentBank,seed).slice(0,count):shuffle(NUMBER_SYSTEM_QUESTIONS,seed).slice(0,count);return bank.map((q,i)=>prepareQuestion(q,seed,i))},[mode,seed]);
 const current=questions[questionIndex];
 const isQuiz=mode!=='learn';
 const stage=mode==='test'?'test':mode==='challenge'?'challenge':'practice';
 useEffect(()=>{if(!isQuiz||done||mode!=='test')return;const id=setInterval(()=>setRemaining(v=>{if(v<=1){clearInterval(id);setDone(true);return 0}return v-1}),1000);return()=>clearInterval(id)},[isQuiz,done,mode]);
 const startMode=next=>{setMode(next);setSeed(Date.now()>>>0);setQuestionIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0);setMistakes([]);setRemaining(TEST_SECONDS)};
 const choose=i=>{if(selected!==null||done||!current)return;setSelected(i);if(i===current.answer){setScore(v=>v+1);if(mode!=='test'){const pts=mode==='challenge'?20:10;setEarned(v=>v+pts);addXp?.(pts)}}else if(mode!=='test'){setMistakes(v=>v.includes(questionIndex)?v:[...v,questionIndex]);try{const old=JSON.parse(localStorage.getItem('class9-mistakes')||'[]');const rec={id:`number-system|${current.id}`,subject:'गणित',chapter,question:current.q,options:current.options,answer:current.answer,correct:current.options[current.answer],selected:current.options[i],explain:current.explain,at:Date.now()};localStorage.setItem('class9-mistakes',JSON.stringify([rec,...old.filter(x=>x.id!==rec.id)].slice(0,100)))}catch{}}};
 const next=()=>{if(!current)return setDone(true);if(selected===null)return;if(questionIndex>=questions.length-1)setDone(true);else{setQuestionIndex(v=>v+1);setSelected(null)}};
 const finish=()=>{setDone(true);finishSession?.({subject:'गणित',chapter,mode,score,total:questions.length,percent:Math.round(score/questions.length*100),earnedXp:earned,completed:true})};
 const restart=()=>startMode(mode);
 useEffect(()=>{if(!done||mode==='learn'||questions.length===0)return;markStageComplete(`गणित::${chapter}`,stage);finishSession?.({subject:'गणित',chapter,mode,score,total:questions.length,percent:Math.round(score/questions.length*100),earnedXp:earned,completed:true})},[done]);
 const percent=questions.length?Math.round(score/questions.length*100):0;
 if(mode==='learn')return <main className="number-system-shell"><header className="ns-hero"><div><button className="ns-back pressable" onClick={onBack}>← गणित</button><span className="ns-kicker">कक्षा 9 • अध्याय 1</span><h1>संख्या पद्धति</h1><p>संख्या परिवार से लेकर अपरिमेयता, घातांक और परिमेयीकरण तक — concept को समझें, फिर apply करें।</p></div><div className="ns-hero-mark" aria-hidden="true">ℝ</div></header><section className="ns-stats"><div><strong>6</strong><span>मुख्य विषय</span></div><div><strong>65+</strong><span>प्रश्न</span></div><div><strong>4</strong><span>मोड</span></div><div><strong>100%</strong><span>random options</span></div></section><section className="ns-modebar"><button className="ns-mode active pressable" onClick={()=>startMode('learn')}>📖 सीखें</button><button className="ns-mode pressable" onClick={()=>startMode('practice')}>📝 अभ्यास</button><button className="ns-mode pressable" onClick={()=>startMode('challenge')}>🔥 चुनौती</button><button className="ns-mode pressable" onClick={()=>startMode('test')}>🎯 टेस्ट</button></section><section className="ns-lessons"><div className="ns-section-head"><div><span>LEARN PATH</span><h2>Concepts step-by-step</h2></div><small>एक topic पूरा करें, फिर आगे बढ़ें।</small></div><div className="ns-lesson-tabs">{NUMBER_SYSTEM_LESSONS.map((lesson,i)=><button key={lesson.id} className={`ns-lesson-tab pressable ${i===lessonIndex?'selected':''}`} onClick={()=>setLessonIndex(i)}><span>{String(i+1).padStart(2,'0')}</span><strong>{lesson.title}</strong><em>{lesson.tag}</em></button>)}</div><article className="ns-lesson-card"><div className="ns-lesson-label">{NUMBER_SYSTEM_LESSONS[lessonIndex].tag}</div><h2>{NUMBER_SYSTEM_LESSONS[lessonIndex].title}</h2><p>{NUMBER_SYSTEM_LESSONS[lessonIndex].summary}</p><div className="ns-point-grid">{NUMBER_SYSTEM_LESSONS[lessonIndex].points.map(point=><div key={point}><b>✓</b><span>{point}</span></div>)}</div><div className="ns-example"><span>उदाहरण</span><strong>{NUMBER_SYSTEM_LESSONS[lessonIndex].example}</strong></div><div className="ns-tip"><span>💡 Tip</span>{NUMBER_SYSTEM_LESSONS[lessonIndex].tip}</div><div className="ns-lesson-actions"><button className="ns-secondary pressable" onClick={()=>setLessonIndex(v=>Math.max(0,v-1))} disabled={lessonIndex===0}>← पिछला</button><button className="ns-primary pressable" onClick={()=>{if(lessonIndex<NUMBER_SYSTEM_LESSONS.length-1)setLessonIndex(v=>v+1);else startMode('practice')}}>{lessonIndex<NUMBER_SYSTEM_LESSONS.length-1?'अगला concept →':'अभ्यास शुरू करें →'}</button></div></article></section></main>;
 if(done)return <main className="number-system-shell"><header className="ns-simple-head"><button className="ns-back pressable" onClick={onBack}>← अध्याय</button><span>{mode==='test'?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती परिणाम':'📝 अभ्यास परिणाम'}</span></header><section className="ns-result"><div className="ns-result-ring"><strong>{percent}%</strong><span>सही</span></div><p className="ns-result-score">{score} / {questions.length} सही</p><h1>{percent>=90?'कमाल! 🏆':percent>=75?'बहुत अच्छा! 💪':percent>=50?'अच्छी शुरुआत! 📚':'दोबारा concept देखें। 🔁'}</h1><p>{mode==='test'?'टेस्ट पूरा हुआ।':`आपने ${earned} XP कमाए।`}</p><div className="ns-result-grid"><div><b>✅</b><span>{score} सही</span></div><div><b>❌</b><span>{questions.length-score} गलत</span></div><div><b>🔀</b><span>Options shuffled</span></div></div><div className="ns-result-actions"><button className="ns-secondary pressable" onClick={restart}>फिर से करें</button><button className="ns-primary pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></section></main>;
 return <main className="number-system-shell"><header className="ns-quiz-head"><div><button className="ns-back pressable" onClick={onBack}>← अध्याय</button><span className="ns-kicker">{mode==='test'?'समयबद्ध टेस्ट':mode==='challenge'?'🔥 Challenge':'Practice'} • संख्या पद्धति</span><h1>{mode==='test'?'🎯 परीक्षा मोड':mode==='challenge'?'🔥 Challenge Mode':'📝 Practice Mode'}</h1></div><div className={`ns-timer ${mode==='test'?'show':''}`}>{mode==='test'&&<>⏱ {formatTime(remaining)}</>}</div></header><section className="ns-quiz-card"><div className="ns-question-meta"><span>प्रश्न {questionIndex+1} / {questions.length}</span><span>{Math.round(((questionIndex+1)/questions.length)*100)}%</span></div><div className="ns-progress"><span style={{width:`${((questionIndex+1)/questions.length)*100}%`}}/></div><div className="ns-breadcrumb">{current?.topic?.toUpperCase()} • {current?.level?.toUpperCase()}</div><h2>{current?.q}</h2><div className="ns-options">{current?.options.map((opt,i)=><button key={`${current.id}-${opt}`} className={`ns-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} disabled={selected!==null} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{opt}</button>)}</div>{selected!==null&&mode!=='test'&&<div className={`ns-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ सही विकल्प देखें'}</strong><p>{current.explain}</p></div>}{selected!==null&&mode==='test'&&<div className="ns-feedback neutral"><strong>✓ उत्तर दर्ज</strong><p>टेस्ट समाप्त होने पर score देखें।</p></div>}<div className="ns-quiz-foot"><span>{mode==='test'?'सही उत्तर अंत में दिखेगा':'उत्तर चुनकर आगे बढ़ें'}</span><button className="ns-primary pressable" disabled={selected===null} onClick={next}>{questionIndex===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></section></main>;
}
