import React,{useMemo,useState} from 'react';
import {chapter15Practice} from './chapter15Practice';

const challenge=[
 {q:'एक संतुलित पासा तीन बार फेंका जाता है। किसी एक निश्चित संख्या के तीनों बार आने की प्रायिकता क्या होगी?',options:['1/6','1/36','1/216','1/18'],answer:2,explain:'हर बार उस निश्चित संख्या की प्रायिकता 1/6 है। तीन स्वतंत्र बार के लिए (1/6)×(1/6)×(1/6)=1/216।'},
 {q:'दो बार सिक्का उछालने पर कम-से-कम एक बार चित न आने की प्रायिकता क्या है?',options:['1/4','1/2','3/4','1'],answer:0,explain:'कम-से-कम एक बार चित न आने का अर्थ दोनों बार पट है। उसकी प्रायिकता 1/4 है।'},
 {q:'एक थैले में 5 लाल, 3 नीली और 2 हरी गेंदें हैं। लाल या हरी गेंद मिलने की प्रायिकता क्या होगी?',options:['1/2','7/10','3/5','4/5'],answer:1,explain:'लाल या हरी गेंदें 5+2=7 और कुल गेंदें 10 हैं। इसलिए प्रायिकता 7/10।'},
 {q:'यदि किसी घटना की प्रायिकता 0.72 है, तो उसके न होने की प्रायिकता क्या होगी?',options:['0.18','0.28','0.32','0.72'],answer:1,explain:'पूरक घटना की प्रायिकता 1−0.72=0.28।'},
 {q:'एक प्रयोग में 12 समान रूप से संभावित परिणाम हैं। घटना A के 5 और घटना B के 4 अनुकूल परिणाम हैं और दोनों घटनाओं में कोई परिणाम साझा नहीं है। A या B की प्रायिकता क्या होगी?',options:['5/12','1/3','3/4','9/12'],answer:2,explain:'कुल अनुकूल परिणाम 5+4=9 हैं। प्रायिकता 9/12=3/4।'}
];
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function ProbabilityEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const questions=useMemo(()=>isTest?shuffle(chapter15Practice).slice(0,15):mode==='challenge'?challenge:chapter15Practice,[mode,isTest]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index],points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points)}}};
 const next=()=>{if(selected===null||!current)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">प्रायिकता • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0)}}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">गणित • प्रायिकता</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className="question-actions"><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>;
}
