import React,{useEffect,useMemo,useRef,useState}from'react';
import'./reasoning-lab-v2.css';

const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const make=(question,correct,distractors,explanation,difficulty='अभ्यास')=>({question,correct:String(correct),options:[String(correct),...distractors.map(String)],explanation,difficulty});
const TIMER_CONFIG={practice:{minutes:15,perQuestion:45},challenge:{minutes:20,perQuestion:60},test:{minutes:30,perQuestion:60}};
const letter=n=>String.fromCharCode(65+((n-1)%26+26)%26);
const pos=c=>c.toUpperCase().charCodeAt(0)-64;
const wordShift=(word,step)=>word.split('').map(c=>String.fromCharCode(65+((pos(c)+step-1)%26+26)%26)).join('');

const numberBank=[
 ...Array.from({length:15},(_,i)=>{const a=7+i,d=3+(i%7),v=[a,a+d,a+2*d,a+3*d],ans=a+4*d;return make(`${v.join(', ')}, ?`,ans,[ans-1,ans+d,ans+2*d],`हर चरण में +${d}।`,'अभ्यास')}),
 ...Array.from({length:15},(_,i)=>{const a=3+i%6,k=2+(i%3),v=[a,a*k,a*k*k,a*k*k*k],ans=a*k**4;return make(`${v.join(', ')}, ?`,ans,[ans+k,ans-k,ans+k*2],`हर बार ×${k}।`,'अभ्यास')}),
 ...Array.from({length:15},(_,i)=>{const a=4+i,d=2+(i%5),v=[a,a+d,a+3*d,a+6*d],ans=a+10*d;return make(`${v.join(', ')}, ?`,ans,[ans-d,ans+d,ans+2*d],`अंतर +${d}, +${2*d}, +${3*d}; अगला +${4*d}।`,'चैलेंज')}),
 ...Array.from({length:15},(_,i)=>{const a=5+i,v=[a,a*2+1,a*2+4,a*2+8],ans=a*2+13;return make(`${v.join(', ')}, ?`,ans,[ans-2,ans+2,ans+5],'बारी-बारी से ×2 और बढ़ते odd additions वाला pattern।','चैलेंज')}),
 ...Array.from({length:20},(_,i)=>{const n=3+(i%12),kind=i%4;if(kind===0){const v=[n*n,(n+1)**2,(n+2)**2];return make(`${v.join(', ')}, ?`,(n+3)**2,[(n+3)*(n+2),(n+3)**2+1,(n+4)**2],'क्रमिक पूर्ण वर्ग।','कठिन')}if(kind===1){const v=[n,n+2,n+6,n+12];return make(`${v.join(', ')}, ?`,n+20,[n+18,n+22,n+24],'अंतर +2,+4,+6,+8।','कठिन')}if(kind===2){const v=[n,n+1,n+4,n+9];return make(`${v.join(', ')}, ?`,n+16,[n+15,n+18,n+25],'अंतर 1,3,5,7 की ओर बढ़ता है।','कठिन')}const v=[n*2,n*3-1,n*4-2,n*5-3],ans=n*6-4;return make(`${v.join(', ')}, ?`,ans,[ans-1,ans+1,ans+2],'हर पद में multiplier बढ़ता है और subtraction क्रमशः 0,1,2,3,4… है।','कठिन')})
];

const alphabetBank=[
 ...Array.from({length:15},(_,i)=>{const a=1+(i%12),d=2+(i%5),v=[a,a+d,a+2*d,a+3*d].map(letter),ans=letter(a+4*d);return make(`${v.join(', ')}, ?`,ans,[letter(a+4*d-1),letter(a+4*d+1),letter(a+4*d+2)],`हर बार +${d} letters।`,'अभ्यास')}),
 ...Array.from({length:15},(_,i)=>{const a=26-(i%12),d=2+(i%5),v=[a,a-d,a-2*d,a-3*d].map(letter),ans=letter(a-4*d);return make(`${v.join(', ')}, ?`,ans,[letter(a-4*d-1),letter(a-4*d+1),letter(a-4*d+2)],`हर बार −${d} letters।`,'अभ्यास')}),
 ...Array.from({length:15},(_,i)=>{const a=1+(i%8),v=[a,a+2,a+5,a+9].map(letter),ans=letter(a+14);return make(`${v.join(', ')}, ?`,ans,[letter(a+13),letter(a+15),letter(a+16)],'Jump +2,+3,+4,+5।','चैलेंज')}),
 ...Array.from({length:15},(_,i)=>{const a=2+(i%7),v=[a,a+5,a+3,a+8,a+6].map(letter),ans=letter(a+11);return make(`${v.join(', ')}, ?`,ans,[letter(a+10),letter(a+12),letter(a+13)],'दो alternating jumps: +5, −2।','चैलेंज')}),
 ...Array.from({length:20},(_,i)=>{const a=1+(i%10),pattern=i%4;if(pattern===0){const v=[a,a+1,a+4,a+5].map(letter);return make(`${v.join(', ')}, ?`,letter(a+8),[letter(a+7),letter(a+9),letter(a+10)],'Pattern +1,+3,+1,+3।','कठिन')}if(pattern===1){const v=[a,a+4,a+5,a+9].map(letter);return make(`${v.join(', ')}, ?`,letter(a+10),[letter(a+8),letter(a+11),letter(a+12)],'Pattern +4,+1,+4,+1।','कठिन')}if(pattern===2){const v=[a,a+6,a+5,a+11].map(letter);return make(`${v.join(', ')}, ?`,letter(a+10),[letter(a+9),letter(a+12),letter(a+13)],'Pattern +6,−1,+6,−1।','कठिन')}const v=[a,a+7,a+14,a+21].map(letter);return make(`${v.join(', ')}, ?`,letter(a+2),[letter(a+1),letter(a+3),letter(a+4)],'हर बार +7 position और Z के बाद फिर A से cycle।','कठिन')})
];

const analogySeeds=[
 ['Doctor : Patient :: Teacher : ?','Student',['Book','Classroom','School'],'व्यक्ति : सेवा प्राप्त करने वाला।'],
 ['Bird : Fly :: Fish : ?','Swim',['Run','Walk','Climb'],'जीव : मुख्य क्रिया।'],
 ['Pen : Write :: Brush : ?','Paint',['Cut','Measure','Count'],'उपकरण : कार्य।'],
 ['Eye : Vision :: Ear : ?','Hearing',['Speech','Taste','Touch'],'अंग : संवेदना।'],
 ['Seed : Plant :: Egg : ?','Bird',['Flower','Fruit','Leaf'],'उत्पत्ति संबंध।'],
 ['Page : Book :: Brick : ?','Wall',['Road','Door','Roof'],'भाग : पूर्ण।'],
 ['King : Queen :: Man : ?','Woman',['Boy','Girl','Child'],'लिंग संबंध।'],
 ['Puppy : Dog :: Kitten : ?','Cat',['Cow','Goat','Horse'],'शिशु : वयस्क।'],
 ['Delhi : India :: Tokyo : ?','Japan',['China','Nepal','Korea'],'राजधानी : देश।'],
 ['Mercury : Planet :: Ganges : ?','River',['Mountain','City','Ocean'],'वर्ग संबंध।'],
 ['Author : Novel :: Sculptor : ?','Statue',['Hammer','Stone','Paint'],'सृजनकर्ता : सृजन।'],
 ['Thermometer : Temperature :: Clock : ?','Time',['Weight','Length','Speed'],'उपकरण : माप।'],
 ['Mango : Fruit :: Carrot : ?','Vegetable',['Flower','Grain','Spice'],'सदस्य : category।'],
 ['Hot : Cold :: Tall : ?','Short',['Wide','Thin','Heavy'],'विलोम संबंध।'],
 ['Morning : Sunrise :: Evening : ?','Sunset',['Rain','Noon','Cloud'],'समय : घटना।'],
 ['Milk : Cow :: Honey : ?','Bee',['Goat','Hen','Horse'],'स्रोत संबंध।'],
 ['Knife : Cut :: Key : ?','Unlock',['Write','Paint','Cook'],'वस्तु : कार्य।'],
 ['Car : Road :: Plane : ?','Air',['Water','Track','Garage'],'वाहन : माध्यम।'],
 ['Hand : Palm :: Foot : ?','Sole',['Toe','Leg','Heel'],'पूर्ण : मुख्य भाग।'],
 ['Triangle : 3 :: Pentagon : ?','5',['4','6','7'],'आकृति : भुजाएँ।'],
 ['Wool : Sheep :: Silk : ?','Silkworm',['Cotton','Cow','Goat'],'उत्पाद : स्रोत।'],
 ['Smile : Joy :: Tears : ?','Sorrow',['Anger','Sleep','Hunger'],'भाव : संकेत।'],
 ['School : Student :: Hospital : ?','Patient',['Doctor','Medicine','Nurse'],'स्थान : मुख्य व्यक्ति।'],
 ['Finger : Hand :: Toe : ?','Foot',['Leg','Knee','Arm'],'भाग : पूर्ण।']
];
const analogyBank=[...analogySeeds.map(x=>make(...x)),...Array.from({length:96},(_,i)=>{const a=4+i,t=i%8;if(t===0)return make(`${a} : ${a+5} :: ${a+8} : ?`,a+13,[a+12,a+14,a+15],'दोनों जोड़ों में +5।','अभ्यास');if(t===1)return make(`${a} : ${a*2} :: ${a+3} : ?`,(a+3)*2,[a+3,a*2+3,(a+3)*3],'दोनों में ×2।','चैलेंज');if(t===2)return make(`${a} : ${a*a} :: ${a+2} : ?`,(a+2)**2,[(a+2)*2,(a+2)**2+2,(a+2)**3],'square relation।','चैलेंज');if(t===3)return make(`${a} : ${a**3} :: ${a+1} : ?`,(a+1)**3,[(a+1)**2,(a+1)*3,(a+1)*4],'cube relation।','कठिन');if(t===4){const z=[['Writer','Book'],['Singer','Song'],['Chef','Dish'],['Architect','Building']][i%4];return make(`Creator : Work :: ${z[0]} : ?`,z[1],['Brush','Stage','Office'],'सृजनकर्ता : सृजन।','चैलेंज')}if(t===5){const z=[['Teeth','Chew'],['Eyes','See'],['Ears','Hear'],['Nose','Smell']][i%4];return make(`Body part : Function :: ${z[0]} : ?`,z[1],['Walk','Sleep','Speak'],'अंग : कार्य।','चैलेंज')}if(t===6){const z=[['Rose','Flower'],['Gold','Metal'],['Mango','Fruit'],['Tiger','Animal']][i%4];return make(`Member : Category :: ${z[0]} : ?`,z[1],['Place','Action','Color'],'सदस्य : वर्ग।','अभ्यास')}const z=[['Day','24 hours','Week'],['Week','7 days','Fortnight'],['Year','12 months','Month'],['Dozen','12','Score']][i%4];return make(`${z[0]} : ${z[1]} :: ${z[2]} : ?`,i%4===0?'7 days':i%4===1?'14 days':i%4===2?'12':'20',[i%4===0?'12 hours':'10','24 hours','30 days'],'इकाई/समय संबंध को दूसरी जोड़ी पर लागू करें।','कठिन')})];

const classificationBank=[...[
 ['अलग चुनिए: 14, 21, 28, 35, 42','42',['49','56','63'],'बाकी 7 के क्रमिक गुणज हैं; अंतिम item अलग pattern नहीं रखता।'],
 ['अलग चुनिए: 9, 16, 25, 36, 50','50',['49','64','81'],'बाकी perfect squares हैं।'],
 ['अलग शब्द: गुलाब, कमल, चमेली, गाजर','गाजर',['सूरजमुखी','नीलकमल','गेंदा'],'गाजर फूल नहीं है।'],
 ['अलग: मीटर, सेंटीमीटर, किलोमीटर, किलोग्राम','किलोग्राम',['मिलीमीटर','डेसीमीटर','मीटर'],'तीन लंबाई की इकाइयाँ हैं।'],
 ['अलग: जनवरी, मार्च, जुलाई, शुक्रवार','शुक्रवार',['अप्रैल','अगस्त','दिसंबर'],'तीन महीने हैं; शुक्रवार सप्ताह का दिन है।'],
 ['अलग अक्षर: B, D, F, H, K','K',['J','L','N'],'पहले चार अक्षर समान अंतर से हैं; K pattern तोड़ता है।'],
 ['अलग: 8, 27, 64, 81','81',['125','216','343'],'बाकी perfect cubes हैं।'],
 ['अलग: गंगा, यमुना, नर्मदा, हिमालय','हिमालय',['गोदावरी','कावेरी','सोन'],'हिमालय नदी नहीं है।'],
 ['अलग: बस, ट्रेन, ट्रक, आम','आम',['कार','साइकिल','रिक्शा'],'आम वाहन नहीं है।'],
 ['अलग संख्या: 13, 17, 19, 21','21',['23','29','31'],'21 prime नहीं है।'],
 ['अलग: A, E, I, O, T','T',['U','E','I'],'T vowel नहीं है।'],
 ['अलग माप: लीटर, मिलीलीटर, गैलन, मीटर','मीटर',['कप','पिंट','क्वार्ट'],'मीटर volume की इकाई नहीं है।']
 ].map(x=>make(...x)),...Array.from({length:96},(_,i)=>{const b=4+i,t=i%8;if(t===0){const n=[b*2,b*4,b*6,b*9];return make(`अलग संख्या: ${n.join(', ')}`,n[3],[b*8,b*10,b*12],'पहले तीन समान even multiples हैं।','चैलेंज')}if(t===1){const n=[b*b,(b+1)**2,(b+2)**2,b*b+5];return make(`अलग संख्या: ${n.join(', ')}`,n[3],[(b+3)**2,(b+4)**2,(b+5)**2],'बाकी perfect squares हैं।','कठिन')}if(t===2){const w=[['कबूतर','गौरैया','तोता','मछली'],['सोना','चाँदी','ताँबा','लकड़ी'],['आम','सेब','केला','पालक'],['पटना','दिल्ली','जयपुर','नेपाल']][i%4];return make(`अलग शब्द: ${w.join(', ')}`,w[3],[w[0],w[1],w[2]],'पहले तीन एक ही category में हैं।','अभ्यास')}if(t===3){const w=[['मीटर','सेमी','किमी','किलो'],['लीटर','गैलन','मिलीलीटर','मीटर'],['सेकंड','मिनट','घंटा','किलोमीटर']][i%3];return make(`अलग इकाई: ${w.join(', ')}`,w[3],w.slice(0,3),'तीन units एक ही physical quantity से संबंधित हैं।','अभ्यास')}if(t===4){const a=1+(i%12),v=[a,a+3,a+6,a+9,a+13].map(letter);return make(`अलग अक्षर: ${v.join(', ')}`,v[4],[v[0],v[1],v[2]],'पहले चार समान +3 jump follow करते हैं।','चैलेंज')}if(t===5){const days=['सोमवार','बुधवार','शुक्रवार','अप्रैल'];return make(`अलग चुनिए: ${days.join(', ')}`,days[3],['मंगलवार','रविवार','शनिवार'],'तीन सप्ताह के दिन हैं; एक महीना है।','अभ्यास')}if(t===6){const n=[b+1,b+3,b+5,b+8];return make(`अलग संख्या: ${n.join(', ')}`,n[3],[b+7,b+9,b+11],'पहले तीन odd-step progression बनाते हैं।','चैलेंज')}const words=[['स्कूल','अस्पताल','डाकघर','केला'],['कुर्सी','मेज','अलमारी','आम'],['बाघ','शेर','चीता','कबूतर']][i%3];return make(`अलग शब्द: ${words.join(', ')}`,words[3],words.slice(0,3),'तीन items एक साझा category में हैं।','अभ्यास')})];

const codingWords=['CAT','DOG','PEN','SUN','BOX','HEN','MAP','FISH','BIRD','LAMP','TREE','HOME','GAME','ROAD','BOOK','MANGO','GRAPE','BLUE','GOLD','FIRE','APPLE','TRAIN','SCHOOL','CHAIR','MUSIC','STAR','RING','NOTE','BALL','KING','PLANT','STONE','CLOUD','RIVER','LIGHT','HOUSE'];
const codingBank=[...Array.from({length:54},(_,i)=>{const ref=codingWords[i%codingWords.length],target=codingWords[(i+7)%codingWords.length],step=1+i%5,code=wordShift(ref,step),ans=wordShift(target,step);return make(`यदि ${ref} को ${code} लिखा जाए, तो ${target} को उसी नियम से कैसे लिखेंगे?`,ans,[wordShift(target,step-1),wordShift(target,step+1),wordShift(target,-step)],`हर अक्षर में ${step} position का shift है।`,'अभ्यास')}),...Array.from({length:24},(_,i)=>{const ref=codingWords[(i+4)%codingWords.length],target=codingWords[(i+15)%codingWords.length],step=2+i%4,code=wordShift(ref,step),ans=wordShift(target,step);return make(`यदि ${ref} → ${code}, तो ${target} → ?`,ans,[wordShift(target,step-1),wordShift(target,step+1),wordShift(target,-step)],`Reference pair से +${step} shift पहचानें।`,'चैलेंज')}),...Array.from({length:24},(_,i)=>{const ref=codingWords[(i+9)%codingWords.length],target=codingWords[(i+19)%codingWords.length],step=-1-(i%4),code=wordShift(ref,step),ans=wordShift(target,step);return make(`यदि ${ref} → ${code}, तो ${target} → ?`,ans,[wordShift(target,step+1),wordShift(target,step-1),wordShift(target,-step)],`हर अक्षर ${Math.abs(step)} positions पीछे जाता है।`,'कठिन')})];

const relationSets=['पिता','माँ','भाई','बहन','चाचा','चाची','मामा','मौसी','बुआ','दादा','दादी','नाना','नानी','भतीजा','भांजा','भांजी'];
const directionBank=[...[
 ['उत्तर की ओर मुख है; 90° दाएँ मुड़ते हैं। अंतिम दिशा?','पूर्व',['पश्चिम','उत्तर','दक्षिण'],'उत्तर से right = पूर्व।'],
 ['पूर्व की ओर मुख है; 90° बाएँ मुड़ते हैं। अंतिम दिशा?','उत्तर',['दक्षिण','पूर्व','पश्चिम'],'पूर्व से left = उत्तर।'],
 ['दक्षिण की ओर मुख है; 90° बाएँ मुड़ते हैं। अंतिम दिशा?','पूर्व',['पश्चिम','उत्तर','दक्षिण'],'दक्षिण से left = पूर्व।'],
 ['पश्चिम की ओर मुख है; 180° घूमते हैं। अंतिम दिशा?','पूर्व',['उत्तर','दक्षिण','पश्चिम'],'180° opposite दिशा देता है।'],
 ['6m उत्तर और 8m पूर्व। प्रारम्भिक स्थान से दिशा?','उत्तर-पूर्व',['उत्तर-पश्चिम','दक्षिण-पूर्व','दक्षिण-पश्चिम'],'उत्तर + पूर्व = उत्तर-पूर्व।'],
 ['10m उत्तर, 6m दक्षिण, 4m पश्चिम। प्रारम्भिक स्थान से दिशा?','उत्तर-पश्चिम',['उत्तर-पूर्व','दक्षिण-पश्चिम','दक्षिण-पूर्व'],'शुद्ध movement 4m उत्तर और 4m पश्चिम।'],
 ['A, B का पिता है और B, C की बहन है। A का C से संबंध?','पिता',['भाई','चाचा','दादा'],'B और C भाई-बहन हैं; A पिता है।'],
 ['P, Q की माँ है और Q, R का भाई है। P का R से संबंध?','माँ',['बहन','दादी','मौसी'],'Q और R भाई-बहन हैं।'],
 ['A, B का पिता है और B, C की माँ है। A का C से संबंध?','नाना',['पिता','मामा','दादा'],'माँ का पिता = नाना।'],
 ['P, Q की बहन है और Q, R का पिता है। P का R से संबंध?','बुआ',['माँ','दादी','बहन'],'पिता की बहन = बुआ।'],
 ['M, N का भाई है और N, P की माँ है। M का P से संबंध?','मामा',['चाचा','पिता','भाई'],'माँ का भाई = मामा।'],
 ['X, Y की बहन है और Y, Z का भाई है। X का Z से संबंध?','बहन',['बुआ','मौसी','माँ'],'X और Z भाई-बहन हैं।']
 ].map(x=>make(...x)),...Array.from({length:48},(_,i)=>{const dirs=['उत्तर','पूर्व','दक्षिण','पश्चिम'],start=dirs[i%4],turnPattern=[[90,90,180],[90,180,90],[270,90,90],[180,270,90],[90,270,180],[180,180,90],[270,270,90],[90,90,270]][i%8],idx={उत्तर:0,पूर्व:1,दक्षिण:2,पश्चिम:3};let p=idx[start];turnPattern.forEach(v=>{p=(p+(v===270?3:v/90))%4});const ans=dirs[p];return make(`${start} की ओर मुख है; ${turnPattern.map(v=>`${v}° दाएँ`).join(', ')} के बाद दिशा?`,ans,dirs.filter(x=>x!==ans),'हर turn के बाद current facing direction update करें।',i<16?'अभ्यास':i<32?'चैलेंज':'कठिन')}),...Array.from({length:48},(_,i)=>{const g=[['A','B','C'],['P','Q','R'],['M','N','O'],['X','Y','Z']][i%4],t=i%8;let text,ans,exp;if(t===0){text=`${g[0]}, ${g[1]} का भाई है और ${g[1]}, ${g[2]} का पिता है। ${g[0]} का ${g[2]} से संबंध?`;ans='चाचा';exp='पिता का भाई = चाचा।'}else if(t===1){text=`${g[0]}, ${g[1]} की बहन है और ${g[1]}, ${g[2]} की माँ है। ${g[0]} का ${g[2]} से संबंध?`;ans='मौसी';exp='माँ की बहन = मौसी।'}else if(t===2){text=`${g[0]}, ${g[1]} का पिता है और ${g[1]}, ${g[2]} का भाई है। ${g[0]} का ${g[2]} से संबंध?`;ans='पिता';exp='दोनों का पिता समान है।'}else if(t===3){text=`${g[0]}, ${g[1]} की माँ है और ${g[1]}, ${g[2]} का पिता है। ${g[0]} का ${g[2]} से संबंध?`;ans='दादी';exp='पिता की माँ = दादी।'}else if(t===4){text=`${g[0]}, ${g[1]} की बहन है; ${g[1]}, ${g[2]} का पिता है। ${g[0]} का ${g[2]} से संबंध?`;ans='बुआ';exp='पिता की बहन = बुआ।'}else if(t===5){text=`${g[0]}, ${g[1]} का पुत्र है और ${g[1]}, ${g[2]} का भाई है। ${g[0]} का ${g[2]} से संबंध?`;ans='भतीजा';exp='भाई का पुत्र = भतीजा।'}else if(t===6){text=`${g[0]}, ${g[1]} की पुत्री है और ${g[1]}, ${g[2]} की बहन है। ${g[0]} का ${g[2]} से संबंध?`;ans='भांजी';exp='बहन की पुत्री = भांजी।'}else{text=`${g[0]}, ${g[1]} की माँ है; ${g[1]}, ${g[2]} की बहन है। ${g[0]} का ${g[2]} से संबंध?`;ans='माँ';exp='भाई-बहन की माँ दोनों की माँ होती है।'}return make(text,ans,relationSets.filter(x=>x!==ans).slice(0,3),exp,i<16?'अभ्यास':i<32?'चैलेंज':'कठिन')})];

const chapters=[
{id:'number-series',title:'संख्या श्रृंखला',icon:'🔢',kicker:'PATTERN DETECTION',desc:'नई mixed sequences में difference, ratio और hidden pattern पहचानें।',skills:['Difference','Ratio','Alternate','Squares','Mixed'],learn:{headline:'Sequence को छोटे rules में तोड़ो',example:'5, 9, 15, 23, 33, ?',answer:'45',why:'अंतर +4,+6,+8,+10 हैं; अगला +12 → 45।',trap:'केवल दो numbers देखकर rule तय मत करें।',steps:['Consecutive differences निकालें।','× और ÷ patterns जाँचें।','Increasing differences देखें।','कम-से-कम 4 transitions verify करें।'],tip:'पहले difference table बनाना सबसे तेज तरीका है।'}},
{id:'alphabet-series',title:'अक्षर श्रृंखला',icon:'🔤',kicker:'LETTER PATTERNS',desc:'Position-based, reverse और alternating alphabet patterns solve करें।',skills:['A=1…Z=26','Forward','Backward','Alternate','Cycle'],learn:{headline:'Letters को positions में बदलो',example:'B, E, I, N, ?',answer:'T',why:'Jump +3,+4,+5,+6; अगला +7 → T।',trap:'Alphabet को केवल देखकर guess मत करें।',steps:['A=1…Z=26 map करो।','हर jump लिखो।','Increasing या alternating jump जाँचो।','Wrap-around हो तो 26 के बाद A लें।'],tip:'Position arithmetic mixed alphabet questions में बहुत मदद करता है।'}},
{id:'analogy',title:'समानता (Analogy)',icon:'🔗',kicker:'RELATION MAPPING',desc:'पहली जोड़ी का exact relation दूसरी जोड़ी पर लागू करें।',skills:['Function','Category','Part–Whole','Opposite','Numerical'],learn:{headline:'Relation को एक स्पष्ट rule में बदलो',example:'Eye : See :: Ear : ?',answer:'Hear',why:'अंग और उसके function का relation है।',trap:'सिर्फ words की similarity पर भरोसा मत करें।',steps:['पहली जोड़ी का relation बोलो।','Function/category पहचानो।','उसी relation को दूसरी जोड़ी पर लगाओ।','Options से cross-check करो।'],tip:'Relation एक छोटे वाक्य में explain कर पाना चाहिए।'}},
{id:'classification',title:'वर्गीकरण / Odd One Out',icon:'🧩',kicker:'ODD ONE OUT',desc:'Common property खोजकर असंगत item चुनें।',skills:['Number','Word','Letter','Unit','Category'],learn:{headline:'Common property पहले खोजो',example:'16, 25, 36, 49, 52',answer:'52',why:'पहले चार perfect squares हैं।',trap:'ऐसी property मत चुनो जो सिर्फ दो items पर लागू हो।',steps:['सभी items की तुलना करो।','Category या mathematical property खोजो।','एक odd item isolate करो।','बाकी तीन/चार पर वही rule verify करो।'],tip:'सबसे मजबूत shared property को प्राथमिकता दें।'}},
{id:'coding-decoding',title:'Coding–Decoding',icon:'🔐',kicker:'CODE BREAKING',desc:'Reference pair से code rule निकालें और target word पर लागू करें।',skills:['Shift','Reverse','Position','Word code','Mixed'],learn:{headline:'पहले code rule decode करो',example:'DOG → EPH; CAT → ?',answer:'DBU',why:'हर अक्षर +1 shift हुआ है।',trap:'दिए गए reference word को ही दोबारा code करने का सवाल न समझें।',steps:['Reference pair compare करो।','हर character का बदलाव देखो।','पूरे word पर rule verify करो।','फिर target word code करो।'],tip:'कम-से-कम दो characters पर transformation confirm करें।'}},
{id:'direction-blood',title:'दिशा एवं रक्त संबंध',icon:'🧭',kicker:'LOGICAL RELATIONS',desc:'Multi-turn direction और family-tree reasoning को step-by-step solve करें।',skills:['Direction','Distance','Turns','Family Tree','Relations'],learn:{headline:'Mental map + family tree दोनों बनाओ',example:'उत्तर 6m, दाएँ, फिर दक्षिण 6m।',answer:'पूर्व/पश्चिम नहीं; प्रारम्भिक बिंदु से सीधे नीचे? पहले turns track करें।',why:'Direction questions में हर turn current facing के अनुसार बदलता है।',trap:'पहले turn की दिशा को पूरे सवाल में स्थिर मत मानो।',steps:['Starting direction तय करो।','हर turn के बाद नई दिशा लिखो।','Distance को net movement में बदलो।','Blood relation में generation levels mark करो।'],tip:'जटिल family relation में छोटा tree बनाना अधिक reliable है।'}}
];
const banks={'number-series':numberBank,'alphabet-series':alphabetBank,'analogy':analogyBank,'classification':classificationBank,'coding-decoding':codingBank,'direction-blood':directionBank};
const deepDive={'number-series':'Second difference, alternating operation और hidden square/cube patterns को भी test करें।','alphabet-series':'Position arithmetic, reverse jumps और cyclic A–Z movement पर ध्यान दें।','analogy':'Function, category, part-whole, source और numerical relations को exact rule में बदलें।','classification':'एक common property सभी matching items पर समान रूप से लागू होनी चाहिए।','coding-decoding':'Reference pair से transformation निकालकर हर character पर वही rule लगाएँ।','direction-blood':'Current facing direction और generation level दोनों लगातार track करें।'};
const prepare=(bank,count,mode='practice')=>{const rank={अभ्यास:0,चैलेंज:1,कठिन:2};const pool=mode==='practice'?bank.filter(q=>rank[q.difficulty]<2):mode==='challenge'?bank.filter(q=>rank[q.difficulty]>=1):bank;return shuffle(pool.length>=count?pool:bank).slice(0,count).map(q=>({...q,options:shuffle(q.options.map(text=>({text:String(text),correct:String(text)===q.correct})))}))};

export default function ReasoningLabV2({initialChapter=null,initialMode=null,onExit=()=>{},addXp=()=>{},finishSession=()=>{}}){
 const chapterInitial=chapters.some(c=>c.id===initialChapter)?initialChapter:chapters[0].id;
 const modeInitial=['learn','practice','challenge','test'].includes(initialMode)?initialMode:'learn';
 const[chapterId,setChapterId]=useState(chapterInitial);const[mode,setMode]=useState(modeInitial);const[session,setSession]=useState(null);const[answers,setAnswers]=useState({});const answersRef=useRef({});const[score,setScore]=useState(0);const[completed,setCompleted]=useState(false);const[testStarted,setTestStarted]=useState(false);const[timeLeft,setTimeLeft]=useState(TIMER_CONFIG.practice.minutes*60);
 const active=chapters.find(c=>c.id===chapterId)||chapters[0].id?chapters.find(c=>c.id===chapterId)||chapters[0]:chapters[0];const bank=banks[active.id];const counts=useMemo(()=>({practice:20,challenge:20}),[]);
 const resetQuiz=()=>{setSession(null);setAnswers({});answersRef.current={};setScore(0);setCompleted(false);setTestStarted(false)};
 const begin=nextMode=>{setMode(nextMode);setAnswers({});answersRef.current={};setScore(0);setCompleted(false);if(nextMode==='test'){setSession(null);setTimeLeft(TIMER_CONFIG.test.minutes*60);setTestStarted(false)}else{setSession(prepare(bank,counts[nextMode],nextMode));setTimeLeft(TIMER_CONFIG[nextMode].minutes*60);setTestStarted(true)}};
 const startTest=()=>{setAnswers({});answersRef.current={};setScore(0);setCompleted(false);setSession(prepare(bank,30,'test'));setTimeLeft(TIMER_CONFIG.test.minutes*60);setTestStarted(true)};
 const finish=timedOut=>{if(!session)return;const current=answersRef.current;const correct=session.reduce((n,q,i)=>n+(current[i]?.correct?1:0),0);setScore(correct);setCompleted(true);finishSession({subject:'reasoning',chapter:active.id,mode,correct,total:session.length,timedOut:Boolean(timedOut),at:new Date().toISOString()});addXp(correct);setTestStarted(false)};
 useEffect(()=>{if(!testStarted||!session)return;const id=setInterval(()=>{setTimeLeft(t=>{if(t<=1){clearInterval(id);finish(true);return 0}return t-1})},1000);return()=>clearInterval(id)},[mode,testStarted,session]);
 useEffect(()=>{answersRef.current=answers},[answers]);
 useEffect(()=>{resetQuiz()},[chapterId]);
 const mm=String(Math.floor(timeLeft/60)).padStart(2,'0'),ss=String(timeLeft%60).padStart(2,'0');
 const choose=(i,opt)=>{answersRef.current={...answersRef.current,[i]:opt};setAnswers(a=>({...a,[i]:opt}))};
 return <div className="rlab-shell">
  <header className="rlab-header"><button type="button" className="rlab-back" onClick={onExit}>← Reasoning Lab</button><div className="rlab-brand"><span>REASONING LAB</span><small>Class 9 • तर्कशक्ति</small></div></header>
  <div className="rlab-content">
   <aside className="rlab-sidebar"><div className="rlab-sidebar-title">CHAPTERS</div>{chapters.map(c=><button type="button" key={c.id} className={`rlab-chapter ${c.id===active.id?'active':''}`} onClick={()=>{setChapterId(c.id);setMode('learn')}}><span>{c.icon}</span><div><b>{c.title}</b><small>{c.skills.slice(0,2).join(' • ')}</small></div></button>)}</aside>
   <main className="rlab-main">
    <section className="rlab-hero"><div className="rlab-icon">{active.icon}</div><div><div className="rlab-kicker">CHAPTER • {active.kicker}</div><h1>{active.title}</h1><p>{active.desc}</p></div></section>
    <section className="rlab-stats"><div><strong>{bank.length}+</strong><span>QUESTION BANK</span></div><div><strong>20</strong><span>PRACTICE</span></div><div><strong>20</strong><span>CHALLENGE</span></div><div><strong>30</strong><span>FINAL TEST</span></div></section>
    <div className="rlab-skills">{active.skills.map(s=><span key={s}>✓ {s}</span>)}</div>
    <nav className="rlab-tabs">{[['learn','📖 Learn'],['practice','✍️ Practice'],['challenge','🔥 Challenge'],['test','🎯 Final Test']].map(([id,label])=><button type="button" key={id} className={mode===id?'active':''} onClick={()=>id==='test'?begin(id):begin(id)}>{label}</button>)}</nav>
    {mode==='learn'&&<section className="rlab-learn"><div className="smart-head"><span>SMART LEARNING PATH</span><h2>{active.learn.headline}</h2><p>एक fixed process follow करके speed और accuracy दोनों बढ़ाएँ।</p></div><div className="smart-steps">{active.learn.steps.map((st,i)=><article key={st}><b>0{i+1}</b><span>{st}</span></article>)}</div><div className="worked"><div><span>WORKED EXAMPLE</span><h3>{active.learn.example}</h3></div><div className="worked-answer">ANSWER <strong>{active.learn.answer}</strong></div><p>{active.learn.why}</p></div><div className="tip"><b>⚠️ Common Trap</b><span>{active.learn.trap}</span></div><div style={{marginTop:18,padding:'18px 20px',border:'1px solid #dbe5ef',borderRadius:16,background:'#f8fbff'}}><div style={{fontSize:12,fontWeight:800,letterSpacing:'.08em',color:'#287a9f'}}>DEEP DIVE • EXTRA CONTENT</div><p style={{margin:'8px 0 0',lineHeight:1.65}}>{deepDive[active.id]}</p></div><div className="ready"><div><small>READY?</small><h3>Guided Practice से शुरुआत करें</h3><p>{active.learn.tip}</p></div><button type="button" onClick={()=>begin('practice')}>Practice शुरू करें →</button></div></section>}
    {(mode==='practice'||mode==='challenge')&&!session&&<section className="rlab-start"><div className="start-icon">{mode==='practice'?'✍️':'🔥'}</div><h2>{mode==='practice'?'Guided Practice':'Challenge Mode'}</h2><p>{mode==='practice'?'20 fresh questions • 15 minutes • answers and marks at the end.':'20 higher-difficulty fresh questions • 20 minutes • answers and marks at the end.'}</p><button type="button" onClick={()=>begin(mode)}>Start {mode==='practice'?'Practice':'Challenge'} →</button></section>}
    {mode==='test'&&!testStarted&&<section className="rlab-start test-start"><div className="start-icon">🎯</div><div className="timer-preview">30:00</div><h2>Final Test</h2><p>30 नए प्रश्न • 30 मिनट • हर attempt में options randomised होंगे।</p><div className="test-rules"><span>⏱️ Auto-submit on timeout</span><span>🔀 Random options</span><span>📊 Final score</span></div><button type="button" onClick={startTest}>Test शुरू करें →</button></section>}
    {session&&testStarted&&<section className="rlab-quiz"><div className="quiz-top"><div><b>{mode==='test'?'FINAL TEST':mode==='practice'?'PRACTICE':'CHALLENGE'}</b><span>{Object.keys(answers).length} / {session.length} answered</span></div><div className={`countdown ${timeLeft<=60?'danger':''}`}>⏱️ {mm}:{ss}</div></div><div className="progressbar"><span style={{width:`${Math.min(100,Object.keys(answers).length/session.length*100)}%`}}/></div>{session.map((q,i)=><div className="question-card" key={`${q.question}-${i}`}><div className="q-meta">Q{i+1} <span>{q.difficulty}</span></div><h3>{q.question}</h3><div className="options">{q.options.map((o,j)=><button type="button" key={j} className={answers[i]?.text===o.text?'selected':''} onClick={()=>choose(i,o)}><span>{String.fromCharCode(65+j)}</span>{o.text}</button>)}</div>{answers[i]&&<div style={{marginTop:12,padding:'10px 12px',borderRadius:12,background:'#f7fafc'}}><b>✓ Answer recorded</b><div style={{marginTop:4}}>सही उत्तर, अंक और explanation results के अंत में दिखेंगे।</div></div>}</div>)}<div className="quiz-fallback-list">{session.every((_,i)=>answers[i]!==undefined)&&<div className="all-answered"><b>All questions answered.</b><button type="button" onClick={()=>finish(false)}>{mode==='test'?'Submit Final Test':'Finish & See Results'} →</button></div>}</div></section>}
    {completed&&<section className="rlab-result"><div className="result-score"><span>SCORE</span><strong>{score} / {mode==='test'?30:session?.length||20}</strong><p>{score>=Math.ceil((mode==='test'?30:20)*0.8)?'Excellent! तुम्हारी reasoning speed strong है.':score>=Math.ceil((mode==='test'?30:20)*0.6)?'Good work! थोड़ी और practice से accuracy बढ़ेगी.':'Practice जारी रखो और rules को step-by-step verify करो.'}</p></div><section className="answer-key" style={{marginTop:20}}><h3>📋 Answer Review</h3>{session.map((q,i)=>{const picked=answers[i];const ok=Boolean(picked&&picked.correct);return <article key={`${q.question}-${i}`} className="answer-key-item" style={{textAlign:'left',marginTop:10}}><strong>Q{i+1}</strong><div style={{marginTop:5}}>{q.question}</div><div style={{marginTop:5}}>Your answer: {picked?picked.text:'—'} {picked?(ok?'✓':'✗'):''}</div><div style={{marginTop:4}}>Correct answer: {q.correct}</div>{q.explanation&&<p style={{marginTop:5}}>💡 {q.explanation}</p>}</article>})}</section><button type="button" onClick={()=>{resetQuiz();setMode('learn')}}>अध्याय पर लौटें</button></section>}
   </main>
  </div>
 </div>
}
