import React,{useEffect,useMemo,useState} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import './science3-learn.css';

const typeLabel={intro:'परिचय',concept:'अवधारणा',example:'उदाहरण',check:'त्वरित जाँच'};

function VisualDiagram({visual}){
 const type=visual?.type||'generic';
 if(type==='soundSource'||type==='medium'||type==='longitudinal'||type==='compressRare') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc11-wave"><span className="sc11-source">◉</span><div className="sc11-particles">{Array.from({length:11},(_,i)=><span key={i}/>)}</div><span className="sc11-arrow">→</span></div></div>;
 if(type==='amplitude') return <div className="sc3-motion-diagram sc3-amplitude" aria-hidden="true"><div className="sc11-compare"><div className="sc11-amp-col"><span className="sc11-amp-small"/></div><div className="sc11-amp-col"><span className="sc11-amp-big"/></div></div></div>;
 if(type==='frequency') return <div className="sc3-motion-diagram sc3-frequency" aria-hidden="true"><div className="sc11-bars"><i className="sc11-bar low"/><i className="sc11-bar high"/></div></div>;
 if(type==='period') return <div className="sc3-motion-diagram sc3-period" aria-hidden="true"><div className="sc11-dots">{Array.from({length:8},(_,i)=><span key={i}/>)}</div><strong>T = 1/ν</strong></div>;
 if(type==='wavelength') return <div className="sc3-motion-diagram sc3-wavelength" aria-hidden="true"><div className="sc11-wavelength"><span className="sc11-mark"><span>λ</span></span><span className="sc11-mark"><span>λ</span></span></div></div>;
 if(type==='waveSpeed'||type==='speedExample') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc11-formulas"><strong>{type==='speedExample'?'λ = 2 m':'λ'}</strong><strong>{type==='speedExample'?'ν = 3 Hz':'ν'}</strong><strong>{type==='speedExample'?'v = 6 m/s':'v = λν'}</strong></div></div>;
 if(type==='mediumSpeed') return <div className="sc3-motion-diagram sc3-mediumSpeed" aria-hidden="true"><div className="sc11-stack"><div><b>ठोस</b><span>अधिक</span></div><div><b>द्रव</b><span>मध्य</span></div><div><b>गैस</b><span>कम</span></div></div></div>;
 if(type==='audibleRange'||type==='ultraInfra') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc11-range"/></div>;
 if(type==='pitch') return <div className="sc3-motion-diagram sc3-pitch" aria-hidden="true"><div className="sc11-bars"><i className="sc11-bar low"/><i className="sc11-bar high"/><strong>ν ↑ → पिच ↑</strong></div></div>;
 if(type==='reflection'||type==='echo'||type==='echoDistance') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc11-echo"><span>◉</span><i className="sc11-pulse"/><div className="wall"/><i className="sc11-pulse"/><span>◉</span></div>{type==='echoDistance'&&<strong>d = vt/2</strong>}</div>;
 if(type==='reverberation') return <div className="sc3-motion-diagram sc3-reverberation" aria-hidden="true"><div className="sc11-crowd">{Array.from({length:13},(_,i)=><i key={i}/>)}</div><strong>↔ ↔ ↔ कई परावर्तन</strong></div>;
 if(type==='ear') return <div className="sc3-motion-diagram sc3-ear" aria-hidden="true"><div className="sc11-ear"><span>◉ →</span><span>👂</span><span>→ 🧠</span></div></div>;
 if(type==='sonar') return <div className="sc3-motion-diagram sc3-sonar" aria-hidden="true"><span className="sc11-boat">⛴</span><i className="sc11-ray"/><span className="sc11-target">●</span></div>;
 if(type==='dailySound') return <div className="sc3-motion-diagram sc3-dailySound" aria-hidden="true"><div className="sc11-stack"><div>🎵<b>संगीत</b></div><div>🩺<b>Ultrasound</b></div><div>⛴<b>SONAR</b></div></div></div>;
 if(type==='soundSummary') return <div className="sc3-motion-diagram sc3-soundSummary" aria-hidden="true"><div className="sc11-formulas"><strong>v = λν</strong><strong>T = 1/ν</strong><strong>d = vt/2</strong></div></div>;
 if(type==='work'||type==='zeroWork') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-work-box">▰</div><div className="sc10-floor"/><span className="sc10-arrow force">बल →</span><span className="sc10-arrow disp">विस्थापन →</span>{type==='zeroWork'&&<strong className="sc10-zero">विस्थापन = 0 ⇒ W = 0</strong>}</div>;
 if(type==='workFormula'||type==='workExample') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-formula"><strong>{type==='workFormula'?'W = F × s':'10 N × 3 m = 30 J'}</strong><span>कार्य = बल × विस्थापन</span></div></div>;
 if(type==='energy'||type==='mechanical'||type==='energyConserve') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-energy-row"><span>स्थितिज ऊर्जा</span><i>↕</i><span>गतिज ऊर्जा</span></div>{type==='mechanical'&&<strong>यांत्रिक ऊर्जा = K + U</strong>}{type==='energyConserve'&&<strong>कुल ऊर्जा संरक्षित</strong>}</div>;
 if(type==='kinetic'||type==='kineticExample') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-speed"><div className="sc10-speed-row"><span>v</span><div className="sc10-bar one"><i/></div><strong>{type==='kinetic'?'K':'9 J'}</strong></div><div className="sc10-speed-row"><span>2v</span><div className="sc10-bar two"><i/></div><strong>{type==='kinetic'?'4K':'4×'}</strong></div></div></div>;
 if(type==='potential'||type==='potentialExample') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-ground"/><span className="sc10-height-object">●</span><div className="sc10-height-line"/><span className="sc10-height-tag">h</span><div className="sc10-formula"><strong>{type==='potential'?'U = mgh':'U = 98 J'}</strong></div></div>;
 if(type==='swingEnergy') return <div className="sc3-motion-diagram sc3-swingEnergy" aria-hidden="true"><div className="sc10-swing-rope"/><div className="sc10-swing-ball">●</div><strong className="sc10-swing-label">U ↔ K</strong></div>;
 if(type==='power'||type==='powerExample'||type==='watt') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-power"><strong>{type==='power'?'P = W/t':type==='powerExample'?'20 W':'1 kW = 1000 W'}</strong><span>शक्ति = कार्य / समय</span></div></div>;
 if(type==='dailyPower'||type==='workEnergyPower') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-triad"><span>कार्य</span><i>→</i><span>ऊर्जा</span><i>→</i><span>शक्ति</span></div></div>;
 if(type==='summaryWorkEnergy'||type==='challengePrep') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc10-summary"><strong>W = F×s</strong><strong>K = ½mv²</strong><strong>U = mgh</strong><strong>P = W/t</strong></div></div>;
 if(type==='gravity'||type==='gravityLaw') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-gravity-space"><span className="sc3-mass sc3-mass-left">m₁</span><span className="sc3-gravity-arrow left">↘</span><span className="sc3-distance">r</span><span className="sc3-gravity-arrow right">↙</span><span className="sc3-mass sc3-mass-right">m₂</span></div>{type==='gravity'&&<div className="sc3-gravity-caption">दो द्रव्यमान एक-दूसरे को आकर्षित करते हैं</div>}{type==='gravityLaw'&&<div className="sc3-formula-card">F = Gm₁m₂ / r²</div>}</div>;
 if(type==='inverseSquare') return <div className="sc3-motion-diagram sc3-inverseSquare" aria-hidden="true"><div className="sc3-inverse-panels"><div><span className="sc3-mini-masses">●────●</span><b>दूरी = r</b><strong>बल = F</strong></div><i>→</i><div><span className="sc3-mini-masses">●────────●</span><b>दूरी = 2r</b><strong>बल = F/4</strong></div></div><div className="sc3-inverse-note">दूरी 2 गुनी → बल 1/4</div></div>;
 if(type==='earthGravity'||type==='gAccel'||type==='freeFall') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-earth">🌍</div><div className="sc3-fall-object">●</div><div className="sc3-down-arrow">↓ g</div><div className="sc3-fall-caption">{type==='gAccel'?'g ≈ 9.8 m/s²':type==='freeFall'?'मुक्त पतन: मुख्य त्वरण नीचे की ओर':'पृथ्वी वस्तु को अपनी ओर खींचती है'}</div></div>;
 if(type==='actionReactionGravity') return <div className="sc3-motion-diagram sc3-actionReactionGravity" aria-hidden="true"><div className="sc3-earth-small">🌍</div><div className="sc3-object-orb">●</div><div className="sc3-action-arrows"><span>वस्तु पर ← F</span><span>F → पृथ्वी पर</span></div><div className="sc3-equal-note">परिमाण बराबर, दिशाएँ विपरीत</div></div>;
 if(type==='mass'||type==='weight'||type==='formulaSummary') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-formula-main">{type==='mass'?'द्रव्यमान = पदार्थ की मात्रा':type==='weight'?'भार W = mg':'F = Gm₁m₂/r²  |  W = mg'}</div><div className="sc3-formula-sub">{type==='mass'?'इकाई: kg • स्थान बदलने पर सामान्यतः वही रहता है':type==='weight'?'इकाई: न्यूटन (N) • g के साथ बदलता है':'सही सूत्र चुनें और इकाइयाँ जाँचें'}</div></div>;
 if(type==='weightExample') return <div className="sc3-motion-diagram sc3-weightExample" aria-hidden="true"><div className="sc3-calculation"><strong>m = 2 kg</strong><span>×</span><strong>g = 9.8 m/s²</strong><span>=</span><b>W = 19.6 N</b></div><div className="sc3-calculation-note">भार = द्रव्यमान × गुरुत्वीय त्वरण</div></div>;
 if(type==='moonWeight') return <div className="sc3-motion-diagram sc3-moonWeight" aria-hidden="true"><div className="sc3-planet-compare"><div><span>🌍</span><b>पृथ्वी</b><strong>W</strong></div><i>→ लगभग 1/6 →</i><div><span>🌙</span><b>चंद्रमा</b><strong>W/6</strong></div></div><div className="sc3-compare-note">द्रव्यमान वही, भार कम</div></div>;
 if(type==='heightG') return <div className="sc3-motion-diagram sc3-heightG" aria-hidden="true"><div className="sc3-height-earth">🌍</div><div className="sc3-height-object">●</div><div className="sc3-height-line"/><div className="sc3-height-label">ऊँचाई ↑ → पृथ्वी से दूरी ↑ → g ↓</div></div>;
 if(type==='orbitGravity') return <div className="sc3-motion-diagram sc3-orbitGravity" aria-hidden="true"><div className="sc3-orbit-path"><span>🌍</span><b>●</b></div><div className="sc3-orbit-force">Fᵍ ↙</div><div className="sc3-orbit-note">गुरुत्वाकर्षण केंद्र की ओर खींचता है</div></div>;
 if(type==='upDown') return <div className="sc3-motion-diagram sc3-upDown" aria-hidden="true"><div className="sc3-trajectory"><span>●</span></div><div className="sc3-trajectory-label"><span>↑ वेग घटता है</span><span>• उच्चतम बिंदु</span><span>↓ फिर नीचे</span></div></div>;
 if(type==='dailyGravity') return <div className="sc3-motion-diagram sc3-dailyGravity" aria-hidden="true"><div className="sc3-daily-icons"><span>🍎<b>गिरना</b></span><span>🌊<b>ज्वार</b></span><span>🛰️<b>कक्षा</b></span></div><div className="sc3-daily-note">गुरुत्वाकर्षण रोज़मर्रा की कई घटनाओं में सक्रिय है</div></div>;
 if(type==='force'||type==='pushPull'||type==='effects'||type==='balanced'||type==='secondLaw'||type==='thirdLaw'||type==='friction') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-track"><span className="sc3-object sc3-object-a"/><span className="sc3-object sc3-object-b"/></div>{type==='balanced'&&<div className="sc3-forces"><span>← 10 N</span><strong>वस्तु</strong><span>10 N →</span></div>}{type==='pushPull'&&<div className="sc3-force-arrows"><span>↤ खिंचाव</span><span>धक्का ↦</span></div>}{type==='secondLaw'&&<div className="sc3-force-arrows"><span>F ↦</span><strong>m</strong><span>a ↦</span></div>}{type==='thirdLaw'&&<div className="sc3-force-arrows"><span>क्रिया ↦</span><strong>◉ ◉</strong><span>↤ प्रतिक्रिया</span></div>}{type==='friction'&&<div className="sc3-force-arrows"><span>बल ↦</span><strong>▰</strong><span>← घर्षण</span></div>}{(type==='force'||type==='effects')&&<div className="sc3-action-sequence"><span>बल</span><i>→</i><span>परिवर्तन</span><i>→</i><span>नई अवस्था</span></div>}</div>;
 if(type==='inertia'||type==='busStart'||type==='busStop'||type==='firstLaw') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-ground"/><div className="sc3-bus">🚌</div><div className="sc3-person">●</div>{type==='firstLaw'&&<div className="sc3-law-label">नेट बल = 0</div>}{type==='inertia'&&<div className="sc3-inertia-flow"><span>अवस्था</span><i>→</i><span>बदलाव का प्रयास</span><i>→</i><span>जड़त्व</span></div>}{(type==='busStart'||type==='busStop')&&<div className="sc3-bus-caption">{type==='busStart'?'बस आगे → शरीर पीछे की ओर':'बस रुकती है → शरीर आगे की ओर'}</div>}</div>;
 if(type==='momentum') return <div className="sc3-motion-diagram sc3-momentum" aria-hidden="true"><div className="sc3-momentum-items"><span className="sc3-ball small">●</span><b>m</b><i>×</i><span className="sc3-speed-arrow">v →</span><strong>= p</strong></div><div className="sc3-momentum-note">द्रव्यमान × वेग = संवेग</div></div>;
 if(type==='circular') return <div className="sc3-motion-diagram sc3-circular" aria-hidden="true"><div className="sc3-circle-path"><span>●</span></div><span className="sc3-circle-arrow">↗ दिशा बदलती है</span></div>;
 if(type==='momentumCollision'||type==='collision') return <div className="sc3-motion-diagram sc3-collision" aria-hidden="true"><div className="sc3-collision-balls"><span>● →</span><span>← ●</span></div><div className="sc3-collision-caption">टक्कर → कुल संवेग संरक्षित</div></div>;
 return null;
}

function SafeVisual({visual,title}){if(!visual)return null;const items=Array.isArray(visual.items)?visual.items:[];return <div className="sc3-safe-visual" aria-label={`दृश्य: ${title}`}><div className="sc3-visual-grid"><span className="sc3-visual-kicker">अध्याय दृश्य</span><strong>{visual.title||title}</strong><VisualDiagram visual={visual}/><div className="sc3-visual-items">{items.map((item,index)=><div className="sc3-visual-item" key={`${item}-${index}`}><b>{index+1}</b><span>{item}</span></div>)}</div></div></div>}

function LearnView({chapter,data,onBack,addXp,finishSession}){
 const lessons=data?.lessons||[];
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[completed,setCompleted]=useState(false);
 const item=lessons[index]||lessons[0],selected=answers[index],percent=lessons.length?Math.round(((index+1)/lessons.length)*100):0;
 useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});},[]);
 const goTo=i=>{if(!lessons.length)return;const bounded=Math.max(0,Math.min(lessons.length-1,i));setIndex(bounded);window.scrollTo({top:0,left:0,behavior:'auto'});};
 const choose=value=>{if(selected===undefined)setAnswers(prev=>({...prev,[index]:value}));};
 const next=()=>{if(!item)return;if(item.question&&selected===undefined)return;if(index<lessons.length-1){goTo(index+1);return;}if(completed)return;const pending=lessons.some((x,i)=>x.question&&answers[i]===undefined);if(pending)return;setCompleted(true);const correct=lessons.reduce((n,x,i)=>n+(x.question&&Number(answers[i])===Number(x.answer)?1:0),0);addXp?.(20);finishSession?.({subject:'विज्ञान',chapter,mode:'learn',attempted:lessons.filter(x=>x.question).length,correct,completed:true,at:Date.now()});window.scrollTo({top:0,left:0,behavior:'auto'});};
 if(!lessons.length)return <main className="page"><header className="page-header"><button type="button" className="pressable" onClick={onBack}>← अध्याय</button><h1>अध्याय सामग्री उपलब्ध नहीं है</h1><p>इस अध्याय की सीखने की सामग्री अभी जोड़ी जानी बाकी है।</p></header></main>;
 if(completed)return <main className="page sc3-learn-page"><nav className="sc3-learn-nav"><button type="button" className="pressable" onClick={onBack}>← अध्याय</button><div className="sc3-nav-title"><strong>{chapter}</strong><span>सीखना पूरा</span></div></nav><section className="sc3-learn-hero"><span className="eyebrow">विज्ञान • {chapter}</span><h1>अध्याय पूरा हुआ 🎉</h1><p>आपने सभी {lessons.length} सीखने के चरण पूरे किए।</p></section><section className="sc3-learn-layout"><div className="sc3-learn-main-only"><div className="sc3-learn-complete"><div className="icon">📚</div><h2>बहुत बढ़िया!</h2><p>अब अभ्यास में अपनी समझ और मजबूत करें।</p><button type="button" className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></div></section></main>;
 return <main className="page sc3-learn-page"><nav className="sc3-learn-nav"><button type="button" className="pressable" onClick={onBack}>← अध्याय</button><div className="sc3-nav-title"><strong>{chapter}</strong><span>📖 सीखें</span></div><div className="sc3-nav-progress" style={{'--sc3-progress':`${percent}%`}}><div><span>चरण {index+1}/{lessons.length}</span><span>{percent}%</span></div><i/></div></nav><section className="sc3-learn-hero"><span className="eyebrow">विज्ञान • {chapter}</span><h1>{chapter}</h1><p>विषय चुनें, पढ़ें, उदाहरण देखें और अपनी समझ जाँचें।</p></section><section className="sc3-learn-layout"><aside className="sc3-contents" aria-label="अध्याय सूची"><div className="sc3-contents-head"><strong>अध्याय सूची</strong><span>{lessons.length} सीखने के चरण</span></div><div className="sc3-contents-list">{lessons.map((lesson,i)=><button type="button" className={`pressable ${i===index?'is-active':''}`} key={`${lesson.title}-${i}`} onClick={()=>goTo(i)} aria-current={i===index?'page':undefined}><span className="sc3-num">{i+1}</span><span className="sc3-copy"><strong>{lesson.title}</strong><small>{typeLabel[lesson.type]||'पाठ'}</small></span></button>)}</div></aside><article className="sc3-lesson"><div className="sc3-lesson-meta"><span className="sc3-lesson-type">{typeLabel[item.type]||'पाठ'}</span><span>चरण {index+1} / {lessons.length}</span></div><h2>{item.title}</h2><p className="sc3-lesson-body">{item.body||item.explanation||''}</p><SafeVisual visual={item.visual} title={item.title}/>{item.points&&<ul className="sc3-points">{item.points.map(point=><li key={point}>{point}</li>)}</ul>}{item.question&&<div className="sc3-check"><strong>🎯 त्वरित जाँच</strong><p>{item.question}</p>{item.options.map((option,i)=><button type="button" disabled={selected!==undefined} className={`pressable ${selected!==undefined&&i===item.answer?'correct':''} ${selected===i&&i!==item.answer?'wrong':''}`} key={option} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}{selected!==undefined&&<div className={`sc3-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ बिल्कुल सही':'✗ उत्तर समझें'}</strong><p>{item.explain}</p></div>}</div>}<div className="sc3-lesson-actions"><button type="button" className="secondary-btn pressable" onClick={onBack}>बाद में</button><div className="sc3-next-group"><button type="button" className="secondary-btn pressable" disabled={index===0} onClick={()=>goTo(index-1)}>← पिछला</button><button type="button" className="primary-btn pressable" disabled={Boolean(item.question&&selected===undefined)} onClick={next}>{index===lessons.length-1?'अध्याय पूरा करें':'अगला →'}</button></div></div></article></section></main>;
}

function shuffleArray(list){const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function prepareQuestion(question){const options=(question?.options||[]).map((text,index)=>({text,index}));const shuffled=shuffleArray(options);return {...question,options:shuffled.map(x=>x.text),answer:shuffled.findIndex(x=>x.index===question.answer)};}

function Assessment({mode,chapter,bank,onBack,addXp,finishSession}){
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[responses,setResponses]=useState([]);
 const items=useMemo(()=>{const source=mode==='challenge'?(bank?.challenge||[]):(bank?.questions||[]);const limit=mode==='challenge'?Math.min(10,source.length):mode==='test'?Math.min(20,source.length):source.length;return shuffleArray(source).slice(0,limit).map(prepareQuestion);},[mode,bank]);
 const item=items[index];
 const choose=i=>{if(selected!==null||!item)return;setSelected(i);if(i===item.answer)setScore(s=>s+1);setResponses(prev=>[...prev,{question:item,selected:i}]);addXp?.(i===item.answer?(mode==='challenge'?25:10):0);};
 const next=()=>{if(selected===null||!item)return;const final=score+(selected===item.answer?1:0);if(index===items.length-1){setScore(final);setDone(true);markStageComplete(`विज्ञान::${chapter}`,mode);finishSession?.({subject:'विज्ञान',chapter,mode,attempted:items.length,correct:final,completed:true,at:Date.now()});}else{setIndex(i=>i+1);setSelected(null);}};
 if(!items.length)return <main className="page"><header className="page-header"><button type="button" className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">सामग्री जाँच</div><h1>प्रश्न उपलब्ध नहीं हैं</h1><p>इस मोड के लिए प्रश्न बैंक अभी उपलब्ध नहीं है।</p></header><section className="page-content"><div className="science-complete"><button type="button" className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
 if(done){const pct=Math.round(score/items.length*100);return <main className="page"><header className="page-header"><button type="button" className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">परिणाम</div><h1>{pct>=80?'बहुत बढ़िया!':pct>=50?'अच्छी कोशिश!':'फिर से अभ्यास करें'}</h1><p>{score} / {items.length} सही • {pct}%</p></header><section className="page-content"><div className="science-complete"><h2>आपका परिणाम</h2><p>{mode==='test'?'टेस्ट':mode==='challenge'?'चुनौती':'अभ्यास'} पूरा हुआ। नीचे हर प्रश्न का उत्तर और कारण देखें।</p><div className="science-review-list">{responses.map((entry,i)=>{const correct=entry.selected===entry.question.answer;return <article className={`science-review-item ${correct?'review-correct':'review-wrong'}`} key={`${entry.question.question}-${i}`}><div><strong>प्रश्न {i+1}</strong><span>{correct?'✓ सही':'✗ गलत'}</span></div><h3>{entry.question.question}</h3><p><b>आपका उत्तर:</b> {entry.question.options[entry.selected]||'उत्तर नहीं चुना'}</p><p><b>सही उत्तर:</b> {entry.question.options[entry.question.answer]}</p><p><b>क्यों?</b> {entry.question.explain}</p></article>;})}</div><button type="button" className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
 }
 return <main className="page"><header className="page-header"><button type="button" className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">विज्ञान • {chapter}</span><span>{index+1} / {items.length}</span></div><h1>{mode==='test'?'🎯 टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="quiz-progress"><span style={{width:`${((index+1)/items.length)*100}%`}}/></div></header><section className="page-content"><article className="science-question-card"><span className="question-number">प्रश्न {index+1}</span><h2>{item.question}</h2><div className="science-options">{item.options.map((option,i)=><button type="button" disabled={selected!==null} className={`answer-option pressable ${selected!==null&&i===item.answer?'correct':''} ${selected===i&&i!==item.answer?'wrong':''} ${selected!==null&&i!==selected&&i!==item.answer?'muted':''}`} key={`${option}-${i}`} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{selected!==null&&<div className={`science-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{item.explain}</p></div>}<div className="science-quiz-actions"><span>{selected===null?'उत्तर चुनें':'उत्तर दर्ज हो गया • सही उत्तर देखें'}</span><button type="button" className="primary-btn pressable" disabled={selected===null} onClick={next}>{index===items.length-1?'परिणाम देखें':'अगला →'}</button></div></article></section></main>;
}

export function ScienceNextChapterEngine({chapter,data,bank,onBack,addXp,finishSession}){const [mode,setMode]=useState(null);if(mode==='learn')return <LearnView chapter={chapter} data={data} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;if(mode)return <Assessment mode={mode} chapter={chapter} bank={bank} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;return <main className="page science-chapter-page"><header className="page-header science-header"><button type="button" className="pressable" onClick={onBack}>← विषय</button><div className="badge">कक्षा 9 • विज्ञान • अध्याय</div><h1>{chapter}</h1><p>पहले सीखें, फिर अभ्यास, चुनौती और टेस्ट से अपनी समझ मजबूत करें।</p></header><section className="page-content"><div className="science-launch"><div className="science-launch-art"><div className="science-orbit"/><div className="science-flask">◉</div><span className="science-bubble b1"/><span className="science-bubble b2"/><span className="science-bubble b3"/></div><div><span className="science-kicker">अध्याय यात्रा</span><h2>{data.goal}</h2><p>मुख्य अवधारणाएँ छोटे-छोटे चरणों में सीखें और फिर अपनी समझ को परखें।</p></div></div><div className="science-mode-grid"><button type="button" className="mode-card pressable" onClick={()=>setMode('learn')}><span>📖</span><strong>सीखें</strong><small>{data.lessons.length} सीखने के चरण</small><b>शुरू करें →</b></button><button type="button" className="mode-card pressable" onClick={()=>setMode('practice')}><span>📝</span><strong>अभ्यास</strong><small>{bank?.questions?.length||0} प्रश्न</small><b>अभ्यास करें →</b></button><button type="button" className="mode-card pressable" onClick={()=>setMode('challenge')}><span>🔥</span><strong>चुनौती</strong><small>{bank?.challenge?.length||0} कठिन प्रश्न</small><b>चुनौती लें →</b></button><button type="button" className="mode-card pressable" onClick={()=>setMode('test')}><span>🎯</span><strong>टेस्ट</strong><small>{Math.min(20,bank?.questions?.length||0)} प्रश्न</small><b>टेस्ट दें →</b></button></div></section></main>;}
