import React,{useEffect,useMemo,useState} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import {scienceChapter7Learning} from './scienceChapter7Learning';
import './scienceChapter7.css';

const questions=[
 {q:'समय के साथ वस्तु की स्थिति बदलने को क्या कहते हैं?',o:['गति','द्रव्यमान','तापमान','घनत्व'],a:0,e:'समय के साथ स्थिति बदलना गति कहलाता है।'},
 {q:'दूरी किसे दर्शाती है?',o:['वस्तु द्वारा तय किए गए कुल पथ की लंबाई','केवल प्रारम्भ और अंत की सीधी रेखा','केवल दिशा','केवल समय'],a:0,e:'दूरी वास्तविक पथ की कुल लंबाई है।'},
 {q:'विस्थापन में क्या शामिल होता है?',o:['परिमाण और दिशा','केवल समय','केवल कुल पथ','केवल द्रव्यमान'],a:0,e:'विस्थापन प्रारम्भिक से अंतिम स्थिति का निर्देशित सबसे छोटा परिवर्तन है।'},
 {q:'एक विद्यार्थी 30 m आगे जाकर 30 m वापस लौटता है। कुल दूरी कितनी है?',o:['60 m','0 m','30 m','15 m'],a:0,e:'कुल दूरी = 30 + 30 = 60 m।'},
 {q:'उसी स्थिति में विद्यार्थी का विस्थापन कितना है?',o:['0 m','60 m','30 m','15 m'],a:0,e:'वह प्रारम्भिक स्थान पर लौट आया, इसलिए विस्थापन 0 m है।'},
 {q:'औसत चाल का सूत्र क्या है?',o:['कुल दूरी ÷ कुल समय','कुल समय ÷ कुल दूरी','विस्थापन ÷ समय','समय × दूरी'],a:0,e:'औसत चाल = कुल दूरी / कुल समय।'},
 {q:'वेग और चाल में मुख्य अंतर क्या है?',o:['वेग में दिशा भी होती है','चाल में हमेशा दिशा होती है','वेग में समय नहीं होता','दोनों हमेशा समान होते हैं'],a:0,e:'चाल अदिश है; वेग दिशा सहित गति बताता है।'},
 {q:'त्वरण किसकी परिवर्तन दर है?',o:['वेग की','द्रव्यमान की','तापमान की','लंबाई की'],a:0,e:'त्वरण समय के साथ वेग में परिवर्तन की दर है।'},
 {q:'त्वरण का SI मात्रक क्या है?',o:['m/s²','m/s','m','s'],a:0,e:'त्वरण का SI मात्रक m/s² है।'},
 {q:'दूरी-समय ग्राफ में समय किस अक्ष पर लिया जाता है?',o:['x-अक्ष','y-अक्ष','दोनों पर हमेशा','किसी अक्ष पर नहीं'],a:0,e:'दूरी-समय ग्राफ में समय x-अक्ष और दूरी y-अक्ष पर होती है।'},
 {q:'दूरी-समय ग्राफ की ढाल क्या बताती है?',o:['चाल','द्रव्यमान','बल','तापमान'],a:0,e:'दूरी/समय की ढाल चाल बताती है।'},
 {q:'वेग-समय ग्राफ की ढाल क्या बताती है?',o:['त्वरण','दूरी','द्रव्यमान','समय'],a:0,e:'वेग/समय की ढाल त्वरण बताती है।'},
 {q:'समान त्वरण वाली गति के लिए पहला समीकरण कौन-सा है?',o:['v = u + at','s = vt','F = ma','p = mv'],a:0,e:'समान त्वरण में v = u + at पहला गति समीकरण है।'},
 {q:'s = ut + ½at² में u क्या है?',o:['प्रारम्भिक वेग','अंतिम वेग','त्वरण','समय'],a:0,e:'u प्रारम्भिक वेग को दर्शाता है।'},
 {q:'यदि u = 0, a = 2 m/s² और t = 5 s हो, तो v कितना होगा?',o:['10 m/s','2 m/s','5 m/s','25 m/s'],a:0,e:'v = u + at = 0 + 2×5 = 10 m/s।'},
 {q:'यदि वस्तु समान समय में समान दूरी तय करती है, तो उसकी गति कैसी है?',o:['समान गति','असमान गति','केवल वृत्तीय गति','कोई गति नहीं'],a:0,e:'समान समयांतराल में समान दूरी तय करना समान गति की पहचान है।'},
 {q:'वृत्ताकार पथ पर समान चाल से चलती वस्तु का वेग क्यों बदलता है?',o:['दिशा लगातार बदलती रहती है','द्रव्यमान लगातार बदलता है','समय रुक जाता है','चाल शून्य हो जाती है'],a:0,e:'चाल समान रह सकती है, लेकिन दिशा बदलती रहती है; इसलिए वेग बदलता है।'},
 {q:'एक पूरा वृत्त लगाकर उसी स्थान पर लौटने पर विस्थापन क्या होगा?',o:['शून्य','व्यास','त्रिज्या','पूरी परिधि'],a:0,e:'प्रारम्भिक और अंतिम स्थान समान होने से विस्थापन शून्य है।'},
 {q:'वेग-समय ग्राफ के नीचे का क्षेत्र किससे संबंधित है?',o:['विस्थापन','द्रव्यमान','तापमान','घनत्व'],a:0,e:'वेग-समय ग्राफ के नीचे का क्षेत्र विस्थापन देता है।'},
 {q:'यदि वेग समय के साथ घट रहा है, तो किस स्थिति का संकेत मिल सकता है?',o:['मंदन या ऋणात्मक त्वरण','हमेशा शून्य त्वरण','हमेशा समान चाल','द्रव्यमान में वृद्धि'],a:0,e:'वेग घटने पर चुनी दिशा के सापेक्ष ऋणात्मक त्वरण या मंदन हो सकता है।'},
 {q:'औसत वेग किससे निकाला जाता है?',o:['कुल विस्थापन ÷ कुल समय','कुल दूरी ÷ कुल समय','कुल समय ÷ कुल विस्थापन','दूरी × समय'],a:0,e:'औसत वेग = कुल विस्थापन / कुल समय।'},
 {q:'संदर्भ बिंदु क्यों आवश्यक है?',o:['स्थिति को किसी निश्चित बिंदु के सापेक्ष बताने के लिए','केवल द्रव्यमान मापने के लिए','केवल तापमान जानने के लिए','केवल रंग पहचानने के लिए'],a:0,e:'स्थिति और गति का वर्णन संदर्भ बिंदु के सापेक्ष किया जाता है।'},
 {q:'दूरी-समय ग्राफ क्षैतिज सीधी रेखा हो तो वस्तु क्या कर रही है?',o:['विराम में है','बहुत तेज चल रही है','समान त्वरण में है','वृत्तीय गति कर रही है'],a:0,e:'समय बढ़ने पर दूरी न बदले तो वस्तु विराम में है।'}
];

const challenge=[
 {q:'एक वस्तु 80 m पूर्व और फिर 30 m पश्चिम जाती है। विस्थापन कितना है?',o:['50 m पूर्व','110 m पूर्व','50 m पश्चिम','110 m पश्चिम'],a:0,e:'पूर्व को धनात्मक लें: 80 − 30 = 50 m पूर्व।'},
 {q:'20 m/s की चाल से 5 s में तय दूरी कितनी होगी?',o:['100 m','25 m','4 m','200 m'],a:0,e:'दूरी = चाल × समय = 20 × 5 = 100 m।'},
 {q:'दूरी और विस्थापन का परिमाण बराबर कब हो सकता है?',o:['सीधे एक ही दिशा में चलने पर','हर स्थिति में','पूरा चक्कर लगाने पर','जब दूरी शून्य हो'],a:0,e:'सीधे एक दिशा में जाने पर वास्तविक पथ और सबसे छोटा निर्देशित परिवर्तन बराबर हो सकते हैं।'},
 {q:'u = 5 m/s, a = 3 m/s², t = 4 s हो तो अंतिम वेग?',o:['17 m/s','12 m/s','8 m/s','20 m/s'],a:0,e:'v = u + at = 5 + 3×4 = 17 m/s।'},
 {q:'वेग 10 m/s से 25 m/s तक 3 s में बदलता है। त्वरण?',o:['5 m/s²','15 m/s²','7.5 m/s²','35 m/s²'],a:0,e:'a = (25−10)/3 = 5 m/s²।'},
 {q:'दूरी-समय ग्राफ की ढाल 6 m/s है। इसका अर्थ क्या है?',o:['चाल 6 m/s है','त्वरण 6 m/s² है','विस्थापन 6 m है','समय 6 s है'],a:0,e:'दूरी-समय ग्राफ की ढाल चाल बताती है।'},
 {q:'वृत्तीय गति में समान चाल के बावजूद वेग बदलने का कारण?',o:['दिशा बदलती है','समय बदलना बंद करता है','द्रव्यमान शून्य होता है','दूरी शून्य होती है'],a:0,e:'वेग सदिश है; दिशा बदलने पर वेग बदलता है।'},
 {q:'वेग-समय ग्राफ की ढाल 2 m/s² है। यह क्या बताती है?',o:['त्वरण 2 m/s²','चाल 2 m/s','दूरी 2 m','विस्थापन 2 m'],a:0,e:'v-t ग्राफ की ढाल त्वरण देती है।'},
 {q:'एक धावक 100 m आगे और 100 m वापस आता है। दूरी और विस्थापन?',o:['दूरी 200 m, विस्थापन 0 m','दूरी 0 m, विस्थापन 200 m','दोनों 100 m','दोनों 200 m'],a:0,e:'पूरा पथ 200 m है और प्रारम्भिक स्थान पर लौटने से विस्थापन 0 m है।'},
 {q:'समान त्वरण में कौन-सा समीकरण t के बिना v और u को जोड़ता है?',o:['v² = u² + 2as','v = u + at','s = ut + ½at²','a = v/t'],a:0,e:'v² = u² + 2as में समय t सीधे उपस्थित नहीं है।'}
];

function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function prepare(q){const mapped=q.o.map((text,index)=>({text,index}));const s=shuffle(mapped);return {...q,o:s.map(x=>x.text),a:s.findIndex(x=>x.index===q.a)};}

function MotionVisual({visual}){
 const type=visual?.type||'motion';
 const title=visual?.title||'गति का दृश्य';
 const common=<><span className="c7-visual-kicker">चलता हुआ दृश्य</span><strong>{title}</strong></>;
 if(type==='reference')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><svg viewBox="0 0 720 190" role="img" aria-label="संदर्भ बिंदु का दृश्य"><rect x="55" y="75" width="480" height="65" rx="18" className="bus"/><rect x="90" y="45" width="90" height="35" rx="8" className="window"/><rect x="195" y="45" width="90" height="35" rx="8" className="window"/><circle cx="135" cy="145" r="18" className="wheel"/><circle cx="455" cy="145" r="18" className="wheel"/><circle cx="240" cy="105" r="12" className="person"/><path d="M565 145h90" className="axis"/><path d="M645 138l10 7-10 7" className="axis"/><path d="M575 145v-45" className="axis"/><text x="570" y="92">सड़क</text><text x="205" y="32">बस के सापेक्ष: विराम</text><text x="545" y="170">संदर्भ दिशा</text></svg></div>;
 if(type==='distance')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><svg viewBox="0 0 720 190" role="img" aria-label="दूरी का वास्तविक पथ"><path d="M70 135 C160 35 235 165 330 75 S500 35 640 130" className="route"/><circle cx="70" cy="135" r="9" className="start"/><circle cx="640" cy="130" r="9" className="end"/><text x="48" y="165">आरम्भ</text><text x="600" y="160">अंत</text><text x="250" y="50">पूरा वास्तविक पथ = दूरी</text></svg></div>;
 if(type==='displacement')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><svg viewBox="0 0 720 210" role="img" aria-label="दूरी और विस्थापन का अंतर"><path d="M75 150 C150 40 245 185 335 80 S500 35 625 150" className="route"/><path d="M75 150 L625 150" className="direct"/><circle cx="75" cy="150" r="10" className="start"/><circle cx="625" cy="150" r="10" className="end"/><text x="82" y="45">घुमावदार पथ → दूरी</text><text x="265" y="178">सीधा तीर → विस्थापन</text></svg></div>;
 if(type==='uniform'||type==='nonuniform')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><div className={`c7-bars ${type}`}><div><span>1 s</span><i style={{'--w':type==='uniform'?'34%':'22%'}}/></div><div><span>2 s</span><i style={{'--w':type==='uniform'?'34%':'52%'}}/></div><div><span>3 s</span><i style={{'--w':type==='uniform'?'34%':'15%'}}/></div></div></div>;
 if(type==='speed'||type==='velocity')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><div className="c7-formula"><div><b>{type==='velocity'?'विस्थापन':'दूरी'}</b><span>÷ समय</span></div><strong>=</strong><div className="formula-result">{type==='velocity'?'वेग → दिशा सहित':'चाल'}</div></div></div>;
 if(type==='speedVelocity')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><div className="c7-compare"><article><b>चाल</b><span>दूरी ÷ समय</span><small>अदिश</small></article><article><b>वेग</b><span>विस्थापन ÷ समय</span><small>सदिश + दिशा</small></article></div></div>;
 if(type==='acceleration')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><div className="c7-accel"><span>u = 5</span><i/><span>v = 10</span><i/><span>v = 15</span><i/><span>वेग बढ़ता है</span></div></div>;
 if(type==='circular')return <div className="c7-visual"><div className="c7-visual-head">{common}</div><svg viewBox="0 0 720 220" role="img" aria-label="वृत्तीय गति"><circle cx="360" cy="110" r="72" className="orbit"/><circle cx="360" cy="110" r="5" className="center"/><path d="M360 38v-28M360 10l-8 10M360 10l8 10" className="direct"/><circle cx="432" cy="110" r="12" className="moving"/><text x="330" y="126">केंद्र</text><text x="445" y="105">वस्तु</text><text x="382" y="25">दिशा बदलती है</text></svg></div>;
 if(type==='distanceTime')return <Graph title={title} x="समय" y="दूरी" path="M70 170 L650 55" label="ढाल = चाल"/>;
 if(type==='velocityTime')return <Graph title={title} x="समय" y="वेग" path="M70 170 L650 65" label="ढाल = त्वरण"/>;
 return <div className="c7-visual"><div className="c7-visual-head">{common}</div><svg viewBox="0 0 720 190" role="img" aria-label="गति का क्रम"><path d="M80 125H630" className="axis"/><path d="M610 115l20 10-20 10" className="axis"/><circle cx="120" cy="125" r="14" className="moving"/><circle cx="350" cy="125" r="14" className="moving"/><circle cx="580" cy="125" r="14" className="moving"/><text x="90" y="75">प्रारम्भ</text><text x="320" y="75">समय बीता</text><text x="540" y="75">नई स्थिति</text></svg></div>;
}

function Graph({title,x,y,path,label}){return <div className="c7-visual"><div className="c7-visual-head"><span className="c7-visual-kicker">ग्राफ</span><strong>{title}</strong></div><svg viewBox="0 0 720 250" role="img" aria-label={title}><path d="M75 205V35M75 205H665" className="axis"/><path d={path} className="graph-line"/><text x="640" y="228">{x}</text><text x="18" y="50">{y}</text><text x="285" y="75">{label}</text></svg></div>}

function Lesson({lesson,index,total,onPrev,onNext,onBack}){
 const [selected,setSelected]=useState(null);
 useEffect(()=>{setSelected(null);window.scrollTo({top:0,left:0,behavior:'auto'});},[index]);
 const locked=lesson.question&&selected===null;
 return <main className="page c7-page"><header className="c7-top"><button type="button" className="c7-btn ghost" onClick={onBack}>← अध्याय</button><div><b>{lesson.title}</b><span>चरण {index+1} / {total}</span></div><div className="c7-progress"><i style={{width:`${((index+1)/total)*100}%`}}/></div></header><section className="c7-learning"><aside className="c7-outline"><div><b>अध्याय यात्रा</b><small>{total} सीखने के चरण</small></div><nav>{scienceChapter7Learning.lessons.map((x,i)=><button type="button" key={`${x.title}-${i}`} className={i===index?'active':''} onClick={()=>onNext(i)}><span>{i+1}</span><strong>{x.title}</strong></button>)}</nav></aside><article className="c7-card"><div className="c7-type">{lesson.type==='check'?'त्वरित जाँच':lesson.type==='example'?'उदाहरण':lesson.type==='concept'?'अवधारणा':'परिचय'}</div><h1>{lesson.title}</h1><p className="c7-body">{lesson.body}</p>{lesson.visual&&<MotionVisual visual={lesson.visual}/>} {lesson.points&&<ul className="c7-points">{lesson.points.map(p=><li key={p}>{p}</li>)}</ul>}{lesson.question&&<div className="c7-check"><h3>🎯 अपनी समझ जाँचें</h3><p>{lesson.question}</p>{lesson.options.map((o,i)=><button type="button" key={o} disabled={selected!==null} className={`c7-option ${selected!==null&&i===lesson.answer?'correct':''} ${selected===i&&i!==lesson.answer?'wrong':''}`} onClick={()=>setSelected(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}{selected!==null&&<div className={`c7-feedback ${selected===lesson.answer?'good':'bad'}`}><b>{selected===lesson.answer?'✓ बिल्कुल सही':'✗ उत्तर समझें'}</b><p>{lesson.explain}</p></div>}</div>}<footer className="c7-actions"><button type="button" className="c7-btn secondary" onClick={onBack}>बाद में</button><div><button type="button" className="c7-btn secondary" disabled={index===0} onClick={()=>onPrev(index-1)}>← पिछला</button><button type="button" className="c7-btn primary" disabled={locked} onClick={()=>onNext(index+1)}>{index===total-1?'अध्याय पूरा करें':'अगला →'}</button></div></footer></article></section></main>;
}

function Assessment({mode,onBack,addXp,finishSession}){
 const source=mode==='challenge'?challenge:questions;
 const items=useMemo(()=>shuffle(source).slice(0,mode==='challenge'?10:mode==='test'?20:15).map(prepare),[mode]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[responses,setResponses]=useState([]);
 const item=items[index];
 if(!item)return null;
 const choose=i=>{if(selected!==null)return;setSelected(i);setResponses(r=>[...r,{item,selected:i}]);if(i===item.a)setScore(s=>s+1);addXp?.(i===item.a?(mode==='challenge'?25:10):0);};
 const next=()=>{if(selected===null)return;const final=score+(selected===item.a?1:0);if(index===items.length-1){setScore(final);setDone(true);markStageComplete(`विज्ञान::गति`,mode);finishSession?.({subject:'विज्ञान',chapter:'गति',mode,attempted:items.length,correct:final,completed:true,at:Date.now()});}else{setIndex(i=>i+1);setSelected(null);}};
 if(done){const pct=Math.round(score/items.length*100);return <main className="page c7-assess"><header className="c7-assess-head"><button type="button" className="c7-btn ghost" onClick={onBack}>← अध्याय</button><span>परिणाम</span><h1>{pct>=80?'शानदार!':pct>=50?'अच्छी कोशिश!':'फिर से अभ्यास करें'}</h1><p>{score} / {items.length} सही • {pct}%</p></header><section className="c7-result"><div className="c7-score-ring" style={{'--score':`${pct}%`}}><strong>{pct}%</strong><span>स्कोर</span></div><div className="c7-review">{responses.map((r,i)=><article key={`${r.item.q}-${i}`} className={r.selected===r.item.a?'right':'wrong'}><div><b>प्रश्न {i+1}</b><span>{r.selected===r.item.a?'✓ सही':'✗ गलत'}</span></div><h3>{r.item.q}</h3><p><b>आपका उत्तर:</b> {r.item.o[r.selected]}</p><p><b>सही उत्तर:</b> {r.item.o[r.item.a]}</p><p><b>क्यों?</b> {r.item.e}</p></article>)}</div><button type="button" className="c7-btn primary wide" onClick={onBack}>अध्याय पर लौटें →</button></section></main>}
 return <main className="page c7-assess"><header className="c7-assess-head"><button type="button" className="c7-btn ghost" onClick={onBack}>← अध्याय</button><div><span>{mode==='test'?'🎯 टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</span><b>{index+1} / {items.length}</b></div><h1>प्रश्न {index+1}</h1><p>{item.q}</p><div className="c7-question-progress"><i style={{width:`${((index+1)/items.length)*100}%`}}/></div></header><section className="c7-question"><div className="c7-options">{item.o.map((o,i)=><button type="button" key={`${o}-${i}`} disabled={selected!==null} className={`c7-option ${selected!==null&&i===item.a?'correct':''} ${selected===i&&i!==item.a?'wrong':''} ${selected!==null&&i!==selected&&i!==item.a?'muted':''}`} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{selected!==null&&<div className={`c7-feedback ${selected===item.a?'good':'bad'}`}><b>{selected===item.a?'✓ सही उत्तर':'✗ गलत उत्तर'}</b><p>{item.e}</p></div>}<div className="c7-quiz-actions"><span>{selected===null?'एक उत्तर चुनें':'उत्तर लॉक हो गया'}</span><button type="button" className="c7-btn primary" disabled={selected===null} onClick={next}>{index===items.length-1?'परिणाम देखें':'अगला →'}</button></div></section></main>;
}

export function ScienceChapter7Engine({chapter='गति',onBack,addXp,finishSession}){
 const [mode,setMode]=useState(null);
 if(mode==='learn')return <Lesson lesson={scienceChapter7Learning.lessons[0]} index={0} total={scienceChapter7Learning.lessons.length} onBack={()=>setMode(null)} onPrev={()=>{}} onNext={i=>setMode(i>=scienceChapter7Learning.lessons.length?'complete':`lesson-${i}`)}/>;
 if(typeof mode==='string'&&mode.startsWith('lesson-')){const i=Number(mode.split('-')[1]);if(i<scienceChapter7Learning.lessons.length)return <Lesson lesson={scienceChapter7Learning.lessons[i]} index={i} total={scienceChapter7Learning.lessons.length} onBack={()=>setMode(null)} onPrev={j=>setMode(j<0?'learn':`lesson-${j}`)} onNext={j=>setMode(j>=scienceChapter7Learning.lessons.length?'complete':`lesson-${j}`)}/>;}
 if(mode==='complete')return <main className="page c7-complete"><div className="c7-complete-card"><div className="c7-trophy">🏆</div><span>अध्याय यात्रा पूरी</span><h1>गति समझने की नींव तैयार है!</h1><p>अब अभ्यास, चुनौती और टेस्ट में अपनी समझ को परखें।</p><button type="button" className="c7-btn primary" onClick={()=>setMode(null)}>अध्याय पर लौटें</button></div></main>;
 if(mode==='practice'||mode==='challenge'||mode==='test')return <Assessment mode={mode} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;
 return <main className="page c7-launch"><header className="c7-launch-head"><button type="button" className="c7-btn ghost" onClick={onBack}>← विषय</button><span>कक्षा 9 • विज्ञान • अध्याय 7</span><h1>{chapter}</h1><p>{scienceChapter7Learning.goal}</p></header><section className="c7-launch-grid"><div className="c7-hero-visual"><svg viewBox="0 0 700 260" role="img" aria-label="गति का एनिमेटेड दृश्य"><path d="M70 190 C180 80 260 230 370 125 S520 55 635 175" className="route"/><circle cx="70" cy="190" r="11" className="start"/><circle cx="635" cy="175" r="11" className="end"/><circle r="10" className="hero-dot"><animateMotion dur="4s" repeatCount="indefinite" path="M70 190 C180 80 260 230 370 125 S520 55 635 175"/></circle><text x="55" y="225">आरम्भ</text><text x="590" y="210">अंत</text><text x="225" y="55">पथ बदलता है • स्थिति बदलती है • गति</text></svg></div><div className="c7-mode-card"><span>अध्याय यात्रा</span><h2>चार चरणों में सीखो</h2><div className="c7-mode-list"><button type="button" onClick={()=>setMode('learn')}><b>01</b><span>📖 सीखें<small>अवधारणा + दृश्य + त्वरित जाँच</small></span><em>→</em></button><button type="button" onClick={()=>setMode('practice')}><b>02</b><span>📝 अभ्यास<small>15 प्रश्न • उत्तर के साथ कारण</small></span><em>→</em></button><button type="button" onClick={()=>setMode('challenge')}><b>03</b><span>🔥 चुनौती<small>10 कठिन/HOTS प्रश्न</small></span><em>→</em></button><button type="button" onClick={()=>setMode('test')}><b>04</b><span>🎯 टेस्ट<small>20 प्रश्न • परिणाम समीक्षा</small></span><em>→</em></button></div></div></section></main>;
}

export default ScienceChapter7Engine;
