import React,{useEffect,useMemo,useState} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import {ScienceChapterVisual} from './ScienceChapterVisual';
import './science-chapter-visual.css';

const practice=[
['पदार्थ की सही पहचान क्या है?',['जिसका द्रव्यमान हो और स्थान घेरे','जिसे केवल देखा जा सके','जिसकी कोई ऊर्जा न हो','जो केवल ठोस हो'],0,'पदार्थ का द्रव्यमान होता है और वह स्थान घेरता है।'],
['पदार्थ के कणों के बारे में कौन-सा कथन सही है?',['वे हमेशा बहुत बड़े होते हैं','वे लगातार गति करते हैं','उनके बीच कोई स्थान नहीं होता','वे केवल गैस में पाए जाते हैं'],1,'पदार्थ के कण निरंतर गति करते रहते हैं।'],
['ठोस का कौन-सा गुण सामान्यतः सही है?',['निश्चित आकार और आयतन','निश्चित आकार लेकिन अनिश्चित आयतन','अनिश्चित आकार और आयतन','केवल आयतन निश्चित'],0,'ठोस का आकार और आयतन दोनों निश्चित होते हैं।'],
['द्रव का आकार कैसा होता है?',['हमेशा निश्चित','पात्र के अनुसार बदलता है','हमेशा गोल','हमेशा चौकोर'],1,'द्रव का आयतन निश्चित होता है, पर वह पात्र का आकार ले लेता है।'],
['गैस को आसानी से संपीडित करने का कारण क्या है?',['कणों के बीच अधिक रिक्त स्थान','कणों का रंग','कणों का भार नहीं होना','गैस का ठोस होना'],0,'गैस के कणों के बीच अपेक्षाकृत अधिक खाली स्थान होता है।'],
['स्याही का पानी में फैलना किससे समझाया जाता है?',['विसरण','गलन','हिमांक','जमना'],0,'कणों की निरंतर गति के कारण स्याही धीरे-धीरे पूरे पानी में फैलती है।'],
['तापमान बढ़ाने पर कणों की गति सामान्यतः क्या होती है?',['घटती है','बढ़ती है','रुक जाती है','हमेशा समान रहती है'],1,'तापमान बढ़ने पर कणों की औसत गतिज ऊर्जा और गति बढ़ती है।'],
['वाष्पीकरण मुख्यतः कहाँ होता है?',['पूरे द्रव में','द्रव की सतह पर','केवल तल पर','पात्र के बाहर'],1,'वाष्पीकरण सतह पर होने वाला परिवर्तन है।'],
['उबलना और वाष्पीकरण में मुख्य अंतर क्या है?',['दोनों बिल्कुल समान हैं','उबलना पूरे द्रव में होता है, वाष्पीकरण सतह पर','वाष्पीकरण केवल ठोस में होता है','उबलना केवल गैस में होता है'],1,'उबलने में पूरे द्रव में तीव्र परिवर्तन होता है, जबकि वाष्पीकरण सतह से होता है।'],
['कपूर का सीधे गैस में बदलना किसका उदाहरण है?',['गलन','ऊर्ध्वपातन','संघनन','जमना'],1,'ठोस से सीधे गैस में बदलना ऊर्ध्वपातन कहलाता है।'],
['मिट्टी के घड़े का पानी ठंडा होने का प्रमुख कारण क्या है?',['वाष्पीकरण','दहन','जमना','गलन'],0,'घड़े की सतह से पानी के वाष्पीकरण में ऊष्मा लगती है, जिससे शीतलन होता है।'],
['वाष्पीकरण को तेज करने वाला कारक कौन-सा है?',['तापमान बढ़ाना','सतह घटाना','हवा रोकना','आर्द्रता बढ़ाना'],0,'तापमान बढ़ने पर अधिक कण पर्याप्त ऊर्जा पाकर सतह से बाहर निकल सकते हैं।'],
['गैस के कण ठोस की तुलना में कैसे होते हैं?',['बहुत पास','अधिक दूर-दूर','बिल्कुल स्थिर','केवल नीचे रहते हैं'],1,'गैस के कणों के बीच अधिक दूरी और रिक्त स्थान होता है।'],
['गलन किस परिवर्तन को कहते हैं?',['द्रव से गैस','गैस से द्रव','ठोस से द्रव','गैस से ठोस'],2,'ताप देने पर ठोस के द्रव में बदलने को गलन कहते हैं।'],
['संघनन किस दिशा का परिवर्तन है?',['गैस से द्रव','द्रव से गैस','ठोस से द्रव','ठोस से गैस'],0,'गैस के द्रव में बदलने को संघनन कहते हैं।'],
['कणों के बीच आकर्षण बल सबसे अधिक सामान्यतः किस अवस्था में होता है?',['ठोस','द्रव','गैस','प्लाज़्मा'],0,'ठोस में कण बहुत पास होते हैं, इसलिए उनका पारस्परिक आकर्षण सामान्यतः अधिक प्रभावी होता है।'],
['गैस पर दबाव बढ़ाने से सामान्यतः क्या होता है?',['कणों की दूरी बढ़ती है','कणों की दूरी घट सकती है','गैस गायब हो जाती है','द्रव्यमान शून्य हो जाता है'],1,'दबाव से कणों को पास लाया जा सकता है।'],
['निम्न में कौन-सा कथन गलत है?',['हर अनंत दशमलव अपरिमेय होता है','गैस संपीडित हो सकती है','द्रव पात्र का आकार लेता है','ठोस का आयतन निश्चित होता है'],0,'आवर्ती अनंत दशमलव परिमेय हो सकते हैं; इसलिए हर अनंत दशमलव अपरिमेय नहीं होता।'],
['पसीना शरीर को ठंडा करने में कैसे मदद करता है?',['वाष्पीकरण शरीर से ऊष्मा लेता है','पसीना जम जाता है','हवा द्रव बन जाती है','शरीर ऊष्मा बनाना बंद कर देता है'],0,'वाष्पीकरण के लिए ऊष्मा चाहिए, जो शरीर की सतह से ली जाती है।'],
['एक ही पानी को चौड़े पात्र में रखने पर वह जल्दी सूख सकता है। इसका मुख्य कारण?',['बड़ा सतह क्षेत्रफल','कम कण','कम द्रव्यमान','अधिक घनत्व'],0,'अधिक सतह क्षेत्रफल से अधिक कण सतह के संपर्क में आते हैं।'],
['वाष्पीकरण की दर किन स्थितियों में बढ़ेगी?',['कम तापमान, अधिक आर्द्रता','अधिक तापमान, अधिक हवा','कम सतह क्षेत्रफल, अधिक आर्द्रता','बिना हवा और कम तापमान'],1,'अधिक तापमान और हवा की गति वाष्पीकरण को तेज कर सकती है।'],
['ठोस को गर्म करने पर कणों में क्या बदलता है?',['औसत गतिज ऊर्जा बढ़ती है','द्रव्यमान गायब होता है','कणों की संख्या शून्य होती है','कण रुक जाते हैं'],0,'ऊष्मा देने पर कणों की औसत गतिज ऊर्जा बढ़ती है।'],
['दाब बढ़ाने और तापमान घटाने से कुछ गैसों को क्या किया जा सकता है?',['द्रवित करने में सहायता','हमेशा ठोस बनाने में','द्रव्यमान खत्म करने में','प्रकाश में बदलने में'],0,'उचित परिस्थितियों में अधिक दबाव और कम तापमान गैस के द्रवीकरण में सहायता करते हैं।'],
['यदि कमरे में इत्र छिड़कने के बाद थोड़ी देर में दूर बैठे व्यक्ति तक गंध पहुँचती है, तो यह किसका प्रमाण है?',['कणों की गति और विसरण','ठोस का गलना','ऊष्मीय प्रसार का अभाव','कणों की स्थिरता'],0,'इत्र के कण हवा में फैलते हैं; यह विसरण का दैनिक जीवन का उदाहरण है।'],
['किस परिवर्तन में बीच में द्रव अवस्था आवश्यक नहीं है?',['ऊर्ध्वपातन','गलन','संघनन','उबलना'],0,'ऊर्ध्वपातन में ठोस सीधे गैस में बदल सकता है।'],
['यदि आर्द्रता बहुत अधिक हो जाए, तो वाष्पीकरण पर क्या प्रभाव पड़ता है?',['वाष्पीकरण धीमा हो सकता है','वाष्पीकरण हमेशा बहुत तेज होगा','कोई प्रभाव नहीं','द्रव ठोस बनता है'],0,'हवा में जलवाष्प अधिक होने पर नए जलवाष्प के निकलने की प्रवृत्ति घटती है।'],
['कपड़े धूप और हवा में जल्दी क्यों सूखते हैं?',['अधिक तापमान और हवा वाष्पीकरण तेज करते हैं','कपड़े पदार्थ नहीं हैं','पानी का द्रव्यमान खत्म हो जाता है','सूर्य पानी को खींचता है'],0,'धूप से तापमान बढ़ता है और हवा सतह के पास की जलवाष्प हटाती रहती है।'],
['यदि दो समान द्रवों में एक का सतह क्षेत्रफल दुगुना हो, तो बाकी परिस्थितियाँ समान होने पर क्या अपेक्षित है?',['उसमें वाष्पीकरण की दर अधिक हो सकती है','वाष्पीकरण असंभव होगा','द्रव ठोस हो जाएगा','तापमान शून्य हो जाएगा'],0,'बड़ा सतह क्षेत्रफल सामान्यतः वाष्पीकरण को तेज करता है।'],
['कणों के बीच रिक्त स्थान का सबसे अच्छा उदाहरण कौन-सा है?',['पानी में चीनी का घुलना','पत्थर का टूटना','लकड़ी का रंग','सूर्य का प्रकाश'],0,'चीनी के कण पानी के कणों के बीच उपलब्ध स्थान में फैलते हैं।'],
['किस अवस्था में कणों की अनियमित गति और दूरी सबसे अधिक होती है?',['गैस','ठोस','द्रव','सभी समान'],0,'गैस में कण दूर-दूर होते हैं और स्वतंत्र रूप से अधिक फैलते हैं।'],
['यदि किसी द्रव पर हवा की गति बढ़ाई जाए तो क्या हो सकता है?',['वाष्पीकरण तेज हो सकता है','वाष्पीकरण रुक जाएगा','द्रव का द्रव्यमान दोगुना होगा','द्रव ठोस बन जाएगा'],0,'हवा सतह के पास की जलवाष्प हटाती है, जिससे वाष्पीकरण तेज हो सकता है।'],
['वाष्पीकरण के कारण शीतलन कब स्पष्ट होगा?',['जब द्रव को ऊर्जा वाष्पीकरण के लिए मिलती है','जब द्रव बिल्कुल स्थिर हो','जब तापमान हमेशा शून्य हो','जब कोई सतह न हो'],0,'वाष्पीकरण में आवश्यक ऊर्जा आसपास से ली जाती है, जिससे शीतलन प्रभाव दिखाई देता है।'],
['एक गैस को बहुत छोटे पात्र में दबाया जाए तो सबसे पहले क्या बदलता है?',['कणों के बीच की दूरी घट सकती है','कणों की संख्या बदलती है','कण पदार्थ नहीं रहते','द्रव्यमान गायब हो जाता है'],0,'संपीड़न में उपलब्ध स्थान घटता है, इसलिए कण पास आ सकते हैं।'],
['कौन-सा कथन तीनों अवस्थाओं को सबसे सही ढंग से जोड़ता है?',['अवस्था कणों की दूरी, गति और आकर्षण से जुड़ी है','अवस्था केवल रंग पर निर्भर है','अवस्था केवल द्रव्यमान पर निर्भर है','अवस्था केवल पात्र पर निर्भर है'],0,'कणों की व्यवस्था, गति और उनके बीच आकर्षण से पदार्थ के गुण और अवस्था समझी जाती है।'],
['यदि एक बर्फ का टुकड़ा गर्म कमरे में रखा जाए तो क्रम क्या हो सकता है?',['ठोस → द्रव → गैस','गैस → द्रव → ठोस','द्रव → ठोस → गैस','ठोस → गैस → द्रव हमेशा'],0,'ताप मिलने पर बर्फ पिघलकर पानी और आगे वाष्प में बदल सकती है।'],
['वाष्पीकरण और उबलने का सही संबंध क्या है?',['दोनों द्रव से गैस परिवर्तन हैं, पर उनकी प्रक्रिया अलग है','दोनों ठोस से गैस हैं','दोनों गैस से द्रव हैं','दोनों केवल शून्य डिग्री पर होते हैं'],0,'दोनों में द्रव गैस बनता है, लेकिन वाष्पीकरण सतह से और उबलना पूरे द्रव में होता है।'],
['यदि किसी पदार्थ के कण बहुत पास हैं और आकर्षण अधिक है, तो कौन-सी अवस्था संभव है?',['ठोस','गैस','केवल वाष्प','कोई नहीं'],0,'ऐसी व्यवस्था ठोस अवस्था की विशेषता है।'],
['किस गतिविधि से पदार्थ के कणों की गति का अनुमान सबसे स्पष्ट मिलता है?',['स्याही का पानी में धीरे-धीरे फैलना','लकड़ी का टुकड़ा देखना','कागज का रंग देखना','दीवार की लंबाई नापना'],0,'विसरण के कारण स्याही का फैलना कणों की निरंतर गति को दर्शाता है।']
];

const challenge=[
 ['दो समान गिलासों में बराबर पानी है। एक को पंखे के सामने रखा गया। किसमें पानी जल्दी कम होने की संभावना है?',['पंखे के सामने','पंखे से दूर','दोनों हमेशा समान','किसी में नहीं'],0,'हवा की गति बढ़ने से सतह की जलवाष्प हटती रहती है, इसलिए वाष्पीकरण तेज हो सकता है।'],
 ['चौड़े मुँह वाले पात्र और संकरे मुँह वाले पात्र में समान मात्रा का पानी है। बाकी दशाएँ समान हैं। कौन पहले सूख सकता है?',['चौड़े मुँह वाला','संकरे मुँह वाला','दोनों अनिवार्य रूप से समान','तुलना असंभव'],0,'चौड़े पात्र का सतह क्षेत्रफल अधिक है, इसलिए वाष्पीकरण अधिक तेज हो सकता है।'],
 ['एक बंद पात्र में पानी की वाष्प ठंडी होने पर क्या होने की संभावना है?',['वाष्प का कुछ भाग द्रव बन सकता है','सारा पानी गैस बन जाएगा','द्रव्यमान नष्ट होगा','कण रुक जाएँगे'],0,'ठंडा करने पर जलवाष्प संघनित होकर द्रव जल बना सकती है।'],
 ['दोनों नमूने समान तापमान पर हैं। एक में कण पास-पास और दूसरे में बहुत दूर हैं। दूसरा नमूना किस अवस्था का अधिक संभावित है?',['गैस','ठोस','द्रव','किसी का नहीं'],0,'दूर-दूर कण और अधिक रिक्त स्थान गैस की विशेषता हैं।'],
 ['एक विद्यार्थी कहता है कि 0.333… अपरिमेय है क्योंकि दशमलव समाप्त नहीं होता। सही प्रतिक्रिया?',['गलत; यह आवर्ती दशमलव है और परिमेय है','सही; हर अनंत दशमलव अपरिमेय है','यह वास्तविक नहीं है','यह केवल पूर्णांक है'],0,'आवर्ती अनंत दशमलव परिमेय हो सकता है।']
];

export function ScienceChapter1Engine({chapter,onBack,addXp,finishSession}){
 const [mode,setMode]=useState('menu'),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[started,setStarted]=useState(Date.now());
 const lessons=require('./scienceChapter1Learning').scienceChapter1Learning.lessons;
 const questions=mode==='test'?practice.slice(0,20):mode==='practice'?practice:challenge;
 const item=questions[index];
 const answered=answers[index]!==undefined;
 const score=Object.entries(answers).reduce((n,[i,v])=>n+(String(v)===String(questions[Number(i)]?.[2]??questions[Number(i)]?.answer)?1:0),0);
 const choose=v=>{if(!answered)setAnswers(a=>({...a,[index]:v}))};
 const next=()=>{if(!answered)return;if(index<questions.length-1){setIndex(i=>i+1);return}addXp?.(mode==='challenge'?25:mode==='test'?30:15);finishSession?.({subject:'विज्ञान',chapter,mode,completed:true,attempted:questions.length,correct:score});setMode('result')};
 const start=m=>{setMode(m);setIndex(0);setAnswers({});setStarted(Date.now())};
 if(mode==='menu')return <main className="page science-chapter-page"><header className="page-header science-header"><button className="pressable" onClick={onBack}>← विषय</button><div className="badge">कक्षा 9 • विज्ञान</div><h1>{chapter}</h1><p>सरल हिन्दी समझ, प्रयोग-जैसे दृश्य, अभ्यास और परीक्षा की तैयारी।</p></header><section className="page-content"><div className="science-launch"><div className="science-launch-art"><div className="science-orbit"/><div className="science-flask">⚗</div><span className="science-bubble b1"/><span className="science-bubble b2"/><span className="science-bubble b3"/></div><div><span className="science-kicker">अध्याय यात्रा</span><h2>देखकर समझें, फिर स्वयं समझाएँ</h2><p>पहले सीखें, फिर प्रश्नों से अपनी समझ जाँचें।</p></div></div><div className="science-mode-grid"><button className="mode-card pressable" onClick={()=>setMode('learn')}><span>📖</span><strong>सीखें</strong><small>{lessons.length} सीखने के चरण</small><b>शुरू करें →</b></button><button className="mode-card pressable" onClick={()=>start('practice')}><span>📝</span><strong>अभ्यास</strong><small>{practice.length} प्रश्न</small><b>अभ्यास करें →</b></button><button className="mode-card pressable" onClick={()=>start('challenge')}><span>🔥</span><strong>चुनौती</strong><small>तर्क वाले प्रश्न</small><b>चुनौती लें →</b></button><button className="mode-card pressable" onClick={()=>start('test')}><span>🎯</span><strong>टेस्ट</strong><small>20 प्रश्न</small><b>टेस्ट दें →</b></button></div></section></main>;
 if(mode==='learn')return <LearnView lessons={lessons} chapter={chapter} onBack={()=>setMode('menu')} onDone={onBack} addXp={addXp} finishSession={finishSession}/>;
 if(mode==='result')return <main className="page science-result-page"><header className="page-header"><button className="pressable" onClick={()=>setMode('menu')}>← अध्याय</button><div className="badge">परिणाम</div><h1>{score} / {questions.length}</h1><p>{score===questions.length?'बहुत बढ़िया!':'गलतियों को समझकर फिर एक प्रयास करें।'}</p></header><section className="page-content"><div className="science-result-card"><div className="science-result-ring"><span>{Math.round(score/questions.length*100)}%</span></div><h2>अभ्यास पूरा हुआ</h2><p>हर गलत उत्तर के लिए नीचे दिए स्पष्टीकरण को ध्यान से पढ़ें और फिर दोबारा प्रयास करें।</p><button className="primary-btn pressable" onClick={()=>start(mode==='result'?'practice':'practice')}>फिर से अभ्यास</button><button className="secondary-btn pressable" onClick={()=>setMode('menu')}>अध्याय पर लौटें</button></div></section></main>;
 return <main className="page science-quiz-page"><header className="page-header science-header"><button className="pressable" onClick={()=>setMode('menu')}>← अध्याय</button><div className="quiz-meta"><span className="badge">{mode==='challenge'?'चुनौती':mode==='test'?'टेस्ट':'अभ्यास'}</span><span>{index+1} / {questions.length}</span></div><h1>{mode==='challenge'?'अवधारणा को तर्क से परखें':mode==='test'?'अध्याय परीक्षण':'अभ्यास से समझ मजबूत करें'}</h1><div className="quiz-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><article className="science-question-card"><span className="question-number">प्रश्न {index+1}</span><h2>{item[0]}</h2><div className="science-options">{item[1].map((o,i)=>{const ok=answered&&i===item[2];const wrong=answered&&answers[index]===i&&i!==item[2];return <button key={o} className={`answer-option pressable ${ok?'correct':''} ${wrong?'wrong':''}`} disabled={answered} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>})}</div>{answered&&<div className={`science-feedback ${answers[index]===item[2]?'good':'bad'}`}><strong>{answers[index]===item[2]?'✓ सही उत्तर':'✗ फिर से समझें'}</strong><p>{item[3]}</p></div>}<div className="science-quiz-actions"><span>{score} सही</span><button className="primary-btn pressable" disabled={!answered} onClick={next}>{index===questions.length-1?'समाप्त करें':'अगला प्रश्न →'}</button></div></article></section></main>;
}

function LearnView({lessons,chapter,onBack,onDone,addXp,finishSession}){const [index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[completed,setCompleted]=useState(false);const item=lessons[index];const selected=answers[index];const percent=Math.round(((index+1)/lessons.length)*100);const choose=v=>{if(selected===undefined)setAnswers(a=>({...a,[index]:v}))};const next=()=>{if(item.question&&selected===undefined)return;if(index<lessons.length-1){setIndex(i=>i+1);return}setCompleted(true);addXp?.(20);finishSession?.({subject:'विज्ञान',chapter,mode:'learn',completed:true,attempted:lessons.filter(x=>x.question).length,correct:lessons.reduce((n,x,i)=>n+(x.question&&String(answers[i])===String(x.answer)?1:0),0)});};if(completed)return <main className="page science-learn-page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">सीखना पूरा</div><h1>अध्याय पूरा हुआ 🎉</h1></header><section className="page-content"><div className="science-complete"><div className="science-complete-icon">🔬</div><h2>बहुत बढ़िया!</h2><p>अब अभ्यास में अपनी समझ को और मजबूत करें।</p><button className="primary-btn pressable" onClick={onBack}>अभ्यास पर जाएँ →</button></div></section></main>;
 return <main className="page science-learn-page"><header className="page-header science-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">विज्ञान • {chapter}</span><span>{index+1} / {lessons.length}</span></div><h1>📖 सीखें</h1><p>अवधारणा → दृश्य → उदाहरण → त्वरित जाँच</p><div className="quiz-progress"><span style={{width:`${percent}%`}}/></div></header><section className="page-content"><article className="lesson-card"><span className="lesson-type">{item.type==='intro'?'अध्याय की शुरुआत':item.type==='concept'?'अवधारणा':item.type==='example'?'उदाहरण':'त्वरित जाँच'}</span><h2>{item.title}</h2><p className="lesson-body">{item.body}</p>{item.visual&&<ScienceChapterVisual visual={item.visual}/>} {item.points&&<ul className="science-points">{item.points.map(p=><li key={p}>{p}</li>)}</ul>}{item.question&&<div className="science-check"><strong>🎯 त्वरित जाँच</strong><p>{item.question}</p>{item.options.map((o,i)=><button disabled={selected!==undefined} className={`answer-option pressable ${selected!==undefined&&i===item.answer?'correct':''} ${selected===i&&i!==item.answer?'wrong':''}`} key={o} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}{selected!==undefined&&<div className={`science-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ बिल्कुल सही':'✗ उत्तर समझें'}</strong><p>{item.explain}</p></div>}</div>}<div className="lesson-actions"><button className="secondary-btn pressable" onClick={onBack}>बाद में</button><button className="primary-btn pressable" onClick={next}>{index===lessons.length-1?'अध्याय पूरा करें':'आगे बढ़ें →'}</button></div></article></section></main>}
