import React,{useMemo,useState} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import {scienceChapter14Learning as data} from './scienceChapter14Learning';
import './science3-learn.css';
import './science14.css';
const make=(question,options,answer,explain)=>({question,options,answer,explain});
const questions=[
make('प्राकृतिक संसाधन का उचित उदाहरण कौन-सा है?',['वायु','प्लास्टिक की बोतल','सीमेंट','कंप्यूटर'],0,'वायु प्रकृति से मिलने वाला प्राकृतिक संसाधन है।'),
make('वायुमंडल में अधिकांश मौसम घटनाएँ किस परत में होती हैं?',['क्षोभमंडल','समतापमंडल','आयनमंडल','बहिर्मंडल'],0,'क्षोभमंडल पृथ्वी की सतह के निकट की परत है जहाँ अधिकांश मौसम घटनाएँ होती हैं।'),
make('पौधे प्रकाश-संश्लेषण में किस गैस का उपयोग करते हैं?',['कार्बन डाइऑक्साइड','ऑक्सीजन','हीलियम','हाइड्रोजन'],0,'प्रकाश-संश्लेषण में पौधे कार्बन डाइऑक्साइड का उपयोग करते हैं।'),
make('जल चक्र में जलवाष्प के ठंडा होकर बूंदों में बदलने को क्या कहते हैं?',['संघनन','वाष्पीकरण','बहाव','अवशोषण'],0,'जलवाष्प के ठंडा होकर द्रव बूंदों में बदलने को संघनन कहते हैं।'),
make('भूमिगत जल के स्तर को बढ़ाने वाली प्रक्रिया?',['जल पुनर्भरण','अत्यधिक पंपिंग','कंक्रीटीकरण','वन कटाई'],0,'वर्षा का पानी मिट्टी में जाकर भूमिगत जल का पुनर्भरण कर सकता है।'),
make('मृदा अपरदन से मुख्यतः क्या हट सकता है?',['ऊपरी उपजाऊ मृदा','वायुमंडल','सूर्य का प्रकाश','समुद्र का जल'],0,'अपरदन से उपजाऊ ऊपरी मृदा की परत हट सकती है।'),
make('नाइट्रोजन स्थिरीकरण में कौन मदद कर सकता है?',['राइजोबियम','यीस्ट','कवक की हर प्रजाति','लाल रक्त कोशिका'],0,'राइजोबियम जैसे जीवाणु वायुमंडलीय नाइट्रोजन को पौधों के लिए उपयोगी रूप में बदलने में मदद कर सकते हैं।'),
make('कार्बन डाइऑक्साइड को कार्बनिक पदार्थ में बदलने वाली प्रक्रिया?',['प्रकाश-संश्लेषण','श्वसन','दहन','अपघटन'],0,'प्रकाश-संश्लेषण में CO₂ का उपयोग करके कार्बनिक पदार्थ बनते हैं।'),
make('मृत जैविक पदार्थों के विघटन में कौन महत्वपूर्ण है?',['अपघटक','केवल शाकाहारी','केवल पक्षी','केवल सूर्य'],0,'बैक्टीरिया और कवक जैसे अपघटक मृत पदार्थों को तोड़ते हैं।'),
make('ओजोन परत मुख्यतः किससे रक्षा करती है?',['हानिकारक पराबैंगनी विकिरण','भूकंप','बाढ़','ध्वनि'],0,'समतापमंडलीय ओजोन परत UV विकिरण के एक बड़े भाग को अवशोषित करती है।'),
make('जल प्रदूषण का संभावित स्रोत?',['सीवेज और औद्योगिक अपशिष्ट','साफ वर्षा जल','वनस्पति','स्वच्छ पेयजल'],0,'सीवेज और औद्योगिक अपशिष्ट जल निकायों को प्रदूषित कर सकते हैं।'),
make('वायु प्रदूषण में सूक्ष्म कणों का प्रमुख प्रभाव?',['वायु गुणवत्ता खराब करना','मृदा निर्माण तेज करना','जल चक्र बंद करना','ओजोन बनाना'],0,'सूक्ष्म कण वायु गुणवत्ता और स्वास्थ्य को प्रभावित कर सकते हैं।'),
make('किससे मृदा अपरदन कम करने में मदद मिलती है?',['वनस्पति आवरण','अत्यधिक चराई','वन कटाई','ढलान पर नंगी मिट्टी'],0,'वनस्पति की जड़ें मिट्टी को बाँधती हैं और अपरदन कम कर सकती हैं।'),
make('ऑक्सीजन का प्रमुख जैविक स्रोत कौन-सी प्रक्रिया है?',['प्रकाश-संश्लेषण','दहन','श्वसन','अपघटन'],0,'प्रकाश-संश्लेषण ऑक्सीजन के उत्पादन में प्रमुख जैविक भूमिका निभाता है।'),
make('प्राकृतिक चक्रों का मुख्य महत्व क्या है?',['पदार्थों का पुनर्चक्रण','संसाधनों को स्थायी रूप से खत्म करना','केवल तापमान बढ़ाना','केवल वर्षा रोकना'],0,'जैव-भूरासायनिक चक्र पदार्थों को जीवित और निर्जीव घटकों के बीच पुनः परिचालित करते हैं।'),
make('स्थायी उपयोग का अर्थ क्या है?',['वर्तमान उपयोग के साथ भविष्य की क्षमता बचाना','जितना हो सके उतना दोहन','सभी संसाधन तुरंत खत्म करना','सिर्फ एक उपयोग करना'],0,'सतत उपयोग संसाधनों की भविष्य की उपलब्धता और पारिस्थितिक संतुलन को ध्यान में रखता है।'),
make('भूमिगत जल अधिक घटने का एक कारण?',['अत्यधिक निष्कर्षण','वर्षा जल का रिसाव','पुनर्भरण','जल संरक्षण'],0,'पुनर्भरण की तुलना में अधिक दोहन होने पर भूमिगत जलस्तर गिर सकता है।'),
make('कार्बन चक्र में CO₂ वापस वायुमंडल में कौन ला सकता है?',['श्वसन','प्रकाश-संश्लेषण','जल पुनर्भरण','संघनन'],0,'श्वसन के दौरान जीव कार्बनिक पदार्थ से ऊर्जा लेते हुए CO₂ छोड़ते हैं।'),
make('प्राकृतिक संसाधनों का संरक्षण क्यों आवश्यक है?',['जीवन और भविष्य की जरूरतों के लिए','क्योंकि संसाधन कभी उपयोगी नहीं होते','केवल परीक्षा के लिए','केवल शहरों के लिए'],0,'प्राकृतिक संसाधन जीवन-समर्थन करते हैं, इसलिए उनका विवेकपूर्ण संरक्षण जरूरी है।'),
make('मानव प्रभाव का संतुलित उदाहरण?',['अपशिष्ट कम करना और पुनर्चक्रण','अत्यधिक वन कटाई','नदियों में कचरा डालना','अत्यधिक जल दोहन'],0,'कचरा कम करना और पुनर्चक्रण संसाधन दबाव घटाने में मदद कर सकते हैं।')];
const challenge=[
make('किसी शहर में वर्षा का पानी सड़क से सीधे नाली में चला जाता है। भूमिगत जल सुधारने का बेहतर उपाय?',['वर्षाजल संचयन और पुनर्भरण संरचनाएँ','और अधिक पक्की सतह बनाना','पंपिंग बढ़ाना','पेड़ हटाना'],0,'वर्षाजल को संग्रहित या मिट्टी में पहुँचाने से पुनर्भरण बढ़ाया जा सकता है।'),
make('किसी पहाड़ी ढाल पर वन हटने लगे। सबसे संभावित पर्यावरणीय परिणाम?',['मृदा अपरदन बढ़ना','अपरदन शून्य होना','वर्षा हमेशा बढ़ना','भूमिगत जल तुरंत बढ़ना'],0,'वनस्पति हटने से जड़-आधारित मृदा संरक्षण घटता है और अपरदन बढ़ सकता है।'),
make('तालाब में जैविक अपशिष्ट बढ़ता जाए तो जलजीवों पर क्या असर हो सकता है?',['जल गुणवत्ता बिगड़ सकती है और ऑक्सीजन घट सकती है','जल हमेशा अधिक शुद्ध होगा','जलीय जीवन निश्चित बढ़ेगा','प्रदूषण रुक जाएगा'],0,'अधिक जैविक अपशिष्ट के अपघटन से घुलित ऑक्सीजन कम हो सकती है।'),
make('यदि प्रकाश-संश्लेषण बहुत कम हो जाए तो वायु के CO₂/O₂ संतुलन पर क्या प्रभाव अपेक्षित है?',['CO₂ का अवशोषण घटे और O₂ उत्पादन घटे','CO₂ शून्य हो जाए','O₂ उत्पादन अनंत हो जाए','कोई संबंध नहीं'],0,'प्रकाश-संश्लेषण CO₂ के अवशोषण और O₂ उत्पादन से जुड़ा है।'),
make('नाइट्रोजन चक्र में अपघटक क्यों महत्वपूर्ण हैं?',['वे मृत पदार्थों का नाइट्रोजन फिर चक्र में लौटाने में मदद करते हैं','वे सभी नाइट्रोजन खत्म करते हैं','वे केवल ऑक्सीजन बनाते हैं','वे जल को भाप बनाते हैं'],0,'अपघटन से पोषक तत्व ऐसे रूपों में लौटते हैं जिनका चक्र में आगे उपयोग हो सकता है।'),
make('ओजोन क्षय और जल प्रदूषण में एक साझा पर्यावरणीय सीख क्या है?',['मानव गतिविधियों के प्रभाव को समझकर रोकथाम जरूरी है','प्रदूषण हमेशा उपयोगी है','प्राकृतिक तंत्र कभी प्रभावित नहीं होते','केवल तकनीक पर्याप्त है'],0,'दोनों उदाहरण पर्यावरणीय तंत्र पर मानव प्रभाव और जिम्मेदार प्रबंधन के महत्व दिखाते हैं।'),
make('किस नीति से संसाधनों पर दबाव सबसे कम हो सकता है?',['कम उपयोग + पुनः उपयोग + पुनर्चक्रण','एकल उपयोग बढ़ाना','अपशिष्ट खुला फेंकना','जल की बर्बादी'],0,'कम खपत, पुनः उपयोग और पुनर्चक्रण संसाधन मांग और अपशिष्ट दोनों घटाते हैं।'),
make('एक क्षेत्र में पानी की कमी है लेकिन वर्षा मौसमी रूप से पर्याप्त है। कौन-सी संयुक्त रणनीति तर्कसंगत है?',['वर्षाजल संचयन + भूमिगत जल पुनर्भरण + दक्ष सिंचाई','केवल अधिक भूजल पंप करना','तालाब भरना बंद करना','पेड़ हटाना'],0,'संग्रहण, पुनर्भरण और दक्ष उपयोग मिलकर जल सुरक्षा बढ़ा सकते हैं।'),
make('प्राकृतिक संसाधनों के बीच परस्पर निर्भरता का उदाहरण?',['मृदा का जल और पौधों की वृद्धि से संबंध','वायु का पृथ्वी से कोई संबंध नहीं','जल का जीवों से कोई संबंध नहीं','मृदा केवल चट्टान है'],0,'जल, मृदा और वायु मिलकर पौधों तथा पूरे जीवमंडल को सहारा देते हैं।'),
make('सतत विकास में “भविष्य” को शामिल करने का अर्थ क्या है?',['आज की जरूरतें पूरी करते हुए भविष्य के संसाधनों और तंत्रों को सुरक्षित रखना','सभी संसाधन आज ही उपयोग करना','भविष्य की जरूरतें भूल जाना','सिर्फ उत्पादन बढ़ाना'],0,'सतत विकास वर्तमान और भविष्य दोनों की जरूरतों को संतुलित करता है।')];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const prep=q=>{const p=q.options.map((text,index)=>({text,index})),s=shuffle(p);return {...q,options:s.map(x=>x.text),answer:s.findIndex(x=>x.index===q.answer)}};
function Visual({type}){let body=null;const flow=(items)=><div className="sc14-flow">{items.map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<items.length-1&&<i>→</i>}</React.Fragment>)}</div>;
if(type==='resourceWeb')body=<div className="sc14-orbit"/>;
else if(type==='earthSystem')body=<div className="sc14-earth">{['🌬️ वायुमंडल','💧 जलमंडल','🪨 स्थलमंडल','🌱 जीवमंडल'].map(x=><span key={x}>{x}</span>)}</div>;
else if(type==='airLayers')body=<div className="sc14-layers"><span>☁️ क्षोभमंडल — मौसम</span><span>🛡️ समतापमंडल — ओजोन</span><span>🌌 ऊपरी वायुमंडल</span></div>;
else if(type==='atmosphere')body=<div className="sc14-layers"><span>0–12 km • क्षोभमंडल</span><span>12–50 km • समतापमंडल</span><span>ऊँचाई ↑ • दाब और घनत्व ↓</span></div>;
else if(type==='gasBalance')body=<div className="sc14-gases">{['N₂','O₂','CO₂','जलवाष्प'].map(x=><span key={x}>{x}</span>)}</div>;
else if(type==='waterUse')body=<div className="sc14-grid"><span>🥤 पीना</span><span>🌾 सिंचाई</span><span>🧼 स्वच्छता</span><span>🏭 उद्योग</span></div>;
else if(type==='waterCycle')body=<div className="sc14-water"/>;
else if(type==='groundwater')body=<div className="sc14-ground"/>;
else if(type==='soilProfile')body=<div className="sc14-ground"><span style={{position:'absolute',left:'50%',top:'30px',transform:'translateX(-50%)',fontWeight:900}}>ऊपरी मिट्टी → पोषक + ह्यूमस</span></div>;
else if(type==='soilErosion')body=flow(['🌳 वनस्पति','🧱 मिट्टी बंधी','🌧️ अपरदन ↓']);
else if(type==='nitrogenCycle'||type==='nCycle')body=flow(['N₂ वायु','स्थिरीकरण','पौधों में आत्मसात','अपघटन','वायुमंडल/मृदा']);
else if(type==='carbonCycle')body=flow(['CO₂','प्रकाश-संश्लेषण','जीव','श्वसन/अपघटन','CO₂']);
else if(type==='oxygenCycle')body=flow(['प्रकाश-संश्लेषण','O₂','श्वसन','CO₂','प्रकाश-संश्लेषण']);
else if(type==='cycleNetwork')body=<div className="sc14-cycle"><span>💧 जल चक्र</span><span>🌿 कार्बन चक्र</span><span>🧬 नाइट्रोजन चक्र</span><span>🫁 ऑक्सीजन चक्र</span></div>;
else if(type==='decomposer')body=flow(['🍂 मृत पदार्थ','🦠 अपघटक','🪨 पोषक तत्व','🌱 पौधे']);
else if(type==='ozone')body=<div className="sc14-ozone"><span className="sun">☀️</span><span className="uv">UV</span><span className="shield">🛡️ O₃ ओजोन</span><span>🌍 जीवन</span></div>;
else if(type==='ozoneLoss')body=flow(['हानिकारक रसायन','O₃ क्षय','UV संपर्क ↑']);
else if(type==='airPollution')body=<div className="sc14-impact"><span>🚗 वाहन</span><span>🏭 उद्योग</span><span>🔥 धुआँ</span><span>🌬️ कण</span></div>;
else if(type==='waterPollution')body=<div className="sc14-impact"><span>🚽 सीवेज</span><span>🏭 अपशिष्ट</span><span>🌾 अपवाह</span><span>🐟 जलीय जीवन</span></div>;
else if(type==='humanImpact')body=<div className="sc14-impact"><span>🌳 वन कटाई</span><span>💧 अतिदोहन</span><span>🏙️ भूमि बदलाव</span><span>🗑️ अपशिष्ट</span></div>;
else if(type==='sustainability')body=<div className="sc14-sustain"><span>💧 बचत</span><span>♻️ पुनर्चक्रण</span><span>🌳 संरक्षण</span><span>⚡ दक्षता</span></div>;
else body=<div className="sc14-summary">{['वायु','जल','मृदा','चक्र','संरक्षण'].map(x=><span key={x}>{x}</span>)}</div>;
return <div className="sc14-v">{body}</div>}
function Learn({onBack,addXp,finishSession}){const lessons=Array.isArray(data.lessons)?data.lessons:[];const[i,setI]=useState(0);const[done,setDone]=useState(false);const[xpSent,setXpSent]=useState(false);const x=lessons[i];if(!x)return <main className="page"><section className="page-content"><div className="science-error-card"><h2>अध्याय सामग्री उपलब्ध नहीं है</h2><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें</button></div></section></main>;const next=()=>{if(i<lessons.length-1){setI(v=>v+1);return}if(!xpSent){addXp?.(20);finishSession?.({subject:'विज्ञान',chapter:'प्राकृतिक संपदा',mode:'learn',attempted:lessons.length,correct:lessons.length,completed:true,at:Date.now()});setXpSent(true)}setDone(true)};if(done)return <main className="page sc3-learn-page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>अध्याय पूरा हुआ 🎉</h1></header><section className="page-content"><div className="sc3-learn-complete"><h2>बहुत बढ़िया!</h2><p>अब आप प्राकृतिक संसाधनों और उनके चक्रों को जोड़कर समझ सकते हैं।</p><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
return <main className="page sc3-learn-page"><nav className="sc3-learn-nav"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="sc3-nav-title"><strong>प्राकृतिक संपदा</strong><span>📖 सीखें</span></div><div className="sc3-nav-progress"><div><span>चरण {i+1}/{lessons.length}</span><span>{Math.round((i+1)/lessons.length*100)}%</span></div><i style={{width:`${(i+1)/lessons.length*100}%`}}/></div></nav><section className="sc3-learn-hero"><span className="eyebrow">विज्ञान • अध्याय 14</span><h1>{x.title}</h1><p>{x.body}</p></section><section className="sc3-learn-layout"><aside className="sc3-contents"><div className="sc3-contents-head"><strong>अध्याय सूची</strong><span>{lessons.length} चरण</span></div><div className="sc3-contents-list">{lessons.map((a,k)=><button className={`pressable ${k===i?'is-active':''}`} key={`${a.title}-${k}`} onClick={()=>setI(k)}><span className="sc3-num">{k+1}</span><span className="sc3-copy"><strong>{a.title}</strong><small>अवधारणा</small></span></button>)}</div></aside><article className="sc3-lesson"><Visual type={x.visual?.type}/>{x.points&&<ul className="sc3-points">{x.points.map(p=><li key={p}>{p}</li>)}</ul>}<div className="sc3-lesson-actions"><button className="secondary-btn pressable" onClick={onBack}>बाद में</button><div className="sc3-next-group"><button className="secondary-btn pressable" disabled={!i} onClick={()=>setI(v=>Math.max(0,v-1))}>← पिछला</button><button className="primary-btn pressable" onClick={next}>{i===lessons.length-1?'अध्याय पूरा करें':'अगला →'}</button></div></div></article></section></main>}
function Assessment({mode,chapter,onBack,addXp,finishSession}){const bank=mode==='challenge'?challenge:questions;const items=useMemo(()=>shuffle(bank).slice(0,mode==='test'?20:15).map(prep),[mode]);const[i,setI]=useState(0);const[sel,setSel]=useState(null);const[score,setScore]=useState(0);const[done,setDone]=useState(false);const[responses,setResponses]=useState([]);const x=items[i];const choose=k=>{if(sel!==null)return;setSel(k);setResponses(r=>[...r,{question:x,selected:k}]);if(k===x.answer){setScore(s=>s+1);addXp?.(mode==='challenge'?25:10)}};const next=()=>{if(sel===null)return;const final=score+(sel===x.answer?1:0);if(i===items.length-1){setScore(final);setDone(true);markStageComplete(`विज्ञान::${chapter}`,mode);finishSession?.({subject:'विज्ञान',chapter,mode,attempted:items.length,correct:final,completed:true,at:Date.now()})}else{setI(v=>v+1);setSel(null)}};if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>परिणाम</h1><p>{score}/{items.length} सही</p></header><section className="page-content"><div className="science-review-list">{responses.map((r,k)=>{const ok=r.selected===r.question.answer;return <article className={`science-review-item ${ok?'review-correct':'review-wrong'}`} key={k}><h3>प्रश्न {k+1}</h3><p><b>आपका उत्तर:</b> {r.question.options[r.selected]}</p><p><b>सही उत्तर:</b> {r.question.options[r.question.answer]}</p><p><b>क्यों?</b> {r.question.explain}</p></article>})}</div><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></section></main>;return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>{mode==='test'?'🎯 टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><p>प्रश्न {i+1}/{items.length}</p></header><section className="page-content"><article className="science-question-card"><h2>{x.question}</h2><div className="science-options">{x.options.map((o,k)=><button className={`answer-option pressable ${sel!==null&&k===x.answer?'correct':''} ${sel===k&&k!==x.answer?'wrong':''}`} disabled={sel!==null} key={`${o}-${k}`} onClick={()=>choose(k)}><span>{String.fromCharCode(65+k)}</span>{o}</button>)}</div>{sel!==null&&<div className={`science-feedback ${sel===x.answer?'good':'bad'}`}><p>{x.explain}</p></div>}<button className="primary-btn pressable" disabled={sel===null} onClick={next}>{i===items.length-1?'परिणाम देखें':'अगला →'}</button></article></section></main>}
export function ScienceChapter14Engine({chapter,onBack,addXp,finishSession}){const[mode,setMode]=useState(null);if(mode==='learn')return <Learn onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;if(mode)return <Assessment mode={mode} chapter={chapter} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;return <main className="page science-chapter-page"><header className="page-header science-header"><button className="pressable" onClick={onBack}>← विषय</button><div className="badge">कक्षा 9 • विज्ञान • अध्याय 14</div><h1>{chapter}</h1><p>{data.goal}</p></header><section className="page-content"><div className="science-launch"><div className="science-launch-art"><div className="science-orbit"/><div className="science-flask">🌍</div><span className="science-bubble b1">💧</span><span className="science-bubble b2">🌿</span><span className="science-bubble b3">☀️</span></div><div><span className="science-kicker">अध्याय यात्रा</span><h2>पृथ्वी के संसाधनों को समझें</h2><p>वायु, जल, मृदा और जैव-भूरासायनिक चक्रों को step-by-step जोड़कर पढ़ें।</p></div></div><div className="science-mode-grid"><button className="mode-card pressable" onClick={()=>setMode('learn')}><span>📖</span><strong>सीखें</strong><small>{data.lessons.length} चरण</small><b>शुरू करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('practice')}><span>📝</span><strong>अभ्यास</strong><small>15 प्रश्न</small><b>अभ्यास करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('challenge')}><span>🔥</span><strong>चुनौती</strong><small>10 कठिन प्रश्न</small><b>चुनौती लें →</b></button><button className="mode-card pressable" onClick={()=>setMode('test')}><span>🎯</span><strong>टेस्ट</strong><small>20 प्रश्न</small><b>टेस्ट दें →</b></button></div></section></main>}
