import React,{useEffect,useMemo,useState} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import './science3-learn.css';

const typeLabel={intro:'परिचय',concept:'अवधारणा',example:'उदाहरण',check:'त्वरित जाँच'};

function VisualDiagram({visual}){
 const type=visual?.type||'generic';
 if(type==='force'||type==='pushPull'||type==='effects'||type==='balanced'||type==='secondLaw'||type==='thirdLaw'||type==='friction') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-track"><span className="sc3-object sc3-object-a"/><span className="sc3-object sc3-object-b"/></div>{type==='balanced'&&<div className="sc3-forces"><span>← 10 N</span><strong>वस्तु</strong><span>10 N →</span></div>}{type==='pushPull'&&<div className="sc3-force-arrows"><span>↤ खिंचाव</span><span>धक्का ↦</span></div>}{type==='secondLaw'&&<div className="sc3-force-arrows"><span>F ↦</span><strong>m</strong><span>a ↦</span></div>}{type==='thirdLaw'&&<div className="sc3-force-arrows"><span>क्रिया ↦</span><strong>◉ ◉</strong><span>↤ प्रतिक्रिया</span></div>}{type==='friction'&&<div className="sc3-force-arrows"><span>बल ↦</span><strong>▰</strong><span>← घर्षण</span></div>}{(type==='force'||type==='effects')&&<div className="sc3-action-sequence"><span>बल</span><i>→</i><span>परिवर्तन</span><i>→</i><span>नई अवस्था</span></div>}</div>;
 if(type==='inertia'||type==='busStart'||type==='busStop'||type==='firstLaw') return <div className={`sc3-motion-diagram sc3-${type}`} aria-hidden="true"><div className="sc3-ground"/><div className="sc3-bus">🚌</div><div className="sc3-person">●</div>{type==='firstLaw'&&<div className="sc3-law-label">नेट बल = 0</div>}{type==='inertia'&&<div className="sc3-inertia-flow"><span>अवस्था</span><i>→</i><span>बदलाव का प्रयास</span><i>→</i><span>जड़त्व</span></div>}{(type==='busStart'||type==='busStop')&&<div className="sc3-bus-caption">{type==='busStart'?'बस आगे → शरीर पीछे की ओर':'बस रुकती है → शरीर आगे की ओर'}</div>}</div>;
 if(type==='momentum') return <div className="sc3-motion-diagram sc3-momentum" aria-hidden="true"><div className="sc3-momentum-items"><span className="sc3-ball small">●</span><b>m</b><i>×</i><span className="sc3-speed-arrow">v →</span><strong>= p</strong></div><div className="sc3-momentum-note">द्रव्यमान × वेग = संवेग</div></div>;
 if(type==='circular') return <div className="sc3-motion-diagram sc3-circular" aria-hidden="true"><div className="sc3-circle-path"><span>●</span></div><span className="sc3-circle-arrow">↗ दिशा बदलती है</span></div>;
 if(type==='momentumCollision'||type==='collision') return <div className="sc3-motion-diagram sc3-collision" aria-hidden="true"><div className="sc3-collision-balls"><span>● →</span><span>← ●</span></div><div className="sc3-collision-caption">टक्कर → कुल संवेग संरक्षित</div></div>;
 return null;
}

function SafeVisual({visual,title}){
 if(!visual)return null;
 const items=Array.isArray(visual.items)?visual.items:[];
 return <div className="sc3-safe-visual" aria-label={`दृश्य: ${title}`}><div className="sc3-visual-grid"><span className="sc3-visual-kicker">अध्याय दृश्य</span><strong>{visual.title||title}</strong><VisualDiagram visual={visual}/><div className="sc3-visual-items">{items.map((item,index)=><div className="sc3-visual-item" key={`${item}-${index}`}><b>{index+1}</b><span>{item}</span></div>)}</div></div></div>;
}

function LearnView({chapter,data,onBack,addXp,finishSession}){
 const lessons=data?.lessons||[];
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[completed,setCompleted]=useState(false);
 const item=lessons[index]||lessons[0],selected=answers[index],percent=lessons.length?Math.round(((index+1)/lessons.length)*100):0;
 useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});},[]);
 const goTo=i=>{if(!lessons.length)return;const bounded=Math.max(0,Math.min(lessons.length-1,i));setIndex(bounded);window.scrollTo({top:0,left:0,behavior:'auto'});};
 const choose=value=>{if(selected===undefined)setAnswers(prev=>({...prev,[index]:value}));};
 const next=()=>{if(!item)return;if(item.question&&selected===undefined)return;if(index<lessons.length-1){goTo(index+1);return;}if(completed)return;const pending=lessons.some((x,i)=>x.question&&answers[i]===undefined);if(pending)return;setCompleted(true);const correct=lessons.reduce((n,x,i)=>n+(x.question&&Number(answers[i])===Number(x.answer)?1:0),0);addXp?.(20);finishSession?.({subject:'विज्ञान',chapter,mode:'learn',attempted:lessons.filter(x=>x.question).length,correct,completed:true,at:Date.now()});window.scrollTo({top:0,left:0,behavior:'auto'});};
 if(!lessons.length)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>अध्याय सामग्री उपलब्ध नहीं है</h1><p>इस अध्याय की सीखने की सामग्री अभी जोड़ी जानी बाकी है।</p></header></main>;
 if(completed)return <main className="page sc3-learn-page"><nav className="sc3-learn-nav"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="sc3-nav-title"><strong>{chapter}</strong><span>सीखना पूरा</span></div></nav><section className="sc3-learn-hero"><span className="eyebrow">विज्ञान • {chapter}</span><h1>अध्याय पूरा हुआ 🎉</h1><p>आपने सभी {lessons.length} सीखने के चरण पूरे किए।</p></section><section className="sc3-learn-layout"><div className="sc3-learn-main-only"><div className="sc3-learn-complete"><div className="icon">📚</div><h2>बहुत बढ़िया!</h2><p>अब अभ्यास में अपनी समझ और मजबूत करें।</p><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></div></section></main>;
 return <main className="page sc3-learn-page"><nav className="sc3-learn-nav"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="sc3-nav-title"><strong>{chapter}</strong><span>📖 सीखें</span></div><div className="sc3-nav-progress" style={{'--sc3-progress':`${percent}%`}}><div><span>चरण {index+1}/{lessons.length}</span><span>{percent}%</span></div><i/></div></nav><section className="sc3-learn-hero"><span className="eyebrow">विज्ञान • {chapter}</span><h1>{chapter}</h1><p>विषय चुनें, पढ़ें, उदाहरण देखें और अपनी समझ जाँचें।</p></section><section className="sc3-learn-layout"><aside className="sc3-contents" aria-label="अध्याय सूची"><div className="sc3-contents-head"><strong>अध्याय सूची</strong><span>{lessons.length} सीखने के चरण</span></div><div className="sc3-contents-list">{lessons.map((lesson,i)=><button type="button" className={`pressable ${i===index?'is-active':''}`} key={`${lesson.title}-${i}`} onClick={()=>goTo(i)} aria-current={i===index?'page':undefined}><span className="sc3-num">{i+1}</span><span className="sc3-copy"><strong>{lesson.title}</strong><small>{typeLabel[lesson.type]||'पाठ'}</small></span></button>)}</div></aside><article className="sc3-lesson"><div className="sc3-lesson-meta"><span className="sc3-lesson-type">{typeLabel[item.type]||'पाठ'}</span><span>चरण {index+1} / {lessons.length}</span></div><h2>{item.title}</h2><p className="sc3-lesson-body">{item.body}</p><SafeVisual visual={item.visual} title={item.title}/>{item.points&&<ul className="sc3-points">{item.points.map(point=><li key={point}>{point}</li>)}</ul>}{item.question&&<div className="sc3-check"><strong>🎯 त्वरित जाँच</strong><p>{item.question}</p>{item.options.map((option,i)=><button type="button" disabled={selected!==undefined} className={`pressable ${selected!==undefined&&i===item.answer?'correct':''} ${selected===i&&i!==item.answer?'wrong':''}`} key={option} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}{selected!==undefined&&<div className={`sc3-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ बिल्कुल सही':'✗ उत्तर समझें'}</strong><p>{item.explain}</p></div>}</div>}<div className="sc3-lesson-actions"><button className="secondary-btn pressable" onClick={onBack}>बाद में</button><div className="sc3-next-group"><button className="secondary-btn pressable" disabled={index===0} onClick={()=>goTo(index-1)}>← पिछला</button><button className="primary-btn pressable" disabled={Boolean(item.question&&selected===undefined)} onClick={next}>{index===lessons.length-1?'अध्याय पूरा करें':'अगला →'}</button></div></div></article></section></main>;
}

function shuffleArray(list){const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function prepareQuestion(question){const options=(question?.options||[]).map((text,index)=>({text,index}));const shuffled=shuffleArray(options);return {...question,options:shuffled.map(x=>x.text),answer:shuffled.findIndex(x=>x.index===question.answer)};}

function Assessment({mode,chapter,bank,onBack,addXp,finishSession}){
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[responses,setResponses]=useState([]);
 const items=useMemo(()=>{const source=mode==='challenge'?(bank?.challenge||[]):(bank?.questions||[]);const limit=mode==='challenge'?10:mode==='test'?20:15;return shuffleArray(source).slice(0,limit).map(prepareQuestion);},[mode,bank]);
 const item=items[index];
 const choose=i=>{if(selected!==null||!item)return;setSelected(i);if(i===item.answer)setScore(s=>s+1);setResponses(prev=>[...prev,{question:item,selected:i}]);addXp?.(i===item.answer?(mode==='challenge'?25:10):0);};
 const next=()=>{if(selected===null||!item)return;const final=score+(selected===item.answer?1:0);if(index===items.length-1){setScore(final);setDone(true);markStageComplete(`विज्ञान::${chapter}`,mode);finishSession?.({subject:'विज्ञान',chapter,mode,attempted:items.length,correct:final,completed:true,at:Date.now()});}else{setIndex(i=>i+1);setSelected(null);}};
 if(!items.length)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">सामग्री जाँच</div><h1>प्रश्न उपलब्ध नहीं हैं</h1><p>इस मोड के लिए प्रश्न बैंक अभी उपलब्ध नहीं है।</p></header><section className="page-content"><div className="science-complete"><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
 if(done){const pct=Math.round(score/items.length*100);return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">परिणाम</div><h1>{pct>=80?'बहुत बढ़िया!':pct>=50?'अच्छी कोशिश!':'फिर से अभ्यास करें'}</h1><p>{score} / {items.length} सही • {pct}%</p></header><section className="page-content"><div className="science-complete"><h2>आपका परिणाम</h2><p>{mode==='test'?'टेस्ट':mode==='challenge'?'चुनौती':'अभ्यास'} पूरा हुआ। नीचे हर प्रश्न का उत्तर और कारण देखें।</p><div className="science-review-list">{responses.map((entry,i)=>{const correct=entry.selected===entry.question.answer;return <article className={`science-review-item ${correct?'review-correct':'review-wrong'}`} key={`${entry.question.question}-${i}`}><div><strong>प्रश्न {i+1}</strong><span>{correct?'✓ सही':'✗ गलत'}</span></div><h3>{entry.question.question}</h3><p><b>आपका उत्तर:</b> {entry.question.options[entry.selected]||'उत्तर नहीं चुना'}</p><p><b>सही उत्तर:</b> {entry.question.options[entry.question.answer]}</p><p><b>क्यों?</b> {entry.question.explain}</p></article>;})}</div><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
 }
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">विज्ञान • {chapter}</span><span>{index+1} / {items.length}</span></div><h1>{mode==='test'?'🎯 टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="quiz-progress"><span style={{width:`${((index+1)/items.length)*100}%`}}/></div></header><section className="page-content"><article className="science-question-card"><span className="question-number">प्रश्न {index+1}</span><h2>{item.question}</h2><div className="science-options">{item.options.map((option,i)=><button type="button" disabled={selected!==null} className={`answer-option pressable ${selected!==null&&i===item.answer?'correct':''} ${selected===i&&i!==item.answer?'wrong':''} ${selected!==null&&i!==selected&&i!==item.answer?'muted':''}`} key={`${option}-${i}`} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{selected!==null&&<div className={`science-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{item.explain}</p></div>}<div className="science-quiz-actions"><span>{selected===null?'उत्तर चुनें':'उत्तर दर्ज हो गया • सही उत्तर देखें'}</span><button className="primary-btn pressable" disabled={selected===null} onClick={next}>{index===items.length-1?'परिणाम देखें':'अगला →'}</button></div></article></section></main>;
}

export function ScienceNextChapterEngine({chapter,data,bank,onBack,addXp,finishSession}){const [mode,setMode]=useState(null);if(mode==='learn')return <LearnView chapter={chapter} data={data} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;if(mode)return <Assessment mode={mode} chapter={chapter} bank={bank} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;return <main className="page science-chapter-page"><header className="page-header science-header"><button className="pressable" onClick={onBack}>← विषय</button><div className="badge">कक्षा 9 • विज्ञान • अध्याय</div><h1>{chapter}</h1><p>पहले सीखें, फिर अभ्यास, चुनौती और टेस्ट से अपनी समझ मजबूत करें।</p></header><section className="page-content"><div className="science-launch"><div className="science-launch-art"><div className="science-orbit"/><div className="science-flask">◉</div><span className="science-bubble b1"/><span className="science-bubble b2"/><span className="science-bubble b3"/></div><div><span className="science-kicker">अध्याय यात्रा</span><h2>{data.goal}</h2><p>मुख्य अवधारणाएँ छोटे-छोटे चरणों में सीखें और फिर अपनी समझ को परखें।</p></div></div><div className="science-mode-grid"><button className="mode-card pressable" onClick={()=>setMode('learn')}><span>📖</span><strong>सीखें</strong><small>{data.lessons.length} सीखने के चरण</small><b>शुरू करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('practice')}><span>📝</span><strong>अभ्यास</strong><small>15 प्रश्न</small><b>अभ्यास करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('challenge')}><span>🔥</span><strong>चुनौती</strong><small>10 कठिन प्रश्न</small><b>चुनौती लें →</b></button><button className="mode-card pressable" onClick={()=>setMode('test')}><span>🎯</span><strong>टेस्ट</strong><small>20 प्रश्न</small><b>टेस्ट दें →</b></button></div></section></main>;
}
