import React,{useMemo,useState,useEffect} from 'react';
import {markStageComplete} from './engines/progress/progressStore';
import {scienceChapter13Learning as data} from './scienceChapter13Learning';
import './science3-learn.css';import './science13.css';
const make=(question,options,answer,explain)=>({question,options,answer,explain});
const questions=[
make('अच्छे स्वास्थ्य में क्या शामिल है?',['शारीरिक, मानसिक और सामाजिक कल्याण','केवल शरीर का वजन','केवल रोग न होना','केवल व्यायाम'],0,'स्वास्थ्य को शारीरिक, मानसिक और सामाजिक कल्याण की व्यापक अवस्था के रूप में समझा जाता है।'),
make('तीव्र रोग की सामान्य विशेषता क्या है?',['कम अवधि तक रहना','हमेशा जीवनभर रहना','कभी संक्रमण न होना','केवल आनुवंशिक होना'],0,'तीव्र रोग अपेक्षाकृत कम अवधि के होते हैं।'),
make('कौन-सा संक्रामक रोग का उदाहरण है?',['सामान्य सर्दी-जुकाम','मधुमेह','उच्च रक्तचाप','विटामिन की कमी'],0,'सामान्य सर्दी-जुकाम संक्रामक रोग का उदाहरण है।'),
make('रोगजनक का अर्थ क्या है?',['रोग उत्पन्न करने वाला कारक या जीव','केवल पोषक तत्व','केवल दवा','स्वच्छ जल'],0,'रोगजनक वह कारक या सूक्ष्मजीव है जो रोग उत्पन्न कर सकता है।'),
make('दूषित जल से रोग फैलने का एक कारण क्या है?',['रोगजनक शरीर में जल के साथ पहुँच सकता है','जल हमेशा रोग रोकता है','जल से रोगजनक नष्ट होते हैं','केवल हवा से संक्रमण संभव है'],0,'दूषित जल रोगजनकों को शरीर तक पहुँचा सकता है।'),
make('मच्छर किस भूमिका में कार्य कर सकता है?',['वाहक','टीका','एंटीबायोटिक','पोषक तत्व'],0,'कुछ रोगजनकों को एक मेज़बान से दूसरे तक पहुँचाने में मच्छर जैसे वाहक भूमिका निभा सकते हैं।'),
make('टीकाकरण का मुख्य उद्देश्य क्या है?',['विशिष्ट रोग के विरुद्ध प्रतिरक्षा प्रतिक्रिया तैयार करना','हर रोग को तुरंत ठीक करना','पोषण की जगह लेना','सभी सूक्ष्मजीव खत्म करना'],0,'टीका प्रतिरक्षा तंत्र को किसी विशेष रोगजनक के विरुद्ध सुरक्षा प्रतिक्रिया विकसित करने में तैयार करता है।'),
make('समुदाय के स्वास्थ्य के लिए कौन-सा उपाय महत्वपूर्ण है?',['सुरक्षित पेयजल और स्वच्छता','केवल व्यक्तिगत महँगी वस्तुएँ','केवल खेल','केवल परीक्षा'],0,'सुरक्षित जल, स्वच्छता और अन्य सार्वजनिक स्वास्थ्य उपाय समुदाय के रोग-जोखिम को कम करते हैं।'),
make('संक्रामक रोग के फैलाव को रोकने के लिए क्या मददगार है?',['फैलाव के माध्यम को रोकना','रोगजनक बढ़ाना','स्वच्छता छोड़ना','दूषित भोजन बाँटना'],0,'प्रसार की श्रृंखला तोड़ने से संक्रमण फैलने का जोखिम कम किया जा सकता है।'),
make('रोग का अंग-विशिष्ट प्रभाव किस बात को दर्शाता है?',['अलग रोग शरीर के अलग अंगों या ऊतकों को प्रभावित कर सकते हैं','हर रोग पूरे शरीर को एक जैसा प्रभावित करता है','रोगजनक केवल त्वचा पर रहते हैं','लक्षणों का कोई कारण नहीं होता'],0,'रोगजनक और रोग प्रक्रिया अलग-अलग अंगों या ऊतकों को विशेष रूप से प्रभावित कर सकती है।'),
make('निम्न में से कौन-सा असंक्रामक रोग का उदाहरण है?',['उच्च रक्तचाप','मलेरिया','टाइफाइड','कॉमन कोल्ड'],0,'उच्च रक्तचाप सामान्यतः व्यक्ति से व्यक्ति फैलने वाला संक्रमण नहीं है।'),
make('अच्छी वेंटिलेशन से कुछ श्वसन संक्रमणों में क्या मदद मिल सकती है?',['हवा के आदान-प्रदान से जोखिम कम करने में','रोगजनक को पोषण देने में','जल को दूषित करने में','टीका बनाने में'],0,'बेहतर वेंटिलेशन कुछ श्वसन संक्रमणों के प्रसार का जोखिम कम करने में सहायक हो सकता है।'),
make('रोग की रोकथाम में सुरक्षित भोजन क्यों महत्वपूर्ण है?',['क्योंकि दूषित भोजन रोगजनक पहुँचा सकता है','क्योंकि भोजन हमेशा रोग रोकता है','क्योंकि केवल भोजन से ही हर रोग होता है','क्योंकि भोजन टीका है'],0,'दूषित भोजन संक्रमण का माध्यम हो सकता है।'),
make('व्यक्ति और समुदाय दोनों के उपाय क्यों जरूरी हैं?',['क्योंकि स्वास्थ्य व्यक्तिगत और सामाजिक दोनों परिस्थितियों से प्रभावित होता है','क्योंकि केवल दवा ही स्वास्थ्य है','क्योंकि समुदाय का कोई प्रभाव नहीं','क्योंकि स्वच्छता का महत्व नहीं'],0,'व्यक्तिगत आदतों के साथ सामुदायिक स्वच्छता और स्वास्थ्य सेवाएँ भी महत्वपूर्ण हैं।'),
make('प्रतिरक्षा तंत्र का प्रमुख कार्य क्या है?',['रोगजनकों से रक्षा में मदद करना','भोजन को ऊर्जा में बदलना','हड्डियाँ बनाना','जल को साफ करना'],0,'प्रतिरक्षा तंत्र शरीर की रोगजनकों से रक्षा करने में महत्वपूर्ण भूमिका निभाता है।'),
make('रोग की रोकथाम का अच्छा उदाहरण क्या है?',['सुरक्षित जल, स्वच्छता और उचित टीकाकरण','दूषित पानी पीना','भीड़ में स्वच्छता न रखना','बीमारी फैलाना'],0,'रोकथाम में स्वच्छता, सुरक्षित जल और टीकाकरण जैसे उपाय महत्वपूर्ण हैं।'),
make('दीर्घकालिक रोग का स्वास्थ्य पर क्या प्रभाव हो सकता है?',['लंबे समय तक गतिविधि और जीवन-गुणवत्ता प्रभावित हो सकती है','हमेशा कुछ घंटों में ठीक हो जाता है','कभी कोई प्रभाव नहीं पड़ता','केवल मौसम बदलता है'],0,'दीर्घकालिक रोग लंबे समय तक बने रहकर स्वास्थ्य और दैनिक जीवन पर असर डाल सकते हैं।'),
make('रोग के कारण समझना क्यों जरूरी है?',['उचित रोकथाम और नियंत्रण की रणनीति चुनने में मदद करता है','क्योंकि हर रोग की एक ही दवा होती है','क्योंकि लक्षण महत्वहीन हैं','क्योंकि संक्रमण कभी नहीं फैलता'],0,'कारण और प्रसार का माध्यम समझने से रोकथाम और नियंत्रण बेहतर ढंग से किया जा सकता है।'),
make('स्वच्छ सार्वजनिक वातावरण किसे लाभ देता है?',['पूरे समुदाय को','केवल एक व्यक्ति को','केवल स्कूल को','किसी को नहीं'],0,'सार्वजनिक स्वच्छता और सुरक्षित जल जैसे उपाय पूरे समुदाय के स्वास्थ्य की रक्षा करते हैं।'),
make('“रोग-मुक्त” और “स्वस्थ” में क्या संबंध है?',['रोग-मुक्त होना स्वास्थ्य का पूरा अर्थ नहीं है','दोनों हमेशा बिल्कुल एक ही हैं','रोग-मुक्त होना असंभव है','स्वास्थ्य का रोग से कोई संबंध नहीं'],0,'स्वास्थ्य बहुआयामी है; केवल स्पष्ट रोग की अनुपस्थिति को पूर्ण स्वास्थ्य नहीं माना जाता।')];
const challenge=[
make('किसी गाँव में दूषित जल से कई लोग बीमार पड़ें तो सबसे प्रभावी सामुदायिक कदम क्या होगा?',['जल स्रोत की स्वच्छता और सुरक्षित पेयजल सुनिश्चित करना','केवल प्रत्येक व्यक्ति को अलग कमरा देना','भोजन बंद करना','मच्छरों को बढ़ाना'],0,'साझा जल स्रोत समस्या का संकेत है, इसलिए सुरक्षित जल और स्वच्छता पर सामुदायिक कार्रवाई जरूरी है।'),
make('एक ही रोग दो लोगों में अलग गंभीरता से क्यों दिख सकता है?',['मेज़बान की स्थिति और अन्य कारक अलग हो सकते हैं','रोगजनक हर व्यक्ति में बिल्कुल समान नहीं पहुँचते','लक्षण कभी शरीर पर निर्भर नहीं होते','हर रोग केवल मौसम पर निर्भर है'],0,'रोग का प्रभाव व्यक्ति की प्रतिरक्षा और अन्य परिस्थितियों से भी प्रभावित हो सकता है।'),
make('यदि किसी संक्रमण का मुख्य प्रसार मार्ग ज्ञात हो जाए तो अगला तार्किक कदम क्या है?',['उस प्रसार मार्ग को बाधित करने की रणनीति बनाना','प्रसार तेज करना','रोगजनक बढ़ाना','स्वच्छता हटाना'],0,'प्रसार मार्ग की पहचान रोकथाम की लक्षित रणनीति बनाने में मदद करती है।'),
make('व्यक्ति स्वस्थ दिखे लेकिन सामाजिक और मानसिक स्थिति खराब हो तो क्या निष्कर्ष सही है?',['पूर्ण स्वास्थ्य की स्थिति नहीं मानी जा सकती','वह निश्चित रूप से पूरी तरह स्वस्थ है','मानसिक स्वास्थ्य महत्वहीन है','सामाजिक वातावरण का कोई असर नहीं'],0,'स्वास्थ्य में मानसिक और सामाजिक कल्याण भी शामिल हैं।'),
make('टीकाकरण और स्वच्छता का साथ उपयोग क्यों बेहतर है?',['दोनों अलग-अलग स्तरों पर रोग-जोखिम घटाने में मदद करते हैं','दोनों एक ही चीज हैं','स्वच्छता टीके को निष्क्रिय करती है','टीकाकरण से जल सुरक्षित हो जाता है'],0,'टीकाकरण विशिष्ट प्रतिरक्षा तैयार करता है, जबकि स्वच्छता संक्रमण के संपर्क और प्रसार को घटाने में मदद करती है।'),
make('यदि कोई बीमारी संक्रामक नहीं है तो कौन-सी रणनीति अधिक उचित होगी?',['उसके विशिष्ट जोखिम कारकों और कारणों पर ध्यान देना','हर व्यक्ति को अलग रखना','दूषित जल फैलाना','वाहक बढ़ाना'],0,'असंक्रामक रोगों के नियंत्रण में उनके विशिष्ट कारण और जोखिम कारक महत्वपूर्ण होते हैं।'),
make('भीड़भाड़ और खराब वेंटिलेशन से श्वसन संक्रमण का जोखिम क्यों बढ़ सकता है?',['निकट संपर्क और हवा का कम आदान-प्रदान प्रसार आसान बना सकते हैं','क्योंकि हर हवा रोगजनक रहित होती है','क्योंकि वेंटिलेशन रोग पैदा करता है','क्योंकि केवल जल से संक्रमण फैलता है'],0,'भीड़भाड़ और कम वायु-परिवर्तन कुछ श्वसन संक्रमणों के प्रसार के अवसर बढ़ा सकते हैं।'),
make('रोग नियंत्रण को “श्रृंखला” की तरह क्यों समझा जा सकता है?',['कारण, प्रसार और मेज़बान के स्तर पर हस्तक्षेप किया जा सकता है','क्योंकि रोग हमेशा एक ही कदम से होता है','क्योंकि उपचार की जरूरत नहीं','क्योंकि सभी रोग एक जैसे हैं'],0,'रोग नियंत्रण में कारण, प्रसार के मार्ग और संवेदनशील मेज़बान—तीनों स्तरों पर उपाय हो सकते हैं।'),
make('सार्वजनिक स्वास्थ्य और व्यक्तिगत स्वास्थ्य में सबसे सही संबंध क्या है?',['दोनों परस्पर जुड़े हैं','दोनों पूरी तरह अलग हैं','केवल सार्वजनिक स्वास्थ्य महत्वपूर्ण है','केवल व्यक्तिगत आदतें मायने रखती हैं'],0,'व्यक्तिगत व्यवहार और सामुदायिक परिस्थितियाँ एक-दूसरे को प्रभावित करती हैं।'),
make('रोग के लक्षण समझने के साथ कारण जानना अधिक उपयोगी क्यों है?',['क्योंकि कारण बदलने पर रोकथाम की रणनीति भी बदल सकती है','क्योंकि लक्षण कभी उपयोगी नहीं होते','क्योंकि हर रोग का कारण एक है','क्योंकि रोकथाम का कोई संबंध नहीं'],0,'कारण की जानकारी से लक्षित रोकथाम और नियंत्रण उपाय चुनना आसान होता है।')];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const prep=q=>{const p=q.options.map((text,index)=>({text,index})),s=shuffle(p);return {...q,options:s.map(x=>x.text),answer:s.findIndex(x=>x.index===q.answer)}};
function Visual({v}){const t=v?.type;let body;
if(t==='healthBalance')body=<div className="sc13-balance">{['🫀 शरीर','🧠 मन','🤝 समाज','🌿 स्वास्थ्य'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='healthyVsDisease')body=<div className="sc13-compare"><div><b>रोग-मुक्त</b><small>कोई स्पष्ट रोग नहीं</small></div><strong>≠</strong><div><b>स्वस्थ</b><small>समग्र कल्याण</small></div></div>;
else if(t==='healthFactors')body=<div className="sc13-grid">{['🥗 पोषण','💧 जल','🧼 स्वच्छता','🌬️ वातावरण'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='diseaseMap')body=<div className="sc13-flow">कारण <i>→</i> शरीर में परिवर्तन <i>→</i> लक्षण</div>;
else if(t==='acuteChronic')body=<div className="sc13-timeline"><span>तीव्र<div/></span><span>दीर्घकालिक<div/></span></div>;
else if(t==='causeNetwork')body=<div className="sc13-network">{['🦠 कारण','🧑 व्यक्ति','🏠 पर्यावरण','⚠️ जोखिम'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='infectiousSplit')body=<div className="sc13-compare"><div><b>संक्रामक</b><small>फैलाव संभव</small></div><div><b>असंक्रामक</b><small>सामान्यतः व्यक्ति-से-व्यक्ति नहीं</small></div></div>;
else if(t==='pathogenTypes')body=<div className="sc13-pathogens">{['🦠 बैक्टीरिया','🔬 वायरस','🧫 प्रोटोजोआ','🍄 कवक'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='entryRoutes')body=<div className="sc13-grid">{['👃 श्वसन','🥤 भोजन/जल','🩸 शरीर द्रव','🦟 वाहक'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='spreadRoutes')body=<div className="sc13-pathogens">{['🤝 संपर्क','💨 बूंदें','🍱 भोजन/जल','🦟 वाहक'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='airSpread')body=<div className="sc13-air">😷 <i>•••</i> → 👥</div>;
else if(t==='foodWater')body=<div className="sc13-grid">{['💧 साफ जल','🧼 साफ हाथ','🍲 सुरक्षित भोजन'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='vectorControl')body=<div className="sc13-flow">🦟 वाहक <i>→</i> 🦠 <i>→</i> संक्रमण</div>;
else if(t==='organTarget')body=<div className="sc13-organ">{['🫁 श्वसन','🫃 पाचन','🧬 अन्य ऊतक'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='immuneDefense')body=<div className="sc13-flow">🦠 रोगजनक <i>→</i> 🛡️ प्रतिरक्षा <i>→</i> नियंत्रण</div>;
else if(t==='preventionLayers')body=<div className="sc13-layers"><span>व्यक्ति</span><span>घर</span><span>समुदाय</span></div>;
else if(t==='vaccineMemory')body=<div className="sc13-flow">💉 टीका <i>→</i> 🧠 प्रतिरक्षा तैयारी <i>→</i> 🛡️ सुरक्षा</div>;
else if(t==='communityHealth')body=<div className="sc13-grid">{['🚰 जल','🧹 स्वच्छता','💉 टीकाकरण','🏥 स्वास्थ्य सेवा'].map(x=><span key={x}>{x}</span>)}</div>;
else if(t==='controlChain')body=<div className="sc13-flow">कारण <i>→</i> प्रसार <i>→</i> मेज़बान <i>→</i> नियंत्रण</div>;
else if(t==='caseStudy')body=<div className="sc13-flow">समस्या <i>→</i> कारण की खोज <i>→</i> रोकथाम</div>;
else body=<div className="sc13-summary">{['स्वास्थ्य','रोग','संक्रमण','रोकथाम','समुदाय'].map(x=><span key={x}>{x}</span>)}</div>;
return <div className="sc13-v">{body}</div>}
function Learn({onBack,addXp,finishSession}){const lessons=Array.isArray(data.lessons)?data.lessons:[],[i,setI]=useState(0),[ans,setAns]=useState({}),[done,setDone]=useState(false);useEffect(()=>window.scrollTo({top:0,behavior:'auto'}),[i]);const x=lessons[i];if(!x)return <main className="page"><section className="page-content"><div className="science-error-card"><h2>अध्याय सामग्री उपलब्ध नहीं है</h2><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें</button></div></section></main>;const sel=ans[i];const next=()=>{if(x.question&&sel===undefined)return;if(i<lessons.length-1){setI(v=>v+1);return}if(done)return;setDone(true);addXp?.(20);finishSession?.({subject:'विज्ञान',chapter:'हम बीमार क्यों होते हैं',mode:'learn',attempted:lessons.filter(a=>a?.question).length,correct:lessons.filter((a,k)=>a?.question&&ans[k]===a.answer).length,completed:true,at:Date.now()})};if(done)return <main className="page sc3-learn-page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>अध्याय पूरा हुआ 🎉</h1></header><section className="page-content"><div className="sc3-learn-complete"><h2>बहुत बढ़िया!</h2><p>आपने स्वास्थ्य और रोग के मुख्य concepts पूरे किए।</p><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
return <main className="page sc3-learn-page"><nav className="sc3-learn-nav"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="sc3-nav-title"><strong>हम बीमार क्यों होते हैं</strong><span>📖 सीखें</span></div><div className="sc3-nav-progress"><div><span>चरण {i+1}/{lessons.length}</span><span>{Math.round((i+1)/lessons.length*100)}%</span></div><i style={{width:`${(i+1)/lessons.length*100}%`}}/></div></nav><section className="sc3-learn-hero"><span className="eyebrow">विज्ञान • अध्याय 13</span><h1>{x.title}</h1><p>{x.body}</p></section><section className="sc3-learn-layout"><aside className="sc3-contents"><div className="sc3-contents-head"><strong>अध्याय सूची</strong><span>{lessons.length} चरण</span></div><div className="sc3-contents-list">{lessons.map((a,k)=><button className={`pressable ${k===i?'is-active':''}`} key={`${a.title}-${k}`} onClick={()=>setI(k)}><span className="sc3-num">{k+1}</span><span className="sc3-copy"><strong>{a.title}</strong><small>अवधारणा</small></span></button>)}</div></aside><article className="sc3-lesson"><Visual v={x.visual}/>{x.points&&<ul className="sc3-points">{x.points.map(p=><li key={p}>{p}</li>)}</ul>}{x.question&&<div className="sc3-check"><strong>🎯 त्वरित जाँच</strong><p>{x.question}</p>{(Array.isArray(x.options)?x.options:[]).map((o,k)=><button className={`pressable ${sel!==undefined&&k===x.answer?'correct':''} ${sel===k&&k!==x.answer?'wrong':''}`} disabled={sel!==undefined} key={`${o}-${k}`} onClick={()=>setAns(a=>({...a,[i]:k}))}><span>{String.fromCharCode(65+k)}</span>{o}</button>)}{sel!==undefined&&<div className={`sc3-feedback ${sel===x.answer?'good':'bad'}`}><p>{x.explain||'उत्तर की व्याख्या उपलब्ध है।'}</p></div>}</div>}<div className="sc3-lesson-actions"><button className="secondary-btn pressable" onClick={onBack}>बाद में</button><div className="sc3-next-group"><button className="secondary-btn pressable" disabled={!i} onClick={()=>setI(v=>Math.max(0,v-1))}>← पिछला</button><button className="primary-btn pressable" disabled={Boolean(x.question&&sel===undefined)} onClick={next}>{i===lessons.length-1?'अध्याय पूरा करें':'अगला →'}</button></div></div></article></section></main>}
function Assessment({mode,chapter,onBack,addXp,finishSession}){const bank=mode==='challenge'?challenge:questions;const [i,setI]=useState(0),[sel,setSel]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[responses,setResponses]=useState([]);const items=useMemo(()=>shuffle(bank).slice(0,mode==='test'?20:15).map(prep),[mode]);const x=items[i];const choose=k=>{if(sel!==null)return;setSel(k);setResponses(r=>[...r,{question:x,selected:k}]);if(k===x.answer){setScore(s=>s+1);addXp?.(mode==='challenge'?25:10)}};const next=()=>{if(sel===null)return;const final=score+(sel===x.answer?1:0);if(i===items.length-1){setScore(final);setDone(true);markStageComplete(`विज्ञान::${chapter}`,mode);finishSession?.({subject:'विज्ञान',chapter,mode,attempted:items.length,correct:final,completed:true,at:Date.now()})}else{setI(v=>v+1);setSel(null)}};if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>परिणाम</h1><p>{score}/{items.length} सही</p></header><section className="page-content"><div className="science-review-list">{responses.map((r,k)=>{const ok=r.selected===r.question.answer;return <article className={`science-review-item ${ok?'review-correct':'review-wrong'}`} key={k}><h3>प्रश्न {k+1}</h3><p><b>आपका उत्तर:</b> {r.question.options[r.selected]}</p><p><b>सही उत्तर:</b> {r.question.options[r.question.answer]}</p><p><b>क्यों?</b> {r.question.explain}</p></article>})}</div><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></section></main>;
return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>{mode==='test'?'🎯 टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><p>प्रश्न {i+1}/{items.length}</p></header><section className="page-content"><article className="science-question-card"><h2>{x.question}</h2><div className="science-options">{x.options.map((o,k)=><button className={`answer-option pressable ${sel!==null&&k===x.answer?'correct':''} ${sel===k&&k!==x.answer?'wrong':''}`} disabled={sel!==null} key={`${o}-${k}`} onClick={()=>choose(k)}><span>{String.fromCharCode(65+k)}</span>{o}</button>)}</div>{sel!==null&&<div className={`science-feedback ${sel===x.answer?'good':'bad'}`}><p>{x.explain}</p></div>}<button className="primary-btn pressable" disabled={sel===null} onClick={next}>{i===items.length-1?'परिणाम देखें':'अगला →'}</button></article></section></main>}
export function ScienceChapter13Engine({chapter,onBack,addXp,finishSession}){const[mode,setMode]=useState(null);if(mode==='learn')return <Learn onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;if(mode)return <Assessment mode={mode} chapter={chapter} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;return <main className="page science-chapter-page"><header className="page-header science-header"><button className="pressable" onClick={onBack}>← विषय</button><div className="badge">कक्षा 9 • विज्ञान • अध्याय 13</div><h1>{chapter}</h1><p>{data.goal}</p></header><section className="page-content"><div className="science-launch"><div className="science-launch-art"><div className="science-orbit"/><div className="science-flask">🩺</div><span className="science-bubble b1">🦠</span><span className="science-bubble b2">💧</span><span className="science-bubble b3">🛡️</span></div><div><span className="science-kicker">अध्याय यात्रा</span><h2>स्वास्थ्य से रोग-नियंत्रण तक</h2><p>स्वास्थ्य, रोग के कारण, संक्रमण का प्रसार और बचाव को step-by-step समझें।</p></div></div><div className="science-mode-grid"><button className="mode-card pressable" onClick={()=>setMode('learn')}><span>📖</span><strong>सीखें</strong><small>{data.lessons.length} चरण</small><b>शुरू करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('practice')}><span>📝</span><strong>अभ्यास</strong><small>15 प्रश्न</small><b>अभ्यास करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('challenge')}><span>🔥</span><strong>चुनौती</strong><small>10 कठिन प्रश्न</small><b>चुनौती लें →</b></button><button className="mode-card pressable" onClick={()=>setMode('test')}><span>🎯</span><strong>टेस्ट</strong><small>20 प्रश्न</small><b>टेस्ट दें →</b></button></div></section></main>}
