import React,{useEffect,useMemo,useState} from 'react';
import {scienceChapter2Learning} from './scienceChapter2Learning';
import {ScienceChapter2Visual} from './ScienceChapter2Visual';
import {markStageComplete} from './engines/progress/progressStore';
import './science-engine.css';
import './science-chapter2-visual.css';

const practice=[
['शुद्ध पदार्थ का प्रमुख गुण क्या है?',['संघटन निश्चित होता है','संघटन हमेशा बदलता है','घटक किसी भी अनुपात में अलग होते हैं','केवल दो अवस्थाएँ होती हैं'],0,'शुद्ध पदार्थ का संघटन निश्चित रहता है।'],
['वायु किसका उदाहरण है?',['तत्व','यौगिक','मिश्रण','एकल शुद्ध पदार्थ'],2,'वायु कई गैसों का समांगी मिश्रण है।'],
['नमक का पानी किस प्रकार का मिश्रण है?',['विषमांगी','समांगी','निलंबन','केवल तत्व'],1,'नमक पानी में समान रूप से घुलकर समांगी विलयन बनाता है।'],
['नमक के पानी में विलेय कौन है?',['पानी','नमक','दोनों','कोई नहीं'],1,'नमक घुलने वाला पदार्थ है, इसलिए वह विलेय है।'],
['नमक के पानी में विलायक कौन है?',['नमक','पानी','दोनों समान रूप से','वायु'],1,'पानी वह माध्यम है जिसमें नमक घुलता है।'],
['रेत और पानी को अलग करने की उपयुक्त विधि है—',['छनन','आसवन','क्रोमैटोग्राफी','ऊर्ध्वपातन'],0,'रेत पानी में अघुलनशील है, इसलिए छनन उपयुक्त है।'],
['घुले हुए नमक को पानी से अलग करके नमक प्राप्त करने में कौन-सी विधि उपयोगी है?',['वाष्पीकरण','छनन','क्रोमैटोग्राफी','चुंबकीय पृथक्करण'],0,'पानी वाष्पित होने पर घुला नमक बच जाता है।'],
['निलंबन के कण सामान्यतः कैसे होते हैं?',['बहुत बड़े और बैठने योग्य','हमेशा अदृश्य और कभी नहीं बैठते','गैस के समान','केवल द्रव के कण'],0,'निलंबन में बड़े कण हो सकते हैं जो कुछ समय बाद नीचे बैठते हैं।'],
['कोलॉइड में प्रकाश का पथ दिखाई देने का कारण क्या है?',['टिंडल प्रभाव','गलन','जमना','आसवन'],0,'कोलॉइडल कण प्रकाश का प्रकीर्णन कर सकते हैं।'],
['टिंडल प्रभाव किस घटना से संबंधित है?',['प्रकाश का प्रकीर्णन','द्रव का उबलना','ठोस का पिघलना','गैस का संपीडन'],0,'कोलॉइडल कणों द्वारा प्रकाश का प्रकीर्णन टिंडल प्रभाव कहलाता है।'],
['आसवन में कौन-सा क्रम होता है?',['गरम करना → वाष्प → संघनन','छनन → जमना','जमना → वाष्पीकरण','केवल छनन'],0,'आसवन में पदार्थ को वाष्पित करके फिर संघनित किया जाता है।'],
['क्रोमैटोग्राफी किसके पृथक्करण में विशेष रूप से उपयोगी हो सकती है?',['रंगों के मिश्रण','रेत और पत्थर के बड़े टुकड़े','लोहे के टुकड़े और रेत','पानी और तेल हमेशा'],0,'मिश्रित रंगों के घटक अलग-अलग गति से चलते हैं।'],
['तत्व और यौगिक में मुख्य अंतर क्या है?',['यौगिक में तत्व रासायनिक रूप से जुड़े होते हैं','तत्व हमेशा मिश्रण होते हैं','यौगिक के घटक किसी भी अनुपात में होते हैं','तत्व केवल गैस होते हैं'],0,'यौगिक में तत्व निश्चित अनुपात में रासायनिक रूप से जुड़े होते हैं।'],
['मिश्रण के घटकों के बारे में कौन-सा कथन सही है?',['वे कई भौतिक गुण बनाए रख सकते हैं','वे हमेशा नए पदार्थ बनाते हैं','उनका अनुपात हमेशा निश्चित होता है','उन्हें कभी अलग नहीं किया जा सकता'],0,'मिश्रण के घटक अपने कई गुण बनाए रखते हैं और उचित भौतिक विधियों से अलग किए जा सकते हैं।'],
['दूध को निलंबन की बजाय किस श्रेणी से समझना अधिक उपयुक्त है?',['कोलॉइड','तत्व','शुद्ध पदार्थ','गैस'],0,'दूध एक कोलॉइडल तंत्र का सामान्य उदाहरण है।'],
['संतृप्त विलयन में किसी निश्चित तापमान पर—',['और विलेय घुलने की सीमा हो सकती है','विलेय कभी नहीं घुला','केवल विलायक होता है','वह हमेशा निलंबन होता है'],0,'संतृप्त विलयन में उस तापमान पर विलेय के घुलने की अधिकतम सीमा पूरी हो सकती है।'],
['असंतृप्त विलयन के बारे में कौन-सा कथन सही है?',['उपयुक्त परिस्थिति में और विलेय घुल सकता है','इसमें कोई विलायक नहीं होता','यह हमेशा विषमांगी है','यह केवल ठोस होता है'],0,'असंतृप्त विलयन में सामान्यतः और विलेय घुलने की क्षमता बची होती है।'],
['मिश्रण को अलग करने की विधि चुनने का पहला कदम क्या होना चाहिए?',['घटकों का भौतिक गुण पहचानना','बिना देखे कोई विधि चुनना','हमेशा उबालना','हमेशा छनना'],0,'घुलनशीलता, कण आकार या क्वथनांक जैसे गुण देखकर विधि चुननी चाहिए।'],
['तेल और पानी जैसे मिश्रण को केवल वाष्पीकरण से अलग करना क्यों उचित नहीं है?',['दोनों द्रवों के व्यवहार और पृथक्करण की विधि अलग होती है','तेल पदार्थ नहीं है','पानी हमेशा ठोस है','तेल गैस है'],0,'अमिश्रणीय द्रवों के लिए अलग पृथक्करण विधियाँ अधिक उपयुक्त हो सकती हैं।'],
['किसी विलयन में घटक समान रूप से फैले हैं। वह सामान्यतः क्या होगा?',['समांगी मिश्रण','विषमांगी मिश्रण','निलंबन','केवल तत्व'],0,'समान संघटन वाला मिश्रण समांगी कहलाता है।'],
['कौन-सा विकल्प सही जोड़ी बनाता है?',['रेत-पानी → छनन','नमक-पानी से नमक → केवल छनन','रंगों का मिश्रण → केवल चुंबक','अलग क्वथनांक वाले द्रव → केवल छनन'],0,'रेत और पानी में अघुलनशील ठोस होने के कारण छनन उचित है।'],
['वाष्पीकरण और उबलने में एक प्रमुख अंतर क्या है?',['वाष्पीकरण सतह से होता है','उबलना केवल ठोस में होता है','वाष्पीकरण में कभी ऊष्मा नहीं लगती','दोनों हमेशा एक ही प्रक्रिया हैं'],0,'वाष्पीकरण द्रव की सतह से धीरे-धीरे हो सकता है।'],
['निलंबन को कुछ समय छोड़ देने पर क्या हो सकता है?',['कण नीचे बैठ सकते हैं','सभी कण गैस बन जाते हैं','यह तत्व बन जाता है','विलयन निश्चित रूप से बन जाता है'],0,'बड़े निलंबित कण गुरुत्व के प्रभाव से नीचे बैठ सकते हैं।'],
['कोलॉइड के कणों का व्यवहार किस कथन से बेहतर समझ आता है?',['वे माध्यम में लंबे समय तक फैले रह सकते हैं','वे तुरंत हमेशा नीचे बैठते हैं','वे केवल ठोस अवस्था में होते हैं','वे प्रकाश को कभी प्रभावित नहीं करते'],0,'कोलॉइडल कण सामान्यतः आसानी से नीचे नहीं बैठते और प्रकाश का प्रकीर्णन कर सकते हैं।'],
['निश्चित अनुपात में रासायनिक रूप से जुड़े तत्व मिलकर क्या बनाते हैं?',['यौगिक','मिश्रण','निलंबन','कोलॉइड'],0,'यौगिक में तत्व निश्चित अनुपात में रासायनिक रूप से जुड़े होते हैं।'],
['यदि किसी मिश्रण में एक घटक चुंबकीय है, तो कौन-सा गुण पृथक्करण में मदद कर सकता है?',['चुंबकीय आकर्षण','केवल क्वथनांक','केवल रंग','केवल स्वाद'],0,'चुंबकीय पदार्थ को चुंबक की सहायता से अलग किया जा सकता है।'],
['प्रकीर्णन का अर्थ क्या है?',['प्रकाश का अलग-अलग दिशाओं में फैलना','पानी का जमना','ठोस का टूटना','गैस का द्रव बनना'],0,'छोटे कण प्रकाश को विभिन्न दिशाओं में फैला सकते हैं।'],
['नमक और पानी के मिश्रण में पानी को संघनित करके वापस पाने के लिए कौन-सी विधि उपयोगी है?',['आसवन','केवल छनन','केवल चुंबक','क्रोमैटोग्राफी'],0,'आसवन में पानी वाष्पित होकर फिर संघनित होता है, इसलिए उसे एकत्र किया जा सकता है।'],
['एक छात्र कहता है कि हर मिश्रण विषमांगी होता है। यह कथन—',['गलत है','सही है','केवल गैस के लिए सही है','केवल ठोस के लिए सही है'],0,'समांगी और विषमांगी दोनों प्रकार के मिश्रण होते हैं।'],
['शुद्ध जल और नमक का विलयन अलग क्यों माने जाते हैं?',['विलयन में एक से अधिक घटक होते हैं','शुद्ध जल हमेशा मिश्रण है','नमक पानी में बदल जाता है','दोनों का संघटन हमेशा समान है'],0,'शुद्ध जल का संघटन निश्चित है, जबकि नमक के विलयन में जल और नमक दोनों घटक हैं।']
];
const challenge=[
['एक मिश्रण में नमक, रेत और पानी है। नमक तथा रेत अलग-अलग प्राप्त करने की उचित रणनीति क्या है?',['पहले छनन से रेत हटाएँ, फिर विलयन से नमक अलग करें','पहले क्रोमैटोग्राफी करें','केवल चुंबक लगाएँ','केवल ठंडा करें'],0,'रेत अघुलनशील है, इसलिए पहले छनन से हटेगी। फिर नमक-पानी के विलयन से वाष्पीकरण या उपयुक्त आसवन प्रक्रिया द्वारा पृथक्करण किया जा सकता है।'],
['दो मिश्रणीय द्रवों के क्वथनांक पर्याप्त अलग हैं। कौन-सी विधि सबसे तर्कसंगत है?',['आसवन','छनन','चुंबकीय पृथक्करण','अवसादन'],0,'क्वथनांक के अंतर का उपयोग आसवन में किया जाता है।'],
['एक प्रकाश किरण धुंध जैसे नमूने से गुजरते समय दिखाई देती है। सबसे उचित निष्कर्ष क्या है?',['कोलॉइडल कण प्रकीर्णन कर रहे हो सकते हैं','नमूना निश्चित रूप से तत्व है','नमूना हमेशा शुद्ध जल है','वहाँ कोई कण नहीं हैं'],0,'सूक्ष्म कण प्रकाश का प्रकीर्णन कर सकते हैं, जो टिंडल प्रभाव से जुड़ा है।'],
['एक छात्र नमक-पानी को फिल्टर पेपर से पूरी तरह अलग करना चाहता है। कठिनाई क्यों होगी?',['नमक के कण विलयन में बहुत छोटे होते हैं और घुले होते हैं','पानी ठोस है','फिल्टर केवल गैस रोकता है','नमक चुंबकीय है'],0,'घुला हुआ नमक सामान्य फिल्टर पेपर से अलग नहीं किया जा सकता; वाष्पीकरण/आसवन जैसे तरीके चाहिए।'],
['एक अज्ञात नमूने में अलग-अलग रंग कई ऊँचाइयों पर दिखाई देने लगते हैं। यह किस तकनीक का संकेत हो सकता है?',['क्रोमैटोग्राफी','छनन','अवसादन','उर्ध्वपातन'],0,'क्रोमैटोग्राफी में घटक अलग-अलग गति से चलते हैं।'],
['यदि समान पदार्थ के तीन नमूने अलग-अलग अनुपात में मिलाकर भी एकसमान संघटन बनाए रखें, तो वह किस प्रकार का हो सकता है?',['समांगी मिश्रण','केवल यौगिक','केवल तत्व','निलंबन'],0,'समांगी मिश्रण में प्रत्येक भाग का संघटन समान हो सकता है।'],
['निलंबन और कोलॉइड में भेद करते समय कौन-सा अवलोकन उपयोगी है?',['कण बैठने की प्रवृत्ति और प्रकाश का व्यवहार','केवल गंध','केवल रंग','केवल तापमान'],0,'निलंबन के कण बैठ सकते हैं, जबकि कोलॉइड लंबे समय तक फैले रह सकते हैं और टिंडल प्रभाव दे सकते हैं।'],
['किस कथन से मिश्रण और यौगिक का सबसे अच्छा अंतर स्पष्ट होता है?',['मिश्रण में घटकों का अनुपात बदल सकता है; यौगिक में अनुपात निश्चित होता है','दोनों में हमेशा वही गुण होते हैं','दोनों को कभी अलग नहीं किया जा सकता','मिश्रण हमेशा ठोस होता है'],0,'यौगिक में तत्व निश्चित अनुपात में रासायनिक रूप से जुड़े होते हैं, जबकि मिश्रण में ऐसा आवश्यक नहीं है।'],
['यदि पदार्थ का कोई शुद्ध नमूना अलग-अलग भागों में एक जैसा संघटन दिखाए, तो पहला अनुमान क्या हो सकता है?',['वह समांगी या शुद्ध तंत्र हो सकता है','वह निश्चित रूप से निलंबन है','वह निश्चित रूप से गैस है','वह केवल धातु है'],0,'समान संघटन शुद्ध पदार्थ या समांगी मिश्रण की ओर संकेत कर सकता है; आगे की जाँच आवश्यक है।'],
['एक प्रक्रिया में गरम करके वाष्प बनाई जाती है और दूसरी जगह ठंडा करके द्रव वापस प्राप्त किया जाता है। यह किस पृथक्करण का मूल सिद्धांत है?',['आसवन','छनन','अवसादन','चुंबकीय पृथक्करण'],0,'वाष्पीकरण और संघनन का क्रम आसवन का आधार है।']
];

function Quiz({title,questions,mode,onBack,addXp}){const[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[time,setTime]=useState(mode==='test'?900:0);const current=questions[index];useEffect(()=>{if(mode!=='test'||done)return;const id=setInterval(()=>setTime(t=>{if(t<=1){clearInterval(id);setDone(true);return 0}return t-1}),1000);return()=>clearInterval(id)},[mode,done]);useEffect(()=>{if(done&&questions.length)markStageComplete(`विज्ञान::हमारे आसपास के पदार्थ`,mode)},[done]);const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current[2]){setScore(s=>s+1);if(mode!=='test')addXp?.(mode==='challenge'?25:15)}};const next=()=>{if(selected===null)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};if(done)return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><h1>{title} पूरा</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small> / {questions.length}</small></div><div className="result-percent">{Math.round(score/questions.length*100)}% सही</div><div className="result-bar"><span style={{width:`${Math.round(score/questions.length*100)}%`}}/></div><h2>{score>=questions.length*.8?'बहुत बढ़िया! 🎉':score>=questions.length*.6?'अच्छा प्रयास! 💪':'फिर से अभ्यास करें 📚'}</h2><p>{mode==='test'?'अब उत्तरों की समीक्षा करें और जहाँ गलती हुई वहाँ कारण समझें।':'हर उत्तर के बाद दिए गए कारण से अवधारणा मजबूत करें।'}</p><div className="result-actions"><button className="secondary-btn pressable" onClick={()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setTime(mode==='test'?900:0)}}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
  const mm=String(Math.floor(time/60)).padStart(2,'0'),ss=String(time%60).padStart(2,'0');return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">विज्ञान • {mode}</span><span>{mode==='test'?`⏱ ${mm}:${ss}`:`${index+1} / ${questions.length}`}</span></div><h1>{title}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}</span><h2>{current[0]}</h2><div className="options-grid">{current[1].map((o,i)=><button key={o} className={`answer-option pressable ${selected!==null?(i===current[2]?'correct':i===selected?'wrong':'muted'):''}`} disabled={selected!==null} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current[2]?'good':'bad'}`}><strong>{selected===current[2]?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current[3]}</p></div>}<div className="question-actions"><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>}

export function ScienceChapter2Engine({chapter='क्या हमारे आसपास के पदार्थ शुद्ध हैं?',onBack,addXp,finishSession,initialMode='learn'}){const [mode,setMode]=useState(initialMode);const lessons=scienceChapter2Learning.lessons;const visualTypes=['mixture','mixture','solution','compare','solution','solution','solution','suspension','colloid','compare','compare','light','separation','filtration','evaporation','distillation','distillation','chromatography','compare','decision','compare','decision','separation','mixture','compare','compare','decision'];const [index,setIndex]=useState(0);const [answers,setAnswers]=useState({});const item=lessons[index];const selected=answers[index];const check=v=>{if(selected===undefined)setAnswers(a=>({...a,[index]:v}))};const next=()=>{if(index<lessons.length-1){setIndex(i=>i+1);return;}markStageComplete(`विज्ञान::${chapter}`,'learn');addXp?.(20);finishSession?.({subject:'विज्ञान',chapter,mode:'learn',completed:true,attempted:Object.keys(answers).length,correct:Object.entries(answers).filter(([i,v])=>String(lessons[i]?.answer)===String(v)).length,at:Date.now()});setMode('practice')};if(mode==='practice'||mode==='challenge'||mode==='test'){const qs=mode==='practice'?practice:mode==='challenge'?challenge:practice.slice(0,20);return <Quiz title={mode==='practice'?'📝 अभ्यास':mode==='challenge'?'🔥 चुनौती':'🎯 टेस्ट'} questions={qs} mode={mode} onBack={()=>setMode('learn')} addXp={addXp}/>}
return <main className="page lesson-page"><header className="page-header lesson-header"><button className="pressable" onClick={onBack}>← विज्ञान</button><div className="lesson-top"><span className="badge">विज्ञान • {chapter}</span><span>{index+1} / {lessons.length}</span></div><div className="lesson-title-row"><div><h1>📖 सीखें</h1><p>अवधारणा समझें → दृश्य प्रयोग देखें → फिर जाँच करें।</p></div><div className="lesson-progress-ring"><span>{Math.round(((index+1)/lessons.length)*100)}%</span></div></div><div className="lesson-progress"><span style={{width:`${((index+1)/lessons.length)*100}%`}}/></div></header><section className="page-content"><div className="lesson-card"><span className="lesson-type">{item.type==='intro'?'अध्याय की शुरुआत':item.type==='example'?'समझें • उदाहरण':item.type==='check'?'त्वरित जाँच':'अवधारणा'}</span><h2>{item.title}</h2><p className="lesson-body">{item.body}</p><ScienceChapter2Visual type={visualTypes[index%visualTypes.length]}/>{item.points&&<div className="lesson-points-wrap"><div className="mini-heading">✅ याद रखें</div><ul className="lesson-points">{item.points.map((p,i)=><li key={i}>{p}</li>)}</ul></div>}{item.example&&<div className="lesson-example"><div className="mini-heading">💡 उदाहरण</div><p>{item.example}</p></div>}{item.question&&<div className="quick-check"><strong>{item.question}</strong><div className="check-options-grid">{item.options.map((o,i)=><button key={o} disabled={selected!==undefined} className={`check-option pressable ${selected!==undefined&&i===item.answer?'correct':''}`} onClick={()=>check(i)}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{selected!==undefined&&<div className={`check-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ बिल्कुल सही!':'✗ उत्तर दोबारा समझें'}</strong><p>{item.explain}</p></div>}</div>}<div className="lesson-actions"><button className="secondary-btn pressable" onClick={onBack}>बाद में पढ़ूँगा</button><button className="primary-btn pressable" onClick={next}>{index===lessons.length-1?'अध्याय पूरा करें':'आगे बढ़ें →'}</button></div></div></section></main>}
