import React,{useMemo,useState} from 'react';
import {ScienceLearnView} from './ScienceLearnView';
import {scienceChapter5Learning} from './scienceChapter5Learning';
import {ScienceChapter5Visual} from './ScienceChapter5Visual';
import {markStageComplete} from './engines/progress/progressStore';
import './science-engine.css';

const questions=[
{question:'कोशिका किसे कहा जाता है?',options:['जीव की मूल संरचनात्मक और क्रियात्मक इकाई','केवल शरीर की बाहरी परत','केवल रक्त का भाग','केवल पौधे का तना'],answer:0,explain:'कोशिका जीव की मूल संरचनात्मक और क्रियात्मक इकाई है।'},
{question:'एककोशिकीय जीव का सही उदाहरण कौन-सा है?',options:['मनुष्य','अमीबा','पेड़','कुत्ता'],answer:1,explain:'अमीबा एक ही कोशिका से बना एककोशिकीय जीव है।'},
{question:'कोशिका की बाहरी सीमा मुख्यतः कौन बनाती है?',options:['केंद्रक','कोशिका झिल्ली','राइबोसोम','माइटोकॉन्ड्रिया'],answer:1,explain:'कोशिका झिल्ली कोशिका की बाहरी सीमा बनाती है।'},
{question:'पादप कोशिका में कोशिका झिल्ली के बाहर क्या पाया जाता है?',options:['कोशिका भित्ति','केवल केंद्रक','केवल राइबोसोम','लाइसोसोम'],answer:0,explain:'पादप कोशिकाओं में कोशिका झिल्ली के बाहर सेल्यूलोजयुक्त कोशिका भित्ति होती है।'},
{question:'केंद्रक का मुख्य महत्व क्या है?',options:['आनुवंशिक पदार्थ रखना और नियंत्रण में मदद करना','केवल भोजन पचाना','केवल जल संग्रह करना','केवल ऊर्जा बनाना'],answer:0,explain:'केंद्रक में आनुवंशिक पदार्थ रहता है और यह कोशिका की गतिविधियों के नियंत्रण में महत्वपूर्ण है।'},
{question:'माइटोकॉन्ड्रिया किससे संबंधित है?',options:['ऊर्जा उत्पादन','कोशिका भित्ति निर्माण','केवल जल संग्रह','प्रकाश ग्रहण'],answer:0,explain:'माइटोकॉन्ड्रिया कोशिकीय श्वसन और उपयोगी ऊर्जा उत्पादन से संबंधित है।'},
{question:'हरितलवक का मुख्य कार्य क्या है?',options:['प्रकाश संश्लेषण','प्रोटीन पाचन','संदेश भेजना','रक्त परिवहन'],answer:0,explain:'हरितलवक में क्लोरोफिल होता है और प्रकाश संश्लेषण में इसकी मुख्य भूमिका है।'},
{question:'रिक्तिकाय का एक प्रमुख कार्य क्या है?',options:['भंडारण','प्रोटीन निर्माण ही','गुणसूत्र बनाना','तंत्रिका संदेश भेजना'],answer:0,explain:'रिक्तिकाय जल, घुले पदार्थ और अन्य सामग्री के भंडारण में सहायता करते हैं।'},
{question:'राइबोसोम किस प्रक्रिया से सबसे अधिक संबंधित है?',options:['प्रोटीन संश्लेषण','प्रकाश संश्लेषण','जल परिवहन','कोशिका विभाजन ही'],answer:0,explain:'राइबोसोम प्रोटीन संश्लेषण के प्रमुख स्थल हैं।'},
{question:'गॉल्जी तंत्र की प्रमुख भूमिका क्या है?',options:['संशोधन, छँटाई और पैकेजिंग','केवल आनुवंशिक पदार्थ बनाना','केवल प्रकाश संश्लेषण','केवल कोशिका भित्ति बनाना'],answer:0,explain:'गॉल्जी तंत्र पदार्थों के संशोधन, छँटाई और पैकेजिंग में मदद करता है।'},
{question:'लाइसोसोम में क्या पाया जाता है?',options:['पाचनकारी एंजाइम','क्लोरोफिल','हीमोग्लोबिन','गुणसूत्र'],answer:0,explain:'लाइसोसोम में ऐसे एंजाइम होते हैं जो कोशिका के अवांछित पदार्थों के अपघटन में सहायता करते हैं।'},
{question:'अंतर्द्रव्यी जालिका का एक प्रमुख कार्य क्या है?',options:['आंतरिक परिवहन और कुछ पदार्थों के निर्माण में सहायता','केवल प्रकाश संश्लेषण','केवल गुणसूत्रों को संग्रहित करना','केवल जल संग्रह करना'],answer:0,explain:'अंतर्द्रव्यी जालिका कोशिका के भीतर पदार्थों के परिवहन और कुछ पदार्थों के निर्माण से जुड़ी है।'},
{question:'खुरदरी अंतर्द्रव्यी जालिका की सतह पर क्या पाया जाता है?',options:['राइबोसोम','हरितलवक','गुणसूत्र','कोशिका भित्ति'],answer:0,explain:'खुरदरी ER की सतह पर राइबोसोम जुड़े होते हैं।'},
{question:'प्रोकैरियोटिक कोशिका की प्रमुख विशेषता क्या है?',options:['सुस्पष्ट झिल्ली-बद्ध केंद्रक का अभाव','बहुत बड़ा झिल्ली-बद्ध केंद्रक','हर कोशिका में हरितलवक','केवल बड़ी केंद्रीय रिक्तिका'],answer:0,explain:'प्रोकैरियोटिक कोशिकाओं में सुस्पष्ट झिल्ली-बद्ध केंद्रक नहीं होता।'},
{question:'यूकैरियोटिक कोशिका में कौन-सी विशेषता होती है?',options:['सुस्पष्ट झिल्ली-बद्ध केंद्रक','केंद्रक का पूर्ण अभाव','केवल कोशिका भित्ति','केवल एक कोशिकांग'],answer:0,explain:'यूकैरियोटिक कोशिकाओं में सुस्पष्ट झिल्ली-बद्ध केंद्रक पाया जाता है।'},
{question:'परासरण में मुख्य रूप से किसका संचरण होता है?',options:['जल','केवल प्रोटीन','केवल DNA','केवल वसा'],answer:0,explain:'परासरण अर्धपारगम्य झिल्ली के पार जल के संचरण से संबंधित है।'},
{question:'पादप कोशिका में बड़ी केंद्रीय रिक्तिका किसमें सहायक होती है?',options:['भंडारण और तुर्गता बनाए रखने में','केवल प्रोटीन संश्लेषण में','केवल संदेश भेजने में','केवल प्रकाश उत्सर्जन में'],answer:0,explain:'केंद्रीय रिक्तिका जल व घुले पदार्थों के भंडारण तथा कोशिका की तुर्गता में सहायता करती है।'},
{question:'पादप और जन्तु कोशिका में कौन-सा भाग दोनों में पाया जाता है?',options:['कोशिका झिल्ली','कोशिका भित्ति','हरितलवक','बड़ी केंद्रीय रिक्तिका'],answer:0,explain:'कोशिका झिल्ली दोनों प्रकार की कोशिकाओं का साझा प्रमुख भाग है।'},
{question:'कोशिका का आकार और संरचना किससे जुड़ी हो सकती है?',options:['उसके कार्य से','सिर्फ रंग से','सिर्फ तापमान से','सिर्फ उम्र से'],answer:0,explain:'कोशिकाएँ अपने कार्य के अनुसार आकार और संरचना में विशेषीकरण दिखा सकती हैं।'},
{question:'बहुकोशिकीय जीवों में कोशिकाएँ क्यों विशेषीकृत होती हैं?',options:['कार्य-विभाजन के लिए','केवल रंग बदलने के लिए','केवल आकार बढ़ाने के लिए','केवल भोजन रोकने के लिए'],answer:0,explain:'विभिन्न कार्यों को कुशलता से करने के लिए बहुकोशिकीय जीवों में कोशिकाएँ विशेषीकृत होती हैं।'},
{question:'कोशिका झिल्ली को चयनात्मक पारगम्य क्यों कहा जाता है?',options:['क्योंकि यह पदार्थों के आवागमन को नियंत्रित करती है','क्योंकि यह केवल पानी से बनी है','क्योंकि यह केंद्रक बनाती है','क्योंकि यह प्रकाश को बंद करती है'],answer:0,explain:'झिल्ली सभी पदार्थों को समान रूप से पार नहीं होने देती और आवागमन को नियंत्रित करती है।'},
{question:'यदि किसी कोशिका को अत्यधिक नमक वाले घोल में रखा जाए, तो परासरण के कारण क्या हो सकता है?',options:['जल कोशिका से बाहर जा सकता है','सिर्फ DNA बाहर जाएगा','कोशिका में हमेशा अधिक जल आएगा','कोई जल गति नहीं होगी'],answer:0,explain:'बाहरी घोल में जल की उपलब्धता कम होने पर जल कोशिका से बाहर की ओर जा सकता है।'}
];

const challenge=[
{question:'एक पादप कोशिका में जल की कमी होने पर रिक्तिका और कोशिका भित्ति की भूमिकाओं का सही संयुक्त वर्णन कौन-सा है?',options:['रिक्तिका जल भंडारण में और कोशिका भित्ति संरचनात्मक सहारे में मदद करती है','दोनों केवल प्रोटीन बनाते हैं','रिक्तिका DNA बनाती है और भित्ति ऊर्जा बनाती है','दोनों केवल प्रकाश को रोकते हैं'],answer:0,explain:'रिक्तिका भंडारण व तुर्गता में और कोशिका भित्ति संरचनात्मक सहारे में योगदान देती है।'},
{question:'यदि गॉल्जी तंत्र ठीक से काम न करे, तो कौन-सी प्रक्रिया सबसे सीधे प्रभावित होगी?',options:['संशोधन और पैकेजिंग','आनुवंशिक पदार्थ का मूल संग्रह','जल का परासरण ही','प्रकाश का अवशोषण'],answer:0,explain:'गॉल्जी तंत्र पदार्थों के संशोधन, छँटाई और पैकेजिंग में महत्वपूर्ण है।'},
{question:'किस विकल्प में खुरदरी और चिकनी ER का सही अंतर है?',options:['खुरदरी ER पर राइबोसोम होते हैं, चिकनी ER पर नहीं','दोनों पर गुणसूत्र होते हैं','चिकनी ER केवल पादप कोशिका में होती है','खुरदरी ER में केंद्रक होता है'],answer:0,explain:'खुरदरी ER की सतह पर राइबोसोम होते हैं; चिकनी ER पर राइबोसोम नहीं होते।'},
{question:'एक कोशिका में सुस्पष्ट झिल्ली-बद्ध केंद्रक और अनेक झिल्ली-बद्ध कोशिकांग पाए जाते हैं। यह किस प्रकार की कोशिका है?',options:['यूकैरियोटिक','प्रोकैरियोटिक','केवल एककोशिकीय','अकोशिकीय'],answer:0,explain:'सुस्पष्ट झिल्ली-बद्ध केंद्रक यूकैरियोटिक कोशिका की प्रमुख विशेषता है।'},
{question:'यदि कोशिका झिल्ली किसी पदार्थ का आवागमन रोक दे, तो इसका सीधा अर्थ क्या है?',options:['उस पदार्थ का झिल्ली के पार आवागमन नियंत्रित या बाधित है','केंद्रक नष्ट हो गया','माइटोकॉन्ड्रिया रुक गया','कोशिका विभाजन तुरंत शुरू हो गया'],answer:0,explain:'चयनात्मक पारगम्यता का अर्थ है कि पदार्थों का आवागमन झिल्ली द्वारा नियंत्रित होता है।'},
{question:'परासरण और सामान्य पदार्थ-विसरण में मुख्य अंतर किससे जुड़ा है?',options:['परासरण में जल का अर्धपारगम्य झिल्ली के पार संचरण प्रमुख है','परासरण में केवल DNA चलता है','विसरण में केवल कोशिकांग चलते हैं','दोनों में हमेशा ऊर्जा खर्च होती है'],answer:0,explain:'परासरण विशेष रूप से जल के अर्धपारगम्य झिल्ली के पार संचरण से संबंधित है।'},
{question:'किस स्थिति में कोशिका को कार्य-विभाजन का लाभ सबसे स्पष्ट होगा?',options:['बहुकोशिकीय जीव में अलग-अलग कोशिकाएँ अलग कार्य करें','एक कोशिका में सभी कार्य बंद हो जाएँ','केवल कोशिका भित्ति कार्य करे','केवल केंद्रक कार्य करे'],answer:0,explain:'बहुकोशिकीय जीवों में कोशिकीय विशेषीकरण कार्य-विभाजन को अधिक कुशल बनाता है।'},
{question:'किस युग्म में कोशिकांग और कार्य दोनों सही हैं?',options:['राइबोसोम–प्रोटीन संश्लेषण','हरितलवक–पैकेजिंग','गॉल्जी–प्रकाश संश्लेषण','लाइसोसोम–वंशागति संग्रह'],answer:0,explain:'राइबोसोम प्रोटीन संश्लेषण से संबंधित हैं।'},
{question:'यदि किसी कोशिका में माइटोकॉन्ड्रिया की गतिविधि घट जाए, तो कौन-सा प्रभाव सबसे तर्कसंगत है?',options:['उपयोगी ऊर्जा उपलब्ध कराने की क्षमता प्रभावित हो सकती है','कोशिका भित्ति तुरंत गायब हो जाएगी','गुणसूत्र कोशिका से बाहर निकलेंगे','हरितलवक पशु कोशिका में बन जाएगा'],answer:0,explain:'माइटोकॉन्ड्रिया कोशिकीय श्वसन और उपयोगी ऊर्जा उपलब्ध कराने में महत्वपूर्ण हैं।'},
{question:'किस कथन से पादप कोशिका की पहचान सबसे अच्छी होती है?',options:['कोशिका भित्ति, हरितलवक और बड़ी केंद्रीय रिक्तिका जैसे प्रमुख संकेत','केवल केंद्रक','केवल कोशिका झिल्ली','केवल कोशिकाद्रव्य'],answer:0,explain:'पादप कोशिका की पहचान में कोशिका भित्ति, हरितलवक और बड़ी केंद्रीय रिक्तिका प्रमुख संकेत हैं।'}
];

function Assessment({mode,chapter,bank,onBack,addXp,finishSession}){
 const [index,setIndex]=useState(0);const [selected,setSelected]=useState(null);const [score,setScore]=useState(0);const [done,setDone]=useState(false);const [history,setHistory]=useState([]);
 const items=useMemo(()=>{const source=mode==='challenge'?bank.challenge:bank.questions;const limit=mode==='challenge'?10:mode==='test'?20:15;return [...source].sort(()=>Math.random()-.5).slice(0,Math.min(limit,source.length));},[mode,bank]);
 const item=items[index];
 const choose=i=>{if(selected!==null)return;setSelected(i);const correct=i===item.answer;setScore(s=>s+(correct?1:0));addXp?.(correct?(mode==='challenge'?25:mode==='test'?10:5):0);setHistory(h=>[...h,{question:item.question,selected:i,answer:item.answer,options:item.options,explain:item.explain,correct}]);};
 const next=()=>{const finalScore=score+(selected===item.answer?1:0);if(index===items.length-1){setScore(finalScore);setDone(true);markStageComplete(`विज्ञान::${chapter}`,mode);finishSession?.({subject:'विज्ञान',chapter,mode,attempted:items.length,correct:finalScore,completed:true,at:Date.now()});return;}setIndex(i=>i+1);setSelected(null);};
 if(!item)return null;
 if(done)return <main className="page sc5-result-page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">विज्ञान • {chapter}</div><h1>{score>=items.length*.8?'बहुत बढ़िया!':'अच्छी कोशिश!'}</h1><p>{score} / {items.length} सही • {Math.round(score/items.length*100)}%</p></header><section className="page-content"><div className="science-complete"><h2>उत्तर समीक्षा</h2><p>हर प्रश्न का सही उत्तर और कारण नीचे देखें।</p><div className="sc5-review">{history.map((h,i)=><article key={`${h.question}-${i}`}><div><strong>प्रश्न {i+1}</strong><span className={h.correct?'good':'bad'}>{h.correct?'✓ सही':'✗ गलत'}</span></div><h3>{h.question}</h3><p><b>सही उत्तर:</b> {h.options[h.answer]}</p>{!h.correct&&<p><b>आपका उत्तर:</b> {h.options[h.selected]}</p>}<p className="review-explain">{h.explain}</p></article>)}</div><button className="primary-btn pressable" onClick={onBack}>अध्याय पर लौटें →</button></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">विज्ञान • {chapter}</span><span>{index+1} / {items.length}</span></div><h1>{mode==='test'?'🎯 टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className="quiz-progress"><span style={{width:`${((index+1)/items.length)*100}%`}}/></div></header><section className="page-content"><article className="science-question-card"><span className="question-number">प्रश्न {index+1}</span><h2>{item.question}</h2><div className="science-options">{item.options.map((option,i)=><button type="button" disabled={selected!==null} className={`answer-option pressable ${selected!==null&&i===item.answer?'correct':''} ${selected===i&&i!==item.answer?'wrong':''} ${selected!==null&&i!==item.answer&&i!==selected?'muted':''}`} key={option} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{selected!==null&&<div className={`science-feedback ${selected===item.answer?'good':'bad'}`}><strong>{selected===item.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{item.explain}</p></div>}<div className="science-quiz-actions"><span>{selected===null?'उत्तर चुनें':'उत्तर दर्ज हो गया'}</span><button className="primary-btn pressable" disabled={selected===null} onClick={next}>{index===items.length-1?'परिणाम देखें':'अगला →'}</button></div></article></section></main>;
}

const visualMap={
 cell:'cell',singleMulti:'singleMulti',plantAnimal:'plantAnimal',membrane:'membrane',wall:'wall',nucleus:'nucleus',mitochondria:'mitochondria',plastid:'plastid',er:'er',golgi:'golgi',lysosome:'lysosome',vacuole:'vacuole',prokaryote:'prokaryote',eukaryote:'eukaryote',osmosis:'osmosis',division:'division'
};

function ChapterLanding({chapter,data,onBack,setMode}){
 const focus=['कोशिका की मूल योजना','झिल्ली और कोशिका भित्ति','केंद्रक व आनुवंशिक पदार्थ','प्रमुख कोशिकांग','पादप बनाम जन्तु कोशिका','परासरण व विसरण','प्रोकैरियोटिक व यूकैरियोटिक कोशिका'];
 return <main className="page science-chapter-page sc5-landing"><header className="page-header science-header"><button className="pressable" onClick={onBack}>← विषय</button><div className="badge">कक्षा 9 • विज्ञान • अध्याय 5</div><h1>{chapter}</h1><p>कोशिका की संरचना को भाग-दर-भाग समझें, फिर अपनी समझ को अभ्यास, चुनौती और टेस्ट से परखें।</p></header><section className="page-content"><div className="science-launch sc5-launch"><div><span className="science-kicker">अध्याय अध्ययन मानचित्र</span><h2>{data.goal}</h2><p>यहाँ पहले कोशिका की मूल योजना, फिर झिल्ली, केंद्रक, कोशिकांग, परिवहन और कोशिका-प्रकारों को क्रम से समझें।</p></div><div className="sc5-map-card"><strong>क्या-क्या सीखेंगे?</strong><div>{focus.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div></div></div><div className="science-mode-grid"><button className="mode-card pressable" onClick={()=>setMode('learn')}><span>📖</span><strong>सीखें</strong><small>{data.lessons.length} सीखने के चरण</small><b>शुरू करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('practice')}><span>📝</span><strong>अभ्यास</strong><small>15 प्रश्न</small><b>अभ्यास करें →</b></button><button className="mode-card pressable" onClick={()=>setMode('challenge')}><span>🔥</span><strong>चुनौती</strong><small>10 कठिन प्रश्न</small><b>चुनौती लें →</b></button><button className="mode-card pressable" onClick={()=>setMode('test')}><span>🎯</span><strong>टेस्ट</strong><small>20 प्रश्न</small><b>टेस्ट दें →</b></button></div></section></main>;
}

export function ScienceChapter5Engine({chapter,onBack,addXp,finishSession}){
 const [mode,setMode]=useState(null);
 if(mode==='learn')return <ScienceLearnView chapter={chapter} chapterNumber={5} title={chapter} lessons={scienceChapter5Learning.lessons} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession} renderVisual={item=>item?.visual?<ScienceChapter5Visual kind={visualMap[item.visual.type]||'cell'}/>:null} completeIcon="🔬"/>;
 if(mode)return <Assessment mode={mode} chapter={chapter} bank={{questions,challenge}} onBack={()=>setMode(null)} addXp={addXp} finishSession={finishSession}/>;
 return <ChapterLanding chapter={chapter} data={scienceChapter5Learning} onBack={onBack} setMode={setMode}/>;
}

export default ScienceChapter5Engine;
