import React,{useEffect,useMemo,useState} from 'react';
import {getPracticeQuestions} from './practiceData';
import './engine.css';

const TEST_SECONDS=600;
function saveMistake(item,subject,chapter,selected){try{const key='class9-mistakes';const old=JSON.parse(localStorage.getItem(key)||'[]');const rec={id:`${subject}|${chapter}|${item.q}`,subject,chapter,question:item.q,options:item.options,answer:item.answer,explain:item.explain,selected,at:Date.now()};localStorage.setItem(key,JSON.stringify([rec,...old.filter(x=>x.id!==rec.id)].slice(0,100)));}catch{}}
function loadMistakes(){try{return JSON.parse(localStorage.getItem('class9-mistakes')||'[]')}catch{return[]}}

export function StudyEngine({subject,chapter,mode,onBack,addXp}){
 const base=getPracticeQuestions(subject?.name,chapter);
 const questions=useMemo(()=>mode==='challenge'?[...base].reverse().map(q=>({...q,q:`🔥 चुनौती: ${q.q}`})):base,[base,mode]);
 const isTest=mode==='test';
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[mistakes,setMistakes]=useState([]),[earned,setEarned]=useState(0),[remaining,setRemaining]=useState(TEST_SECONDS),[showReview,setShowReview]=useState(false);
 useEffect(()=>{if(!isTest||done)return;const id=setInterval(()=>setRemaining(s=>{if(s<=1){clearInterval(id);setDone(true);return 0}return s-1}),1000);return()=>clearInterval(id)},[isTest,done]);
 const current=questions[index],points=mode==='challenge'?25:15,label=mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास';
 const choose=i=>{if(selected!==null||done)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp(points)}}else{setMistakes(m=>[...m,index]);saveMistake(current,subject?.name,chapter,i)}};
 const next=()=>{if(selected===null&&!isTest)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 const restart=()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setMistakes([]);setEarned(0);setRemaining(TEST_SECONDS);setShowReview(false)};
 const percent=Math.round(score/questions.length*100),mm=String(Math.floor(remaining/60)).padStart(2,'0'),ss=String(remaining%60).padStart(2,'0');
 if(done){
   const reviewItems=loadMistakes().filter(x=>x.subject===subject?.name&&x.chapter===chapter);
   if(showReview)return <ReviewView items={reviewItems} back={()=>setShowReview(false)}/>;
   return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="badge">कक्षा 9 • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':label+' पूरी'}</h1></header><section className="page-content"><div className="result-card"><div className="result-score">{score}<small>/ {questions.length}</small></div><div className="result-percent">{percent}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभ्यास जारी रखें 📚'}</h2><p>{isTest?'टेस्ट पूरा हो गया।':`आपने ${earned} XP कमाए।`}</p>{reviewItems.length>0&&<button className="review-link pressable" onClick={()=>setShowReview(true)}>📕 मेरी गलतियाँ देखें ({reviewItems.length})</button>} {mistakes.length>0&&!isTest&&<div className="review-note">📌 {mistakes.length} गलत प्रश्न समीक्षा में सेव किए गए हैं।</div>}<div className="result-actions"><button className="secondary-btn pressable" onClick={restart}>फिर से करें</button><button className="primary-btn pressable" onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 }
 return <main className="page"><header className="page-header"><button className="pressable" onClick={onBack}>← अध्याय</button><div className="lesson-top"><span className="badge">{subject?.name} • {chapter}</span>{isTest?<span className="timer-pill">⏱ {mm}:{ss}</span>:<span>{index+1} / {questions.length}</span>}</div><h1>{isTest?'🎯 समयबद्ध टेस्ट':label}</h1><div className="lesson-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className="page-content"><div className="question-card"><span className="lesson-type">प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className="options-grid">{current.options.map((option,i)=><button key={option} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{isTest?'✓ उत्तर दर्ज':selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{isTest?'टेस्ट पूरा होने पर सही उत्तर और explanation review में दिखाई जाएगी।':current.explain}</p></div>}<div className="question-actions"><span>{isTest?'टेस्ट मोड • सही उत्तर अंत में':selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className="primary-btn pressable" onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>;
}

function ReviewView({items,back}){const [item,setItem]=useState(null);if(item)return <main className="page"><header className="page-header"><button className="pressable" onClick={()=>setItem(null)}>← गलतियाँ</button><div className="badge">गलती समीक्षा</div><h1>उत्तर समझें</h1></header><section className="page-content"><div className="review-card"><span className="lesson-type">गलत प्रश्न • {item.subject}</span><h2>{item.question}</h2><div className="review-row wrong-row"><strong>आपका उत्तर</strong><span>{item.options[item.selected]}</span></div><div className="review-row correct-row"><strong>सही उत्तर</strong><span>{item.options[item.answer]}</span></div><div className="review-explain"><strong>क्यों सही है?</strong><p>{item.explain}</p></div><button className="primary-btn pressable" onClick={()=>setItem(null)}>ठीक है, समझ गया ✓</button></div></section></main>;
 return <main className="page"><header className="page-header"><button className="pressable" onClick={back}>← परिणाम</button><div className="badge">गलती समीक्षा</div><h1>📕 मेरी गलतियाँ</h1><p>हर गलत प्रश्न को समझें — फिर वही गलती दोबारा न करें।</p></header><section className="page-content">{items.length===0?<div className="empty-review"><span>🎉</span><h2>इस अध्याय में कोई गलती नहीं मिली</h2></div>:<div className="review-list">{items.map((x,i)=><button className="review-item pressable" key={x.id||i} onClick={()=>setItem(x)}><span className="review-no">{i+1}</span><div><strong>{x.question}</strong><small>आपका उत्तर: {x.options[x.selected]} • सही: {x.options[x.answer]}</small></div><b>समझें →</b></button>)}</div>}</section></main>;
}

export function TestEngine(props){return <StudyEngine {...props} mode="test"/>}
