import React,{useMemo,useState}from'react';

const TESTS=[
{n:'01',date:'13 Sep 2026',label:'Foundation + opening chapters',subjects:{Maths:'Ch 1–2',Science:'Ch 1–2',Hindi:'g1–g2 + p1',Sanskrit:'Ch 1–2',SST:'H1–2 · G1 · C1 · E1',English:'Reader 1–2 · Prose 1'},status:'Planned'},
{n:'02',date:'27 Sep 2026',label:'Continue syllabus coverage',subjects:{Maths:'Ch 3–4',Science:'Ch 3–4',Hindi:'g3–g4 + p2',Sanskrit:'Ch 3–4',SST:'H3–4 · G2–3 · C2 · E2',English:'Reader 3–4 · Prose 2'},status:'Planned'},
{n:'03',date:'11 Oct 2026',label:'Early-to-mid syllabus',subjects:{Maths:'Ch 5–6',Science:'Ch 5–6',Hindi:'g5–g6 + p3',Sanskrit:'Ch 5–6',SST:'H5–6 · G4–5 · C3 · E3',English:'Reader 5–6 · Prose 3 · Poetry 10'},status:'Planned'},
{n:'04',date:'25 Oct 2026',label:'Mid-syllabus',subjects:{Maths:'Ch 7–8',Science:'Ch 7–8',Hindi:'g7–g8 + p4–p5',Sanskrit:'Ch 7–8',SST:'H7–8 · G6–7 · C4 · E4',English:'Reader 7–8 · Prose 4–5'},status:'Planned'},
{n:'05',date:'08 Nov 2026',label:'Mid-to-late syllabus',subjects:{Maths:'Ch 9–10',Science:'Ch 9–10',Hindi:'g9–g10 + p6–p7',Sanskrit:'Ch 9–10',SST:'G8–10 · C5 · E5–6',English:'Prose 6–7 · Poetry 11–12'},status:'Planned'},
{n:'06',date:'22 Nov 2026',label:'Late syllabus coverage',subjects:{Maths:'Ch 11–12',Science:'Ch 11–12',Hindi:'g11–g12 + p8–p9',Sanskrit:'Ch 11–12',SST:'G11–13 · C6 · revision block',English:'Prose 8–9 · Poetry 13–14 · Read 1'},status:'Planned'},
{n:'07',date:'06 Dec 2026',label:'Syllabus completion push',subjects:{Maths:'Ch 13–14',Science:'Ch 13–14',Hindi:'p10–p11',Sanskrit:'Ch 13–14',SST:'H1–8 · G1–7 · C1–3 · E1–3 revision',English:'Poetry 15–16 · Read 2'},status:'Planned'},
{n:'08',date:'20 Dec 2026',label:'First-pass completion + integration',subjects:{Maths:'Ch 15 + mixed Ch 1–15',Science:'Ch 15 + mixed Ch 1–15',Hindi:'p12 + mixed g1–g12 · p1–p12',Sanskrit:'Ch 15 + mixed Primary Ch 1–15',SST:'H1–8 · G8–13 · C4–6 · E4–6 revision',English:'Poetry 17 · Read 3 · mixed Reader/Prose/Poetry'},status:'Milestone'},
{n:'09',date:'03 Jan 2027',label:'Full Syllabus Revision I',subjects:{Maths:'Ch 1–15 balanced',Science:'Ch 1–15 balanced',Hindi:'g1–g12 + p1–p12',Sanskrit:'Primary Ch 1–15',SST:'All 33 chapters',English:'Reader 1–8 · Prose 1–9 · Poetry 10–17 · Read 1–3'},status:'Revision'},
{n:'10',date:'17 Jan 2027',label:'Weak-Area + Mixed Revision',subjects:{Maths:'Performance-weighted',Science:'Performance-weighted',Hindi:'Performance-weighted',Sanskrit:'Performance-weighted',SST:'Performance-weighted',English:'Performance-weighted'},status:'Revision'},
{n:'11',date:'31 Jan 2027',label:'Full BSEB-Style Mock Examination',subjects:{Maths:'Full syllabus',Science:'Full syllabus',Hindi:'Full syllabus',Sanskrit:'Full syllabus',SST:'Full syllabus',English:'Full syllabus'},status:'Mock'},
{n:'12',date:'14 Feb 2027',label:'Final Pre-Board / Readiness Test',subjects:{Maths:'Full syllabus',Science:'Full syllabus',Hindi:'Full syllabus',Sanskrit:'Full syllabus',SST:'Full syllabus',English:'Full syllabus'},status:'Mock'},
{n:'Final',date:'28 Feb 2027',label:'Final Examination',subjects:{Maths:'Complete Class 9 syllabus',Science:'Complete Class 9 syllabus',Hindi:'Complete Class 9 syllabus',Sanskrit:'Complete Class 9 syllabus',SST:'Complete Class 9 syllabus',English:'Complete Class 9 syllabus'},status:'Final'},
];
const SUBJECTS=['Maths','Science','Hindi','Sanskrit','SST','English'];
const css={page:{minHeight:'100vh',padding:'28px 18px 56px',background:'linear-gradient(135deg,#f8fafc,#eef2ff)',fontFamily:'Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',color:'#172033'},wrap:{maxWidth:1180,margin:'0 auto'},back:{border:0,background:'transparent',fontWeight:700,fontSize:15,cursor:'pointer',marginBottom:16,color:'#46546c'},hero:{background:'linear-gradient(135deg,#18253f,#314b79)',borderRadius:24,padding:'30px 28px',color:'#fff',boxShadow:'0 18px 44px rgba(30,41,59,.16)'},eyebrow:{fontSize:12,letterSpacing:1.4,fontWeight:800,opacity:.76},title:{margin:'7px 0 8px',fontSize:'clamp(30px,5vw,48px)',lineHeight:1.05},lead:{margin:0,maxWidth:820,lineHeight:1.65,opacity:.9},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:14,marginTop:18},stat:{background:'rgba(255,255,255,.1)',border:'1px solid rgba(255,255,255,.15)',borderRadius:16,padding:'13px 14px'},statStrong:{display:'block',fontSize:22},controls:{display:'flex',gap:10,flexWrap:'wrap',margin:'22px 0'},chip:{padding:'9px 13px',borderRadius:999,border:'1px solid #d7deeb',background:'#fff',cursor:'pointer',fontWeight:700},chipOn:{background:'#172033',color:'#fff',borderColor:'#172033'},section:{marginTop:22},sectionTitle:{margin:'0 0 12px',fontSize:22},cards:{display:'grid',gap:14},card:{background:'#fff',border:'1px solid #e4e9f2',borderRadius:20,padding:18,boxShadow:'0 8px 26px rgba(15,23,42,.06)'},cardTop:{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'},testNo:{fontSize:12,fontWeight:900,letterSpacing:1.2,color:'#667085'},date:{fontSize:18,fontWeight:850,marginTop:4},tag:{fontSize:11,fontWeight:800,padding:'7px 10px',borderRadius:999,background:'#edf2ff',color:'#374151'},purpose:{margin:'10px 0 14px',fontWeight:700},subjectGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:9},subject:{padding:11,borderRadius:13,background:'#f7f9fc',border:'1px solid #e9edf4'},subjectName:{fontSize:11,fontWeight:800,color:'#667085',textTransform:'uppercase',letterSpacing:.5},subjectVal:{display:'block',marginTop:4,fontWeight:700,lineHeight:1.35},note:{marginTop:10,fontSize:13,color:'#667085'}};

export default function TestCentrePlanner(){
 const[filter,setFilter]=useState('All');
 const[expanded,setExpanded]=useState('01');
 const visible=useMemo(()=>filter==='All'?TESTS:TESTS.filter(t=>t.status===filter),[filter]);
 const back=()=>{const p=new URLSearchParams();p.set('page','home');window.history.pushState({},'',`${window.location.pathname}?${p}`);window.dispatchEvent(new PopStateEvent('popstate'))};
 const filters=['All','Planned','Milestone','Revision','Mock','Final'];
 return <main style={css.page}><div style={css.wrap}><button type="button" onClick={back} style={css.back}>← वापस होम</button><header style={css.hero}><div style={css.eyebrow}>CLASS 9 • BIHAR BOARD • 2026–27</div><h1 style={css.title}>Test Centre</h1><p style={css.lead}>नियत तिथियों पर होने वाले रविवार के टेस्ट, revision papers और mock examinations यहाँ दिखाई देंगे। Test तभी learner-facing बनेगा जब उसका question bank अलग से तैयार और QA-pass होकर publish किया जाए।</p><div style={css.grid}><div style={css.stat}><span>Academic Tests</span><strong style={css.statStrong}>12</strong></div><div style={css.stat}><span>Final Exam</span><strong style={css.statStrong}>28 Feb 2027</strong></div><div style={css.stat}><span>Subjects / Test</span><strong style={css.statStrong}>6</strong></div><div style={css.stat}><span>Current State</span><strong style={css.statStrong}>Planner Live</strong></div></div></header><section style={css.controls} aria-label="Test filters">{filters.map(f=><button key={f} type="button" onClick={()=>setFilter(f)} style={{...css.chip,...(filter===f?css.chipOn:{})}}>{f}</button>)}</section><section style={css.section}><h2 style={css.sectionTitle}>2026–27 Examination Calendar</h2><div style={css.cards}>{visible.map(t=>{const open=expanded===t.n;return <article key={t.n} style={css.card}><div style={css.cardTop}><div><div style={css.testNo}>{t.n==='Final'?'FINAL EXAM':'TEST '+t.n}</div><div style={css.date}>{t.date}</div></div><span style={css.tag}>{t.status}</span></div><p style={css.purpose}>{t.label}</p><button type="button" onClick={()=>setExpanded(open?'':t.n)} style={{...css.chip,padding:'8px 11px'}}>{open?'विवरण छिपाएँ':'सिलेबस देखें'} →</button>{open&&<><div style={{height:10}}/><div style={css.subjectGrid}>{SUBJECTS.map(s=><div key={s} style={css.subject}><span style={css.subjectName}>{s}</span><span style={css.subjectVal}>{t.subjects[s]}</span></div>)}</div><div style={css.note}>{t.n==='Final'?'यह अंतिम परीक्षा है; पूरी कक्षा 9 की तैयारी target है.':t.n==='10'?'Weak-area weighting learner performance history के आधार पर बाद में लागू की जाएगी.':t.n==='11'||t.n==='12'?'Mock paper full-syllabus और BSEB-style format में अलग question bank के रूप में publish होगा.':'इस entry का calendar fixed है; question bank publish होने तक यह केवल planner entry है.'}</div></>}</article>})}</div></section></div></main>;
}
