import React,{useMemo,useState} from 'react';
import {chapter7Practice} from './chapter7Practice';
const challenge=[
{q:'यदि ΔABC में AB=AC और D, BC का मध्यबिंदु है, तो AD के बारे में क्या सिद्ध किया जा सकता है?',options:['AD केवल माध्यिका है','AD माध्यिका और लंब दोनों है','AD केवल ऊँचाई है','AD, BC के समानांतर है'],answer:1,explain:'AB=AC वाले समद्विबाहु त्रिभुज में आधार के मध्यबिंदु से शीर्ष तक खींची गई रेखा दोनों छोटे त्रिभुजों को भुजा-भुजा-भुजा कसौटी से सर्वांगसम सिद्ध करने में मदद करती है; इसलिए AD आधार पर लंब भी होता है।'},
{q:'यदि ΔABC ≅ ΔPQR और AC=11 सेमी, तो PR कितना होगा?',options:['9 सेमी','10 सेमी','11 सेमी','12 सेमी'],answer:2,explain:'क्रम ABC ↔ PQR में C ↔ R है, इसलिए AC और PR संगत हैं। अतः PR=11 सेमी।'},
{q:'यदि किसी त्रिभुज में दो भुजाएँ 7 सेमी और 10 सेमी हैं, तो तीसरी भुजा x के लिए कौन-सी सीमा सही है?',options:['x>17','3<x<17','x<3','7<x<10'],answer:1,explain:'त्रिभुज असमानता से |10−7|<x<10+7, इसलिए 3<x<17।'},
{q:'दो त्रिभुजों में केवल तीन कोण क्रमशः बराबर हैं। इससे सर्वांगसमता क्यों सिद्ध नहीं होती?',options:['क्योंकि कोण मापे नहीं जा सकते','क्योंकि आकार समान हो सकता है पर माप अलग हो सकता है','क्योंकि त्रिभुज में तीन कोण नहीं होते','क्योंकि भुजाएँ हमेशा असमान होती हैं'],answer:1,explain:'केवल कोणों की समानता से आकार समान हो सकता है, लेकिन त्रिभुज का वास्तविक माप अलग हो सकता है।'},
{q:'यदि AB>AC, तो उनके सामने के कोणों में कौन बड़ा होगा?',options:['∠B','∠C','दोनों बराबर','कोई नहीं'],answer:1,explain:'बड़ी भुजा के सामने बड़ा कोण होता है। AB के सामने ∠C है, इसलिए ∠C बड़ा होगा।'},
{q:'यदि दो त्रिभुज भुजा-कोण-भुजा कसौटी से सर्वांगसम हैं, तो कौन-सा भाग भी निश्चित रूप से बराबर होगा?',options:['सभी संगत कोण','केवल तीसरी भुजा नहीं','कोई भाग नहीं','केवल क्षेत्रफल'],answer:0,explain:'सर्वांगसमता के बाद सभी संगत भुजाएँ और कोण बराबर होते हैं।'},
{q:'यदि 4, 5 और x किसी त्रिभुज की भुजाएँ हैं, तो x=1 क्यों संभव नहीं है?',options:['4+1>5 नहीं है','5+1>4 है','4+5>1 है','सभी शर्तें पूरी हैं'],answer:0,explain:'4+1=5 है, जो तीसरी भुजा के बराबर है; त्रिभुज बनने के लिए योग सख्ती से बड़ा होना चाहिए।'},
{q:'यदि AB=AC और ∠A=40°, तो आधार कोण कितने होंगे?',options:['40°,40°','60°,80°','70°,70°','80°,60°'],answer:2,explain:'AB=AC से ∠B=∠C। दोनों का योग 180−40=140° है, इसलिए प्रत्येक 70°।'},
{q:'यदि ΔABC ≅ ΔDEF, तो AC किसके संगत है?',options:['DE','DF','EF','FD नहीं हो सकता'],answer:1,explain:'क्रम ABC ↔ DEF में A↔D और C↔F, इसलिए AC ↔ DF।'},
{q:'किस स्थिति में प्रमाण लिखते समय केवल चित्र पर भरोसा करना सबसे गलत होगा?',options:['जब कोई कोण चित्र में बराबर दिखे','जब बराबर कोण दिया हुआ हो','जब भुजा की लंबाई दी हुई हो','जब सर्वांगसमता कसौटी दी गई हो'],answer:0,explain:'चित्र अनुमान दे सकता है, लेकिन सामान्य गणितीय निष्कर्ष दिए गए तथ्यों और तर्क से सिद्ध होना चाहिए।'}
];
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
export function TrianglesEngine({chapter,mode,onBack,addXp}){
 const isTest=mode==='test';
 const questions=useMemo(()=>isTest?shuffle(chapter7Practice).slice(0,15):mode==='challenge'?challenge:chapter7Practice,[mode,isTest]);
 const[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[earned,setEarned]=useState(0);
 const current=questions[index],points=mode==='challenge'?25:15;
 const choose=i=>{if(selected!==null||!current)return;setSelected(i);if(i===current.answer){setScore(s=>s+1);if(!isTest){setEarned(e=>e+points);addXp?.(points)}}};
 const next=()=>{if(selected===null)return;if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setSelected(null)}};
 if(done)return <main className='page'><header className='page-header'><button className='pressable' onClick={onBack}>← अध्याय</button><div className='badge'>त्रिभुज • परिणाम</div><h1>{isTest?'🎯 टेस्ट परिणाम':mode==='challenge'?'🔥 चुनौती पूरी':'📝 अभ्यास पूरा'}</h1></header><section className='page-content'><div className='result-card'><div className='result-score'>{score}<small> / {questions.length}</small></div><div className='result-percent'>{Math.round(score/questions.length*100)}% सही</div><h2>{score===questions.length?'शानदार! 🎉':score>=questions.length*.7?'बहुत अच्छा! 💪':'अभी और अभ्यास करें 📚'}</h2><p>{isTest?'टेस्ट पूरा हुआ।':'आपने '+earned+' XP कमाए।'}</p><div className='result-actions'><button className='secondary-btn pressable' onClick={()=>{setIndex(0);setSelected(null);setScore(0);setDone(false);setEarned(0)}}>फिर से करें</button><button className='primary-btn pressable' onClick={onBack}>अध्याय पर जाएँ →</button></div></div></section></main>;
 return <main className='page'><header className='page-header'><button className='pressable' onClick={onBack}>← अध्याय</button><div className='lesson-top'><span className='badge'>गणित • त्रिभुज</span><span>{index+1} / {questions.length}</span></div><h1>{isTest?'🎯 समयबद्ध टेस्ट':mode==='challenge'?'🔥 चुनौती':'📝 अभ्यास'}</h1><div className='lesson-progress'><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></header><section className='page-content'><div className='question-card'><span className='lesson-type'>प्रश्न {index+1} / {questions.length}{!isTest&&` • +${points} XP`}</span><h2>{current.q}</h2><div className='options-grid'>{current.options.map((option,i)=><button key={`${option}-${i}`} disabled={selected!==null} className={`answer-option pressable ${selected!==null?(i===current.answer?'correct':i===selected?'wrong':'muted'):''}`} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {option}</button>)}</div>{selected!==null&&<div className={`answer-feedback ${selected===current.answer?'good':'bad'}`}><strong>{selected===current.answer?'✓ सही उत्तर':'✗ गलत उत्तर'}</strong><p>{current.explain}</p></div>}<div className='question-actions'><span>{selected===null?'उत्तर चुनें':`स्कोर: ${score}/${index+1}`}</span><button className='primary-btn pressable' onClick={next}>{index===questions.length-1?'परिणाम देखें':'अगला प्रश्न →'}</button></div></div></section></main>
}
