import React,{useEffect,useRef}from'react';
import {awardSmartXP}from'./engines/xp/xpRules.js';
import {getXPState}from'./engines/xp/xpStore.js';
import {recordActivityAndRewards}from'./engines/xp/xpRewards.js';
import {getCanonicalProgress}from'./engines/progress/progressStore.js';
import {XPAchievementOverlay,ChapterCompletionOverlay}from'./XPBadges.jsx';
import {cbtConfig}from'./cbtConfig';

const STAGES=new Set(['learn','practice','challenge','test']);
const REQUIRED_STAGES=['learn','practice','challenge','test'];
const textOf=node=>String(node?.textContent||'').replace(/\s+/g,' ').trim();
const hash=raw=>{let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)};
const newAttemptId=()=>{try{if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID()}catch{}return`attempt-${Date.now()}-${Math.random().toString(36).slice(2,10)}`};
const resolveContext=()=>{if(typeof window==='undefined')return null;const params=new URLSearchParams(window.location.search);const stageCandidate=params.get('mode')||params.get('reasoningMode')||'';const stage=STAGES.has(stageCandidate)?stageCandidate:null;const subjectId=String(params.get('subject')||'').trim();if(!stage||!subjectId)return null;const canonicalTopicId=String(params.get('topic')||params.get('topicId')||params.get('chapter')||'').trim();const contextEntries=[...params.entries()].filter(([k])=>!['page','mode','reasoningMode'].includes(k)).sort(([a],[b])=>a.localeCompare(b));const context=contextEntries.map(([k,v])=>`${k}=${v}`).join('&');const contextHash=hash(context||subjectId);const topicId=canonicalTopicId||`context:${contextHash}`;return{stage,subjectId,topicId,activityId:`hub:${subjectId}:${topicId}:stage:${stage}`,routeKey:`${subjectId}|${topicId}|${stage}`}};
const scoreFromRoot=root=>{const raw=textOf(root?.querySelector('.result-score'))||textOf([...root.querySelectorAll('[class]')].find(node=>/\b\d+\s*\/\s*\d+\b/.test(textOf(node))&&/result|score|quiz/i.test(String(node.className||''))));const match=raw.match(/(\d+)\s*\/\s*(\d+)/);if(match){const correct=Number(match[1]),total=Math.max(0,Number(match[2]));return{correctAnswers:correct,questionsTotal:total,scorePercent:total?Math.round(correct/total*100):0}}const pm=textOf(root?.querySelector('.result-percent')).match(/(\d+(?:\.\d+)?)\s*%/);return pm?{correctAnswers:0,questionsTotal:0,scorePercent:Number(pm[1])}:{correctAnswers:0,questionsTotal:0,scorePercent:0}};
const hasCompletion=({root,stage})=>{if(!root)return false;if(root.querySelector('.result-card,.completion-hero,.completion-grid .result-score,.etq-result,.etq-result-card,[class*="result-card"],[class*="result-panel"],[class*="quiz-result"],[class*="score-card"]'))return true;const candidates=[...root.querySelectorAll('[class]')].filter(node=>/(result|completion|score)/i.test(String(node.className||'')));return candidates.some(node=>{const text=textOf(node);if(!text)return false;const score=/\b\d+\s*\/\s*\d+\b/.test(text)||/\b\d+(?:\.\d+)?\s*%/.test(text);const complete=/(?:completed|complete|chapter\s+finished|final\s+test|result|परिणाम|पूरा\s+हुआ|अध्याय\s+पूरा|सीखना\s+पूरा)/i.test(text);return score||(stage==='learn'&&complete)})};
const isChapterComplete=(subjectId,topicId)=>{const state=getCanonicalProgress();const row=state?.topics?.[`${subjectId}::${topicId}`];return Boolean(row?.stages&&REQUIRED_STAGES.every(stage=>row.stages[stage]===true))};
const dispatchCompletion=(context,result,outcome)=>{setTimeout(()=>{try{window.dispatchEvent(new CustomEvent('class9-xp-completion',{detail:{...context,result,...outcome}}))}catch{}},0)};
const awardCompleted=({stage,activityId,attemptId,subjectId,topicId,result})=>{const before=getXPState().totalXp;const awarded=awardSmartXP({stage,activityId,attemptId,subjectId,topicId,result});const after=getXPState().totalXp;const rewards=recordActivityAndRewards({previousXp:before,currentXp:after,subjectId});return{awarded,rewards,totalXp:after}};

export function XPCompletionBoundary({children}){
 const rootRef=useRef(null),activeRouteKey=useRef(''),wasComplete=useRef(false),lastEventMarker=useRef(''),completedChapters=useRef(new Set());
 useEffect(()=>{
  const root=rootRef.current;if(!root)return undefined;
  const announceChapterCompletion=(context,result={},outcome={})=>{if(!context?.subjectId||!context?.topicId)return;const key=`${context.subjectId}::${context.topicId}`;if(completedChapters.current.has(key))return;if(!isChapterComplete(context.subjectId,context.topicId))return;completedChapters.current.add(key);dispatchCompletion(context,result,outcome)};
  const awardForContext=(context,resultOverride=null)=>{if(!context||wasComplete.current)return;wasComplete.current=true;const result=resultOverride||{...scoreFromRoot(root),completed:true};const outcome=awardCompleted({stage:context.stage,activityId:context.activityId,attemptId:newAttemptId(),subjectId:context.subjectId,topicId:context.topicId,result});if(context.stage==='test')announceChapterCompletion(context,result,outcome)};
  const resetForRoute=(context)=>{const key=context?.routeKey||'';if(key!==activeRouteKey.current){activeRouteKey.current=key;wasComplete.current=false;lastEventMarker.current='';}};
  const settle=()=>{const context=resolveContext();resetForRoute(context);if(!context)return;if(!wasComplete.current&&hasCompletion({root,stage:context.stage}))awardForContext(context)};
  const onCanonicalProgress=event=>{const context=resolveContext();resetForRoute(context);if(!context||wasComplete.current)return;const detail=event?.detail||{};if(String(detail.subjectId||'')!==context.subjectId||String(detail.stage||'')!==context.stage||String(detail.topicId||'')!==context.topicId)return;const marker=`${context.routeKey}:${String(detail.lastActivityAt||'')}`;if(marker===lastEventMarker.current)return;lastEventMarker.current=marker;window.setTimeout(()=>awardForContext(context,{completed:true,correctAnswers:Number(detail.analytics?.correctAnswers||0),questionsTotal:Number(detail.analytics?.questionsTotal||0),scorePercent:Number(detail.analytics?.lastPercent||0)}),0)};
  const onCanonicalCompletion=event=>{const detail=event?.detail||{};const subjectId=String(detail.subjectId||'').trim();const topicId=String(detail.topicId||'').trim();if(!subjectId||!topicId)return;const stage=STAGES.has(String(detail.stage||''))?String(detail.stage):'test';const context={stage,subjectId,topicId,activityId:`hub:${subjectId}:${topicId}:canonical-completion`,routeKey:`${subjectId}|${topicId}|canonical-completion`};const result={completed:true,correctAnswers:Number(detail.analytics?.correctAnswers||0),questionsTotal:Number(detail.analytics?.questionsTotal||0),scorePercent:Number(detail.analytics?.lastPercent||0)};window.setTimeout(()=>announceChapterCompletion(context,result),50)};
  settle();
  const observer=new MutationObserver(settle);observer.observe(root,{childList:true,subtree:true,characterData:true});
  const routePoll=setInterval(settle,250);
  window.addEventListener('class9-progress-updated',onCanonicalProgress);
  window.addEventListener('class9-progress-updated',onCanonicalCompletion);
  const onCbtMessage=event=>{if(event.origin!==new URL(cbtConfig.url).origin)return;const data=event.data;if(!data||data.type!=='class9-cbt-result')return;const correctAnswers=Number(data.correctAnswers),questionsTotal=Number(data.questionsTotal);if(!Number.isSafeInteger(correctAnswers)||!Number.isSafeInteger(questionsTotal)||correctAnswers<0||questionsTotal<1||correctAnswers>questionsTotal)return;const activityId=String(data.activityId||'cbt-bseb').replace(/[^A-Za-z0-9._:-]+/g,'-').slice(0,120);const attemptId=String(data.attemptId||newAttemptId()).replace(/[^A-Za-z0-9._:-]+/g,'-').slice(0,80);const subjectId=String(data.subjectId||'class9').slice(0,160);const topicId=String(data.topicId||'test-centre').slice(0,160);const outcome=awardCompleted({stage:'test',activityId,attemptId,subjectId,topicId,result:{completed:true,correctAnswers,questionsTotal,scorePercent:Math.round(correctAnswers/questionsTotal*100)}});if(isChapterComplete(subjectId,topicId))announceChapterCompletion({stage:'test',activityId,attemptId,subjectId,topicId},{completed:true,correctAnswers,questionsTotal},outcome)};
  window.addEventListener('message',onCbtMessage);
  return()=>{observer.disconnect();clearInterval(routePoll);window.removeEventListener('class9-progress-updated',onCanonicalProgress);window.removeEventListener('class9-progress-updated',onCanonicalCompletion);window.removeEventListener('message',onCbtMessage)};
 },[]);
 return <div ref={rootRef}>{children}<XPAchievementOverlay/><ChapterCompletionOverlay/></div>;
}
